### ISSUE TITLE
How do you add an already-opened tab to some container?

### ISSUE THREAD

**Issue by fujisan43** [mozilla/multi-account-containers#1001]
Right now, I have to open a tab from the container menu and then copy the link from the already-opened tab and paste it in the newly opened container tab.
We should be able to select a container from that already-opened tab.

**Comment by SoftVision-EmilPasca** [comment]
Hi @fujisan43, thanks for reporting this issue. However, this is a duplicate of https://github.com/mozilla/multi-account-containers/issues/311.
