### ISSUE TITLE
Lost many hidden tabs on browser restart thate were unloaded by "tab Suspender"

### ISSUE THREAD

**Issue by lelutin** [mozilla/multi-account-containers#1004]
Hello,

I've just lost many tabs when restarting the browser. I'm not sure that what's happening is the same as #417.

All the tabs that I've lost were the ones that had been unloaded/hibernated by the plugin tab Suspender before the restart happened, so I believe there might be a problem with interacting with this plugin's activity.

**Comment by falolaf** [comment]
saving/loading tabs for moz-extension urls, e.g. as done with tab suspender, has been disabled some time ago. I'm using my own version of the containers addon where I have enabled moz-extension urls again and it works as expected. I.e. suspended tabs are saved/restored.

**Comment by kendallcorner** [comment]
Hi. This looks like a duplicate of #831. Please vote (:+1:) or discuss on those issues so they are more likely to be completed. I'll close this, but feel free to reopen if you think it's a different issue.
