### ISSUE TITLE
Right arrow keyboard shortcut

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/multi-account-containers#1009]
When the browser popup menu for Containers is open, a specific Container is selected, and the right arrow to expose the submenu is visible for that Container, pressing the right arrow keyboard button should take you to the submenu.

**Comment by groovecoder** [comment]
I think @TanviHacks is away for a couple days ... I think you're welcome to work on this one. (Doesn't seem to be fixed on Mac in any case.)

**Comment by Paarmita** [comment]
@groovecoder I think @tie-rack has added a PR.

**Comment by groovecoder** [comment]
Ah thanks ... we haven't triaged the outstanding PRs yet. I'll try to do that a bit in the upcoming week or so.

**Comment by chujunlu** [comment]
Hi @groovecoder , I'm Chujun, an Outreachy 2019 applicant. I'm interested in working in privacy and security related projects so I'd like to contribute to this one. To be honest, I don't have experience in Extension Development, and I'm wondering is it possible to debug the extension with the browser debugger (image below) like I used to with web apps? If not, is there any way to debug the code base besides putting in `console.log` statements? Sorry if that's a dumb question. Thanks!
<img width="1224" alt="Screen Shot 2019-10-03 at 5 59 12 AM" src="https://user-images.githubusercontent.com/38041280/66129621-1bc87f80-e5a5-11e9-80e8-0b78aa7cfddc.png">

**Comment by olsenme** [comment]
I'm happy to take this issue on if it is still unresolved

**Comment by AlbionaHoti** [comment]
If the task will not be solved, I would like to proceed. I am an Outreachy applicant. @groovecoder

**Comment by yellowwoods12** [comment]
Hi @maxxcrawford and @groovecoder, I am Outreachy applicant and would like to work on this issue.

**Comment by dnahol** [comment]
Hi @maxxcrawford and @groovecoder. I am an Outreachy applicant as well. If no one is taking this, I'd like to.

**Comment by dnahol** [comment]
This was solved by #1524, right?

**Comment by maxxcrawford** [comment]
This has been added!
