### ISSUE TITLE
'Switch to tab' closes container tab

### ISSUE THREAD

**Issue by rubcap** [mozilla/multi-account-containers#1010]
_Steps to reproduce:_
1. Go to Add-on Manager and disable all add-ons except Multi-Account Containers.
2. Open random websites A (Duckduckgo.com), B (Mozilla.org), C (GitHub.com) in three normal tabs.
3. Open a Container tab D: new tab page is opened.
4. In Container tab D - set focus on address bar - enter "Duck": browser suggests switching to tab A based on the title of website A (this doesn't seem to work all the time; sometimes no suggestions are given even though there is a match with an other tab = separate issue?)
5. Click the address bar suggestion to switch to tab A.

_Expected result;_
Browser switches to tab A, leaves tab D (container tab) as it is

_Actual result:_
Browser switches to tab A, closes tab D (container tab)

**Comment by groovecoder** [comment]
This is the designed behavior for Firefox tabs.

**Comment by TanviHacks** [comment]
Seems like the right thing to do here is to disable "Switch to tab" functionality when you cross over the Container boundary.

**Comment by rubcap** [comment]
Hi groovecoder, how is this designed behavior? For Firefox or for Container tabs?
Cause I've never seen tabs being closed when switching to another tab.
I also don't see where the "switch to tab" functionality could interfere with Containers and hence should be disabled? Thank you for your response.
