### ISSUE TITLE
Ability to switch/relaunch the current tab in a new container

### ISSUE THREAD

**Issue by jefferai** [mozilla/multi-account-containers#1012]
This is related to #923 and #987 but I think is different.

It would be really useful is if I could re-launch the current tab in a different container. I often start browsing from the New Tab page, which can't be assigned to any particular container, but as a result end up in the Default container. If I end up following a link to Twitter, rather than having to copy the URL, open a tab in the Social container, and paste in the URL, it'd be nice to be able to use the right-click menu (or some shortcut) to tell firefox to relaunch the current URL in a different container.

I realize that you can pin certain sites to always open in specific containers but when you have multiple accounts on those sites this breaks down a bit. Either you need to do the copy/new tab/paste workflow to use the correct account in the correct container, or you need to know in advance to start your browsing session from one container or the other, which would then defeat some of the non-tracking purposes of containers.

**Comment by bernd-wechner** [comment]
Agreed. Just experimenting now and the one key missing feature is a way to move an existing tab into a given container. Quite clunky process to do by hand.

**Comment by falolaf** [comment]
Something like:
https://addons.mozilla.org/en-US/firefox/addon/switch-container/

**Comment by falolaf** [comment]
Are you looking for something like:
https://addons.mozilla.org/en-US/firefox/addon/switch-container/
Not on the tab though.

**Comment by bernd-wechner** [comment]
Spot on, though wondering why this has to be a separate add-on and isn't part of the basic functionality. It's got to be a pretty ordinary use case surely?

**Comment by jefferai** [comment]
Possibly that add-on addresses it; it details privacy implications of leaking tracking IDs in URLs across containers, which in a "dumb" copy and paste workflow into a new container tab will still exist anyways (but a "smart" user could modify the URL before pasting).

I think half of my problem would be addressed simply by having a way to say "create a new tab in the same container as the current one". It wouldn't be quite the same, but it'd still save a lot of clicks.

**Comment by falolaf** [comment]
If you would like to open a new tab in current container this addon might work for you:
https://addons.mozilla.org/sv-SE/firefox/addon/new-container-tab/
via keyboard shortcut.

**Comment by ruipacheco** [comment]
Those links should all be rolled into the containers add-on.

**Comment by jonathanKingston** [comment]
We have discussed this at length and we won't be doing this (at least in the short term): https://github.com/mozilla/multi-account-containers/wiki/Moving-between-containers

> https://addons.mozilla.org/sv-SE/firefox/addon/new-container-tab/

This actually is going to become a pref that you can control soon: https://bugzilla.mozilla.org/show_bug.cgi?id=1406371

Thanks, let me know if you have any questions.

**Comment by jefferai** [comment]
The pref looks like it will solve 95% of my complaint here. Thanks!
