### ISSUE TITLE
New Tab Buttons for Containers

### ISSUE THREAD

**Issue by Willamin** [mozilla/multi-account-containers#1014]
A great addition for this extension would be new tab buttons alongside the default button. I've attached a quick-and-dirty mockup of how I envision this. 

![extra-buttons](https://user-images.githubusercontent.com/7304492/33449568-2979dfb4-d5d7-11e7-8257-eab3395bc609.png)

**Comment by ArchangeGabriel** [comment]
This is cluttering the UI, especially if you have a lot of containers. What’s wrong with the long press? Excepted that it lacks discoverability.

**Comment by Willamin** [comment]
> This is cluttering the UI, especially if you have a lot of containers
Excellent point - I didn't think about what would happen if someone had many containers.

> What’s wrong with the long press? 
As a user, UI delays are annoying (when they only exist because of UI design). Honestly, for many workflows, the long press works great for opening specific containers. I've found that I typically close tabs when I'm finished with them. When I'm performing tasks that require multiple tabs open at the same time, I find myself long pressing the new tab button often enough that the long press feels like it's slowing me down.

I think many users will have only a handful of containers that they use often. It would be nice to have the ability to add container specific new tab buttons via the customize interface.

**Comment by ArchangeGabriel** [comment]
OK. Drag&Drop colored new tab icon for selected containers seems nice: this way, you can add only the most relevant one there, and the rest of them are still under the long press.

**Comment by groovecoder** [comment]
This is a cool idea, but not possible from the platform & Firefox UI.

**Comment by TanviHacks** [comment]
A separate addon could build something like this, but the platform will restrict you to only adding 1 extra icon (1 extra plus button, but not multiple).

**Comment by Willamin** [comment]
@groovecoder What makes this not possible?

**Comment by groovecoder** [comment]
@jonathanKingston can explain better. There's currently only a way to add 1 additional item to the tab bar UI. To add more, we will need the feature in mozilla-central, and Firefox UI team wouldn't approve adding more clutter to the tab bar UI.
