### ISSUE TITLE
Feature Request: "Always open in" configurable domain level

### ISSUE THREAD

**Issue by pauschuu** [mozilla/multi-account-containers#1017]
Right now it seems that the full domain is considered for matching "Always open in". I want to be able to set it to TLD only, for example.

Because sites like google.com, they have tons of subdomains, and I want my whole google world in its own container but I don't want to click "always open in" for every single google subdomain I use again and again.

**Comment by stoically** [comment]
The [Containerise Add-on](https://addons.mozilla.org/en-US/firefox/addon/containerise/) lets you specify Domain and automatically includes Subdomains.

**Comment by groovecoder** [comment]
Duplicate of https://github.com/mozilla/multi-account-containers/issues/473.
