### ISSUE TITLE
"Open Link in New Container Tab" submenu active but empty when there are no containers

### ISSUE THREAD

**Issue by anewuser** [mozilla/multi-account-containers#1019]
- Go to about:preferences#containers and delete all containers
- Open example.org
- Right-click on the link

Actual results:

"Open Link in New Container Tab" is visible and not greyed-out, even though it has no purpose with no sub-entries.

Expected results:

When there are currently no containers, the ""Open Link in New Container Tab" entry in the link context menu should be hidden or greyed-out, or it should offer the option to create a new container, or show a link to "Manage containers" (about:preferences#containers).

Firefox 57.0.1
Windows 10

**Comment by groovecoder** [comment]
This is a platform-level bug, so closing this GitHub issue. Please file a bugzilla bug for it.

**Comment by anewuser** [comment]
@groovecoder It was posted on Bugzilla before, and someone closed it and said that this was the proper place.

https://bugzilla.mozilla.org/show_bug.cgi?id=1417238

**Comment by groovecoder** [comment]
Hmm ... sorry about that. I re-opened it for you.
