### ISSUE TITLE
Help Wanted - How do I delete Containers?

### ISSUE THREAD

**Issue by lburg801** [mozilla/multi-account-containers#1026]
I made a mistake with labeling some containers and since there was no way to delete that tab from belonging to that container, I removed Container  from my add-ons yesterday. Today, I have just discovered that while the icon is gone, the containers are still active. I need to delete them. Can you help? Thanks

**Comment by stoically** [comment]
You could install/enable the Add-on again and remove the Container using the Multi-Account Containers Icon > Edit Containers. Btw, if you mean with "tab belonging to a container" that a specific website always opens in a container, you could browse to that website, click the Icon and remove the tick from the "Always open in $Container" checkbox. Hope that helps.

**Comment by lburg801** [comment]
Hi and thanks for your help. That worked although it also closed the open
tabs belonging to the container. I hope they will make this add-on easier
to use with a right click menu. Before I uninstalled it I did try to get
the "always ..." option to show without luck. I probably did not do it in
the order you describe. Thanks again for your help.
