### ISSUE TITLE
Focus name field on opening New Container sub-panel

### ISSUE THREAD

**Issue by yozlet** [mozilla/multi-account-containers#1028]
In the sub-panel that appears on hitting the "+" (Create New Container) button: 
 * The `Name` field should be automatically focused
 * The default `Container #xx` text in that field should be selected so that typing removes it. (Alternative solution: Have no default text. I don't know why anyone would use the `Container #xx` scheme when naming containers, but maybe there's a reason for it?)

This is a continual "missing stair" issue for me: every time I create a new container, I start typing because I expect that field to be focused. I'm assuming that I'm not the only person this happens to.

**Comment by tiagonbotelho** [comment]
Hey!

Adding `autofocus` to https://github.com/mozilla/multi-account-containers/blob/master/src/popup.html#L178 did not seem to work.

I presume it is not supported in `popup.html`? I tried finding an explanation for why it was not working but could not find one unfortunately.

Tried adding `document.querySelector("#edit-container-panel-name-input").focus()` to the `prepare` function of `P_CONTAINER_EDIT` (near https://github.com/mozilla/multi-account-containers/blob/master/src/js/popup.js#L1001) but it did not work as well.

Also tried using the same code on the Browser console to see if it focused but was not able to get the `input` to focus.

I've noticed that we are using the `focus()` method [here](https://github.com/mozilla/multi-account-containers/blob/master/src/js/popup.js#L510) I can't seem to find the reason why it works there and not in the place I linked above.

**Comment by yozlet** [comment]
@groovecoder Further to my issue description: why is `Container #xx` the default value for the `Name` field?

**Comment by groovecoder** [comment]
@yozlet - there's no strong opinion or reason to have `Container #XX` as the default value.

**Comment by tiagonbotelho** [comment]
@groovecoder is there something I am missing as to why I am unable to gave `focus()` working on the `<input>` for the container name? I posted my findings in the comment above 😄 I've been trying to make this work for a while now

**Comment by yozlet** [comment]
@tiagonbotelho Thank you for working on this and sticking with it!

**Comment by tiagonbotelho** [comment]
@groovecoder can you help me a hand please? I really wanted to ship a PR for this 😄

**Comment by groovecoder** [comment]
Yes go ahead and make a PR if you like. I'm not sure I can review it this week but I'll try.

**Comment by ShivangiKakkar** [comment]
@groovecoder No problem :) Thanks!
