### ISSUE TITLE
Right aligned container button dropdown UI gets squeezed

### ISSUE THREAD

**Issue by tilgovi** [mozilla/multi-account-containers#1033]
I can put the containers button on my tab bar and remove the normal "new tab" button from it. This customization results in a setup that's familiar for muscle memory and very clear.

In OS X fullscreen mode, this results in the button being placed at the very far right of the screen. The dropdown seems to nudge itself leftward to avoid being off the screen, but the new container button seems squeezed as a result.

<img width="295" alt="screen shot 2017-12-05 at 10 48 25" src="https://user-images.githubusercontent.com/20818/33625077-4d5440f0-d9ab-11e7-89ea-37aa78640b3a.png">

**Comment by Soundharyaam** [comment]
Hi, Can I work on this bug?

**Comment by Soundharyaam** [comment]
Thanks!

**Comment by tilgovi** [comment]
I still see this behavior, but only when adding the button to my tab bar, in place of the default new tab button.

**Comment by tilgovi** [comment]
In this location:

<img width="240" alt="screen shot 2018-09-20 at 11 30 52" src="https://user-images.githubusercontent.com/20818/45839256-b327a100-bcc8-11e8-94ec-e3ae00e89735.png">

**Comment by Soundharyaam** [comment]
Yeah. I kinda got your point and trying to reproduce the bug. From the "Multi Account Containers" button, I clicked the "+" of the respective items such as "Personal, work, banking", etc. This in turn created this ">" button and also opened the new tab.

I am seeing something like this:
<img width="359" alt="screen shot 2018-09-21 at 12 25 23 am" src="https://user-images.githubusercontent.com/24657693/45840611-0a635b00-bd35-11e8-9c9a-3e4019205295.png">

What is the next step which I should do to reproduce this bug?
If I am missing something, please let me know. 
Thanks!

**Comment by tilgovi** [comment]
I see the same as you with the button in the same location.

What you are missing is that the problem appears when the button is in the _tab bar_, not the toolbar with the location field.

Use the UI customization to move the containers button up and to the right, into the tab bar. See my screenshot. The button is _above_ the `☰`.

**Comment by Soundharyaam** [comment]
@tilgovi Thank you. I did UI customization to place the containers button on my tab bar and also removed the normal "new tab" button from it. Now, I am seeing something like this:


<img width="369" alt="screen shot 2018-09-21 at 11 37 21 am" src="https://user-images.githubusercontent.com/24657693/45863274-08c88000-bd93-11e8-9c07-0f3a9994243a.png">

**Comment by tilgovi** [comment]
Very strange. Perhaps it only happens in full screen? I'll check tomorrow.

Thanks for looking into it. It's a small thing, I know.

**Comment by yatri1609** [comment]
@tilgovi You are right it is there Even I faced the same UI problem.
![screenshot from 2018-09-23 16-09-09](https://user-images.githubusercontent.com/34381723/45927068-32c4a280-bf4b-11e8-8755-f6ab1a8469bb.png)

**Comment by yatri1609** [comment]
So @groovecoder Can I take this up as my first issue under Outreachy contribution?

**Comment by ShivangiKakkar** [comment]
@tilgovi Yes this issue still exists. And, yeah it reproduces only for full screen.
@yatri1609 @Paarmita @Soundharyaam Maybe you weren't full screen or this reproduces only for MacOS. :)

<img width="1440" alt="screen shot 2018-09-28 at 12 42 45 am" src="https://user-images.githubusercontent.com/35342019/46169096-d0a3ce80-c2b7-11e8-88d8-98fe5c508792.png">

**Comment by tilgovi** [comment]
Thanks for looking, you all! It's really not a large issue and it's not the default placement, but I think it's nice to imagine this experience being so polished that it could replace the default ➕ for new tabs!

**Comment by yatri1609** [comment]
@ShivangiKakkar It did produce for me as I mentioned earlier, have a look at my comment above.

**Comment by ShivangiKakkar** [comment]
@yatri1609 The ➕(add a new container) button didn't seem to be squeezed. [here](https://github.com/mozilla/multi-account-containers/issues/1033#issuecomment-423807191) If it did reproduce for you then I'd assume it's present for linux too.

**Comment by yatri1609** [comment]
@ShivangiKakkar exactly

**Comment by Aishat-Akinyemi** [comment]
Hello @groovecoder  @maxxcrawford I am an Outreachy 2019 applicant, may I work on this as my first contribution? Thank you.

**Comment by groovecoder** [comment]
@Aishat-Akinyemi I'm going to leave this un-assigned while you're working on #973 .

**Comment by silvererudite** [comment]
hey @groovecoder May I take a shot at this?

**Comment by groovecoder** [comment]
Yup, I'll assign to myself to hold it for you. Let me know if you work on something else so I can un-assign it if needed.

**Comment by silvererudite** [comment]
@groovecoder apparently i cannot seem to reproduce the issue in windows(local machine on which I'm working in).  No matter where I place the icon, it seems to work fine at least for Windows.

**Comment by silvererudite** [comment]
@groovecoder you can unassign this as I have nothing to do here really and I'm working on another issue

thanks

**Comment by osumgbachiamaka** [comment]
@groovecoder can i take this task

**Comment by maxxcrawford** [comment]
@osumgbachiamaka Absolutely. Good luck!

**Comment by osumgbachiamaka** [comment]
working on it

**Comment by osumgbachiamaka** [comment]
I have this as it looks [here](https://github.com/mozilla/multi-account-containers/issues/1033#issuecomment-423807191). Can you please assign me to nanother task for now. 

If this issue can not be reproduced on linux, please unassign me so i can move over to another task.

**Comment by oksmelnik** [comment]
Was able to reproduce this bug, would like to work on it. I'm an outreachy applicant

**Comment by maxxcrawford** [comment]
@osumgbachiamaka Understood. Please tag me or @groovecoder in another issue. 

@oksmelnik I'm assigning this to you. Thanks!

**Comment by oksmelnik** [comment]
working on it

**Comment by oksmelnik** [comment]
From what I can see, right side of this popup is actually off the screen. As a solution, I could move buttons to the left a bit, but not sure it's the right approach for such an edge case. What do you think, @tilgovi @groovecoder? 

<img width="326" alt="Screenshot 2019-10-11 at 09 12 47" src="https://user-images.githubusercontent.com/3542544/66631918-94fc4e00-ec07-11e9-86eb-74d822c848ce.png">
<img width="346" alt="Screenshot 2019-10-11 at 09 12 18" src="https://user-images.githubusercontent.com/3542544/66631924-975ea800-ec07-11e9-8387-68ee6f7d2b69.png">

**Comment by tilgovi** [comment]
It might be fine not to fix it. I just noticed it and filed it when I saw it, but it's only cosmetic.

It also might be a problem with how popups are placed. The arrow that connects the popup to the button moves to the left, which makes me think that some code, perhaps in Firefox itself, is trying to move the popup so that it's not off screen, but not moving it far enough. Maybe setting a fixed width for the popup, if it doesn't have one already, would help. Otherwise, I suspect the problem is not in the add-on, but in Firefox's placement of popups.

**Comment by oksmelnik** [comment]
Yes, seems like all the popups are being places this way. And the border around the new container button makes the overlap more visible. 

The width of the popup is fixed with inline-size property, I've experimented a bit, but ran out of ideas of what else could be done here. 

<img width="384" alt="Screenshot 2019-10-12 at 17 08 53" src="https://user-images.githubusercontent.com/3542544/66703677-5f458b00-ed15-11e9-9b51-f397f23476d9.png">
<img width="413" alt="Screenshot 2019-10-12 at 17 10 39" src="https://user-images.githubusercontent.com/3542544/66703679-61a7e500-ed15-11e9-861a-1b7669932db2.png">

**Comment by tilgovi** [comment]
It seems like there's nothing to be done here. I'll close the issue. Thanks, everyone, for looking into it!
