### ISSUE TITLE
Add description for keyboard shortcuts in mozilla add-on page.

### ISSUE THREAD

**Issue by hiteshpaul** [mozilla/multi-account-containers#1038]
It is difficult for new users to find the keyboard shortcut to focus on container toolbar menu, i.e `Ctrl + .` It's a request to add a brief description and details about the keyboard mappings in the [description page](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)

**Comment by trevorwelch** [comment]
Good call! This issue was the only way I was able to find this shortcut 👍

**Comment by jonathanKingston** [comment]
I added a section at the bottom explaining this. Someone will likely come along and make it sound better. Thanks for suggesting this.
