### ISSUE TITLE
Add-on not happening in general

### ISSUE THREAD

**Issue by bvhme** [mozilla/multi-account-containers#1039]
I've recently switched to Firefox and it was amazing, I am in love with the multi-account-containers and was using them in combo with the Tree-style-tabs. Sadly, when the add-on is enabled absolutely nothing happens. As in, when I enable the plugin, nothing at all changes, I don't get the toolbar item or the option in the Tree-style-tabs to open a new tab in a container.

Where can I get started on debugging this issue? My [`about:support is on Gists`](https://gist.github.com/bvhme/06a55f435b57a5a9b47c909a973c5a81).

Thanks!!!

**Comment by SoftVision-EmilPasca** [comment]
Hi @bvhme, thanks for reporting this issue. Can you please provide more information, as the Operating system, Firefox version and also the add-ons that you may have installed?

**Comment by bvhme** [comment]
Yes! The following is from the `about:support`

```javascript
  "application": {
    "name": "Firefox",
    "osVersion": "Darwin 17.2.0", // maxOS 10.13.1 (17B1003)
    "version": "58.0b9",
    "buildID": "20171204150510",
```

And Tree Style Tab is the only extension I have enabled right now:

```javascript
  "extensions": [
    {
      "name": "Multi-Account Containers",
      "version": "4.1.0",
      "isActive": true,
      "id": "@testpilot-containers"
    },
    {
      "name": "Tree Style Tab",
      "version": "2.3.0",
      "isActive": true,
      "id": "treestyletab@piro.sakura.ne.jp"
    },
    {
      "name": "DuckDuckGo Plus",
      "version": "2017.11.30",
      "isActive": false,
      "id": "jid1-ZAdIEUB7XOzOJw@jetpack"
    },
    {
      "name": "Grammarly for Firefox",
      "version": "8.803.1337",
      "isActive": false,
      "id": "87677a2c52b84ad3a151a4a72f5bd3c4@jetpack"
    },
    {
      "name": "Todoist: To-Do list and Task Manager",
      "version": "5.3",
      "isActive": false,
      "id": "support@todoist.com"
    },
    {
      "name": "uBlock Origin",
      "version": "1.14.20",
      "isActive": false,
      "id": "uBlock0@raymondhill.net"
    },
    {
      "name": "ZenHub for GitHub",
      "version": "2.35.68",
      "isActive": false,
      "id": "zenhub@zenhub.io"
    }
    ],
```

**Comment by SoftVision-EmilPasca** [comment]
@bvhme, thanks for the quick reply.  Could you also confirm that in `about:config`, the below preferences are set as:
privacy.userContext.enabled - true
privacy.userContext.longPressBehavior - 2
privacy.userContext.ui.enabled - true
privacy.usercontext.about_newtab_segregation.enabled - true

**Comment by bvhme** [comment]
It seems so:

```javascript
"privacy.userContext.ui.enabled": true,
"privacy.usercontext.about_newtab_segregation.enabled": true,
"privacy.userContext.enabled": true,
"privacy.userContext.extension": "@testpilot-containers",
"privacy.userContext.longPressBehavior": 2,
```

**Comment by bvhme** [comment]
I have new information!

I found out that I can still open container tabs from the 'File' menu, and they work, including the visual indicator of what container they are!

**Comment by SoftVision-PaulOiegas** [comment]
Hey @bvhme , sry for the late reply but Emil had some urgent things to do on Friday and he wasn't able to reply. From what I see, the "Tree Style Tab" add-on has no support for the "Multi Account Containers" add-on. You can see the opened containers in it with a distinct color, but that's all. 
Probably if you want any support in it, you will have to log an enhancement on [their GitHub repository](https://github.com/piroor/treestyletab/issues).

However, you can still open containers by doing long press (click) on the new tab "+" button on the horizontal tab strip of the browser.

Also, if you are not insisting on keeping Tree Style Tabs, there is an alternate add-on that moves tabs on the side, but you won't have them grouped by the domain from which they come from. It's called "Tab Center Redux" and you can find it [here](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/).

**Comment by groovecoder** [comment]
Closing from our repo as this is 3rd-party add-on incompatibility. Please file issues in the Tree Style Tab repo.
