### ISSUE TITLE
[Feature request] Open previously hidden tabs in the background

### ISSUE THREAD

**Issue by DennisGaida** [mozilla/multi-account-containers#1041]
When I open all tabs from a hidden container ("Show this container") all of the tabs are opened in the foreground. All tabs contents are loaded instead of loaded when I select them.

I would prefer if only the first selected tab is loaded and all the others are loaded in the background - i.e. not loaded. When I open a hidden container with e.g. 40 tabs  (previously hidden) Firefox gets really sluggish and even unresponsive.  
This behavior is even "worse" when I open a new tab which is automatically loaded in a specific currently hidden container (say Amazon for the shopping container). Next to this new tab I just started loading all of the hidden tabs - maybe this is the desired behavior, but I would like to be able to either not load them or load them in the background.

Maybe the new [`discard()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/discard) feature maybe be leveraged to achieve this behavior?

**Comment by groovecoder** [comment]
It may be possible to re-open the hidden tabs with `active:false`. Marking as a good first bug/enhancement.

**Comment by hritvi** [comment]
May I work on this issue @groovecoder?

**Comment by groovecoder** [comment]
Yup, sure thing.

**Comment by falolaf** [comment]
For the case to not load tabs in a hidden container when a new tab in said container is opened you can have a look at this PR:
https://github.com/mozilla/multi-account-containers/pull/1119

**Comment by nidhi-nigam** [comment]
@groovecoder  Can I take up this issue if it is available?

**Comment by groovecoder** [comment]
I think @hritvi is already working on this?

**Comment by nidhi-nigam** [comment]
@groovecoder Is there any other good first issue available?

**Comment by groovecoder** [comment]
Check out these others? https://github.com/mozilla/multi-account-containers/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22

**Comment by Cmapnep** [comment]
UP

**Comment by revealtheweb** [comment]
Hi @groovecoder, I'm an applicant from Outreachy, and I would like to work on this feature with your guide. Please I would appreciate all relevant information to begin work on this.
Thanks.

**Comment by groovecoder** [comment]
Assigning to myself for @revealtheweb. Let me know if you decide to work on something else and I'll un-assigne this.

**Comment by Karskaya** [comment]
Hi @groovecoder and @revealtheweb! I'm Outreachy applicant as well and will be glad to work with this ticket if @revealtheweb will decide to move on with something else.

**Comment by revealtheweb** [comment]
hi @groovecoder . Thanks. I'll take on the issue. Will update as I progress

**Comment by Karskaya** [comment]
Hello @groovecoder ! If it's unassigned for some reasons, I'm still here looking for a ticket.

**Comment by maxxcrawford** [comment]
@revealtheweb How's this going? Wanted to check in on your progress. Thanks!

**Comment by maxxcrawford** [comment]
@revealtheweb Realized you're already on #198. I'm going to unassign this issue and reassign it to @Karskaya. If you already have a PR, feel free to submit it for this issue. 

@Karskaya Go for it!

**Comment by Karskaya** [comment]
@maxxcrawford oh, I've just saw the answer. Start working, thank you!

**Comment by Karskaya** [comment]
@maxxcrawford Made PR three days ago. Could you please review? Or should I ask @groovecoder for this?
