### ISSUE TITLE
[Feature request] Don't reload all tabs from hidden container, if new tab created

### ISSUE THREAD

**Issue by moontear** [mozilla/multi-account-containers#1042]
Consider a hidden container with 30 tabs (e.g. "Shopping"). Creating a new tab e.g. for Amazon (which is automatically set to "Shopping") this opens all currently hidden tabs, cluttering everything. And slowing down Firefox.

It would be great if not all tabs were repopulated upon adding a new tab that belongs to that group. I suppose that would make the option to hide/unhide single tabs per container necessary. This would allow for all tabs in a container to remain hidden, the new tab could be the only one visible.

**Comment by falolaf** [comment]
Well, this was made intentionally some time back. You could try my fork of this addon:
https://github.com/falolaf/multi-account-containers/tree/my_fixes_on_4_1_0

Load it through about:support. Use any file in the webextension directory.

(This version also allows you to use Tab suspender addon together with containers addon.)

**Comment by moontear** [comment]
Thanks for your fork, I'll look into it. I'll leave this request standing though as I really do believe it would be good to be able to hide single tabs besides hiding all tabs of a container.

**Comment by falolaf** [comment]
Yes, that would be a good thing I believe. Not part of my fork though. I don't have much time to invest in addon development. Not much knowledge either so far.

**Comment by groovecoder** [comment]
We have no plans to design half-hidden Container states. This may be a good feature for a separate add-on.
