### ISSUE TITLE
Containerizing domains can break extensions

### ISSUE THREAD

**Issue by aproposnix** [mozilla/multi-account-containers#1043]
Sorry, couldn't think of a more clear title.  I use Evernote webclipper.  As of version 6.9.3 they have switched to a different login method using Google oauth. Since I have both domains (evernote and Google) in their own containers I was completely unable to login (I would see a blank login window which would disappear after a second or two). 

Though my experience is coming from the Evernote webclipper, this could happen to any extension when the user has multiple domains containerized. 

The workaround was to temporarily disable containers, login to Evernote (using the oauth method) and then re-enable after logging in. 

I get the fact that containers are working as designed but is there any way to improve the user experience so issues like this don't happen or to just inform the user of potential conflicts?

**Comment by TanviHacks** [comment]
If you login to evernote via google oauth in your default container, does the Evernote webclipper extension work?

**Comment by groovecoder** [comment]
We have no plans to allow sites to share/cross Container boundaries. I have worked around this by effectively signing into Google in my other Containers where I use apps that require Google auth.
