### ISSUE TITLE
container should change seamlessly

### ISSUE THREAD

**Issue by alekksander** [mozilla/multi-account-containers#1045]
the transition isn't quite good looking one ;)

**Comment by SoftVision-PaulOiegas** [comment]
Hi @alekksander and thanks for your report. Can you please share some more details like a screen recording so we can see the exact issue you are referring to? I'm not really sure at which transition you are referring to.

**Comment by alekksander** [comment]
let's say i open examplewebaddress.com assigned to container „banking” — opened tab is closing, and new, „banking” tab is opened. this closing and opening is not only bad looking and distracting, but also steals focus if i'm already at different tab, or opening examplewebaddress.com from different container (or no container). so in my understanding ideally focus shouldn't be stole, and address should be assigned without closing and opening new tab, just the color change, and rest goes in background.

**Comment by SoftVision-PaulOiegas** [comment]
Thanks for the details. Let's see what @groovecoder and @jonathanKingston think about this possible issue.

**Comment by groovecoder** [comment]
This requires an upstream enhancement in mozilla-central. Please see: https://bugzilla.mozilla.org/show_bug.cgi?id=1323873
