### ISSUE TITLE
[Feature request] "New tab" hotkey should open tab in current container

### ISSUE THREAD

**Issue by ericlathrop** [mozilla/multi-account-containers#1046]
When I've got a tab for my Work container open, I want to open new tabs in the same container with a simple keyboard shortcut (The normal ctrl+t). Currently they always open in the default container, and there's no hotkeys I can find to open a tab for a particular container.

**Comment by ericlathrop** [comment]
Hopefully this behavior would work with other extensions. I use [Vimium](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/) to open new tabs with the "t" key, and would like this to function the same way.

**Comment by anewuser** [comment]
Please close this and follow https://github.com/mozilla/multi-account-containers/issues/462
