### ISSUE TITLE
Awkward wording when deleting a container

### ISSUE THREAD

**Issue by hwine** [mozilla/multi-account-containers#1051]
The current wording suggests (to me at least) that _all_ of my container tabs will be closed. The behavior is "any open tab for the container to be deleted will be closed".

Suggestion (IANAET*): "If you remove this container now, this container's tabs will be closed"

![screen shot 2017-12-19 at 11 47 50](https://user-images.githubusercontent.com/132412/34175961-1e0f87b0-e4b3-11e7-98f7-78061568aed4.png)

* I Am Not An English Teacher

**Comment by ericlathrop** [comment]
From the HTML, it looks like there's supposed to be a number for the amount of tabs that will be closed:
https://github.com/ericlathrop/multi-account-containers/blob/bea201a389ae2151d7ef187c0d217e053d3acec9/src/popup.html#L207

e.g. "If you remove this container now, 3 container tabs will be closed."

It doesn't look like the number is implemented in the code. Should the number be implemented, or should the wording be changed?

**Comment by Sylvia23** [comment]
Hi there, I am an outreachy aspirant for Round 17. I would like to take up this issue if it's free to work upon. This might help me get started with the project and set up the development environment. Any advice on where and how to get started with the implementation is also most welcome. Thanks!

**Comment by yatri1609** [comment]
@groovecoder Can I take this issue ? I think this will help me get started with this project.

**Comment by groovecoder** [comment]
@Sylvia23 if you'd like to take a look at this first that sounds good. Note that https://github.com/mozilla/multi-account-containers/pull/1205 is open for this, but it may have some issues? I haven't looked at it recently.

@yatri1609 if @Sylvia23 decides not to start on this, you can take it.

**Comment by yatri1609** [comment]
@groovecoder Sure! If not this then can you assign me some other issue ? So that I can start working on this project.

**Comment by yatri1609** [comment]
@groovecoder Can I take up this issue?

**Comment by groovecoder** [comment]
@yatri1609 sure. you might check out the old https://github.com/mozilla/multi-account-containers/pull/1205 PR to see if that can be re-purposed/re-used?

**Comment by yatri1609** [comment]
> @yatri1609 sure. you might check out the old #1205 PR to see if that can be re-purposed/re-used?

Sure @groovecoder

**Comment by mingchia-andy-liu** [comment]
Hello, @Sylvia23 @yatri1609, I had a PR up for this issue back on April. I didn't know how the assignment works. I should have asked to be assigned on this issue instead of working on it head straight. If anything, I would still like to merge my PR in once the test is fixed (the original failing is resolved but there is a new one). But if there is a passing PR ready to be merged, I will just close mine.

Hello @groovecoder, is it possible to assign the issue to me? I would like to finish this PR.

**Comment by viicktur** [comment]
Hello, has this issue been fixed? Being looking arround for some first comer issue to tackle any suggestion please guys

**Comment by viicktur** [comment]
Hello @hwine , as per your former discovery on the wording when deleting a container, i recently experiemnted om it and discovered that it now display a wording of deleting all the tabs made a specific container.

Would you still want the wording to specifically say "this container tab will be deleted" as against saying "all the individual <number> of tab associated with that tab should be deleted", if so i woukd like to be assigned to it so i can open a PR



![image](https://user-images.githubusercontent.com/47690561/66020162-86d47080-e529-11e9-8985-338f8622886e.png)

**Comment by hwine** [comment]
@viicktur - I am not a project member, just the bug reporter.

That said, it does look like 66a9116524620e97d0879fafe8c78b8f0807738a was intended to fix this, but GitHub didn't pick it up automatically, so closing manually.
