### ISSUE TITLE
[Feature Request] From bookmarks toolbar, have an "open in container" menu option

### ISSUE THREAD

**Issue by Conan1989** [mozilla/multi-account-containers#1056]
Hi,
Currently, when right clicking a link in a page, there's a menu item "Open Link in new Container Tab"
Request this to be extended to bookmarks in the bookmarks toolbar

**Comment by UsernameIsAlreadyTaken12345** [comment]
And please also for a bookmark folder.

**Comment by groovecoder** [comment]
This is a platform-level bug on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1401488
