### ISSUE TITLE
Way to manually edit URLS opened in/assigned to containers without opening up tabs?

### ISSUE THREAD

**Issue by somoso** [mozilla/multi-account-containers#1057]
I was wondering if there will be a UI for manually assigning URLS to containers without having to go through the whole hassle of opening a tab and then assigning the URL to the container via the extension?

What I'm personally thinking in mind is a textbox/table for each container that has the URLs (if textbox, then separated by enter key or comma or w/e separator) that will always open in that container. 

If it was a table, then I was thinking we could have an additional checkbox next to the URL that would be "always open in this container". This table layout could mean that we select a URL and then click a button to clear cookies & all associated data. Finally, it could highlight rows red if there are duplicate URLS in different containers and they are both selected as "always will open in container" which will go away once the user deselects all other checkboxes except the one they want the URL to open in.

**Comment by ArchangeGabriel** [comment]
Dupe of #719.

**Comment by somoso** [comment]
Cool, will close ticket.
