### ISSUE TITLE
opening a new tab from a link switches to said tab *if* that tab is in another container

### ISSUE THREAD

**Issue by aktau** [mozilla/multi-account-containers#1061]
I see this often when I click links from my Search container to my Work container (e.g.: github). Whenever I click a Github link (command+click, I'm on macOS) to open a new tab in the background, I see it first load the tab in the Search container, then realize this link is supposed to be opened in the Work container, and then my view invariably switches to that tab, which I wanted to be opened in the background.

**Comment by ArchangeGabriel** [comment]
Dupe of #442, which is fixed but not released (widely?).

**Comment by aktau** [comment]
Great. Sorry for the fuss, I had only searched for open issues.
