### ISSUE TITLE
Account container cookies not manageable for other add-ons

### ISSUE THREAD

**Issue by jrie** [mozilla/multi-account-containers#1062]
Hello,

I wrote a cookie management add-on, fairly new, which allows to manage (flag to delete explicity, auto-flag (for a domain) and "global" for all navigated domains, and auto-delete or keep cookies on page actions based on this rules, for sub- and base domains separately, while the user is browsing in certain "modes".

The add-on "Flag cookies" can be found here on github @ https://github.com/jrie/flagCookies - before I repeat what the add-on does in detail, there are also screenshots, which might clear up some things.

I would like to make it compatible with Multi-account-containers, hence, allow the users to automatically delete or permit cookies, based on there settings, like in the regular cookie storage for a domain.

But Multi-account, from what I understand, does "copy" or shadow the domain cookies in a exclusive storage, in storage.local, this restricts to handle cookies of those tabs through other add-ons, not only mine.

I gladly would like to provide the add-on compatible, but the way cookies are stored, isolate them. Hence, I cannot "protect" against tracking, when Multi-account-containers is used, since I cant see the cookies anymore for the domain.

Is there any way of keeping cookies manageable for other add ons in container tabs?

Feedback would be much appreciated!

**Comment by falolaf** [comment]
How does Cookie AutoDelete handle this:
https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/

**Comment by jrie** [comment]
Ah, thats interesting, I wasnt aware that its possible to make use of the cookieStoreId using Identities and retrieval using the store id.

That's actually a good hint. 👍 

So it was about me not retrieving the correct storage id of Multi-Account-Containers cookieStore.

**Comment by groovecoder** [comment]
Sounds like `storeId` from `browser.cookies` API solved this for you. Closing.
