### ISSUE TITLE
Multi-Account-Containers 4.1.0 ( Linux Mint 8.3) FireFox 57.0.3

### ISSUE THREAD

**Issue by jfbourdeau** [mozilla/multi-account-containers#1063]
Steps to reproduce:

After adding the cool Multi-Account-Containers on my FireFox 57.0.3 on Linux  mint 18.3
I started using this new add on, open several Tabs and after while pages won't load... 

Actual results:

SO after 15 to 30 minutes something less, I can't load WebPages anymore... I restart FIreFox and problem dissapear " for a while ".

My friend  on his MAC, do not have this problem with this great Addon

**Comment by SoftVision-EmilPasca** [comment]
Hi @jfbourdeau, thanks for reporting this issue. In order to investigate this further can you please list all the addons that you have installed on your profile or the information from `about:support` page?

**Comment by dannycolin** [comment]
Closing this issue since both MAC 4.1.0 and Firefox 57 have reached end of life a long time ago. If you still experience this issue, please file a new bug report.
