### ISSUE TITLE
Security issue: Visited links leak

### ISSUE THREAD

**Issue by StealthBlackOxide** [mozilla/multi-account-containers#1068]
The Addon which is integrated in FF57 leaks all visited links if the Firefox setting "layout.css.visited_links_enabled" is set to true (it is set to true when doing a fresh install or if not manually set to false on an existing installation).

How to reproduce:

Container 1: 
1) Visit website xyz which uses CSS visited link function (example: https://www.heise.de/newsticker/).
2) Click on a link.

Container 2:
1) Visit the same website xyz from Container 1 in Container 2.
2) Without clicking anything the same link from Container 1 is marked as visited in Container 2.

**Comment by SoftVision-EmilPasca** [comment]
I can confirm that the issue is reproducible on Windows 10 x64, Ubuntu 14.04 x64 and Mac OS X 10.12 with latest Firefox Release(57.0.4) and the latest Nightly (59.0a1-20180107220443) following the described STR.

**Comment by groovecoder** [comment]
I believe the underlying issue here is that History is not separated by Containers. There's a bugzilla bug for this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1283320

But, This add-on is not designed to solve this, so I'm closing this add-on issue.
