### ISSUE TITLE
Inconsistent "Firefox" in Multi-Account Containers' UI is redundant

### ISSUE THREAD

**Issue by n1trux** [mozilla/multi-account-containers#1070]
I get that the extension is named "Firefox Multi-Account Containers" but shouldn't it be simply "Multi-Account Containers" in the UI?

For example, the toolbar entry already is only "Multi-Account Containers" but in the context menu on sites it's "_Firefox_ Multi-Account Containers". Please remove the redundant "Firefox".

**Comment by grahamperrin** [comment]
> toolbar entry already is only "Multi-Account Containers"

Exactly. 

#763

From <https://github.com/mozilla/multi-account-containers/issues/850#issuecomment-331674800>:

> … Firefox Multi-Account Containers is the name we use on addons.mozilla.org and that name is so people searching can find it more. …

It's now more than _recommended_, it's By Firefox https://addons.mozilla.org/en-GB/firefox/search/?promoted=line&q=Containers&type=extension

Seeking _Containers_ finds the extension uppermost amongst search results: 

![image](https://user-images.githubusercontent.com/192271/116685994-1adb1800-a9ab-11eb-8a19-8871d3877d2d.png)

– with the **Firefox** icon alongside.
