### ISSUE TITLE
[Feature Request] Add hotkeys for opening diffrent types of tabs.

### ISSUE THREAD

**Issue by ThisUserIsEpic2** [mozilla/multi-account-containers#1071]
Enable the user to set hotkeys to open diffrent tabs, eg:
Ctrl + Shift + W for a work tab
Ctrl + Shift + P for a personal tab
This would make it easier to manage how your tabs open.

**Comment by rahulshw** [comment]
Yes, this is an extremely needed feature.

**Comment by groovecoder** [comment]
We released 5.0.1 yesterday which includes more keyboard shortcuts to open container tabs. Please check https://github.com/mozilla/multi-account-containers/pull/992#issuecomment-346135625 to see if the helps.

**Comment by SnoFox** [comment]
Trying to move from Chrome here. My workflow:
1. Find the window with the profile I want to use.
2. Hit Ctrl+T

While playing with Multi-Account containers today, I was hoping to get that same workflow, or similar workflow, which the original suggestion can facilitate with custom hotkeys.

**Comment by Nudin** [comment]
I'd love to set one container as "default" – so that `Ctrl+T` opens this kind of container instead of a "default-tab".

**Comment by sparklesam** [comment]
*Mac users only*
Actually Mac has integrated shortcut internally. Since New Container Tab is a part of the menu bar `File -> New Container Tab -> Container Name`. We can use `System Preference -> Keyboard -> App Shortcuts` to create a keyboard shortcut anyway we want. 

Like this 
<img width="619" alt="screen shot 2018-04-19 at 11 38 01 am" src="https://user-images.githubusercontent.com/10287995/38970116-3b2deec8-43c6-11e8-96eb-64454383c0a1.png">

But small problem is it only activate when I click on the menu first, still figuring out a proper solution.

**Comment by zefilipe** [comment]
After a weeks using the amazing addon containers, it faults keyboard shortcuts to:
- hide container tabs
- show container tabs
- define wich container is this tab (plus button) 
...

**Comment by fooditron** [comment]
Methinks the current tab container should dictate the container of the new tab, no?

Glad to see this is an issue being actively discussed!

**Comment by acdha** [comment]
Just wanted to second @fooditron: 99% of the time it would be what I want if Command-T opened a tab using the same container as the one which had focus when I hit the hotkey.

**Comment by bettyvschmartz** [comment]
Looks like this suggestion from @ThisUserIsEpic2 hasn't gained any attention but this has been something I've been hoping for. I tend to use keyboard shortcuts to operate and ctrl+t opening a tab outside of a container isn't ideal, especially when the option _"Select a container for each new tab"_ is set. 

-- BVS

**Comment by nikaro** [comment]
You can press `Ctrl + .` and then a number (`1` for personal, `2` for work, etc.) to open a given container type.

**Comment by fooditron** [comment]
I highly recommend the **Easy Container Shortcuts** Add-on. I've been using it for a year now.

How it works:

to open a new container tab: **CTRL + SHIFT + NumberRow** 
to switch containers: **ALT + CTRL + NumberRow**

**Comment by bettyvschmartz** [comment]
> You can press `Ctrl + .` and then a number (`1` for personal, `2` for work, etc.) to open a given container type.

Sure, I mentioned this in issue [#462](https://github.com/mozilla/multi-account-containers/issues/462#issuecomment-732340051)

**Comment by bettyvschmartz** [comment]
> I highly recommend the **Easy Container Shortcuts** Add-on. I've been using it for a year now.
> 
> How it works:
> 
> to open a new container tab: **CTRL + SHIFT + NumberRow** 
> to switch containers: **ALT + CTRL + NumberRow**

I'd prefer something native from Mozilla for this. Plus, a number of add-ons seem to need a lot of permissions. 

-- BVS

**Comment by fooditron** [comment]
So would I. But this has been an acceptable substitute for me.

**Comment by dannycolin** [comment]
Closing since you can assign a shortcut to a specific container in the latest version.

See: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
