### ISSUE TITLE
Breaks 2FA

### ISSUE THREAD

**Issue by TriMoon** [mozilla/multi-account-containers#1074]
Simple test:
  - Have https://discourse.mozilla.org/ set to open in "Personal" container
  - Have https://github.com/ set to open in any other container eg. "Work".
  1. Navigate to https://discourse.mozilla.org/ and try to login using github.
  1. It won't be able because it can't find the cookie...

**Comment by TriMoon** [comment]
Seems related to https://github.com/mozilla/multi-account-containers/issues/311#issuecomment-287359299

**Comment by groovecoder** [comment]
This is the intended behavior. Your "Personal" container should not have access to cookies in the GitHub container.

**Comment by TriMoon** [comment]
So it's a confirmed and intended breaking of 2FA mechanism? weird...
One group trying to make things easier, while the other intentionally makes it impossible.
And both claim to improve privacy...

So as consumers of these technologies, we need to make a clear choice, one or the other...
I guess 2FA will win... thx

**Comment by groovecoder** [comment]
It's not intended to break the 2FA. Can you be more specific exactly which 2FA you're using? (On discourse.mozilla.org, or on github.com, or both?)

Crossing the container barrier during a 3rd-party OAuth flow that needs cookies will break on purpose.

**Comment by TriMoon** [comment]
This
> It's not intended to break the 2FA.

And this
> Crossing the container barrier during a 3rd-party OAuth flow that needs cookies will break on purpose.

Contradict each other....
As i said, the current behavior is thus **intended** to break 2FA when a user makes active use of this extension period...
If it's **NOT** intended to break 2FA while using this extension, then it should not change containers while performing the 2FA...

> Can you be more specific exactly which 2FA you're using? (On discourse.mozilla.org, or on github.com, or both?)

Read the instructions in OP carefully, you should come to conclusion that the answer is mozilla, while both are set to use different containers...

**Comment by groovecoder** [comment]
Okay, that explains it. 2FA and OAuth are not interchangeable.

I can absolutely reproduce your instructions in OP where crossing a Container boundary breaks OAuth when the OAuth provider site is assigned to a different container.

This is by design and we won't be changing it.

My solution (e.g., with GitHub auth to other sites) has been to create a "GitHub" container and assign all sites that use my GitHub account for OAuth  to my "GitHub" container. Hope that helps.
