### ISSUE TITLE
Synchronize our config to several stations ?

### ISSUE THREAD

**Issue by jfbourdeau** [mozilla/multi-account-containers#1076]
Is there is sync our config of multi-account-containers on several stations ?
So we don't have to make the add-on learns 20 or 30 sites on 3 differents computers ?
JF

**Comment by jfbourdeau** [comment]
Is there a FOLDER we can BackUp to COPY / Paste in on a new station ?

**Comment by groovecoder** [comment]
This is a dupe of https://github.com/mozilla/multi-account-containers/issues/339.
