### ISSUE TITLE
Firefox for Android 57.0.4 (Firefox Quantum) not compatible

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/multi-account-containers#1083]
I cannot install Firefox Multi-Account Containers in Firefox for Android 57.0.4 despite that "Version 5.0.1" at https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/versions/ says "Works with Firefox for Android 57.0 and later"

**Comment by groovecoder** [comment]
See https://github.com/mozilla/multi-account-containers/issues/989 for comments about Android support. We don't have it, so I updated the addons.mozilla.org page to remove Android.

**Comment by davidhedlund** [comment]
Thank you.
