### ISSUE TITLE
Add a container class to HTML element (to enable user styles and scripts)

### ISSUE THREAD

**Issue by skddc** [mozilla/multi-account-containers#1086]
I just tried to find out if it's possible to add some userstyles based on which container tab is open, so I can more easily differentiate between accounts when posting. (Oftentimes I respond to Mastodon posts from the wrong account for example.)

Would you consider adding a classname, e.g. container name lowercase-dasherized or sth, to container pages' `<html>` or `<body>` element? That way anyone can easily add styles and scripts to any website, based on what container they're viewing it in.

**Comment by groovecoder** [comment]
Thanks for the issue. For what it's worth, I use https://addons.mozilla.org/firefox/addon/containers-theme/ to differentiate container tabs.

The ability to "add styles and scripts to any website" needs thorough security analysis and examination that is outside the scope of this particular add-on. https://add0n.com/stylus.html may be helpful instead.

**Comment by skddc** [comment]
> The ability to "add styles and scripts to any website" needs thorough security analysis and examination that is outside the scope of this particular add-on. https://add0n.com/stylus.html may be helpful instead.

I can see potential security issues there (privacy issue when adding container names e.g., but a hash would suffice as well). However, the issue is specifically about adding styles *based on the container context a page is viewed in*. I opened the issue to find a way for how to use something like Stylus, but have different styles for different container contexts. Stylus on its own can't solve that.

> Thanks for the issue. For what it's worth, I use https://addons.mozilla.org/firefox/addon/containers-theme/ to differentiate container tabs.

This is defnitely a good stopgap, making it easier to discern between the tabs for now. Thanks for the tip!

**Comment by groovecoder** [comment]
I think Stylus can implement this if they make their code check the `cookieStoreId` of a tab before they style it. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab You should file an issue with them.

**Comment by skddc** [comment]
Ooh, so there *is* a way to determine which container I'm in from the client side then. I'll check it out, thanks!
