### ISSUE TITLE
Invoke the menu when right-clicking the tab itself

### ISSUE THREAD

**Issue by galvao** [mozilla/multi-account-containers#1087]
Some websites (most notably Google Drive) disallow/replace context menu so It's impossible to manipulate how containers would work with them.
It would be good if we could do that in some other way, like right clicking the tab itself, for an example.

**Comment by groovecoder** [comment]
Is there a specific feature in the context menu that isn't available in the pop-up?

**Comment by galvao** [comment]
@groovecoder Hey there, Luke. What do you mean by popup? The context menu is the one you get by right-clicking on the page area right?

**Comment by groovecoder** [comment]
The pop-up when you click the browser action icon ...

<img width="302" alt="image" src="https://user-images.githubusercontent.com/71928/35280661-79696fb2-0016-11e8-8bec-446ebb36b064.png">

**Comment by galvao** [comment]
*facepalm* Of course! Got it! Thanks, man, never occured to me.
