### ISSUE TITLE
Intergrated/Windows Auth (NTLM) leaks between containers

### ISSUE THREAD

**Issue by fowl2** [mozilla/multi-account-containers#1089]
I have `network.automatic-ntlm-auth.allow-non-fqdn` and `network.automatic-ntlm-auth.trusted-uris` set to let me access my company's corporate resources without entering my credentials repeatedly. 

Sometimes I need to use a different account but no matter what container I use I'm automatically authenticated.

Private browsing presents a username/password dialog.

[about:support extract](https://github.com/mozilla/multi-account-containers/files/1654328/mozilla-multi-account-containers-issues-1089.json.txt)

**Comment by jonathanKingston** [comment]
I raised this here: https://bugzilla.mozilla.org/show_bug.cgi?id=1432562
Subscribe there for updates.
Thanks!
