### ISSUE TITLE
Tor container

### ISSUE THREAD

**Issue by Lionirdeadman** [mozilla/multi-account-containers#1090]
Basically, have the ability to create a container which tries to mimic as closely as possible the Tor browser (to avoid fingerprinting) and connects to the tor network. 

This would allow the user to create an "anonymous" container.

**Comment by groovecoder** [comment]
This is a great idea, but it's beyond the scope of this add-on. Please follow the Tor Uplift project & bugs instead:

https://wiki.mozilla.org/Security/Tor_Uplift
