### ISSUE TITLE
Ability to move existing open tabs to containers

### ISSUE THREAD

**Issue by sschuberth** [mozilla/multi-account-containers#1091]
I had a ton of tabs open before installing this extension. After installing the extension, I wished there was an easy way to move my existing open tabs to containers, similar to the existing "Move to New Window" feature.

**Comment by ArchangeGabriel** [comment]
There are already dozen of issues about this. The answer is https://github.com/mozilla/multi-account-containers/wiki/Moving-between-containers.

**Comment by sschuberth** [comment]
Isn't "moving between containers" something different than "moving from no container to any container"?

**Comment by ArchangeGabriel** [comment]
“No container” is a container, the “default” container.

**Comment by sschuberth** [comment]
I see. I believe that could be made more clear in the linked Wiki page. That's very unfortunately, but feel free to close the issue then.

**Comment by falolaf** [comment]
You could use this addon:
https://addons.mozilla.org/en-US/firefox/addon/switch-container/

**Comment by sschuberth** [comment]
Thanks. Turns out I prefer https://addons.mozilla.org/en-US/firefox/addon/context-plus/ as it adds itself to the tab context menu instead of creating a toolbar icon to use.
