### ISSUE TITLE
Undo close tab + assignment issues

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/multi-account-containers#1093]
Summary: You can't undo close tab twice after the browser attempts to open an assigned website in the wrong Container.  This may or may not also require that assigned website to go through a redirect. 

STR:
1) Go to bugzilla.mozilla.org in a Bugs Container.
2) Assign bugzilla.mozilla.org to Bugs.
3) Visit bugzilla.mozilla.org in the default Container.  Click the "Always Remember" box and click the button to open the Bugs Container.
4) Go to mail.google.com in Work Container.
5) Open email from bugzilla.  Click the link to a bug.
The browser will open a Work Container with a redirected mail.google.com link.  The redirected link will then take you to bugzilla.mozilla.org.  The browser will see the redirect and open a Bugs Container because bugzilla.mozilla.org is assigned to Bugs, closing the Work Container.
6) You now have a Bugs Container with a bugzilla bug in it.  Close that bugzilla.mozilla.org link
7) Repeat step 5 with a new bugzilla email and a new bugzilla link (i.e. go to a different but number using the steps in step 5).
8) Close the tab for the second bugzilla bug.
9) You want to reopen the tab you closed in step 6.
Expected: clicking undo close tab twice should reopen both bugzilla links you closed.
Actual: You can only reopen the tab from step 8. 

This might be because undo close tab is opening the Work Container tab where the redirect took place.  This Work Container gets opened and quickly closed, replaced with a Bugs Container.  Once your browser is in this state, you can't get to any of your previous closed tabs.

**Comment by jonathanKingston** [comment]
We might be able to fix it if we track the redirection of a previous tab perhaps. It might not be error free like site assignment isn't.

**Comment by stoically** [comment]
Is there actually a way to influence which tabs Firefox will open when clicking "Undo close tab"? I found no such WebExtension API. And if not I don't see how tracking redirects could help in that case - or do I missed something here?

**Comment by kendallcorner** [comment]
While testing, I found that I can open both bug pages by undoing tab close 3 times (I also get the extra gmail page that was opened and then closed quickly), so this looks like it is fixed. I'll close it, but please reopen or let me know if there's more work to be done here.
