### ISSUE TITLE
_execute_browser_action shortcut on Mac should be Cmd+., not ctrl+.

### ISSUE THREAD

**Issue by mozjag** [mozilla/multi-account-containers#1094]
All the other (browser) shortcuts use Cmd as the base shortcut modifier on Mac, I don't think this add-on should go out of its way to use ctrl on Mac instead.

**Comment by groovecoder** [comment]
Sadly, `Cmd`+`.` is already the shortcut for Cancel/Stop (loading page).

**Comment by mozjag** [comment]
Huh... TIL. Thanks for taking the time to let me know.
