### ISSUE TITLE
Add container ID to history entries

### ISSUE THREAD

**Issue by anewuser** [mozilla/multi-account-containers#1096]
If you just add container IDs to the [list of attributes that can be accessed through the history API](https://developer.mozilla.orgAdd-ons/WebExtensions/API/history/HistoryItem), extension developers will be able to solve problems like https://github.com/mozilla/multi-account-containers/issues/47 and  https://github.com/stoically/firefox-add-on-temporary-containers/issues/17 .

**Comment by stoically** [comment]
The related Firefox bug is tracked here https://bugzilla.mozilla.org/show_bug.cgi?id=1283320

**Comment by TanviHacks** [comment]
This requires platform support.
