### ISSUE TITLE
Provide "Option" contextual menu (Label: enhancement)

### ISSUE THREAD

**Issue by v00p** [mozilla/multi-account-containers#1098]
Redirecting to _about:preferences#containers._

**Comment by TanviHacks** [comment]
Can you provide more details on what you would like?

**Comment by v00p** [comment]
@TanviHacks Reaching MUA addons' preferences (about:preferences#containers) should be more accessible.
Currently the only way to reach this is by either manually typing/copy-pasting "about:preferences#containers" in the url bar or reaching Firefox's option (about:preferences#general) page, and then click on container's "Settings" button...

MUA already has the `privacy.userContext.enabled` config allowing in-page contextual access to MUA, so adding an MUA's "options" button in that in-page context menu should be fairly easy.

MUA also has contextual menu capability on the FF toolbar as well, but none of the two way currently provide a quick access to MUA's Options/MUA containers's settings

ie: ![https://i.epvpimg.com/LdFefab.png](https://i.epvpimg.com/LdFefab.png)

**Comment by v00p** [comment]
Also, This "Firefox Multi-Account Container" Context Menu shown above is sometime not present in some login hyperlink, while any other extension using contextual menu does. 
ie. Right-click on Twitter's login button. You'll see all of your other extension's enabled context menu, except that of Firefox Multi-Account Containers

**Comment by v00p** [comment]
Too much to ask for now (so many more urgent fixes yet-to-be made) ..
