### ISSUE TITLE
UI Enhancement: Scrollable container list with search bar

### ISSUE THREAD

**Issue by t4777sd** [mozilla/multi-account-containers#1103]
After about 20 containers it becomes unwieldy. It would be good if the container list scrolled so that it had a maximum height and above the container box was a search box that you can type and it would filter the displayed list based on what was typed.

It would make utilizing many containers much more user friendly.

**Comment by sakshi97** [comment]
Hi, @groovecoder. Can I take up this issue? It would help me get started with this repository.

**Comment by Paarmita** [comment]
@groovecoder @jonathanKingston @t4777sd  Can I work on it? I guess search input UI would look good. Any suggestions are welcomed.

![screenshot from 2018-09-24 15-10-33](https://user-images.githubusercontent.com/26546816/45945717-03c23580-c00c-11e8-9c85-cf8c8fba2f7a.png)

**Comment by Riju19** [comment]
Hi! Is anyone working on this issue? If not, I'd like to take it up.

**Comment by groovecoder** [comment]
I think @Paarmita or @sakshi97 may already be working on this?

**Comment by sakshi97** [comment]
I wasn't able to start due to exams and course commitments. But I will take this up now.

**Comment by AlbionaHoti** [comment]
I am an Outreachy applicant, I would like to work on this issue if it's not solved yet. @groovecoder

**Comment by yellowwoods12** [comment]
Hi @groovecoder and @maxxcrawford, I've started working on this issue and will complete it soon. I am an Outreachy applicant. 
Can you please assign it to me?
Here is the screeshot of how the feature will look. Any changes and suggestions for the design are welcome.
![Screenshot from 2019-10-11 12-47-41](https://user-images.githubusercontent.com/31931348/66632547-5aee7480-ec26-11e9-9159-d46fd3d8122e.png)

**Comment by zackzack02** [comment]
One year later (after closing #1527), can you reconsider implementing this feature ?
Please,

**Comment by hub2git** [comment]
> This feature is very important. Is there any release date expected?

Every time my Firefox updates itself, I excitedly check if this extension has a search box.  :) Can't wait for it to appear! It will be a huge timesaver!
