### ISSUE TITLE
Cannot create container with numbers in the name using popup

### ISSUE THREAD

**Issue by leth** [mozilla/multi-account-containers#1113]
When you try to type a low number (e.g 2 or 3) into the name field, the popup will instead open a new tab in the container matching that number.

![z3q1b5fdme](https://user-images.githubusercontent.com/52370/36020389-6af76ecc-0d7a-11e8-9908-59cff806c015.gif)

To workaround this, I typed the name elsewhere, and pasted it in -_-

**Comment by stoically** [comment]
This got handled in https://github.com/mozilla/multi-account-containers/pull/1097 and will be fixed in the next version.
