### ISSUE TITLE
Websites seem to be able to read data from other container tabs

### ISSUE THREAD

**Issue by dreihodenbob** [mozilla/multi-account-containers#1122]
Hi,

I'm not sure if I got the whole concept of container tabs wrong or if there's something not working as it should. I'm using multi account containers because my assumption is, that the containers are completely separated from each other and websites opened in container a are not able to see which websites are opened in container b. Is that correct?

Because multiple times now I made the experience, that this obviously does not work as expected. In Facebook, which is opened in container A I get advertising for sites I visited in a different container. Is this supposed to work this way or is there a known issue about it?

Thanks,

Richard

**Comment by groovecoder** [comment]
Containers are powered by Contextual Identities, which [separate cookies and other site storage](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers#What_is_.28and_isn.27t.29_separated_between_Containers) mechanisms that are used to track users.

Some trackers use other methods which are not effectively separated by Containers. 😢
