### ISSUE TITLE
"New Container Tab" choice is ignored when no prior windows exist

### ISSUE THREAD

**Issue by arafalov** [mozilla/multi-account-containers#1123]
If all all windows are closed (on Mac) and _File/New Container Tab/Container name_ is chosen, the opened tab (only one in the window) is generic, not a container-specific.

Tested with 5.0.1 on Mac.

**Comment by groovecoder** [comment]
This is a platform bug. @TanviHacks will add the bug number here and we'll close this issue.

**Comment by TanviHacks** [comment]
Filed platform bug https://bugzilla.mozilla.org/show_bug.cgi?id=1442346
