### ISSUE TITLE
Trying to name/rename a container with a digit launches new tab

### ISSUE THREAD

**Issue by ivan-m** [mozilla/multi-account-containers#1126]
If I try to either create a new container (using the + on the bottom right of the button's menu) or edit the name of an existing container, as soon as I type in a digit between 1 and `n` then instead a new tab in the `n`th existing container is opened (with `0` opening a new tab using the 10th container).

That is, if I have the following existing Containers:

* Personal
* Work
* School

And I want to rename "School" to "School 02", then the `0` successfully gets entered in, but as soon as I hit the `2` key then a new "Work" tab is opened.

Firefox version: 58.0.2 (64-bit)
OS: macOS 10.13.3 
Installed extensions: 
* Awesome Autocomplete for Github
* Cisco WebEx Extension
* Firefox Multi-Account Containers
* Google search link fix
* Open in Browser
* Privacy Badger
* Self Destroying Cookies
* Tab Session Manager
* Tree Style Tab
* TST Closed Tabs Menu
* TST Open In Private
* uBlock Origin
* Mute all inactive tabs (disabled)

**Comment by ivan-m** [comment]
As a follow-up: trying to enter Shift+`n` (e.g. `@` in the previous example) causes the same behaviour.

**Comment by stoically** [comment]
This got handled in #1097 and will be fixed in the next version.

Duplicate: #1084

**Comment by groovecoder** [comment]
Closing as dupe. We'll release next version today.
