### ISSUE TITLE
When load inaccessible site 

### ISSUE THREAD

**Issue by wellington1993** [mozilla/multi-account-containers#1127]
Hi,

when loadin local site without start server or sometimes when pages load.
The Browser console show this alerts:
```
siteSettings is null  assignManager.js:136
Error: Missing host permission for the tab undefined
```

```
08:13:28.994 siteSettings is null 1 assignManager.js:136
	applyChanges resource://gre/modules/WebRequest.jsm:806:23
	throw self-hosted:1230:9
```

I don't know why...

Thanks!

**Comment by stoically** [comment]
This got handled in https://github.com/mozilla/multi-account-containers/pull/1106 and will be fixed with the next version

**Comment by jonathanKingston** [comment]
This merged to live yesterday. Let me know if this is still occurring. Thanks!

**Comment by wellington1993** [comment]
@jonathanKingston  Still occurring at Firefox Nightly:

This file:`
view-source:moz-extension://1d51de64-b5f9-4d08-992f-9f679b93e50d/js/background/assignManager.js
`

That version:
```
Nome 	Firefox
Versão 	61.0a1
ID da compilação 	20180321102906
```

That system:
```
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
OS 	Linux 4.15.0-12-generic
```

Thanks!

**Comment by stoically** [comment]
@wellington1993 Can you confirm that you experience that with the latest Multi-Account Containers which is 6.0.0?
