### ISSUE TITLE
Document extension communication protocol

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/multi-account-containers#1130]
Extensions can query data from this one. It would be nice if that was documented somewhere (README, wiki, etc.). From looking over existing comments etc. I've gathered the following:

---

The `contextualIdentities` permission is required to query information.

The message that is sent must be an object with the following properties:
 - `method` set to `getAssignment`
 - `url` with the URL to query information for

The reply is either falsy or an object with at least the following properties:
 - `neverAsk` (presumably a boolean)
 - `userContextId` (presumably the cookie store ID)

---

Example usage:
```js
browser.runtime.sendMessageExternal('@testpilot-containers', {
  method: 'getAssignment',
  url: 'https://example.com'
}).then((assignment) => {
  // Use result
});
```

**Comment by stoically** [comment]
Hi, adding this to the Wiki seems like a good idea.

To extend on what you collected so far:

---

The `contextualIdentities` permission is required to send messages.

The message that is sent must be an object with the following properties:

* `method` set to `getAssignment`
* `url` with the URL to check for assignment

The reply is a Promise that resolves to either falsy if no assignment was found or to an object with at least the following properties:

* `neverAsk`, boolean, `true` if the assignment was made permanent with "Remember my choice"
* `userContextId`, string, the `cookieStoreId` without the leading `firefox-container-`

If the `contextualIdentities` permission is missing, no `method` is given, the `method` is unknown or the `url` parameter is `undefined` for the `getAssignment` method the Promise will get rejected.

Example usage:

```js
browser.runtime.sendMessage('@testpilot-containers', {
  method: 'getAssignment',
  url: 'https://example.com'
}).then((assignment) => {
  // Use result
}).catch((error) => {
  // Something went wrong
});
```

**Comment by groovecoder** [comment]
I'll assign this to @stoically so he can add this to a wiki page.

**Comment by groovecoder** [comment]
Assigned to @stoically to add this content to a new wiki page for "3rd-party" Container add-on authors.

**Comment by stoically** [comment]
I've added it to the Wiki: https://github.com/mozilla/multi-account-containers/wiki/API Feel free to let me know if you feel that something is missing.
