### ISSUE TITLE
Custom New Tabs prevents proper functioning

### ISSUE THREAD

**Issue by siffegh** [mozilla/multi-account-containers#1132]
Container tabs created with Firefox Multi-Account Containers are just regular tabs if Custom New Tabs (https://addons.mozilla.org/en-US/firefox/addon/custom-new-tabs) is also installed.

**Comment by stoically** [comment]
Custom New Tabs needs to be container-aware, so this needs to be resolved in the Issue you created with CNT https://github.com/deadmund/Custom-New-Tab/issues/20 - I left a comment there to maybe help out.

**Comment by siffegh** [comment]
Thanks much.

**Comment by groovecoder** [comment]
Marking as addon incompatibility and closing as it needs to be fixed by Custom-New-Tab
