### ISSUE TITLE
[Feature Request] Proxy settings for each category

### ISSUE THREAD

**Issue by sehakoc** [mozilla/multi-account-containers#1134]
Hello, I would like to make a feature request.
I love to use Firefox for my academic researches and while doing that I need to use my university proxy address for reaching academic resources. For this purpose I tought that it will be perfect for assign different proxy settings for each category.

For example I have 2 container categories: 1) Education 2) Bank
I should assign a proxy only for "Education" category and while I'm using "Bank" category this tabs shouldn't be effected by other categories proxy settings.

I don't know it is applicable or not but I think it would be very useful.

**Comment by stoically** [comment]
Duplicate that you can vote for: https://github.com/mozilla/multi-account-containers/issues/313
