### ISSUE TITLE
"Always open in container" check box does not take into account the port 

### ISSUE THREAD

**Issue by axmichail** [mozilla/multi-account-containers#1135]
http://test:8089
http://test:8090

They should be allowed to be opened in different containers using that check box, 

I enabled the first one in container C1 , it works fine
I try enabling the second one to open always in container C2 : 
1. open a tab within the second container 
2. navigate to http://test:8090 

Rather than letting me open this website in C2, it auto-takes me into C1, which is wrong. 

Please fix it

**Comment by ArchangeGabriel** [comment]
Well indeed only the domain is used, not any other part of the URL, including port.

**Comment by TanviHacks** [comment]
For standard ports (443, 80) we should not take into account the port.  But for non-standard ports we should allow assignment.

**Comment by skddc** [comment]
Bump. This is still terrible for developing stuff on localhost. Especially because removing the assignment is also impossible. It doesn't remember when you check "remember this decision" and use the current default container.

**Comment by skddc** [comment]
Maybe we need to reset something manually, when it was set before the fix?

**Comment by ShivangiKakkar** [comment]
@groovecoder @skddc, After pulling the latest release and simulating the exact scenario as described in the issue, localhost:8090 opens correctly in C2. Tried other combinations as well couldn't find a problem, seems like it is solved.

**Comment by groovecoder** [comment]
@skddc ah, the code fixed this bug at assignment time. So, I think you'll need to un-assign and re-assign the sites to their containers to fix this.

**Comment by skddc** [comment]
How do I un-assign? The re-assigment is exactly what's broken for me.

**Comment by groovecoder** [comment]
Click "Edit Containers" at the bottom of the browserAction panel, then click the container name, and you should see a list of the domains that are assigned to the container. When you mouse over one of the domains, a little trash can icon will appear. Click it to delete the assignment.

**Comment by skddc** [comment]
Oof, finally found it thanks to your help! :pray:

**Comment by groovecoder** [comment]
Glad you found it. Closing this now.
