### ISSUE TITLE
[BUG] Cookies cleared after disabling and enabling Multi-Account-Containers

### ISSUE THREAD

**Issue by i486** [mozilla/multi-account-containers#1139]
I disabled both Multi-Account-Containers and Test Pilot in Add-ons page and enabled them again.

Now all sites are logged out in all containers (it seems cookies are cleared). 

I think this is a bug, no?

**Comment by stoically** [comment]
Disabling or removing the last Add-on that keeps the container-feature active intentionally triggeres a complete reset of containers in Firefox. https://github.com/mozilla/multi-account-containers/issues/864#issuecomment-335288110 However, it should indeed warn the user that exactly that will happen.

**Comment by groovecoder** [comment]
We don't have a good way to add a warning on uninstall or disable. 😢 And adding a warning during install is probably scary for users too. Don't think we can do anything here.
