### ISSUE TITLE
Loading favicons in "open site in assigned container" prompt may fail due to tracking protection

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/multi-account-containers#1143]
Tracking protection may block the loading of favicons in the "Open this site in your assigned container?" prompt.

This could in theory be bypassed by having a full host permission for the blocked host (see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#Host_permissions ) however, that would result in crazy amounts of required host permissions.

A more realistic fix would be https://bugzilla.mozilla.org/show_bug.cgi?id=1315616 which would give extensions access to favicons via browser favicon infrastructure.

**Comment by freaktechnik** [comment]
As an aside: are favicons in the prompt loaded via the assigned default container?

**Comment by groovecoder** [comment]
Agree that bug 1315616 is the better fix. So I'm going to label this a bug, but I'm also going to close it.

**Comment by stoically** [comment]
@freaktechnik favicons are loaded in the container the confirm page is loaded in
