### ISSUE TITLE
Firefox Multi Account Containers 5.0.1 : permission to monitor web-extensions

### ISSUE THREAD

**Issue by prog-amateur** [mozilla/multi-account-containers#1144]
Hello, 

Before to update my add-on on version 5.0.1, I would like to clarify why Firefox Multi Account Containers asks me permission to monitor my other web-extensions ? 

Can somebody explain exactly how and why is it necessary please ? 

Thank you very much.

**Comment by stoically** [comment]
Hello, you can find a detailed explanation about the permissions here: https://github.com/mozilla/multi-account-containers/wiki/Permissions

**Comment by stoically** [comment]
Hope that helps, let me know if not.
