### ISSUE TITLE
Allow users to enter their own domain to always open in container

### ISSUE THREAD

**Issue by grenzor** [mozilla/multi-account-containers#1148]
There are websites that can have intermediate pages which are then redirected to the main site. For example when you visit gmail.com it doesn't land on gmail.com and actually just redirects to another domain which means that gmail.com will open in an unspecified container and only the redirected main page will then get loaded in the user specified container. 

There is no way to right-click then click 'Always open in this container' on gmail.com as it will redirect the page too quick. 

Please allow users to add their own domains or all subdomains (*.domain.com) to 'Always open in this container' in the settings of each container.

**Comment by stoically** [comment]
Hi, duplicate that you can vote for: https://github.com/mozilla/multi-account-containers/issues/473

I agree that it would be useful to configure other domains for containers, even without wildcard-support, because that seems to be the main concern currently.
