### ISSUE TITLE
How should plus button scroll if there are too many containers?

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/multi-account-containers#115]
If we have too many containers, what should the plus button UI look like?  Should it be scrollable, should it shrink, etc?

@johngruen

**Comment by youwenliang** [comment]
@TanviHacks 

One thought is that we can show at most 4 containers and a "more button". If a user clicks the "more button" the doorhanger will show up for more options.

![1 3 container open new tab behavior](https://cloud.githubusercontent.com/assets/8919308/22721719/573e9638-eded-11e6-8613-785d23ec30d0.png)
![1 4 container expand panel](https://cloud.githubusercontent.com/assets/8919308/22721720/5740f130-eded-11e6-9400-37b831f1547b.png)

**Comment by Madis0** [comment]
It should scroll like any other context menu - arrows on top and bottom, will scroll when the cursor is nearby.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
