### ISSUE TITLE
Containers get reset when toggling Extension state ON/OFF

### ISSUE THREAD

**Issue by v00p** [mozilla/multi-account-containers#1150]
Had to manually restore `containers.json `(along with couple other profiles file as there is no clear documentation on what files are bound to this extension)

**Comment by stoically** [comment]
Sorry about your containers and glad you could restore them - however, this is [intended behavior](https://github.com/mozilla/multi-account-containers/issues/864#issuecomment-335288110). You can follow #864 to see if something changes.

**Comment by thefireinyourflies** [comment]
hi @v00p do you remember which other files need restore besides containers.json? does it restore tabs in containers or just the container items?
