### ISSUE TITLE
Sometimes small font at Retina display

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mozilla/multi-account-containers#1152]
<img width="364" alt="screen shot 2018-03-15 at 10 17 05 am" src="https://user-images.githubusercontent.com/3514015/37449156-4de4ef00-283a-11e8-9aa9-43f41c1a855d.png">

**Comment by yatri1609** [comment]
@vitaly-zdanevich Can you explain the bug a bit more ?

**Comment by ShivangiKakkar** [comment]
I guess he means that the container shows above behaviour as explained when tested for a Mac Retina display. Not sure, need to test myself but we may test this by going to`about:config` -> search for layout.css.devPixelsPerPx ->  change the ratio from -1 to -2.

**Comment by yatri1609** [comment]
Ohk I guess we need to have a look at it. If I would be able to reproduce it I'll love to work on this.

**Comment by vitaly-zdanevich** [comment]
Cannot reproduce on the current Firefox Nightly.
