### ISSUE TITLE
Can't hide a container

### ISSUE THREAD

**Issue by Vatq** [mozilla/multi-account-containers#1154]
Can't hide a container. When clicking on the right arrow to view the container so I may hide it, a login dialog pops up and no matter how many times I try to view the container content and completing the login dialog it never allows me back in. Only way to get it working again is deleting all tabs from the container and recreate the tabs so, basically I can just stick with bookmarks since I will lose tabs using this

**Comment by stoically** [comment]
Could you please provide steps to reproduce? Especially which websites are open in the container that you want to hide and for which website the login dialog pops up when clicking on "Hide this container"?

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. Steps to reproduce this issue were never provided, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Comment by stoically** [comment]
@kendallcorner Great to see you catching up on triaging the issue here! Just a quick note: issues closed by collaborators can't get reopened by non-collaborators.

**Comment by kendallcorner** [comment]
Ah shoot. @groovecoder told me they could.  I'll keep an eye out for any comments from people wanting to reopen. Thanks for letting me know!
