### ISSUE TITLE
After unhiding page reloads

### ISSUE THREAD

**Issue by killua1zoldyck** [mozilla/multi-account-containers#1156]
All the pages in a container reloads after "Un-Hiding" the containers.

**Comment by stoically** [comment]
"Hiding" container tabs actually closes the tabs and opens new tabs with the "Hidden Tabs" URL when "Showing" them again. This is expected behavior, since there's no way of actually just "hiding" tabs ("Undo close tabs" or "Recently closed tabs" in Firefox work the same way).
