### ISSUE TITLE
Disabling this extension makes it forget customizations

### ISSUE THREAD

**Issue by igvk** [mozilla/multi-account-containers#1159]
While troubleshooting Firefox extensions (using both safe mode and manually disabling extensions), I noticed that when Multi-account containers were re-enabled, all my customized containers were forgotten.
And also no way to backup/restore them.

**Comment by stoically** [comment]
Sorry about your containers - however, this is [intended behavior](https://github.com/mozilla/multi-account-containers/issues/864#issuecomment-335288110). You can follow #864 to see if something changes.
