### ISSUE TITLE
Is there any way to not get the "you opened 100 containers" message?

### ISSUE THREAD

**Issue by o55** [mozilla/multi-account-containers#1161]
I love the containers extension. Thanks a lot for making it! However: Having the  "you opened 100 containers" appear every 100 times I click a button is incredibly annoying. (I see it daily.) Is it possible to turn off this message? If not, should it not be? A simple don't tell me again button seems reasonable.

**Comment by groovecoder** [comment]
It should not show up again after you click the button to close it. You're seeing it every day? 😢

**Comment by o55** [comment]
Thankfully it seems to have stopped now (checked by opening 100 containers right now). I only saw the popup 4-5 times in the first 4 days I was using the extension. (On the same browser without any reset of cache or anything like that, on the same machine with the same OS install.)
