### ISSUE TITLE
Multi-account containers with "Never remember history"

### ISSUE THREAD

**Issue by uakfdotb** [mozilla/multi-account-containers#1164]
Opening a tab from the extension when "Never remember history" is selected does not seem to do anything. I read from https://support.mozilla.org/en-US/kb/containers that it is because the extension is disabled when "Never remember history" is selected.

Is it possible to add support for using multi-account containers with "Never remember history"? The UI would be the same, it would just work instead of not doing anything with that browser option. But perhaps there is something in the browser that makes this difficult.

My use case is that I want to keep different activities isolated during one browsing session, but I also don't want the browser to use the disk cache.

Relatedly: if I use "Custom settings for history", and uncheck "Remember my browsing/download/search/form history" but check "Clear history when Firefox closes", and also disable the disk cache from about:config, is this equivalent to "Never remember history", and can I use this extension in that way?

**Comment by uakfdotb** [comment]
I see that pr #133 no longer works because WebExtensions doesn't support checking the browser option. I will try to think of a work-around. But I have never worked on an extension before so someone else probably has a better idea of how to work-around the issue.

**Comment by stoically** [comment]
"Never remember history" will start the browser in "Permanent Private Mode", and the Container feature isn't available in Private Windows.

Duplicate that you could vote for: #469
