### ISSUE TITLE
Load links, searches, bookmarks outisde of the Container.

### ISSUE THREAD

**Issue by Dotsquall** [mozilla/multi-account-containers#1165]
The new Firefox Container has this feature/behavior:

"When Facebook is open and you navigate to another website using the same tab (by entering an address, doing a search, or clicking a bookmark), the new website will be loaded outside of the Container"

Is there a way to get this on the main Add-on? having this option on a toggle would be nice.

**Comment by execat** [comment]
Hi, I have the same question.

Firstly, thanks for working on this addon. It has quickly become my fav addon 😁 

I want the domain list on my container (Google, YouTube) to act as a filter to what opens in that container.

eg.
1. Open google.com and search for something. It will correctly get switched to "Google" container
2. Click on a result
3. If the result is, say, GitHub (preconfigured in "Work" container to switch container by domain), the container switches to "Work" container from "Google" container
4. If the result is something not configured (say Hacker News), the container remains "Google".

A desirable result is that if the URL of the page is not in the list of domains allowed for that container, then your container gets switched to the default container. It is probably not expected for all containers, but I see the point in enabling it as an option for some containers like Facebook or Google.

**Comment by gacelperfinian** [comment]
I have read the [contain-facebook](https://github.com/mozilla/contain-facebook) addon's code (especially [background.js](https://github.com/mozilla/contain-facebook/blob/99bec758fb0a79ce43f36fe71a14998abfa61908/background.js)). It is using an async hook with some Facebook-specific support. Seems that this addon and that code needs a significant refactor to fit them nicely :)

**Comment by DanBuchan** [comment]
Just to chip in too. I would really like this behaviour. I have a twitter container but I'd like links that open in a new tab to just open in the default container without access to the twitter container cookies/details/info

**Comment by TrekkieTechie** [comment]
This is definitely needed, and has been asked for before: https://github.com/mozilla/multi-account-containers/issues/847

**Comment by stoically** [comment]
Great to see that you like the Facebook Container Isolation functionality.

As pointed out by @TrekkieTechie this has been asked before and it would be nice if you could add your votes for this functionality in #847. Leaving the issue open for a bit as I'd assume that other MAC users discovering the Facebook Container Add-on might've the same question.

To get this functionality right now by means of an extra Add-on you might want to check out my comment here: https://github.com/mozilla/multi-account-containers/issues/847#issuecomment-376979829

**Comment by madb1lly** [comment]
This is the main reason I'm not using Containers more. I want the _option_ to configure my containers to behave like the Facebook container add-on, i.e. that links outside Facebook open in a default container (or if another container is configured for that domain then in that container). I still want to be able to configure containers that retain the current behaviour though, so please only make the Facebook container behaviour optional.
