### ISSUE TITLE
Does not function on mac, potentialldy due to config changes

### ISSUE THREAD

**Issue by DiSino** [mozilla/multi-account-containers#1166]
The plugin does not function (no possibility to start tabs in any of the containers). Standard mac installation with the following changes to the configuration: https://blog.vpn.ac/firefox-privacy-security-tweaks.html

**Comment by stoically** [comment]
Do you by chance have `Never remember history` activated in the Firefox Options under `History`? None of the mentioned configurations or Add-ons in the article interferes with MAC functionality and I can't think of any other configuration that renders MAC completely unusable.

**Comment by DiSino** [comment]
@stoically Thank you, that indeed was the issue.
