### ISSUE TITLE
Can this plugin added as built in for nightly 

### ISSUE THREAD

**Issue by as3mbus** [mozilla/multi-account-containers#1175]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: Arch Linux, Latest
- Firefox Version: Nightly 61.0a1 (2018-03-30) (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
ColorZilla	3.3	true	{6AC85730-7D0F-4de0-B3FA-21142DD85326}
Firefox Multi-Account Containers	6.0.0	true	@testpilot-containers
GNOME Shell integration	10.1	true	chrome-gnome-shell@gnome.org
Min Vid	0.4.9	true	@min-vid
Search and Switch Containers	1.6	true	{cdbfc05c-3a99-460e-ba11-11ec4b71f789}
Tampermonkey	4.6.5709	true	firefox@tampermonkey.net
Test Pilot	2.0.8-dev-2425b5a	true	@testpilot-addon
uBlock Origin	1.15.18	true	uBlock0@raymondhill.net
Web Scrobbler	2.4.3	true	{799c0914-748b-41df-a25c-22d008f9e83f}

### Actual behavior
Multi Account Container Plugin need to be installed in every version of firefox 

### Expected behavior
add it inside nightly or maybe into quantum as a built in. see note for my reasoning

### Steps to reproduce
1. install firefox
2. find out it's hard to operate container
3. create this issue

#### In Short :  
can this plugin be included in nightly as a built in feature ? it would help many early adopter (like me) to try out and test this new feature as well as know about them and use it.
with container tab current state it would be really hard to know about this container tab by holding new tab button (which i wont use it much since i use shortcut [Ctrl + T])
#### More Reasoning : 
I really liked the new container feature of the new firefox. i also tried it in test pilot with it's cool mechanics (tbh i only started to get the grasp of it just now).
I was wondering why the new container tool button isn't present in new firefox as the new container feature is implemented. i've checked test pilot page of container tab wont deliver me to this plugin( or maybe my bad patience for reading stuff in the internet) finally i found mozilla support page and got here thanks to mozilla community (especially jscher2000), i found this git repo. 
i was interested in the reason why this container tool buton isn't included with the container feature as it's provide the ease of using container and also introducing container tab feature much more recognizable by new user.
i get more intrigued to write this issue with the new post about facebook container plugin which IMO only move facebook tab into an isolated container tab called "facebook" which could also be done with this plugin (always open in <container> check box)

**Comment by Madis0** [comment]
It is built to Nightly, however the extension part [gives "a richer user experience"](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/).

>**Haven't I seen this in Firefox before?**
>
>Firefox Multi-Account Containers was first introduced as "Containers" available only in Firefox Nightly. It went on to be a Test Pilot Experiment, where we improved the user experience and added new features. Now it exists here as an extension that can be installed by all Firefox users.
>
>Although you can still use the feature built into Firefox Nightly, we recommend using this extension as it has a richer user experience.

**Comment by as3mbus** [comment]
@Madis0 that's what i meant. why this extension "part" is not built in, even though the container feature did. 

if it's created with the purpose to become an extension why do they add container feature as a built-in but not include these tool.
since IMO the container feature without this tool is much more hassle, it would be best if we remove the container feature altogether and include it here.

but if the purpose of the container feature is keeping it as simple as possible, then at least add this in let's get started menu at start page.
at least it's introduce the feature to user much better than what it is right now.

**Comment by grahamperrin** [comment]
> why do they add container feature as a built-in 

For the feature to be usable by a variety of extensions; not for Multi-Account Containers alone.

**Comment by dannycolin** [comment]
Containers are a built-in feature and a WebExtension API that any extension can use for a variety of use cases. As much as I also would like to see a more advanced built-in container manager in Firefox, this isn't something actionable by anyone working on this project. 

I'd invite you to open a bug report on bugzilla.mozilla.org for the features in Multi-Account Containers that you think should be built-in in Firefox. You can also look in https://bugzilla.mozilla.org/show_bug.cgi?id=1191418 to see if the features you'd like have already been reported so you could subscribe to the bug reports in question.

Closing for now.
