### ISSUE TITLE
Multi-Account Containers and Facebook Container install blocked

### ISSUE THREAD

**Issue by CanarySec** [mozilla/multi-account-containers#1176]
The add-ons page for both extensions detects Firefox 52 and therefore won't allow installation. I was running the latest version of 59. I tried reinstalling from the download (also 59 but my Mac claimed it was an older file). The pages still detect an older version.

![screen shot 2018-04-01 at 9 16 03 am](https://user-images.githubusercontent.com/13111306/38174088-6e5cdc86-35b7-11e8-811b-86bf0cdd380c.png)

**Comment by stoically** [comment]
Could you check if you have `privacy.resistFingerprinting` set to `true` in `about:config`?

**Comment by jwaldmann** [comment]
Also, the installer seems to check the useragent string, so if you use `general.useragent.override`, then it won't work. It seems you can reset all these after installing.
