### ISSUE TITLE
Feature request: Manually edit which sites open in a container

### ISSUE THREAD

**Issue by madb1lly** [mozilla/multi-account-containers#1180]
Hi,

I'd like to be able to manually edit which sites open in a container. E.g. I've created a new tab for accounts.google.com, but maybe I want * .google. * to open in that tab - manually editting it would be much quicker than having to select the container each time I visited one of that group of sites.

If this is already possible then I've missed it, please tell me how! :)

Cheers.

**Comment by groovecoder** [comment]
Dupe of https://github.com/mozilla/multi-account-containers/issues/719 ... please upvote and comment there.

**Comment by madb1lly** [comment]
Thanks, I missed that one when I searched for existing issues.

**Comment by xanoni** [comment]
Found to workarounds that helped me, see https://github.com/mozilla/multi-account-containers/issues/1670#issuecomment-1416930533
