### ISSUE TITLE
[Feature Request] Beeing able to switch/change container once the site is open

### ISSUE THREAD

**Issue by solfen** [mozilla/multi-account-containers#1181]
### Actual behavior
When you open a container its type is set forever. It's especially bothering when combined with the "always open in" feature.

### Requested behavior
Being able to change the container type after the site has been opened. Like clicking on the container name in the address bar and having the option to reload the site in another container. Oh and maybe also to be able to open the site in a container if it was in "no context".

**Comment by falolaf** [comment]
Are you looking for something like this addon:
https://addons.mozilla.org/en-US/firefox/addon/switch-container/

**Comment by solfen** [comment]
Oh I didn't saw the security risk detailed in the wiki section, sorry !
Thanks for the addon link :)

**Comment by andreicristianpetcu** [comment]
More here https://addons.mozilla.org/ro/android/collections/andreipetcu/container-switching/
