### ISSUE TITLE
[Feature Request] Regex: Allow editing rules in regular expression?

### ISSUE THREAD

**Issue by Endle** [mozilla/multi-account-containers#1183]
### Actual behavior

Added <google.com> to  containerA

### Expected behavior

I can add a rule `*.google*.com`  
So all my visits to <mail.google.com> , <translate.google.com> will be handled within containerA

**Comment by benjamink** [comment]
Yes please.

**Comment by emilio-aburto** [comment]
Pleaaase <3

**Comment by castillar** [comment]
Implementing this could fit neatly with implementing issue 1317 (https://github.com/mozilla/multi-account-containers/issues/1317)--the ability to manually add sites or wildcards to a container list would be *enormously* useful.

**Comment by dueyfinster** [comment]
I will close the request on Mozilla for the same: https://bugzilla.mozilla.org/show_bug.cgi?id=1572403

**Comment by dannycolin** [comment]
FYI, there's an addon that let you use regex https://addons.mozilla.org/en-US/firefox/addon/containerise

Also, there's an issue (#473) and a PR (#1475)  to add a wildcard subdomains functionality.

**Comment by kendallcorner** [comment]
Hi. This looks like a duplicate of #473. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to reopen if you think it's a different issue.
