### ISSUE TITLE
Open bookmark in new tab duplicates tabs

### ISSUE THREAD

**Issue by fintara** [mozilla/multi-account-containers#1186]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: Arch Linux
- Firefox Version: 59.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: Facebook Container 1.3.0, Neat URL 4.0.1, uBlock Origin 1.15.24

### Actual behavior
Tab is created without container, after which it is closed and two tabs are created in the correct container.

### Expected behavior
Tab is created without container, after which it is closed and one tab is created in the correct container.

### Steps to reproduce
1. Add a website to the bookmarks toolbar.
2. Make this site to always open in a particular container.
3. Open the website in a new tab (from the bookmarks toolbar).

### Notes
..

**Comment by vibhas77** [comment]
Duplicate issue #1174

**Comment by fintara** [comment]
@vibhas77 not sure if it's a duplicate. The website is opened in the correct container, but twice. 

And actually it happens regardless of choosing "open in new tab" or just "open" -- if current tab has different container, the website will be opened twice.

**Comment by fintara** [comment]
Extremelly odd, happens only with https://www.youtube.com. Another sites that are supposed to open in the same container open only 1 tab (as expected).

**Comment by platelminto** [comment]
I also have this issue, and only with YouTube. This is very weird.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
