### ISSUE TITLE
"Always Open in Container" Name Logic (mail.google.com vs drive.google.com) + Regular Expressions?

### ISSUE THREAD

**Issue by bitsol** [mozilla/multi-account-containers#1187]
## Example Workflow, and why this is important
So, if I want a container to always open Google services (as an example), what do I do? I go to google.com in a container and click the "Always Open" checkbox. Then I visit drive.google.com and click "Always Open". Then I visit mail.google.com and click "Always Open". By now I'm wishing for a feature:
## The Solution
Maybe we could create an option that would allow the user to create a regular expression for "domain matching" (*.google.com), assuming it doesn't already exist somewhere.

Thoughts?

**Comment by nareshv** [comment]
Good to have this as it makes containers more powerful. If firefox can remember which domains to open in which containers, then nothing like it.

**Comment by bitsol** [comment]
I was just informed this is a duplicate issue. See the following:
https://github.com/mozilla/multi-account-containers/issues/473
