### ISSUE TITLE
Can't mark "Always open in..." for default container

### ISSUE THREAD

**Issue by maxnordlund** [mozilla/multi-account-containers#1194]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes

- Multi-Account Containers Version: 6.0.0
- Operating System + Version: OSX 10.13.4
- Firefox Version: 59.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:
about:addons: https://gist.github.com/maxnordlund/87aac7acad3773cf7a8c5b0e955de3ba

### Actual behavior
Nothing happens

### Expected behavior
Have the ability to assign sites/origins to the default container.

### Steps to reproduce
1. Go to any site in the default container
2. Select "Always open in"
3. Nothing happens

### Notes
I tried to assign https://accounts.firefox.com/ to the default container, but alas it does not work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-123)

**Comment by nocode99** [comment]
This behavior still exists on Firefox 63.0 with Container version 6.0.0 on Linux Mint.  My personal gmail has it's own container, but often, I would prefer other authenticated sites (ie Github) to open in the default.

**Comment by tntturtl** [comment]
Same issue on latest stable build (64.0.2)

**Comment by TimonVS** [comment]
I'm in the exact same situation as @nocode99. I want my work mail in a container but I'd like GitHub to open in the default container. I was able to configure this using [Containerise](https://addons.mozilla.org/en-US/firefox/addon/containerise/) but it's a bit messy (it opens the tab in a work container first, Containerise quickly closes the tab and opens a new one in the default container) and I'd rather not install another plugin that has this much access.

**Comment by dlee** [comment]
I can confirm that the "Always open in Default" checkbox is disabled. The checkbox only becomes available if you're on a non-Default container.

**Comment by mvdan** [comment]
I usually don't like plus-one comments, but I agree with this thread. I found it surprising that the tickbox was disabled. I made my setup with the default plus a work container, and the setup isn't nearly as powerful if I can't fix certain sites to the default container.

Of course, I could replace the default container with a "personal" container of some sort. However, why is that necessary? That would also color 90% of my tabs, which I'd like to avoid if possible.

**Comment by SCdF** [comment]
It's frustrating that it isn't native in the extension, but [Containerise](https://addons.mozilla.org/en-US/firefox/addon/containerise/) as noted above seems to work for me here.

**Comment by pappasam** [comment]
Bump

**Comment by pepelsbey** [comment]
Just like people above and in the other issues I have personal and work Gmail accounts, but I want all GitHub links to be opened in the Default container. I’d really love to see this option enabled.

**Comment by jessebrennan** [comment]
This seems like a bug to me, I'm curious why it's marked as an enhancement.

**Comment by feebabs** [comment]
I would agree this a bug. Somehow google.com was set to open in a specific container and from what I see there's no way for me to reset it back to the default container. Unless I'm just missing the setting, it seems like an oversight in the UI design. (v7.0.2)

**Comment by nocode99** [comment]
Bump

**Comment by grahamperrin** [comment]
> "Always open in..." … default container

▶ 2017 issue #503

@maxnordlund please close this duplicate. Thank you.

**Comment by maxnordlund** [comment]
Compared to #503 this used an issue template if I recall correctly. I like it, because it makes you write a clear set of instructions to reproduce the issue. If a maintainer wants to keep this for said instructions, please do, if you want to close this to triage, also please do.

In any case, this extension has been part of my daily live for years and is working beautifully ❤️

**Comment by grahamperrin** [comment]
Fair enough, re: https://github.com/mozilla/multi-account-containers/issues/503#ref-issue-314613225 please be prepared to engage with the other duplicates.

**Comment by dannycolin** [comment]
It's closed as a duplicate so there's a link on #503 that refers back here to make sure the information isn't lost.
