### ISSUE TITLE
Keyboard shortcuts (Ctrl .) conflicting with Github's Insert Reply hotkey

### ISSUE THREAD

**Issue by v00p** [mozilla/multi-account-containers#1201]
Github.com's Insert Comment's hotkey  `Ctrl .` is conflicting with MAC.

**[Suggested Solution]**
Convert hard-coded hotkey into user-configurable ones

Related #1189

**Comment by v00p** [comment]
Related #1189

**Comment by despairblue** [comment]
It also conflicts with 1Password X.

**Comment by alexsasharegan** [comment]
Yes, the 1Password conflict really affects my workflow. Wouldn't mind switching 1Password X to the Chrome shortcut `shift+cntrl+x`, but that doesn't seem to work for me.

**Comment by Knorrke** [comment]
It's also conflicting with Google Docs and Slack. Would be cool to be able to change the shortcut!

**Comment by k4ch0** [comment]
Indeed, +1 to can configure the shortcut!

**Comment by MostHated** [comment]
I have been trying to find them but have yet to see anything. Are there any additional hotkeys? I would love to see something like, ctrl + alt + 1 opens a new tab for container 1, ctrl + alt + 2 opens a new tab for container 2 (just examples of course).

**Comment by Knorrke** [comment]
@MostHated they are configured in the manifest.json:
https://github.com/mozilla/multi-account-containers/blob/41686fdf6c017cdd9cdf1ba132e416e35291a28d/src/manifest.json#L36-L44

But firefox 66 solved this now, every addon keybinding can be configured in `about:addons` 🎉 
https://www.ghacks.net/2019/01/16/manage-firefox-add-ons-keyboard-shortcuts-on-aboutaddons/

**Comment by dannycolin** [comment]
Closing since shortcuts can now be configured. See https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
