### ISSUE TITLE
[Feature Request] Open containerized page's hyperlinks into same container

### ISSUE THREAD

**Issue by v00p** [mozilla/multi-account-containers#1202]
Current Behaviour: 
Currently, web page hyperlinks launched from within containers will launch in same container without asking, only if the domain is bound to only one container or none at all (bound as in "_Always open in [container]_" option is checked). If more than one container is bound a same domain, any hyperlink clicked from within a containerized web page will automatically launch the [Container selection page (_Open this site in your assigned container_?)](moz-extension://87b72371-5f79-468a-b6ec-4baae3316131/confirm-page.html?url=...) ..

  Desired Behaviour:  Add and option for the user to allow hyperlinks clicked with third button mouse click to never trigger the Container selection, rather preserve the current container it was launched from.

**Comment by shtrom** [comment]
A variation of this, with a twist: sites like PayPal need to open in the caller's container to sucessfully process a payment (i.e., following links from an existing container). However, when opening PayPal by URL, I would like it to open in its own container, as specified with “Always open in...”.

I suspect it may be the same for OAuth.

**Comment by v00p** [comment]
I'll close, as it's a duplicate of  #1210
