### ISSUE TITLE
Color of container tab name and decoration, doesn't respond to editing.

### ISSUE THREAD

**Issue by befeather** [mozilla/multi-account-containers#1203]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: Xubuntu 16.04.4 LTS
- Firefox Version: 59.0.2 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: Multi-Account Containers: Enabled

### Actual behavior

While one of container tabs is opened and its color is changed, color of tab decoration is not changing at the same time, not even after refresh or opening urls in it. Tab decoration color changes only in newly opened containers. Color of the name/label of container (which is in url area) changes 
sometimes. 

### Expected behavior

Once container color is changed in "edit mode" it is expected to take effect immanently. Otherwise causes confusion.

### Steps to reproduce
1. Open new container tab
2. Edit it, change color
3. Look how tab color is not changing

### Notes

![peek 2018-04-25 03-32](https://user-images.githubusercontent.com/16600722/39220396-76bad146-4839-11e8-920a-e93226767f25.gif)

**Comment by kendallcorner** [comment]
Hi. This looks like a duplicate of #792. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to reopen if you think it's a different issue.
