### ISSUE TITLE
First container in menu is shown as highlighted, icon is a plus

### ISSUE THREAD

**Issue by aibaraiduas** [mozilla/multi-account-containers#1209]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: Ubuntu 16.04
- Firefox Version: 60.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: None.

### Actual behavior
When you click the container tab icon, the first container tab does not display its regular icon. It is rather a +, and the entry is highlighted as if the mouse is positioned over it. If the mouse is placed over that entry, the gray highlight is made slightly less gray. The only way to return the icon and color to what it should be is to click the blank space above. This problem appeared when I upgraded to Firefox 60. Tested with a clean profile with only the Multi-account containers addon.

### Expected behavior
When the container tab icon is clicked, all the containers should properly display their icons and not be highlighted. 

### Steps to reproduce
1. Click the container tab button.
2. See that the first entry has a + and is gray.

### Screenshots

Current, but incorrect behavior:
![screenshot from 2018-05-11 11-49-03](https://user-images.githubusercontent.com/5825551/39936970-4c489872-551c-11e8-986e-f5698b33f323.png)

Behavior is another entry is moused over:
![screenshot from 2018-05-11 13-06-13](https://user-images.githubusercontent.com/5825551/39936973-4fd9206a-551c-11e8-9b5c-7ce4af5e8067.png)

How it should look when the icon is clicked:
![screenshot from 2018-05-11 11-49-18](https://user-images.githubusercontent.com/5825551/39936977-5390023c-551c-11e8-84da-fd47b9848132.png)

**Comment by SoftVision-EmilPasca** [comment]
Hy @aibaraiduas, thanks for submitting this issue. However, this is a duplicate of https://github.com/mozilla/multi-account-containers/issues/1173
