### ISSUE TITLE
to be removed

### ISSUE THREAD

**Issue by ba0m** [mozilla/multi-account-containers#1210]
wrong post. sorry

**Comment by ba0m** [comment]
ie: ![](https://i.epvpimg.com/kI0Nfab.png)

**Comment by 3nv4r** [comment]
+1

**Comment by 3nv4r** [comment]
Anyone plan work on that one?

**Comment by 3nv4r** [comment]
Can't wait for this to be implemented... please provide some input .. Why can't we assign a domain to more than one container ?
