### ISSUE TITLE
[Feature Request] Make it simple to switch tabs (possibly in page action)

### ISSUE THREAD

**Issue by vhfmag** [mozilla/multi-account-containers#1211]
I have a container assigned to Twitter domains. If I open a Github link from there, the new tab is opened in the Twitter container, in which I'm not logged in to my Github account. As of now, the only way to move that tab to the default container is to copy and paste the url in a new tab. Maybe the Multi-Account Containers page action could allow switching containers?

I know that I could have opened the link in a different container by the context menu, but that's not my usual way to use the browser and maybe making switching easy could improve many people's experiences.

Any thoughts?

**Comment by reedhaffner** [comment]
You could create a "default" container (containing Github and others) and set Github to only open in that.

**Comment by benjamink** [comment]
Being able to convert the current tab to a container tab would be awesome.  I think that's what's being asked for - if not, I'd like to see my suggestion as well.  Not sure how you deal with all the existing cookies, etc. But converting an open tab to a specific container is a bit clunky (following the copy URL, open new container tab, paste URL method).

**Comment by vhfmag** [comment]
That's exactly what I wanted to propose. There are workarounds that work right now, such as opening the link in a different container to start with, switch containers manually, and assigning a default container for the domain (e.g. Github in the given example), but being able to easily switch containers would make some flows much more intuitive.

**Comment by benjamink** [comment]
I found this extension but it comes with a valuable warning that would apply just as much for this feature request: https://addons.mozilla.org/en-US/firefox/addon/switch-container/

That extension is adding the functionality requested here, I believe.

**Comment by vhfmag** [comment]
Turns out it has been previously decided that this feature won't be implemented, as stated on the [documentation page](https://github.com/mozilla/multi-account-containers/wiki/Moving-between-containers) cited on the above extension:

> Unfortunately the Containers extension won't allow moving between containers because of the privacy/security impact.
>
> We built Containers and also Lightbeam, to provide tools for people to see how much tracking there is on the internet.
>
> Moving one URL from one container to another has the ability to increase tracking across containers.

As such, I will close this issue.

As a note, though, I wonder how the [Facebook Container extension](https://github.com/mozilla/contain-facebook) handles that issue.
