### ISSUE TITLE
[Feature Request] Lost web sessions after a fast disable/enable multi-account-containers add-on

### ISSUE THREAD

**Issue by tvass** [mozilla/multi-account-containers#1212]
### Actual behavior
I lost all my sessions when I disable and enable back the add-on a few seconds later. 

### Expected behavior
Make web sessions survives a fast disable/enable multi-account-containers add-on.

### Steps to reproduce
1. Login to https://[.....].com
2. Disable add-on
3. Enable add-on
4. Go back to https://[.....].com to see session if lost.

**Comment by dannycolin** [comment]
Duplicate of #1236
