### ISSUE TITLE
[Feature Request] Scratch / temporary containers

### ISSUE THREAD

**Issue by altwohill** [mozilla/multi-account-containers#1216]
I love multi account containers and use them a lot.
I do wish it was possible to have a "scratch" container that destroys all its data once the last tab is closed. 
At the moment I open up a private window to accomplish this but it would be nice to have it in the same window as the rest of my tabs.

**Comment by falolaf** [comment]
How about:
https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/

**Comment by altwohill** [comment]
well, how about that? Thanks!
