### ISSUE TITLE
"Open in new container" does not work from a tab which has a default container rule.

### ISSUE THREAD

**Issue by 0xBUGSPRAY** [mozilla/multi-account-containers#1222]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: macOS High Sierra Version 10.13.3
- Firefox Version: Firefox Quantum 60.0.1 64 bit
- Other installed Add-ons + Version + Enabled/Disabled-Status: None

### Actual behavior
If a page loaded has a default container configured and remembered to always load in that container, then the "Open link in a new container tab" opens the link in the new tab in the original page's container rather than the explicitly specified container.

### Expected behavior
"Open link in new container tab" should open a link in a new tab with the specified container despite of what container the original page is associated with.

### Steps to reproduce
1. Set a default container for a website (used eg. is Google) and remember that preference by reloading and checking the remember box.
2. Open a webpage (used eg. is a Google search) in a tab where the website had been associated with default container.
3. Right click a link on the page -> open link in new container tab -> \<anything other than the default container for the original page\>
4. The new tab opens up in the default container for the original page rather than the explicitly specified container.

### Notes
..

**Comment by naoliden** [comment]
So apparently the answer is installing the Switch-Container Add-on? Can this be included among MAC features?
I know that MAC already has a "Reopen this site in..." function, but I can't make it so it closes the previous tab, it has the option in settings, but I don't know why it doesn't work on my PC.

**Comment by globalhuman** [comment]
How is it that this issue has:

- repeatedly been raised over the years
- accumulated interest and support
- no workaround provided 

and it's not been addressed? 

The behaviour is unintuitive and is a blocker for me to using this extension. 

I want to accomplish the following workflow:

1. Go to GitHub.com (work)
2. Open link with right click "Open in new container tab (personal)"
3. Navigate container that has been opened in my (personal) container

What currently happens:

1. Go to Github.com (work)
2. Open link with right click "Open in new container tab (personal)"
3. The above request is disregarded and it is opened in my (work) container

I currently use another browser to get the desired behaviour. 

Suggestion:

The setting `Always open in this container` is too literal. It should be `default open in this container`. The `default` could have a number of contexts/rules surrounding when it's activated. i.e.

1. new tabs
2. external links (opened from outside of browser)
3. link opened from another container
4. ??

**Comment by dannycolin** [comment]
Duplicate of #1442
