### ISSUE TITLE
Blank pop-up list when Firefox Color is activated.

### ISSUE THREAD

**Issue by vmoutoussamy** [mozilla/multi-account-containers#1223]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: MacOS High Sierra 10.13.4 
- Firefox Version: Nightly 62.0a1 (2018-06-07) (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
DNS Over HTTPS	1.0	true	httpdns@shield.mozilla.org
Firefox Multi-Account Containers	6.0.0	true	@testpilot-containers
Ghostery – Privacy Ad Blocker	8.1.2	true	firefox@ghostery.com
Switch Container	0.8	true	{c580e2d6-885a-4cb9-af49-59b3b48350e9}
Test Pilot	3.0.3vfd65300	true	@testpilot-addon
uBlock Origin	1.16.8	true	uBlock0@raymondhill.net
Firefox Color	1.0.1	false	FirefoxColor@mozilla.com

### Actual behavior
Blank pop-up list when Firefox Color is activated.

### Expected behavior
pop-up listing Container 

### Steps to reproduce
1. Activate Firefox Color (https://color.firefox.com/)
2. See the issue
3. Deactivate Firefox Color
4. No issue 

### Notes
It's easy to reproduce for me, whenever I activate the Firefox Color add-ons, the pop-up list will be blank. Deactivating Firefox Color immediately make the pop-up to list the available containers.

**Comment by SoftVision-EmilPasca** [comment]
Hi @vmoutoussamy, thanks for reporting this issue. However, I have not managed to reproduce it with the steps described above. After installing all the mentioned addons, when clicking on the "Multi Account Containers" toolbar icon, the Container list is properly displayed.

Can you please check the attached screen recording and let me know if I've omitted any step or if there's any additional step required to reproduce your issue?
Attached screen recording: https://tinyurl.com/y74vyshr

**Comment by vmoutoussamy** [comment]
Weirdly enough, I'm not able to reproduce the issue anymore... It was so easy in the first place... Anyway, sorry for the inconvenience, please close this issue.
