### ISSUE TITLE
All settings lost. How can I get them back?

### ISSUE THREAD

**Issue by dbolton** [mozilla/multi-account-containers#1228]
I was briefly using Firefox beta channel to get Firefox 61 early. When Firefox 61 came out I reinstalled the stable version of Firefox and lost all my settings for Multi-Account containers.

How do I get the settings back? I have complete backups of my Firefox profile folder.

**Comment by dbolton** [comment]
It looks like the settings are saved two places in the Firefox profile folder:
containers.json
browser-extension-data\@testpilot-containers\storage.js

The first contains the container names, icons, and colors
The second contains the list of sites that should open in each container

**Comment by TriMoon** [comment]
This info should be added to https://support.mozilla.org/en-US/kb/containers

**Comment by grahamperrin** [comment]
> This info should be added to [support.mozilla.org/en-US/kb/containers](https://support.mozilla.org/en-US/kb/containers)

@TriMoon hi, you can sign in there and discuss the page. There's also the option to edit. 

In parallel: #2030
