### ISSUE TITLE
no working with https://www.facebook.com/BugBounty/?hc_ref=ARQUtlBVA5tAXBbgnEinR2vC8BnOW3YqTuX92crNDV7loMPJZl0hxsomQTfKuugHwKg&fref=nf

### ISSUE THREAD

**Issue by paratopo** [mozilla/multi-account-containers#1230]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No:
- Are you using Firefox in a Private Window? Yes/No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No:
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce
1. ..
2. ..
3. ..

### Notes
..

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it.  If you don't feel the underlying issue has been resolved, feel free to comment with steps to reproduce, and I can reopen it.
