### ISSUE TITLE
Strange & unwanted behavior with `mobile.twitter.com`

### ISSUE THREAD

**Issue by crenwick** [mozilla/multi-account-containers#1237]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: 
No
- Are you using Firefox in a Private Window? Yes/No: 
No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: 
Yes
- Multi-Account Containers Version: 
6.0.0
- Operating System + Version: 
MacOS 10.12.6
- Firefox Version: 
62.0b10
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
https://github.com/crenwick/on-before-request-bug

### Actual behavior
Setting `mobile.twitter.com` to a "Always open in" a non-default container does not work. Additionally, it will make `mobile.twitter.com` not trigger the `browser.webRequest.onBeforeRequest` addons API for this add-on, and **other add-ons** installed on the FF profile.

### Expected behavior
Setting `mobile.twitter.com` to a "Always open in" a non-default container should open that chosen container when going to the URL `mobile.twitter.com`.

### Steps to reproduce
1. Set `mobile.twitter.com` to a "Always open in" a non-default container.
2. Open a new tab in the default container and go to `mobile.twitter.com`.
3. Note how this add-on did not switch away from the default container.
3. Download [this minimum add-on](https://github.com/crenwick/on-before-request-bug).
4. In `about:debugging#addons`, add that add-on manifest.json file and enter the debug mode.
5. Go to `mobile.twitter.com` and note how the console never logs from the `onBeforeRequest` function (but will for other URLs).

### Notes
- Uninstalling or disabling this multi-account-containers addon does not fix the bug for other addons.
- `mobile.twitter.com` is the only URL I've noticed that triggers this behavior, but are likely more.

**Comment by gowthaman-basuvaraj** [comment]
+1, yes twitter.com works correctly, only mobile.twitter.com is experiencing this behavior

**Comment by kendallcorner** [comment]
Hi. It looks like this is a service worker issue, and that has been fixed: #822  I'm going to close this issue.  If you don't feel the underlying issue has been resolved, feel free to comment with updated steps to reproduce, and I can reopen it.
