### ISSUE TITLE
Preserve container for addon opened tabs

### ISSUE THREAD

**Issue by r-gcc-65061** [mozilla/multi-account-containers#1246]
I'm not sure if this is an issue that should be submitted to the addon maintainer, but currently addons that operate by opening new tabs don't respect the container setting for the container tab it is called from. For example, $ADDON might take the current tab's url and send it to some web service, but the new tab it opens for it will be in a default, no container tab rather than preserving the container of the tab it was called from. Bookmarklets seem to not have this issue though.

**Comment by ChodaBoy** [comment]
Once example I ran into was addons that manage open tabs like MergeMarks which "merges all open tabs into one bookmark folder to be restored later". When you restore those tabs from the bookmarks via the addon, they are all opened in the default container and do not respect the original container.

**Comment by groovecoder** [comment]
Every add-on that uses the `tabs` API will need to [pass `cookieStoreId` param](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#Parameters) to create tabs in certain containers. This is not something we can do in this repo. Please file an issue with the add-on(s) you're using.
