### ISSUE TITLE
Always open specific domains in specific container

### ISSUE THREAD

**Issue by pixiekat** [mozilla/multi-account-containers#1247]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: Yes
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: macOS 10.13.5
- Firefox Version: Nightly 63.0a1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Right now you can open a site in a specific container and select "always open site in this container", which is fine. However when you have sites like Tumblr where each blog has their own subdomain, you end up having to do this for every Tumblr site ever. 

### Expected behavior
It would be nice if you can have additional options:

[ ] Always open site in this container
[ ] Always open entire domain in this container

Etc.

### Steps to reproduce
1. Open tumblr.com in a browser container. 
2. Select 'Always open in this container'
3. Try to follow a link to someblog.tumblr.com and it will open in whatever container you clicked from (or no container).

**Comment by kendallcorner** [comment]
Hi. This looks like a duplicate of #473. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.
