### ISSUE TITLE
Open in Container Tab not available for booksmarks

### ISSUE THREAD

**Issue by peterkronenberg** [mozilla/multi-account-containers#1250]
If I right-click on a link, I get the option to Open in Container Tab.  But I don't get this option if I right-click on a bookmark, either in the sidebar or the bookmarks toolbar.  Can we get this functionality?

**Comment by dannycolin** [comment]
FYI https://addons.mozilla.org/en-US/firefox/addon/open-bookmark-in-container-tab/

You might also be interested to follow the issue #323 for the progress on the feature you're asking for :).

**Comment by kendallcorner** [comment]
Yes, this looks like a duplicate of #323 (which we have just merged a solution for!). Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.
