### ISSUE TITLE
Question:  possible to view/edit explicit container assignment rules?

### ISSUE THREAD

**Issue by meeotch** [mozilla/multi-account-containers#1252]
Is it possible to view/edit the rules that result from my choices w.r.t. checking the "Always open in" and "Remember my decision" checkboxes?

The context is that I'm trying to force some google services (Voice, Contacts, Gmail) into a "Personal" container with a logged-in Google account, and others (Youtube & Search, including when I type something into the address bar) into a "No Google" container that's logged-out, so that Google can't get all up in my internet shiz and sell my history to the NSA.

This seems to work with voice.google.com and mail.google.com.  And by putting www.google.com into the No Google container by default, and then confirming this choice the first time I do an address-bar search, the search end of things does what I want.  

However, contacts.google.com doesn't seem to understand where to go, and just stays in whatever container I open it in.  I'd like to get a closer look at what's happening under the hood to try and figure out why it's not working.

**Comment by beroal** [comment]
“Always open in” checkboxes are shown after clicking the extension’s button → “Edit Containers” → a container → the pencil button. I have not found how to view “Remember my decision” checkboxes.

**Comment by justingarrick** [comment]
Certainly not ideal, but this seems to be editable in `<your Firefox profile dir>/browser-extension-data/@testpilot-containers/storage.js`

**Comment by meeotch** [comment]
Well, that seems to shed some light, thanks...  With the help of an online javascript beautifier, I was able to determine that contacts.google.com in fact adds a "www.google.com" rule to the plugin data.  Probably because the url resolves to www.google.com/contacts, whereas voice.google.com retains its prefix.

I guess I'll have to get used to duplicating/opening a tab of the appropriate container before going to contacts.google.com.  (Haven't yet experimented to see if the storage.js file allows for matching longer url's than just a single TLD.)

**Comment by andreapx** [comment]
Is the option to edit the URL going to be implemented?
I think that it's very useful. I've setup 89 containers last month and I don't know which site is where. I also need to move one website (since when I open gmail.com it loop betweekn 2 containers...ops!) but I can't (well, I'll try with the storage.js and a javascript beautifier)

**Comment by michaelblyons** [comment]
> Certainly not ideal, but this seems to be editable in `<your Firefox profile dir>/browser-extension-data/@testpilot-containers/storage.js`

I do not appear to have an `@testpilot-containers` folder there.

**Comment by kendallcorner** [comment]
I think the question was answered, so I'm going to close the issue, but feel free to vote(:+1:) on or add to the discussion on similar issues, such as #473 , #691, and #847.
