### ISSUE TITLE
discourse forums bypass container boundries

### ISSUE THREAD

**Issue by lukastribus** [mozilla/multi-account-containers#1253]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: Windows 10
- Firefox Version: 61.0.2 64bit
- Other installed Add-ons + Version + Enabled/Disabled-Status: None (fresh FF profile)

### Actual behavior
Discourse forums store informations about already read topics (somehow) and this makes it across container boundaries.

### Expected behavior

The information regarding already read topics is supposed to be contained within a container.

### Steps to reproduce

1. Go to a discourse forum (from the default container)
2. checkout a specific subforum (the [dev section of discourse.mozilla.org for example](https://discourse.mozilla.org/c/add-ons/development))
3. read a few different threads
4. open the specific subform in another container
5. topics we read earlier are already greyed out, because that information leaked through from the default (or another) container.

Can easily be reproduced with a fresh new firefox profile.

### Notes

I was unable to figure out how discourse stores the information about the already read topics. I have other issues with Multi Container and discourse forums as well (*once* it has been opened in the default container, assigning it to another container with `always open in <container>`  doesn't have any effect: opening it in a default container again will work, without multi container intervening) - but I assume the root cause is the same.

Other sites work just fine, I have this issue(s) with discourse only, which I'd imagine uses a particular fancy way of storing data in the browser.

**Comment by kendallcorner** [comment]
This appears to be Firefox marking these as visited links. The website should not be able to determine whether you have visited the links or not. Currently history is shared between containers. There are some issues open concerning this. If you would like to add your input, we recommend you vote (:+1:) or discuss on those issues (e.g. #47 ). Thanks!
