### ISSUE TITLE
Vulnerabilities in npm

### ISSUE THREAD

**Issue by hritvi** [mozilla/multi-account-containers#1261]
- Operating System + Version: Linux 18.04 LTS

### Actual behavior
While the initial set up run the following vulnerabilities are present in node
```
found 20 vulnerabilities (3 low, 14 moderate, 2 high, 1 critical)
run `npm audit fix` to fix them, or `npm audit` for details
```

### Expected behavior
No vulnerabilities should be present

### Steps to reproduce
1. Clone the repository
2. Run `npm install`

**Comment by twhite96** [comment]
As an Outreachy intern, I'll take this.

**Comment by twhite96** [comment]
Hmm. It seems the package `deploy-txp` has a dependency that has been audited as critical. Most of the vulnerabilities are attributed to this package. Is there another package similar to this that we can use to mitigate the number of vulnerabilities? 

https://www.npmjs.com/advisories/566

https://www.npmjs.com/advisories/663

**Comment by hritvi** [comment]
Hey @twhite96 I am currently working on this issue.
You are right, the most of the vulnerabilities are because of dependencies of the package `deploy-txt`. I don't this so replacing this package would be a good option. @groovecoder could you please help us a little here. Thanks :slightly_smiling_face:

**Comment by jonathanKingston** [comment]
It seems this is [maintained by a Mozilla member of staff](https://github.com/meandavejustice/deploy-txp). I can't remember if we still use this at all but @groovecoder would.

The solution might be to rip it out or fork the code and update it.

**Comment by groovecoder** [comment]
I think we can actually get rid of `deploy-txp` - we only used it when we were deploying the add-on to testpilot.firefox.com.

**Comment by twhite96** [comment]
Okay. I'll strip that one out.
