### ISSUE TITLE
Always open in default not working

### ISSUE THREAD

**Issue by Paarmita** [mozilla/multi-account-containers#1264]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: No
- Multi-Account Containers Version: 
- Operating System + Version: Linux Ubuntu 16.04
- Firefox Version: Firefox version 62.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: None

### Actual behavior
Always Open in Default checkbox not working. When we click on the checkbox there is no checkmark and nothing happens.

### Expected behavior
Shows checkmark and make the chosen container as default.

![button](https://user-images.githubusercontent.com/26546816/45861478-64dad680-bd8a-11e8-93b8-6746ca5f849b.png)

**Comment by ShivangiKakkar** [comment]
@Paarmita Maybe this is the desired behaviour. The checkbox works when you open a url in the container tab. But yeah, mentors would be able to confirm on this :)

**Comment by Paarmita** [comment]
@ShivangiKakkar It's not working in any of the cases, I tried this as well.

**Comment by Paarmita** [comment]
Yeah thanks :)  It worked now, there might be an error earlier

**Comment by juanibiapina** [comment]
It does not work for the `Default` container, only other containers.

**Comment by charlieegan3** [comment]
Can we reopen this? I'm still experiencing this issue when trying to make a site always use the default container.

**Comment by lhorace** [comment]
Hello there,

I think the intended behavior here is, the checkbox becomes available when you open the site !Default container.

**Comment by charlieegan3** [comment]
If that were the case, why does it show 'Always open in Default'?
![screenshot from 2019-03-05 16-41-02](https://user-images.githubusercontent.com/1774239/53821457-bb695500-3f65-11e9-87db-c7765421bad0.png)

**Comment by ShivangiKakkar** [comment]
@charlieegan3 @juanibiapina Hey! according to me, this is the desired behaviour anyhow if you open a tab it will open in default so if you wanna assign a particular tab it must be in some container otherwise it will anyhow open in default. Let me know if I am interpreting you wrong. :)

**Comment by charlieegan3** [comment]
So if I'm in a tab of `container A` then usually I want links I follow to also open in `container A`.

However, what do I do when I have a site like github where I have one account rather than multiple? I'd like them to always open in `container Default`.

Maybe there's another way to do this but my instinct is to attempt to set the github site to always `Default` container. Maybe there is no such think as the default container but the UI makes it appear as if there is one.

Either way, I'd like to have the option of always opening a given site in the Default container.

My screenshot above I think makes it clear what the desired action is - I click the checkbox next to `always open in Default` :wink:

**Comment by lhorace** [comment]
Totally get the gist here, the workaround would be to specify the container you want to open the link in via Open -> No Container.

**Comment by charlieegan3** [comment]
I think both of those features would be good too but they're slightly different.

* https://github.com/mozilla/multi-account-containers/issues/1318 is close but usually I want followed links to open in the same container. I'm looking for a site-by-site setting instead to override that (there's already a feature for this, but it doesn't work with the default container).
* https://github.com/mozilla/multi-account-containers/issues/1343 is different again as they don't seem to want to use the default container.

I think based on the checkbox appearing but being unusable for the default container that this is closer to a bug than a feature for me at least.

**Comment by lhorace** [comment]
>  there's already a feature for this, but it doesn't work with the default container.

Ideally one wouldn't want to use Default container at all, uses Temporary Container here. There's going to be a lot for and against on this particular issue. I feel like that would probably end up in a back pile and never see the light of day. That's my observation about this repository at least. This might not answer your question but have you tried https://addons.mozilla.org/en-US/firefox/addon/containerise/ ?

> I think based on the checkbox appearing but being unusable for the default container that this is closer to a bug than a feature for me at least.

I would suggest opening a new issue, as the title and OP's post seems to suggest something different at least to me. I would vote for it, not showing the option, or at least make it more obvious why the option is disabled. Would be ideal.

**Comment by charlieegan3** [comment]
I think this is the issue we need :wink: https://github.com/mozilla/multi-account-containers/issues/1194

**Comment by juanibiapina** [comment]
So at least the unusable checkbox should not appear.

**Comment by floriensk** [comment]
@Paarmita could we reopen this? The desired behaviour can only be achieved through extensions, though it is indeed a need.
