### ISSUE TITLE
Container not taking the size of the overflow-menu when added to it

### ISSUE THREAD

**Issue by yatri1609** [mozilla/multi-account-containers#1268]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Operating System + Version: Ubuntu 18.04
- Firefox Version: 62.0 (64-bit)

### Actual behavior
When multi-account-container is added to overflow menu it doesn't take the size of the menu.

### Expected behavior
It should adapt the actual size of the menu.

### Steps to reproduce
1. Add multi-account-container to overflow menu
2. Open multi-account-container

### Notes
This is the screenshot of the same
![screenshot from 2018-09-23 18-26-36](https://user-images.githubusercontent.com/34381723/45929618-e771ba80-bf71-11e8-88b4-2cf700150e4e.png)

**Comment by ShivangiKakkar** [comment]
I think this issue is duplicate of #766 :)

**Comment by yatri1609** [comment]
Yes but it is still unsolved ! And I have already asked @groovecoder to guide me. :)

**Comment by ShivangiKakkar** [comment]
@groovecoder @jonathanKingston I think this should be closed. It is a duplicate of #766 . Can I close this issue?

**Comment by jonathanKingston** [comment]
Thanks for the submission it is however a duplicate.
