### ISSUE TITLE
Sort Tab button not working

### ISSUE THREAD

**Issue by yatri1609** [mozilla/multi-account-containers#1269]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Operating System + Version: Ubuntu 18.04
- Firefox Version: 62.0 (64-bit)

### Actual behavior
On clicking Sort Tabs there is no response of the container.

### Expected behavior
The container must allow sorting of the different containers.

### Steps to reproduce
1. Open tabs under container
2. Click on Sort Tabs

### Notes
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/34381723/45942378-cce62280-bfff-11e8-98b1-dc70f8c5745f.gif)

**Comment by yatri1609** [comment]
@groovecoder I would like to take issues and improvements like this during my Outreachy internship period. But for now I would like to work on some issues like this and other where I can start my contributions to the project

**Comment by Paarmita** [comment]
@yatri1609 Working in my case. U can try opening 5 or more tabs with different containers.

**Comment by yatri1609** [comment]
Ohk let me test it once again

**Comment by yatri1609** [comment]
@Paarmita Which OS do you use? As it is still not working in my case

**Comment by Paarmita** [comment]
I'm testing in Linux Ubuntu.

**Comment by jonathanKingston** [comment]
Sorting applies to the containers:
Work, Personal,Work, Work
Would result in: Work, Work, Work, Personal

Is this not what is happening?

**Comment by ShivangiKakkar** [comment]
@jonathanKingston It is doing perfectly fine in MacOS. Not sure about Linux.

**Comment by yatri1609** [comment]
@jonathanKingston No that wasn't happening in Ubuntu 18.04

**Comment by Paarmita** [comment]
@jonathanKingston It's working fine for Ubuntu 16.04 as well.

**Comment by jonathanKingston** [comment]
Cool, I'm going to close this out unless I'm misunderstanding :) thanks
