### ISSUE TITLE
`always open in` checkbox on Nightly has no visual checkmark

### ISSUE THREAD

**Issue by escapewindow** [mozilla/multi-account-containers#1271]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: n/a, appears to have changed in Nightly
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: osx 10.13.6
- Firefox Version: Nightly 64.0a1 (2018-09-24) (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

```
Firefox Multi-Account Containers	6.0.0	true	@testpilot-containers
Forest: stay focused, be present	3.8.6	true	@forest-firefox-addon
LastPass: Free Password Manager	4.17.1.7	true	support@lastpass.com
Privacy Badger	2018.9.20	true	jid1-MnnxcxisBPnSXQ@jetpack
Switch Container	0.8	true	{c580e2d6-885a-4cb9-af49-59b3b48350e9}
Temporary Containers	0.90	true	{c607c8df-14a7-4f28-894f-29e8722976af}
Test Pilot	3.0.5vfed9863	true	@testpilot-addon
Tree Style Tab	2.5.4	true	treestyletab@piro.sakura.ne.jp
wxIF	0.2	true	{8b3ee44a-0805-4c2c-acef-15aab34fbd20}
```

### Actual behavior
`Always open in` has no check mark, even for sites that already have been set to always open in a container. It is also unclickable.

### Expected behavior
`Always open in` should be clickable and settable for a given tab and container. If a site has already opened in its preferred container, the checkbox should be clicked already.

### Steps to reproduce
1. Click on multi-account containers icon in the toolbar
2. Try to click on the `always open in` button

### Notes
Seems to be recent.

**Comment by lachlan-00** [comment]
I just tested this in windows 10 and the tick box works but doesn't change state visually.

**Comment by escapewindow** [comment]
My github tabs are now opening in the wrong container. I think this is because I unclicked the `always open in` checkbox and had no visual hint.

**Comment by jonathanKingston** [comment]
Hey @escapewindow thanks for the report!

Hey @ShivangiKakkar or @Paarmita would you be able to look into what is the cause of this.

Some questions that might help debug:
- Is it specific to this addon or is it reproducible on another more simplified addon?
- Is it specific to Nightly or does it happen on Firefox stable?
- Did a change get released to the addon recently(I haven't been on this project in a long time so unsure).

My hunch is the default styles changed within the browser popups and this caused the regressions, building the addon and trying a few things might help debug.

**Comment by ShivangiKakkar** [comment]
@jonathanKingston Would love to. :)

**Comment by ShivangiKakkar** [comment]
@jonathanKingston 
- I tried it on another simple addon, checkbox works fine in nightly. Thus it must be specific to multi-container addons.
- It is specific to Nightly. It doesn't happen on Firefox stable. In Firefox stable it asks for permission to open in the same container instead.
- No. It last released in near about February.

The question I had in my mind was if it's really an addon fix or a nightly platform related issue? If yes how do I run the current dev for multi containers on nightly, as `./node_modules/.bin/web-ext run -s src/` open the addon in the stable Firefox not in nightly?

**Comment by jonathanKingston** [comment]
`./node_modules/.bin/web-ext run -s src/ -f ~/location/nightly/etc` is a way to check Nightly only same for if you are building it yourself. I believe `npm run build` will give you a zip that about:debugging can then open also.

**Comment by mozfreddyb** [comment]
It took me a while to find the buttons to a) prevent the popup from closing when switching to the debugger and b) switch the Inspector to the popup.

I can confirm that the checkbox works and has the event listener attached as written in popup.js line 597. So the error must be where the popup is initialized. I see the function `setupAssignmentCheckbox()` in popup.js would contain the logic, but setting a breakpoint never triggers when opening the popup. Maybe it should be called someplace where it's not?

**Comment by jonathanKingston** [comment]
@ShivangiKakkar I'm seeing a console log withing the [browser toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox) for "Error: Invalid badge background color: "" ExtensionUtils.jsm "

This likely is preventing the rest of the popup code from finishing / loading. If we fix that it might just fix this issue automatically.

**Comment by jonathanKingston** [comment]
@ShivangiKakkar as far as I can tell the badge error I mentioned doesn't solve this. I filed a PR specific to just that.
