### ISSUE TITLE
All the tooltips hide behind the popup/menu after first hover

### ISSUE THREAD

**Issue by ShivangiKakkar** [mozilla/multi-account-containers#1273]
### Prerequisites:
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? No
- Are you using Firefox in a Private Window? No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: Mac OS (10.13.6)
- Firefox Version: 62.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: No

### Actual behaviour:
- The tooltip is not displayed whenever hovered except the first time.

### Expected behaviour:
- The respected tooltip should be displayed whenever hovered.

### Steps to reproduce:
1. Click on the `Multi-Account Container` addon.
2. Hover on the containers. The first time it will show the tooltip correctly.
3. After that, the tooltip is shown behind the popup/menu while hovering on the containers as well as their arrows(to view personal container). Even the `Sort Tab` is affected by this behaviour.
4. Now if you hover on the `Multi-Account Container` addon, there also the tooltip is shown behind the menu.
### Notes:
- It is reproducible only with full screen.
- Here is the gif with the issue:

![webp net-gifmaker](https://user-images.githubusercontent.com/35342019/46095761-f14a2680-c1da-11e8-8550-007b56e2bc1c.gif)

**Comment by ShivangiKakkar** [comment]
@groovecoder @bakulf @jonathanKingston This seems like a critical issue, what do you think might be causing this behaviour for the tooltips? 
I am also trying to find the same. Thanks.

**Comment by jonathanKingston** [comment]
@ShivangiKakkar I suspect this might be related to the autofocusing that happens then the tooltip is popped open (I'm not sure if we removed this code since Firefox now focuses into the frame).

I can't reproduce this on Linux or Mac Nightly 64. It does however look like a Firefox bug rather than an addon one.

**Comment by ShivangiKakkar** [comment]
@jonathanKingston I just tested it for Nightly 64, it did reproduce for me. Did you check this while being in full-screen mode?

**Comment by jonathanKingston** [comment]
I double checked and couldn't replicate on both devices. Are you using multiple screens on mac?

**Comment by ShivangiKakkar** [comment]
@jonathanKingston I didn't get `multiple screens`? But as shown in the gif above, It is reproducible for me now as well for both Nightly and stable Firefox.

**Comment by jonathanKingston** [comment]
As in multiple visual displays, a plugged in screen to a laptop for example. I'm struggling to reproduce at all. I'm using the latest mojave 10.14 though.

**Comment by grahamperrin** [comment]
Is this still an issue? 

From opening post <https://github.com/mozilla/multi-account-containers/issues/1273#issue-364123572>: 

> 2 Hover on the containers. The first time it will show the tooltip correctly.

After adding the extension to a refreshed profile, and completing the tour, I see no tooltip.

**Comment by dannycolin** [comment]
> After adding the extension to a refreshed profile, and completing the tour, I see no tooltip.

They seems to have been removed when the UI was revamped so we can close this.
