### ISSUE TITLE
Containers button is active in the first tab of private session

### ISSUE THREAD

**Issue by krobelus** [mozilla/multi-account-containers#1280]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? **No**
- Are you using Firefox in a Private Window? **Yes**
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? **Yes**
- Multi-Account Containers Version: **6.0.0**
- Operating System + Version: **Arch Linux**
- Firefox Version: **62.0.2** (same issue with nightly)
- Other installed Add-ons + Version + Enabled/Disabled-Status: **None**

### Actual behavior
The button for multi-account containers is enabled in the first tab of a new private window.
However, in new tabs in the same private window, it is disabled.

### Expected behavior
The button should probably be disabled throughout.

### Steps to reproduce
1. Start Firefox with a new profile
2. Install the Multi-Account Containers
3. Open a new private window
4. Press `Ctrl+.` or the button in the toolbar to see the containers menu

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed by PR #1512, so I'm going to close it.  If you don't feel the underlying issue has been resolved, feel free to comment with updated steps to reproduce, and I can reopen it.
