### ISSUE TITLE
Update addon homepage link

### ISSUE THREAD

**Issue by scheinercc** [mozilla/multi-account-containers#1286]
I wanted to report a problem by looking up the addon's homepage from the addons' detail view*. It is still linked to https://testpilot.firefox.com where "Show Past Experiments" > Container 'Feedback' just brought me to the questionare - which was not what I needed.
Only by going to AMO I found the link to Github.

I would recommend changing the home page to: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

*<img width="978" alt="image" src="https://user-images.githubusercontent.com/817856/47013433-da23a680-d192-11e8-965f-3487ec06dafb.png">

**Comment by jonathanKingston** [comment]
@groovecoder I can't find this URL anywhere, it's not in AMO or the addon code. Has this always been an issue?

**Comment by kendallcorner** [comment]
This appears to have been fixed, so I'm going to close it.
