### ISSUE TITLE
Feature Request: Open Sites Direct over Multi-Account-Containers

### ISSUE THREAD

**Issue by HassanMullah** [mozilla/multi-account-containers#1288]
Hello, there,

it would be very cool if you could add an option to the context menu. I would like to move the mouse over a link and see "open with multi-account-container" .... and then on with the different containers you have created. This would be faster than opening the multi-account container first and then opening the site.

**Comment by falolaf** [comment]
It is possible but not through M.A.C rather FF own implemenation. From FF62 I believe.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it.  If you don't feel the underlying issue has been resolved, feel free to comment with updated steps to reproduce, and I can reopen it.
