### ISSUE TITLE
[Meta] Is development of the extension dead?

### ISSUE THREAD

**Issue by kurobeats** [mozilla/multi-account-containers#1290]
First of all, this innovation is amazing. Mozilla are on the cusp of something awesome with this functionality but I'm wary committing time to modifying my workflow/s to allow day to day use of this add-on if it's a dead side project.

So essentially my question is, is this extension still being actively developed?

**Comment by yssmcl** [comment]
https://github.com/mozilla/multi-account-containers/issues/1259
