### ISSUE TITLE
It is possible to open Firefox with a selected container?

### ISSUE THREAD

**Issue by ema-pe** [mozilla/multi-account-containers#1301]
Hi, I have a question: is it possible to open Firefox via command line (like `firefox https://github.com`) with a specified container, for example `Shopping` or `Work` instead of default one?

**Comment by groovecoder** [comment]
I don't think this is possible. @jonathanKingston ?

**Comment by kendallcorner** [comment]
Hi. This looks like a duplicate of #365. Please vote (:+1:) or discuss on those issues so they are more likely to be completed. I'll close this, but feel free to reopen if you think it's a different issue.
