### ISSUE TITLE
Open new tab in current container or tie a window to a container

### ISSUE THREAD

**Issue by psoulos** [mozilla/multi-account-containers#1305]
There is one feature that prevents me switching to Firefox from Chrome. In Chrome, I use a window for Work and a window for Personal. I see two ways to accomplish this feature using Firefox Containers. 

1. If new tabs are opened by default in the current container, then I can maintain a window for different containers.
2. A feature to set a container for an entire window would be a solution similar to Chrome.

**Comment by falolaf** [comment]
And you need containers functionality for this? E.g. you need to be logged in to the same site with two different accounts?

**Comment by psoulos** [comment]
Yeah, there is an overlap in the websites that I use for work and personal (stackoverflow, gmail, etc)

**Comment by BigBlueHat** [comment]
@psoulos you probably want something like Firefox's Profile Manager:
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

The advantage Containers have is that you get all the shared themes, extensions, etc. across all your tabs regardless of the accounts you're using within the "Container tab."

The advantage of a fully separate Profile is that *everything* is separate: themes, extensions, cookies, accounts (including your Firefox sync account), etc.

Both approaches have their use. Profile Manager could use more promotion and a more obvious UX, though. Perhaps this group can tackle that next?

**Comment by psoulos** [comment]
Thank you @BigBlueHat, that is exactly what I was looking for! Profiles allow me to separate out my personal and work accounts, while containers allow me additional privacy for each account. Making Profile Manager more obvious in the UX could help bring people over to Firefox from Chrome and other browsers where profiles are given prominent exposure in the UI. Asking people to open Terminal to start the Profile Manager is going to turn a lot of people away.
