### ISSUE TITLE
"Open link in new container tab -> No container" doesn't work if the link is to the current site which has been set "always open in" current container

### ISSUE THREAD

**Issue by garywill** [mozilla/multi-account-containers#1312]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected?   no
- Are you using Firefox in a Private Window?  no
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"?  yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: Linux x64
- Firefox Version: 60
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior

"Open link in new container tab -> No container" doesn't work if the link is to the current site which has been set "always open in" current container. Link will be opened in current container.

### Expected behavior

Link is opened in a no-container tab.

### Steps to reproduce

1. Create a container C, and set `www.site.com` always open in my container C.
2. In container C tab `www.site.com`, there's a link to `www.site.com/blah`. Right click that link and choose "Open link in new container tab -> No container"
3. A new tab is created, asking if I want to open in `Current container` or `container C`. From the color I see this asking tab is already in `container C`. So whatever I click, it open in `container C`

### Notes

If the link is to other site or to `other.site.com` or to `site.com`, no problem happens.

**Comment by stoically** [comment]
This is working as expected. If you assign a website to "always open in" and "remember my choice", it should always open the site in that container, regardless of the "open in new container tab" selection.

**Comment by cubetastic33** [comment]
Wouldn't it be helpful if it were possible to just open it in some other container for once, even though the _default_ option is a different container? That is, by default it opens in a specific container, but it can be opened in something else if needed.

**Comment by garywill** [comment]
I found a workaround. Right-click the link and click "open in new window".
