### ISSUE TITLE
Container workflow change

### ISSUE THREAD

**Issue by mispp** [mozilla/multi-account-containers#1313]
I think workflow for containers should be changed. Every time i forget to open a container *before* entering the website. Here is a proposal to address this issue:

1a - enable 'move' from default container to custom container
----------------------------------------------------------------------------
Current workflow:

- open a normal tab
- visit facebook
- remember that facebook does not have its own container
- create a container
- open facebook again (2nd login)
- click 'always open facebook in this container'
- close container
- upon the next visit, click again 'i want to always open facebook in this container'.

Desired workflow:
- open a normal tab
- visit facebook
- remember that facebook does not have its own container
- click 'move' to its own container
- All subsequent steps would happen automatically:
  - create container named facebook.com
  - move current tab to that container (with active login)
  - enable to, without question, always open facebook in this container

Explanation: using default container in this scenario either way 'leaks' whatever is in there to facebook. We can just as easily enable the move which is advocated against on github pages by mozilla. Comment why moving is bad applies to <move from one container to the other>, but mentioned scenario, i think, was not considered.

1b - make an option for container extension to clean all cookies, logins and other data for only *default container*
----------------------------------------------------------------------------
Considering current workflow in point 1a, this would make sure that any tracking crap facebook would save in the default container would be deleted for next browser restart, so another 'forget' would not be picked up by facebook to be of the same person.

2 - Automatic creation of container for every visited domain.
----------------------------------------------------------------------------
Alternative for point 1a would be something like 'temporary containers' extension, but it would not be temporary and names for containers would be domain name.
Without user intervention, create container for every visited domain and always use this container by default when visiting that domain.
This would of course behave like 'temporary containers' extension when in private mode.

**Comment by hackel** [comment]
1 - Are you suggesting to blindly copy all cookies, local storage, etc. from the default container into the new custom container?  This seems risky.  The current "Reopen in Container" option makes more sense to me, but I would like to see a "New..." option that would prompt for a container name to create and reopen the current site in.

1b - Cookie AutoDelete supports clearing cookies automatically per-container.

2 - This is basically just first-party isolation. (Enable privacy.firstparty.isolate)

**Comment by mispp** [comment]
1 - no, not blindly copy everything, just things relevant for the visited domain. in other words, move the domain to a container only keeping login active. having an option to name the container is fine, but i'd prefer it to have a step less and just call the container based on the domain
whole point of this is to have logins (and tracking) separated. one login on one location = one container.

1b. - ok... 

2 - i thought that privacy.firstparty.isolate works differently. that you can in the same container open also some other domain? i.e. mix up facebook and google


maybe also automatically generated containers should be distinguished from manually created. with manually created a person might want to have several active logins in the same container, while the idea in point 1 would be that this cannot happen.

**Comment by hackel** [comment]
The first point is that you cannot predict how a particular site keeps track of login sessions.  Most still use cookies, some localStorage, etc.  You would have to copy everything for it to work reliably.  I agree it would be convenient to be able to do so, but I prefer privacy over convenience.

With first party isolation, there is a separate data store for each domain, so even if a site on google.com loads a script from facebook.com that sets a cookie, it won't be accessible on a facebook.com site, because the cookie stores are separate.  It sounds like this is exactly what you would achieve by having a one-container-per-domain configuration.  The ability to have multiple manually-created containers for one domain is definitely desirable, but there's already a separate issue for that.
