### ISSUE TITLE
Edit Container panel: "default" favicons render as missing images

### ISSUE THREAD

**Issue by groovecoder** [mozilla/multi-account-containers#1314]
See https://github.com/mozilla/multi-account-containers/pull/1292#issuecomment-444521831

**Comment by richa031** [comment]
i'm new to open source please help me find the details for this bug

**Comment by ryandrew14** [comment]
@groovecoder I can't reproduce this, has this been fixed elsewhere?

**Comment by ryandrew14** [comment]
Reproduced -- diving into this now.

**Comment by kendallcorner** [comment]
Hi there, I used the other place the favicons were working.

**Comment by kendallcorner** [comment]
That PR should close this.

**Comment by maxxcrawford** [comment]
Resolved by #1470
