### ISSUE TITLE
Two tabs created rather than one

### ISSUE THREAD

**Issue by deimidis** [mozilla/multi-account-containers#1319]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No:
- Are you using Firefox in a Private Window? Yes/No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No:
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
When I chose to open a new container tab, there's two new tabs open, one with the container and one withut container 

### Expected behavior
Only one tab is created

### Steps to reproduce
1. Click on plus sign and select a container
2. See that two tabs are created rather than one
3. ..

### Notes
..

**Comment by stoically** [comment]
Unfortunately I'm unable to reproduce this.

Please make sure that you don't have other Add-ons installed that might cause this behavior.
