### ISSUE TITLE
Panel does not open after update to Firefox 64

### ISSUE THREAD

**Issue by shankargopal** [mozilla/multi-account-containers#1321]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.0.1
- Operating System + Version: Debian Linux Testing, kernel 4.15.0-2-686-pae
- Firefox Version: 64.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:

 Name 	Version 	Enabled 
Cookie AutoDelete	2.2.0	true	
Firefox Multi-Account Containers	6.0.1	true	
Link Cleaner	1.5	true	
Privacy Badger	2018.12.17	true	
Textarea Cache	4.0.1	true	
Tridactyl	1.14.6	true	
uBlock Origin	1.17.4	true	
User-Agent Switcher	0.2.4	true	
Video DownloadHelper	7.3.5	true	
Bloody Vikings!	0.9.4	false	
Decentraleyes	2.0.8	false	
Temporary Containers	0.90	true	

### Actual behavior
When I click on the icon for MAC, I get a small empty box instead of the list of containers.  I'm attaching a screenshot.   The full list of containers is still visible in the Preferences.

![Screenshot of panel](https://user-images.githubusercontent.com/1425785/50382523-80c28100-06c7-11e9-9614-9e3e380908bd.jpg)

### Expected behavior
The normal list of containers.

### Steps to reproduce
1. Click on icon
2. Panel does not open

### Notes
As far as I can tell, this problem started after I updated Firefox to 64.0.

The Cookie AutoDelete panel also appears to have stopped working at the same time??

**Comment by shankargopal** [comment]
It seems to be completely erratic.  I restarted Firefox several times before posting the above bug - it made no difference.  Some time later, I re-enabled Temporary Containers, and that also made no difference (including after a restart).  But then after some time I restarted Firefox after closing it for some other work, and MAC started working normally again.  

This pattern - not working for some time, then working again - repeated itself again today.

**Comment by mcepl** [comment]
For me it was after upgrade to FF 66.*, but the results looks the same.

**Comment by stoically** [comment]
This also happens for me with other Add-on popups, so it seems that it's not MAC specific.

**Comment by dannycolin** [comment]
Closing since it was a bug in Firefox itself that should be fixed by now. If you still experience it, please file a bug report directly on bugzilla.mozilla.org.
