### ISSUE TITLE
Default start page does not always open in selected container

### ISSUE THREAD

**Issue by mothlyme** [mozilla/multi-account-containers#1322]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? No
- Are you using Firefox in a Private Window? No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? No
- Multi-Account Containers Version: 6.0.1
- Operating System + Version: Win10 1803
- Firefox Version: 64.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: Irrelevant

### Actual behavior
Start page sometimes (seems to be 50/50) opens in default container or the selected one

### Expected behavior
Start page opens in a custom set container

### Steps to reproduce
1. Set something as homepage
2. Put this page into a container (Always open in that container)
3. Restart firefox

### Notes
This seems to be an issue related to the time the plugin takes to start versus the page fully loading

**Comment by stoically** [comment]
Duplicate of https://github.com/mozilla/multi-account-containers/issues/474 - please track progress there, Thanks!
