### ISSUE TITLE
Default to Open New Tab in Container [New User]

### ISSUE THREAD

**Issue by w4rner** [mozilla/multi-account-containers#1326]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? No:
- Are you using Firefox in a Private Window? No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? No:
- Multi-Account Containers Version: 6.0.1
- Operating System + Version: Mac OS Mojave 10.14.2
- Firefox Version: 64.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
Name 	Version 	Enabled 	ID
Adblock Plus	3.4.2	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Bitly | Unleash the power of the link	3.0.4	true	extension@bitly.com
Boomerang for Gmail	1.2.9	true	{65e41d20-f092-41b7-bb83-c6e8a9ab0f57}
Cisco Webex Extension	1.1.0	true	ciscowebexstart1@cisco.com
DF YouTube (Distraction Free)	1.13.204	true	dfyoutube@example.com
Disable Facebook News Feed	1.6	true	{85cd2b5d-b3bd-4037-8335-ced996a95092}
Firefox Multi-Account Containers	6.0.1	true	@testpilot-containers
LastPass: Free Password Manager	4.21.0.4	true	support@lastpass.com
News Feed Eradicator for Facebook	1.2.1	true	@news-feed-eradicator
Print Friendly & PDF	1.3	true	ff-addon@printfriendly.com
RescueTime for Firefox	3.2.1	true	rescuetime_firefox@rescuetime.com
ReviewMeta.com Review Analyzer	2.5	true	FirefoxExtension@ReviewMeta.com
Side View	0.4.3710	true	side-view@mozilla.org
Sort Bookmarks	0.5	true	sort-bookmarks@heftig
Test Pilot	3.0.6vffecb95	true	@testpilot-addon

### Actual behavior
..
Currently when I open a New Tab it is not in a container. 
I want it to default to the * container

![image](https://user-images.githubusercontent.com/31451410/51049255-f74df280-1592-11e9-9342-110e8de5f070.png)
Can't click on Always Open in button.
### Expected behavior
..
I'm not sure I understand how it works, but is this what the Always Open In feature is for?

### Steps to reproduce
1. ..
2. ..
3. ..

### Notes
..
Want to improve on posting these issues. Please give me feedback. 
1). Copy & Paste other extensions: how to just get names?
2). Should I remove the HTML <!-- style comments?

**Comment by groovecoder** [comment]
I think this is a dupe of https://github.com/mozilla/multi-account-containers/issues/356 - vote and comment there please.
