### ISSUE TITLE
Searches via search/URL bar open results in wrong container

### ISSUE THREAD

**Issue by possiblyhuman** [mozilla/multi-account-containers#1330]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: **NO**
- Are you using Firefox in a Private Window? Yes/No: **NO**
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: **YES**
- Multi-Account Containers Version: **6.1.0**
- Operating System + Version: **Windows 10 Pro 64bit Version 10.0.17134 Build 17134**
- Firefox Version: **64.0.2 64bit**
- Other installed Add-ons + Version + Enabled/Disabled-Status:
BetterTTV	7.0	true	firefox@betterttv.net
Dark Background and Light Text	0.6.10	true	jid1-QoFqdK4qzUfGWQ@jetpack
Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
HTTPS Everywhere	2019.1.7	true	https-everywhere-eff@eff.org
IMGoogle	2.3	true	igoogle@eros.man
NoScript	10.2.1	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Old Reddit Redirect	1.1.2	true	{9063c2e9-e07c-4c2c-9646-cfe7ca8d0498}
Privacy Badger	2018.12.17	true	jid1-MnnxcxisBPnSXQ@jetpack
Reddit Enhancement Suite	5.14.3	true	jid1-xUfzOsOFlzSOXg@jetpack
uBlock Origin	1.18.0	true	uBlock0@raymondhill.net
View Image	2.1.1	true	{287dcf75-bec6-4eec-b4f6-71948a2eea29}
Violentmonkey	2.10.1	true	{aecec67f-0d10-4fa7-b7c7-609a2db280cf}
Zoom Page WE	13.2	true	zoompage-we@DW-dev
Auto Reload Tab	0.5	false	{0ed335eb-9779-4d7f-b9d8-7ec2e96a1f43}
Panel View for Google™ Translate	0.4.0	false	jid0-fbHwsGfb6kJyq2hj65KnbGte3yT@jetpack
S3.Translator	6.19	false	s3google@translator
Temporary Containers	0.90	false	{c607c8df-14a7-4f28-894f-29e8722976af}
Video DownloadHelper	7.3.5	false	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
WX Download Status Bar	1.9.2	false	{a1c84bb7-d5fc-4906-90b4-965e520b29bf}

### Actual behavior
I have my search provider (startpage.com) defaulted to always open in its own separate container. However, doing a search via the search bar or URL bar opens startpage.com in the current tab, even when the current tab is not in the startpage.com container.

### Expected behavior
A search via the search bar or URL bar should only open the startpage.com results in the current tab if that tab is in the startpage.com container, otherwise it should open it in a new startpage.com container tab.

### Steps to reproduce
1. Set startpage.com as default search provider.
2. Add startpage.com to a container (by opening a container tab, loading startpage.com in it and ticking "always open in..." in the multi account containers extension menu.
3. Make it so startpage.com always opens in the above container (by attempting to open it in a different (or no) container, which will cause a warning where you can then select to always force it into the above container)
4. Open a tab in a container other than the startpage.com container (or no container).
5. Do a search via the search bar or URL bar.
6. The search results should open in the current tab, even though that tab is not in the correct container for startpage.com.

### Notes
Not tested with other search providers.

### Edit
Just noticed that the same issue also occurs when performing a search via the right-click context menu item "Search startpage for '...'" when selecting text.

**Comment by stoically** [comment]
This is working as expected. If you assign a website to always open in a container, exactly that should happen, regardless of where you're coming from.

[Containers with Transitions](https://addons.mozilla.org/firefox/addon/containers-with-transitions/) might achieve what you're looking for.

**Comment by possiblyhuman** [comment]
@stoically

> If you assign a website to always open in a container, exactly that should happen, regardless of where you're coming from.

I set startpage.com to always open in its own container, but the above steps make it so it doesn't open in its own container.

This sounds contrary to what you said should happen.

**Comment by stoically** [comment]
In your STR you wrote `The search results should open in the current tab, even though that tab is not in the correct container for startpage.com.` - which I understood as you want it to open in the current container instead of the assigned container.

If you instead meant, that in this case the startpage results are not opened in the assigned container, then I'm unfortunately unable to reproduce - it works as expected for me (assign www.startpage.com to a container, opened new tab in no container, did search using addressbar, opened results in assigned container).

**Comment by possiblyhuman** [comment]
> If you instead meant, that in this case the startpage results are not opened in the assigned container, then I'm unfortunately unable to reproduce - it works as expected for me (assign www.startpage.com to a container, opened new tab in no container, did search using addressbar, opened results in assigned container).

Yeah, I wrote in the STR what actually happens. The Expected Behaviour is what should have happened.

But, if it's working for you, I don't know. I'm still getting the issue my end. Maybe some edge-case with my setup.

I changed stuff to work-around the issue, so it's no longer a problem for me anyway.

Cheers for checking though.
