### ISSUE TITLE
First tab in each new session always opens in the default container

### ISSUE THREAD

**Issue by GonePh1shing** [mozilla/multi-account-containers#1340]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a greyed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Windows 10 Enterprise N 2016 LTSB (Build 14393)
- Firefox Version: 65.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:
None - I have tried this on a fresh install of Firefox.

### Actual behaviour
The first tab of each session _always_ opens in the default tab. This seems to happen regardless of what site is initially opened or what container it is set to open in. All subsequently created tabs open as expected.

### Expected behaviour
All tabs should always open in the containers they are set to.

### Steps to reproduce
1. Create a container (e.g. 'Google') and set a site to always open in that container (e.g. https://www.youtube.com).
2. Create a desktop shortcut for the above site.
3. Close Firefox.
4. Open the created shortcut.
5. The website will now open with in the default tab.

### Notes
I'm not sure if this is expected behaviour, or if it's a current limitation. Besides just being inconvenient, this issue poses a potential security/privacy threat depending on what site is being opened and the current container configuration.

**Comment by stoically** [comment]
Duplicate of https://github.com/mozilla/multi-account-containers/issues/474 - please vote there. Thanks!
