### ISSUE TITLE
How to automatically have two of the same website open in different containers ?

### ISSUE THREAD

**Issue by ng4ever** [mozilla/multi-account-containers#1342]
Basically I have two different login information for the same website.

**Comment by D219** [comment]
One solution would have been #854, but it was closed

**Comment by nba2** [comment]
+1, me and others in #854 would very much appreciate this feature. I just switched from firefox to chrome and it was very easy to have one personal profile and one profile for school that were totally separate. Multi-account containers is very much lacking in comparison.

**Comment by stoically** [comment]
Duplicate of https://github.com/mozilla/multi-account-containers/issues/1171 - please vote there. Thanks!
