### ISSUE TITLE
Containers triggering false-positive Content Security Policy violations

### ISSUE THREAD

**Issue by kevinrobinson** [mozilla/multi-account-containers#1344]
### Context
Firefox: 65.0.1 (64-bit)
Firefox Multi-Account Containers: Version 6.1.0, Last updated: 24 Jan 2019

### Actual behavior
Firefox detects Content Security violations for a site and sends violations to that site's `report-uri` when there are no such violations.  This appears to be coming from something that the Firefox Multi-Account container is doing, since these violations disappear when I disable the extension.

Here's a minimal test case ([repl.it source](https://repl.it/@kevinrobinson/SpanishCompetitiveAutoexec), [deployment](https://spanishcompetitiveautoexec.kevinrobinson.repl.co/)).  This uses the recommended starting point CSP from https://content-security-policy.com/ with a placeholder `report-uri` to demonstrate the problem.

You can see Firefox thinks this page has a CSP violation, and that it is because of an inline script at line 1 column 1:
<img width="1061" alt="screen shot 2019-02-15 at 1 30 41 pm" src="https://user-images.githubusercontent.com/1056957/52876743-19a0d600-3126-11e9-8e4f-195c163cd858.png">
<img width="798" alt="screen shot 2019-02-15 at 1 30 37 pm" src="https://user-images.githubusercontent.com/1056957/52876744-19a0d600-3126-11e9-816d-58c75c72097f.png">

but there is no script there, this is the source from the [repl.it test case](https://repl.it/@kevinrobinson/SpanishCompetitiveAutoexec):
```
<!DOCTYPE html>
<html lang="en">
  <head><title>demo</title></head>
  <body><div>oh noes! Firefox containers trigger CSP violations?</body>
</html>
```

### Expected behavior
No CSP violations.

### Notes
From reading this Firefox [blog post from November 2017](https://blog.mozilla.org/addons/2017/11/20/extensions-in-firefox-58/) in "Improved Content Security Policy (CSP) Handling" it seems like maybe this work started but wasn't finished?  This [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) ("[meta] Page CSP should not apply to content inserted by content scripts.") seems relevant, and is still open.

I can't quite tell whether the problem is in this extension, or in Firefox itself.  Either way, if this is now an officially supported Mozilla extension, maybe someone here can help direct me where to work on this or learn more.

Thanks for reading! and apologies if this is the wrong place to be sharing  :)

**Comment by stoically** [comment]
Thanks for the report. This can't unfortunately be solved by the MAC Add-on - please consider opening a [bugzilla](http://bugzilla.mozilla.org/) issue instead.
