### ISSUE TITLE
Convert default container to named container

### ISSUE THREAD

**Issue by roothorick** [mozilla/multi-account-containers#1346]
Relevantly different from the "transfer stuff between containers" outlined in the FAQ; I'd like the ability to convert the default container into a named container, creating a new, "empty" default container its place. All tabs, cookies, history etc. would carry over to the named container and nothing left behind. This shouldn't run afoul of privacy concerns as nothing is ever actually shared between containers.

**Comment by kapad** [comment]
Either this, or simply allow setting certain websites to open by default in the "no container" (i.e. the default container) which is currently not possible. 

I very often open links from email (a Google container) that I want to open in the "default" container. 

(An example use case for me would be if any one were to comment on this issue. I would get an email from GitHub that I would open in Gmail in my "Google" container. Now by just clicking this link, it would open the issue in a new tab in the same container but I'm logged into GitHub in the default container. Now I want to be able to either set that Firefox should always open `github.com` links in the default container, which right now, isn't possible. 

Also, it's simply very tedious to create and manage a "default" container by hand. (i.e. create a container named "default" and then open all sites in this container).

**Comment by lhorace** [comment]
A lot of people are sometimes asking for same feature spread across different issues, why I find often, these issues stay stale and never actioned. It would be nice if someone could combine relevant parts into one issue so people can vote for them.

As for OPs post, I am not sure why developers should implement this? Why not simply create a container, assign the site to it, and be done with it? Why convert 'default' container into a named container? Are you suggesting instances where, 'Oooooh, I like to open this site in a named container and copy over the cookies over'? Seems like a convenience feature?

> I very often open links from email (a Google container) that I want to open in the "default" container.

Does Right click -> Open in container -> No container work for you?

**Comment by kapad** [comment]
> Does Right click -> Open in container -> No container work for you?
Yes. This works, but it's breaking my usual workflow. 

**Consider the following example** 
> - I've logged in to Github in the default container, i.e. No container. 
> - I'm logged into Gmail in the "Google" container. 
> - I get an email with an update on an issue. I want to see the entire issue, and therefore click the link. 
> - This opens the link in the "Google" container where I am not logged into Github. 
> - I either have to right click the issue link and manually select it to open in the "No container" every time I click on this link. 
> - If I want to save myself from this manual right click every time, then I need to create a Github container. 
> - Only then am I able to make this container the default for `github.com` links. 
> - Now, I also have a container called "Facebook", where I am logged into Facebook, Instagram, etc. 
> - I have also set `facebook.com` links to open in this container by default. 
> - Now, when I get an email from facebook with some update about one of my posts, I can just click this link and have it open in the "Facebook" container and not the "Google" container. 
> - What I want to be able to do, is get the same experience of opening a link in a **specific** container for sites that I want to always open in the **default** container. 
> - That definitely seems like a valid and common use case that a lot of users would face. 

> "Oooooh, I like to open this site in a named container and copy over the cookies over"
Oooooh, I don't think you even understood my use case. See the example, if you still don't get it, or think it's not a common use case, leave me a comment here.

**Comment by lhorace** [comment]
> Oooooh, I don't think you even understood my use case.

That's why I asked to get a better understanding, the point wasn't to undermined your point but to bring light that there plenty of similar issues on this topic. Just so you know:

This a comment from groovecoder, one of the developers on the project:
> No, this is now an add-on on AMO. But it's not receiving active development - (this repository) bug-fixes and maintenance patches only.
https://github.com/mozilla/multi-account-containers/issues/339#issuecomment-434534754.

I would surmise, you'll have better luck submitting a PR or having someone work on this. However it would be nice collating every issue _that_ seem to be related together for users to vote for them.

I don't use default containers at all here, I group my work differently, so I don't have use case here. IIRC, point in case, there is another feature request that's currently open asking for sites that are not bound to any particular containers by default open in 'No container'.

Lastly, you request, at least to me is different from what the OP's requesting? Which to me, turn a 'unamed container' to a 'named' container. Somewhat, 'clone' or duplicate. Though, at least for me, I'm not convinced though it would be a convenient feature to those who wants it.

**Comment by kapad** [comment]
> Lastly, you request, at least to me is different from what the OP's requesting? Which to me, turn a 'unamed container' to a 'named' container. Somewhat, 'clone' or duplicate. Though, at least for me, I'm not convinced though it would be a convenient feature to those who wants it.

Yes. You're right on this. I didn't realize it when I was posting. 

> That's why I asked to get a better understanding, the point wasn't to undermined your point but to bring light that there plenty of similar issues on this topic. Just so you know:

My bad for misunderstanding your intent.

**Comment by PabloGrok** [comment]
I'd like to leave my 2 cents here too. I find this containers extension really nice but sometimes frustrating. My need is to have EVERY website open by default in a named container (my main "online personality") not in a "default" container with no name, no color and no icon, so I guess this is a +1 to roothorick's original post.

**Comment by stoically** [comment]
Transferring storage from one container to another would need Firefox support - but since this has a high risk of compromising privacy, it is out of scope for MAC.

As for the always open all websites in a specific container, the Containers with Transitions Add-on might be able to achieve that.
