### ISSUE TITLE
Tab history stack lost when navigating to a container

### ISSUE THREAD

**Issue by sgtsquiggs** [mozilla/multi-account-containers#1348]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Ubuntu 16.04
- Firefox Version: 63.0.3 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
1Password X – Password Manager	1.14.1	true	{d634138d-c276-4fc8-924b-40a0ea21d284}
AdGuard AdBlocker	2.10.17	true	adguardadblocker@adguard.com
Amazon Container	1.0.1	true	@contain-amzn
DuckDuckGo Privacy Essentials	2019.1.31	true	jid1-ZAdIEUB7XOzOJw@jetpack
Facebook Container	1.4.2	true	@contain-facebook
Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
Google Container	1.3.4	true	@contain-google
Reddit Container	1.0.2	true	@containing-reddit
Reddit Enhancement Suite	5.14.5	true	jid1-xUfzOsOFlzSOXg@jetpack
Smart Amazon Smile	1.1	true	{9e0e0b12-7910-49da-b44b-1a2f9110d61e}

### Actual behavior
Click a link that takes me to reddit or amazon (separate configured containers)
Can't click back button; all tab history is lost

### Expected behavior
Click a link that takes me to reddit or amazon (separate configured containers)
Back button still works

### Notes
Could the container filter what is available (in history) to the DOM instead of removing the entire history.

**Comment by stoically** [comment]
This is due to how MAC works under the hood. When navigating to an assigned website a *new* tab, with new history is created. You still have the history in the old tab though.

To support this, something like https://github.com/mozilla/multi-account-containers/issues/1029 would be needed.
