### ISSUE TITLE
[question] MAC has landed in the Beta release of Firefox, should bugs not be reporting against Bugzilla?

### ISSUE THREAD

**Issue by lhorace** [mozilla/multi-account-containers#1353]
Hello everyone,

Now that MAC has landed in Beta, somewhat official, and issues are pilling up and not receiving any attention. Are developers time now focused on release, if so, is Github still the spot to be reporting issues?

Regards

**Comment by falolaf** [comment]
So, MAC will be part of FF soon? Where can I read more about that?

**Comment by lhorace** [comment]
Nothing official 'till release, since it's in Beta and Beta has pre-release features. The overriding assumption here, it's not really a question of if but when? I don't know the track record of Firefox Beta (iron out bugs before) release, if any or all features make it to release (not pulled out at the last minute).

The comment from groovecoder:
> No, this is now an add-on on AMO. But it's not receiving active development - (this repository) bug-fixes and maintenance patches only.

https://github.com/mozilla/multi-account-containers/issues/339#issuecomment-434534754

**Comment by stoically** [comment]
AFAIK MAC will not be pre-installed with Firefox - so MAC related bugs should still be filed here; though container-feature (contextualIdentities) specific bugs belong on bugzilla.
