### ISSUE TITLE
The development tools Debugger tab ignores container session to load resources

### ISSUE THREAD

**Issue by ite-klass** [mozilla/multi-account-containers#1356]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Windows 10 x64
- Firefox Version: 65.0.2

### Actual behavior
Opening the JavaScript debugger, opening the current page file seems to load the resource anew and disregarding the container session - instead using the non-containered normal session.

### Expected behavior
The displayed page source is the one visible, using the container session.

### Steps to reproduce
1. Open webpage that depends on a session value
2. Open webpage in container
3. Open development tools -> Debugger -> page
4. The page source will be the one from the non-container session instead of the containered visible page

**Comment by stoically** [comment]
This is not something that can be fixed in the Add-on. You might want to report this to [bugzilla](http://bugzilla.mozilla.org/).

**Comment by ite-klass** [comment]
I have no tech insight into why it should be there rather than here, so my argument/ticket would be weak. So I won’t do that.
