### ISSUE TITLE
When using "Reopen in container" from tab, "Firefox Multi-Account Containers" sometimes is missing from the context menu

### ISSUE THREAD

**Issue by JobLeonard** [mozilla/multi-account-containers#1358]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: KDE Neon, GIT Stable
- Firefox Version: 67.0b1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

| Extension | Version |
| --- | --- |
| Block Site | 0.1.9 |
| Clean Links | 3.2.5 |
| Container Tabs Sidebar | 0.0.4 |
| Decentraleyes | 2.0.10 |
| Desktop Wikipedia | 0.1 |
| DjVu.js Viewer | 0.2.4.3 |
| Download all Images | 0.5.7 |
| DuckDuckGo Hide Unwanted Results | 0.7 |
| Extension for Gmail Basic HTML View | 2.0 |
| Extension source viewer | 1.6.10 |
| File Icon for GitHub, GitLab and Bitbucket | 0.8.1 |
| Firefox Color | 2.1.2 |
| Firefox Multi-Account Containers | 6.1.0 |
| Forget that page | 1.6.0 |
| Fx Color (github) | 1.0.1 |
| Gecko Profiler | 0.29 |
| Google Search Filter | 1.0.10 |
| Google search link fix | 1.6.7 |
| Happy Right-Click | 1.1.0 |
| image-save | 1.2 |
| Let's get color blind | 1.0.0 |
| Link Cleaner | 1.5 |
| Live Reload | 1.6.0 |
| Neat URL | 4.1.5 |
| New Tab Override | 14.2.0 |
| Notes by Firefox | 4.3.3 |
| Octotree | 2.5.6 |
| Old Reddit Redirect | 1.1.2 |
| pinterest-guest | 2.1 |
| Plasma Integration | 1.4 |
| Reddit Enhancement Suite | 5.14.5 |
| Redirect AMP to HTML | 2.0.0 |
| Refined GitHub | 19.3.10.1842 |
| Render Whitespace on GitHub | 1.3.12 |
| Side View | 0.4.3710 |
| Stop AutoPlay Next for YouTube™ | 0.1.7 |
| Stylus | 1.5.2 |
| Theater Mode for YouTube™ (large player view) | 0.1.3 |
| Trackerless Magnet URI | 1.0.2 |
| Twitter View Original Images | 0.1.8.100 |
| uBlock Origin | 1.18.4 |
| uMatrix | 1.3.16 |
| Universal Bypass | 10.6 |
| Unpaywall | 3.78 |
| Wayback machine website | 1.2.1 |
| Youtube Audio | 0.0.2.2 |
| YouTube Classic | 1.3 |

### Actual behavior
- "Firefox Multi-Account Container" is missing from right-click context menu (the one seen by right-clicking on the website itself, not the one you get by clicking on the tab) of the page reopened in a container. This behavior is persistent *until* said page is refreshed a second time. After doing so, the "Firefox Multi-Account Container" is visible in the context menu, and any other website re-opened through right-clicking the tab will show the extension from the first reload.

### Expected behavior
- "Firefox Multi-Account Container" is immediately visible

### Steps to reproduce

1. open a website
2. right-click on tab, select "Reopen in Container"
3. select a container
4. open new tab
5. right-click on the document body to open the context menu

**Comment by stoically** [comment]
Can't unfortunately reproduce the issue. The context menu is always present after reopening for me.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it.  If you don't feel the underlying issue has been resolved, feel free to comment with updated steps to reproduce, and I can reopen it.
