### ISSUE TITLE
"Always open in" is always disabled 

### ISSUE THREAD

**Issue by trollepierre** [mozilla/multi-account-containers#1360]
The "Always open in [container]" checkbox always appear to be disabled. Even when I open a window of the good container. Firefox 65.0.2

<img width="315" alt="Capture d’écran 2019-03-18 à 19 13 18" src="https://user-images.githubusercontent.com/8363334/54553330-3db83700-49b2-11e9-9102-750ed46e00d4.png">

**Comment by promeneur** [comment]
opensuse 15.0
Firefox 66.0.2
Multi-account containers 6.1.0

i confirm this. thus nothing is recorded

**Comment by trollepierre** [comment]
however it's been one week since I don't have this problem. But I don't know what I did to fix it...

**Comment by promeneur** [comment]
there is no bug but a bad understanding of how to use this extension.

**Comment by stoically** [comment]
This is expected behavior since it's not possible to assign "new tabs" to a container. You can only assign websites to containers, no internal Firefox pages.
