### ISSUE TITLE
Opening in assigned container url-decodes parameters

### ISSUE THREAD

**Issue by Rob--W** [mozilla/multi-account-containers#1361]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1535643 for the full report and STR.

I think that the issue is caused by the `decodeURIComponent` call here:
https://github.com/mozilla/multi-account-containers/blob/99db19279225664f943df7c873e01c355c875b26/src/js/confirm-page.js#L3

The parameter is set at:
https://github.com/mozilla/multi-account-containers/blob/c2f2d69ba1685a74335837ec86a0896779729a2f/src/js/background/assignManager.js#L426

The URLSearchParams API (`new URL(...).searchParams`) already decodes the parameter, so the extra `decodeURIComponent` call results in double-decoding.

**Comment by kbenson** [comment]
As a very simple way to test this bug, if you have a google container that requests you switch when accessing google.com URLs, and to a Ctrl-k search for "at&t", after authorizing the switch to the google container you'll find your search is for "at".

The full chain looks like this:
1) Ctrl-k search for at&t and redirected to container chainge confirm page with URL moz-extension://bd774d98-6895-4a38-a343-f40686fefbf4/confirm-page.html?url=https%3A//www.google.com/search%3Fclient%3Dfirefox-b-1-d%26q%3Dat%2526t&cookieStoreId=firefox-container-1

2) On authorizing the container switch, you are sent to the following URL https://www.google.com/search?client=firefox-b-1-d&q=at&t

Note that q=at&t is not the same as q=at%26t (which is what google shows when you manually search there)

Rob--W likely identified the location this is happening, but I figured a fairly easy way to test it would be useful.

**Comment by Rob--W** [comment]
@stoically This bug has steps to reproduce (last comment) and a description that is a hint towards the simple fix (original report).

Could you slap the good-first-bug label on this issue?

**Comment by kendallcorner** [comment]
@maxxcrawford I'm working on this one.  Currently testing.

@Rob--W it works for this one example. Any pointers on testing this? Just find a site that uses a lot of %s and other characters in their urls?

**Comment by maxxcrawford** [comment]
@kendallcorner Assigned. Thanks!

**Comment by Rob--W** [comment]
@kendallcorner I wanted to reply to https://github.com/mozilla/multi-account-containers/issues/1361#issuecomment-542365390 , but noticed that you've already found a test case, created a patch and got it merged.

Thanks for the patch :)

**Comment by Rob--W** [comment]
PS. Next time you submit a patch, add `Fixes #1361` to the pull request. Then Github will automatically close the linked issue when the PR is merged. For more information, see https://help.github.com/en/articles/closing-issues-using-keywords
