### ISSUE TITLE
[Feature request] list websites associated with container

### ISSUE THREAD

**Issue by ricab** [mozilla/multi-account-containers#1363]
Sometimes I want to "always open a website in a container", but choose the container with this other related website. Or I want to check what sites are potentially going to be exposed to this each other in a container.

For that I would have to see what sites I assigned to which containers. I could not find a way to do that today.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-162)

**Comment by lhorace** [comment]
Hey there,

> Or I want to check what sites are potentially going to be exposed to this each other in a container.

This could be checked now, albeit obscure, `click on MAC -> Edit Container -> Pencil of the container`, from here you should see a list of assigned sites.

> For that I would have to see what sites I assigned to which containers. I could not find a way to do that today.

That would be nice, though, may not be human readable, you could have a look at the json file for the time being?

**Comment by ricab** [comment]
Ah I see, thanks. Where can I find the json file?

**Comment by lhorace** [comment]
`.mozilla/firefox/<profilename>.default/containers.json` and `.mozilla/firefox/<profilename>.default/browser-extension-data/@testpilot-containers/storage.js`. The latter is difficult to read.

**Comment by ricab** [comment]
OK, I have `storage.js.migrated` here, which does not seem to have the current session's info yet. But I could indeed see some sites associated with container id's in the second file and then lookup the container ids->names in the first. `clang-format` made it easier to read the jsons :) 

I think I'll stick with the first method you proposed. Thank you!

**Comment by stoically** [comment]
Starting with Firefox 66 the Add-on storage is automatically migrated to IndexedDB (hence the `storage.js.migrated` file). It's now located in `.mozilla/<profile>/storage/default/moz-extension+++<Internal UUID>^userContextId=4294967295`. The `Internal UUID` for a given Add-on can be obtained from `about:debugging`. A way to get more or less human readable local storage would be:
- Navigate to `about:debugging`
- Tick `Enable add-on debugging`
- Click on `Debug` under the Add-on name
- Confirm the dialog
- In the `Console` type `browser.storage.local.get().then(console.log)`
- Check the returned `Object`

**Comment by grahamperrin** [comment]
![image](https://user-images.githubusercontent.com/192271/115923260-e086ed80-a475-11eb-9560-3cb3cdbaf059.png)

**Comment by Steve-Z** [comment]
> ![image](https://user-images.githubusercontent.com/192271/115923260-e086ed80-a475-11eb-9560-3cb3cdbaf059.png)

What is this? How did you do that?

**Comment by achernyakevich-sc** [comment]
@Steve-Z, It looks that this picture exposes screen that could be accessed by: click to MAC button on toolbar -> in opened UI click `Manage Containers` -> then click to your container (in your case it looks like it should be `Shopping` container) -> in opened UI click `Manage Sites List...`.

@ricab So it looks that feature is already implemented. Maybe you could close the issue?

**Comment by dannycolin** [comment]
Previous comment gave the solution so closing.
