### ISSUE TITLE
CLI interface to open link in specific container

### ISSUE THREAD

**Issue by christophgysin** [mozilla/multi-account-containers#1366]
I would like to have a way to be able to open a link from the commandline in a specifc container. E.g.:

```bash
$ firefox --new-tab --container=work <url>
```
Is there a way something like this could be implemented?

I'm happy to contribute if someone can point me in the right direction what is needed to achieve this.

**Comment by stoically** [comment]
Duplicate of https://github.com/mozilla/multi-account-containers/issues/365 - please vote there. Thanks!

**Comment by QuantumGrizzly** [comment]
In the meantime, you can use the extension honsiorovskyi/open-url-in-container
