### ISSUE TITLE
[Feature request] Addon seperation

### ISSUE THREAD

**Issue by Leptopoda** [mozilla/multi-account-containers#1370]
Is there a way to seperate addons too?
I would like to use different addons in different containers. Or in my banking container I want every unencryptet traffic blocked (https everywhere) but in my normal container I don't want this.

so is there a way to have different settings of the addons in the different containers??

**Comment by groovecoder** [comment]
This is an upstream bug for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1365019

**Comment by Leptopoda** [comment]
so I can close this issue??

**Comment by ReporterX** [comment]
> 
> 
> so I can close this issue??

You don't have to.

FYI, you may create different profiles to achieve this.
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by alexanderadam** [comment]
This is probably also related to #309

**Comment by dannycolin** [comment]
Duplicates of #1167
