### ISSUE TITLE
[Feature request] Sort tabs with less steps

### ISSUE THREAD

**Issue by piroor** [mozilla/multi-account-containers#1373]
Currently "Sort Tabs" command moves all tabs always, even if they don't need to be moved:
https://github.com/mozilla/multi-account-containers/blob/6f4d3c43274701e8c166f3ed80e4d453860fd31d/src/js/background/backgroundLogic.js#L278-L286

 * This operation produces too much tab moves. When there are too many tabs (for example, over 1000+) it may take much time.
 * It scrambles tabs unexpectedly and unnecessarily. It is critically dangerous on some kinds of addons like Tree Style Tab. 

So, instead only minimum tabs should be moved based on the algorithm of "diff". Actually [Tree Style Tab addon does that](https://github.com/piroor/treestyletab/blob/ce805bdfdd00d700400d98f17b57f4679de7c3ee/webextensions/background/tabs-move.js#L336). TST uses a [diff library ported from Python](https://github.com/piroor/treestyletab/blob/master/webextensions/common/diff.js), but there are more alternatives, for example:

* https://github.com/kpdecker/jsdiff
* https://github.com/jhchen/fast-diff
* https://johnresig.com/projects/javascript-diff-algorithm/

How about such an improvement?

**Comment by lhorace** [comment]
Two things, if you are willing, submit a PR and have the community vote. The latter might not be necessary. I would urge you to tap one of the developers to get them to review it. Right now, from what I understand, developers won't be available to work on MAC till near the end of the year.

**Comment by piroor** [comment]
OK, I've created a PR to implement this.
