### ISSUE TITLE
Container Preference Synchronisation

### ISSUE THREAD

**Issue by srlennon** [mozilla/multi-account-containers#1381]
Would it be possible to have your preferences for containers synchronised across all devices using Firefox. For example I setup a number of websites to always use certain containers (Personal, Work, Banking) when they open and I would like these preferences to sync across devices so I don't have to manage them all in multiple places.

**Comment by groovecoder** [comment]
Sounds like a dupe of https://github.com/mozilla/multi-account-containers/issues/339. Upvote & comment there.

**Comment by srlennon** [comment]
My bad, my search for whatever reason failed to find open issue 339. #339 covers this and more.
