### ISSUE TITLE
[Feature Request] Cotainer Window

### ISSUE THREAD

**Issue by Toldry** [mozilla/multi-account-containers#1383]
Opening an entire window of container tabs, such that when opening a new tab from this window (for example by pressing the shortcut `CTRL+T`), the new tab is automatically assigned to the same container as the source tab

**Comment by WorldsEndless** [comment]
This would be very nice. IIRC, there was a separate plugin that offered this but without the benefit of tabs. This is essentially the Firefox Profile functionality.

**Comment by stoically** [comment]
Closing as duplicate of https://github.com/mozilla/multi-account-containers/issues/943 - please vote there. Thanks!
