### ISSUE TITLE
History is still visible in default, which was searched in containers, why ?

### ISSUE THREAD

**Issue by NavdeepD2** [mozilla/multi-account-containers#1386]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: **No**
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: **Yes**
- Multi-Account Containers Version: **6.1.0**
- Operating System + Version: **Ubuntu 16.04 LTS**
- Firefox Version: **Quantum 66.0.3**
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Container search history is visible in default tab

### Expected behavior
Container history should remain in container 

### Steps to reproduce
1. Open a container - go to Google -> Search something different which is not searched before.
2. Now open default tab, Go to History, that search is there.

**Comment by NavdeepD2** [comment]
Anyone ????

**Comment by stoically** [comment]
History isn't aware of containers yet.

Platform bug is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1283320

Marking as duplicate of https://github.com/mozilla/multi-account-containers/issues/1233
