### ISSUE TITLE
After hiding all container tabs in a window, showing them opens them in the current window

### ISSUE THREAD

**Issue by groovecoder** [mozilla/multi-account-containers#139]
STR:

1. Move all container tabs into a new window
2. Click "Hide these container tabs" in the tab listing panel
3. Click "Show these container tabs" in the tab listing panel

Expected results:

The container tabs should re-open in a separate window

Actual results:

The container tabs open in the existing/active window

**Comment by bakulf** [comment]
why do you expect that? It makes sense to me to have the tabs opened in the current window. If you want to move them, you can do it with 1 additional click.

**Comment by johngruen** [comment]
Optimal would be to restore them into a separate window. Not a blocker.

**Comment by TanviHacks** [comment]
This is working as designed.
