### ISSUE TITLE
Extension is considered "legacy"

### ISSUE THREAD

**Issue by Jugale** [mozilla/multi-account-containers#1391]
Today, both Firefox Quantum and Firefox Developer Edition disabled this extension:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/2460248/57174190-13e1a380-6e7e-11e9-8c69-89c0635ce901.png">

The "More Information" link goes to the page http://mzl.la/1J7Lcsp
It seems that this extension needs to be signed in order for it to be available again? I attempted to re-install the extension but got an error saying "Download failed. Please check your connection." (I definitely have connection)

Template Info:
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? No
- Are you using Firefox in a Private Window? No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? No... can't see this setting
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: macOS 10.14.4
- Firefox Version: Quantum 66.0.3 and Developer Edition 67.0b16
- Other installed Add-ons + Version + Enabled/Disabled-Status: Other addons also suddenly showing as legacy

**Comment by MikuAuahDark** [comment]
Can confirm. Firefox just show warning that the addon is disabled a few minutes ago as of writing.

This should be high priority issue, I don't want to lose all cookies in the container.

**Comment by calvinbay** [comment]
Same prob here just happen today >>> add-on could not be verified for use in Firefox and has been disabled.

**Comment by MikuAuahDark** [comment]
It seems to happen on all extensions that was previously developed for Test Pilot. Which means, Firefox Side View and Firefox Color also affected.

**Comment by Mhynlo** [comment]
Looks like the Firefox team is tracking the issue here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by subinraju90** [comment]
Hope it gets resolved soon

**Comment by demoklion** [comment]
Here's a temporary workaround:
>Unsigned extensions can be installed in Developer Edition, Nightly, and ESR versions of Firefox, after toggling the xpinstall.signatures.required preference in about:config. 

[From mozilla's website](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution)

**Comment by stoically** [comment]
This is due to an expired certificate in Firefox itself. As stated by @Mhynlo, please follow https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 to track progress.
