### ISSUE TITLE
config lost after mozilla's armagadd-on-2.0 debacle

### ISSUE THREAD

**Issue by tleveille** [mozilla/multi-account-containers#1392]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? No
- Are you using Firefox in a Private Window? No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Fedora 30 x86_64
- Firefox Version: 66.0.3
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Following mozilla bug 1548973 related to the add-ons signing certificates expiration the addon was disabled automatically. I decided to work around this by disabling the signature verification ( toggling xpinstall.signatures.required to false in about:config ). Now the multi-account-containers shows up again but I lost all my config. The only available containers are the 4 default ones.

### Expected behavior
Having access to all my custom setup containers

### Steps to reproduce
See actual behavior

### Notes
Probably related to a bug when the extension is disabled regardless of the reason why it is disabled.

**Comment by stoically** [comment]
Sorry about your containers.

Duplicate of #864
