### ISSUE TITLE
Lost the add-on after firefox update!

### ISSUE THREAD

**Issue by 11MAJ11** [mozilla/multi-account-containers#1393]
Hi

after my Firefox got updated, the container add-on became obsolete and unsupported.

Now I lost all of my containers that I can't live without.

What to do now?

**Comment by stoically** [comment]
This is due to an expired certificate in Firefox itself. Please follow https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 to track progress.

**Comment by tigny** [comment]
indeed. a lot of add-ons are "unsupported" currently...

**Comment by 11MAJ11** [comment]
> 
> 
> indeed. a lot of add-ons are "unsupported" currently...

Why do many add-ons become incompatible after a firefox update? 

I tried switching to chrome only because of this.

**Comment by tigny** [comment]
There is no need to switch to Ggl Chrm:
"Certificate issue causing add-ons to be disabled or fail to install:
We rolled-out a fix for release, beta and nightly users on Desktop. The fix will be automatically applied in the background within the next few hours, you don’t need to take active steps.
For more information, please see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/  "

**Comment by 11MAJ11** [comment]
Hi,

Thank god, containers are back, but I lost their data completely, is there a way to store my container data and bak it up whenever I want? 

Thank
