### ISSUE TITLE
Container Extension Disappeared

### ISSUE THREAD

**Issue by binearyfar** [mozilla/multi-account-containers#1396]
I've been using multi-account containers and today it suddenly disappeared while I was actively using it. I tried re-installing and it says it "Download failed..." My connection is working, so what's the issue?
![Screen Shot 2019-05-04 at 1 37 48 PM](https://user-images.githubusercontent.com/50273461/57182810-f0b0f700-6e71-11e9-812e-95eefedb3aa9.png)

**Comment by stoically** [comment]
This is due to an expired certificate in Firefox itself. Please follow https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 to track progress.
