### ISSUE TITLE
Cert expiration issue affecting this and other add-ons

### ISSUE THREAD

**Issue by jpitts** [mozilla/multi-account-containers#1397]
Multi-Account Containers is removed from my browser, very likely related to [an issue being widely discussed](https://www.engadget.com/2019/05/03/firefox-extension-add-on-cert/). The fix isn't yet restoring the Multi-Account Containers in my updated Firefox v66.0.3, as of 11am PST.

![image](https://user-images.githubusercontent.com/509756/57183085-9ce7e300-6e5c-11e9-93ca-69c6638f5a93.png)

When I follow the "more information" link however I get something unrelated to the cert expiration. Screen shot from [Mozilla notification about Add-on signing](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct):

![image](https://user-images.githubusercontent.com/509756/57183072-7033cb80-6e5c-11e9-8efb-f78c473b4046.png)

**Comment by aplatypus** [comment]
This issue has affected plug-ins across the board.  It is an extremely crippling of my workflow.  On a Sunday with no WARNING and not ameliorating work-arounds.

For example it MUST be allowed for me the User to enable such a known, reliable plugin for 30 days or something.  And re-enable the plugin again after 30 days if the issue has not been fixed.

Several items that have been disabled are security related.  Like multi-account containers.  

Mozilla broke my internet security.

**Comment by cody42** [comment]
Mozilla has published a fix, but manual steps are neccessary to apply ist as fast as possible: See https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by jpitts** [comment]
This is resolved with the Firefox v66.0.4 update.
