### ISSUE TITLE
"Always Open In [Container]" does not work with photos.google.com

### ISSUE THREAD

**Issue by hub2git** [mozilla/multi-account-containers#1400]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No 
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: No
- Multi-Account Containers Version: 6.10
- Operating System + Version: Linux Mint 19.1 Cinnamon 64-bit
- Firefox Version: 66.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:

```
ADB Helper	0.12.1	true	adbhelper@mozilla.org
AutoPinTab	1.1.0	true	autopintab__coolsoft.ita@gmail.com
Bananatag Email Tracking	4.2.3	true	{c3f5a962-2f7c-4834-8809-c574b05b5dd4}
Dark Background and Light Text	0.6.10	true	jid1-QoFqdK4qzUfGWQ@jetpack
Diigo Web Collector - Capture and Annotate	6.0.0.4	true	{fc2b8f80-d9a5-4f51-8076-7c7ce3c67ee3}
Facebook™ Seen Blocker	0.1.5	true	jid0-AcfdPqSA2Ugt2vdJh6Kj7IiOp5W@jetpack
hotfix-update-xpi-intermediate	1.0.2	true	hotfix-update-xpi-intermediate@mozilla.com
HTTPS Everywhere	2019.5.2.1	true	https-everywhere@eff.org
Privacy Badger	2019.2.19	true	jid1-MnnxcxisBPnSXQ@jetpack
Reddit Enhancement Suite	5.14.5	true	jid1-xUfzOsOFlzSOXg@jetpack
Stylish - Custom themes for any website	3.1.8	true	{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}
Tree Style Tab	3.0.10	true	treestyletab@piro.sakura.ne.jp
uBlock Origin	1.18.16	true	uBlock0@raymondhill.net
View Image	2.1.1	true	{287dcf75-bec6-4eec-b4f6-71948a2eea29}
Violentmonkey	2.10.4	true	{aecec67f-0d10-4fa7-b7c7-609a2db280cf}
Windscribe VPN	2.4.3	true	@windscribeff
```

### Actual behavior
Photos.google.com opens in the default (non-container) tab

### Expected behavior
I expect photos.google.com to open up in ContainerX, because I've selected ContainerX to always open photos.google.com

### Steps to reproduce
Steps 1 to 7 are preperatory steps
1. Click on Multi-Account Containers button on the toolbar
2. Choose a container. (Let's call it _ContainerX_ in this issue)
3. In the new ContainerX tab, go to photos.google.com
4. Sign into your google account
5. Click the Multi-Account Containers button on the toolbar again
6. It should say something like
> Current tab
> Photos - Google Photos
> [] Always open in ContainerX
7. Tick the checkbox

8. Create a new tab (Ctrl-T in my linux computer)
9. Go to photos.google.com

### Notes
I don't have this problem with other sites. For example, hangouts.google.com and voice.google.com correctly open up  in _ContainerZ_.  Bing.com correctly opens in _ContainerY_. It's just photos.google.com that is the problem.

**Comment by stoically** [comment]
That's because the domain in question uses ServiceWorkers, which doesn't work with assignments.

Duplicate of https://github.com/mozilla/multi-account-containers/issues/822

**Comment by hub2git** [comment]
> That's because the domain in question uses ServiceWorkers, which doesn't work with assignments.
> 
> Duplicate of #822

https://github.com/mozilla/multi-account-containers/issues/822#issuecomment-452068677 seems to fix the problem.
