### ISSUE TITLE
My user containers have all disappeared after firefox update... HELP !!

### ISSUE THREAD

**Issue by FreeWF** [mozilla/multi-account-containers#1402]
My user containers have all disappeared after firefox update !!
I had about 20 containers with more than 300 Links that were hours and hours of research.
I absolutely need to restore them. Can you help me ? It's just a nightmare...
Thanks...

**Comment by FreeWF** [comment]
PS: the add-on did not appeared after restart, so after reading some informations, I let firefox make study. Few hours after, the add-on appeared but all the user containers had all disappeared. Everything empty. How to restore everything ? Where those informations are stored ?

**Comment by psylenced** [comment]
https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/

> If add-ons that use Containers functionality (such as Multi-Account Containers and Facebook Container) were disabled as part of this problem, any lost site data or custom configurations for those add-ons will not be recovered by this release. Users may need to set them up and login again in about:addons (Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1549204 ). 

Basically - due to Firefox's expired certificate error - the container data is lost and unrecoverable.

**Comment by matthewadie** [comment]
This happened to me as well, and now I have to re-setup several containers on 5 different machines.  I love Firefox and I live the Multi-Account Containers, but there really needs to be a way to sync between machines and make backups.

**Comment by caltheon** [comment]
Same issue on all my computers.  At least I can stop searching for an answer on how to fix, this is one giant screw-up for Firefox and for this extension

**Comment by FreeWF** [comment]
At least, please give me a solution to recover it manually, where the list of the links were saved, I can maybe recover with a deleted file recover software. This is a disaster...

**Comment by groovecoder** [comment]
This was caused by a larger issue with all add-ons, described here:

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

A release was made yesterday to fix the download + install issue:

https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/

To address the underlying issue of data loss when container add-ons are disabled or un-installed, we have both a long-standing GitHub issue in this repo:

https://github.com/mozilla/multi-account-containers/issues/1236

And a corresponding bug in bugzilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1549204

Please upvote and/or comment there so we can consolidate all the work in this area.

**Comment by JakobGSvendsen** [comment]
crazy to auto roll on an update that breaks large amounts of user data. Time to recosider using firefox again.

**Comment by mgajda** [comment]
I just clicked "refresh and update" button in Firefox 84.0.2 and the same issue occured, so I infer that Firefox team may want to test against data loss events more thoroughly.

**Comment by tuchang** [comment]
I have the same issue. Actually, it has happened since long time ago. However, today I need it more than ever. It is still broken.

**Comment by itdcmy** [comment]
Looks like the bug is back again. 
This has just happened to me when I updated to FF 98.0

**Comment by tochinet** [comment]
Not even sure it did update, after a computer restart, pfeeew, all gone. I didn't even know that was possible. FUCK

**Comment by achernyakevich-sc** [comment]
I'm not sure it is related to MAC... I have seen symptoms similar to what you described one time after my daughter updated Firefox. And it was not related to MAC. It happen this way:

- after installing update or right before installing update Firefox displayed proposal something like "Would you like to speedup your browsing by making clean install during update".
- she didn't know what does it mean and didn't pay enough attention to read details (though she is 20 years old) and pressed "yes".
- as result Firefox was restarted, updated and it used completely clean Firefox profile - looks like all add-ons were reset to default state.

Maybe something like this happen with your installation. What I didn't do but potentially could help you - check all available Firefox profiles in the home directory and check what is currently used. Maybe there is other one that was earlier used by you before it happen. If so then you will need just to switch Firefox to use the correct one.

**Comment by jonlm** [comment]
One thing I recommend is having your containers synced to your FF account. This can be enabled in the container extension prefs. I do this anyway so that they sync between my different computers, but I think it also means they would be recovered if you ran into this bug.

**Comment by merwok** [comment]
FWIW I now install session recovery extensions in all browsers, after losing too many tabs a few times.

**Comment by jonlm** [comment]
@merwok Are there any session recovery extensions that restore the set of saved containers and their settings? I'm not aware of any.

**Comment by ianreppel** [comment]
This still happens on Firefox 151 in 2026, unfortunately.
