### ISSUE TITLE
Clicking on container name, when offered to open site in assigned container, has no effect

### ISSUE THREAD

**Issue by ppayne** [mozilla/multi-account-containers#1403]
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? No:
- Are you using Firefox in a Private Window? No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes:
- Multi-Account Containers Version: 6.0.1
- Operating System + Version: Microsoft Windows v6.1.7601
- Firefox Version: 66.0b6
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
When the "Open this site in your assigned container?" message appears a blue button will appear that says "Open in XXXX Container". Clicking anywhere in this button will open the site in the XXXX container. However clicking on XXXX (the container name) will have no effect, the click is ignored.

### Expected behavior
Clicking anywhere in the button should open the site, including the text of the container name.

### Notes
Affected object might be dfn with class "container-name".

**Comment by ppayne** [comment]
May be related to #1350, also similar to #1365.

**Comment by jonathanKingston** [comment]
Yup this looks like a duplicate, thanks for raising though. I will try and get a release out soon.
