### ISSUE TITLE
View * Container arrow missing after Firefox Certificate issue

### ISSUE THREAD

**Issue by rpedrica** [mozilla/multi-account-containers#1404]
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Slackware Linux -current (kernel 4.19.36, gcc 9.1.0)
- Firefox Version: 60.6.2esr (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Extensions
Name 	Version 	Enabled 	ID
Adblock Plus - free ad blocker	3.5.2	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Country Flags & IP Whois	0.2.9	true	{802a552e-13d1-4683-a40a-1e5325fba4bb}
Firefox Lightbeam	2.1.0	true	jid1-F9UJ2thwoAm5gQ@jetpack
Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
Google Translator for Firefox	3.0.3.3	true	translator@zoli.bod
Mailvelope	3.1.0	true	jid1-AQqSMBYb0a8ADg@jetpack
Netcraft Extension	1.13.1	true	{0e10f3d7-07f6-4f12-97b9-9b27e07139a5}
Search by Image	1.19.1	true	{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}
To Google Translate	3.9	true	jid1-93WyvpgvxzGATw@jetpack
Video DownloadHelper	7.3.5	true	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
Bitwarden - Free Password Manager	1.39.3	false	{446900e4-71c2-419f-a6a7-df9c091e268b}
KeePassXC-Browser	1.4.3	false	keepassxc-browser@keepassxc.org
Tab Groups	2.1.4	false	tabgroups@quicksaver

### Actual behavior

The right arrow which provides Show this Container is missing from some container groups, after the 60.6.2esr update to fix the broken certificate issue in Firefox.

### Expected behavior

Normally, one will click on the Multi-Account Containers icon on the toolbar, then click the right-arrow to the right of the container group you want to open, and select Show This Container

### Steps to reproduce
1. Click Multi-Account Containers icon in toolbar
2. Click arrow to right of container group you want to open
3. Select Show this Container

### Notes
![multi-account-cont](https://user-images.githubusercontent.com/1016286/57277657-e75ba080-70a4-11e9-8b80-748e130d297f.png)

**Comment by grahamperrin** [comment]
Realistically, is this still an issue?

**Comment by rpedrica** [comment]
Apologies I had forgot all about this - it's been resolved for a long time already.
