### ISSUE TITLE
Clash of Keybinding with 1Password

### ISSUE THREAD

**Issue by kilasuit** [mozilla/multi-account-containers#1406]
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Win 10 - 1903
- Firefox Version:  66.0.4
- Other installed Add-ons + Version + Enabled/Disabled-Status: : 1Password X - 1.14.3

### Actual behavior
Inability to use Keyboard blindings for 1Password as FF Multi Account Containers uses same Key Bunding

### Expected behavior
To be able to use 1Password Key Bindings alongside FF Multi Account Containers

### Steps to reproduce
1.Install 1Password
2.visit site
3. try use Crtl + period keybinding

**Comment by stoically** [comment]
You can manage shortcuts for Add-ons in Firefox directly. Open the Add-on Manager (Ctrl+Shift+A), select "Extensions", click the cog top right and select "Manage Extension Shortcuts".
