### ISSUE TITLE
When using "Reopen in container X" it will still open in container Y 

### ISSUE THREAD

**Issue by vinzent** [mozilla/multi-account-containers#1410]
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Fedora 30
- Firefox Version: 66.0.4
- Other installed Add-ons + Version + Enabled/Disabled-Status:
hotfix-update-xpi-intermediate	1.0.3 true

### Actual behavior

Click on "Reopen in container X" still opens in "Container Y" if "Always open in container Y" is activated

### Expected behavior

Click on "Reopen in container X" opens in "Container X" even "Always open in container Y" is activated

### Steps to reproduce

* Activate "Work" container
* Open https://www.mozilla.org/
* Tick "Always open in Work container"
* Close tab
* Open new tab, goto https://www.mozilla.org/
* Tick "Remember my decision for this site", click "Open in Work Container"
* Right-click to tab, select "Reopen in container -> Personal"
* New tab opens with Work container

### Notes

My use case is  to force $chat-tool to my personal container and have the ability to start in another container to use the same $chat-tool with my work profile.

It used to work for me until recently. But I'm not able to reproduce the behaviour I had. So I suspect it only worked for me by chance.

**Comment by lhorace** [comment]
I think the behaviour you describing is intended behaviour? You want to _always want it to open in work_ which negates _Reopen in personal_

**Comment by vinzent** [comment]
But if I explicitly select "open in container X" I expect it to be openend in the selected container and not in the one that was selected as the default container. 

I was using this feature for few weeks now and the latest update made it stop working. 

Tried with 6.0.0 - but same issue here. 

Can't find the 6.0.1 version to try.

**Comment by lhorace** [comment]
I think what you want is a feature request because it changes of behaviour, but for now, don't select _always_ open in work container.

**Comment by vinzent** [comment]
funny thing, can't reproduce the old behaviour I. downgraded to 66.0.2 and 6.0.1 but no luck. So it worked for me as I expected it just by some unknown circumstances.

So I think I can workaround my personal issue by not ticking "Remember my decision for this site", so I will prevent the page from being opened in an wrong container but still being able to override the default.

**Comment by ndarville** [comment]
I have this error when Instagram is set to the Facebook container. Force-opening in another container doesn’t work, and the auto-open setting is unchecked from the domain.

**Comment by AFlowOfCode** [comment]
I agree that there should be a simple way to temporarily override "always open in x container", and that "reopen in container" is a logical solution for that. There are sites that 999 out of 1000 times I want to open in the assigned container, and I love being able to do that, but I don't want to have to mess with extension configuration to be able to open it up in a different way every so often.

**Comment by sivaraam** [comment]
I also face this issue. I seem to have chosen "Always open in x container" for some websites. How am I supposed to revert that? I can't find a way to turn it off now. 🤔

**Comment by kendallcorner** [comment]
@sivaraam  you can turn it off by unchecking and rechecking the 'always open in...' box. Now it will ask every time, or if you just want it off altogether, you can just uncheck the box.

**Comment by sivaraam** [comment]
Thanks for the tip @kendallcorner! I was initially unable to revert the preference as I couldn't figure out how to uncheck the "Always open in x container" box for the sites which I had enabled it long time ago. Now, I realise that the box is in the plug-in window. It took me a long time to realise this as I forgot that multi-account-containers was a plug-in and not a built-in feature of the browser. Thanks for the great plug-in! :slightly_smiling_face:
