### ISSUE TITLE
After Manual Disablement and re-enable, Multi-account Containers ceased to open sites in their containers

### ISSUE THREAD

**Issue by StellarGreg** [mozilla/multi-account-containers#1413]
Hi, just BEFORE the recent drop out of virtually all extensions, I needed to disable ALL my security extensions to get through an important transaction on line. When I re-enabled my containers were gone, but having re-created them and attempting to go through the necessary "teach it what to do" process, the second time that I'm going to a site I expect it to ask if I want to open in the current tab or the assigned container. On ticking the box to "always do this" and pressing the button for the assigned container NOTHING HAPPENS! The site doesn't open in ANY tab/container...
I've tried repeated removals of the extension to try to start afresh, but I always get some variation of things being rememebered - just never the exact same combination!! Wierd! And it still doesn't work...
My most recent attempt to get a "Clean Boot" for the extension was to remove the extension and then delete the relevant items from my profile, including under "Browser Extension Data" and "Extensions", including a folder called "staged" which I deemed to contain holdover data? This didn't work either.
If you can't re-create this or solve it I will next have to save my bookmarks and then raze Firefox right to the ground to get a Fresh Start for just one extension!

SYSTEM:-
FMAC version 6.1.0 currently (that may have been updated due to the overall extension issue but if so it has made no difference.)
Windows 10 Pro1803 64 Bit
Firefox 66.0.5 64 bit
But at the start of this issue I will have been using the previous Firefox version, whatever that was.
The change of Firefox version hasn't solved it...
Other extensions:-
Absolute Enable Right Click & Copy	1.3.8	true	{9350bc42-47fb-4598-ae0f-825e3dd9ceba}
AdBlocker Ultimate	2.37	true	adblockultimate@adblockultimate.net
Add Search	1.1.1	true	addsearch@burningmoth.com
Bulk Media Downloader	0.2.1	true	{72b2e02b-3a71-4895-886c-fd12ebe36ba3}
Cookie AutoDelete	3.0.2	true	CookieAutoDelete@kennydo.com
Download Manager (S3)	5.10	true	s3download@statusbar
Easy Youtube Video Downloader Express	15.0	true	{b9acf540-acba-11e1-8ccb-001fd0e08bd4}
Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
Fullscreen Maps	1.3.6.0	true	jid1-I1AHb505ZWPehw@jetpack
HTTPS Everywhere	2019.5.6.1	true	https-everywhere@eff.org
I don't care about cookies	3.0.0	true	jid1-KKzOGWgsW3Ao4Q@jetpack
No Coin - Block miners on the web!	0.4.13	true	{5657c026-efc3-4860-b43b-16e4eaa8a9aa}
Norton Safe Web	3.7.0.11	true	nortonsafeweb@symantec.com
NoScript	10.6.1	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Startpage.com — Private Search Engine	1.1.3	true	{20fc2e06-e3e4-4b2b-812b-ab431220cada}

### Actual behavior
After
1) setting up a new container and
2) opening the relevant site in it
3) clicking on "always open in xxxxx"
4) Next time on that site your page comes up with the prompt "Open this in current container or in xxxxx"
5) Clicking on the Green button on the right and nothing happens at all. Ths site isnt' opened anywhere...

### Expected behavior
On 5) above I expect my site to open in it's already assigned and confirmed "Always Container".

I hope you can re-proeduce this and solve it soon as I'm not looking forward to my next attempted solution!!

Otherwise a brilliant extension that I really want back!!!
Greg

**Comment by kendallcorner** [comment]
Is this still happening? A bug similar to this was fixed recently. I just can't find it to link to it.

**Comment by DrewNull** [comment]
Just happened to me 5 minutes ago (March 4, 2022). 

1. Create a new container.
2. Disable the containers extension, 
3. Re-enable the containers extension. 
4. The new container is gone. So are any other containers you ever created, ever.
