### ISSUE TITLE
Addin icon almost invisible when using Dark theme

### ISSUE THREAD

**Issue by jcpro** [mozilla/multi-account-containers#1424]
### Actual behavior
The Multi Account Container icon in the FF toolbar almost blends in with the default Dark theme FF making it difficult to see on certain monitors.  Even in Compact Dark mode the icon is still too dark to see.

### Expected behavior
The icon should stand out and be more visible when users are using Dark theme.

Normal Dark Mode:
![firefox_2019-05-24_09-43-20](https://user-images.githubusercontent.com/8902068/58340148-64f31080-7e08-11e9-985a-a5b38c481af5.png)

Compact Dark Mode:
![firefox_2019-05-24_09-46-00](https://user-images.githubusercontent.com/8902068/58340324-cdda8880-7e08-11e9-846b-2da9c1af8334.png)

**Comment by Hultan** [comment]
I have the exact same issue with FF and Linux Manjaro and the Adapta-Noko-Maia theme.

**Comment by silverwind** [comment]
👍 I think the icon should respect dark themes and be of the same color as the hamburger here:

<img width="56" src="https://user-images.githubusercontent.com/115237/59091685-25e8b300-8910-11e9-8e57-cbd8f7aa26bb.png">

**Comment by ThinkWithPbody** [comment]
I'm currently using Firefox Color and I hope changes made there could reflect on the icon for MultiAccount Container.

**Comment by silverwind** [comment]
Filed https://github.com/mozilla/multi-account-containers/pull/1435.
