### ISSUE TITLE
Facebook container loses its icon from the list of containers

### ISSUE THREAD

**Issue by udaykapur** [mozilla/multi-account-containers#1425]
Since upgrading to FF 67.0, I have noticed the icon which is shown next to the Facebook container from the list of containers has gone missing. After the first time it went missing yesterday, I chose a colored circle for it but it went missing again today.
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Ubuntu 18.04.02 LTS
- Firefox Version: 67.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: 

Name | Version | Enabled
------- | ---------- | -----------
Bloody Vikings! | 0.9.4 | true
Decentraleyes | 2.0.11 | true
Disable WebRTC | 1.0.20 | true
Disconnect | 5.18.27 | true
English Popup Dictionary | 1.8.3 | true
Facebook Container | 1.9.1 | true
Firefox Multi-Account Containers | 6.1.0 | true
hotfix-update-xpi-intermediate | 1.0.6 | true
HTTPS Everywhere | 2019.5.13 | true
Privacy Badger | 2019.2.19 | true
uBlock Origin | 1.19.6 | true

### Actual behavior
![image1(1)](https://user-images.githubusercontent.com/15121710/58366418-58a8a980-7f15-11e9-88d9-979d7d5d4d87.jpg)

### Expected behavior
The icon for Facebook should not go missing.

### Notes
Please close this issue in case this is an isolated case with my system as I could not find anyone else facing the same issue when I searched for it online. Maybe someone at your end could try and reproduce the issue with the given info. 

Thanks

**Comment by udaykapur** [comment]
Edit: typo

**Comment by kendallcorner** [comment]
Yes, I've seen this. I think it's because the fence icon that Faceboook Container uses is not a part of the MAC icon set.

**Comment by udaykapur** [comment]
Sorry haven't tested it on a MAC but the issue still exists in my system which is running Ubuntu - system config is pretty much the same as mentioned in the original issue except for usual updates to softwares/packages.

If this is reproducible on a MAC as well then it is likely independent of the OS and may exist across all platforms.

**Comment by kendallcorner** [comment]
Sorry, MAC is our short hand for Multi Account Containers :smiley:. I think it affect all systems.

**Comment by udaykapur** [comment]
Oops, all good. Thanks for the clarification. 

Read your comment again and it makes more sense to me now with the the fence icon being missing from the icon set.

**Comment by dcormier** [comment]
If you go to `about:preferences#containers` and edit a container, you can see the fence icon when you edit a container (far right).

![image](https://user-images.githubusercontent.com/216265/74256869-0d604200-4cc2-11ea-87e7-307996022213.png)

This is in FF 72.0.2 on macOS.
