### ISSUE TITLE
Ability to backup config to a file

### ISSUE THREAD

**Issue by skank** [mozilla/multi-account-containers#1427]
Recent events has caused users to lose their configs.
The config is rather cumbersome with a lot of clicking etc.

Ideally we should be able to export settings to a file.
As an example uBlock & uMatrix has this very essential feature.

**Comment by julien-garrigue** [comment]
Ah yes, that would be very very useful to save the config somewhere. Thank you

**Comment by cdev45** [comment]
Hi Team. I LOVE this Firefox Add-on, however we need the ability to backup our settings during device formats, device transfers, etc. Starting from scratch is a nightmare. Thank you!

**Comment by kendallcorner** [comment]
Linking to the original #1282 , but I'm leaving this open since a PR is submitted on it.

**Comment by dannycolin** [comment]
Duplicate of #1282
