### ISSUE TITLE
Not a real Container

### ISSUE THREAD

**Issue by hightower5** [mozilla/multi-account-containers#1439]
Containers creates cookies out of containers. I found in the privacy and security settings cookies from the used containers. This is not really useful and desired.

**Comment by lhorace** [comment]
Hello,

Can you explain how have you determined that?

Regards.

Images welcome.

**Comment by hightower5** [comment]
![Container](https://user-images.githubusercontent.com/18751660/59440909-ffd37f00-8df7-11e9-866d-5cfefcacc13d.png)

**Comment by lhorace** [comment]
That's not completely accurate, what's happening here is Cookies and Site Data lumps all cookies together and appears to be a platform bug, see https://bugzilla.mozilla.org/show_bug.cgi?id=1480175 and https://bugzilla.mozilla.org/show_bug.cgi?id=1485309. MAC does containerize site cookie data, you can test yourself using steps below:

1. delete all paypal cookies
2. create a container
3. log into paypal inside container
4. Open default container or any other container and view the results.

Regards

**Comment by kendallcorner** [comment]
Hi. It looks like this has been answered by @lhorace and there is a platform bug to address the issue, so I'm going to close this. If you don't feel the issue has been resolved, please discuss on the bugzilla bug(s). Thanks!
