### ISSUE TITLE
Please reconsider or reopen #854

### ISSUE THREAD

**Issue by mvdan** [mozilla/multi-account-containers#1443]
I believe https://github.com/mozilla/multi-account-containers/issues/854 was prematurely closed, and a number of people have been asking for it to be reopened in the last year.

It seems like the developer who closed the issue didn't fully grasp the point of the issue, and assumed it was a duplicate. He said "please re-open if not", but we can't, and noone is paying attention to the closed issue.

Hence I'm asking here, hopefully with more success :)

I'd prefer that the original issue be re-opened, instead of filing an entirely new one, because that one has many people involved already.

**Comment by mvdan** [comment]
For some context - #323 is related, and does mention this feature on the side:

> Or might be even more useful if user could associate a particular bookmark with a particular Container so that it automatically opens in the right Container.

So perhaps they are duplicates, as long as #323 requires this feature too. The other option is to keep the two features (manual vs automatic container selection) in the two separate issues, thus reopening #854.

**Comment by kendallcorner** [comment]
I've reopened #854
