### ISSUE TITLE
Release new version and publish on AMO

### ISSUE THREAD

**Issue by girst** [mozilla/multi-account-containers#1447]
There have been 10 commits since latest released version (6.1.0) was released on AMO, including a fix for http://bugzil.la/1539507 (buttons on 'always open in' page not working).

Please release a new version that includes this fix on AMO.

**Comment by ps-gssleap** [comment]
It's October. There hasn't been a release since January. How about it?

**Comment by ps-gssleap** [comment]
[Related](/mozilla/multi-account-containers/issues/1505)

**Comment by ps-gssleap** [comment]
6.1.1 has been released. Thank you!
