### ISSUE TITLE
Icon does not show when dark theme is selected

### ISSUE THREAD

**Issue by janw-me** [mozilla/multi-account-containers#1448]
I switched to dark theme (a default buildin color scheme).
And the icon was invisible. Below is the screenshot of the hover state which is visible but barely.

I'm on vanilla Ubuntu 19.04 with Firefox 67.0.4
Container version 6.1.0 last updated 25 jan 2019

![image](https://user-images.githubusercontent.com/1026882/60578323-48d87c80-9d81-11e9-8977-6c4ec43e365f.png)

**Comment by irvinm** [comment]
I agree.  It would be beneficial to provide an option to display a lighter icon that better supported dark themes.

![image](https://user-images.githubusercontent.com/979729/60771998-75600180-a0bd-11e9-867b-c5d54ca5d571.png)

**Comment by TriMoon** [comment]
Maybe they could make use of the functions in the script i wrote at https://github.com/soldair/node-qrcode/issues/185#issuecomment-511446585 to check for difference in colors....

**Comment by osumgbachiamaka** [comment]
Since the good first bug issues are all assigned, can i take this @groovecoder @maxxcrawford

**Comment by maxxcrawford** [comment]
@osumgbachiamaka All yours! Assigning now.

**Comment by silvererudite** [comment]
@maxxcrawford and @osumgbachiamaka  I think this issue was fixed but the new version isn't released in AMO so it still persists in the version found in AMO now. If I'm not wrong, there's already a PR #1435 which fixed it and I also cloned the latest repo and it works fine.

**Comment by maxxcrawford** [comment]
@silvererudite Can you confirm that the [latest release](https://github.com/mozilla/multi-account-containers/releases/tag/6.1.1) (now on [AMO](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)) solves this?

**Comment by silvererudite** [comment]
@maxxcrawford yes it does. The icon works fine on the latest version. I think You should close the issue as it's already solved.
