### ISSUE TITLE
Firefox multi-account containers  'forgets' assigned sites

### ISSUE THREAD

**Issue by jgoding77** [mozilla/multi-account-containers#1449]
-->
- Multi-Account Containers Version:
- Operating System + Version: Occurs both in Win10 and Win 7 
- Firefox Version: 67.0.3 (64-bit) )Win 7)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
All enabled: Canvas Defender, DuckDuckGo, Facebook, Multi-Account Containers, Ghostery, Grammarly

### Actual behavior
After assigning sites to individual accounter multi-account containers repeatedly forgets assigned sites and need to repeat assignment.  It's to the point where I've stopped and therefore this valuable feature is useless (for me)

### Expected behavior
Remember sites once assigned to a container

### Steps to reproduce
See above,  It's happened repeatedly,

### Notes
All enabled, history not cleared.

**Comment by kendallcorner** [comment]
Please provide steps to reproduce, thanks

**Comment by jgoding77** [comment]
Hi Kendall,

Unfortunately, I've given up trying to fix this and stopped using this
useful feature. Like I mentioned in the description, multi-account
containers (MAC) worked for a while, and then became lobotomized - meaning
after each attempt to assign different sites with specific containers
(personal, financial, etc), the MAC containers would not retain the
assignments I made and just go blank. Kind of like an etch-a-sketch.

I'd use it again in a heartbeat if it worked.

Regards,
John

**Comment by kendallcorner** [comment]
Thanks. I'm closing this. If anyone else has reliable steps to reproduce, I can reopen.
