### ISSUE TITLE
Installation aborted because the add-on appears to be corrupt.

### ISSUE THREAD

**Issue by benelori** [mozilla/multi-account-containers#1450]
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Ubuntu 19.04
- Firefox Version: 66.0.3
- Other installed Add-ons + Version + Enabled/Disabled-Status:

AdGuard AdBlocker	3.2.1	false	adguardadblocker@adguard.com
DuckDuckGo Privacy Essentials	2019.7.2	false	jid1-ZAdIEUB7XOzOJw@jetpack
Enhancer for YouTube™	2.0.92	false	enhancerforyoutube@maximerf.addons.mozilla.org
Facebook Container	2.0	false	@contain-facebook
Giant Bomb QoL	4.2	false	giantbomb@qol.snake
Greasemonkey	4.9	false	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
JetBrains Toolbox Extension	1.15.5580	false	{bf9e77ee-c405-4dd7-9bed-2f55e448d19a}
Merge Windows	1.0.2	false	{6d0b1446-4a7c-40e9-9bcf-568a8e26d00b}
NoScript	10.6.3	false	{73a6fe31-595d-460b-a920-fcc0f8843232}
Temporary Containers	0.103	false	{c607c8df-14a7-4f28-894f-29e8722976af}

### Actual behavior
When trying to install, I get _Installation aborted because the add-on appears to be corrupt._ error message.

### Expected behavior
Installation without issue.

### Steps to reproduce
1. Fresh install of Ubuntu 19.04
2. Access add-on page
3. Try to install
![Screenshot from 2019-07-06 20-40-07](https://user-images.githubusercontent.com/6870459/60759530-4c912b00-a02f-11e9-8f44-6c9ecd52ccf6.png)

**Comment by benelori** [comment]
I think this is integrated by default in the newer versions of firefox.

**Comment by noahlz** [comment]
"I think this is integrated by default in the newer versions of firefox."

Where can I find this feature in Firefox then? I'm on Ubuntu with Firefox 66.0.3

**Comment by Crismon96** [comment]
I have the same problem on Linux Mint with some of the add-ons I usually use on other operating systems. So my guess is that they are not already integrated and I am very interested in solving this issue.

**Comment by Crismon96** [comment]
So, If you are a Linux-noob like myself then you might have forgotten to update OS-Software. i do that with the "Update Manager" in Mint. By that I installed the latest version of Firefox and now i can download the addons troublefree. Please note that this warning can also be reasonable and you should always only trust addons with sufficient download and reviews or a trustable source.

**Comment by Valeyard1** [comment]
Any news on this? I'm getting the same error :(

**Comment by ori-cohen** [comment]
I am getting this error on Tor browser on MacOS.
<img width="362" alt="MultiAccountContainers-InstallationOnTor" src="https://user-images.githubusercontent.com/11043895/87254377-bed1f200-c471-11ea-8c07-7c2d6df65406.png">

**Comment by m-a-orlowski** [comment]
I had the same problem, but I finally found out this happens if you've toggled the _extensions.allowPrivateBrowsingByDefault_ option to _true_ in _about:config_. Maybe you did the same?

**Comment by a-hwang** [comment]
> 
> 
> I had the same problem, but I finally found out this happens if you've toggled the _extensions.allowPrivateBrowsingByDefault_ option to _true_ in _about:config_. Maybe you did the same?

You finally solved my problem after an hour of frustration. Thank you very much!

**Comment by bingoxo** [comment]
> 
> 
> I am getting this error on Tor browser on MacOS.
> <img alt="MultiAccountContainers-InstallationOnTor" width="362" src="https://user-images.githubusercontent.com/11043895/87254377-bed1f200-c471-11ea-8c07-7c2d6df65406.png">

i got it to install in tor but couldnt get it to work , could you ?

**Comment by shamarin** [comment]
I have the same problem with Firefox beta 102.b8
