### ISSUE TITLE
Feature Request -> Reopen in Container (Always)

### ISSUE THREAD

**Issue by rthompsonhi** [mozilla/multi-account-containers#1453]
This request is to expand upon "Reopen in Container ->" list.   Provide a second menu item "Reopen in Container (and Always open in Container) ->" list.   The intent being, when moving a tab to a new container, it auto-adds the site to the "Always Open in this Container" config and a user doesn't have to perform two steps.   This could be a configurable option if necessary.

Thanks

**Comment by grahamperrin** [comment]
> … second menu item … Always …

This became a feature some time ago: 

![image](https://user-images.githubusercontent.com/192271/115924575-d4039480-a477-11eb-9a09-9cc3ed375eb1.png)

@rthompsonhi you can close this issue. Thank you.

**Comment by grahamperrin** [comment]
Thanks!
