### ISSUE TITLE
Keyboard shortcut conficts with 1Password

### ISSUE THREAD

**Issue by openjck** [mozilla/multi-account-containers#1454]
1Password uses the same default keyboard shortcut:

<kbd>Ctrl</kbd> + <kbd>.</kbd>

As a result, it's occasionally not possible to open 1Password with its default keyboard shortcut if this extension is installed.

**Comment by openjck** [comment]
It may be worth asking whether this extension needs a keyboard shortcut at all.

**Comment by kyounger** [comment]
You can reassign keyboard shortcuts in fairly recent versions of firefox.

**Comment by ksmithut** [comment]
@kyounger Where does one change the keyboard shortcut for the multi-account-containers plugin? I know it's possible to change the 1Password keyboard shortcut (although it's changed within the plugin specific settings), but I never use (or never need to use) the keyboard shortcut for this plugin

**Comment by ksmithut** [comment]
Found it. In the Addons menu, Click on extensions, then click on the gear on the top right corner, then select the Manage Extension Shortcuts. There you should be able to change or remove the shortcut for any of your extensions.

**Comment by openjck** [comment]
I didn't know about that. Thanks!

Still, I think it's unfortunate that this add-on overrides the shortcut of a more popular add-on, especially considering that I can't imagine a case where I'd want to use a shortcut to activate this add-on.

**Comment by bdmorin** [comment]
This thread helped me. Thanks.

**Comment by thomasfedb** [comment]
This was a real pest for me until I discovered how to unset the shortcut for this extension. A different default (or no default) would be preferable.
