### ISSUE TITLE
open in default containers - why should I choose container name? 

### ISSUE THREAD

**Issue by vsrawat** [mozilla/multi-account-containers#1456]
When I open some website that, due to your shabbily made add-on, doesn't open in its default defined container - I am supposed to "reopen in container and choose container name"

why should I choose container name?
i have already defined it and it is stored with you. My container settings are showing that association. In fact the site should have opened in that container on the first click itself. but it doesn't and I have to reopen and select that name all over again.

When you know which site is to open in which container, just by clicking "reopen in container" should open the site in that defined container.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This this should be fixed, with steps outlined in https://github.com/mozilla/multi-account-containers/issues/1457#issuecomment-562180102 , so I'm going to close it. If that doesn't work, feel free to reopen it with and updated description of the issue.
