### ISSUE TITLE
Request: Customize other add-ons per container

### ISSUE THREAD

**Issue by s3rvant** [mozilla/multi-account-containers#1461]
Not sure if this is even possible however I would love to be able to customize which add-ons are enabled (and even their configurations) per container.

As an example I prefer to run NoScript all the time however it occasionally gives trouble for particular sites and rather than disabling the add-on it'd be awesome to just reopen the tab in a different container that has the entire NoScript add-on disabled for just that one container.

Another example is that I prefer to run as lean as possible however should I want access to an add-on that allows downloading media or some similar tool it would be convenient to be able to reopen that tab in a container with the necessary add-ons enabled for just that container.

**Comment by groovecoder** [comment]
This requires platform work too: https://bugzilla.mozilla.org/show_bug.cgi?id=1365019

**Comment by alexanderadam** [comment]
Duplicate of #1370

**Comment by dannycolin** [comment]
Duplicates of #1167
