### ISSUE TITLE
Grammarly add-on not active in containers

### ISSUE THREAD

**Issue by tallthom** [mozilla/multi-account-containers#1463]
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: MacOS High Sierra 10.13.6
- Firefox Version: 67.0.4
- Other installed Add-ons + Version + Enabled/Disabled-Status: Grammarly (8.852.2307), LastPass (4.29.04)
Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
Grammarly for Firefox	8.852.2307	true	87677a2c52b84ad3a151a4a72f5bd3c4@jetpack
LastPass: Free Password Manager	4.29.0.4	true	support@lastpass.com

### Actual behavior
Can't use Grammarly in my containers.

### Expected behavior
Should recognize that I'm signed into Grammarly and allow access in the containers.

### Steps to reproduce
1. Install Grammarly add-on
2. Log in (either in a container or not, it doesn't matter)
3. Try to use Grammarly while typing in text in the browser.

### Notes
Let me know if I can provide more information.

**Comment by kendallcorner** [comment]
Did you report this to Grammarly? I'm labeling it as a bug, but it sounds like Grammarly may need to fix it on their end.

**Comment by kendallcorner** [comment]
Oops. Did not mean to close.

**Comment by tallthom** [comment]
> Did you report this to Grammarly? I'm labeling it as a bug, but it sounds like Grammarly may need to fix it on their end.

Hi @kendallcorner -- sorry, I didn't report this to Grammarly. I'm not sure how I would do that... do I make a request that they support Firefox multi-containers? Will they even know what multi-containers are? Apologies for my confusion...

**Comment by groovecoder** [comment]
@tallthom You should start from their add-on page and look for a support or home page link: https://addons.mozilla.org/firefox/addon/grammarly-1/

**Comment by tallthom** [comment]
Ok, @groovecoder -- thanks for the guidance. I've found their support pages and logged an issue. If they let me know anything, I'll try to post it here. Otherwise, I guess we can close this issue?

**Comment by groovecoder** [comment]
Yup - closing here.

**Comment by algomaster99** [comment]
Hey @tallthom ! Any update if Grammarly has fixed this issue? It still seems to persist in `v8.904.0`.

**Comment by tallthom** [comment]
No idea. I stopped using Grammarly on Firefox.
