### ISSUE TITLE
Want to list URLs that are set to open by default in a particular container

### ISSUE THREAD

**Issue by wfiveash** [mozilla/multi-account-containers#1465]
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
I can not figure out how to list the URLs that will open by default in a particular container I created.

### Expected behavior
I would like to list all the URLs/websites that will open by default in a container I created called News.  I would like to be able to do the same for the other containers I've created.

### Steps to reproduce
1.
2.
3.

**Comment by kendallcorner** [comment]
Hi there. It's under the edit panel. You can also remove them if you don't want from that panel.
![Peek 2019-12-05 09-12](https://user-images.githubusercontent.com/3195251/70247677-5e424000-173f-11ea-8e12-db39c1fedf53.gif)

I'm closing this, but feel free to reopen if there's still an issue.
