### ISSUE TITLE
Can a shortcut key be added to go to an existing account container?

### ISSUE THREAD

**Issue by MrGoatsy** [mozilla/multi-account-containers#1466]
For example: CTRL+ALT+NUM1 or something.

It would make using it easier.

**Comment by whisperity** [comment]
How about CTRL-<ContainerID>-T, which is analoguous to the plain Ctrl-T? :grin: So Ctrl-1-T would be first container, etc.

**Comment by MrGoatsy** [comment]
That would work that key combination is hard to press.

**Comment by grahamperrin** [comment]
Implemented. 

@MrGoatsy please, can you close this issue?

**Comment by dannycolin** [comment]
It has been implemented for a while now. (Ctrl + Shift + [0-9]) so I'm closing this issue.
