### ISSUE TITLE
Keyboard shortcut won't work

### ISSUE THREAD

**Issue by lapega** [mozilla/multi-account-containers#1469]
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Ubuntu 18.04
- Firefox Version: 68.0
- Other installed Add-ons: Gnome-shell 10.1, Background-tab 1.0 it, uBlock Origin 1.20.2 (all enabled)

### Actual behavior
When press Ctrl + . nothing happens

### Expected behavior
Press Ctrl + . and get a menu to open a new container tab

### Steps to reproduce
1. Install Firefox Multi-account Containers
2. Press Ctrl + .

### Notes
When using the long press click in new tab button, works fine.

**Comment by ywg-jean** [comment]
same on OSX, none of the following opens the container tab
* cmd+.
* cmd+shift+. (on a french keyboard the dot requires shift)
* ctrl+.
* ctrl+shift+.

**Comment by uberentwickelt** [comment]
It appears you need the Add-On in your toolbar or the overflow menu in order for the shortcut to work.

When you remove the icon from the toolbar, it appears long press on the new tab button is the only way to open a containers menu without going into settings.

**Comment by lapega** [comment]
Wow, such a strange behavior.

I don't like having addons buttons in the toolbar, I'm a minimalist person ;) 
So I suppose I'll use the long press way meanwhile.

Thanks for the response!

**Comment by a-matai** [comment]
Hi,

it used to be that "ctrl+.+(1-4) would open up the correct container. The numbers don't work if it's in overflow, but works fine if in toolbar.

**Comment by maxxcrawford** [comment]
This has been addressed in the [latest release](https://github.com/mozilla/multi-account-containers/releases/tag/7.0.1). Thanks!
