### ISSUE TITLE
Unneeded separator in reopening menu when using only one container

### ISSUE THREAD

**Issue by nclm** [mozilla/multi-account-containers#1471]
### Actual behavior
<img width="498" alt="image" src="https://user-images.githubusercontent.com/923008/62042840-54438a00-b1ff-11e9-883f-9cc178f714d5.png">

### Steps to reproduce
1. Have only 1 container
2. Open a tab in this container
3. Right click the tab and choose Reopen
4. The menu has the “No container” entries and then a useless separator

### Expected behavior

The separator should not be there in that case.

**Comment by Jo-IE** [comment]
Hey @maxxcrawford @groovecoder I would like to work on this please! #outreachy

**Comment by dannycolin** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1329453
