### ISSUE TITLE
Allow us to apply certain add-ons per container

### ISSUE THREAD

**Issue by n8zwn** [mozilla/multi-account-containers#1486]
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior

You cannot choose the specific add-ons that apply to a container, such as foxy proxy or other tools I use for work. 

### Expected behavior

I would love the ability to have certain add-ons available based on the container. Is this even possible?

**Comment by HURSSGH** [comment]
Agree completely.

In fact, I would like to see containers have all preferences configurable on a per-container basis.

**Comment by alexanderadam** [comment]
Duplicate of #1370

**Comment by dannycolin** [comment]
Duplicates of #1167
