### ISSUE TITLE
Feature request: Sync containers (or be able to export settings) + adding websites by a list

### ISSUE THREAD

**Issue by TobiasDev** [mozilla/multi-account-containers#1489]
I love the Firefox Container options to not share data with everything, eg. when I have to use Pintrest at work I can have that in it it's own container to not share data with my other websites, etc. :) However, something I think is a bit lacking the is set-up for this. Rather than forcing the user to set this up per PC basis and having to visit the website in the right container, I would love to see settings for this. 

Eg. 
1. Either that my containers and the websites they are assigned to work with Firefox sync or, that we could export all our containers (names, websites belonging to them etc.) so you can just import it to another browser when you want. 

2. Instead of having to open a website in the right container, and then also having to set it to a container by default, we should have "Container" settings. For example, if I have a container called "Social Media" rather than me having to open the websites in the right one, I can press a cog wheel and then just add them to a list, and then Firefox will always open any of those address in that container by default. 
So I could do like
https://twitter.com
https://facebook.com
etc.

**Comment by groovecoder** [comment]
Good suggestions ... I think these are dupes of https://github.com/mozilla/multi-account-containers/issues/339 and https://github.com/mozilla/multi-account-containers/issues/719 though? Can you upvote & comment on those? We are going to have [another Outreachy internship](https://www.outreachy.org/apply/project-selection/) for this project soon, and we'll be looking at the most up-voted issues for the work sprint.
