### ISSUE TITLE
Cannot remove Amazon and other add ons

### ISSUE THREAD

**Issue by OIITCONZ** [mozilla/multi-account-containers#1493]
I cannot find an issue link for this:

amazon Add on is in my list of installed addons ( about:support) 
It is not ticked as a search engine. 
It does not show in my list of add ons. 
I cannot find info on how to fix this anywhere. 
It shouldn't show. 

Goto About:support
Scroll to Add-ons
Find amazon in list.

Go to options/ Addons.
Scroll through list
It is not there. 
Ditto Bing, Twitter, 

firefox 69.0 
Windows 7 - Latest updates

My about:support link details shown below.

***Amazon.com 1.1 true amazondotcom@search.mozilla.org - WTF???? Killed this so many times!!!!!***
Bing 1.0 true bing@search.mozilla.org
ColorZilla 3.3 true {6AC85730-7D0F-4de0-B3FA-21142DD85326}
DuckDuckGo 1.0 true ddg@search.mozilla.org
Google 1.0 true google@search.mozilla.org
HTML Validator 0.9.8.8 true {3b56bcc7-54e5-44a2-9b44-66c3ef58c13e}
ruler 2.0.3 true {b1355a29-9265-4b5e-a3ad-e9d61265d5ac}
Take Webpage Screenshots Entirely - FireShot 0.98.94.10 true {5e11ab1e-083c-11e5-a6c0-1697f925ec7b}
Twitter 1.0 true twitter@search.mozilla.org
Video Downloader professional 1.98.2 true ffext_basicvideoext@startpage24
Web Developer 2.0.1 true {c45c406e-ab73-11d8-be73-000a95be3b12}
Wikipedia (en) 1.0 true wikipedia@search.mozilla.org

**Comment by jonathanKingston** [comment]
This is a native addon purely for providing amazon search, I'm not sure if you can remove the code but you can remove it from the url bar through about:preferences. Search providers don't actually have code other than doing just than, being a search provider.

Either way this isn't a multi-account container issue.

**Comment by OIITCONZ** [comment]
Hi Jonathon, AS I said I cannot find an issue link for this:

I'm aware it is not a multi container issue. 

I think having non removable add ons put in place by Mozilla breaks the freedom and privacy Mozilla claim to offer. Addons are code and code linking to third parties is not private or choice. 

Feel free to move this to a better thread if you know where one is. 

Shane
