### ISSUE TITLE
open all tabs

### ISSUE THREAD

**Issue by Arumplee** [mozilla/multi-account-containers#1498]
is there a way to open all tabs at once?

**Comment by jonathanKingston** [comment]
Is this when the tabs are hidden? Are you able to explain the issue a little further?

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. Since there was no response here, I'm going to close this one. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
