### ISSUE TITLE
Feature Request: Manual editing for sites assigned to a container

### ISSUE THREAD

**Issue by ndhuang** [mozilla/multi-account-containers#1501]
It would be very useful to have manual control over which sites are set to open in a given container automatically.  The particular use case I'm encountering is with slack.  When logged in `<workspace>.slack.com` redirects to `app.slack.com/...`.  Given that I've already logged in, when I open a link to `<workspace>.slack.com` in the appropriate container, it redirects, and I don't have a chance to add `<workspace>.slack.com` to the list of sites assigned to the container.  I realize I can work around this by logging out, assigning the site to a container, and logging back in.

**Comment by jc00ke** [comment]
I've noticed this too, with the recent change to how Slack serves via `app.slack.com`. Would love to see manual editing enabled.

**Comment by dpruth** [comment]
I've also run into this. If there was a way to include wildcards, or simply based the URL matching off the base domain (excluding subdomain or directories), that'd be very helpful. I've run into this with sharepoint.com sites and subdomains.

**Comment by Angel418** [comment]
URL matching isn't enough - for example, reddit can use multiple accounts, but serves the exact same URL's.

**Comment by Jean85** [comment]
There's #1500 that tries to partially tackle this issue.

**Comment by alex-hempel** [comment]
I would like to see this as well. Simply allowing for manual adding and editing of URLs assigned to a container would be immensely helpful.

@Jean85 unfortunately the PR you referenced does not cover my particular uses case, as I need specific URLs for containers, not wildcards.

**Comment by Spectre5** [comment]
I also really need this for several different sites/containers that I use.  I'd like to have an "add site" button at the bottom of the container edit screen, under "sites assigned to this container".  In the meantime, is where a way to manually do this in some settings file in the firefox profile?  I looked around a little bit there but couldn't find anything.

**Comment by Hard-Wired** [comment]
Manual editing/adding to the container URL list is a must. This is the primary reason I don't end up using this extension because it is too hard to add a URL of a website that immediately forwards to another URL (e.g., outlook.com forwards to outlook.live.com). A lot of Google sites work this way as well. So annoying. Please add container URL editing/adding!!!

**Comment by buzuck** [comment]
This is a prerequisite to #691, as wildcards require manual editing.

**Comment by utucuro** [comment]
The current behavior completely breaks authentication across Google properties. For example, installing an android app via play.google.com sends the user to accounts.google.com which then takes them to the local google site and the accounts.youtube.com (for some reason) site. I can visit the two accounts.*.com sites, but the local site automatically redirects to accounts.google.com, so I cannot even add it to the container I need it to be in...

**Comment by grahamperrin** [comment]
▶ #839

@ndhuang please, can you close this duplicate issue? Thank you.

**Comment by ndhuang** [comment]
Duplicate of #839
