### ISSUE TITLE
Tooltip shows HTML entities for some characters

### ISSUE THREAD

**Issue by chk1** [mozilla/multi-account-containers#1507]
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Windows 10 1809
- Firefox Version: 69.0.1, 70.0b9 (dev edition)
- Other installed Add-ons + Version + Enabled/Disabled-Status: none in dev edition

### Actual behavior
The tooltip on containers in the container list displays HTML entities for some characters, for example, container `a/b c` has the tooltip `a&#x2F;b c`

Screenshots:

![image](https://user-images.githubusercontent.com/828496/65766114-560bca00-e12a-11e9-9344-02b0f2e11df6.png)

![image](https://user-images.githubusercontent.com/828496/65766109-52784300-e12a-11e9-940f-628a0c74c7ba.png)

### Expected behavior
The tooltip should display the same text as in the container list

### Steps to reproduce
1. Create container with special characters like `&` or `/`
2. Open Multi-Account-Container addon dropdown from Firefox toolbar
3. Hover mouse on a container

**Comment by Jo-IE** [comment]
I would like to work on this :)

**Comment by maxxcrawford** [comment]
@Jo-IE Assigned. Thanks for contributing!

**Comment by bini11** [comment]
Hey @maxxcrawford I'm an Outreachy applicant & looking forward to contributing to this project but there're very few bugs with outreachy tag which are already taken so can you assign any bug to me or point me to a direction for contribution.

**Comment by Jo-IE** [comment]
Hi @maxxcrawford I have made the necessary edits in `popup.js` to resolve this issue. Currently, the title attribute of the `tr` element is being passed into an `escaped` function to replace HTML characters with the entities seen on hover. What I have done is set the tooltip attribute without using that `escaped` function. I am just making sure there isn't anything else I'm missing before I submit my PR. Thanks in advance!

**Comment by Jo-IE** [comment]
I'm also getting this error when I run `npm test` Do you have any pointers for me? @maxxcrawford 

I've tried deleting my `node modules` folder and `package-lock.json` file and running `npm install` but still no luck.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testpilot-containers@6.1.0 lint:js: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testpilot-containers@6.1.0 lint:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by maxxcrawford** [comment]
@Jo-IE Go ahead and file the PR. 

Not sure about the `npm test` results. Try running the same command on the `master` branch and see if you get the same error. I confirmed on my end and that test ran back correctly.

**Comment by maxxcrawford** [comment]
@bini11 We're only adding the `outreachy-assigned` tags to issues that are assigned, so any issue without that tag is available. Look through the [open issues without that tag,](https://github.com/mozilla/multi-account-containers/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3Aoutreachy-assigned+) and comment on one you'd like to contribute to!

**Comment by Jo-IE** [comment]
@maxxcrawford so to resolve the error I deleted my local copy and fork of the repo and made a new fork and ran `npm test` before making any changes and the tests worked perfectly. However, I switched to a new branch and made the changes to resolve this PR and after making the changes I ran `npm test` on the new branch and I'm getting those errors. I finally had to manually do node `./node_modules/eslint/bin/eslint --fix ./src/js/popup.js`  and after that `npm test` worked again

**Comment by Jo-IE** [comment]
Hey @maxxcrawford @groovecoder I have submitted a [PR](https://github.com/mozilla/multi-account-containers/pull/1517) for this issue.
