### ISSUE TITLE
Firefox container is the same thing with the linux container?

### ISSUE THREAD

**Issue by huster16** [mozilla/multi-account-containers#1508]
May I ask whether the Firefox container is the same with linux container? Or it just the generalized "container" designed by Firefox?

**Comment by Aishat-Akinyemi** [comment]
It is a webextension built to work with firefox broswers, it lets you  

> "carve out a separate box for each of your online lives " . 

 Check the introduction at [https://blog.mozilla.org/firefox/introducing-firefox-multi-account-containers/](url)
