### ISSUE TITLE
Addon Submisison Validation Error

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/multi-account-containers#1514]
When submitting `web-ext` zip of v6.1.1, I received the following error: 

![image](https://user-images.githubusercontent.com/2692333/66162161-6bce3300-e5f3-11e9-9c52-6c75ddaaf441.png)

**Comment by Edely** [comment]
Hi, @maxxcrawford, I am an outreachy applicant and would like to work on this issue if it is available.

**Comment by groovecoder** [comment]
@Edely this one is probably better for @maxxcrawford or I to do, since it needs close coordination with the AMO team to make sure we get it right.

**Comment by Edely** [comment]
No problem, @groovecoder . Do you know if there is other issues I could work on. It seems every issue with "good first bug" label is assigned to someone.

**Comment by groovecoder** [comment]
You might check the "help wanted" issues too. https://github.com/mozilla/multi-account-containers/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

@maxxcrawford and I will need to go thru some un-triaged issues and add some more labels! Very active Outreachy cohort! 🎉

**Comment by osumgbachiamaka** [comment]
@groovecoder @maxxcrawford I am also looking for issues to work on as my first contribution to this project

**Comment by maxxcrawford** [comment]
Closing this issue, as it has been resolved. 

My AMO email (which uses my FxA Sync email) was @gmail.com. This lint is by-passed by using a @mozilla.com email address.
