### ISSUE TITLE
Firefox Nightly URL bar magnification covers container tab color

### ISSUE THREAD

**Issue by mylesmyles** [mozilla/multi-account-containers#1522]
Just some feedback. Firefox nightly has a cool URL bar magnification effect that is applied when you are typing in the URL bar. However, it covers the container colors in the tabs so you have to click away from the URL bar to see which container a tab is.

Screenshots:
URL bar unfocused: ![image](https://user-images.githubusercontent.com/6269517/66501766-402ecb00-ea81-11e9-931d-ea96b6f6b399.png)
URL bar focused: ![image](https://user-images.githubusercontent.com/6269517/66501846-6a808880-ea81-11e9-8434-27f4820f621d.png)

Obviously the URL magnification feature might change, but I figured I'd let you know.

Cheers!

**Comment by dannycolin** [comment]
Closing. The container indicator is now above the tab Firefox 89+
