### ISSUE TITLE
Support for Firefox Colors

### ISSUE THREAD

**Issue by rdlmda** [mozilla/multi-account-containers#1526]
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Fedora 30
- Firefox Version: 69.0.1

### Actual behavior

Icon color not matching:
![Captura de tela de 2019-10-10 15-12-36](https://user-images.githubusercontent.com/4602525/66594968-75fead00-eb70-11e9-9f1c-8a62764a8374.png)

![Captura de tela de 2019-10-10 15-14-29](https://user-images.githubusercontent.com/4602525/66595105-acd4c300-eb70-11e9-8a4a-5e4dab9ea31a.png)

![Captura de tela de 2019-10-10 15-15-25](https://user-images.githubusercontent.com/4602525/66595178-d1c93600-eb70-11e9-81bf-22e64b604ece.png)

### Expected behavior

Icon color matching the pattern

### Steps to reproduce
1. Change colors on https://color.firefox.com/

**Comment by martineizayaga** [comment]
Where would the style rules for the icon be?

**Comment by rdlmda** [comment]
What are style rules?

**Comment by rdlmda** [comment]
Turns out Firefox Colors are applied only on native icons and not icons provided by extensions.
