### ISSUE TITLE
Unclickable checkbox with "Always Open in Default"

### ISSUE THREAD

**Issue by yellowwoods12** [mozilla/multi-account-containers#1528]
### Testing System Specifications

- Multi-Account Containers Version:6.1.1
- Operating System + Version: Ubuntu 18.04
- Firefox Version: 69.0.1 (64-bit)

### Actual behavior
The checkbox displayed with "Always Open in Default" cannot be checked in the present version and lacks functionality.

![Screenshot from 2019-10-11 16-46-02](https://user-images.githubusercontent.com/31931348/66648044-255a8300-ec48-11e9-933a-a60bffa9aa29.png)

### Expected behavior
The checkbox displayed with "Always Open in Default" should be checked when clicked and remain like that until clicked again.

### Steps to reproduce
1. Open Firefox.
2. Open the Multi-Account Containers popup.
3. Try clicking on checkbox with "Always Open on Default" message on the side.

**Comment by silvererudite** [comment]
@yellowwoods12 the checkbox does work. I believe you are facing the issue as the usage is not quite clear. Currently you need to first open a container by choosing one from the list. From there you can go to your fav site and then click the checkbox to assign it to that container. You will see it works. 
However as far as I tested, the checkbox won't work until a container is opened you know.

**Comment by yellowwoods12** [comment]
@silvererudite yes I am clear with that. The issue is to provide the checkbox with some functionality until we open a site in a container. Another solution to this issue can be to completely hide this checkbox until a site is opened in one.

**Comment by dnahol** [comment]
Hi @yellowwoods12 . I see what you mean! I saw you on another thread say you were an Outreachy applicant. Me too! Are you working on this? If not, I'd like to take it! Let me know.

**Comment by yellowwoods12** [comment]
Hi @dnahol, Yes I am working on it.
@groovecoder @maxxcrawford Can you please assign it to me?

**Comment by dannycolin** [comment]
Closing since the UI has changed and there's no more checkbox.
