### ISSUE TITLE
Ways to display complete name of the current tab

### ISSUE THREAD

**Issue by yellowwoods12** [mozilla/multi-account-containers#1529]
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Ubuntu 18.04
- Firefox Version: 69.0.1 (64-bit)

### Actual behavior
Whenever a currently open tab has a very long name only a part of it is displayed in the container popup. For example, in the following image for the current tab "Browser Support for Javascript APIs" only a part of the name i.e., "Browser Support for" is completely visible.

![Screenshot from 2019-10-11 17-07-40](https://user-images.githubusercontent.com/31931348/66649429-c8f96280-ec4b-11e9-80d3-a3ccc685c3f3.png)

### Expected behavior
I was able to figure out two feature enhancements that can be added here.
1) On hovering over the name of the current tab, the entire name should horizontally scroll through the popup so that it is completely visible.
2) On hover, the entire name of the current tab should be displayed like when it happens on hovering over Sort Tabs button.

![Screenshot from 2019-10-11 17-20-51](https://user-images.githubusercontent.com/31931348/66649373-9a7b8780-ec4b-11e9-8ff7-c8716a07dada.png)

### Notes
These are just some easily implementable enhancements for the present scenario. Any further suggestions are most welcome.

**Comment by HagarMostafa** [comment]
@groovecoder and @maxxcrawford can I try working on this issue?

**Comment by silvererudite** [comment]
@yellowwoods12  Currently if we hover over the tab name of the currently displayed tab it shows us the tooltip of the entire name. Wouldn't it be an overkill if we implement sth that already exists.

I think it is a good design choice as it keeps the UI of the popup minimal and clutter free. It's just my opinion but would love some perspective from the maintainers.

**Comment by yellowwoods12** [comment]
Hi @silvererudite, tooltip was also something that I suggested in this issue as this is something which is not currently implemented in the present version. Also the UI should be minimal but at the same time it must be independently sufficient for providing any kind of information.
Lets see what @maxxcrawford and @groovecoder think about this.

**Comment by groovecoder** [comment]
Assigning for @HagarMostafa to work on - please let us know if you decide not to work on this and we'll un-assign it.

**Comment by HagarMostafa** [comment]
Hello @groovecoder, @maxxcrawford, I have made a hover tooltip for the popup title. Any recommended modifications are most welcomed.
![tooltip](https://user-images.githubusercontent.com/24817937/67253585-a4399200-f478-11e9-92f4-fbaf57545fd7.jpg)

**Comment by yellowwoods12** [comment]
Hi @HagarMostafa, it looks good. I think you should make a pull request for it so that they can review.

**Comment by HagarMostafa** [comment]
Hi @groovecoder, @maxxcrawford , I created a pull request, please check.

**Comment by dannycolin** [comment]
Closing since the UI has changed and we don't show the container name in the main popup menu anymore.
