### ISSUE TITLE
All the containers reset and new containers vanish when "Run in Private Windows" configuration is changed

### ISSUE THREAD

**Issue by ghost** [mozilla/multi-account-containers#1536]
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Windows 10 1809
- Firefox Version: 69.0.3 32bit
- Other installed Add-ons + Version + Enabled/Disabled-Status:
AdNauseam	3.8.401	true	adnauseam@rednoise.org
Amazon.co.uk	1.1	true	amazon@search.mozilla.org
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.0	true	bing@search.mozilla.org
Chambers (UK)	1.0	true	chambers-en-GB@search.mozilla.org
Dark Reader	4.8.1	true	addon@darkreader.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
enhanced-h264ify	2.1.0	true	{9a41dee2-b924-4161-a971-7fb35c053a4a}
Firefox Multi-Account Containers	6.1.1	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
Twitter	1.0	true	twitter@search.mozilla.org
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Easy Youtube Video Downloader Express	16.0	false	{b9acf540-acba-11e1-8ccb-001fd0e08bd4}
LeechBlock NG	1.0.4	false	leechblockng@proginosko.com
Privacy Badger	2019.10.8	false	jid1-MnnxcxisBPnSXQ@jetpack
uBlock Origin	1.22.4	false	uBlock0@raymondhill.net

### Actual behavior
All the containers reset and new containers vanished when I toggled "Run in Private Windows" option from "Allow" to "Don't Allow".

### Expected behavior
Backup containers, or give warning that it will reset, or retain configuration when I toggled "Run in Private Windows" option from "Allow" to "Don't Allow".

### Steps to reproduce
1. Add new containers
2. Go to add-ons manager
3. Go to more options
4. Change the "Run in Private Windows" configuration.

### Notes
Please add options to backup and sync containers. Thank you.

**Comment by dannycolin** [comment]
Closing since the latest version of the addon isn't allowed to run in Private Window mode.
