### ISSUE TITLE
Multi-windows containers

### ISSUE THREAD

**Issue by TRzon** [mozilla/multi-account-containers#1546]
I like the idea of tab-containers, but what about making it working on multi windows containers?
I use firefox with plenty of tabs opened in multiple windows, and i feel like it would worth it to consider having multiple tabs in multiple windows containers. Have you ever thought of it?

**Comment by kendallcorner** [comment]
If you are meaning what is described in #319, please +1 or discuss on that issue to avoid duplicates. I'll close this, but feel free to reopen if you think it's a different issue.
