### ISSUE TITLE
Make container panel tabbable and container identity buttons accessible via enter key

### ISSUE THREAD

**Issue by dnahol** [mozilla/multi-account-containers#1547]
### Actual behavior
Container identities list in container panel is not tabbable (reachable via tab key). Container identity buttons are not accessible accessible via enter key.

Here is a GIF screen recording of what happens when you try to tab through the panel. Notice the right Show Tabs buttons are never highlighted when tabbing through:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2976514/67338761-a5050f00-f4de-11e9-8c8d-602f18af1d02.gif)

### Expected behavior
Container identities list in container panel should be tabbable (reachable via tab key). Container identity buttons should be accessible accessible via enter key.

### Steps to reproduce
1. Click on container popup button
2. Press tab to navigate to a container identity (e.g. "Shopping") in the container identities list
3. Press enter to add Shopping tab
4. Pressing tab will not allow you to reach the Show Tabs arrow button for the Shopping container identity

### Notes
- Multi-Account Containers Version: Version 6.1.1, Last Updated: October 22, 2019
- Operating System + Version: Mac OS Sierra Version 10.13.6 
- Firefox Version: Firefox Quantum Version 69.0.3 (64-bit)

**Comment by kendallcorner** [comment]
Link to #1555

**Comment by grahamperrin** [comment]
`7.3.0`: the panel seems to respond to intuitive use of arrow keys and so on.

**Comment by dannycolin** [comment]
It does. Pressing "Enter" opens a new container tab and pressing "right arrow" opens the menu with more options.

Since this specific issue looks like solved, I'll close this bug repot but feel free to open a new one if you find more accessibility issues in the addon.
