### ISSUE TITLE
Make edit containers panel tabbable

### ISSUE THREAD

**Issue by dnahol** [mozilla/multi-account-containers#1555]
### Actual behavior
Edit containers panel buttons not accessible via tab key
![EditContainersTabbing Issue](https://user-images.githubusercontent.com/2976514/67447445-b6c2e100-f5c8-11e9-944e-ae1edde1ea21.gif)

### Expected behavior
Edit containers panel buttons should be accessible via tab key

### Steps to reproduce
1. Open containers popup
2. Click Edit Containers button on bottom of main panel
3. Press tab to navigate through edit and delete buttons for every identity (It doesn't work)

### Notes
- Multi-Account Containers Version: Version 6.1.1, Last Updated: October 22, 2019
- Operating System + Version: Mac OS Sierra Version 10.13.6 
- Firefox Version: Firefox Quantum Version 69.0.3 (64-bit)

**Comment by NoumanMasood** [comment]
Hi, I am outreachy intern. Can i work on this problem?

**Comment by dnahol** [comment]
Hi @NoumanMasood I submitted a PR for this yesterday. I'd be happy to hear any comments you may have onboard!

**Comment by NoumanMasood** [comment]
ok I need to do contribution for outreachy. Can you help me to guide which task should I do?

**Comment by dnahol** [comment]
I hear you. I'm doing the same. As far as I can see, basically any open issue that isn't already assigned is fair game. There is a "Good First Bug" tag as well, but you don't have to limit yourself to that.

**Comment by dnahol** [comment]
Oh and also some issues aren't assigned but they do have a PR on there already, like this one. You will see the PR mentioned like mine is above your comment.

**Comment by NoumanMasood** [comment]
ok means that we can create issues ourselves too and then can work on it . right?

**Comment by dnahol** [comment]
yep

**Comment by grahamperrin** [comment]
`7.3.0`: **Manage Containers** appears to respond to intuitive use of arrow keys, and so on.

**Comment by dannycolin** [comment]
Fixed in another bug.
