### ISSUE TITLE
Issue with Containers Add-on

### ISSUE THREAD

**Issue by OllieH619** [mozilla/multi-account-containers#1558]
- Multi-Account Containers Version: 6.1.1
- Operating System + Win 10
- Firefox Version:  70.0 (64-bit)

### Actual behavior

Clicking on the containers icon in top right and its just displaying a small drop down box:

![image](https://user-images.githubusercontent.com/56963167/67501362-10381800-f67c-11e9-9d0f-0262de6fbc45.png)

### Expected behavior

I believe when clicking the icon it should bring up more than it is now

### Steps to reproduce
1. Open Firefox
2. Click the icon for Container

### Notes

I have tried the following:

Turned pop-up blocker off
Reinstalled firefox (clean version)
Rebooted machine

**Comment by grahamperrin** [comment]
I believe that things such as this were fixed long ago. 

@OllieH619 please, can you close this issue?
