### ISSUE TITLE
Make Container Info Panel Tabbable

### ISSUE THREAD

**Issue by dnahol** [mozilla/multi-account-containers#1559]
### Actual behavior
Container Info Panel buttons and tabs are not reachable via pressing Tab.

Screen recording showing container info panel buttons not accessible via Tab key:
![ContainerInfoTabbing Issue](https://user-images.githubusercontent.com/2976514/67519333-7a8c9080-f65b-11e9-9f19-f5cabbfa5fbb.gif)

### Expected behavior
Container Info Panel buttons and tabs should be reachable via pressing Tab.

### Steps to reproduce
1. Open Containers popup
2. Create a container tab
3. Go to the Container Tab Info panel for that container
4. Use tab to navigate through the buttons and tabs in the Container Info panel (It doesn't work)

### Notes
- Multi-Account Containers Version: Version 6.1.1, Last Updated: October 22, 2019
- Operating System + Version: Mac OS Sierra Version 10.13.6 
- Firefox Version: Firefox Browser Version 70.0 (64-bit)

**Comment by groovecoder** [comment]
I think this is closed via https://github.com/mozilla/multi-account-containers/pull/1524, right?

**Comment by dnahol** [comment]
Yes, closing now.
