### ISSUE TITLE
Add more colors and icons in editing containers

### ISSUE THREAD

**Issue by NoumanMasood** [mozilla/multi-account-containers#1566]
**Please fix this as a priority!**

![image](https://user-images.githubusercontent.com/14115229/67980785-f892fd80-fc40-11e9-8c67-7bc65c1d79b4.png)

This extension should have more options for colors and icons while editing it. It provides user more options and give more flexibility to choose colors and icons of their desire.

Multi-Account Containers Version: 6.1.1 (and all previous)
Operating System + Version: windows 8.1
Firefox Version: 70.0 (64-bit)
Other installed Add-ons + Version + Enabled/Disabled-Status: Tree tabs, Onetab, Bookmarks managers, all enabled and used.

### Actual behavior
Currently, it shows only limited set of colors 
![image](https://user-images.githubusercontent.com/14115229/67981011-7fe07100-fc41-11e9-8689-bc339c5d1d4a.png)

### Expected behavior
It should give more options for colors.
![image](https://user-images.githubusercontent.com/14115229/67981364-4b20e980-fc42-11e9-9ca1-11e5edb4826d.png)

### Steps to reproduce
1. Click on edit containers.
2. Click on pencil icon
3. Modal will open

**Comment by shmerl** [comment]
I'd add the ability to set any custom color. That shouldn't be hard.

**Comment by mstojanovic** [comment]
i agree, more colors would be great!

**Comment by TMMC** [comment]
> 
> 
> I'd add a suggestion to add the ability to set any custom color. That shouldn't be hard.'
> 
> As for more icons, see: #843

Moreover, ability to add custom icons (SVG, PNG, etc.) would be really great idea and it would give user more visual separation of page within custom container.

**Comment by mixaxdd** [comment]
I tryed to add more colors but fail (add 2 colors) 
use this https://developer.mozilla.org/ru/docs/Web/CSS/color_value

./js/popup.js:  
``const colors = ["blue", "turquoise", "green", "yellow", "orange", "red", "pink", "purple", "lightgreen", "tomato"];``

./css/popup.css: 
``[data-identity-color="lightgreen"] {
  --identity-tab-color: #90ee90;
  --identity-icon-color: #90ee90;
}
[data-identity-color="tomato"] {
  --identity-tab-color: #ff6347;
  --identity-icon-color: #ff6347;
}``

Yes, it add 2 circle in "Choose a color", but colors not apply.
What am I missing?

**Comment by alexanderadam** [comment]
Chosing arbitary colors is a duplicate of #391

**Comment by TonyGravagno** [comment]
👍 on more colors and icons. I regret now that I didn't take time to understand this great containers feature until today. With my very first use I was frustrated with the limit of colors and icons.

As individuals we have identities and sub-identities as roles. I don't just have one "work" identity for a single container. Within "work" I am a developer, I am a business owner, I am a network/site administrator. With each role I have different accounts (and aliases) for email, GitHub, Google, Twitter, Facebook, etc. The limited selection of colors and icons doesn't allow me to identify a container by role.

I read the info about why specific colors are allowed based on the worldly experience and trials of Firefox developers. This is completely out of sync with the real-world concept that you have no idea about the full diversity of use cases where this feature will be used, or the themes and applications that will be used with it. A default palette is appreciated, not a limitation to your notion of what looks right for me, or what limited roles I might play in life.

So please extend the API, about:config Options, and the container Preference settings to allow us to use colors and icon assets other than the hard-coded (usercontext.css) values currently set. This includes expanding the number of available assets - so please don't change it to allow only 10 of whatever assets we prefer. Open it up. Disk is cheap. :)

Thanks.

**Comment by grahamperrin** [comment]
> colors

▶ 2017 issue #391

> icons

▶ 2017 issue #843, 2018 issue #1185

@NoumanMasood please close this duplicate. Thank you.

**Comment by houdayec** [comment]
It's been a lot of time now... Don't forget this container feature, it is very helpful. Please add some juicy updates!

**Comment by dannycolin** [comment]
duplicate of #2368 and #391

**Comment by TonyGravagno** [comment]
I disagree with the decision to close this ticket as a dupe of #2368. This ticket is about COLORS and icons. That ticket is only about icons. If that ticket is fully processed and closed, we'll have custom icons and no new colors. The request for more/custom colors needs to remain open for processing in its own right.

I further disagree with closing #1965 as a dupe of #2368 for the same reason.

I do not like the idea that one ticket requested two features. We kinda blew it there. Each feature should be implemented or not, on its own merits and with its own patches.

An older issue cannot be a duplicate of a newer issue. Newer issues should be closed as duplicates of older ones that have already had discussions and evaluations. There was no need to create a single new ticket to represent all of these others, though I understand and appreciate the thought there.

@dannycolin I believe you've unintentionally abused your ability to close issues here, by creating a new consolidated issue that has limited scope, and closing others that have a more broad scope. This would not be the case if #2368 included Colors and Icons ... but if it did it would be a 100% duplicate of this one.

I recommend:

- Re-open this ticket to remove the dupe flag.
- Change the description, removing 'and icons'. So this ticket is just about Colors.
- Tag this with ![label: M-C Platform](https://img.shields.io/github/labels/mozilla/multi-account-containers/needs%3A%20M-C%20Platform).
- If this is a dupe of prior tickets, flag it as such. If others follow this one, asking for colors, flag them as dupes of this one or those prior.

The result should be two open tickets, one for icons and one for colors. This should also be a learning experience : Try not to create duplicate tickets. Try not to request more than one feature in a single ticket. When consolidating tickets, try not to lose details that will result in a final solution that doesn't include proper evaluation of tickets that are now closed as completed.

**Comment by Ahplla** [comment]
I don't understand why this was shut down! This is an essential feature, at least 3 more icons and  colors!

**Comment by achernyakevich-sc** [comment]
> I don't understand why this was shut down! This is an essential feature, at least 3 more icons and colors!

@Ahplla because this one is a duplicate of two older issues. So discussions and implementation will be continued there. See https://github.com/mozilla/multi-account-containers/issues/1566#issuecomment-1133480659
