### ISSUE TITLE
Change design of Sort Tab button

### ISSUE THREAD

**Issue by NoumanMasood** [mozilla/multi-account-containers#1568]
**Please fix this as a priority!**

Sort Tab button design needs to be updated so that user can see the button clearly.

Multi-Account Containers Version: 6.1.1 (and all previous)
Operating System + Version: windows 10
Firefox Version: 70.0 (64-bit)
Other installed Add-ons + Version + Enabled/Disabled-Status: Tree tabs, Onetab, Bookmarks managers, all enabled and used.

### Actual behavior
Currently, sort Tab button design is very bad.
![image](https://user-images.githubusercontent.com/14115229/68053454-c4d1d980-fd0d-11e9-89a4-69575d6366ef.png)

### Expected behavior
It should be like this so that user can see the button clearly.
![image](https://user-images.githubusercontent.com/14115229/68053512-ef239700-fd0d-11e9-8a00-5e908fb9d31f.png)

**Comment by NoumanMasood** [comment]
@groovecoder  @maxxcrawford  Please review it.

**Comment by UnicodeTreason** [comment]
I would argue this has now occurred with the new GUI.
