### ISSUE TITLE
Automatically Create and Enter Ephemeral Container for Uncovered URL

### ISSUE THREAD

**Issue by abhillman** [mozilla/multi-account-containers#1578]
Concrete example: I am in a container for Google.com. I click on a link that is not covered by an existing container. That link creates a fresh, ephemeral container for that domain (or IP). From there, the ability to save the ephemeral container if desired. This helps address the problem of the default (or other container) becoming cluttered with generally identifiable cookies.

**Comment by AndrewKvalheim** [comment]
Sounds like you might be looking for #419.

**Comment by kendallcorner** [comment]
Yes, I believe your reqest should be covered by #419 as Andrew has said, #655, or #914. Please +1 or discuss on those issues. I'll close this, but feel free to reopen if you think it's a different issue.
