### ISSUE TITLE
Managing Cookies

### ISSUE THREAD

**Issue by inyrface** [mozilla/multi-account-containers#1581]
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Win10
- Firefox Version: 70.0.1

### Feature Request
Is it possible to have an interface to manage the cookies in each of the different containers separately?

Also is it possible to be able to rearrange the containers when opening the containers panel?

**Comment by kendallcorner** [comment]
For your cookies question, check out issues #48 and #318 
For rearrange containers: #330 
Please vote or discuss on those issues. I'll close this, but feel free to reopen if you think they are different issues.
