### ISSUE TITLE
[Feature request] Sandbox history and consolidate new tab buttons

### ISSUE THREAD

**Issue by Taur10** [mozilla/multi-account-containers#1583]
Two small feature requests as noted in the title.

Sandbox history, I'd like my new tab page to show pages appropriate to the Tab Container I'm in, ditto for history being sorted by container.

Having new tab and new container buttons is a bit annoying, it'd be nice if the new tab offered a drop down menu or right clicking on it would give me a list of containers to open.

**Comment by kendallcorner** [comment]
> Sandbox history, I'd like my new tab page to show pages appropriate to the Tab Container I'm in, ditto for history being sorted by container.

The history suggestions look like issues #47 and #318. For new tab, checkout #375.
Please vote or discuss on those issues. I'll close this, but feel free to reopen if you think they are different issues.

> Having new tab and new container buttons is a bit annoying, it'd be nice if the new tab offered a drop down menu or right clicking on it would give me a list of containers to open.

Try long pressing/clicking your new tab button :grin:

**Comment by kendallcorner** [comment]
Also link to #1233 for history

**Comment by kendallcorner** [comment]
I keep finding older ones. Original for history issue looks like #537
