### ISSUE TITLE
[Feature Request] Open a predefined homepage instead of the new tabs page.

### ISSUE THREAD

**Issue by HubKing** [mozilla/multi-account-containers#1589]
Currently there seems to be an option to open a website always with a specific container, but that is not always the best option. For example, imaging if you want to use Gmail with three accounts A,B, and C. You can't use "Always open in [container] option for Gmail. You would have to open click the container, which opens the new tabs page, and then you would type the Gmail URL. Or you could open Gmail and then choose "Reopen in container"

But wouldn't it be more convenient & intuitive if you could just specify the default page that is opened when you click a container in the toolbar? For example, in the screen below, if I click "Work", FireFox opens the company homepage instead of a new tabs page.

![firefox-containers-featured-800x400](https://user-images.githubusercontent.com/10900489/69820231-03db4800-1244-11ea-87d3-1993bcaaac51.jpg)

**Comment by manuelcanga** [comment]
+1

**Comment by kendallcorner** [comment]
I think this is the same as #375 . Please vote or discuss on that issue. I'll close this, but feel free to reopen if you think it's a different issue.
