### ISSUE TITLE
Tab instantly closes when last focused window was private window

### ISSUE THREAD

**Issue by kumpelblase2** [mozilla/multi-account-containers#1593]
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Linux 5.3.13, Xorg 1.20.6
- Firefox Version: Nightly 72.0a1 (2019-12-02)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
<details><summary>Full list</summary>

```
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
BetterTTV	7.2.71	true	firefox@betterttv.net
Bing	1.0	true	bing@search.mozilla.org
Default Bookmark Folder	2.10.1	true	default-bookmark-folder@gustiaux.com
DuckDuckGo	1.0	true	ddg@search.mozilla.org
Firefox Color	2.1.5	true	FirefoxColor@mozilla.com
Firefox Multi-Account Containers	6.1.1	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
HTTPS Everywhere	2019.11.7	true	https-everywhere@eff.org
Midnight Lizard	10.4.2	true	{8fbc7259-8015-4172-9af1-20e1edfbbd3a}
Privacy Badger	2019.11.18	true	jid1-MnnxcxisBPnSXQ-eff@jetpack
Proven	2.4.0	true	{f729eea1-320b-4084-93fd-b8c2910b5b48}
Pushbullet	347	true	jid1-BYcQOfYfmBMd9A@jetpack
Stylus	1.5.6	true	{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}
Tab Session Manager	5.1.1	true	Tab-Session-Manager@sienori
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.24.2	true	uBlock0@raymondhill.net
uMatrix	1.4.0	true	uMatrix@raymondhill.net
Vue.js devtools	5.3.3	true	{5caff8cc-3d2e-4110-a88a-003cc85b3858}
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
New container tab	0.2.0	false	{71d4d33f-0bb1-4d92-8389-3f604d62a11a}
Tree Style Tab	3.2.5	false	treestyletab@piro.sakura.ne.jp
Vimium	1.64.6	false	{d7742d87-e61d-4b78-b8a1-b469842139fa}
```

</details>

### Actual behavior
When trying to open a link from an external application which should get opened in a container, a tab opens but gets instantly closed again. This only happens if the last focused window was a private window.

### Expected behavior
Tab does not get closed but stays open and is in the right container.

### Steps to reproduce
1. Allow Multi Account Containers to run in private windows
2. Create a container (say with the name "Google")
3. Open "www.google.com" and tick the box to always open this page in the "Google" container.
4. Open a new private window.
5. Using command line or through other external means, open a link to "www.google.com". E.g. using `firefox-nightly "http://www.google.com"`

### Notes
As stated above, this does _only_ happen, when the last focused window was a private window. I'm not sure if this is in relation to the fact that I'm using a window manager and not a full desktop environment, because I tried to reproduce this on macOS (though using the developer edition) but I couldn't. This is also did not start recently but has probably been an issue for months for me.

**Comment by kumpelblase2** [comment]
I can reproduce it now with normal Firefox (v71) as well. They key I have missed is to allow the extension to also run in private windows. With that disabled, things work fine, but if it's enabled and thus allowed for private windows, the the described behavior is perceived. I've updated the issue accordingly.

Given that I personally don't have any issue disabling that setting, this is therefor no longer an issue for me. Obviously it'd be great if this will get fixed eventually, but I don't mind it to be closed and move on to more important issues.

**Comment by rvandegrift** [comment]
I may be hitting the same issue.

Starting in 6.2.0, any site which is set to auto-open in a container can no longer be opened in a private window.  I sometimes need to view site in my container and outside simultaneously, so it'd be great if this could be fixed.

I used Firefox ESR on Debian buster.  The config screen says "Not Allowed in Private Windows", so I cannot test toggling that option.

**Comment by kendallcorner** [comment]
@kumpelblase2 is that an older version of MAC you set to enable/disable in private windows? 6.2.0 should be permanently disabled in private windows as @rvandegrift points out.

**Comment by kumpelblase2** [comment]
@kendallcorner Yes, since 6.2 was only released this month (IIRC), I was still using the most recent version at that time - 6.1.1. I've kept it disabled since so I didn't see any difference in the new version.

If it's always disabled now, I'll close this as the bug can no longer occur (because it would require it to be enabled in private windows).
