### ISSUE TITLE
Localization into Spanish shows a period in context menu that shouldn't be there

### ISSUE THREAD

**Issue by Pcsl** [mozilla/multi-account-containers#1603]
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Windows 10
- Firefox Version: 71.0 (64 bits)

### Actual behavior
Spanish translation for context menu "Open link in New Container Tab" adds a period at the end: "Abrir enlace en pestaña de contenedor nueva."

https://i.imgur.com/wSMmc2B.png

### Expected behavior
The final period should be removed.

### Steps to reproduce
1. Right click any link

**Comment by kendallcorner** [comment]
This is part of the platform and should be filed over at bugzilla.mozilla.org. If you want to do that, go for it, otherwise, I will try to get to it.

**Comment by Pcsl** [comment]
Oh, sorry, I actually was unsure about what was the right place to post this bug (I even tried to change the translation by myself).
I posted the bug at Bugzilla so I will close this issue.

Thank you!
