### ISSUE TITLE
"when redirects change requestId midflight should uncancel after 2 seconds" test is flaky

### ISSUE THREAD

**Issue by adamjc** [mozilla/multi-account-containers#1606]
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Mac OS Mojave 10.14.6
- Firefox Version: 71.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: fresh install of ff

### Actual behavior
The test 'when redirects change requestId midflight should uncancel after 2 seconds' sometimes passes, sometimes fails.

### Expected behavior
It always passes

### Steps to reproduce
1. clone the repo
2. checkout any commit you'd like
3. run the tests a few times

### Notes
I do realise that the [README](https://github.com/mozilla/multi-account-containers/blob/master/README.md) does say that the test is flaky for some people -- but perhaps we should do something about the test if it's flaky

**Comment by kendallcorner** [comment]
@stoically have you seen this issue? It happens every time on my machine.  Is it possible that it's fixed in your test refactor?

**Comment by stoically** [comment]
@kendallcorner Yep, it's fixed in #1464. Additionally there's a change in nightly that fixes the bug in Firefox once the `dom.serviceWorkers.parent_intercept` pref gets flipped to true in stable. Details in [1437748](https://bugzilla.mozilla.org/show_bug.cgi?id=1437748).

**Comment by stoically** [comment]
#1464 was merged
