### ISSUE TITLE
[Feature request] Implement additional user options

### ISSUE THREAD

**Issue by opus-x** [mozilla/multi-account-containers#1610]
When opening a site in a container (e.g. Bing-search), clicking a link, the new (unassigned) site will stay in the same container thus enabling tracking. Although useful for using different profiles its not secure/private.

**Options to add (user decides behavior):**

- Open new unassigned sites in the default container, temporary container or use current container

- Switch/assign (toolbar) site/tab to different container (assign a new default container for site) _1)_

- Changing to a new container will open a new tab (avoid losing history) or use the current tab

- Option to open web sites in their own containers without assigning (auto-created for TLDs) _2)_

- Possibility to assign a default container for a site when there are multiple containers for the site or specify to assign the last one used.

- Possibility to sort container labels

_1)  Default container in this context is the last one used for the site
2) When reassigned by user the auto-created container is renamed_

**Comment by ecmonsen** [comment]
+1 to "Option to open web sites in their own containers without assigning "

**Comment by DIW79** [comment]
+1 again to "Option to open web sites in their own containers without assigning (auto-created or TLDs)"

This would be a huge improvement in functonality as would the ability to save these new TLDs in containers and to have them automatically assigned to "always open in" their own container!

**Comment by Solid-Ice8** [comment]
Please use Temporary Containers & Simple Tab Groups for combined functionalities of all mentioned.

#1695 #1722

**Comment by grahamperrin** [comment]
> sort container labels

@opus-x you can strike this off your list; it's implemented. Thank you.

**Comment by dannycolin** [comment]
There's a few that can be strike has implemented or that already have been reported. I'm closing this for now because it's better to only have one request per report. 

So feel free to report new reports if there's one of the request that hasn't already been reported.
