### ISSUE TITLE
Issues have "vote for me" label without documentation how voting is done

### ISSUE THREAD

**Issue by RonKaminsky** [mozilla/multi-account-containers#1612]
A label "vote for me" was attached to various issues. However, Github, as far as I can tell, does not allow attaching an accessible description to labels (which would be where I would look for information about how such voting should be done, and how the votes affect the development process).

Without such functionality in Github, the project should explicitly describe what this label means. I'm not sure exactly where is the best place for this description, however. Putting it on the top-level README would be best in terms of being able to find it, but it's possibly not important enough to be put there. The next place might be in "Contributions" which is linked from the top level. Or, a comment could be added to every issue with this label (which would be a lot of work, but the least intrusive).

**Comment by gabschne** [comment]
The "vote for me" label can be seen in many GitHub repositories. It typically means to give the first comment of a issue (which normally describes the issue/bug/feature request) a thumbs up if you are also interested in a feature request. Then, interested people and developers can sort issues by most thumbs up's.

See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github#reacting-to-ideas-in-comments for a little help.

**Comment by RonKaminsky** [comment]
> It typically means

The issue is that any repo using it should **specifically** define what it means. I do not see any information at the linked page you provide about using "thumbs up" for voting (rather than, for example, the "heart", or comments which include special text).

**Comment by gabschne** [comment]
I didn't write that it should not be explained somewhere what it means and how it can be done. My comment was only meant as a help for you, it seemed to me that you didn't know how to vote yourself. Neither did I write anywhere that the link explains how to vote.

However, if others also think it should be specified somewhere how to vote, I would be for a little section about contributing (and also voting) in the README file with some basic and short information and a link to the CONTRIBUTING.md for more detailed explanations.

**Comment by dannycolin** [comment]
Closing as invalid. "Vote for me" label has been removed and feature request will slowly be moved to connect.mozilla.org where there's a builtin voting feature.
