### ISSUE TITLE
Feature request: open bookmark in container from bookmarks toolbar

### ISSUE THREAD

**Issue by ecmonsen** [mozilla/multi-account-containers#1616]
I'd love to be able to right-click a bookmark in the Bookmarks Toolbar, and be given the option to open that bookmark in a specific container, just like when right-clicking a link.

Assigning the website to a container will not work in this case because I want to open the bookmark in different containers on different occasions.

Thanks.

**Comment by gabschne** [comment]
Duplicate of #323.

This issue was resolved by #1537, but there has been no new release of the extension since it was merged.

**Comment by kendallcorner** [comment]
Closed because of duplication
