### ISSUE TITLE
Firefox forgets/looses icons (and sometimes colours) for containers (especially custom and Facebook Container)

### ISSUE THREAD

**Issue by TMMC** [mozilla/multi-account-containers#1618]
**OS/Browser:** Windows 10 (v. 1909) (64 bits)Firefox 72.0.2 (64 bits)

![containers](https://user-images.githubusercontent.com/300390/72782638-91279100-3c24-11ea-9f58-dd7cc86ad499.jpg)

![FB container in URL bar](https://user-images.githubusercontent.com/300390/72782639-91c02780-3c24-11ea-83ab-788e4aefb5be.png)

### Description
- After clicking the 'Multi-account Containers' button, in UI popup the icon of Facebook Container is blank and colour is often set to the first one from the list, though, it is shown correctly in URL bar within container context.
- It seems to be the same problem with custom containers, but I cannot reproduce the problem right now.
- Icons (and sometimes colours) are reset to buggy state each time the browser is restarted.

**Comment by dcormier** [comment]
This looks like #1425.

**Comment by kendallcorner** [comment]
Agree that this is a duplicate. Let me know if you disagree or if you can replicate the other issues you were having. I'll close for now.

**Comment by TMMC** [comment]
Yes, it is, my bad.
