### ISSUE TITLE
Remove 'default container' setting for a domain

### ISSUE THREAD

**Issue by evert** [mozilla/multi-account-containers#1621]
I can't seem to remove the default container setting for drive.google.com and docs.google.com via the UI. "Always remember" seems to be ignored.

Instead, I would like either manually remove these entries, or just clear the entire database with domain settings for containers. Where is this file located? I spent a bunch of time trying to find it but had no luck

**Comment by kendallcorner** [comment]
When you are on the page, you can uncheck the box "Always open in ...", or you can edit the container and delete the sites from the list. I am closing this, but let me know if that does not fix your issue.

**Comment by evert** [comment]
It's weird, I used containers for as long as they are around, but somehow forgot about the add-on menu button in the top-right O_o

sorry for the noise
