### ISSUE TITLE
MAC saves each Temporary Container 

### ISSUE THREAD

**Issue by nnnnicholas** [mozilla/multi-account-containers#1623]
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: WIN 10
- Firefox Version: 72.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status: Temporary Containers

### Actual behavior
MAC creates and saves each newly created Temporary Container

### Expected behavior
MAC does not save Temporary Containers

### Steps to reproduce
1. Open new tab with Temporary Containers Automatic mode activated
2. Observe newly created MAC container (screenshot)

### Notes
![image](https://user-images.githubusercontent.com/1418561/73420437-77efa600-42f0-11ea-831f-3267f34cd355.png)

**Comment by stoically** [comment]
MAC shows all containers added to Firefox using the [native API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities/create), and TCs aren't special somehow, which is why they're listed as well.

**Comment by alongfield** [comment]
Would love to see this changed to exclude tmp containers.  I had to disable sync because it was amplifying the number of these so much.  I had 100+ of them syncing between the various installs of FF that I have.  The UI to configure temp container lifetime seems to have disappeared too, forcing me to need to clean these up after sync by hand.

**Comment by Solid-Ice8** [comment]
I think part of the reason is because TC has the ability to convert temp to perm container and vice versa.

I've tested and It's compatible with MA-C.

**Comment by lestephane** [comment]
Does anyone have a workaround to remove all these temp containers with one command? Going through each one of them manually is just too painful.

**Comment by stoically** [comment]
@lestephane  Maybe https://github.com/stoically/temporary-containers/issues/371#issuecomment-615861439 can be of help

**Comment by abulgatz** [comment]
The temporary containers get saved and are impossible to delete, as they re-appear on sync!
