### ISSUE TITLE
Suggestion: Cloud Based or Export utility

### ISSUE THREAD

**Issue by louddesignstudios** [mozilla/multi-account-containers#1628]
Hello,

Can you make the addon connect to personal email account to sync Containers automatically across
Computers?

Or

At Least Add Import/Export Settings
Had to reconfigure it each time I install on a computer.

All The Best

**Comment by nnnnicholas** [comment]
You're in luck. This is solved in a recent update rolling out now.
https://blog.mozilla.org/security/2020/02/06/multi-account-containers-sync/
https://github.com/mozilla/multi-account-containers/pull/1611

**Comment by kendallcorner** [comment]
Duplicate of #339
