### ISSUE TITLE
Feature request: Add support for deep links

### ISSUE THREAD

**Issue by mvaneijken** [mozilla/multi-account-containers#1629]
Currently Firefox Multi-Account containers support automatic container selection based on the FQDN of the site connecting to. It would be great if this would also be possible for deeplinks with support for wildcards. 

Example (this is a practical example as Microsoft is moving from <name>.visualstudio.com to dev.azure.com/<name>): 

- https://dev.azure.com/tenantA/* --> Container A
- https://dev.azure.com/tenantB/* --> Container B

Links below the specified path are included for this container, examples:
1. Deep link https://dev.azure.com/tenantA/_git/Repo directs to Container A
2. Deep link https://dev.azure.com/tenantB/_git/Repo directs to Container B

**Comment by mvaneijken** [comment]
Never mind, this seems to be possible...

**Comment by cuzza0** [comment]
@mvaneijken Can you share how this is possible?
