### ISSUE TITLE
Edited and deleted default containers are not synced as expected at sync between 2 profiles

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/multi-account-containers#1630]
**Build:**
firefox_multi-account_containers-6.1.5

**Affected platforms:**
Windows PRO 10 64 x bit
MacOS Catalina 10.15

**Affected versions:**
Firefox 74.0a1 (Build ID: 20200210093912)

**Preconditions:**

Create two profiles using profile manager on FF browser, Profile A and Profile B.
Login on both profiles using a Firefox account.
Sync is ON
"Add-ons" and "Logins and passwords" preferences are checked
Install test build "firefox_multi-account_containers-6.1.5" through about:debugging. 

**Steps to reproduce:**

1. On both profiles install the extension and select "Start syncing".
2. On profile A, Add a container using the default suggestion and another custom container. Do not sync yet.
3. Next Edit one of the Default containers and Delete another one. 
4. Navigate to fxa icon and select the Sync Now option from the drop down menu. 
5. On profile B navigate to fxa icon and select the Sync Now option from the drop down menu. Check the extensions popup menu to verify that changes performed to containers on profile A have been synced to profile B. 

**Expected results:**
Changes performed to containers on profile A have been synced to profile B. The Add/edit and delete changes performed on profile A have been synced exactly so on profile B.

**Actual Results:**
On profile B the default containers that have been edited/deleted are still listed in the extension popup menu as they were before being modified. The modified containers are also present.

Note: After another sync the changes from profile B are transferred to profile A so now both profiles display the extra containers. 
Note 2: As mentioned, do not sync before all add.edit and delete actions have been performed. 
Note 3: Could not reproduce this behavior on FF 67 or FF 73. 

![WIN Add Edit Delete Containers between profiles FF74](https://user-images.githubusercontent.com/53306802/74161045-06382600-4c27-11ea-8d5f-5c7ed1830f18.gif)

[FF 74 sync lofg error.txt](https://github.com/mozilla/multi-account-containers/files/4182032/FF.74.sync.lofg.error.txt)

[FF74 console log.txt](https://github.com/mozilla/multi-account-containers/files/4182035/FF74.console.log.txt)

**Comment by kendallcorner** [comment]
This is actually expected behavior

**Comment by kendallcorner** [comment]
https://github.com/mozilla/multi-account-containers/issues/1631#issuecomment-584327581
