### ISSUE TITLE
At sync between devices edited and deleted default containers are still listed in the extension's popup menu

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/multi-account-containers#1631]
**Build:**
firefox_multi-account_containers-6.1.5

**Affected platforms:**
Windows PRO 10 64 x bit
MacOS Catalina 10.15

**Affected versions:**
Firefox 67.0 (Build ID: 20190516215225)
Firefox 73.0 (Build ID:20200207001703)

**Preconditions:**

On device A create two profiles using profile manager on FF browser, Profile A and Profile B,  selecting "Add-ons" and "Logins and passwords" preferences when creating them. 
Login on both profiles using the same Firefox account.
Install test build "firefox_multi-account_containers-6.1.5" through about:debugging.
On a second device B, on the same FF browser version, create a new profile using selecting the same preferences and install the extension through about:debugging. 

**Steps to reproduce:**

1. On device A on both profiles install the extension and select "Start syncing".
2. On device A On profile A perform the exact steps without syncing : Add a container using the suggested name,color, sign, add a customized container. Enter Edit containers and delete one of the default containers and then edit another of the default containers. Then, from the FxA icon drop down menu select Sync Now. 
3. On device A, on profile B, sync now and check that all modified containers have been synced. 
4. On Device B, on the existing profile, login with the same firefox account used on on device A profiles. 
5. On device B, go through the extension install menu and select "Start syncing". 
6. On device B, from the FxA icon drop down menu select "Sync Now."

**Expected results:**
On device B, in the profile's extension popup menu, the exact same containers from Device A profiles are listed. 

**Actual Results:**
On device B, extra default containers (the ones which have been edited/deleted) are listed in the extension's pop up menu. 

[mac console log.txt](https://github.com/mozilla/multi-account-containers/files/4182174/mac.console.log.txt)

![WIN Add Edit Delete Containers between profiles FF73](https://user-images.githubusercontent.com/53306802/74173591-0b9f6b80-4c3b-11ea-9009-bafcbc1515b8.gif)

<img width="1280" alt="Sync from windows to MAC device" src="https://user-images.githubusercontent.com/53306802/74173640-2376ef80-4c3b-11ea-9141-71817ec66ad5.png">

**Comment by kendallcorner** [comment]
This is expected behavior. Since it is possible people have set up an extensive list of containers on two or more machines already, we chose potential duplication over potential destruction of a container. What may look like a default container could be in use on the secondary machine, so we are keeping it.

MAC addon sync matches by name and then by UUID. Until the two profiles have synced once (which can take up to 10 minutes on the new profile if a sync is not forced between profiles), the addon will not connect two containers with the same name, and so will not make any changes to profile B.

**Comment by m-p-3** [comment]
Maybe it would be less confusing to display which browser/device created a container where there is a duplicate name.. I had a sync issue where the same container was duplicated at least 50 times and had no luck figuring out which one was valid. Had to nuke the whole thing.
