### ISSUE TITLE
[Bug]- container fails to open tabs, deletes pinned tabs

### ISSUE THREAD

**Issue by jcmcmurry** [mozilla/multi-account-containers#1632]
- Multi-Account Containers Version: 6.2.0
- Operating System + Version: Windows 10 Ver. 1909
- Firefox Version: 72.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Adblock Plus - free ad blocker	3.8	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Amazon.com			1.1	true	amazondotcom@search.mozilla.org
Auto Tab Discard		0.3.5.2	true	{c2c003ee-bd69-42a2-b0e9-6f34222cb046}
Bing				        1.1	true	bing@search.mozilla.org
DuckDuckGo			1.0	true	ddg@search.mozilla.org
eBay				1.0	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	6.2.0	true	@testpilot-containers
Google				1.0	true	google@search.mozilla.org
Honey				11.11.4	true	jid1-93CWPmRbVPjRQA@jetpack
NoScript			        11.0.13	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Test Pilot			  3.0.6vffecb95	true	@testpilot-addon
Twitter				1.0	true	twitter@search.mozilla.org
Unpaywall			3.90	true	{f209234a-76f0-4735-9920-eb62507a54cd}
Wikipedia (en)			1.0	true	wikipedia@search.mozilla.org
Zotero Connector		5.0.61	true	zotero@chnm.gmu.edu
Containers Sync		1.1.4	false	sync@containers
Dark Reader			4.8.9	false	addon@darkreader.org
Firefox Private Network	18	false	secure-proxy@mozilla.com
Min Vid				0.4.9	false	@min-vid
snoozetabs			1.0.20	false	snoozetabs@mozilla.com
Strict Pop-up Blocker	0.6	false	jid1-P34HaABBBpOerQ@jetpack

### Actual behavior
Pinned tabs do not open when reopening container. Tabs remain listed inside container as though unopened, and the "show this container" button is present, with no reaction when clicked, nor do the greyed pages in the container menu react when clicked.

### Expected behavior
When opening a container, all tabs saved would be opened and loaded, and pinned tabs would open as well and be pinned. After opening, the option to "hide this container" would replace "show this container".

### Steps to reproduce
1. Open a container via opening a previously closed window that was closed by hiding a container.
2. Bugs crawl out from here

### Notes
After facing this issue, I am unable to re-hide the tabs. This wasn't an issue until the most recent update, as I've been reopening one of my containers like this for months now, and closing the container with the close container button. 

Most of these containered tabs were on a site set to "Always open in container", and there are around 30 such tabs, with 4 tabs for sites without this option used. It appears also that the tabs are duplicated and greyed out, and the duplicates won't display or be removed by opening in a new tab or showing container.

EDIT: I tested this with a four-tab container, and the same issue occurs as soon as you add a pinned tab to your container, regardless of how it's opened or what's set to open in the container automatically. So the issue is purely caused by interactions with pinned tabs, and all tabs end up getting saved as duplicates after the pinned tab as greyed out versions (greyed tabs can be cleared if all other tabs are closed in every window, and you click "Move tabs to new window")

**Comment by kendallcorner** [comment]
Did this used to work correctly? Like before the latest release? or were you trying this for the first time?

**Comment by jcmcmurry** [comment]
> Did this used to work correctly? Like before the latest release? or were you trying this for the first time?

Yea it used to. I’ve had pinned tabs in my containers and they worked really well, as they maintained the pin. I didn’t experience issues until after I was informed of the new sync feature (which was the latest release I believe)

**Comment by xdmx** [comment]
I have the same issue, I have multiple containers, and I always pin my tab inside them. Now when I try to open a container that was hidden it doesn't open the pinned tabs. It was working fine until yesterday (before receiving the upgrade for 6.2.0). Now I cannot open all my work/personal/finance open tabs, it's quite blocking :grimacing:

**Comment by pepewu** [comment]
I have the same problem. Pinned containers are not restored anymore.

**Comment by kendallcorner** [comment]
A couple of PRs concerning hiding/unhiding tabs were also in the latest release. We'll take a look.

**Comment by kendallcorner** [comment]
#1541 and #1540 both mention hiding tabs @groovecoder. I will take a look at them.

**Comment by groovecoder** [comment]
Thanks @kendallcorner. If we can fix in time, I think it's fine to do a patch release on a Friday. 😄

**Comment by kendallcorner** [comment]
Looks like it is #1541. Pinned tabs cannot be created as 'discarded'

**Comment by kendallcorner** [comment]
The last update should have fixed this problem. Let me know if you have any more issues.
