### ISSUE TITLE
Saved tabs error

### ISSUE THREAD

**Issue by remoteflying** [mozilla/multi-account-containers#1640]
I have some tabs of several opened containers. When I wanted to close a container, it only shows me the option "Show this container" and not "Hide this container" as it should be. When closing all the tabs of a container, the option "Show this container" still appeared but no tabs open when I click on it. Also, I opened Firefox and opened a tab to the same container I'm using and it opens tabs that I had previously closed. 

This error may happen because I open a tab from another container and all the tabs from that container open at same time. I used to do that a lot to store some links and then click on "Hide this container" to close opened container. However, it should work fine doing this.

**Comment by kendallcorner** [comment]
Did you happen to store a pinned tab with that tab group? There were some issues with the last release. It added a feature that brings the hidden tabs back in the `discarded` (unloaded) state. Pinned tabs are not allowed to be in that state, and this was causing what you are describing.

If no pinned tabs, where these any other kinds of nonstandard urls/tabs that you saved? Like reader formatted pages or `about:` pages? We'll have to investigate if we missed some other items that `discarded: true` is not allowed for. Thanks!

**Comment by kendallcorner** [comment]
Forgot to say. You should be getting an update in teh next couple of days to fix this if it is a pinned tab issue.

**Comment by grahamperrin** [comment]
@remoteflying please, is this still an issue? With Firefox `88` …

**Comment by dannycolin** [comment]
Closing as stalled.
