### ISSUE TITLE
"Always Open In This Container" breaks Private Windows

### ISSUE THREAD

**Issue by rvandegrift** [mozilla/multi-account-containers#1647]
- Multi-Account Containers Version: 6.2.1
- Operating System + Version: Debian buster
- Firefox Version: 68.5 ESR
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.0	true	bing@search.mozilla.org
Cookie AutoDelete	3.0.3	true	CookieAutoDelete@kennydo.com
Decentraleyes	2.0.13	true	jid1-BoFifL9Vbdl2zQ@jetpack
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	6.2.1	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
Google search link fix	1.6.9	true	jid0-XWJxt5VvCXkKzQK99PhZqAn7Xbg@jetpack
HTTPS Everywhere	2019.11.7	true	https-everywhere@eff.org
Tab Reloader (page auto refresh)	0.3.0	true	jid0-bnmfwWw2w2w4e4edvcdDbnMhdVg@jetpack
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.24.4	true	uBlock0@raymondhill.net
User-Agent Switcher and Manager	0.3.4	true	{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org

### Actual behavior

If I assign "example.com" to a container and click the "Always Open In <this container>" box, I can no longer open example.com in a private window.  The private window closes.

I often need to see a logged-out view of a site while remaining logged in via the container window.  This worked normally through 6.1.

### Expected behavior

Sites opened in a private window should not trigger any behavior from multi-account-containers.

### Steps to reproduce
1. Create a container "testing"
2. Open "mutt.org" (or whatever) in a testing container.
3. Enable "Always Open In testing"
4. Open a new Private Window
5. Browse to mutt.org in the Private Window.  It closes immediately.

**Comment by kendallcorner** [comment]
Also: https://github.com/mozilla/multi-account-containers/issues/1593#issuecomment-586514981

**Comment by kendallcorner** [comment]
Oh wait, that's you. You filed your own bug. :+1: 

I can't reproduce this, and the addon should be completely disabled in private browsing mode, so I'm not sure how this would be happening, but I'm interested to see if anyone else has this problem as well. In the meantime, you could try removing and reinstalling the addon.

**Comment by igorkurpis** [comment]
It happens to me also. It worked fine like a week or two ago, but recently, when I try to open page that has been assigned to a specific container nothing loads (if it's the only tab) or tab close imediatly (if I have other tab open).

Multi-Account Containers Version: 6.2.1
Operating System + Version: Debian buster
Firefox Version: 68.4.1 ESR

**Comment by rvandegrift** [comment]
I just removed & reinstalled and the add-on and it works now.

For others with this issue - I didn't lose any container assignment configuration.

Thanks @kendallcorner!

**Comment by igorkurpis** [comment]
Still don't work for me. Multi-account container works in private windows, and block site assigned to containers.

https://postimg.cc/gL2mB3n9
