### ISSUE TITLE
Can't install the extension

### ISSUE THREAD

**Issue by YandLiu** [mozilla/multi-account-containers#1652]
No matter the `privacy.userContext.enabled` in `about:config` is `false` or `true`, when I installed the extension, it always prompted me
> The add-on downloaded from this site could not be installed because it appears to be corrupt.

**Comment by kendallcorner** [comment]
The install should flip that preference for you. You shouldn't have to do it manually. Can you restart your browser and make sure it is up to date? Maybe clear you cache?

**Comment by YandLiu** [comment]
I cleaned the cache and restarted the browser, and downloaded the extension first then dragged it into the browser to install, the problem still exists.

**Comment by kendallcorner** [comment]
Ah. You are not installing from: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ ? 

You are installing from an xpi file? Are you getting the file our releases page on Github?

**Comment by YandLiu** [comment]
I just found I could install the 6.1.1 version extension from GitHub releases, but still couldn't update to 6.2.1 or 6.2.0 on AMO or through the local XPI file, nonetheless I can install other extensions on AMO or through local XPI files normally.

**Comment by kendallcorner** [comment]
So when you click "Add to Firefox" on this page: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ you're getting an error? Which version of Firefox are you running (Nightly, Developer, Release)? And what OS are you using? Did you download the browser installation directly from Mozilla?  Right now you are the only one with this problem, so I'm thinking it has something to do with your browser. You could try uninstalling, downloading direct from Mozilla (firefox.com), and reinstalling

**Comment by YandLiu** [comment]
I finally figured out the cause, it is I set `extensions.allowPrivateBrowsingByDefault` to true.

**Comment by kendallcorner** [comment]
oooh. weird. Thanks for figuring that out. Might be a firefox bug.

**Comment by kendallcorner** [comment]
Yes, looks like it's a platform bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1600423
And that they're planning on removing the pref so this doesn't happen.
