### ISSUE TITLE
Debugging is difficult

### ISSUE THREAD

**Issue by adamjc** [mozilla/multi-account-containers#1653]
I'm trying to implement a feature to add arbitrary URLs to containers. My test is failing, but I do not know how to either:

a) set breakpoints to pause on execution, given how we're running the tests
or
b) log out useful error messages while running the container plugin locally. Running the `./node_modules/.bin/web-ext run -s src/ --verbose` command seems to eat any `console` messages.

Can anyone suggest a nice feedback loop for debugging? 🙏

**Comment by stoically** [comment]
a) `npm run test:watch -- --inspect-brk`, then attaching from e.g. chrome via `chrome://inspect` and setting breakpoints using `debugger;` statements works fine for me
b) the log output goes to the add-ons console (background or popup), `about:debugging#/runtime/this-firefox` and clicking "Inspect" next to MAC gives you that

Also https://github.com/mozilla/multi-account-containers/pull/1627 looks like it's meant to allow arbitrary URLs.

**Comment by adamjc** [comment]
excellent, thank you. Looks like someone has beaten me to it! :)
