### ISSUE TITLE
Where to translate

### ISSUE THREAD

**Issue by Mejans** [mozilla/multi-account-containers#1659]
Hello,
I have been searching in vain, I cannot find here to translate this extension.
Could someone tell me please?
Best regards

**Comment by kendallcorner** [comment]
I don't think we're set up for translations yet. Right, @groovecoder ?

**Comment by dannycolin** [comment]
You can translate the addon on https://pontoon.mozilla.org/it/firefox-multi-account-containers/ and learn more on translating Firefox products on https://community.mozilla.org/en/activities/localize-mozilla/. Closing for now.
