### ISSUE TITLE
Simple change, big improvement, Move Close Button

### ISSUE THREAD

**Issue by ShonkaiDJ** [mozilla/multi-account-containers#1660]
I think it would be a very good idea to move the 'close' button to the front of the URL.
My first thought was to make the window size flexible or to state that there is an issue with the scroll bars, but moving the close button is the easiest way to remove pinned URL's from a container.

![MoveCloseButton](https://user-images.githubusercontent.com/29199283/75232659-e6246d00-57b7-11ea-845d-6f163440eae6.JPG)

**Comment by dannycolin** [comment]
Closing since the UI changed in the recent version of the addon and this shouldn't be a issue anymore. If you still experience a similar bug, please feel free to open a new report.
