### ISSUE TITLE
Can no longer open new container tab by ctrl+. followed by a number

### ISSUE THREAD

**Issue by kerhong** [mozilla/multi-account-containers#1666]
- Multi-Account Containers Version: 6.2.2
- Operating System + Version: Manjaro 19, Gnome
- Firefox Version: 74.0b7 (64-bit), Developer Edition, Linux
- Other installed Add-ons + Version + Enabled/Disabled-Status: -

Before version 6.2.2 it was possible to open a new tab by `ctrl+.` followed by number of the container you wished to open. (ex: `ctrl+.`, `3` would have opened a Banking tab in the default configuration). Now pressing any number while the containers menu is open starts the introduction sequence (multiple steps with 'Next' button introducing add-on features).

### Steps to reproduce
1. Press `ctrl+.`, see containers menu is opened
2. Press `3`
    1. (actual) The add-on introduction sequence starts.
    2. (expected) New tab in 'Banking' container is opened. (this worked before 6.2.2)

### Notes
I am not sure if this was a real feature or just a happy unintended feature. In either case- this shortcut was very useful and convenient.

**Comment by rdgoite** [comment]
Came here to report the same issue. In my case instead of showing the introduction sequence, I'm asked if I want to sync my containers using my Sync account.

**Comment by CalRobert** [comment]
Just had this hapen as well; makes the plugin basically unusable sadly. I'm always prompted by the "put containers to work for you" popup

**Comment by kendallcorner** [comment]
I'll take a look.
