### ISSUE TITLE
container menu list is not visible

### ISSUE THREAD

**Issue by oshanz** [mozilla/multi-account-containers#1668]
- Multi-Account Containers Version: 6.2.3
- Operating System + Version: ubuntu 18.04
- Firefox Version: 74.0b8 (64-bit) Developer Edition
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
sometimes when I click the container button, its container list menu is not visible.
I can see that, Its like that menu opened, but under the html window.

### Expected behavior
menu list should be visible above the web page.

### Steps to reproduce
1. just click the button. randomly this happens. mostly on every other click.

### Notes

**Comment by dannycolin** [comment]
This was an issue with Firefox itself and should be fixed by now so closing. If this happens again, please file a bug report on bugzilla.mozilla.org.
