### ISSUE TITLE
Suggestion: Locked to contaner links

### ISSUE THREAD

**Issue by VoinNochi** [mozilla/multi-account-containers#1671]
Greetings!
Sometimes I need to open same link in different containers, so "Always open in" function doesn't always fits. So I have another variation of feature to suggers.
Please, add ability to lock/attach links to container. I mean, I want to click container, and it opens all attached to it links. If I close part of them, I can click container again to reopen attached missing ones. For now, it removes links from conteiner if I close them.

**Comment by dannycolin** [comment]
There's a "Limit to designated sites" in the container settings for this. Closing for now.
