### ISSUE TITLE
Suggestion: Menu functions

### ISSUE THREAD

**Issue by VoinNochi** [mozilla/multi-account-containers#1672]
Greetings!
Please make buttons:
1. If I click RMB on conteiner tab, I'd like to see function "Hide all container tabs"
2. If I click RMB on container in plugin, I'd like to see function "Delete all cookies", "Clear history" or something similar.

**Comment by dannycolin** [comment]
Thanks for the suggestions. However, we already have a report for this features that have been filed in separated bugs. So I'm going to close this one because it's easy to track one issue per bug report.
