### ISSUE TITLE
Suggestion: More Colours / Alphabetical

### ISSUE THREAD

**Issue by MoFish** [mozilla/multi-account-containers#1673]
**Firstly, this tool has saved me lots of headaches - so thank you.**

**I'm running out of colours for the little icons.** 
Can we either have more choice or ability to specify RGB?

**I have many projects saved, however no ability to re-order them**. 
Is it possible to add ability to order them or alternatively order them alphabetically? A-Z

Thanks!

**Comment by Solid-Ice8** [comment]
Looks like you've made this suggestion before I have and...it hasn't been implemented all this time.

There's no way to auto sort containers, so you'll need to manually sort 'containers.json'. If your not sure how, go to my reference: #1707

**Comment by alexanderadam** [comment]
These should be two issues. The ordering issue is #330

**Comment by grahamperrin** [comment]
@alexanderadam please see the responses to https://github.com/mozilla/multi-account-containers/issues/1866#issuecomment-765571770

**Comment by dannycolin** [comment]
Closing in favor of #1866 for sorting order and #391 for more colors.
