### ISSUE TITLE
Suggestion: Prompt for Container

### ISSUE THREAD

**Issue by FestTestQA** [mozilla/multi-account-containers#1674]
This add on is fabulous.

Scenario - i use Office365 online logging into my accounts from various orgs using this addon.

Given that each account has identical URL's, i cannot set 'Always Open in...' for these. So when i open a link say from my email to an Office item, it will not be forced into the correct container.

Therefor i suggest, that where 'Always Open in X' for a URl is set to more that one container, a prompt/dialog/combo/radio etc should be triggered to redirect to selected container when that url is reached

**Comment by grahamperrin** [comment]
Please try [Always In Container](https://addons.mozilla.org/addon/always-in-container/).

**Comment by dannycolin** [comment]
Duplicate of #1171
