### ISSUE TITLE
Feature request: make containers work like Chrome's "people".

### ISSUE THREAD

**Issue by nimbling** [mozilla/multi-account-containers#1678]
Chrome's "people" are fully top level instances of the browser. When catching an opened link, the "current" or last open "person" is used to open it. I think Firefox's multi account should behave like this.

I have looked through the "similare issues" that cover similar ground but here's hoping my two cents help somehow.

I'm on OSX, I don't know if containers behaves better on windows.

I might be asking the wrong project, is there a more top level split in profiles for firefox than this extension?

• Please have a new tab open in the current container. Not in "default".
(edit: I see the sticky container solves this somewhat: https://addons.mozilla.org/en-US/firefox/addon/sticky-window-containers/ )
• Please allow a different theme per container.
• I'd like to be able to switch container using a shortcut.
• Please allow forcing separate containers to separate windows.

Personal take on this (highly opiniated, I'm aware your use case might differ).

The mental hierarchy of "where am I browsing this" is just really well done if the whole browser is it's own color / theme. And I have a work gmail and a personal gmail open, they need to look different. When I have personal and work profiles, I actually don't need "banking" or "shopping" - as I do those things under personal or for work.

Do other recognize this desire for a slightly different sorting of this concept?

**Comment by es50678** [comment]
This would be absolutely amazing! The "People" feature in chrome is probably the only reason I'm still using it as opposed to firefox. Not sure how many other people feel the same way as us, but I'm definitely onboard with making containers have better parity with "People" in chrome.

**Comment by dannycolin** [comment]
Closing as this is something that'd need to be implemented in Firefox itself and there's nothing we can do on our side.
