### ISSUE TITLE
Authorize only sites from a specific (sub)domain in a container (manage container by sub-domain)

### ISSUE THREAD

**Issue by b3** [mozilla/multi-account-containers#1680]
This is a feature request.

As of today when using MAC one can only specify that certain sites should be affected to a container. 

IMHO, this led oftenly to unexpected **bad** behavior :

- create a container for let's say mail.google.com and set it up so that it always open this site in the container
- open the website and click on a link in this website (let say twitter) :  the link is open in the same container (aka the Google one)
- open a new URL in another tab (assigned to no specific container) and go calendar.google.com then the link is open in container not being the google one 

That way privacy is not really nicely ensured since Google knows that I went on twitter, and UX is not that fun when I want to sandbox a full domain (service provider). Furthermore if I want to sandbox all Google activity in a container I have to open, at least once, every site of Google in the right container and then set it up to always open in that container.

It could be really nice (and good for privacy) that : 
1. one could specify that every site under a specific (sub)domain must be open in a specific container
2. on could specify that only site from this (sub)domain should be open in a specific container. This will mean that when I open a link from one container (let say the Google one) to another site (not in the same (sub)domain) then it is open in another container (a default one).

I think that privacy wise that will be a **major** enhancement.

**Comment by djee-ms** [comment]
Going beyond that, for sites like github.com or dev.azure.com where one might have some personal and/or professional login it would be a great improvement to be able to have partial URL matching via regex for example.

PS: This extension is wonderful, thanks!

**Comment by b3** [comment]
The part 2 of my request seems to be already implemented in recent version of this wonderful extension through the *Limit to Designated Sites* in the *Manager container* tab.

**Comment by dannycolin** [comment]
Yes 2 is already implemented with "Limit to designated sites" :).

For 1, there's #473 that already exist and we're currently working on a patch for that in #2352. We plan to only limit this user-friendly wildcard to root domain (e.g. [all].domain.tld) but not subdomains (e.g. [all].subdomain.google.com). The latter are very rare and your use case should be covered by the former ;). 

However, we also have #691 that you can upvote for a feature that supports more complex URL patterns.

So, I'm closing in favor of #473 and fingers crossed we can get it merged soon!
