### ISSUE TITLE
_Open in Current Container_ button stopped working

### ISSUE THREAD

**Issue by thomasstache** [mozilla/multi-account-containers#1682]
The "_Open in Current Container_" button stopped working for me, where I expect the tab to open without any special container, i.e. the "_Default_" container.

The same if I try the "Open link in Container..." context menu, which brings me to this page: 

![image](https://user-images.githubusercontent.com/649190/76637032-579b4400-654a-11ea-96b3-965e28df3431.png)

"_Open in Shopping_" is a no-op. It always picks the assigned colored container for the domain.

Addon:
Version: 6.2.3
Last Updated: March 2, 2020

Firefox: 75.0b3 (64-bit) Windows 10

**Comment by thomasstache** [comment]
sounds similar to #1331 , so this seems to break again and again?

**Comment by arashpayan** [comment]
This has been happening to me for a couple weeks as well.
Firefox Nightly: 76.0a1 (2020-03-16) (64-bit)
Addon version: 6.2.3 (last updated February 28, 2020)
OS: Ubuntu 18.04

**Comment by michaelschufi** [comment]
Happens for me as well. The grey "Open in {current} container" button behaves like the blue button does. It is clickable for me but I still get redirected to the currently assigned container for the target domain.
Firefox: 75.0b7 (64-bit)
Addon version: 6.2.3, February 29, 2020
OS: Windows 10 Pro 10.0.18363 Build 18363

**Comment by basi01** [comment]
Count me in.
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
Addon version: 6.2.3

**Comment by groovecoder** [comment]
Submitted 6.2.5 to AMO. Should be reviewed & distributed soon.
