### ISSUE TITLE
Suggestion: Pattern match for new externally-opened URLs

### ISSUE THREAD

**Issue by fluffy-critter** [mozilla/multi-account-containers#1684]
### Actual behavior

Opening a link in an external application (mail, slack, etc.) always opens it in the default container, meaning I often have to copy-paste the link into a new, manually-opened container tab.

### Expected behavior

I'd love to be able to give pattern match rules to automatically select a container based on certain domains or paths; for example, I want GitHub links to always open in my default container, *unless* it's a link that points to my work organization, in which case I want it to open in my "work" container.

So for example, if I could specify a pattern of `https://github.com/example-org/*`, then a link to `https://github.com/example-org/some-repo/issues/243` would open in that container.

**Comment by gkaklas** [comment]
@fluffy-critter I believe this is a duplicate of issue 976, which was closed as a duplicate of #691 🤔 If this is the case, I believe it is ok to close this

**Comment by fluffy-critter** [comment]
So it is! Closing.
