### ISSUE TITLE
Containers on Multi Facebook NOT working

### ISSUE THREAD

**Issue by divmonkey** [mozilla/multi-account-containers#1690]
I've created two profile for two different facebook accounts. It can only do 1 account even if you click the other profile.

**Comment by Solid-Ice8** [comment]
I've tested using 2 Facebook (& Twitter) accounts, it works fine.

It'll work as long as you do **NOT**:

1.  Assign "www.facebook.com" to `Always open in *container name*`.
2. Use the add-on "Facebook Container".

**Comment by dannycolin** [comment]
> In example above, if you assign Facebook website to Always open in "Facebook2", you've basically locked yourself out from using multiple accounts. You will be forced to log out of one account to use another.

Exactly this. Make sure you haven't assigned Facebook to one of the container. If it's the case, you remove it (See: https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#remove-always-open-in-site-from-a-container)

Closing for now but let me know if it didn't solve your issue.
