### ISSUE TITLE
Localization possible?

### ISSUE THREAD

**Issue by EverEve** [mozilla/multi-account-containers#1694]
Hello, I wish to translate the addon in Italian. Is it possible? Thanks.

**Comment by dannycolin** [comment]
Multi-Account Containers is, for some time now, available in Italian. If there's anything missing in the translation, feel free to open a pull request on our localization repository (https://github.com/mozilla-l10n/multi-account-containers-l10n). You can also help with the translation via https://pontoon.mozilla.org/it/firefox-multi-account-containers/.

Closing for now. If you have more question about translation and how you can help the community, see https://community.mozilla.org/en/activities/localize-mozilla/.
