### ISSUE TITLE
"switch to tab" feature does not work when targeting tab in another container

### ISSUE THREAD

**Issue by VannTen** [mozilla/multi-account-containers#1705]
- Multi-Account Containers Version: 6.2.3
- Operating System + Version: Archlinux (kernel 5.6.3)
- Firefox Version: 75.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Amazon.co.uk	1.1	true	amazon@search.mozilla.org
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
CanvasBlocker	1.2	true	CanvasBlocker@kkapsner.de
Decentraleyes	2.0.14	true	jid1-BoFifL9Vbdl2zQ@jetpack
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	6.2.3	true	@testpilot-containers
FoxyProxy Standard	7.4.3	true	foxyproxy@eric.h.jung
Google	1.0	true	google@search.mozilla.org
HTTPS Everywhere	2020.3.16	true	https-everywhere@eff.org
LessPass	9.1.4	true	contact@lesspass.com
Privacy Badger	2020.2.19	true	jid1-MnnxcxisBPnSXQ@jetpack
Tampermonkey	4.10.6112	true	firefox@tampermonkey.net
Temporary Containers	1.8	true	{c607c8df-14a7-4f28-894f-29e8722976af}
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.26.0	true	uBlock0@raymondhill.net
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org

### Actual behavior

When I am in a tab in a container, if I click in the search bar and start typing, if there is a match with a tab **in the same container**, I get the option "Switch to tab" instead of going in the current tab to that address. But if the tab is in another container, it is not found.

### Expected behavior

The "Switch to tab" feature work across containers, and I can go back to a tab without having to search it amongst my many tabs :)

### Steps to reproduce

1. Open 2 tabs (A and B) in container "container_1" , 1 in container "container_2" (C)
2. Go to C, start typing A address in search bar. No "switch to tab "option
3. Go to B, start typing A address in search bar. "Switch to tab" option appears

### Notes

I use a lot of tabs, mainly because of my usage of Temporary Containers. It would be nice being able to use that search amongst my tabs, instead of either search manually or open a new tab everytime.

I don't see any security implications (i.e, defeating the purposes of Multi-Container Account) on this, since the search bar is not part of the page, is it ?

Thanks a lot :+1:

**Comment by zetok** [comment]
As a workaround there's https://addons.mozilla.org/en-US/firefox/addon/tab_search/ , works with containers just fine.

**Comment by jayenashar** [comment]
`%` in address bar to show only matches in your currently open tabs, also doesn't work well with this plugin

**Comment by 9p4** [comment]
Set `browser.urlbar.switchTabs.searchAllContainers` to true to resolve.

**Comment by dannycolin** [comment]
Fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1882815
