### ISSUE TITLE
There are more containers out there...

### ISSUE THREAD

**Issue by Solid-Ice8** [mozilla/multi-account-containers#1709]
Keep in mind there's more containers out there than just Multi-Account Containers. These include Facebook Container and other forked versions (Google & Twitter).

For those that care about track blocking & security, these can help you prevent that. However, the downside to these is that it won't allow multi log-in. Perhaps make separate profiles for personal & work? Only my suggestion/opinion.

From my testing, majority of the *.google.com will open in this container. GMail, docs, drive.etc; all of it worked. Additionally, I've even tried like "docs.google.ca" (Canada side). I'm sure the site doesn't exist; but it still opens up in Google container.

I'm no expert on coding, perhaps someone can check the source code in [Google Container](https://github.com/containers-everywhere/contain-google) to see if they're already using wildcards.

And if there's users that consistently have a heavy amount of tabs open, you can consider using **Simple Tab Groups** &/ **Tree Style Tabs**. Both add-ons are sidebar based.

_As a bonus, Simple Tabs Group has functionally for Temporary Container too!
Right-click any link > Open link in group > Temporary Container (with the glasses icon, look familiar?)_

**Comment by Apromixately** [comment]
You seem to be replying to something else or just commenting. If there is one I'm not sure what your issue is.

**Comment by Solid-Ice8** [comment]
Yeah, no issues here. I was commenting on some of the (intensive) issues around & giving some of my suggestions others may find useful.

Specifically:
1) Wildcard domain issues - Counterise could be the solution.
2) Change container tab to normal tab - Huge security risk, let alone all those tracking.
3) I question how people use this add-on. Organizing & categorizing?

I don't believe they're using it for the intended purpose. You may close this 'issue' if anything.

**Comment by bobpaul** [comment]
Please close this issue. This is not a discussion forum. Issues are meant as a TODO list for the developers and if you don't close it, someone from the project will have to spend time closing it. Pruning/sorting issues is surprisingly time consuming and we can all see there's a large backlog of (mostly duplicate) issues.
