### ISSUE TITLE
M-A C Button click only works every 2nd click

### ISSUE THREAD

**Issue by rpedrica** [mozilla/multi-account-containers#1715]
- Multi-Account Containers Version: 6.2.5
- Operating System + Version: Slackware Linux 15 64bit
- Firefox Version: 75
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Adblock Plus - free ad blocker	3.8.4	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Amazon.co.uk	1.1	true	amazon@search.mozilla.org
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
Chambers (UK)	1.0	true	chambers-en-GB@search.mozilla.org
Country Flags & IP Whois	0.3.4	true	{802a552e-13d1-4683-a40a-1e5325fba4bb}
Double-click Image Downloader	7.0.0	true	jid1-xgtdawe3yyUeBQ@jetpack
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Firefox Lightbeam	2.1.0	true	jid1-F9UJ2thwoAm5gQ@jetpack
Firefox Multi-Account Containers	6.2.5	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
Google Translator for Firefox	3.0.3.3	true	translator@zoli.bod
HTTPZ	0.12.0	true	httpz@cm.org
KeePassXC-Browser	1.6.2	true	keepassxc-browser@keepassxc.org
Mailvelope	4.3.1	true	jid1-AQqSMBYb0a8ADg@jetpack
Netcraft Extension	1.15.5	true	{0e10f3d7-07f6-4f12-97b9-9b27e07139a5}
Search by Image	2.2.0	true	{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}
SQRL	0.0.56	true	sqrl@pass.dog
To Google Translate	4.0.6	true	jid1-93WyvpgvxzGATw@jetpack
Twitter	1.0	true	twitter@search.mozilla.org
Video DownloadHelper	7.3.9	true	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Bitwarden - Free Password Manager	1.43.4	false	{446900e4-71c2-419f-a6a7-df9c091e268b}
Tab Groups	2.1.4	false	tabgroups@quicksaver

### Actual behavior
Every 2nd click of the M-A C toolbar button results in a partial expansion of the menu. Every alternate click results in the full menu.

### Expected behavior
Every click of the M-A C button should result in the full menu displaying.

### Steps to reproduce
1. Click on toolbar button - see menu display
2. Click a 2nd time on toolbar button - only the top part of the menu is displayed
3.

### Notes
This issue seemed to start when upgrading to FF75.

**Comment by rpedrica** [comment]
Adding a screenshot of the issue.
![mac](https://user-images.githubusercontent.com/1016286/79477173-2b238d80-800a-11ea-92cb-f3466d0beb51.png)

**Comment by Solid-Ice8** [comment]
Have you ever edit `containers.json`?

Making minor errors could cause this issue.

**Comment by rpedrica** [comment]
Hi there

It seems this issue has resolved it self or was only a temporary issue. The drop panel is working on each click. now.

I can't recall specifically about containers.json but I have a vague idea that yes there may have been some editing in the past due to a previous issue.

I'll remove Tab Groups nonetheless. Thanks for your reply and help.
