### ISSUE TITLE
Replace windows.WINDOW_ID_CURRENT with a tabs.query to support GeckoView

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/multi-account-containers#1716]
From experimenting with MAC on GeckoView, we would need to change usages of `browser.windows.WINDOW_ID_CURRENT` to query for the active session instead:

```js
tabs.query({ active: true, currentWindow: true})
```

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1630144#c2

**Comment by jonalmeida** [comment]
@groovecoder I'm not sure what priority this is for MAC but there was a question about it on the GV matrix channel.

**Comment by dannycolin** [comment]
Closing this for now since containers aren't supported on Android. We'll revisit it when it is.
