### ISSUE TITLE
Order your containers in the container list?

### ISSUE THREAD

**Issue by Lutando** [mozilla/multi-account-containers#1718]
I am wondering if there is a way to order your containers in your container list. Right now it looks like this for me 

A
B
C
D

but I want it to be

D
A
B
C

Can I do this?

**Comment by Solid-Ice8** [comment]
Please read my reference: #1707.

**Comment by Lutando** [comment]
Thank you @Solid-Ice8. I guess ill use that workaround :) no problem for me.

I will close this issue.
