### ISSUE TITLE
rearrange the containers

### ISSUE THREAD

**Issue by guy1234-art** [mozilla/multi-account-containers#1720]
please
how can i rearrange the containers ?
now the first container i did is in the top of the containers 
but i want to put in one the last of the containers

**Comment by Solid-Ice8** [comment]
Please read my reference:  #1707

**Comment by alexanderadam** [comment]
Duplicate of #330

**Comment by dannycolin** [comment]
Duplicate of #330 indeed. See also #1608 for the Pull Request that introduced the ability to reorder containers.
