### ISSUE TITLE
Improvement request: follow link in no container tab

### ISSUE THREAD

**Issue by pierods** [mozilla/multi-account-containers#1722]
Since the goal of having multiple containers is not to be followed around with cookies, the default behavior of opening a clicked link is not optimal:

- if the link points to the same site, it will be opened in a new tab of same container : good
- if the link points to a site connected with a container, it will be opened in that container: good

The problem comes when I follow a link to an external site not connected to a container, in which case it is opened in the same container. Logic wants that, in order not to be followed around, the link is opened in a no container tab.

Example: I create a container for facebook. I read facebook's timeline and I click on various links (some internal to facebook, some external). The external links are opened in the same (facebook) container. Facebook is now following all of my clicks, excepts the ones connected to a container: but I cannot possibly create a container for every site I go to, rendering containerization less effective

Proposed behavior:
- links to an external site not associated to a container are opened by default in a no container tab.

**Comment by rr0ss0rr** [comment]
For Privacy, wouldn't you want to open an external site in a temporary container?  Once deleted, cookies/trackers are trashed.  I'm surprised that MAC doesn't have this ability built in.  Currently relying on "Temporary Containers" to perform this.

**Comment by pierods** [comment]
Temporary containers is nice, and yes, it could improve Containers, but it doesn't fix the problem: you have to right click and then select "open in a temporary container", which means that by default, containers don't do what they are supposed to do (don't open external links in the same container).

**Comment by Solid-Ice8** [comment]
@pierods 
> you have to right click and then select "open in a temporary container", which means that by default.
You can make this behavior default if you've looked around Temporary Container's "Options".

You can enable 'Automatic Mode'. which I quote the description:

> Automatically reopens tabs in Temporary Containers when:

- Opens a new tab
** - Tab tries to load a website in No Container **
- External program opens a link in the browser

I know by default, MA-C should have a 'No Container' container and yes, it should have, but it doesn't...and looks like it has been that way for a long time. I bolded the middle line as I believe this is what you're intended use and meaning is (and it's also mine)

I haven't used right-click > select "open in Temporary Container" at all. I have always used middle click to open a new tab...and after adding in Temporary Container, this has not changed.

As far as I know, before I added TC, middle click will either go to default (no actual container) or it will open a new link in an active container.

Adding TC & with automatic mode will re-direct MA-C's default; non-container into the Temporary Container.

However, if you choose "Hide Number" (also in Options), you'd have to be careful. Every 'new tab' will also make a 'new Temp Container#'.

**Comment by pierods** [comment]
Thanks, that helps. Let's hope the developers pick up the request.

**Comment by grahamperrin** [comment]
@pierods [Always In Container](https://addons.mozilla.org/addon/always-in-container/) is not what you initially requested, however if you try it: 

* does it reshape your thinking in any way?

**Comment by dannycolin** [comment]
You need to enable "Limit to designated sites" for the external links (any sites not assigned to the container) to open in the default "no container". 

Closing for now.
