### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by barefootrails** [mozilla/multi-account-containers#1729]
Would like the ability to open a new container tab where the new tab starts with a copy of the original tabs cookie and session data. My specific use case is AWS Single sign-on. You authenticate into the system then you use a menu jump into various AWS accounts. but you cannot be in two accounts at the same time. Containers would solve that except that when you go into the new container, you lost your original sign credentials and need to sign in again.

**Comment by dannycolin** [comment]
Closing as expected behavior. Containers main concept is to isolate cookies from each others at all time.
