### ISSUE TITLE
Tor: The add-on downloaded from AMO appears to be corrupt.

### ISSUE THREAD

**Issue by jtagcat** [mozilla/multi-account-containers#1735]
All other extensions download fine from AMO, why don't the containers?
![image](https://user-images.githubusercontent.com/38327267/81467496-7f183100-91c8-11ea-854c-a8c49db79229.png)

**Comment by bug-repport** [comment]
Yes, I confirm, correct as soon as possible please!

**Comment by bug-repport** [comment]
found the source of the problem in the closed ticket
extensions.allowPrivateBrowsingByDefault to false 

https://github.com/mozilla/multi-account-containers/issues/1652

**Comment by jtagcat** [comment]
> found the source of the problem in the closed ticket
> extensions.allowPrivateBrowsingByDefault to false
> 
> #1652

Thanks for the digging, what an username.

This is rather a problem of tor. Closing this favouring [Tor Trac #TBD](about:blank).
