### ISSUE TITLE
MAC Breaks "Switch to Tab" functionality in Awesome Bar

### ISSUE THREAD

**Issue by austenadler** [mozilla/multi-account-containers#1738]
- Multi-Account Containers Version: 6.2.5
- Operating System + Version: Linux (Ubuntu 18.04.4 LTS)
- Firefox Version: 76.0 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: None

### Actual behavior
Switching tabs using the awesome bar does not work. There are no results in the awesome bar for other tabs open in the browser.

### Expected behavior
When typing "%TabName" or "TabName" in the awesome bar when there's another tab with the name "TabName", the awesome bar should offer to switch tabs to the other tab.

### Steps to reproduce
1. Create a new firefox profile
2. Search "history item"
3. Open a new tab; verify typing "%hist" will cause the awesome bar the offer to switch tabs to the first tab
4: Install MAC extension and open a MAC
5: Type "%hist" or "hist" and see that the awesome bar no longer offers the other tab as a suggestion
6: Bonus: Open another tab in the same container with title "abcd". Go back to the first tab and type "%ab" and the awesome bar *will* offer to move tabs

### Notes
It seems like firefox treats container tabs as new browsers, so no other tabs exist to switch to. However, this is annoying when used with extensions like "Temporary Containers" where every tab is its own container, effectively removing the ability to switch tabs with the awesome bar.

**Comment by Solid-Ice8** [comment]
I believe this was the expected behaviour and it will not change.

Please read the 'Readme.md' file named "Test Pilot Product Hypothesis Document".

It states that no changes will be made on the awesome bar UX.

**Comment by austenadler** [comment]
I would say that’s a bug then. In its current state, the awesome bar's behavior has changed because of the addon. Switching tabs wouldn’t be added, it would be fixed.

The only reason I could see this as an intended feature is if there's some security issue with it. Because the switch tab feature exists outside the webpage, I believe it should be fine to fix.

May 14, 2020 7:36:32 AM Solid-Ice8 <notifications@github.com>:

**Comment by dannycolin** [comment]
duplicate of #1705
