### ISSUE TITLE
Add-on using a lot more CPU than usual

### ISSUE THREAD

**Issue by ghost** [mozilla/multi-account-containers#1740]

**Comment by ergosteur** [comment]
Seems to be related to #572

**Comment by talklittle** [comment]
It's a bug in the sync feature. See #1691 

You can disable syncing via the Add-ons Manager, click the extension then Preferences tab.

**Comment by cstrzelc** [comment]
Same issue:
FF version 68.6.1esr (64-bit)
MAC OS 10.14.6
m-a-containers version: 6.2.5
m-a-containers sync functionality is not enabled. So not related to  [#1691](https://github.com/mozilla/multi-account-containers/issues/1691)

I'm experiencing the same exact behavior as described by GingerPapa.  Top sorted by CPU shows m-a-containers extension using all CPU.  Mac slows to a halt and fan ramps up to begin cooling.  I'm going to uninstall the extension and reinstall and monitor for several days.

**Comment by cstrzelc** [comment]
Happens intermittently on MAC OSX 10.14.6, FireFox Version 68.8.0esr, Plugin version 7.0.0. I noticed it when my FAN starts up, when running top multi-account containers is typically consuming between 60% - 100% CPU. No explanation on why this happens, I can't find a smoking gun. Happens several times a day and last for minutes. I'm happy to send any diag info if needed when it happens again.

**Comment by dannycolin** [comment]
Closing since there's no description at all. If anyone experience high CPU usage, please file a new bug report with a profile performance attached to it (See profiler.firefox.com).
