### ISSUE TITLE
Breaks in current nightly

### ISSUE THREAD

**Issue by g2p** [mozilla/multi-account-containers#1745]
- Multi-Account Containers Version: 6.2.5
- Operating System + Version: Ubuntu 20.04
- Firefox Version: Nightly 78.0a1 (2020-05-19)
- Other installed Add-ons + Version + Enabled/Disabled-Status: Clean profile with no other extensions

### Actual behavior
No pages load.
Looking in the network inspector, everything loads, but the rendering never happens.

### Expected behavior
Pages load

### Steps to reproduce
1. Create a clean profile in current nightlies
2. Install the extension
3. Load a page

**Comment by mozfreddyb** [comment]
That's a bug in Nightly, no in the addon.
My patch passed our test suite, but was apparently too hairy to get decent coverage.
If you can, try
- downgrading nightly
- temporarily set `"security.cancel_non_local_systemprincipal` to false. I wouldn't advise keeping this to false for a longer time after you get a repaired version of nightly.

**Comment by g2p** [comment]
Thanks for the quick response, hope your day isn't too bad!
I got an update with the change backed out already.
