### ISSUE TITLE
UX/UI Follow-up Issues

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/multi-account-containers#1746]
This PR covers outstanding issues related to the UX/UI updates outlined in PR #1654. 

## Checklist:
- [x] Add dark-mode support for preferences page
- [x] Fix wrapping issue for Open tabs list (See **Image A** below)
- [x] SVG Fill Color Fix ([Solution](https://github.com/mozilla/multi-account-containers/pull/1654#discussion_r427160189)) 

## Screenshots

Image A: 
![image](https://user-images.githubusercontent.com/2692333/82974932-bc3e3a80-9fa0-11ea-90b5-69e321ad55a9.png)

**Comment by dannycolin** [comment]
Closing since PRs have been merged.
