### ISSUE TITLE
REQUEST: More control of what synchronizes

### ISSUE THREAD

**Issue by bobpaul** [mozilla/multi-account-containers#1748]
**Current Behavior**
Currently Sync with Multi-Account containers is all or nothing. All containers and site preferences are synchronized or nothing is synchronized.

**Desired Behavior**
I think a per-container synchronization setting would be useful. Each container should have the options:
- Synchronize this Container
- Synchronize site defaults for this container (requires Synchronize this Container)

When not-synchronizing, changes should not be pushed and received changes should be ignored.

This would allow some containers to exist only on specific machines AND/OR some containers to have machine specific site defaults

**Example Use Case**
On my work Machine, I would like certain domains to soft-default to my "Work" container. On my home machines, I would like those same domains to soft-default to my "Personal" container. (By soft-default, I mean the behavior where if you open in the non-default container it gives the option to open in the current container or open in the default container.

Ex: 90% of the time when I'm at work, I want to open `drive.google.com` in the Work container and 73% of the time when I'm at home, I want to open `drive.google.com` in the Personal container. (But I DO sometimes open it in the Personal container at work and in the Work container at home.)

**Comment by roothorick** [comment]
This would also be very useful with the Temporary Containers extension, whose containers by definition should not be synchronized with other machines. It would also be an easy workaround for https://github.com/stoically/temporary-containers/issues/371

**Comment by abulgatz** [comment]
With the Temporary Containers extension, temporary containers get saved and are impossible to delete, as they re-appear on sync!
