### ISSUE TITLE
Any plans to add "Open link in new container WINDOW"?

### ISSUE THREAD

**Issue by HacimLlih** [mozilla/multi-account-containers#1752]
- Multi-Account Containers Version:   6.2.5
- Operating System + Version:   openSUSE Tumbleweed  20200526-0
- Firefox Version:   76.0.1 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Extensions
Name 	Version 	Enabled 	ID
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Awesome Screenshot - Capture, Annotate & More	3.0.24	true	jid0-GXjLLfbCoAx0LcltEdFrEkQdQPI@jetpack
Bing	1.1	true	bing@search.mozilla.org
Bookmark Dupes	6.4	true	bookmarkdupes@martin-vaeth.org
Dark Reader	4.9.9	true	addon@darkreader.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Enhancer for YouTube™	2.0.101	true	enhancerforyoutube@maximerf.addons.mozilla.org
Facebook Container	2.1.1	true	@contain-facebook
Firefox Multi-Account Containers	6.2.5	true	@testpilot-containers
Gmail reverse conversation	0.0.7	true	{10df04ee-bbe3-4748-91e1-681b747a0420}
Google	1.0	true	google@search.mozilla.org
Honey	12.1.1	true	jid1-93CWPmRbVPjRQA@jetpack
hotfix-update-xpi-intermediate	1.0.6	true	hotfix-update-xpi-intermediate@mozilla.com
LastPass: Free Password Manager	4.47.0.3	true	support@lastpass.com
Mobile View Switcher	0.1.2	true	{fa247c57-77ac-41cd-b942-332051e15ced}
Print Edit WE	26.2	true	printedit-we@DW-dev
RetailMeNot Deal Finder™️	2.0.2562	true	retailmenot-genie@rmn.com
Save Page WE	17.3	true	savepage-we@DW-dev
SingleFile	1.17.43	true	{531906d3-e22f-4a6c-a102-8057b88a1a63}
TheFreeDictionary.com Lookup	2.0	true	{47F7DAA8-DB46-4FE2-87B0-C6D7C8DD2F23}
To Google Translate	4.0.6	true	jid1-93WyvpgvxzGATw@jetpack
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.27.6	true	uBlock0@raymondhill.net
Unpaywall	3.91	true	{f209234a-76f0-4735-9920-eb62507a54cd}
User-Agent Switcher and Manager	0.3.5	true	{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
YouTube Control Center	0.6.3	true	jid1-CikLKKPVkw6ipw@jetpack
Amazon Assistant for Firefox	10.2005.6.12051	false	abb@amazon.com

Pondering if anyone has ever suggested adding the option to..

**"Open link in new container WINDOW"**

I'm finding I daily and frequently am forced to open the preferred container, then using several keystrokes & menu depths to highlight new tab and choosing "Move tab to new window"; thinking I could save many keystrokes per day if this was added?

THANKS HEROES for this great extension to Firefox!!

**Comment by gkaklas** [comment]
@HacimLlih I believe what you are describing is already being discussed in issue #1416 🤔 If that issue describes the same idea, you can close this one :)

**Comment by HacimLlih** [comment]
You are helpfully correct @gkaklas; thanks! Peace & bSAFE.
