### ISSUE TITLE
"Always open in this container" - can't open the URL in other containers or revert the change

### ISSUE THREAD

**Issue by Dimitar5555** [mozilla/multi-account-containers#1753]
I clicked always open in the work container on meet.google.com and now every time when I try right-clicking the tab and open in personal container(for example) it reopens it in the work container even though I want it to open in the personal container. Also I can't find how to undo that setting.

**Comment by falolaf** [comment]
When visiting the mentioned address, click on the M.A.C. toolbar icon, then uncheck "Always open in work".
Then you should be able to open that addres in any other container.

**Comment by Dimitar5555** [comment]
I hadn't even noticed the I have the extension in my toolbar. Thank you for the help.
