### ISSUE TITLE
Addon documentation or an example?

### ISSUE THREAD

**Issue by fixanoid** [mozilla/multi-account-containers#1760]
Hi! I've an addon that creates frames and opens tabs when user performs certain actions. It needs to know the origin of the MAC identity for a particular tab (generally, currentTab suffices) and to be able to open a tab with that identity set. I'm not sure where the documentation or an example for that could be found. 

Thank you!

**Comment by fixanoid** [comment]
Dug a bit further into the cookies part of the permissions. Looks like `cookieStoreId` is readable when querying `browser.tabs` but how do you set it for something? When running `browser.tabs.update` with new `cookieStoreId` I get this error: `Error: Type error for parameter updateProperties (Unexpected property "cookieStoreId") for tabs.update.`. So, how do I update the frames to be the right cookie store? Thank you!

**Comment by dannycolin** [comment]
Very late response but this is more a general question about addon development. For that, you can ask for help on https://chat.mozilla.org/#/room/#addons:mozilla.org.

Closing for now.
