### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by aman5319** [mozilla/multi-account-containers#1761]
If possible, add this feature where we can start a firefox browser session with any container.
so let suppose we have two containers 
1. Personal
2. Professional

Now if we select a Professional container with a browser window session. All new tabs in that window session will open by default in that particular container session.
It will be very helpful in this COVID situation since we are doing our office work in the personal laptop so no need to open a tab one by one by clicking the icon and selecting the particular container.

**Comment by gkaklas** [comment]
I believe this seems like a duplicate of #319  🤔

**Comment by aman5319** [comment]
Yes, It is the duplicate of it. I will close the issue.
