### ISSUE TITLE
[Quality of Life request] Replace/close tab after clicking on a URL mapped to a Container while in another container.

### ISSUE THREAD

**Issue by 4aHxKzD** [mozilla/multi-account-containers#1765]
What the title says.

Consider for example having configured Multi-Account Containers to always open Facebook.com in its own container, and do the following steps:

1. You are currently using a search engine (e.g. Google, DuckDuckGo) while on the `Default Container`
2. You click a hyperlink to Facebook

Now you have two Tabs, one for your search engine and one for Facebook.

Clicking the Facebook hyperlink should create a new tab in its container, but also close the previous Tab that you were using to browse the internet.

**Comment by xdhmoore** [comment]
I ran across this use case while using Tabliss (an extension for configuring your New Tab page). If I create a "Quicklink" to Facebook messenger on my Tabliss New Tab, clicking the link opens another tab with my configured MAC Facebook container, but leaves the old "New Tab" tab open (and changes it to a blank white page for some reason). Ideally, I think opening the link would replace the existing tab. I don't know how that would work with existing functionality. I suppose there are security rules why existing link target="" behavior can't be respected...?

Also, after digging through the issues I think this is probably a duplicate of #1590 .

**Comment by Solid-Ice8** [comment]
For those that may not be aware, middle clicking any link will open the link in its own container.

**Comment by 4aHxKzD** [comment]
There is an option for this in Preferences now.
