### ISSUE TITLE
Disk usage is at 100% when enabled

### ISSUE THREAD

**Issue by cafehaine** [mozilla/multi-account-containers#1768]
- Multi-Account Containers Version: 6.2.5
- Operating System + Version: Windows 10 Pro 1909 (but also happens on latest version of Arch Linux)
- Firefox Version: Firefox Developer Edition 78.0b7
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Amazon.co.uk	1.1	true	amazon@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
Decentraleyes	2.0.14	true	jid1-BoFifL9Vbdl2zQ@jetpack
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Emoji Cheatsheet for GitHub, Basecamp etc.	2.0.1	true	jid1-Xo5SuA6qc1DFpw@jetpack
File Icon for GitHub, GitLab and Bitbucket	0.8.1	true	{85860b32-02a8-431a-b2b1-40fbd64c9c69}
Google	1.0	true	google@search.mozilla.org
HTTPS partout	2020.5.20	true	https-everywhere@eff.org
NoScript	11.0.31	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Plasma Integration	1.7.5	true	plasma-browser-integration@kde.org
Qwant	1.1	true	qwant@search.mozilla.org
Search by Image	2.2.1	true	{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}
SponsorBlock pour YouTube - Supprime les messages commerciaux et publicités intégrées	2.0	true	sponsorBlocker@ajay.app
Stylus	1.5.11	true	{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}
Tree Style Tab	3.5.5	true	treestyletab@piro.sakura.ne.jp
Wikipédia (fr)	1.0	true	wikipedia@search.mozilla.org
YouTube™ on Hover Preview	0.1.9	true	{732db00c-07ee-4763-a8c7-fd666803287e}
About Sync	0.0.52	false	aboutsync@mhammond.github.com
dotEPUB	1.2.5	false	jid1-xvjf0Huq7OaIkg@jetpack
Firefox Multi-Account Containers	6.2.5	false	@testpilot-containers
HTTP/2 Indicator	3.0	false	spdyindicator@chengsun.github.com
Save Page WE	18.0	false	savepage-we@DW-dev
URLs List	0.5.0	false	{88664789-f91e-40e1-adb9-e4e9a8c48867}
User-Agent Switcher and Manager	0.3.5	false	{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}
Vue.js devtools	5.3.3	false	{5caff8cc-3d2e-4110-a88a-003cc85b3858}
WAVE Evaluation Tool	3.0.8	false	{9bbf6724-d709-492e-a313-bfed0415a224}

(multi-account-containers is disabled since I’m getting quite annoyed by this bug)

### Actual behavior
100% disk usage when the addon is enabled
This doesn't seem to happen everytime on Arch Linux, but 100% of the time on Windows.

### Expected behavior
No increase in disk usage

### Steps to reproduce
Start firefox with multi-account-containers, and open a few tabs (gmail/youtube/github/facebook…)

**Comment by groovecoder** [comment]
Can you reproduce this in a Firefox profile that has only the multi-account containers extension and no others?

**Comment by cafehaine** [comment]
I've create a new profile and it doesn't happen there.

It no longers seems to happen reliably on Windows, and I the only thing I did was just to disable/reenable all my extensions.

I'm not sure what might be causing this, but I guess this issue can be closed then, sorry about the noise.

**Comment by narq** [comment]
I've observed the same issue.  SSD was writing and CPU fan was on which drew my attention to it. Having disabled and enabled the plugin, disk usage goes back to normal.  I'll leave it enabled to see how long it takes to happen again.  I'm running 6.2.5 on Void Linux 5.4.46_1 Firefox 77.0.1 (64-bit).

Here's a line from iotop
29786 be/4 ian         0.00 B/s   12.81 M/s  0.00 % 70.01 % firefox [mozStorage #4]

**Comment by ColinCMillar** [comment]
I also get this on Windows with Firefox 77.0.1. I've removed and re-added the add-in, and disabled other add-ins, and it still comes back. CPU high and disk usage at 20MB/s constantly.

**Comment by narq** [comment]
I can reproduce this problem on Windows and Linux, it's still a showstopper for me.

**Comment by groovecoder** [comment]
@narq - are you able to reproduce this in a firefox profile with no other add-ons installed?

**Comment by cstrzelc** [comment]
Happens intermittently on MAC OSX 10.14.6, FireFox Version 68.8.0esr, Plugin version 7.0.0.  I noticed it when my FAN starts up, when running top multi-account containers is typically consuming between 60% - 100% CPU.  No explanation on why this happens, I can't find a smoking gun.  Happens several times a day and last for minutes.  I'm happy to send any diag info if needed when it happens again.

**Comment by grahamperrin** [comment]
@narq bump. 

Also https://profiler.firefox.com/

**Comment by dannycolin** [comment]
Closing: Stalled. 

If someone is able to reliably reproduce this issue, feel free to file a new bug report.
