### ISSUE TITLE
Impossible to evade 'Always open in <ContainerID>' behavior 

### ISSUE THREAD

**Issue by peterv1988** [mozilla/multi-account-containers#1769]
### Actual behavior
1. Once I have configured a website for example drive.google.com (referred to as `Website1`), to be always opened in `ContainerA`
2. If afterwards I open for example docs.google.com (referred to as `Website2`) in `ContainerB`
3. After I click a link in the `ContainerB` tab which links to `Website1`, the link is opened in a new tab (`ContainerA`)

### Expected behavior
Since on step `3.` I am al already browsing `Website2` in a `ContainerB` tab, I expected to see a confirmation promp asking me whether I want to open the link in `ContainerA` or `ContainerB`.

### Notes:
In the example I have configured `Website1` as default to be opened in `ContainerA` because this is the case for me in 80% of time, but currently because of 20% of the time I don't want to use that container currently I am forced to completely turn off the 'Always open in <ContainerID>' checkbox and manually open the desires Container each time.

- Multi-Account Containers Version: 6.2.5
- Operating System + Version: Mac OS 10.15.5
- Firefox Version: 77.0.1 - 64 bit  - using regular browsing mode (so no private tabs)
- Plugins:
```Extensions
Name 	Version 	Enabled 	ID
1Password X Beta – Password Manager	1.20.4	true	{25fc87fa-4d31-4fee-b5c1-c32a7844c063}
Bing	1.1	true	bing@search.mozilla.org
bol.com	1.0	true	bolcom@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	6.2.5	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
HTTPS Everywhere	2020.5.20	true	https-everywhere@eff.org
I don’t care about cookies	3.1.8	true	jid1-KKzOGWgsW3Ao4Q@jetpack
Marktplaats.nl	1.0	true	marktplaats@search.mozilla.org
NoScript	11.0.31	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Privacy Settings	0.3.7	true	jid1-CKHySAadH4nL6Q@jetpack
uBlock Origin	1.27.10	true	uBlock0@raymondhill.net
Wikipedia (nl)	1.0	true	wikipedia@search.mozilla.org
Xdebug helper	1.0.6	true	{806cbba4-1bd3-4916-9ddc-e719e9ca0cbf}
LastPass: Free Password Manager	4.47.0.3	false	support@lastpass.com
Zend Debugger Toolbar	4.0.1	false	{714BDBD0-7E3A-11E6-86F1-66A48202D2A8}
```

**Comment by groovecoder** [comment]
Did you check the "Remember my decision for this site" when you opened the site into the assigned Container?

If so, you can un-assign the site from the Container to clear that checkbox, and then you should get the confirmation prompt each time.

**Comment by peterv1988** [comment]
@groovecoder the problem is I am unable to uncheck this checkbox directly from the user interface. The problem with Google suite (and presumably a big variety of websites) is that first time opening the website you enter the authentication phase. Now the problem (as described step-by-step above) is when you click the checkbox and after that log-in, is that you in "logged-in" phase where you automatically get redirected before you even have the opportunity to uncheck the checkbox.

**Comment by michft-v** [comment]
Possible sub-problem.

Once you configure Always open. Clicking links for external places (slack) to website ALWAYS asks if you want to open in container tab, even when you clicked "Remember my Choice" the last time you clicked a link.

Downgraded to 6.2.4 until this gets fixed. Turned auto update off.

**Comment by grahamperrin** [comment]
> … evade 'Always open in …

▶ #1414

@peterv1988 please close this duplicate issue. Thank you.

**Comment by grahamperrin** [comment]
Thanks!
