### ISSUE TITLE
Bug: Favicon icon ratio out of proportion on "Manage Site List" panel

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/multi-account-containers#1779]
<img width="330" alt="image" src="https://user-images.githubusercontent.com/2692333/87087137-2d0b8000-c1f8-11ea-9557-349208521c20.png">

Use the override CSS used in this commit: https://github.com/mozilla/multi-account-containers/commit/bcd3aaeb92033b17ea4277428924375539670aba

Div ID: `#edit-sites-assigned`

**Comment by groovecoder** [comment]
I'm having trouble reproducing this?
