### ISSUE TITLE
"Limit to designated sites" option not saving changes correctly

### ISSUE THREAD

**Issue by sdht0** [mozilla/multi-account-containers#1781]
- Multi-Account Containers Version: 7.0.0
- Operating System + Version: Arch Linux
- Firefox Version: 79.0b5

### Actual behavior
1) Go to  "Manage containers"
2) For each container, check "Limit to designated sites" to ON.
3) Close popup and reopen "Manage containers" to check settings.
4) "Limit to designated sites" is (seemingly) randomly set to ON or OFF for each container.

### Expected behavior
All containers have "Limit to designated sites" set to on. 

### Notes
I debugged this and it looks like issue happens because [document.querySelector("#site-isolation")](https://github.com/mozilla/multi-account-containers/blob/52749ee1f0169706c424d8d0bc0b7846201e9046/src/js/popup.js#L1311) is returning all the containers that have been opened till that point. So on opening 1->2->3 containers in succession, that query will return [1,2,3] and will toggle the state for all 3, hence giving a random state at the end for each container.

Didn't understand the logic for loading or unloading panels, but the solution seems to be properly unloading the panel for a particular container on pressing the "back" button.

The workaround is of course to close the popup after changing each container and reopening it.

Thanks!

**Comment by s75uiFbxnykgkQMC7NQh** [comment]
Same behavior here, "Limit to designated sites" is randomly set to ON or OFF for each container.
- Multi-Account Containers Version: 7.0.0
- Operating System + Version: Ubuntu 20.04
- Firefox Version: 78.0.2

**Comment by jisanos** [comment]
I am also encountering similar behavior on both Linux (Manjaro) and Windows (10) versions of Firefox.
Multi-Account 7.0.0
Firefox 78.0.2

**Comment by jimaldon** [comment]
I can confirm that this happened when I tried checking "Limit to Designated Sites" on more than one container (pressing back "<" to go to main "Manage Container" menu and select another container)

The option works as intended only if I make changes to the container one-by-one, exiting out of the MAC dialog box every time
