### ISSUE TITLE
 7.0 UX/UI - Ugly font spacing

### ISSUE THREAD

**Issue by vtuu** [mozilla/multi-account-containers#1786]
Look at the "Yandex" container (space between "Y" and "a"), "Shopping" (space between "S" and "h"), "Work" ("W" and "o").
Look at the difference between "Sort" (menu item "Sort tabs by container") and "Search" ("Search" container item).
Aligning of container icon and container name looks broken.
Also there is no padding after the last container item.

Needs to be fixed.

![Untitled](https://user-images.githubusercontent.com/60247155/87214253-5817e000-c36e-11ea-92d5-0addce4c7e68.png)

**Comment by dannycolin** [comment]
Closing since the UI has completely changed in the meantime. If you still have this issue in the newest version, please open a new bug report.
