### ISSUE TITLE
Upgrade web-ext to version >= 4.2.0

### ISSUE THREAD

**Issue by ericlee4** [mozilla/multi-account-containers#1795]
### Actual behavior
`npm run webext` throws:
`WebExtError: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install`

### Expected behavior
Web-ext launches a new browser instance with the temporary extension installed

### Steps to reproduce
1. Run `npm run webext` in a clean environment

### Notes
See https://github.com/mozilla/web-ext/pull/1886. I'm running Firefox Developer Edition 79.0b6 (64-bit) on Arch Linux. Locally upgrading web-ext fixes the issue. 

There's also an unrelated issue with web-ext not detecting the dev edition installation but after fixing that with a symlink/passing an option to web-ext/installing the stable edition the above behavior is observed.

**Comment by dannycolin** [comment]
Closing since the minimum web-ext version is now 5.4.1.
