### ISSUE TITLE
Containers checkbox where to open site by default uncheckable

### ISSUE THREAD

**Issue by mikeconley** [mozilla/multi-account-containers#1800]
Filing this on behalf of Artur Kaminski who originally filed this as https://bugzilla.mozilla.org/show_bug.cgi?id=1493605

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
Build ID: 20180923220427

Steps to reproduce:

Nightly build from https://hg.mozilla.org/mozilla-central/rev/b42bb6bb0be8723d0dd2b3c857c554cefa763062

on

Linux 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

but it happened two days ago (I reload Nightly everyday, immediately as the update is ready).

Install Multi-Account Containers. Open any web site in a container, click the containers icon to open containers menu, try to mark the checkbox titled "Always open in [container name]".

Actual results:

The checkbox is selectable (has focus), but cannot be marked as checked.
Sites previously marked for a particular container are unchecked.

Expected results:

It should be possible to mark and clear the checkbox.
Sites already categorized for containers should have the checkbox marked.

**Comment by mikeconley** [comment]
The checkbox still cannot be marked, but now there appears some kind of floating rectangle box 40px x width of window with a message "Successfully added..." or "Successfully removed..." after click on the checkbox. "Floating" because sometimes it appears on top of browser window, sometimes below some other elements of the interface.

Version 64.0a1 (2018-10-07) (64-bit)

**Comment by dannycolin** [comment]
Closing since the checkbox is gone in 8.x.
