### ISSUE TITLE
Add support for containers to browser.startup.homepage

### ISSUE THREAD

**Issue by mikeconley** [mozilla/multi-account-containers#1801]
Filing on behalf of Daniel Roesler who originally filed this as https://bugzilla.mozilla.org/show_bug.cgi?id=1506476

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0

Steps to reproduce:

1. Enable Multi-Account Containers
2. Set example.com to always open in a Container B
3. Set example.com as the Custom URL homepage in browser.startup.homepage (or via Preferences > Home > Homepage and new windows > Custom URLs)

Actual results:

Situation 1 (incorrect behavior):
1. Close Firefox.
2. Open Firefox.
3. Homepage opens to example.com, but not in Container B
4. Refresh the page.
5. A new tab opens in Container B with example.com as url.

Situation 2 (correct behavior):
1. Have Firefox open.
2. Click the Home icon in the top toolbar.
3. A new tab opens in Container B with example.com as url.

Expected results:

1. When opening Firefox for the first time, Custom URLs for the homepage should open in their default containers. NOTE: This may be security issue since it means urls you expected to open in a specific container is now leaked to your main tabs.

2. The browser.startup.homepage field in about:config should allow to manually specify containers in which to open the urls.

For example:
browser.startup.homepage = "https://google.com|https://example.com/"

Should be able to do something like:
browser.startup.homepage = "https://google.com|{ContainerB}https://example.com/"

Open to suggestions on what the notation syntax should be.

**Comment by mikeconley** [comment]
I created a 90 second screen capture video showing how to reproduce the issue on a new firefox profile (Firefox 63, Xubuntu 16.04).

https://bugzilla.mozilla.org/attachment.cgi?id=9025371

**Comment by mikeconley** [comment]
I just updated to 66.0.1 (64-bit) Mozilla Firefox for Ubuntu canonical - 1.0, and domains now open in their correct containers. Not sure what changed in the latest update, but you can now mark this issue as resolved.

**Comment by mikeconley** [comment]
I just updated to 67.0 (64-bit) Mozilla Firefox for Ubuntu canonical - 1.0, the bug is back. Urls in browser.startup.homepage setting do not automatically open in their containers.

**Comment by mikeconley** [comment]
This bug still persists in Firefox 72.0

**Comment by dannycolin** [comment]
On my side, it works as expected. Can you still reproduce on 103?

**Comment by dannycolin** [comment]
Duplicate of #1289
