### ISSUE TITLE
Arrow-key navigation doesn't work when the add-on is pinned to the overflow menu

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/multi-account-containers#1812]
I just updated to 7.0.1 and it's still not possible to navigate the panel with the arrow keys.  I have to hit tab twice, and then the arrow keys work.  I suspect this is due to the addon being pinned to the overflow menu.

_Originally posted by @hackel in https://github.com/mozilla/multi-account-containers/issues/1785#issuecomment-658810724_

**Comment by hackel** [comment]
> Does the arrows keys work for you when it's not in the overflow menu?

@maxxcrawford Yes, sorry I should have mentioned that.

**Comment by dannycolin** [comment]
Closing: Invalid

Extensions are moving to a new unified menu https://blog.mozilla.org/addons/2022/11/17/unified-extensions-button-and-how-to-handle-permissions-in-manifest-v3/
