### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by khawajamechatronics** [mozilla/multi-account-containers#1820]
Hi,

I like this container application but its not useful for use scenario.

1- I want to use same account for all the container (May be add option to enable use same cookies and other stuff.)
2- I dont like 'reopen' in specific container. I wish to move to other container (as I will be using same account so cookies will be same)
Also tab will just move. I will not have to close tab from default.

Let me if its doable or already implemented or in progress.

Looking Forward,
Khawaja

**Comment by mijailr** [comment]
The idea of the container is exactly the opposite, is to separate the accounts if you want to have a single account maybe a single container is what you want.

**Comment by dannycolin** [comment]
Closing as expected behavior. I have a feeling what you want is a tab grouping feature. This doesn't exist in Firefox but there's a thread on our feedback platform related to that. See: https://connect.mozilla.org/t5/ideas/native-tab-grouping-more-customizable-tab-bar/idi-p/303.
