### ISSUE TITLE
Breaking some other extensions 

### ISSUE THREAD

**Issue by JaggedJax** [mozilla/multi-account-containers#1825]
- Multi-Account Containers Version:
- Operating System + Version: POP!_OS 20.04
- Firefox Version: 78.0.2 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: Zoho Vault 2.5.7 Enabled

### Actual behavior
Zoho Vault launches login page. Login button appears to do nothing. Console shows vault.zoho.com is blocked because it is requesting to open in a specific container, but cannot as the page is attempting to be loaded from the extension window.

### Expected behavior
Clicking login button will direct to the Zoho Vault login.

### Steps to reproduce
1. Install Zoho Vault: https://addons.mozilla.org/en-US/firefox/addon/zoho-vault/
2. Install FF Multi Account Containers
3. Visit vault.zoho.com and select "Always Open This Site in...". Select any container.
4. Click on the Zoho Vault addon and attempt to login from the popup login window. Request will be blocked by FF Multi Account Containers

### Notes
It seems the multi-account container works by blocking the request and then re-opening a new tab. This flow doesn't work in windows opened by an addon. Or at least it does not work with the way Zoho Vault opens their login window when using their addon. There are likely other addons that would be incompatible with Multi Account containers because of this.

Either the addon window needs to switch containers as needed, or it just needs to allow the request through in "no container" so that the page at least loads.

**Comment by grahamperrin** [comment]
> … Always Open This Site in …

▶ 2018 issue #1121 and note the overlap there with other issues. 

@JaggedJax please close this duplicate. Thank you.

**Comment by JaggedJax** [comment]
Closed as dupe of #1121
