### ISSUE TITLE
It's impossible to turn off "Always open in container"

### ISSUE THREAD

**Issue by schuelermine** [mozilla/multi-account-containers#1829]
- Multi-Account Containers Version: 7.0.2
- Operating System + Version: Microsoft Windows [Version 10.0.20170.1000]
- Firefox Version: 79.0b9 (64-bit)

Other installed add-ons:

|Name|Type|Version|Enabled|ID|
|---|---|---|---|---|
|Amazon.com|extension|1.1|true|amazondotcom@search.mozilla.org|
|Bing|extension|1.1|true|bing@search.mozilla.org|
|DuckDuckGo|extension|1.0|true|ddg@search.mozilla.org|
|DuckDuckGo Privacy Essentials|extension|2020.7.9|true|jid1-ZAdIEUB7XOzOJw@jetpack|
|eBay|extension|1.1|true|ebay@search.mozilla.org|
|Facebook Container|extension|2.1.1|true|@contain-facebook|
|Firefox Multi-Account Containers|extension|7.0.2|true|@testpilot-containers|
|Font Finder|extension|0.3.7|true|{a658a273-612e-489e-b4f1-5344e672f4f5}|
|Google|extension|1.0|true|google@search.mozilla.org|
|Reddit Enhancement Suite|extension|5.20.2|true|jid1-xUfzOsOFlzSOXg@jetpack|
|SoundFixer|extension|1.1.0|true|soundfixer@unrelenting.technology|
|Stylus|extension|1.5.11|true|{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}|
|Tab Session Manager|extension|6.1.0|true|Tab-Session-Manager@sienori|
|uBlock Origin|extension|1.28.2|true|uBlock0@raymondhill.net|
|User-Agent Switcher and Manager|extension|0.3.5|true|{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}|
|Wikipedia (en)|extension|1.0|true|wikipedia@search.mozilla.org|
|Firefox Color|extension|2.1.5|false|FirefoxColor@mozilla.com|

When choosing "Always open", it is impossible to reverse this.

See demonstration (some weird colors because GIF):
![output](https://user-images.githubusercontent.com/48802534/88132553-1e519f80-cbe0-11ea-959f-b7ed9c688119.gif)

**Comment by RemRemRemRe** [comment]
Same issue here.

Users did not have too much freedom to customize or tweek this thing.

**Comment by maxxcrawford** [comment]
To remove sites assigned to a Container by default (including those where you've clicked "Remember my decision for this site", do the following: 

1. Click "Manage Containers" at the bottom of the main panel

<img width="330" alt="image" src="https://user-images.githubusercontent.com/2692333/88571655-9f0b0400-d003-11ea-9580-277cf7a9a8bd.png">

1. Select the Container you wish to manage. (In this case, "Else")

<img width="348" alt="image" src="https://user-images.githubusercontent.com/2692333/88571714-adf1b680-d003-11ea-8550-b3adfd4bf2e6.png">

1. Click "Manage site list" on the Container Edit panel 

<img width="345" alt="image" src="https://user-images.githubusercontent.com/2692333/88571757-c1048680-d003-11ea-82a9-500063a1cb05.png">

1. Click the trash can icon over the domain you wish to remove from that specific Container.

**Comment by maxxcrawford** [comment]
Note – I added [a wiki page documenting these steps](https://github.com/mozilla/multi-account-containers/wiki/How-to-remove-a-%22Awlays-open-in%E2%80%A6%22-site-from-a-Container) for future users:
