### ISSUE TITLE
New keybindings (Ctrl+Shift+1, Ctrl+Shift+2) conflict with a built-in Firefox feature, the Firefox Profiler

### ISSUE THREAD

**Issue by dholbert** [mozilla/multi-account-containers#1831]
Firefox Multi-Account Containers recently had an update which introduced some new keybindings to open container tabs: `Ctrl+Shift+1`, `Ctrl+Shift+2`, etc.  (with `Cmd` on mac instead of `Ctrl`, per usual)

Unfortunately, these specific commands are already used by an existing built-in Firefox feature -- the Firefox Performance Profiler. (It's built-in, but hidden by default - to enable it, you just visit https://profiler.firefox.com/ and click the button, and then it's enabled indefinitely from then on.)  See documentation for this feature (including these key commands) at
https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Reporting_a_Performance_Problem

(We often send users there when they file bugs about Firefox being janky, so it's important that the instructions there continue to work.)

For users who have the profiler enabled and the Firefox Multi-Account-Containers add-on installed, it seems to be arbitrary what happens when they press `Ctrl+Shift+1`. In testing this configuration today, I've seen it open a new container tab in some sessions, and activate the profiler in other sessions. (I'm guessing there's a race for who gets to register the keybinding first, or who has the final say).

I think we need to rethink these keybindings, or come up with some sort of workaround so that they don't collide with a built-in feature and produce unexpected/unpredictable behavior.

**Comment by dholbert** [comment]
(I don't know if the Firefox Multi-Account Container keybindings are documented/announced anywhere, but I did get some confirmation that they exist [e.g. it's not just me] from comments like https://github.com/mozilla/multi-account-containers/issues/1784#issuecomment-657001633 )

**Comment by dholbert** [comment]
CC @groovecoder  @maxxcrawford @digitarald

**Comment by maxxcrawford** [comment]
For anyone experiencing this issue, see this guide on how to [override these extension shortcuts](https://github.com/mozilla/multi-account-containers/wiki/How-to-Override-Keyboard-Shortcuts).

**Comment by dholbert** [comment]
Looks like we can close this as a duplicate of #1814, probably.
