### ISSUE TITLE
Google automatially opens outside of container

### ISSUE THREAD

**Issue by MicaHorton** [mozilla/multi-account-containers#1836]
Hi, I'm having an issue where if I go to google.com in my "accounts" container, it'll open automatically outside of the container as a normal tab. If I set google.com to always open in my "accounts" container, it'll work; however, when I try to login, it'll start reloading over and over again without stopping. It causes the tab to look like it's blinking. This only happens with Google (as far as I know of.) It doesn't happen with my Amazon or Github account, etc...

My operating system is macOS Catalina version 10.15.4  My Firefox version is 79.0. My other plugins are Privacy Badger, uBlock and HTTPS Everywhere, all enabled

Steps To Reproduce:
1. Create a new container 
2. Open a tab in that container and go to google.com 
3. Google should redirect and open in a new tab, outside that container

1. Set google.com to always open in the container
2. Open google.com in that container and try to login
3. It should start reloading over and over again

Thanks for putting effort into making this tool. It's really useful.

**Comment by ndmgrphc** [comment]
Never experienced this before today and it's happening constantly now.

**Comment by maxxcrawford** [comment]
To remove a site from a container (that opens by default), use [this guide](https://github.com/mozilla/multi-account-containers/wiki/How-to-remove-a-%22Awlays-open-in%E2%80%A6%22-site-from-a-Container)!
