### ISSUE TITLE
Feature request: Search container name (or filter container name) at top of container name list popup

### ISSUE THREAD

**Issue by xet7** [mozilla/multi-account-containers#1845]
Hi,
I have many containers. Currently for finding some container name, I need to read whole list of container names to try to find the correct one.

There should be search input field at top of Multi-Account-Containers popup.

For example, when I type "HN" it should find HN container, that I use for Hacker News.

Then I would click that found HN countainer name to open that container.

**Comment by frnk01** [comment]
Please prioritize this. At the moment I'm finding it extremely difficult to use the containers in an effective manner when switching alot.

**Comment by hub2git** [comment]
+1. Please implement this suggestion/feature.

In Firefox, we can **search** through our history, our logins/passwords, our bookmarks, the Firefox preferences. This makes it easier to zero in on what we're looking for.

But we can't search through our containers.  Pretty please with whipped cream and cherry on top, please make this happen.

**Comment by grahamperrin** [comment]
> ## Search container name (or filter container name) at top of container name list popup

▶ #1103

@xet7 can you close this duplicate? Thank you.

**Comment by grahamperrin** [comment]
Thanks!
