### ISSUE TITLE
Feature Request: Folders for Organizing Container Tabs

### ISSUE THREAD

**Issue by naydichev** [mozilla/multi-account-containers#1849]
Hello! Thank you for an amazing extension, I use it all the time.

For work, I have about 4 - 5 different AWS Console tabs open at a time, but I like to have a separate container for each account type, so that I can always look in the address bar and have the container name match the account that I'm in.

I would love it if it were possible to organize the container tabs within folders so that I can keep a hierarchy of container tabs organized and not have to be overwhelmed by a huge list everytime.

Bonus points for adding a search bar so I can type the name of the container I want to open.

**Comment by groovecoder** [comment]
This is a cool feature idea, but I think it's best fulfilled by using another tab-management add-on in addition to Multi-Account Containers. E.g., [tree-style tabs](https://addons.mozilla.org/firefox/addon/tree-style-tab/) maybe?

**Comment by naydichev** [comment]
Respectfully, I disagree - I have a lot of different containers, and tree-style tabs does not allow me to navigate them any easier.

I would like to be able to organize and sort my containers for ease of finding them.

For reference - they are mostly used to manager various AWS accounts, and I prefer to give each account it's own container. So I cannot simply assign `console.aws.amazon.com` to a specific container, because they all need it.

**Comment by grahamperrin** [comment]
> organize

▶ Mozilla bug [1357214 - Tab Groups API](https://bugzilla.mozilla.org/show_bug.cgi?id=1357214) – please see the most recent comments.

**Comment by StoopidoMan** [comment]
I need this so bad, I like to create more containers, but I stop myself.
