### ISSUE TITLE
Limiting Scope of an Extension to a Container

### ISSUE THREAD

**Issue by coxjc** [mozilla/multi-account-containers#1850]
Hey everyone! 

I hope this is the right place to ask this question. If not, please do guide me to the correct place. 

I am curious if it is possible to scope the permissions of a container to a specific container. I am wanting this feature because an extension I want to use, Ebates, has an awful privacy policy, so I was hoping to limit it to a dedicated container. 

Is this possible? 

Thank you!

**Comment by hub2git** [comment]
@coxjc That's what containers are for. You can set a container to always open ebates.com / rakuten.com.

**Comment by groovecoder** [comment]
What @hub2git said. You can assign a site to always open in that container, and you can also set "Limit to designated sites"
