### ISSUE TITLE
Feature Request - Drag and drop sorting of containers from the pop-out window

### ISSUE THREAD

**Issue by koolk** [mozilla/multi-account-containers#1858]
**_Feature Request_** - Being able to drag and drop sort from the pop-out menu would be very helpful in keeping "like" containers closer to one another.

![sorting](https://user-images.githubusercontent.com/4127498/92329217-0b7e1780-f034-11ea-8480-75f70a2e3c51.jpg)

**Comment by hub2git** [comment]
+1

**Comment by groovecoder** [comment]
Dupe of https://github.com/mozilla/multi-account-containers/issues/330 please up-vote and/or comment there.
