### ISSUE TITLE
How to undo the "Always open this in a container" for a website

### ISSUE THREAD

**Issue by CSALS** [mozilla/multi-account-containers#1859]
Hey. I selected always open youtube.com in a personal container. How should I undo this? How should I make it open in a normal firefox tab?

**Comment by dkravetz** [comment]
Hi!

Click the extension icon -> Manage containers -> click the container you defaulted youtube to -> click "manage site list..." -> Delete youtube.com from the list

**Comment by CSALS** [comment]
@dkravetz It worked. Thank you.
