### ISSUE TITLE
Keyboard shortcuts to open containers conflict with Firefox's own shortcuts and with macOS's in some keyboard layouts

### ISSUE THREAD

**Issue by AlphaHydrae** [mozilla/multi-account-containers#1863]
### Actual behavior

On macOS with a Swiss keyboard layout:

`Cmd-Shift-1`: container 1 opens, zoom increases (due to Shift-1 being the Plus (+) character in this keyboard layout, so Cmd-Shift-1 is also Cmd-+, Firefox's own shortcut to zoom in).
`Cmd-Shift-3`: no container opens, macOS starts a screen capture
`Cmd-Shift-4`: no container opens, macOS starts a screen capture

### Expected behavior

I'm not expecting Firefox to have conflicting shortcuts, or to override the macOS shortcuts so I guess I would either expect containers not to use any existing shortcuts, and/or even better, to be able to customize them.

### Steps to reproduce

Attempt to open containers 1, 3 or 4 on macOS with the keyboard shortcuts (Cmd-Shift-N) on macOS with a [Swiss keyboard layout](https://discussions.apple.com/content/attachment/353961040).

### Notes

Firefox: 80.0.1 (64bit)
macOS: 10.14.6
Keyboard layout: Swiss French

**Comment by AlphaHydrae** [comment]
Whoops, sorry I did not look hard enough. I only just now found the way to change the shortcuts.

For anyone who might find this issue: Go to Add-ons > Gear Icon > Manage Extension Shortcuts

https://github.com/mozilla/multi-account-containers/issues/1784#issuecomment-657001633

**Comment by SolespireMarcus** [comment]
> Whoops, sorry I did not look hard enough. I only just now found the way to change the shortcuts.
> 
> For anyone who might find this issue: Go to Add-ons > Gear Icon > Manage Extension Shortcuts
> 
> [#1784 (comment)](https://github.com/mozilla/multi-account-containers/issues/1784#issuecomment-657001633)

Yes, you can choose a container to correspond with a selected number, but that doesn't change the fact that Cmd-Shift-3, 4, and 5 still run into conflicts with macOS. This still needs to be fixed. Perhaps instead of using Shift, the Option key should instead be used.
