### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by kuzi-moto** [mozilla/multi-account-containers#1869]
- Multi-Account Containers Version: 7.0.2
- Operating System + Version: Windows 10 - Build 19041
- Firefox Version: Nightly - 82.0a1 (2020-09-18) (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: 

| Name                             | Type      | Version  | Enabled | ID                              |
| -------------------------------- | --------- | -------- | ------- | ------------------------------- |
| Amazon.com                       | extension | 1.3      | TRUE    | amazondotcom@search.mozilla.org |
| Bing                             | extension | 1.2      | TRUE    | bing@search.mozilla.org         |
| DuckDuckGo                       | extension | 1.1      | TRUE    | ddg@search.mozilla.org          |
| eBay                             | extension | 1.2      | TRUE    | ebay@search.mozilla.org         |
| Firefox DevTools ADB Extension   | extension | 0.0.5    | TRUE    | adb@mozilla.org                 |
| Firefox Multi-Account Containers | extension | 7.0.2    | TRUE    | @testpilot-containers           |
| Google                           | extension | 1.1      | TRUE    | google@search.mozilla.org       |
| LastPass: Free Password Manager  | extension | 4.56.1.3 | TRUE    | support@lastpass.com            |
| Popup window                     | extension | 0.1.0    | TRUE    | PopupWindow@ettoolong           |
| uBlock Origin                    | extension | 1.29.2   | TRUE    | uBlock0@raymondhill.net         |
| Wikipedia (en)                   | extension | 1.1      | TRUE    | wikipedia@search.mozilla.org    |

### Actual behavior

Firefox/my machine will suddenly become very glitchy and slow. On checking task manager my system memory usage is at 99% with Firefox using a majority of it. Sometimes up to 8 GB.

### Expected behavior

Firefox memory usage stays sane and operates like usual.

### Steps to reproduce

1. Use Firefox & multi account containers
2. After an hour or so of usage realize there is an issue
3. Exit Firefox, or kill the specific FF process eating all the RAM.

### Notes

I haven't been able to pinpoint exactly what needs to happen to trigger the memory leak, since I'm able to use the extension fine for some time. I can say that almost every time it happens while using the shortcut `"Ctrl" + "Shift" + Num` to select a container, because the new tab does not open. The reason I suspect this extension is because there is a specific FF process that is using the RAM and killing it makes everything normal again.

I wonder if it's specifically related to using the shortcuts to open tabs, because I don't recall it ever happening when I right-click on the new tab icon to select a container, or when selecting a container after opening the list using the shortcut `"Ctrl" + "Shift" + .`

Let me know if there is more information I can provide.

**Comment by VishalSharma2000** [comment]
Yes. One more thing I want to add here. I have not used container for lots of time. So, maybe I'm not aware of this feature existing already. Please correct me If I'm wrong somewhere. I experienced this issue during my usage. 

Even after using multi-container, memory usage of firefox is same as prior(without using multi-container). Can this feature if it doesn't exist can be added i.e. Suppose I have 4 container(say A, B, C, D) for now. If I'm currently using container A tabs then RAM consumption should be only for those containers only. Rest tabs which are present in B, C, D should not consume any memory. They can be stored in Hard Disk(maybe their URLs). We can have a thread running in backend which will be used for linking a container and opening it as per user requirement(like the .dll file we have in windows for linking different files). This may result a bit slower opening time for the container tabs but I think if RAM is saved then it will not be a problem.

**Comment by dannycolin** [comment]
Can you still reproduce in the latest version of Firefox? Also, could you attach a performance profile (See https://profiler.firefox.com/) if this issue still exist.

**Comment by kuzi-moto** [comment]
For what it's worth, I think this is no longer an issue. I have not experienced any of these performance issues in quite some time.
