### ISSUE TITLE
Extension always opens two tabs - one empty (blank without context) and second one correctly with the selected container context

### ISSUE THREAD

**Issue by nekromoff** [mozilla/multi-account-containers#1872]
- Multi-Account Containers Version: latest (July 18)
- Operating System + Version: Ubuntu 19.04
- Firefox Version: 80.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Scenario 1:
1. Open blank tab
2. Selected reopen in container X
3. blank tab is left as it is, container context opens in another (new) blank tab

Scenario 2:
1. External app click on URL that goes to Firefox
2. URL is set to open in a certain container context
3. Tab opens and is left blank
4. Second tab opens with correct context and URL

### Expected behavior
No blank tab is opened before container tab, i.e. only container tab opens

### Steps to reproduce
See above

**Comment by hjasond** [comment]
I also experience this bug with multi-account containers. 

Multi-Account Containers Version: latest (July 18)
Operating System + Version: macOS 11.0 Big Sur (DP 7)
Firefox Version: 81.0

**Comment by hjasond** [comment]
This appears to be fixed in the latest version of multi-account containers released on Sep 29th 2020. Select the option to open the new container in the existing tab in the add-on preferences. Thank you whoever added this feature!

**Comment by dannycolin** [comment]
> This appears to be fixed in the latest version of multi-account containers released on Sep 29th 2020. Select the option to open the new container in the existing tab in the add-on preferences.

Yes, it is for scenarion 2. However, scenario 1 isn't. This is a limitation of the WebExtension API that doesn't let us re-open a privileged URL (any about:* pages) (See https://bugzilla.mozilla.org/show_bug.cgi?id=1269456).

Closing since there's nothing we can do on our side for that.

**Comment by nekromoff** [comment]
What about a workaround: I understand that (re)opening is not an option closing. However what about closing a blank tab that's basically a leftover anyway while opening a new context?

**Comment by dannycolin** [comment]
AFAIK, there's none from API-wise. There might be a way to track the state from the addon but that'd be a lot of work and in all honesty not a top priority for me right now versus other issues since I'm only a volunteer.
