### ISSUE TITLE
twitter urls are not loaded anymore in firefox 82.0b2

### ISSUE THREAD

**Issue by Faldrian** [mozilla/multi-account-containers#1873]
- Multi-Account Containers Version: 7.0.2
- Operating System + Version: Arch Linux
- Firefox Version: 82.0b2 (64-Bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

| Name                              | Typ        | Version       | Aktiviert | ID                                     |
| --------------------------------- | ---------- | ------------- | --------- | -------------------------------------- |
| English United States Dictionary  | dictionary | 68.0          | true      | @unitedstatesenglishdictionary         |
| German Dictionary                 | dictionary | 2.0.6.1webext | true      | de-DE@dictionaries.addons.mozilla.org  |
| Amazon.de                         | extension  | 1.3           | true      | amazon@search.mozilla.org              |
| Bing                              | extension  | 1.2           | true      | bing@search.mozilla.org                |
| DuckDuckGo                        | extension  | 1.1           | true      | ddg@search.mozilla.org                 |
| eBay                              | extension  | 1.2           | true      | ebay@search.mozilla.org                |
| Ecosia                            | extension  | 1.0           | true      | ecosia@search.mozilla.org              |
| Firefox Multi-Account Containers  | extension  | 7.0.2         | true      | @testpilot-containers                  |
| Google                            | extension  | 1.1           | true      | google@search.mozilla.org              |
| LEO Eng-Deu                       | extension  | 1.0           | true      | leo_ende_de@search.mozilla.org         |
| Wikipedia (de)                    | extension  | 1.1           | true      | wikipedia@search.mozilla.org           |
| Copy Current Page URL with Anchor | extension  | 1.0           | false     | jid1-grAPHQfoBoWMdA@jetpack            |
| I don't care about cookies        | extension  | 03.02.01      | false     | jid1-KKzOGWgsW3Ao4Q@jetpack            |
| Link Gopher                       | extension  | 2.0.1         | false     | linkgopher@oooninja.com                |
| Tab Session Manager               | extension  | 06.02.01      | false     | Tab-Session-Manager@sienori            |
| Temporary Containers              | extension  | 01.09.01      | false     | {c607c8df-14a7-4f28-894f-29e8722976af} |
| To Google Translate               | extension  | 4.0.6         | false     | jid1-93WyvpgvxzGATw@jetpack            |
| uBlock Origin                     | extension  | 1.29.2        | false     | uBlock0@raymondhill.net                |

### Actual behavior
On loading an url in a tab, it immediately shows a firefox error (I don't know how to unlocalize it... sadly): "Beim Laden der Seite https://twitter.com/___GreenTea13/status/1308612227449016321 wurde gegen das Netzwerkprotokoll verstoßen. Dieser Fehler kann nicht behoben werden."

The inspector shows this error message on the console: "Fehler beim Laden von 'https://twitter.com/___GreenTea13/status/1308612227449016321'. Ein ServiceWorker hat eine mit 'TypeError: NetworkError when attempting to fetch resource.' abgelehnte Promise an FetchEvent.respondWith() übergeben."

### Expected behavior

The page is loaded.

### Steps to reproduce
1. Open a new tab
2. Paste "https://twitter.com/___GreenTea13/status/1308612227449016321" into awesome bar and submit.
3. Error.

### Notes

When I disable the account container plugin, open a new tab and paste the url, the page loads. At the time of this test it was the only active extension, so this should have an influence on the faulty behaviour.

**Comment by keguira** [comment]
I have the same issue. I had a container dedicated to twitter. A workaround was to remove this container and create a new one.

**Comment by rsip22** [comment]
The same happens here... what solves is reloading the page holding SHIFT (SHIFT+CTRL+R), then the page loads correctly for some reason. Every time.

This only happens to the container where I'm logged on Twitter. Other containers are able to load the Twitter page correctly.

Firefox for Fedora 81.0.1 (64-bit)

**Comment by constantoine** [comment]
Can confirm I have the same issue on Windows (64bits) too, so this isn't just an issue on the linux versions

**Comment by FinnKlausen** [comment]
Same problem on MacOs  Catalina (64bit)

**Comment by constantoine** [comment]
This was somehow fixed. You should close

**Comment by rpl** [comment]
> This was somehow fixed. You should close

Yes, this issue is very likely not specific to the multi account container extension, it is more like the issue tracked on bugzilla as [Bug 1662925](https://bugzilla.mozilla.org/show_bug.cgi?id=1662925), landed in Firefox 83 and uplifted to Firefox 82.

**Comment by dannycolin** [comment]
Closing since the bug upstream has been fixed. Feel free to open a new bug report if a similar issue happen again.
