### ISSUE TITLE
Auto-filled password text fields on page are hidden. [input/text boxes/fields are hidden after :-moz-autofill (with a CSS filter) is applied]

### ISSUE THREAD

**Issue by Myron-S** [mozilla/multi-account-containers#1880]
I've been reporting in this fault in Bugzilla and it could be a fault between Firefox and uBlock origin.

To save me duplicating reported details please see Bugzilla issue:

input/text boxes/fields are hidden after :-moz-autofill (with a CSS filter) is applied
[https://bugzilla.mozilla.org/show_bug.cgi?id=1650653](https://bugzilla.mozilla.org/show_bug.cgi?id=1650653)

**Comment by dannycolin** [comment]
Closing as this is an issue with Firefox autofill and not with Multi-Account Containers.
