### ISSUE TITLE
Windows Persian/Farsi keyboard "No space word break" conflicting with open new container tab shortcut

### ISSUE THREAD

**Issue by geniusbabak** [mozilla/multi-account-containers#1881]
- Multi-Account Containers Version:    7.1.0
- Operating System + Version:             Windows 10
- Firefox Version:                                  81.0

- Other installed Add-ons + Version + Enabled/Disabled-Status:
Adblock Plus                                   |    3.9.5    |    Enabled
Amazon.com                                   |    1.3       |    Enabled
Bing	extension                                |    1.2       |    Enabled
Custom Style Script                         |    0.1.4    |    Enabled
DuckDuckGo                                   |    1.1       |    Enabled
eBay                                                |    1.2       |    Enabled
Facebook Container                         |    2.1.2    |    Enabled
Firefox Multi-Account Containers     |    7.1.0    |    Enabled
Google                                            |    1.1       |    Enabled
JSONView                                        |    2.2.0    |    Enabled
Tomato Clock                                   |    6.0.0    |    Enabled
Wikipedia (en)                                  |    1.1       |    Enabled 

### Actual behavior

In Windows machines with Persian/Farsi keyboard to type "No space word break" we have to press Ctrl+Shift+2
I'm trying to type: "نامه‌ی"
Between "نامه" and "ی" there is a "No space break" that we have to press Ctrl+Shift+2.
If we don't it will become: "نامهی"

Anytime I'm pressing that key combination, in addition to the "No space break", it will open a new container tab. We have to close the tab and go back to our previous tab and we have a lot of those "No space breaks" to type in Persian.

### Expected behavior
It should just type the character and go forward.

### Steps to reproduce
1. In windows machine change you keyboard input language to Persian/Farsi
2. Start typing in any text box in Firefox
3. press Ctrl+Shift+2

### Notes

Here is the bug link in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1667796

**Comment by geniusbabak** [comment]
Here is the link to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1667796

**Comment by dannycolin** [comment]
Hi, 

First of all, I'm a new contributor on the project and I'm triaging old issues but I'd like to apologize for the lack of response on behalf of the team.

For your issue, you can remap the default addon keyboard by following the instructions at https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#modify-extension-shortcuts

I'm closing this issue now. If you encounted other issues, you can [ask for help on our support forum](https://support.mozilla.org/en-US/questions/new/desktop/form).
