### ISSUE TITLE
Ebay and Paypal Issue

### ISSUE THREAD

**Issue by 1tonBunny** [mozilla/multi-account-containers#1884]
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Firefox 86.0 for Ubuntu
Multi container version 7.1.0

### Actual behavior
When using Ebay and Paypal in separaate containers purchases do not work. The only way around this to open Paypal in the same container as Ebay for that transaction.  You can access Paypal in it's own container without issues but any other transaction even for other on-line organisations frequently doesn't work. You have to do the same as for Ebay. This should be made clear to users so that they know that they cannot keep their financial transactions separate from the site they are on for purchases.

With ebay you cannot print out a complete return label just the last bit that is a packing slip. Selecting pages to print from All, first, or second page has no affect

### Expected behavior
Printing out should not be affected by the container.  I assume that the actual return slip is on another server and the container cannot handle the re-direction though seeing that Ebay is in the cloud across CDN, etc this should not affect it

### Steps to reproduce
1. Go to Ebays link to return label. (This only occurs after a seller has accepted a return)
2.Click on Print label and select your printer, pages to print (usually All), and click on print
3. The page that should be printed are All that are two pages

**Comment by devurandom** [comment]
https://github.com/mozilla/multi-account-containers/issues/2244 appears to be a duplicate, but has some additional information.

**Comment by dannycolin** [comment]
This is the expected behavior. If you assign a site to a container, it can't be opened anywhere else. Currently, your only option is to remove the assignment (See https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#remove-always-open-in-site-from-a-container). 

There's also a feature request to allow a domain in multiple container. See #1749
