### ISSUE TITLE
Google recognizes me across container tabs

### ISSUE THREAD

**Issue by Integralist** [mozilla/multi-account-containers#1888]
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: macOS Catalina 10.15.7
- Firefox Version: 81.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

<table xmlns="http://www.w3.org/1999/xhtml">
        <thead>
          <tr>
            <th data-l10n-id="support-addons-name">Name</th>
            <th data-l10n-id="support-addons-type">Type</th>
            <th data-l10n-id="support-addons-version">Version</th>
            <th data-l10n-id="support-addons-enabled">Enabled</th>
            <th data-l10n-id="support-addons-id">ID</th>
          </tr>
        </thead>
        <tbody id="addons-tbody">
        <tr><td>Amazon.co.uk</td><td>extension</td><td>1.3</td><td>true</td><td>amazon@search.mozilla.org</td></tr><tr><td>Bing</td><td>extension</td><td>1.2</td><td>true</td><td>bing@search.mozilla.org</td></tr><tr><td>Chambers (UK)</td><td>extension</td><td>1.0</td><td>true</td><td>chambers-en-GB@search.mozilla.org</td></tr><tr><td>Dark Reader</td><td>extension</td><td>4.9.21</td><td>true</td><td>addon@darkreader.org</td></tr><tr><td>DuckDuckGo</td><td>extension</td><td>1.1</td><td>true</td><td>ddg@search.mozilla.org</td></tr><tr><td>DuckDuckGo Privacy Essentials</td><td>extension</td><td>2020.10.2</td><td>true</td><td>jid1-ZAdIEUB7XOzOJw@jetpack</td></tr><tr><td>eBay</td><td>extension</td><td>1.2</td><td>true</td><td>ebay@search.mozilla.org</td></tr><tr><td>ExpressVPN: VPN proxy to unblock everything</td><td>extension</td><td>4.9.4.3713</td><td>true</td><td>firefox-addon@expressvpn.com</td></tr><tr><td>Firefox Multi-Account Containers</td><td>extension</td><td>7.1.0</td><td>true</td><td>@testpilot-containers</td></tr><tr><td>Google</td><td>extension</td><td>1.1</td><td>true</td><td>google@search.mozilla.org</td></tr><tr><td>Privacy Badger</td><td>extension</td><td>2020.10.7</td><td>true</td><td>jid1-MnnxcxisBPnSXQ@jetpack</td></tr><tr><td>uBlock Origin</td><td>extension</td><td>1.30.2</td><td>true</td><td>uBlock0@raymondhill.net</td></tr><tr><td>Wikipedia (en)</td><td>extension</td><td>1.1</td><td>true</td><td>wikipedia@search.mozilla.org</td></tr></tbody>
      </table>

### Actual behavior

I open a 'Personal' container and log into gmail.com. I open another 'Personal' container and visit youtube.com and discover that I'm now logged into my Google account there.

### Expected behavior

To visit youtube.com in another 'Personal' container should not result in me being logged into a Google account within that container. i.e. I should be a non-logged in/anonymous user as far as YouTube is concerned.

**Comment by NiklasBr** [comment]
I might be misunderstanding you, but it reads to me like things works as advertised:

The "Personal" and "Personal" windows/tabs are *one* container, not two, they can share cookies and such data. Therefore if you want two sites to not be able to do this you need *two* different containers, such as *Mail* and *Media*. Log in to Gmail in *Mail* and the open YouTube in *Media* and now Google should not be able to follow you into the second container.

**Comment by Integralist** [comment]
Ahhh. OK I definitely misunderstood what a 'container' represented then in the context of this Firefox plugin.

I presumed that each 'personal' tab opened was a _new_/_unique_ container instance (so although they both would be grouped by the category of 'personal' they would be isolated -- which I now understand is incorrect 🤦‍♂️)

**Comment by FlorianWendelborn** [comment]
@Integralist I think this issue can be closed. Can you do that?

**Comment by maxxcrawford** [comment]
@Integralist You may want to checkout [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/). It's by one of this extensions' maintainers, @stoically!

**Comment by Integralist** [comment]
Thanks all!
