### ISSUE TITLE
[Feature Request] degoogle gmail links.

### ISSUE THREAD

**Issue by D33M0N** [mozilla/multi-account-containers#1895]
Yes I know, this is entirely out of the scope of this addon, but still, hear me out please.
(I have not found an working addon that does this (at least not together with this addon), so maybe... you can help)

while I have gmail open and I see inside email a link for lets say:
http://www.auto24.ee/

gmail overwrites this url on click to:
https://www.google.com/url?q=https://www.auto24.ee/&source=gmail&ust=1603359820495000&usg=AFQjCNEE8SwsaUJQxNMzl57G9PhwzDT4NQ

(AND it does prompt this addon to suggest if I want to open this site in my gmail container or in my google container, but I do not want to open it in either. I don't even want it to go to www.google.com/url in the first place)

Which totally effs up containers and tracking prevention. I DO NOT WANT to open this link through google tracking proxy or in the gmail container. Also I can't just "limit gmail container to just included domains" or it will break sadly. So can you please add into this addon "leaving gmail url proxy removal" feature, so it does just go directly to the link in the mail??? Or does anyone actually know an addon that does exactly that?

I mean you ALREADY before opening a link put yourself into the process to determine into which container (if any) to open this link into. So it would already make sense if you would offer url un-injection feature before/while doing your container selection thing?

gmail link injection example:
![image](https://user-images.githubusercontent.com/15782020/96709517-76489f80-13a3-11eb-827d-b1a1fbbd3473.png)

How about [Open "https://www.youtube.com/attribution_link?a=iAjJ-9KQxutAY80s&u=/watch%3Fv%3DsKUDWonC6UU%26feature%3Dem-uploademail" directly in YOUTUBE container without the fking google url tracking proxy] button? :smile_cat:

**Comment by groovecoder** [comment]
Sorry yeah, this is outside the scope of this add-on. If someone knows another add-on that strips tracking params, maybe they can add it here in case someone else comes and find this issue?
