### ISSUE TITLE
[Feature Request] Open tabs in dedicated containers based on domains

### ISSUE THREAD

**Issue by derritter88** [mozilla/multi-account-containers#1896]
It would be a great feature, if Multiaccount Container would be able to open new sites in dedicated containers based on the domain.
E.g.:
**Internal LAN**
company.lan & *.company.lan should be opened in Company container

**Comment by CheariX** [comment]
Maybe i oversee something, but if you set `privacy.firstparty.isolate = true`, the behavior should be _very_ similar.

You can check out [freddyb's extension](https://addons.mozilla.org/en-US/firefox/addon/first-party-isolation/) and [identifier-linkability](https://2019.www.torproject.org/projects/torbrowser/design/#identifier-linkability) for more details.

**Comment by derritter88** [comment]
Yeah I had the setting enabled before - but having containers would be a better solution from my point of view.
If I could have all internal stuff in one container, than website A would be able to see what website B does.

Or if I buy something from an online shop and payment will direct me to Paypal it would be fine if it all happens in one container.
Sometimes I had the problem that such things (website A redirects to website B and then back to website A) caused issues.

**Comment by groovecoder** [comment]
Duplicate https://github.com/mozilla/multi-account-containers/issues/473 I believe.
