### ISSUE TITLE
Changing the order of containers

### ISSUE THREAD

**Issue by pervoj** [mozilla/multi-account-containers#1898]
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: Linux Mint 20 Ulyana, Kernel x86_64 Linux 5.4.0-47-generic
- Firefox Version: 82.0

Please, add possibility to change the order of containers. Tanks.

**Comment by groovecoder** [comment]
Duplicate of https://github.com/mozilla/multi-account-containers/issues/330
