### ISSUE TITLE
Two completely different UIs for managing containers: please unify

### ISSUE THREAD

**Issue by Pomax** [mozilla/multi-account-containers#1905]
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Long-click for new tab offers this UI:

![image](https://user-images.githubusercontent.com/177243/99296550-cb899c80-27fb-11eb-9739-ad2428752023.png)

which pops up this page

![image](https://user-images.githubusercontent.com/177243/99296570-d47a6e00-27fb-11eb-8384-c1b33971285e.png)

which only offers these controls for containers:

![image](https://user-images.githubusercontent.com/177243/99296591-dc3a1280-27fb-11eb-86b8-3a3160a2110d.png)

However, if you _manually_ add the addon icon to the toolbar, we get this UI:

![image](https://user-images.githubusercontent.com/177243/99296625-ebb95b80-27fb-11eb-802d-5f17a9845d21.png)

Which takes us to:

![image](https://user-images.githubusercontent.com/177243/99296652-f4119680-27fb-11eb-9ec0-0358ef982d43.png)

And then offers _more options_ than the management options you got from long-press (or even literally going to addons and picking options):

![image](https://user-images.githubusercontent.com/177243/99296721-08ee2a00-27fc-11eb-80f4-37c4a163917e.png)

Why are these completely different UIs? I understand that they might "live" in different places by why don't they even offer the same options?

Please fix this, as the by-far more conventional way to configure an addon is through the addon's own options system.

**Comment by securingmom** [comment]
Consider extending _Manage Site List_ to a UI element next to each container.

**Comment by rainygg** [comment]
Agreed. Not to mention that they aren't exactly feature rich. Domains such as goo.gl cannot be added because the window to catch them with "Always open with" is either so small or nonexistent. Some TLC for this screen is in order.

**Comment by augustgerro** [comment]
Honestly, it's not the best place to hide menu item "Manage sites lists". 
If you are a beginner or you have a lot of containers and you accidentally put google.com in one of them - it will be hell for you why there are redirects, why you can't log in, find the menu item responsible for the list of sites, find in which container is this domain, etc.

I think it would be nice to rethink the UI UX for such a useful extension.

**Comment by gauravmundra** [comment]
Has there been any development on this? Or does this discussion continue on another page?

**Comment by dannycolin** [comment]
> Why are these completely different UIs? I understand that they might "live" in different places by why don't they even offer the same options?

This is because both interfaces have nothing to do with each other. Firefox has an experimental UI for managing containers and Multi-Account Containers is an optional addon to manage your containers. IOW, they're completely two distinct products using the ContextualIdentities API under the hood. 

There are third-party addons like [Containerise](https://addons.mozilla.org/en-US/firefox/addon/containerise/) that are alternative to Multi-Account Containers.

If something is missing in the built-in UI for containers in Firefox, I'll invite you to open a bug report on bugzilla.mozilla.org so the right people can have a look at it. 

Closing for now since there's nothing we can do on our side.

**Comment by Pomax** [comment]
if they have nothing to do with each other, then why do they by all accounts look exactly the same?
