### ISSUE TITLE
Tab Crashes: Print Preview with Simplify Page Option

### ISSUE THREAD

**Issue by mikegilchrist** [mozilla/multi-account-containers#1906]
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: Linux MATE 18.04
- Firefox Version: 82.0.3
- Other installed Add-ons + Version + Enabled/Disabled-Status: Lots...

### Actual behavior
When I am trying to print a page using "Print Preview" with the "Simplify Page" option ticked, the tab crashes and I have to reload the page

### Expected behavior

I expect to be able to print the page

### Steps to reproduce
1. Open a web page, such as (https://www.sciencemag.org/news/2020/11/leprosy-ancient-scourge-humans-found-assail-wild-chimpanzees)
2. Go to Print Preview and then check 'Simplify Page'
3. Click 'Print' and the tab will crash

### Notes

I tried printing a page without containers and it worked fine

**Comment by dannycolin** [comment]
Can you still reproduce in a recent version of Firefox?

**Comment by mikegilchrist** [comment]
Firefox no longer displays this bug.

**Comment by dannycolin** [comment]
Great! I'll close this bug for now. Feel free to create a new one if needed. :)
