### ISSUE TITLE
Add-On does not add any controls (no menu item and context-menu) when installed.

### ISSUE THREAD

**Issue by ColinTimBarndt** [mozilla/multi-account-containers#1911]
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: Microsoft Windows 10 10.0.18363
- Firefox Version: 83.0 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

|Name                            |Type     |Version   |Activated|ID                                            |
|--------------------------------|---------|----------|---------|----------------------------------------------|
|Amazon.de                       |extension|1.3       |true     |amazon@search.mozilla.org                     |
|Bing                            |extension|1.2       |true     |bing@search.mozilla.org                       |
|DuckDuckGo                      |extension|1.1       |true     |ddg@search.mozilla.org                        |
|eBay                            |extension|1.2       |true     |ebay@search.mozilla.org                       |
|Ecosia                          |extension|1.0       |true     |ecosia@search.mozilla.org                     |
|Firefox Multi-Account Containers|extension|7.1.0     |true     |@testpilot-containers                         |
|Google                          |extension|1.1       |true     |google@search.mozilla.org                     |
|LEO Eng-Deu                     |extension|1.0       |true     |leo_ende_de@search.mozilla.org                |
|Wikipedia (de)                  |extension|1.1       |true     |wikipedia@search.mozilla.org                  |
|ClearURLs                       |extension|1.20.0    |false    |{74145f27-f039-47ce-a470-a662b129930a}        |
|Dark Reader                     |extension|4.9.24    |false    |addon@darkreader.org                          |
|Duden.de Suche WE               |extension|2.0.2     |false    |{4a746a55-5792-44d4-ae79-20779c8a8413}        |
|Enhancer for YouTube™           |extension|2.0.101   |false    |enhancerforyoutube@maximerf.addons.mozilla.org|
|Firefox DevTools ADB Extension  |extension|0.0.5     |false    |adb@mozilla.org                               |
|GitHub Dark Theme               |extension|1.1.21    |false    |{1dbe3fd3-f191-4a3b-a5d7-a6f95ed2aea1}        |
|HTTPS Everywhere                |extension|2020.11.17|false    |https-everywhere@eff.org                      |
|NoScript                        |extension|11.1.5    |false    |{73a6fe31-595d-460b-a920-fcc0f8843232}        |
|Privacy Badger                  |extension|2020.10.7 |false    |jid1-MnnxcxisBPnSXQ@jetpack                   |
|React Developer Tools           |extension|4.10.0    |false    |`@react-devtools`                               |
|Stylus                          |extension|1.5.13    |false    |{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}        |
|Three.js Developer Tools        |extension|0.4.0     |false    |three-devtools@jsantell.com                   |
|uBlock Origin                   |extension|1.31.0    |false    |uBlock0@raymondhill.net                       |

### Actual behavior
When I install the add-on, no icon is added and there is no menu where I can select the container. Everything behaves as if the add-on was never installed.

### Expected behavior
The add-on should let me use it as in the showcase video by Mozilla.

### Steps to reproduce
1. Install the add-on.
2. Notice that there is no icon added to the menu-bar

### Notes
I checked whether containers are activated, and they are:
![screenshot1](https://user-images.githubusercontent.com/26167910/100206247-607c4c00-2f06-11eb-814b-0e1ac24fcd90.png)
Here's a screenshot of all Icons that I can use in the browser:
![screenshot2](https://user-images.githubusercontent.com/26167910/100206778-0fb92300-2f07-11eb-8a34-443de9f60e4f.png)

**Comment by Trafficriot911** [comment]
In options, under Privacy and Security, scroll down to "History" and turn off the setting that says "Never remember history." Either use "Remember History" or "Custom"

**Comment by ColinTimBarndt** [comment]
Thank you, this solved the issue.
