### ISSUE TITLE
Feature request: open links from bookmarks bar, history view, etc. in container tab via context menu

### ISSUE THREAD

**Issue by TheHarmonicRealm** [mozilla/multi-account-containers#1919]
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: Windows 10
- Firefox Version: 83.0

### Request

I would love it if when right clicking links from places like the bookmarks bar or the history menus there were an option to open them in a container tab, like the thing you see when you right click links in a web page.

**Comment by Sayrus** [comment]
This seems to be implemented under optional permissions:
![image](https://user-images.githubusercontent.com/22404472/106582044-75dfa900-653b-11eb-811a-bb1b2aef58b1.png)

Once enabled, you can right click any bookmark and pick "Open Bookmark in Container Tab".

**Comment by TheHarmonicRealm** [comment]
Thanks!!
