### ISSUE TITLE
How to restore extension configuration from Firefox profile backup

### ISSUE THREAD

**Issue by braian87b** [mozilla/multi-account-containers#1922]
Hey! I just migrated days ago to a new computers and set up firefox copying the profile directory from a backup.
everything fine, later I ran a firefox refresh to clean some data, and now I installed multi-account containers and want to restore just that extension configuration from my backup instead of replace entire firefox profile directory.

how can I achieve this?, I do not have any of these paths:
~/.mozilla/firefox/<profile-id>/browser-extension-data/@testpilot-containers/storage.js
~/.mozilla/firefox/<profile-id>/browser-extension-data/@testpilots/containers.js
so may be recent version have the data somewhere else?

Thanks!

**Comment by jschwartzenberg** [comment]
Yeah I'm also trying to discover the new storage location. I'm curious if it would be possible to share predefined containers with site lists in a corporate setting.

**Comment by grahamperrin** [comment]
> … I'm also trying to discover the new storage location. …

Me too, for #2027

**Comment by grahamperrin** [comment]
#2030

**Comment by dannycolin** [comment]
Closing in favor of #2030 that should give you the information needed.
