### ISSUE TITLE
Add Firefox for Android support

### ISSUE THREAD

**Issue by 532910** [mozilla/multi-account-containers#1929]
Time has passed since #989. Fennec become Fenix. But it still would be nice to have multi-account-containers on mobile.

**Comment by dannycolin** [comment]
Sadly, there's nothing we can do until the Container API is implemented in Fenix. See [#10581 on Fenix repository](https://github.com/mozilla-mobile/fenix/issues/10581).

**Comment by 532910** [comment]
Let's leave this open utill #10581 resolution.

**Comment by dannycolin** [comment]
Fair enough. I simply wanted to make everyone aware that it depends on something that needs to be implemented upstream. Hopefully, it'll happen sooner than later :)

**Comment by dannycolin** [comment]
Moved to https://connect.mozilla.org/t5/ideas/multi-account-containers-for-android
