### ISSUE TITLE
Limiting extensions by container works in MacOS, but not Windows 10

### ISSUE THREAD

**Issue by Bout2GitIt** [mozilla/multi-account-containers#1937]
### Actual Behavior
I've configured my [Honey extension](https://www.joinhoney.com/) to only work in the Shopping container. I've done this by 
- Setting JoinHoney.com to always open in Shopping container
- Setting the extension's UUID to always open in the Shopping container
- Whitelisting *.joinhoney.com in Cookie Autodelete
- Using the extension on sites in the Shopping container (like eBay and Amazon, which I've set to always open in Shopping)

When I try to use the Honey extension in Windows 10, the extension prompts me to login. When I login, I'm taken to a joinhoney.com page in the Shopping container, where I get a notification: You're already logged in. But when it takes me back to the site where I'm trying to use the extension (like eBay) I get the first notification again: login to Honey.

### Expected behavior
After logging into Honey (either in its webpage or in the extension) the extension should work as normal: filling in discount codes on websites. 

What's strange is that the Honey extension is working normal in MacOS, even though I've done exactly the same steps on my Mac: I've set the Honey domain and the extension UUID to run only in the Shopping container. And it works!

I thought this might be related to my VPN, as Honey often has difficulties logging in when my VPN is active. But I disabled the VPN on my Window's machine and the problem persists.  I even turned the VPN on on my Mac, and the Honey extension still works there. 

My Mac setup:
Multi-Account Containers Version 7.1.0 
MacOS 10.15.7
Firefox version 83
Honey version 12.4.5 - enabled

My Windows setup:
Multi-Account Containers Version 7.1.0 
Windows 10 Home v. 1909 x64
Firefox version 84.0.1
Honey version 12.4.5 - enabled.

### Steps to reproduce
1. Navigate to a website in my Shopping container (or any container) on my Windows machine
2. Try to use the Honey extension. Get prompted to login. Click the login link.
3. Get taken to joinhoney.com (in the Shopping container) and see that I'm already logged in.
4. Get taken back to the original website and try to use Honey extension. Told I'm not logged in.

### Notes
Here is my full extensions list on MacOS:
|   Name    |	Type  |	Version  |  	Enabled  |  	
|---------------|-----------|-------|--------|
Amazon.com	| extension |	1.3	| true	|
Australis-like refresh in URL bar	| extension	| 1.0.2	| true	|
Bing	| extension	| 1.2	| true	
Bitwarden - Free Password Manager	| extension	| 1.47.1	| true	|
CaretTab - New Tab Clock and Date	| extension	| 2.3.1	| true	|
CheckThemAll	| extension	| 1.5 |	true	| 
ClearURLs	| extension	| 1.20.0	| true	|
Cookie AutoDelete	| extension	| 3.5.1	| true	| 
Crypto Ticker	| extension	| 1.0.16	| true	| 
Decentraleyes	| extension	| 2.0.15	| true	| 
Disable Ctrl-Q and Cmd-Q	| extension	| 1	| true	| 
DuckDuckGo	| extension	| 1.1	| true	| 
eBay	| extension	| 1.2	| true	| 
Facebook Container	| extension	| 2.1.2	| true	| 
Feed Preview	| extension	| 12	| true	| 
Firefox Multi-Account Containers	| extension	| 7.1.0	| true | 
Google	| extension	| 1.1 |	true	| 
Google Container	| extension	| 1.5.3	|true	|
Herp Derp for YouTube™	|extension|	1.6.10	|true	|
Honey	|extension	|12.4.5	|true	|
HTTPS Everywhere	|extension	|2020.11.17	|true	|
Invidition	|extension	|0.16.0	|true	|
Privacy Badger	|extension	|2020.12.10	|true	|
Reddit Enhancement Suite	|extension	|5.20.9	|true	|
Snowflake	|extension	|0.5.2	|true	|
Tags for YouTube™	|extension	|8.4	|true	|
Tree Style Tab	|extension	|3.6.4	|true	|
Trello Card Counter	|extension	|1.1	|true	|
uBlock Origin	|extension	|1.31.0	|true	|
Ugly Email	|extension	|4.1.0	|true	|
Video DownloadHelper	|extension	|7.4.0	|true	|
Wayback Machine	|extension	|1.8.6	|true	|
Wikipedia (en)	|extension	|1.1	|true	|
WX Download Status Bar	|extension	|1.10.0	|true	|
LeechBlock NG	|extension	|1.0.8	|false	|
Lolli: Earn Bitcoin When You Shop	|extension	|1.4.8	|false	|
Metastream Remote	|extension	|0.6.0	|false	|
Pay by Privacy.com	|extension	|1.6.3	|false	|

And here's the extension list on my Windows machine:
| Name |	Type 	|Version| 	Enabled |
|------------------------|---------|------|--------|
Amazon.com	|extension	|1.3|	true	|
Australis-like refresh in URL bar|	extension|	1.0.2|	true|	
Bing	|extension|	1.2|	true|	
Bitwarden - Free Password Manager|	extension	|1.38.0|	true	|
CaretTab - New Tab Clock and Date	|extension	|2.3.1	|true|	
CheckThemAll	|extension|	1.5|	true|	
Chrome Store Foxified	|extension|	3.4	|true|	
ClearURLs	|extension|	1.20.0|	true	|
Cookie AutoDelete|	extension	|3.5.1	|true|	
Crypto Ticker	|extension|	1.0.16	|true|	
Decentraleyes|	extension|	2.0.15|	true	|
Disable Ctrl-Q and Cmd-Q|	extension	|1|	true|	
DuckDuckGo	|extension|	1.1|	true|	
eBay	|extension|	1.2	|true	|
Facebook Container|	extension|	2.1.2|	true|	
Feed Preview|	extension|	12	|true|	
Firefox Multi-Account Containers|	extension|	7.1.0	|true|	
Google	|extension	|1.1|	true	|
Google Container|	extension|	1.5.3|	true|	
Herp Derp for YouTube™	|extension|	1.6.10|	true|	
Honey	|extension|	12.4.5	|true|
HTTPS Everywhere|	extension|	2020.11.17|	true	|
Invidition	|extension|	0.16.0|	true	|
Privacy Badger	|extension|	2020.12.10|	true|	
Reddit Enhancement Suite	|extension|	5.20.10	|true|	
Snowflake	|extension|	0.5.2|	true|	
Tags for YouTube™|	extension|	8.4|	true|	
Tree Style Tab	|extension|	3.6.4	|true|
Trello Card Counter	|extension|	1.1|	true|	
uBlock Origin|	extension|	1.32.4	|true|	
Ugly Email	|extension|	4.1.0|	true	|
Video DownloadHelper|	extension|	7.4.0|	true|	
Wayback Machine	|extension	|1.8.6|	true|	
Wikipedia (en)	|extension|	1.1	|true|	
WX Download Status Bar	|extension|	1.10.0	|true|	
Firefox Private Network	|extension|	15|	false|
LeechBlock NG	|extension|	1.0.8|	false|	
Lolli: Earn Bitcoin When You Shop|	extension|	1.4.8|	false|
Metastream Remote|	extension|	0.6.0|	false|	
Pay by Privacy.com|	extension|	1.6.3|	false|

**Comment by dannycolin** [comment]
Close as invalid. Multi-Account Containers doesn't allow enabling/disabling extensions per container. See #1167
