### ISSUE TITLE
Slack no longer working in container

### ISSUE THREAD

**Issue by tbloch1** [mozilla/multi-account-containers#1939]
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: Windows 10 Education v1909
- Firefox Version: 84.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Amazon.co.uk	extension	1.3	true	amazon@search.mozilla.org
Bing	extension	1.2	true	bing@search.mozilla.org
Chambers (UK)	extension	1.0	true	chambers-en-GB@search.mozilla.org
ClearURLs	extension	1.20.0	true	{74145f27-f039-47ce-a470-a662b129930a}
Cookie AutoDelete	extension	3.5.1	false CookieAutoDelete@kennydo.com
Disconnect	extension	20.3.1.1	false 2.0@disconnect.me
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.2	true	ebay@search.mozilla.org
F.B Purity - Cleans up Facebook (WX)	extension	31.4.1.0	false fbpElectroWebExt@fbpurity.com
Facebook Container	extension	2.1.2	true	@contain-facebook
Film scores for Netflix	extension	1.1.0	false {6babe29b-f164-4a56-8081-06f939062cdb}
Firefox Multi-Account Containers	extension	7.1.0	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
HTTPS Everywhere	extension	2020.11.17	false https-everywhere-eff@eff.org
LastPass: Free Password Manager	extension	4.62.0.6	false support@lastpass.com
Reddit Enhancement Suite	extension	5.20.12	false jid1-xUfzOsOFlzSOXg@jetpack
Temporary Containers	extension	1.9.1	true	{c607c8df-14a7-4f28-894f-29e8722976af}
uBlock Origin	extension	1.32.4	false uBlock0@raymondhill.net
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
Greasemonkey	extension	4.10.0	false	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
SCDL SoundCloud Downloader	extension	5.2	false	scdl@mrvv.net
SoundCloud MP3 Downloader	extension	0.2.6	false	jid1-hnmMaq1milpehc6uI@jetpack

### Actual behavior
When trying to open one of my slack workspaces in it's default container, the page remains blank. The refresh button is also greyed out. I am unable to use slack.

slack.com loads fine, but when I try to navigate to one of my workspaces the same thing occurs. slack.com is also in the same default container as the workspaces which no longer work.

Everything works fine in a private tab.

### Expected behavior
Slack workspaces open so that I can use them.

### Steps to reproduce
1. open a slack workspace that has a default container

**Comment by SiM07** [comment]
You can disable the tracking protection as a workaround.

**Comment by jennydaman** [comment]
I also have this issue. In the "Network" tab of devtools I can see the Transferred state is `NS_ERROR_DOM_ABORT_ERR`

**Comment by jennydaman** [comment]
Bug is known elsewhere on the Internet.

https://www.mooreds.com/wordpress/archives/3429

Fix by clearing site data (cookies, storage) on app.slack.com in about:preferences#privacy

**Comment by tbloch1** [comment]
That's not the same issue as the one I posted @jennydaman.
But I'm glad you found a fix for your problem!

**Comment by grahamperrin** [comment]
> … the fix worked …

Is there still an issue? If so, it might belong in Bugzilla for Mozilla (not specific to this extension).

**Comment by dannycolin** [comment]
Since the issue was solved by clearing site data and it isn't obvious if it's a bug with the addon or Firefox itself, I'm going to close this issue for now. Feel free to open a new bug report if needed.
