### ISSUE TITLE
Modifying Keyboard Shortcuts

### ISSUE THREAD

**Issue by derrickberg-dev** [mozilla/multi-account-containers#1940]
### Actual behavior
The keyboard shortcut "Ctrl + Shift + >" is opening the Multi Account Containers extension menu.

### Expected behavior
The ability to disable it, as its overriding a keyboard shortcut that I am using for something else.

### Steps to reproduce
1. Push the keyboard shortcut "Ctrl + Shift + >" and it should open the Multi Account Containers extension menu.

**Comment by ahzaz** [comment]
This can be modified directly from Firefox.
1. Go to [about:addons](about:addons)
2. Clicking the settings button next to "Manage Your Extensions"
3. Select "Manage Extension Shortcuts"
4. Update the keyboard shortcuts for Firefox Multi-Account Containers

**Comment by derrickberg-dev** [comment]
Oh I see it completely ignores shift and triggers ctrl + period ... ha
