### ISSUE TITLE
Feature request: Leave container

### ISSUE THREAD

**Issue by cbndr** [mozilla/multi-account-containers#1942]
This add-on keeps getting better. One option I miss though, is to "leave" a container.

Example: I have all Google sites opening in a "Google container", but when I click on a search result, say the Apple website, I want that site NOT to open in the Google container. Same for external Facebook links.
This works if the new site has its own container assigned, but obviously that's not the case for all Google search results.

So if I follow a link while surfing in a container that's not assigned to the same container, I'd like to go back to "no container" or a designated "other sites container".

This could be an option per container or a global option.

**Comment by currybullen** [comment]
Doesn't this already exist? 

![image](https://user-images.githubusercontent.com/8695615/104125610-31a42300-5358-11eb-8ce6-5581115265e5.png)

**Comment by cbndr** [comment]
You are right, thanks! Works as expected, too xD
