### ISSUE TITLE
Feature request: Skip asking for "Always open in container"

### ISSUE THREAD

**Issue by cbndr** [mozilla/multi-account-containers#1943]
I would prefer not to be asked if I always want to open a link in the designated container. Instead, this should be automatic from the beginning.

Maybe a global option could be added for this.

**Comment by maxxcrawford** [comment]
Once you click the "Remember my decision for this site" checkbox on that prompt, it goes away. 
<img width="817" alt="image" src="https://user-images.githubusercontent.com/2692333/104222133-7935b800-5407-11eb-9d3b-f2fa51f63ff7.png">
