### ISSUE TITLE
Select light/dark theme option in preferences panel

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/multi-account-containers#1948]
Currently, Dark Mode support automatically [matches](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) the dark/light theme of the OS. 

There should be an option to override this behavior in the preferences panel. 

Copy:
- Headline: Dark Mode Theme
- Radio Buttons: 
  - Default to system
  - Light color mode 
  - Dark color mode 
- Description: This setting manages how the add-on appears in your browser. 
 
Placement: 

<img width="717" alt="image" src="https://user-images.githubusercontent.com/2692333/104226443-6d4cf480-540d-11eb-96fa-5c82c8d9b0d7.png">

**Comment by maxxcrawford** [comment]
cc/ @dannycolin

**Comment by maxxcrawford** [comment]
This is how I'd solve it: https://stackoverflow.com/a/56550819

**Comment by dannycolin** [comment]
> This is how I'd solve it: https://stackoverflow.com/a/56550819

Yep, I used something very similar for [SUMO Live Helper](https://addons.mozilla.org/en-US/firefox/addon/sumo-live-helper-/) (addon for the Support Mozilla contributors) so I'd be almost a matter of copy/pasting ;)

**Comment by dannycolin** [comment]
To implement this feature, I need to convert hardcoded color values to CSS custom properties. However, there's a few inconsistency for the hardcoded one and redundancy for those that are already a custom properties in the colors. For example, at [line 935 to 950](https://github.com/mozilla/multi-account-containers/blob/f4bcd30434e8e9a2a66fff21deb804606bc957d0/src/css/popup.css#L935) there's `--title-text-color` and `--text-heading-color` or `--text-normal-color` and `--text-grey`.

So my question is: Could I standardize a bit more the code for the colors and use the Photon Design System as a guideline? This changes won't be visible for the users but it will definitely makes the code cleaner. 

@maxxcrawford is that ok with you?

**Comment by maxxcrawford** [comment]
@dannycolin Yes – As long as we're consistent, and it matches as closely as it can, let's go for it!

**Comment by dannycolin** [comment]
@maxxcrawford I don't know if you got a notification when I referenced this issue in #1964 so I thought I'll comment here to let you know. No rush tho :wink:

**Comment by maxxcrawford** [comment]
@dannycolin Thanks for the ping. Just did a quick review of #1964! 🙌
