### ISSUE TITLE
How to manually re-arrange containers?

### ISSUE THREAD

**Issue by GildedHonour** [mozilla/multi-account-containers#1951]
How to manually re-arrange existing containers to be in an order I want?

**Comment by adamency** [comment]
Have you installed the extension through addons.mozilla.org ? If so, then you have to wait for the 7.3 version to drop there, it just got released in the repo here less than 24 hours ago.

**Comment by itprofessional74** [comment]
The ability to sort doesn't seem to work so I opened an issue with specifics around what I'm seeing.

**Comment by adamency** [comment]
@itprofessional74 Well you could give a link to it.

**Comment by ve3** [comment]
Confirmed re-arrange not really working, just displaying in management menu.

**Comment by grahamperrin** [comment]
> … just displaying in management menu. …

Mine are in alphabetical order: 

![image](https://user-images.githubusercontent.com/192271/115895340-377acb80-a452-11eb-860f-880095c2602a.png)

`about:profiles`

@ve3 if you can reproduce a problem with a new profile, please seek/open a separate issue. Thanks.

**Comment by grahamperrin** [comment]
> How to manually re-arrange containers?

1. click **Manage Containers**
2. use the drag handles. 

@GildedHonour you can close this issue now. Thanks.

**Comment by ve3** [comment]
New profile doesn't help and I don't know why I have to open the same issue again.

**Comment by grahamperrin** [comment]
> the same

It's different.

**Comment by itprofessional74** [comment]
This still isn't working.  You can drag and manage via the extension button when that arrangement does not show when you click the + to create a new tab.  So changing the order does nothing on the + create new tab button as that is set in a different area.

**Comment by grahamperrin** [comment]
>> manually re-arrange containers

> This still isn't working. 

Containers can be manually rearranged. 

----

> does not show when you click the + to create a new tab. 

That's your separate issue ▶ #1952 … do you want to keep it separate?

**Comment by grahamperrin** [comment]
▶ #1866 – [Feature Request / Suggestion: Sorted Container List · Issue #1866 · mozilla/multi-account-containers](https://github.com/mozilla/multi-account-containers/issues/1866)

**Comment by dannycolin** [comment]
Fixed by #1608.
