### ISSUE TITLE
UI: Scroll-arrows of context menu container list overlapp with entry

### ISSUE THREAD

**Issue by meneken17** [mozilla/multi-account-containers#1953]
- Multi-Account Containers Version: 7.2.0
- Operating System + Version: Windows 10 (64-bit ) 20H2
- Firefox Version: 84.0.2 (64-bit)

### Actual behavior
Whe you have a lot of containers (so much thy dont fit on your display anymore; ~50) and use the "Open in Tab" context menu entry at the top and bottom of the list a scroll arrow appears.
When you then type a key on your keyboard to skip to an entry the selected entry is sometimes hidden behind the scroll arrows.

### Expected behavior
The selected entry should not be overlapped by the arrow

### Steps to reproduce
1. Create ~50 Containers (depending on your screen size)
2. Right click on a tab and select "open in"
3. A list of all your containers opens
4. Scroll to the top and have at least 2 entrys at the bottom which are not shown.
5. Type the first letter of the next-to-last container untill it selects it.
6. You can see that the container is selected and blue, but still hiddenbehind the scroll-down arrow.

![hidden-behind-arrow](https://user-images.githubusercontent.com/8579800/105770871-0e849080-5f60-11eb-9643-7d23c1b005c8.png)

**Comment by dannycolin** [comment]
This is a bug in Firefox. If you can still reproduce in the latest version, please file a bug report on https://bugzilla.mozilla.org.
