### ISSUE TITLE
custom containers reset on add-on disable

### ISSUE THREAD

**Issue by Wojtus11** [mozilla/multi-account-containers#1957]
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Win7/x64
- Firefox Version: 85.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Polish Spellchecker Dictionary	dictionary	1.0.20160228.1webext	true	pl@dictionaries.addons.mozilla.org
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Feedbro	extension	4.9.4	true	{a9c2ad37-e940-4892-8dce-cd73c6cbbc0c}
Firefox Multi-Account Containers	extension	7.3.0	true	@testpilot-containers
Gesturefy	extension	3.0.7	true	{506e023c-7f2b-40a3-8066-bc5deb40aebe}
Google	extension	1.1	true	google@search.mozilla.org
Mute sites by default	extension	1.10	true	@mute-sites-by-default
Skip Redirect	extension	2.3.4	true	skipredirect@sblask
uBlock Origin	extension	1.32.4	true	uBlock0@raymondhill.net
Universal Bypass	extension	13.15.1.3	true	{529b261b-df0b-4e3b-bf42-07b462da0ee8}
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
Containerise	extension	3.8.1	false	containerise@kinte.sh
Facebook Container	extension	2.1.2	false	@contain-facebook
Google Container	extension	1.5.3	false	@contain-google
Greasemonkey	extension	4.11	false	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}

### Actual behavior
Once MAC is disabled in Add-on settings, and then re-enabled again, containers are reset to default names and custom ones removed. Firefox Sync enabled, but this does not help.

### Expected behavior
All containters to be retained as they are until add-on is uninstalled. Possibility to export/import settings as backup.

### Steps to reproduce
1. Create custom container.
2. Open Add-on manager in Firefox, disable MAC.
3. Re-enable MAC. Containter list is reset to default.

### Notes
Setting are in fact not completely lost, as usually creating a new container automagically gets settings from "deleted" one.

**Comment by dedworks** [comment]
Same here with Firefox 85 and M.A.C. 7.3 on both MacOS and Windows

Especially inconvenient while #1960 is forcing me to disable the extension multiple times per day

**Comment by benyaminl** [comment]
Yeah I lost my data just now. Oh Boi... there're no option to back it up?

**Comment by Valtarien** [comment]
Like as in @drmirk's post, I second the suggestion for manual export/import. I wish I had the above problem, but mine is the reverse: I want to reset my containers, set them up how I like, export them, and import them again in case of future problems. Especially since I would like to erase all my containers and start over, then export my setup in case of future problems. I know I could delete them manually, but I have dozens, if not hundreds, of containers added by the "Temporary Containers" add-in. We need some way to export, import, & reinstall manually.
