### ISSUE TITLE
Extension for Chrome

### ISSUE THREAD

**Issue by jbmitchell2** [mozilla/multi-account-containers#1962]
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
PLEASE PLEASE PLEASE port this into a Chrome Extension!!!!!!

### Expected behavior
Usable in Chrome.  PLEASE!

### Steps to reproduce
1.
2.
3.

**Comment by jbmitchell2** [comment]
Thanks for the heads up.  I have entered the feature request.  Myself, my entire team, and many of my customers could kiss Firefox COMPLETELY goodbye if they included this support.

**Comment by jbmitchell2** [comment]
What a pain.  Thanks for the insight.

**Comment by dannycolin** [comment]
Closing since there's nothing we can do on our side as long as Chrome doesn't support the API needed.
