### ISSUE TITLE
Icons/Colours

### ISSUE THREAD

**Issue by Ulrome-Bardsea** [mozilla/multi-account-containers#1965]
Is it possible to add more icons and additional colours in the drop down when creating a new container ?

**Comment by steffenlyng** [comment]
perhaps it could be possible to add your own icons, and choose from a color-dropper, which colours to use

**Comment by michaljenicek** [comment]
+1

**Comment by luisnabais** [comment]
+1

**Comment by weyCC81** [comment]
Have a look at https://github.com/mozilla/multi-account-containers/issues/391

**Comment by grahamperrin** [comment]
> Icons

▶ 2017 issue #843, 2018 issue #1185

> Colors

▶ 2017 issue #391

@Ulrome-Bardsea please close this duplicate. Thank you.

**Comment by dannycolin** [comment]
duplicate of #2368 and #391
