### ISSUE TITLE
Can I add a website to "Always open in an ordinary tab" ?

### ISSUE THREAD

**Issue by kskollepara** [mozilla/multi-account-containers#1967]
Everytime I search a word through the context menu, it opens in the same container. I would like any search to open without any container.

**Comment by ameaninglessname** [comment]
Anyway, you may add a "context menu search engine" extension, and it may open a new tab in default container.

**Comment by rohit-gohri** [comment]
This is also needed for some apps that have associated extensions, for eg passbolt. The extension is only able to authenticate the session if logged in the default container.

**Comment by kskollepara** [comment]
Is there a way to mark this post as a feature request?

**Comment by grahamperrin** [comment]
For search purposes: 

* _Never contain_
* _Never open in container_
* _Never open in a container_

I imagine an additional checkbox, wherever the context menu submenu presents the checkbox that's pictured here: 

![image](https://user-images.githubusercontent.com/192271/115877192-12c92880-a43f-11eb-8d15-04a2c3fb43bc.png)

* the two boxes should be mutually exclusive.

**Comment by grahamperrin** [comment]
> This is also needed for some apps that have associated extensions, for eg passbolt. The extension is only able to authenticate the session if logged in the default no container tab.

Does the extension work if you open a new (non-contained) tab before authentication?

**Comment by grahamperrin** [comment]
> Always open in an ordinary tab

▶ 2017 issue #503

@kskollepara please close this duplicate issue. Thank you.

**Comment by grahamperrin** [comment]
Thanks!
