### ISSUE TITLE
How to get per-tab containers work?

### ISSUE THREAD

**Issue by al-caveman** [mozilla/multi-account-containers#1971]
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: gentoo, latest
- Firefox Version: 85.0.2.-r1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

```
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
Dark Reader	extension	4.9.27	true	addon@darkreader.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
Firefox Multi-Account Containers	extension	7.3.0	true	@testpilot-containers
FoxyProxy Standard	extension	7.5.1	true	foxyproxy@eric.h.jung
Google	extension	1.1	true	google@search.mozilla.org
HTTP Header Live	extension	0.6.5.2	true	{ed102056-8b4f-43a9-99cd-6d1b25abe87e}
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
uBlock Origin	extension	1.33.2	true	uBlock0@raymondhill.net
English (GB) Language Pack	locale	85.0buildid20210118153634	true	langpack-en-GB@firefox.mozilla.org
```

### Actual behavior
Can't see anything that lets me to use containers.  E.g. `Ctrl + .` is not working.  I never used this before, but I guess right clicks on tabs should give me a container menu?  Or left click on tabs?  I don't get that either. 

### Expected behavior
Get per-tab container.

### Steps to reproduce
1. install firefox in gentoo.
2. install the add-on.
3. click around.
4. experience failure and disappointment.

**Comment by trevormeier** [comment]
MAC appears to have stopped working for me as well.

macOS 11.2.1
Firefox 85.0.2
MAC 7.3.0

**Comment by dannycolin** [comment]
For reference, you can find instructions on the basics in https://support.mozilla.org/en-US/kb/containers
