### ISSUE TITLE
FF Container Rules Lost

### ISSUE THREAD

**Issue by akasaka99** [mozilla/multi-account-containers#1975]
Hi - 
A few days ago after a sudden crash on FF 85 on my MacOS 13.6(High Sierra)
I lost all my containers (even though I had sync turned on) but was able to recover them with the disk backup I had of containers.json. 
However, even though I now have my FF Containers back, I don't have the rules associated of each website doing the automatic sorting. 
Where would I be able to find these rules as now the websites just load in the default tab (outiside of containers) ? 
I presume it would be another JSON file? 
Thanks !!

**Comment by akasaka99** [comment]
No one from the developers know in which file the rules are stored???

**Comment by grahamperrin** [comment]
> … in which file the rules are stored …

https://github.com/mozilla/multi-account-containers/search?q=storage&type=commits led me to https://github.com/mozilla/multi-account-containers/commit/136aa3ce0e5a8214d85d1e1aa593ebedf3341db0 (wip: cleaning up storage before sync), from which I assume that no _single_ file comprises, or includes, the set of **site lists** for a profile's set of containers.

Instead: 

* [storage - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage)

### `about:devtools-toolbox?id=%40testpilot-containers&type=extension`

An inspection of _extension storage_ in my case, after beginning to recreate the site associations for  `userContextId` ``1` (Personal): 

![image](https://user-images.githubusercontent.com/192271/115952303-16ab8800-a4dd-11eb-8050-a4cbb70ab106.png)

[Storage Inspector - Firefox Developer Tools | MDN](https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector) 

* the beginning of the page is incomplete (listing five storage types but not extension storage)
* the end of the page includes a link to [Extension Storage - Firefox Developer Tools | MDN](https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector/Extension_Storage). 

There remains a question – whether what's stored for _Firefox Multi-Account Containers_ can be effectively: 

1. extracted from a non-bugged profile (or backup)
2. reused where required.

**Comment by dannycolin** [comment]
This is most likely related to #1236. We got reports in the past where a crash or an update triggered this issue.
