### ISSUE TITLE
Feature request Open a site in a new container without being redirected to the default Container.

### ISSUE THREAD

**Issue by SpinB** [mozilla/multi-account-containers#1980]
My request is the possibility of opening a domain with a already assigned container to open on another container, for ex. if you have Domain1 assigned to Container Mail1 using Account1, right-click and on a Top Site (about:newtab) and open Domain 1 in Container Mail2 to use Account2 without getting automatically redirect to Container Mail1, the request is  to **NOT automatically redirect users to the default container if they choose another one, but keep using the default one if no container is defined by the user.**

**Comment by dannycolin** [comment]
Duplicate of #1442
