### ISSUE TITLE
No bookmarks on Firefox Android?

### ISSUE THREAD

**Issue by johnbirds** [mozilla/multi-account-containers#1983]
Bookmarks won't work because no optional permissions on Firefox Android?

**Comment by mmtmn** [comment]
There is no version that works on android.. right??

**Comment by dannycolin** [comment]
> There is no version that works on android.. right??

No.

**Comment by dannycolin** [comment]
Let's close this since there's nothing actionable on our side for now. We can revisit it when the API is available in Android. For reference, that's https://bugzilla.mozilla.org/show_bug.cgi?id=1638878
