### ISSUE TITLE
Feature Request: regular expression support

### ISSUE THREAD

**Issue by tux-box** [mozilla/multi-account-containers#1984]
I would rather use wild cards like *.domain.tdl or regular expressions to assign sites to containers than to add every possible subdomain to a list.

**Comment by btsimon97** [comment]
This seems to be related to #1909 .

**Comment by rektide** [comment]
This could be a fix for #691. Would love it so much. :heartbeat:

**Comment by dannycolin** [comment]
Duplicate of #691
