### ISSUE TITLE
No way to remove "always open in x container" in newer version?

### ISSUE THREAD

**Issue by KittyNone** [mozilla/multi-account-containers#1989]
Hi! I'm using Firefox 86.0 on Win10 and as near as I can tell I can no longer unassign sites which I marked "always open in x container" under a previous version of the plugin. I know there used to be a checkbox that one could simply uncheck to allow the site to open in the default container, but I can't seem to find any way to do that anymore; the only option available is to assign it to a different named container. Am I missing something? Is the option in a new place? Or do I have no choice but to either live with it or delete the entire container?

**Comment by grahamperrin** [comment]
> No way …

There is (at least) the context menu for the page: 

![image](https://user-images.githubusercontent.com/192271/111555915-48645d00-8781-11eb-8906-3563b3026ebd.png)

**Comment by grahamperrin** [comment]
There's also the wastebasket/bin/trash icon: 

![image](https://user-images.githubusercontent.com/192271/115882068-4ce8f900-a444-11eb-93c4-d5d72a621397.png)

**Comment by macks2008** [comment]
I was also wondering about this? When did they change this? I wanted to temporarily unassign twitter because one site is trying to send it data (I assume in cooking form, since I don't see any URL variables) I actually want to send (related to sharing something) but the "open in assigned tab?" page is blocking it.

**Comment by macks2008** [comment]
@grahamperrin maybe? But I was more asking hypothetically than expecting a specific answer.

**Comment by grahamperrin** [comment]
I'm an end user.
