### ISSUE TITLE
No way to remove a container

### ISSUE THREAD

**Issue by desmap** [mozilla/multi-account-containers#1993]
Pretty much the title and not the same as in https://github.com/mozilla/multi-account-containers/issues/1989

**Comment by grahamperrin** [comment]
Try: 

**Delete This Container**

![image](https://user-images.githubusercontent.com/192271/111555702-dd1a8b00-8780-11eb-9c3b-4a09eb62dae2.png)

**Comment by desmap** [comment]
I must have be blind! Thanks @grahamperrin!
