### ISSUE TITLE
Feature Request: A private-mode MAC

### ISSUE THREAD

**Issue by scottdrichards** [mozilla/multi-account-containers#1994]
Motivation:
My ideal Firefox usage scenario is to have the default browsing mode be Private but then provide the minimally sufficient credentials for actions requiring authentication. So let's say I want to purchase something online. I can browse in private mode but when I find what I wish to purchase, I enable the minimal cookies required to authenticate and complete the purchase.

Current State:
I use the default container (i.e., not being in a container) for my browsing but manually switch containers when I want to be logged in. The issue is, the default container slowly accumulates cookies and trackers (and the accidental login) which negates much of the intent of using containers for this purpose.

Desired Behavior:
Default container is private-mode or pseudo-private mode which clears cookies/cache regularly.

**Comment by wilku103** [comment]
You can use an addon to automatically clear cookies, or use temporary containers addon which after configuration, will automatically make new container for every website

**Comment by scottdrichards** [comment]
Would be nice if there were a first-party solution but I will check this out.

**Comment by wilku103** [comment]
Yeah, implementing temporary containers into MAC would be awesome
