### ISSUE TITLE
Feature Request: handling multiple tabs

### ISSUE THREAD

**Issue by ideophone** [mozilla/multi-account-containers#1998]
it would be most helpful: being able to apply an option of the 'Firefox Multi-Account Containers' to **multiple tabs at once** (i.e., Reopen in Container, Always Open This Site in, ...).

(If selecting the intended tabs and then applying some option to them is not doable: maybe being able to _Open an entire window in a container #1878_ would be an alternative approach.
In either case, such a feature would make it necessary that _Feature request: close tab when re-opening in a new container #1852_ is also implemented.)

**Comment by dannycolin** [comment]
1. ctrl + left click multiple tabs to select them
2. Right-click on a tab and select the action you want to execute (e.g. Open in New Container Tab)

This should be executed on all the selected tabs.
