### ISSUE TITLE
[FEATURE] Separate history - landing page - etc...

### ISSUE THREAD

**Issue by JurgenG** [mozilla/multi-account-containers#2002]
I'd like to use multi-containers to have different personae (e.g. github for work in work container, private github for private container). The most important feature in here for me, would be separate histories for every container.

A nice added feature would be to also containerize password vaults (but not for me as I'm using a dedicated password manager).

- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Windows 10, Ubuntu (both)
- Firefox Version: 86.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: I will add these if relevant.

### Actual behavior
When visiting a site in one container, it shows this site in the history of a different container. As the start page also reflects this history (if configured so), it will also show items that are not relevant to the container context.

### Expected behavior
When inside a container, I only see the history of this container. When opening a new container tab, the suggestions offered will be based upon my containerized history.

### Steps to reproduce
1. Go to container 1 and visit example.org/container1
2. Go to container 2 and start typing examp (autosuggest will show example.org/container1)

### Notes
Thanks already for the ongoing development on FF and the addons!

**Comment by dannycolin** [comment]
History: [bug 1283320](https://bugzilla.mozilla.org/show_bug.cgi?id=1283320)
Homepage: #1289 

Closing as duplicate.
