### ISSUE TITLE
Sorting tabs ( feature request )

### ISSUE THREAD

**Issue by rifaterdemsahin** [mozilla/multi-account-containers#2005]
I want to be able to sort my container tabs
right now they are static i need the most used ones to be placed on the top.

**Comment by tkforbes** [comment]
I will second this request.

**Comment by GrayJack** [comment]
I think this is already possible using "Sort tabs by container" but I think and want to be able to control the priority of the sorting for my containers

**Comment by naught101** [comment]
I would like to be able to reverse the sort order

**Comment by dannycolin** [comment]
> right now they are static i need the most used ones to be placed on the top.

Do you mean reordering the list in the popop panel? If yes, this has already been implemented. You can go in Manage Containers and drag-and-drop them.

**Comment by dannycolin** [comment]
Closing since I didn't get any answer back and that this feature is already implemented on Multi-Account Containers side. For the order in the menus rendered by Firefox itself, we have #1958 to track this.
