### ISSUE TITLE
Files to Copy to Another Browser

### ISSUE THREAD

**Issue by monkeylove** [mozilla/multi-account-containers#2009]
I am currently testing a browser that has no sync option. Is there a way for me to copy the files used by Multi-Account Containers to that browser so that all options show up.

So far, what I did was copy containers.json and cookies.sqlite, and the containers are there except for the sites assigned to each container.

**Comment by dannycolin** [comment]
I can't guarantee the data integrity but copying the profile folder from one computer to the other should work. See this help article to find where your profile folder is: https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data#w_how-do-i-find-my-profile
