### ISSUE TITLE
Last update was 3 months ago. Is this project still alive? 

### ISSUE THREAD

**Issue by naoliden** [mozilla/multi-account-containers#2012]
Last update was 3 months ago. Is this project still alive? I don't see anyone responding to other issues.

**Comment by grahamperrin** [comment]
Yes, it's still alive. 

> Last update was 3 months ago.

At the time of writing, the most recent commit was 2021-03-09. 

https://github.com/mozilla/multi-account-containers/commits/master

If you can, please aim to deduplicate issues.

**Comment by Zyxyx** [comment]
Seems pretty dead right now...
This is the feature I find the most useful with Firefox (together with the 'Temporary Containers' extension).

Unfortunately quite a few things are not working as expected or could be improved, as demonstrated by the number of reported issues and submitted pull requests waiting for approval.

Does anyone know why this extension is not updated anymore by Mozilla (or anyone really) ?

**Comment by maxxcrawford** [comment]
😏
