### ISSUE TITLE
feature request: window (not only tab) title to include container name

### ISSUE THREAD

**Issue by jayenashar** [mozilla/multi-account-containers#2017]
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Debian 10 amd64
- Firefox Version: 87.0 (64-bit)

### Actual behavior
"page title &mdash; container name" is shown when i mouseover the tab in the tab bar (as expected)
"page title &mdash; Mozilla Firefox" is shown in my OS's window's title bar

### Expected behavior
"page title &mdash; container name" is shown when i mouseover the tab in the tab bar (as actual)
"page title &mdash; container name &mdash; Mozilla Firefox" is shown in my OS's window's title bar

### Steps to reproduce
1. open a tab in a container

### Notes
For the purposes of my automatic time tracker.

**Comment by dannycolin** [comment]
This needs to be implemented in Firefox itself. Please file a bug report on https://bugzilla.mozilla.org.
