### ISSUE TITLE
Support UserScripts that activate based on e.g., container name. Maybe getAssignmentByTabId?

### ISSUE THREAD

**Issue by nl-brett-stime** [mozilla/multi-account-containers#2022]
### Expected behavior
It'd be nice if there were some way to conditionally activate a UserScript e.g., running in an external extension such as GreaseMonkey, based upon the container context of the current tab.

### Actual behavior
The M-AC API (https://github.com/mozilla/multi-account-containers/wiki/API) currently provides a method to `getAssignment` by URL. It looks like there's also an internal message handler to `getAssignment` by `tabId` (https://github.com/mozilla/multi-account-containers/blob/ef66bee9293913b69b3562b4bb9df3616d0483de/src/js/background/messageHandler.js#L38-L42).

### Notes
I don't know if it's possible to make calls similar to the following in a UserScript, but if so, it'd be cool if multi-account-containers supported it. If not, then some other means would be appreciated.

E.g.,

```
// ==UserScript==
// @include http://some-site.com/*
// ==/UserScript==

const currentTabDetails = await browser.tabs.getCurrent();

const containerResponse = await browser.runtime.sendMessage('@testpilot-containers', {
  method: 'getAssignmentByTab',
  tab: currentTabDetails
});

if (containerResponse.name == 'Personal') {
  // do stuff
}
```

**Comment by nl-brett-stime** [comment]
https://github.com/greasemonkey/greasemonkey/issues/3092

**Comment by dannycolin** [comment]
Closing since this is something the GreaseMonkey addon should implement on their side.
