### ISSUE TITLE
'Reopen in Container' context menu missing.  Now replaced with 'Open in New Container Tab'

### ISSUE THREAD

**Issue by shadowmage45** [mozilla/multi-account-containers#2025]
### Actual behavior
'Reopen in container' context menu option missing.  Instead has been replaced with 'Open in New Container Tab'

### Expected behavior
'Reopen in container' context menu should be present.

### Steps to reproduce
1. Right click a tab that is opened in a container, and see the context menu option 'Reopen in container' is no longer present.

### Notes

This started happening mid-day today.  No updates were performed to the PC, Firefox, nor any extensions.

How to restore the 'Reopen in Container' context menu option when clicking on a tab?  

![image](https://user-images.githubusercontent.com/1503399/115791605-f4ebbd00-a385-11eb-991a-618e08cb3859.png)

**Comment by grahamperrin** [comment]
Please close this issue. 

What you see is: 

* a feature of Mozilla Firefox
* not the Multi-Account Containers extension. 

Thank you.
