### ISSUE TITLE
Tab colouring in bad position after firefox update

### ISSUE THREAD

**Issue by kinnison** [mozilla/multi-account-containers#2029]
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Debian Buster
- Firefox Version: 89.0b3
- Other installed Add-ons + Version + Enabled/Disabled-Status:

(not sure this is needed but can provide if necessary)

### Actual behavior

The coloured stripe to indicate which container a tab belongs to is now at the top of the tab handle (the bit with the icon/title)

### Expected behavior

The coloured strip should have remained at the bottom of the tab handle

### Steps to reproduce

Not certain, other than it happened after the most recent firefox beta update I received.
All I can say for sure is that the coloured lines are in the right place on FF 87.0 but not on 89.0b3

### Notes

The reason this is bad is that now the coloured lines are directly next to the window furniture which makes them harder to spot.  In addition they used to form a useful visual divider between the tab handles and the toolbar beneath.  Now the two parts of the UI seem to bleed into each other.

**Comment by grahamperrin** [comment]
This will probably require a fix in Firefox. Compare with, for example, these two Mozilla bugs (closed): 

* [1325902 - Increase visibility of container highlight on tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1325902)
* [1387117 - Especially in maximized window, it is almost invisible the container color indicator. And it is no longer visible for selected tab](https://bugzilla.mozilla.org/show_bug.cgi?id=1387117)

I'm not familiar with `89.⋯`, is Photon enabled in your case?

**Comment by kinnison** [comment]
How would I tell if it is?  I'll admit I went on the beta path a while ago for webrender, but I don't actually do complex things with firefox configuration normally.

**Comment by PoisonFrog** [comment]
I'm having the same problem. I hope it gets fixed next update.

**Comment by toupeira** [comment]
Related upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1703789

**Comment by SquidPony** [comment]
I find that with my window not maximized and therefore arbitrary things behind the firefox window, it's quite a bit harder than before to tell what tab is what.

I changed to a non-default theme so that I could at least see what tab was active, and as a by-product the container colors got easier to see. But with them at the top against the visual noise of other content directly above them from other windows they are waaaay less usable than before.

**Comment by dannycolin** [comment]
Closing since shis is a design choice from Firefox and we can't change it on our side. Feel free to open a feature request on Firefox bug tracker at https://bugzilla.mozilla.org.
