### ISSUE TITLE
Consider adding search/filter ui box

### ISSUE THREAD

**Issue by zackzack02** [mozilla/multi-account-containers#2035]
The rationale is simple. Beyond 100 containers it is hard to get to the desired one (have to scroll and manually search for, it takes time). 
A small search / filter box at the top / or bottom of the containers list would be helpful to filter by container name .

**Comment by grahamperrin** [comment]
▶ #1103

Please close this duplicate. Thank you.

**Comment by grahamperrin** [comment]
Thanks!
