### ISSUE TITLE
Extension storage: the about:devtools-toolbox view of keys and values is often incomplete

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/multi-account-containers#2039]
about:devtools-toolbox?id=%40testpilot-containers&type=extension

This morning, for example: 

![image](https://user-images.githubusercontent.com/192271/116799783-66004280-aaf3-11eb-9c70-bb2198915de5.png)

* as if there are only two letters _a_ and _b_ in the alphabet.

**Comment by grahamperrin** [comment]
If _not_ a cosmetic bug (in Firefox): 

* is failure to handle this data a possible cause of **failure to present the page context menu item**?

https://github.com/mozilla/multi-account-containers/issues/1996#issuecomment-830721081

**Comment by rpl** [comment]
@grahamperrin I did notice your message related to this issue in Matrix, quoting here my answer for future reference:

> grahamperrin : I confirm asuth guess, that seem to be an issue with the storage panel and the bugzilla component asuth did mention would be the right one to report it, if I'm reading correctly your multi-account-container issue, that is likely to be some kind of pagination issue of the storage panel (not sure if it is specific to the Extension Storage or to any other kind of storage under similar conditions).
> grahamperrin: If you could [report it on bugzilla as a "Devtools :: Storage Inspector" bug](https://bugzilla.mozilla.org/buglist.cgi?product=DevTools&component=Storage%20Inspector&resolution=---), it would very appreciated (Feel free to also add me in CC on the bug, I mentored the engineer that added support for the ExtensionStorage in that panel and so I do have some context about how it works internally and some of the limitations of the current version)

Personally I doubt that this is the underlying issue for the context menu entries missing in the screenshot you attached to https://github.com/mozilla/multi-account-containers/issues/1996#issuecomment-830721081
Based on the screenshot the entry seems to not have been rendered more than be missing, I'm wondering it that cold be a rendering issue (e.g. one that may be related to WebRender), the information from about:support for the profile where you are able to trigger that issue may help to determine what is the actual issue behind #1996.

I think this one would be worth being reported to "DevTools :: Storage Inspector" using the link above.

**Comment by dannycolin** [comment]
Closing since it isn't an issue with Multi-Account Containers itself.
