### ISSUE TITLE
SUGGESTION: Select bookmark folder to be opened by containere. All bookmarks in that folder will always be opened in the specified container

### ISSUE THREAD

**Issue by dugajean** [mozilla/multi-account-containers#2041]
It would be pretty awesome if I could do the following:

1. Right click on a bookmark folder and select "Open each bookmark within this folder in _Work_ container"
2. With step 1, now whenever I open a bookmark from my _XYZ_ folder, it will open those bookmarks in the _Work_ container by default

This would be a pretty neat feature as I like to organize my bookmarks in folders and would like to be able to control which container those bookmarks should open in.

Hope you can consider this!

**Comment by buehda** [comment]
I would love this feature! It should also be possible to assign containers to each bookmark individually (I don't mean the feature "always open this site in…"). Like that I can save 2 bookmarks with the same URL but in different containers (with different Logins behind).

**Comment by dannycolin** [comment]
1. Type about:addons in the address bar
2. Choose Multi-Account Containers in the list
3. Go to the "preferences" tab for the addon
4. Enable Bookmark Menus

You can now right-click on a bookmark folder to open all in a specific container.
