### ISSUE TITLE
Poor contrast on  "Always Open this Site in…" confirmation page

### ISSUE THREAD

**Issue by htwyford** [mozilla/multi-account-containers#2044]
- Multi-Account Containers Version: 7.3.0
- Firefox Version: 89

This is a dupe of [Bug 1709812](https://bugzilla.mozilla.org/show_bug.cgi?id=1709812):

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0

Steps to reproduce:

(I) Click on the hamburger menu
(II) Click on More tools
(III) Click on Customize Toolbar…
(IV) Select the Dark theme
(V) Open a webpage
(VI) Click on the Always open this in a Container icon in the urlbar
(VII) Select any Container
(VIII) A page should pop up, asking for confirmation

Actual results:

The foreground color, used for the URL, is white, whereas the background color is a slightly darker white. I can't tell which URL I'm asking Firefox to assign to a Container.

Expected results:

Either the foreground or the background color should be black.
Considering how in the White theme the foreground color is black and the background color is white, in the Dark theme the foreground color should be white and the background color should be black.
This doesn't occur in Windows 10

**Comment by htwyford** [comment]
This issue has two related causes:
1. Starting in Firefox 89, in-content pages follow the Firefox theme and not the system theme. This happens with the new `-moz-toolbar-prefers-color-scheme: dark` media query: https://searchfox.org/mozilla-central/search?q=-moz-toolbar-prefers-color-scheme%3A+dark&path=&case=false&regexp=false.
2. We use solid colours on #redirect-url: https://github.com/mozilla/multi-account-containers/blob/4b56a2f0bb91cd9a12b95121fcff0c8e96ff66bd/src/css/confirm-page.css#L48-L65.

What's happening in the bug is that the user has a Light system theme but a dark Firefox theme. That gives us `prefers-color-scheme: light` but `-moz-toolbar-prefers-color-scheme: dark`. The in-content page in Firefox will be dark, but the #redirect-url element defined in this add-on will be light.

There are a few things we could do to resolve this. Using a transparent background would work, or we could use system colors like `Field` and `FieldText`. We could also define `#redirect-url` rules with `-moz-toolbar-prefers-color-scheme: dark` and use `prefers-color-scheme: dark` rules as a Firefox <89 fallback. Here's a sketch:

```
@media (prefers-color-scheme: dark) {
  #redirect-url {
      background: #38383d; /* Grey 70 */
      color: #eee; /* White 20 */
  }
}
@media (-moz-toolbar-prefers-color-scheme: dark) {
  #redirect-url {
    background-color: /* something better */;
    color: /* something better */ ;
  }
}

```

**Comment by dbw9580** [comment]
Can confirm on Firefox 89 and MacOS 11.3.1, too.

**Comment by dannycolin** [comment]
Do you still experience this issue?

**Comment by htwyford** [comment]
Nope!
