### ISSUE TITLE
browser.extension.getURL removed in Firefox 90

### ISSUE THREAD

**Issue by keithx2** [mozilla/multi-account-containers#2047]
[Deprecate APIs ahead of MV3 and disable in MV3](https://bugzilla.mozilla.org/show_bug.cgi?id=1687762)

That function is used in multiple files in the extension.

**Comment by grahamperrin** [comment]
>> 1687762 - Deprecate APIs ahead of MV3 and disable in MV3

https://hg.mozilla.org/mozilla-central/rev/b32c5f52acad
