### ISSUE TITLE
Usability Improvement: Can't open tab in proper container

### ISSUE THREAD

**Issue by loureirorg** [mozilla/multi-account-containers#2048]
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Ubuntu 20.04 (Linux 5.4.0-72-generic)
- Firefox Version: 88.0 (64-bit)

### Steps to reproduce
1. Open: `https://mozilla.org/`;
2. Select: "Always open this site in" > "**Personal**";
3. Select: "Open this site in" > "**Work**";

### Actual behavior
It opens step 3 in "Personal".

### Expected behavior
**Option 1:** To show me a screen, "You selected always to open this site in Personal. Open it in Personal or Work?'. 
**Option 2:** Open in "Work", as I explicitly commanded to - no need for confirmation screen as I'm clearly bypassing it.

Currently, I have no ways to open it in "Work". My workarounds are either re-opening it on Private mode or temporarily removing the "Always open in" and re-add it back later.

### Notes
Not a bug per see, more a usability improvement. Often, people want to always open a site in a container (ex. Amazon > Shopping). Still, there are exceptions where they need to open in a different container (ex. Amazon's AWS > Work).

**Comment by grahamperrin** [comment]
> … no ways to open it in …

▶ #1442

@loureirorg please, can you close this duplicate issue? Thank you.

**Comment by grahamperrin** [comment]
Thanks!
