### ISSUE TITLE
Right-clicking the container selection when creating a new tab opens the container selection a second time.

### ISSUE THREAD

**Issue by L4kritz** [mozilla/multi-account-containers#2050]
- Multi-Account Containers Version:7.3.0
- Operating System + Version:Windows 10 Pro 20H2
- Firefox Version:88.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

|Name                            |Typ       |Version                  |Aktiviert|ID                                      |
|--------------------------------|----------|-------------------------|---------|----------------------------------------|
|English United States Dictionary|dictionary|78.0                     |true     |@unitedstatesenglishdictionary          |
|German Dictionary               |dictionary|2.0.6.1webext            |true     |de-DE@dictionaries.addons.mozilla.org   |
|Amazon.de                       |extension |01. Apr                  |true     |amazon@search.mozilla.org               |
|Bing                            |extension |01. Mrz                  |true     |bing@search.mozilla.org                 |
|DuckDuckGo                      |extension |01. Jan                  |true     |ddg@search.mozilla.org                  |
|eBay                            |extension |01. Mrz                  |true     |ebay@search.mozilla.org                 |
|Ecosia                          |extension |1.0                      |true     |ecosia@search.mozilla.org               |
|Facebook Container              |extension |02.02.2001               |true     |@contain-facebook                       |
|Firefox Multi-Account Containers|extension |07.03.2000               |true     |@testpilot-containers                   |
|Firefox Relay                   |extension |01. Mai                  |true     |private-relay@firefox.com               |
|Google                          |extension |01.01.2021               |true     |google@search.mozilla.org               |
|Honey                           |extension |12.04.2005               |true     |jid1-93CWPmRbVPjRQA@jetpack             |
|LEO Eng-Deu                     |extension |1.0                      |true     |leo_ende_de@search.mozilla.org          |
|NightTimeFP theme               |extension |1.0.1                    |true     |{b3a962bb-594a-488e-ad44-d3e3e7673c67}  |
|Tab Reloader (page auto refresh)|extension |0.3.6                    |true     |jid0-bnmfwWw2w2w4e4edvcdDbnMhdVg@jetpack|
|Tab Session Manager             |extension |06.08.2000               |true     |Tab-Session-Manager@sienori             |
|Tomato Clock                    |extension |6.0.1                    |true     |jid1-Kt2kYYgi32zPuw@jetpack             |
|uBlock Origin                   |extension |1.35.2                   |true     |uBlock0@raymondhill.net                 |
|Wikipedia (de)                  |extension |01. Jan                  |true     |wikipedia@search.mozilla.org            |
|English (US) Language Pack      |locale    |88.0buildid20210415204500|true     |langpack-en-US@firefox.mozilla.org      |
|EPUBReader                      |extension |2.0.13                   |false    |{5384767E-00D9-40E9-B72F-9CC39D655D6F}  |
|Firefox Voice Beta              |extension |0.25.0                   |false    |firefox-voice@mozilla.org               |
|Private Internet Access         |extension |3.0.1                    |false    |{3e4d2037-d300-4e95-859d-3cba866f46d3}  |

### Actual behavior
![rightclick - Kopie](https://user-images.githubusercontent.com/68925999/118047600-838ea100-b36a-11eb-9172-ec280901141f.gif)

### Expected behavior
i dont know but not that.

### Steps to reproduce
1.left click new tab icon. A gray selection box pops up.
2. right click anywhere in the gray box. A second gray selection box pops up.
3. right click one if the items of the second box which opens the container or menu.

### Notes
If you right click the new Tab icon it does not work only first left and then right.

**Comment by dannycolin** [comment]
Closing since it's a bug in Firefox. See [bug 1781160](https://bugzilla.mozilla.org/show_bug.cgi?id=1781160)
