### ISSUE TITLE
[BUG] Containers button cannot be removed from URL field

### ISSUE THREAD

**Issue by ghost** [mozilla/multi-account-containers#2060]
**Current situation**
I am using the Container addon in such a way that I have added the Container button to the Mozilla Firefox toolbar (see screenshot 1) to access all the functions from there. This button is much more functional than the Container button that sits in the URL field (see screenshot 2).

**Issue**
The Container button from the URL field cannot be removed. Having two buttons for the same addon is redundant, especially because the button in the URL field has fewer functions.

**Expected behavior**
There should be an option (in the right click context menu or somewhere else) to remove the Containers button from the URL field.

**Information**
OS: Win 10 21H1 x64
FF: 89.0 x64
Container Addon: 7.3.0

Screenshot 1
![00001](https://user-images.githubusercontent.com/40357209/120360447-0a4ef200-c309-11eb-87ea-cac06c2b0be7.png)

Screenshot 2
![00002](https://user-images.githubusercontent.com/40357209/120360475-1044d300-c309-11eb-99a3-9076ce29d0c6.png)

**Comment by regifr** [comment]
need to remove "Always open this in a Container" icon from url bar

**Comment by blekmus** [comment]
![2021_07_06-01_56_43](https://user-images.githubusercontent.com/47277246/124515633-8606f780-ddfd-11eb-9f0a-384de927e121.png)

It also doesn't seem to adapt to the browser theme as well. But would love to have an option to disable it completely.

**Comment by dannycolin** [comment]
Close #2066
