### ISSUE TITLE
Confirm page: URL almost not legible due to lack of contrast when dark color scheme is configured

### ISSUE THREAD

**Issue by schnittchen** [mozilla/multi-account-containers#2064]
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: PopOS 20.10
- Firefox Version: 89.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: Lots, but I don't think it matters for this issue

### Actual behavior

URL in confirm page has too little text color contrast against the #redirect-url background 

![Screenshot from 2021-06-05 18-32-13](https://user-images.githubusercontent.com/166765/120898779-b99f0800-c62c-11eb-8a48-ccd34b0e408c.png)

### Expected behavior

The URL should be clearly visible

### Steps to reproduce
1. Configure a dark color scheme
2. Set up a site to always open in a container tab
3. Open a new tab in a different container, 
4. Confirm page is shown

**Comment by dhananjayraut** [comment]
I observed the same issue with firefox dark theme. looks like it depends on the color theme preference at the OS level. The text is unreadable when the OS theme is a light one (for example Adwaita on Linux) but looks as expected when the OS theme is set to a dark one.

**Comment by OscarL** [comment]
I had this issue too, until some update around the date Firefox 95.0 got released. Now all I get is a blinding white background,

Oof.

**Comment by dannycolin** [comment]
Do you still experience this issue in the latest version (8.0.9)?

**Comment by schnittchen** [comment]
Seems fixed, thanks!

**Comment by schnittchen** [comment]
Seems fixed, thanks!
