### ISSUE TITLE
Tab right click container menu missing

### ISSUE THREAD

**Issue by mr-brunes** [mozilla/multi-account-containers#2071]
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Win10/64  21H1
- Firefox Version: 89.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Amazon.co.uk	extension	1.9	true	amazon@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
Chambers (UK)	extension	1.0	true	chambers-en-GB@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Google	extension	1.1	true	google@search.mozilla.org
Simple Tab Groups	extension	4.7	true	simple-tab-groups@drive4ik
Tree Style Tab	extension	3.8.3	true	treestyletab@piro.sakura.ne.jp
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org

### Actual behavior
Right click Tab and no containers menu is visible

### Expected behavior
Right click Tab and containers menu is visible showing options to open new tab in container, re-open tab in container etc. 

### Steps to reproduce
1. Right click existing tab
2.
3.

### Notes
I think the menu disappeared with FF 89.0

**Comment by TomIsFat** [comment]
yes, #1920 doesn't work

**Comment by mr-brunes** [comment]
I don't see how #1920 is relevant as that concerns completely different functionality.

However I did find that right-clicking on a link still has the "Open link in New Container Tab" option, i.e. that used to be present on a tab.

**Comment by mr-brunes** [comment]
Bizarrely, the right click tab "Open In New Container Tab" menu option has reappeared on all my PCs!

However the "Reopen in Container" option as illustrated in https://youtu.be/FfN5L5zAJUo?t=718 is still missing.

**Comment by TomIsFat** [comment]
> 
> 
> I don't see how #1920 is relevant as that concerns completely different functionality.
> 
> However I did find that right-clicking on a link still has the "Open link in New Container Tab" option, i.e. that used to be present on a tab.

oh，I found my mistake

**Comment by dannycolin** [comment]
These menus are generated by Firefox itself. If you still experience this issue, please file a bug report on bugzilla.mozilla.org. Closing for now.
