### ISSUE TITLE
Unable to install the add-on, as FF claims that it's corrupt

### ISSUE THREAD

**Issue by harl** [mozilla/multi-account-containers#2073]
When I try to install this add-on directly from AMO, this is what I see:
"The add-on downloaded from this site could not be installed because it appears to be corrupt."
That's all I know about this, because all I get is this rather cryptic / redundant and not very convincing error message.

This is in FF 89.0.2 (and 90.0.2) on Windows 10 Pro.
I'm able to install _other_ add-ons from AMO, and apparently other people have been able to install this same file/upload as well, so this looks to be something specifically wrong with a combination of this add-on and something else, maybe some a:config setting?

**Comment by harl** [comment]
I had already tried installing this add-on (version 7.3.0) manually or as a temporary add-on, which didn't work.

However, from the list of older versions, Firefox lets me install versions 5.0.1 through 6.1.1, but none of the older or newer ones, meaning I can install 5.0.1, 6.0.0, 6.0.1, 6.1.0 or 6.1.1.  So something appears to be different with these from the others.

Even with version 6.1.1 installed now, it doesn't let me install version 7.3.0 and checking for add-on updates has no effect on it.

**Comment by kendallcorner** [comment]
Hey there, did you try this:https://github.com/mozilla/multi-account-containers/issues/1450#issuecomment-681031268

**Comment by harl** [comment]
Thank you, @kendallcorner (and @wodnikk).
Setting "extensions.allowPrivateBrowsingByDefault" to "false" did indeed solve this issue for me.
The add-on got even updated automatically without further ado when checking for updates.
