### ISSUE TITLE
Sites with Long Site Names Cannot be Removed from Assigned Container

### ISSUE THREAD

**Issue by PorcelainMouse** [mozilla/multi-account-containers#2077]
### Actual behavior
The trash icon is not accessible for some sites with long names in the list of assigned sites in  "manage containers" > "manage sites" .  See attached screenshot.

![screenshot_crop](https://user-images.githubusercontent.com/159714/124977931-fb352100-dfe5-11eb-8e39-e93ed667df90.png)

### Expected behavior
should be able to delete any site from list, regardless of representation in the list.

### Steps to reproduce
1. Container button
2. Manage Containers
3. Manage Sites
4. See trash icon shows up only at right end of site entry, but width of pop-up window is limited.  Also, you cannot scroll to right while keeping the mouse over any entry, so, the functionality of the menu is broken by design.

**Comment by dannycolin** [comment]
Fixed in #2422
