### ISSUE TITLE
Extension doesn't capture key events after Ctrl-.

### ISSUE THREAD

**Issue by erjiang** [mozilla/multi-account-containers#2080]
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Ubuntu 18.04 (x64)
- Firefox Version: 90.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: 

### Actual behavior

When I hit Ctrl-. to open the container tabs menu, and then 1-9 to select a container, about 60% of the time it does not get the input. (Menu stays open, nothing happens.)

### Expected behavior

On previous versions of Firefox, it reliably got the number input when the menu was open (unless the page was capturing all keys).

### Steps to reproduce
1. Ctrl-.
2. Hit a number key on the keyboard
3. Extension does nothing, and user needs to retry several times to get it to do something.

### Notes

This seemed to get worse recently after upgrading to 90.0 (64-bit) Firefox for Ubuntu.

**Comment by dannycolin** [comment]
Does it still happen in the latest version (8.0.7)?
