### ISSUE TITLE
Feature Request -- New Tab shortcut (Ctrl+T) -- using same container as current tab

### ISSUE THREAD

**Issue by VasuInukollu** [mozilla/multi-account-containers#2083]
### Actual behavior

The keyboard shortcut for new tab tab opens without a container.

### Expected behavior

Open new tab with the same container as the current active tab.

### Notes

Multi account container is the No.1 reason I like firefox. I juggle between 8 containers and almost 10 tabs constantly. It would be great to have a way to save a few clicks and dependency on mouse to open a container tab.

**Comment by achernyakevich-sc** [comment]
I' afraid it is not possible to implement this way. But there is already shortcuts that could simplify your life:

* `Ctrl+Shift+1` - open new tab of the container number 1
* `Ctrl+Shift+2` - open new tab of the container number 2
* ...

If it helps then probably there is a reason to close this issue. :)

**Comment by achernyakevich-sc** [comment]
Meantime, your case in active discussion in #462. Probably you will be interested for it. Maybe even will close this one as duplicate. :)
