### ISSUE TITLE
Feature request. "You asked Firefox to always open [Container name] for this site". And I meant it!

### ISSUE THREAD

**Issue by Yuriy-II** [mozilla/multi-account-containers#2084]
When Website is being assigned to a Container, user Selects container from a container list titled "Always open this site in..."
It is obvious that user wants to ALWAYS open said site in a certain container.

### Actual behavior
However, when next time visiting the same site, Firefox displays a message:

_Open this site in your assigned container?
You asked Firefox to always open [Container name] for this site:
Would you still like to open in this current container?
Remember my decision for this site_ 

**It is extremely annoying.**

### Expected behavior
Said page should never be displayed once user has assigned a website to ALWAYS open in specific container.

**Comment by nabeelr** [comment]
I disagree, there is a checkbox to make it stop asking you. Check the checkbox and it'll stop asking you. There is a difference between the default action and an unprompted action.

Asking to change the default action shouldn't change the unprompted action.

**Comment by dannycolin** [comment]
Duplicate of #796

**Comment by phansel** [comment]
Checking the checkbox does not work.
