### ISSUE TITLE
Bug when navigating in popup via keyboard

### ISSUE THREAD

**Issue by JVariance** [mozilla/multi-account-containers#2085]
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Windows 10 - Version 21H1 (Build 19043.1110)
- Firefox Version: 90.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status: no influence

### Actual behavior

I open the popup via 'ctrl+period'. I navigate down to one of the containers. I press 'right' key to access the container's view. Let's say I now press the 'right' key five times, I have to press the 'left' key five times again to navigate back to the main view.

### Expected behavior

I just have to press the 'left' key once to navigate back to the main view.

**Comment by dannycolin** [comment]
I can't reproduce in the latest version (8.0.7). Could you confirm that it's also the case for you? Thanks!

**Comment by JVariance** [comment]
It's fixed.
