### ISSUE TITLE
Containers lost for no reason. Sync problem?

### ISSUE THREAD

**Issue by basinilya** [mozilla/multi-account-containers#2091]
7 days have passed since the last time I used Containers. I didn't restart Firefox since then. Today I noticed that "Open in new Container Tab" context menu item is missing and clicking the containers button on the toolbar does nothing. I restarted Firefox and now the addon settings are set to default: the containers I created previously are missing, but the "Work", "Banking", etc. are there.

The important information that is lost is the list of sites to open with specific containers. Where is it stored? I believe it's not `containers.json`

Previously, I had Firefox on two workstations with the same sync account. On the second workstation Firefox is still running and there I have exactly same symptoms: the menu item is missing and the toolbar button does not work.

The addon and the browser are up to date. I haven't updated Firefox for two weeks and I haven't updated the addon since January

The only thing that comes to my mind is that yesterday I logged on to my Firefox account from the third workstation. I didn't have the addon there. Could it be the reason? Please make sure that syncing a fresh Firefox profile does not overwrite the containers settings.

On the first workstation `containers.json` was modified yesterday evening (the time of the 1st sync since logging in from the 3rd workstation). On the second workstation `containers.json` is 2 years old.

**Comment by seanmceligot** [comment]
Same problem. I turned on sync for a second and it immediately deleted my containers and I lost all my logins. Sync should probably be disabled until it's fixed.

**Comment by akasaka99** [comment]
Furthermore they are no way of backing up/exporting containers which everyone was asking FOR YEARS ! And the admin happily censor any question about it. FF now at 3% global usage, next year they will be at 2% totally becoming irrelevant with such type of appalling customer support. Better to a fork like Librewolf, at least they won't track you

**Comment by kendallcorner** [comment]
The missing context menu would be a platform (firefox, not the addon) cause, and so it sounds like your `privacy.userContext.enabled` pref got toggled. This happens when the only addon that uses contextual identities (containers) is removed. There is a [platform bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1549204) about this. When that happens Firefox deletes all your containers and container cookies, so it sounds like that's somehow what happened (maybe logging into FF from the 3rd workstation w/o MAC deleted the addon, as you suggested). I would think once you reinstalled Multi-account containers and turned sync back on, you would get your containers back--especially if your other desktop is syncing properly and has the correct containers setup. You can [backup your profile](https://support.mozilla.org/en-US/kb/back-and-restore-information-firefox-profiles) first if you want to try that.

**Comment by basinilya** [comment]
I installed the addon, enabled sync on all devices and synced the whole ring a couple of times. Now I have my site associations back on one of the devices, but neither containers nor site associations are synchronized with the other two.

**Comment by akasaka99** [comment]
> The missing context menu would be a platform (firefox, not the addon) cause, and so it sounds like your `privacy.userContext.enabled` pref got toggled. This happens when the only addon that uses contextual identities (containers) is removed. There is a [platform bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1549204) about this. When that happens Firefox deletes all your containers and container cookies, so it sounds like that's somehow what happened (maybe logging into FF from the 3rd workstation w/o MAC deleted the addon, as you suggested). I would think once you reinstalled Multi-account containers and turned sync back on, you would get your containers back--especially if your other desktop is syncing properly and has the correct containers setup. You can [backup your profile](https://support.mozilla.org/en-US/kb/back-and-restore-information-firefox-profiles) first if you want to try that.

Do you if it's possible to backup the containers and associated urls instead the entire profile?

**Comment by CyrilFind** [comment]
I've had this problem many times: 
- I feel like it happens after my mac has been in sleep mode but I'm not sure
- clicking "Multi-account containers" does not show the panel but just a white line of 1 or 2px height and the contained tabs are closed
- if i restart Firefox and the  panel reappears but with the default containers
- now the workaround i have found is going into the add-on preferences and toggling the sync option twice (but it doesn't remove the default containers)

**Comment by dannycolin** [comment]
Definitely sounds like #1236 that is triggered by [bug 1549204](https://bugzilla.mozilla.org/show_bug.cgi?id=1549204) upstream. Closing as duplicate.
