### ISSUE TITLE
Can't "forget" an always-open-in-container setting

### ISSUE THREAD

**Issue by runelynx** [mozilla/multi-account-containers#2104]
I mistakenly set a google.com website to always open in one container and now the add-on incessantly nags me every time I go to any google site whether I want to open it in the old or the new container. Half the time the Google auth then fails because of the interruption. 

How can I remove a site from the "always open in" list? I can't work like this :(

**Comment by ameaninglessname** [comment]
![image](https://user-images.githubusercontent.com/20263103/129433608-1d411fd5-5f77-4918-9204-8e26e6a303e9.png)
Click this to uncheck it.

**Comment by runelynx** [comment]
Thanks!!

**Comment by achernyakevich-sc** [comment]
@runelynx Please, could you close this issue as it looks resolved. :)
