### ISSUE TITLE
Suggestion : possibility to link a "bookmark toolbar" to each container-type

### ISSUE THREAD

**Issue by Madydri** [mozilla/multi-account-containers#2112]
When opening a container type, it would be fine if the "bookmark toolbar" could show the bookmarks typically opened in this container.
For example 
In "Bank" there could be the bookmarks for my financial websites,
in "Shopping" the bookmarks of my most used shops
in "Suppliers" the bookmarks to my suppliers.
This could maybe be done with a setting of the container to chose a folder of the bookmarks library

**Comment by dannycolin** [comment]
Moved to https://connect.mozilla.org/t5/ideas/container-preference-in-bookmarks/idi-p/3857
