### ISSUE TITLE
"Always open this site in..." option stopped working in Nightly

### ISSUE THREAD

**Issue by bbhtt** [mozilla/multi-account-containers#2115]
- Multi-Account Containers Version: 7.4.0
- Operating System: Arch Linux
- Firefox Version: 93.0a1 (2021-09-01) buildid: 20210901091701
- Other installed Add-ons: (tested in a blank profile)

### Actual behavior

Nothing happens

### Expected behavior

Assign the site to that container (confirmation page...) and reload it in the container.

### Steps to reproduce

1. Open a website
2. Click extension -> "Always open this site in.."

### Notes

Error in extension and browser console:
```
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved                                        
utils.js:117                                                                                                                                          
    alwaysOpenInContainer moz-extension://cb213c14-b1c7-4141-9b64-f01f90fb0f4c/js/utils.js:117 
```
(Possibly something happened between builds from 2021-08-26 to 2021-09-01)

**Comment by Fanolian** [comment]
Last good Nightly: 2021-08-31
First bad Nightly: 2021-09-01
pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=e8a630d41a7755dbc6c19093f96a89d8fd351b10&tochange=18d7ddf67682e3eb75376f56e4f014c81d2596b3
Changelist: https://mrotherguy.github.io/fx-nightly-changelog/?date=2021-09-01

Bisecting autoland builds:
pushlog: https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=ab5b37f83023f926201c2b226e35076910ce6fd4&tochange=2dc4f1baccc82806eb203617b0184fa634fea3e5

This is regressed by [Bug 1708243 - Stop depending on framescripts with `ExtensionGlobal`](https://bugzilla.mozilla.org/show_bug.cgi?id=1708243).

**Comment by Fanolian** [comment]
I went ahead and filed [Bug 1729395 - Firefox Multi-Account Containers's "Always Open This Site in" does not work after bug 1708243 part 2](https://bugzilla.mozilla.org/show_bug.cgi?id=1729395) since it is affecting a popular "built by Firefox" extension.

**Comment by Rob--W** [comment]
utils.js sends a message: https://github.com/mozilla/multi-account-containers/blob/4b56a2f0bb91cd9a12b95121fcff0c8e96ff66bd/src/js/utils.js#L113-L117

`alwaysOpenInContainer` has two callers, both of which close the page:
- https://github.com/mozilla/multi-account-containers/blob/4b56a2f0bb91cd9a12b95121fcff0c8e96ff66bd/src/js/pageAction.js#L24-L25
- https://github.com/mozilla/multi-account-containers/blob/081ea0bedb7124a695dcfe690b3ec0fd237e5ede/src/js/popup.js#L1225-L1226

**Comment by mdmcnamara** [comment]
Thanks, team!!  Sincerely appreciate your attention on this one.

**Comment by niikoo** [comment]
+1 
Also applies to Firefox Nightly for Android

**Comment by Rob--W** [comment]
> +1 
> Also applies to Firefox Nightly for Android

Huh are you using container tabs on Firefox Nightly (Fenix)?
The implementation of containers is incorrect and unsupported; using it will result in the loss of data in the future when the bug is fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1643740

**Comment by niikoo** [comment]
> 
> 
> > +1
> > Also applies to Firefox Nightly for Android
> 
> Huh are you using container tabs on Firefox Nightly (Fenix)?
> The implementation of containers is incorrect and unsupported; using it will result in the loss of data in the future when the bug is fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1643740

Thanks for the information.

**Comment by zombie** [comment]
The original issue here is that there is no `await` for the `Utils.alwaysOpenInContainer() method at these two call sites:
https://github.com/mozilla/multi-account-containers/blob/4b56a2f0bb/src/js/pageAction.js#L24-L25
https://github.com/mozilla/multi-account-containers/blob/081ea0bed/src/js/popup.js#L1225-L1226

This means that `sendMessage()` is called _after_ the popup is already closed, which was never guaranteed to work.  While I landed a fix in Firefox to make it work again, I still recommend fixing the extension to not depend on this behavior as it may stop working in the future.

**Comment by dannycolin** [comment]
Closing as [bug 1729395](https://bugzilla.mozilla.org/show_bug.cgi?id=1729395) has been fixed upstream.
