### ISSUE TITLE
Always open this site in... + different logins + limit to designated sites

### ISSUE THREAD

**Issue by jlmxyz** [mozilla/multi-account-containers#2122]
- Multi-Account Containers Version: 7.4.0
-  gentoo linux
- 91.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:
```
Dictionnaire français	dictionary	7.0b	true	fr-dicollecte@dictionaries.addons.mozilla.org
Amazon.co.uk	extension	1.9	true	amazon@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Ecosia – Le moteur de recherche qui plante des arbres	extension	4.0.4	true	{d04b0b40-3dab-4f0b-97a6-04ec3eddbfb0}
Firefox Multi-Account Containers	extension	7.4.0	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
Mailvelope	extension	4.4.1	true	jid1-AQqSMBYb0a8ADg@jetpack
Qwant	extension	1.1	true	qwant@search.mozilla.org
Save Page WE	extension	26.1	true	savepage-we@DW-dev
Tab Session Manager	extension	6.10.0	true	Tab-Session-Manager@sienori
Video DownloadHelper	extension	7.6.0	true	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
Wikipédia (fr)	extension	1.1	true	wikipedia@search.mozilla.org
Français Language Pack	locale	91.0buildid20210823123856	true	langpack-fr@firefox.mozilla.org
```
I want to have the links opened from gmail not opened into the google container so that the opened site can't use the google cookies....
but at the same time I have multiple google accounts, so I would like to have theses accounts "separated" from each others.... 
so in fact I need google(context1) opened into container1  and google(context2) opened into container2, and that if I open a link from one google workspace (drive, gmail, etc...) that this link is opened into default container....
is it possible ?

**Comment by dannycolin** [comment]
Currently, it isn't possible to allow the same domain name in more than one container if "Limit to designated sites" is enabled. There are a few older issues asking for the same feature of allowing a domain to be assigned to more than one container (e.g. #1887). I'll close this one to avoid duplicates.
