### ISSUE TITLE
Opening a local PDF with file:// in a new Container tab leads to a blank screen

### ISSUE THREAD

**Issue by tquin** [mozilla/multi-account-containers#2127]
- Multi-Account Containers Version: 7.4.0
- Operating System + Version: Windows 10 21H1 (also observed on Arch Linux)
- Firefox Version: 92.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: N/A

### Actual behavior

Opening the file in a new Container tab leads to a blank page, requiring a page refresh to actually display the content.

### Expected behavior

Re-opening the local file in a new Container tab should render the file contents

### Steps to reproduce
1. Open a local pdf (file://) in a normal tab
2. Right click the tab, and choose 'open in new Container tab'
3. This should re-render the content in the selected Container, but instead opens a container tab with a blank UI

### Notes

This _seems_ to only affect PDFs, but I'm not 100% sure on that. In my testing, multiple PDFs suffered from this bug, while mp4s and pngs did not.

**Comment by dannycolin** [comment]
This is a limitation of the WebExtension API. Here's an excerpt of the documentation:

> For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail:
> * file: URLs (i.e., files on the filesystem. However, to use a file packaged inside the extension, see below)

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1744532

I'm closing this issue since there's nothing on our side that we can do.
