### ISSUE TITLE
What plans for Firefox Android

### ISSUE THREAD

**Issue by nu111** [mozilla/multi-account-containers#2128]
Hi, I love the addon, I would like to have it on Firefox Android too. What are the plans to add support for Firefox Android?

**Comment by kelimuttu** [comment]
We received a similar request from Twitter too recently. 

> Would like containers add-on to make it to Android at some point if possible. - [coelmay]((https://twitter.com/coelmay/status/1460575714218942473))

**Comment by vintagemind** [comment]
> We received a similar request from Twitter too recently.
> 
> > Would like containers add-on to make it to Android at some point if possible. - coelmay

Are they referring this add-on but wanting it to be on Android? 

https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

Thanks!

**Comment by coelmay** [comment]
> We received a similar request from Twitter too recently.
> 
> > Would like containers add-on to make it to Android at some point if possible. - coelmay

Yep, that was me! 😄

**Comment by coelmay** [comment]
> > We received a similar request from Twitter too recently.
> > > Would like containers add-on to make it to Android at some point if possible. - coelmay
> 
> Are they referring to this add-on but wanting it to be on Android?
> 
> https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
> 
> Thanks!

Yes, that what I was referring too. Don't know the ins-and-outs of it, if it is within the realm of possibility or not.

**Comment by dannycolin** [comment]
Sadly, there's nothing we can do until the Container API is implemented in Fenix. See [#10581 on Fenix repository](https://github.com/mozilla-mobile/fenix/issues/10581).
