### ISSUE TITLE
Feature: Set a custom container as default

### ISSUE THREAD

**Issue by TyMick** [mozilla/multi-account-containers#2131]
I primarily use this add-on to separate my personal and work accounts across the web (one "Personal" container, one "Work" container, one "Self-employment" container, several containers for different test accounts for my software development work, etc). Because of that, the container I want to treat as my "default" changes from time to time. When I'm working, I want all my tabs to open in "Work" by default, and when I'm not, I want all my tabs to open in "Personal" by default. I can't create URL rules for all of these sites, because I use a lot of the same sites in both profiles, with separate work and personal accounts. And the keyboard shortcuts to open a new tab in a given container are useful, but they aren't enough, because I also want links I click in external apps, like my email, to open in my "Work" container when I'm working or my "Personal" container when I'm not working.

I would love it if this add-on had a setting that would let me designate which container I want all tabs to open in by default. Then I could just set that setting to "Work" at the beginning of my workday and "Personal" at the end of it, and all my externally-clicked links would open in the container I want them to (plus I'd get to go back to using ⌘T to open new tabs without having to stop and remember which new-tab shortcut I'm supposed to be using for the context I'm in).

**Comment by achernyakevich-sc** [comment]
Probably you could solve your case by using Multi-Account Containers (MCA) with Simple Tab Groups (STG). For STG you could configure in setting that for the dedicated tab group all tabs should be open in dedicated container. And have two groups of tabs - `Work` and `Home`. So when you do something for home you will have activated `Home` tab group and all new tabs will be open in the corresponding `Personal` container. When you will have activated  `Work` tab group then new tabs will be automatically open in the corresponding `Work` container.

As these are two different add-ons names of groups and container don't need to be identical. You just need to properly configure STG to use some container as default for everything that you open in the group.

**Comment by TyMick** [comment]
That does exactly what I need; thanks, @achernyakevich-sc! And Simple Tab Groups does it so well that I'm going to consider this feature to be out of scope for Multi-Account Containers and close this issue. 😊
