### ISSUE TITLE
Clicking the Multi-Account Containers button no longer displays drop-down menu of my containers (or the options to add/edit)

### ISSUE THREAD

**Issue by glitter-queen** [mozilla/multi-account-containers#2144]
- Multi-Account Containers Version: 7.4.0
- Operating System + Version: macOS Catalina version 10.15.7
- Firefox Version: 92.0.1 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Amazon Assistant	extension	10.2104.13.12029	true	abb@amazon.com
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Emoji Cheatsheet for GitHub, Basecamp etc.	extension	2.0.1	true	jid1-Xo5SuA6qc1DFpw@jetpack
FF Facebook Pixel Helper	extension	1.0.6	true	{f78d2e9e-892f-43bf-8bd2-a79a85203a0b}
Firefox Multi-Account Containers	extension	7.4.0	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
Grammarly for Firefox	extension	8.885.0	true	87677a2c52b84ad3a151a4a72f5bd3c4@jetpack
Hunter: Find email addresses in seconds	extension	1.18.7	true	firefox@hunter.io
LastPass: Free Password Manager	extension	4.81.0.3	true	support@lastpass.com
Toggl Track: Productivity & Time Tracker	extension	1.70.7	true	toggl-button@toggl.com
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
Easy Youtube Video Downloader Express	extension	17.3	false	{b9acf540-acba-11e1-8ccb-001fd0e08bd4}
Evernote Web Clipper	extension	6.13.3	false	{E0B8C461-F8FB-49b4-8373-FE32E9252800}
Panorama Tab Groups	extension	0.8.12	false	panorama-tab-groups@example.com
Social Video Downloader	extension	2.3.18	false	{00e68183-fc7d-4a91-b5cc-f7f8272386db}
Tree Style Tab	extension	3.8.12	false	treestyletab@piro.sakura.ne.jp
Workspaces for Firefox	extension	1.1.0	false	{f8829f14-24b7-4e17-8bde-250217de2d71}

### Actual behavior
When I click the Multi-Account Containers button, it does not display my list of containers (or options to add/manage), but instead displays a small line that is the width of what the menu once was. (I clicked that button hundreds of times a day the past several years, so this is a huge issue for me!) 

### Expected behavior
When I used to click the Multi-Account Containers button, it would display the menu so that I could create tabs in my various containers. 

### Steps to reproduce
1. Click the Multi-Account Containers button
<img width="401" alt="Screen Shot 2021-10-03 at 7 21 46 AM" src="https://user-images.githubusercontent.com/91831252/135753553-62a9e301-e1e8-4518-8fc7-c2eacf99a1d8.png">
<img width="470" alt="Screen Shot 2021-10-03 at 7 21 53 AM" src="https://user-images.githubusercontent.com/91831252/135753555-1015ea2c-34cc-4e2e-bd20-05fcabbd3056.png">

**Comment by dannycolin** [comment]
This was an issue with Firefox itself and should have been resolved by now. If you still experience it, please file a bug report directly on bugzilla.mozilla.org.
