### ISSUE TITLE
Reset Always Open In to Default Container

### ISSUE THREAD

**Issue by kalenmike** [mozilla/multi-account-containers#2145]
### Actual behavior
Setting a site as ' Always open this site in...' launches the 'Open this site in your assigned container?' If I click 'Remember my decision for this site' the site will always open in the assigned container. I can change the assigned container but I cannot change it back to default. So the 'Open this site in your assigned container?'  will always show or I have to open the site in one of my labelled containers.

### Expected behavior
The user can reset the site to open in the default container without the prompt 'Open this site in your assigned container?'

### Steps to reproduce
1. Assign a site to a container
2. Navigate to the site and select 'Remember my decision for this site'
3. Open the site in the default container

### Notes
None

**Comment by achernyakevich-sc** [comment]
As I understand you have an issue that was discussed in the #2105. At the end of that issue discussion is quite detailed overview how to make some URL unassigned to earlier assigned container.

If it is and will help you to achieve you could you could make this issue as duplicate of #2105 and close it.

**Comment by kalenmike** [comment]
Duplicate of #2105 

> * Go to the website in question
> 
> * In the URL bar, there should be the "Multi-Account Containers" icon to the right of the URL (left of the star for bookmarks)
> 
> * Right-click on the "Multi-Account Containers" icon
> 
> * Un-check "Always Open in This Container"
