### ISSUE TITLE
Issues for this github repo should allow choosing bug or enhancement to allow quicker response to bug reports

### ISSUE THREAD

**Issue by julie777** [mozilla/multi-account-containers#2153]
Enhancement

Allow creating a new issue to select bug or enhancement. That would allow you to more efficiently and more quickly respond to bugs. It would also allow users to search existing issues more efficiently to make sure they aren't adding duplicates

**Comment by dannycolin** [comment]
Closing since we're now redirecting users to connect.mozilla.org for feature request related to Containers.
