### ISSUE TITLE
"Always open this site in" and "reopen this site in" features not working in esr-78

### ISSUE THREAD

**Issue by PeacefulPotato** [mozilla/multi-account-containers#2160]
- Multi-Account Containers Version: 7.4.0
- Operating System + Version: MX Linux 19.0 + Devuan Beowulf 3.1
- Firefox Version: 78.14.0esr
- Other installed Add-ons + Version + Enabled/Disabled-Status: See below

**Enabled**
Amazon.com 1.1 (amazondotcom@search.mozilla.org)
Bing 1.1.1 (bing@search.mozilla.org)
CanvasBlocker 1.6.1 (CanvasBlocker@kkapsner.de)
Cloud Firewall 3.0 (cloudfirewall@nikisoft.one)
CSS Exfil Protection 1.1.0 {7fc8ef53-24ec-4205-87a4-1e745953bb0d}
DuckDuckGo 1.0 (ddg@search.mozilla.org)
eBay 1.1 (ebay@search.mozilla.org)
Google 1.0 (google@search.mozilla.org)
LocalCDN 2.6.14 {b86e4813-687a-43e6-ab65-0bde4ab75758}
nuTensor 1.5.0.1 (1nuTensor@geekprojects.com)
Redirector 3.5.3 (redirector@einaregilsson.com)
Smart Referer 0.2.15 (smart-referer@meh.paranoid.pk)
uBlock Origin 1.38.6 (uBlock0@raymondhill.net)
uBO-Scope 0.1.12 (uBO-Scope@raymondhill.net)
Want My RSS 0.19 {4d567245-e70d-466a-bb2f-390fc7fb25c2}
Wikipedia (en) 1.0 (wikipedia@search.mozilla.org)
**Disabled**
None

### Actual behavior
Trying to use the "always open this site in" or "reopen this site in" features results in nothing happening.

### Expected behavior
Trying to use said features results in those features working (reopening the site in chosen container or always opening the site in chosen container)

### Steps to reproduce
1. Open Firefox esr-78
2. Install Firefox Multi Account Containers from AMO
3. Go to https://example.com
4. Click "Reopen this site in" and choose a container
5. Click "Always open this site in" and choose a container, then close the tab and try navigating back to "https://example.com"

### Notes
I installed MX Linux 19.0 but am using Devuan Beowulf 3.1 repos.

**Comment by dannycolin** [comment]
Closing since ESR78 is end of life.
