### ISSUE TITLE
[l10n] String openInContainer is reused for no container

### ISSUE THREAD

**Issue by flodolo** [mozilla/multi-account-containers#2168]
cc @lesleyjanenorton @bakulf 

```
  "openInContainer": {
    "message": "Open in $containerName$ Container",
    "placeholders": {
      "containerName": {
        "content": "$1"
      }
    }
  },
```

This string is reused when is empty. We need a different string for that.

<img width="815" alt="Schermata 2021-10-26 alle 14 21 35" src="https://user-images.githubusercontent.com/3644868/138877738-6c0178d7-387f-4f90-beea-2f1123678611.png">

**Comment by lesleyjanenorton** [comment]
Thank you for flagging this @flodolo !
