### ISSUE TITLE
How to reset / undo Gmail links always opening in the same container?

### ISSUE THREAD

**Issue by berriganator** [mozilla/multi-account-containers#2173]
- Multi-Account Containers Version: 7.4.0
- Operating System + Version: OS X 10.14.6 (18G9323)
- Firefox Version: 93.0 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
Dictionnaire français	dictionary	7.0b	true	fr-dicollecte@dictionaries.addons.mozilla.org
German Dictionary, classical spelling standards	dictionary	4.0.1.1webext	true	alterechtschreibung@googlemail.com
Adblock Plus - free ad blocker	extension	3.11.2	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Adobe Acrobat	extension	18.0.10	true	web2pdfextension.17@acrobat.adobe.com
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Expire History By Days	extension	1.3.1	true	expire-history-by-days@bonardo.net
Facebook Container	extension	2.3.1	true	@contain-facebook
Firefox Color	extension	2.1.7	true	FirefoxColor@mozilla.com
Firefox Multi-Account Containers	extension	7.4.0	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
LEO Dictionaries	extension	3.4.1	true	contextMenuExtension@leo.org
Notion Web Clipper	extension	0.3.2	true	{4b547b2c-e114-4344-9b70-09b2fe0785f3}
OneTab	extension	1.54	true	extension@one-tab.com
Read Aloud: A Text to Speech Voice Reader	extension	1.48.0	true	{ddc62400-f22d-4dd3-8b4a-05837de53c2e}
SCDL SoundCloud Downloader	extension	5.4	true	scdl@mrvv.net
To Google Translate	extension	4.2.0	true	jid1-93WyvpgvxzGATw@jetpack
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
YouTube Video and Audio Downloader (Dev Edt.)	extension	1.1.6	true	{f73df109-8fb4-453e-8373-f59e61ca4da3}
Zotero Connector	extension	5.0.91	true	zotero@chnm.gmu.edu
Español (México) Language Pack	locale	93.0buildid20210927210923	true	langpack-es-MX@firefox.mozilla.org
Places Maintenance	extension	2.0.3	false	places-maintenance@bonardo.net

### Actual behavior
I am not sure how it happened, but when I click on a link in my Gmail, it defaults to opening in the Shopping container. I cannot find a way to reset this behavior. I can only right-click on a link and select which container in which to open a new tab, but this does not change the default behavior thereafter.

Thanks for your help!

### Expected behavior
I would like to see in the Firefox preferences tab a way to reset preferences or "always open in" link behaviors for a specific container. 

### Notes
The only way I was able to resolve this was to uninstall / reinstall the add-on.

**Comment by OrangeTux** [comment]
"Manage Containers" is only available when using clicking on the "Multi-Account Containers"-icon in the toolbar. The menu item is not available when using the icon in the URL bar. See https://github.com/mozilla/multi-account-containers/issues/2526#issuecomment-1694348228
