### ISSUE TITLE
Impermeability of containers

### ISSUE THREAD

**Issue by Tianchrisse** [mozilla/multi-account-containers#2181]
Hello All, 

- Multi-Account Containers Version: 7.4.0
- Operating System + Version: 
- Distributor ID: Ubuntu 20.04.3 LTS
- Firefox Version: 93.0 (64 bits)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Adblock Plus - bloqueur de publicités gratuit | extension | 03/11/02 | true
Amazon.co.uk | extension | 1.9 | true
Bing | extension | 1.3 | true
Clear Cache | extension | 3.2 | true
DuckDuckGo | extension | 1.1 | true
eBay | extension | 1.3 | true
Firefox Multi-Account Containers | extension | 07/04/00 | true
Ghostery – Bloqueur de publicité protégeant la vie privée | extension | 08/05/07 | true
Google | extension | 1.1 | true
Notes by Firefox | extension | 04/03/07 | true
Privacy Badger | extension | 2021.8.17 | true
QookieFix | extension | 0.1.26 | true
Qwant | extension | 1.1 | true
Test Pilot | extension | 3.0.6vffecb95 | true
Video DownloadHelper | extension | 07/06/00 | true
Wikipédia (fr) | extension | 1.1 | true
English (CA) Language Pack | locale | 93.0buildid20210927210923 | true
English (GB) Language Pack | locale | 93.0buildid20210927210923 | true
Français Language Pack | locale | 93.0buildid20210927210923 | true
Brief | extension | 02/06/00 | false
Download Facebook Video or Photo | extension | 1.0.3 | false
Easy Youtube Video Downloader Express | extension | 17.4 | false
PDF to JPG - Convert and Merge | extension | 0.1.1 | false

### Actual behavior
Facebook is opened in a dedicated container
I have opened another website (https://onyxcookware.fr/) in another container
Facebook shows me an advertisement of the website which is opened in another container.  

### Expected behavior
I assume Facebook should not be able to access the website opened in another container? 

### Steps to reproduce
1. Open Facebook in one container
2. Open Facebook in another container
3. Check the advertisement on the top right of the Facebook website.

### Notes
![Capture du 2021-10-28 19-12-43](https://user-images.githubusercontent.com/93343000/139308184-e598825e-5c45-4d99-8750-2e0e1da1e62f.png)
![Capture du 2021-10-28 19-13-10](https://user-images.githubusercontent.com/93343000/139308229-32162810-6ec4-4836-b5fb-e759051d378f.png)

**Comment by dannycolin** [comment]
Containers only prevent tracking from cookies. However, Facebook could have used a different method of tracking (e.g. fingerprinting). 

Further, it's impossible to know with the information given if there's a bug that could result in cookies leaking to another container. 

Finally, if you can find any indication of a leakage, this needs to be reported on bugzilla.mozilla.org since the container feature is builtin the browser itself. I'm closing this for now since there's nothing we can do on our side (the addon).
