### ISSUE TITLE
Messy containers order after fresh install firefox

### ISSUE THREAD

**Issue by aficks** [mozilla/multi-account-containers#2185]
Hello all, I created a lot of containers and then sorted them according to the profiles I use most and synced with my firefox account, but after I did a fresh install of firefox and tried to open the site via right click "open bookmarks in container tab" the order of my containers is messy, not in order I've set it up..can you guys fix it because it's a bit annoying to have to manually sort the containers ^^v

**Comment by kelimuttu** [comment]
We hear another request for this feature from Twitter: https://twitter.com/tombalfoort/status/1466889827165646854

**Comment by dannycolin** [comment]
Sounds like a similar sync issue than #1625. Closing as duplicate.
