### ISSUE TITLE
Firefox containers discussion, best practices and feature request for Security and Privacy

### ISSUE THREAD

**Issue by julie777** [mozilla/multi-account-containers#2186]
First, I wish discussions were enabled for this repo. That would allow discussing proposals before submitting them as enhancement requests.

There seems to be some confusion about the reason for multi-account containers in all that others have written about them. This is exacerbated by the confusing and disjointed UI and configuration for them. Because of that I am going to make a suggestion that I believe is in the interest of all Firefox users. I hope that I have though this through enough to make sense.

Note: when I mention origin in mean it per [https://developer.mozilla.org/en-US/docs/Glossary/Origin](origin).

#### Problem
1. cookies can be accessed by any web page from any origin. This allows collection and aggregation of user information without consent.
2. The EU made cookie acceptance a required, and an annoying question on every web page. This is extremely annoying.
3. Google and others are trying to find a replacement for cookies but it seems like the replacement will have the same problems.
4. The current multi-account containers uses a banking container as an example. Opening all banking sites in the same container is just reducing the problem of *unauthorized information sharing* to a smaller set.

#### Proposed solution
- Default to opening each origin in a temporary container and when the tab is closed delete the container. This prevents unauthorized cookie and information sharing.
- Automatically accept cookies to prevent the annoying question.
- Don't suggest using containers for convenient grouping of tabs/sites. Unauthorized information can still happen.
- suggest using Simple Tab Groups or another extension to group tabs for convenience.

#### Problem
1. login status is usually stored in cookies.
2. I recently had an order placed to my amazon account, which I had kept logged in, from another website when I clicked a link thinking that I was going to read about a product.
3. This is so convenient, especially for sites like StackOverflow, Amazon, etc. that users are going to do it regardless of the danger.

#### Proposed solution
Allow user to select a tab and "make container permanent". This would assign a name to the container and open that origin in the same permanent container every time. Users must be allowed to see and edit permanent containers.

#### Problem
Sharing browser data across origins is required to allow one login session to allow access to all services for that account. For example mail.google.com is a different origin than docs.google.com, but one login is used to allow access to all the google features that I use.

### Solution
Allow editing permanent containers to add multiple origins using the same login credentials.
In addition, Firefox saving and providing passwords for websites could store the information in the container data, isolating it from any access outside the container.

#### Problem
Users often have multiple gmail accounts, thus multiple google accounts. They often have a personal account and a work account for some service (mentioned in the MAC documentation). However, although MAC is a purported solution to this issue I can't find any way to actually achieve the goal of having a Firefox container associated with a specific google account.

#### Solution
I didn't actually have a solution for this when I started writing, but it came to me in the previous problem. 

- Associate saved login credentials, for an origin or group of origins that use the same account, with the container. 
- allow cloning a container. Cloning doesn't copy credentials. In the new container login using different credentials.

### Conclusion
I realize that this is a big change from how the extension currently works, at least in some ways. Because containers are part of Firefox and the extension is created by Mozilla Firefox, I am hoping to spark some discussion both about the extension and about possible changes to the way Firefox works by default.

**Comment by dannycolin** [comment]
> First, I wish discussions were enabled for this repo. That would allow discussing proposals before submitting them as enhancement requests.

We try to keep this repository centered on bug reports and feature requests where we limit the discussion on the technical aspect of it before working on the implementation.

For more general proposals like yours, the new Mozilla platform https://connect.mozilla.org sounds like the best place to start a discussion on these topics. If a discusstion/proposal gets enough traction, it will be relayed to the appropriate team. 

I will strongly recommend you to submit your ideas there :).

**Comment by dannycolin** [comment]
Oh I forgot! We also have a room on our matrix server at https://chat.mozilla.org/#/room/#containers:mozilla.org.

I'm closing this issue for now but feel free to ask questions if you need more clarification or help with Connect or to join our Matrix server.

**Comment by danepowell** [comment]
This is an incredibly valuable discussion to continue, can you please provide a link if it moved somewhere else?

**Comment by dannycolin** [comment]
@danepowell For broader discussion about Containers, you can [open a discussion on Mozilla Connect](https://connect.mozilla.org/t5/discussions/bd-p/discussions). 

If you have a more specific idea/feature, you can [submit an idea](https://connect.mozilla.org/t5/ideas/idb-p/ideas) instead. 

Using Mozilla Connect doesn't mean all ideas will be implemented. However, if an idea is trending, it'll be escalated to the right team/person.
