### ISSUE TITLE
Feature Request: Provide a toggle button to disable "Open this site in your assigned container?"

### ISSUE THREAD

**Issue by KevinSpringfield** [mozilla/multi-account-containers#2190]
In my use case, I need to use multiple accounts such as admin coount, test account 1, test account 2, et cetera on the same site and this plugin used to meet my need before feature of "Open this site in your assigned container?" was added.

I prefer to choose which container on my own instead of always asking me which container to use.

It will be nice to have this feature, thanks :D.

**Comment by franciscoj** [comment]
I had this same issue recently. It happens because you use the "Always Open this Site in..." option.

The only way I could find to undo it is to remove the container and adding a new one.

**Comment by dsl101** [comment]
Yes, this _really_ needs a 'never ask me again' option. And possibly the option to store the answer _per domain_ rather than by URL (which is what I assume it is doing). And a way to see what data is stored related to this feature and clear it.

For example, opening a Zoom meeting via URL is always unique, and so always asks, but I'd like to not be asked for _any_ URL in the zoom.us domain. But I _do_ want to be able to manually specify a container, so I can log in to several different zoom account web portals.

**Comment by gjcooper** [comment]
This comment on another issue helped me in what I think is a similar situation. https://github.com/mozilla/multi-account-containers/issues/2151#issuecomment-946249188

That is I accidentally requested google.com to open in a specific container, and everytime I googled something it asked whether I want to open in in that container. Removing google.com from the container in question by following the (unintuitive) linked procedure fixed this issue.

**Comment by dsl101** [comment]
Thanks—yes, that's fixed it for now. I also found the navigation in that panel (getting _back_ from removing the site from a container) to be really temperamental, so I think there are a few rough edges on this extension...

**Comment by achernyakevich-sc** [comment]
Would you be so kind to close this issue as it is resolved. :)

**Comment by ahtokca** [comment]
That would be very useful feature for me too. Just use the 'active' container and never ever ask me again :)

**Comment by adi-g15** [comment]
> This comment on another issue helped me in what I think is a similar situation. [#2151 (comment)](https://github.com/mozilla/multi-account-containers/issues/2151#issuecomment-946249188)
> 
> That is I accidentally requested google.com to open in a specific container, and everytime I googled something it asked whether I want to open in in that container. Removing google.com from the container in question by following the (unintuitive) linked procedure fixed this issue.

+1, same happened with me, it solved it.

I think 2 alternate ways:
1. Either provide an option to 'disable' the always open in this container on the right click on extension or elsewhere
2. Following the "Remember this decision" (right now, it does NOT work, it just kept asking the same thing):


![2021-12-10_00-59](https://user-images.githubusercontent.com/37269665/145463071-63a678c9-3778-439f-b896-79fbc04767b3.png)

**Comment by achernyakevich-sc** [comment]
> Allowing per-URL configuration would solve some of the problems, and allowing storing multiple defaults with the UI supporting that e.g. with the dropdown and with navigation originating from each respecting the selection unless overridden would solve some others.

@effs This functionality is already implemented and available for Firefox users. But it is implemented in Containerise add-on that is greatly integrated with MAC. See https://github.com/mozilla/multi-account-containers/issues/2271#issuecomment-1027020894.

**Comment by effs** [comment]
@achernyakevich-sc Thanks for the pointer, I'll check it out! If I understand correctly, I can disable "always open in" in MAC and use Containerize for that part? I'll have to see how it integrates with TC.

I'd still consider it to be better as part of the default feature set, same as temporary containers, as it would allow one clear place for the rules and a clearer way to escape an assignment (i.e. if I force-open an assigned domain in a non-assigned tab, any clicks from that tab should respect the setting).

I know it's not a simple thing to get the feature set and interface right for that, but it's far less simple for users to get it right having to combine (and find!) multiple addons that may or may not interop exactly right - and I consider the ability for just your normal internet users to separate browsing spaces in the MAC/TC/Cz way to be essential going forward. Fully separate profiles is an outdated solution, but even my programmer circles could use a more straightforward alternative.

**Comment by KevinSpringfield** [comment]
Thanks guys, my problem has been solved. Issue closed.
