### ISSUE TITLE
Support - server location feature

### ISSUE THREAD

**Issue by chrimez** [mozilla/multi-account-containers#2198]
Your Add-on's [release notes (Firefox Release 94.0)](https://www.mozilla.org/en-US/firefox/94.0/releasenotes/) announced: "We’re rolling out the Firefox Multi-Account Containers extension with Mozilla VPN integration. This lets you **_use a different server location for each container_**."

Unfortunately, there is no manual or doc on how to use this feature to "use different server locations". Only a link to GItHub for "support". 

Can you please clarify how to use "different server locations"? Or check which is used? 
-Thank you :D for this helpful add-on

- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Steps to reproduce
1.
2.
3.

**Comment by dannycolin** [comment]
See https://support.mozilla.org/en-US/kb/use-multi-account-containers-mozilla-vpn for instructions on how to set a different VPN server per container. 

If there's something missing in the instruction, feel free to ask for help on the support forum at https://support.mozilla.org/en-US/questions/new/desktop/form. 

Closing for now.
