### ISSUE TITLE
Allow removing "always open in container" shortcut

### ISSUE THREAD

**Issue by xmo-odoo** [mozilla/multi-account-containers#2207]
- Multi-Account Containers Version: 8.0.1
- Operating System + Version: Linux Mint 20.2 ("uma")
- Firefox Version: 94.0b9
- Other installed Add-ons + Version + Enabled/Disabled-Status:
```
amazon@search.mozilla.org
Better Pull Request for GitHub	extension	1.0.35	true	{3ffa20cc-5fc8-4e3a-99af-d71996641e7a}
Bing	extension	1.3	true	bing@search.mozilla.org
Chambers (UK)	extension	1.0	true	chambers-en-GB@search.mozilla.org
Contextlets	extension	0.4.1	true	{dcf34dbe-ccd1-11e7-8f66-ff8971474715}
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Enhancer for YouTube™	extension	2.0.108	true	enhancerforyoutube@maximerf.addons.mozilla.org
Firefox Multi-Account Containers	extension	8.0.1	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
Let's get color blind	extension	1.0.0	true	letsgetcolorblind@hilberteikelboom.nl
Odoo Terminal	extension	8.3.0	true	{cdfbfc50-7cbf-4044-a6fb-cdef5056605c}
Privacy Badger	extension	2021.8.17	true	jid1-MnnxcxisBPnSXQ@jetpack
Refined GitHub	extension	21.11.9	true	{a4c4eda4-fb84-4a84-b4a1-f7c1cbf2a1ad}
Service Worker Detector	extension	2.4.0	true	{7f976419-2e7e-4ca5-983c-0fd0187e92ef}
Stylus	extension	1.5.21	true	{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}
Tampermonkey	extension	4.13.6136	true	firefox@tampermonkey.net
Temporary Containers	extension	1.9.2	true	{c607c8df-14a7-4f28-894f-29e8722976af}
uBlock Origin	extension	1.38.6	true	uBlock0@raymondhill.net
Web Archives	extension	2.1.0	true	{d07ccf11-c0cd-4938-a265-2a4d6ad01189}
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
```
### Actual behavior

The "always open this in a container" shortcut is always enabled, because of its location in the address bar I regularly hit it when I just want to open or switch container.

Unlike other toolbar locations, the address bar can not be customised via the UI and probably requires mucking with the userChrome

### Expected behavior

Being able to get rid of this icon as it's not in any way critical.

**Comment by loominade** [comment]
it certainly doesn't help that the two icons like almost identical:
![two almost identical symbols](https://user-images.githubusercontent.com/11677380/146543330-e51f4b08-3d94-4df0-a862-d9f335f36023.png)

I'd prefer a system wide feature to disable address bar buttons but a setting in the addons preferences might suffice?!

**Comment by xmo-odoo** [comment]
> it certainly doesn't help that the two icons look almost identical: ![two almost identical symbols](https://user-images.githubusercontent.com/11677380/146543330-e51f4b08-3d94-4df0-a862-d9f335f36023.png)

Yep,  very easy to confuse and hit the wrong one.

> I'd prefer a system wide feature to disable address bar buttons but a setting in the addons preferences might suffice?!

I figure the icons on the left would probably be unacceptable to remove so the former would be unlikely to be acceptable, unless it's only the non-critical ones which go on the right? (can't say I've ever used the bookmark icon but it's distinctive so I don't think I've ever hit it by mistake).

**Comment by ouyen** [comment]
Me too, hope to add this setting.

**Comment by ouyen** [comment]
I find the method to hid this shortcut on this post : https://www.reddit.com/r/FirefoxCSS/comments/ok3mev/how_to_hide_the_multiaccount_containers_icon_in/

1. [Enable userChrome.css support in Fx v69+](https://www.reddit.com/r/FirefoxCSS/comments/brmi8v/psa_firefox_v69_users_will_have_to_set_a_pref_to/)(set `toolkit.legacyUserProfileCustomizations.stylesheets` to `true` in about:config)

2. Open about:support

3. Click on "Profile Folder" -> "Open Folder"

4. Create a sub-folder named "chrome"

5. Change into the new folder

6. Create a file named "userChrome.css"

7. Write userChrome.css as below:

```
#pageAction-urlbar-_testpilot-containers { display: none; }
```

8. Restart Firefox

![image](https://user-images.githubusercontent.com/60745334/186101105-d2a20848-c6fc-4db3-95ae-f2066c460f8e.png)

**Comment by dannycolin** [comment]
Close #2066
