### ISSUE TITLE
8.0.2's "what's new" blurb has weird spacing

### ISSUE THREAD

**Issue by globau** [mozilla/multi-account-containers#2211]
Steps:
1. move the toolbar icon into the overflow menu
2. trigger the 8.0.2 what's new page
3. observe the lack of bottom padding

<img width="388" alt="Screen Shot 2021-11-25 at 1 02 33 pm" src="https://user-images.githubusercontent.com/872825/143382705-f3b2dff2-46c2-40c2-95b5-eb1242ae5eee.png">

 This appears to only happen on the first display of this information; closing it without clicking "Done" and re-opening results in the following, which looks good:

<img width="391" alt="Screen Shot 2021-11-25 at 1 06 20 pm" src="https://user-images.githubusercontent.com/872825/143382893-96519af7-cc1c-44a1-be69-3f8c4bc9e25e.png">

Side-by-side it looks like the top padding is also missing initially.

**Comment by dannycolin** [comment]
Closing since extensions won't be allowed in the overflow menu in Firefox 109+.
