### ISSUE TITLE
Accidently Reset Onboarding Panels

### ISSUE THREAD

**Issue by T3chminator** [mozilla/multi-account-containers#2212]
- Multi-Account Containers Version: 8.0.1
- Operating System + Version: Windows 10 64 Bit + Version 10.0.19044 Build 19044

- Firefox Version: 94.0.2 (64-bit)

I accidentally reset the on boarding panels and now not sure how to get them back. Please help.

**Comment by bakulf** [comment]
I don't understand this issue. Can you describe it more? Thanks

**Comment by T3chminator** [comment]
it's fine, i got back my containers. As you mentioned, i had briefly lost
the containers when you was doing maintenance.
