### ISSUE TITLE
Enter key no longer works on "Open this site in your assigned Container?" page

### ISSUE THREAD

**Issue by Exagone313** [mozilla/multi-account-containers#2214]
- Multi-Account Containers Version: 8.0.2
- Operating System + Version: Arch Linux
- Firefox Version: 94.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: not relevant

### Actual behavior

When a website is configured to open in a particular container, but the decision has not been *remembered*, it shows the `Open this site in your assigned Container?` page.

When pressing the *enter* key, it doesn't validate the button `Open in <selected container> Container`

Actually the button is not focused:

![21-11-25-18-10-15-716528312](https://user-images.githubusercontent.com/11819703/143481040-7397828c-b680-4727-bdc8-653f20c4fbeb.png)

### Expected behavior

When pressing the *enter* key, it should open the website in the selected container.

The button is expected to be focused:

![21-11-25-18-08-21-107753020](https://user-images.githubusercontent.com/11819703/143480945-30d0b70d-ffc0-43b5-bf69-f61c24d97e40.png)

### Steps to reproduce
1. Assign a website to container
2. Open a new tab and visit the website
3. On the `Open this site in your assigned Container?` page, press *enter*.

### Notes

This is a regression from the version 8.0.1, which is in fact the 7.x version:

> Version 8.0.1
> Released Nov 2, 2021 - 178.47 KB
> Works with firefox 67.0 and later
> Restoring previous version for some users who may have been accidentally updated prematurely 8.0.

The `autofocus` attribute of the `button` attribute has been removed in commit 05dc48eac2d12dc65dc2e062ad3d64d0fe77051a:
```diff
-        <button id="deny" class="button">Open in <dfn id="current-container-name">Current</dfn> Container</button>
-        <button id="confirm" class="button primary" autofocus>Open in <dfn class="container-name"></dfn> Container</button>
+        <button id="deny" class="button" data-message-id="openInContainer" data-message-arg="current-container-name"></button>
+        <button id="confirm" class="button primary" data-message-id="openInContainer" data-message-arg="container-name"></button>
```

I'm working on a PR.

**Comment by nabeelr** [comment]
I'd like to add fuel tho this fire. This is really annoying and should be corrected.
The highlighted button is always expected to be the action when a person hits the enter key. That not happening breaks UI convention going back more than 40 years.
