### ISSUE TITLE
Keyboard focus

### ISSUE THREAD

**Issue by urbantrout** [mozilla/multi-account-containers#2217]
- Multi-Account Containers Version: 8.0.2
- Operating System + Version: macOS 12.0.1
- Firefox Version: 95.0b12

When being asked if I want to open a specific URL in a container, keyboard focus used to be on the blue button. Since the latest update, this no longer happens:

<img width="818" alt="Screenshot 2021-11-26 at 14 54 11" src="https://user-images.githubusercontent.com/10465787/143591592-b3850c6b-5e89-4e4f-bf77-766dd1e491bf.png">

**Comment by groovecoder** [comment]
Fixing in https://github.com/mozilla/multi-account-containers/pull/2215. Will release ASAP.
