### ISSUE TITLE
[Feature] Open in new container tab key bindings 

### ISSUE THREAD

**Issue by kilasuit** [mozilla/multi-account-containers#2218]
As a feature request I think it would be helpful for there to be an additional key binding like Ctrl + Shift + T to pop up the New Container tab page. 
Additionally it would also be useful to combine this with with 0-9 so that you can open a specific container with just your keyboard

**Comment by achernyakevich-sc** [comment]
At the moment already exists support of `Ctrl+Shift+<1..9>` shortcuts that create a tab in corresponding numbered container.

`Ctrl+Shift+T` already reserved by Firefox to reopen the last closed tab so it will not be possible to implement this way. Instead I would propose to vote for using `Ctrl+Shift+0` to open new tab in the same container as current tab. :)

**Comment by awmartin** [comment]
`Ctrl+Shift+<number>` isn't the macOS shortcut, but `Cmd+Shift+<number>`. This unfortunately interferes with the system-wide standard screenshot shortcuts: `Cmd+Shift+3`, `Cmd+Shift+4`, and `Cmd+Shift+5`.

I recommend this [add-on to avoid collisions.](https://addons.mozilla.org/en-US/firefox/addon/easy-container-shortcuts/)

**Comment by kilasuit** [comment]
You know I should have tested thiat this worked or looked at the manage extension page before raising this. My bad

**Comment by Glokta0** [comment]
Hi @achernyakevich-sc,
Any chance this will migrate down to the default "container tabs" functionality in Firefox, or will I have to use the "Multi-Account Containers" Add-on?
Cheers!
