### ISSUE TITLE
Stop trying to steal user information by asking for unnecessary permissions

### ISSUE THREAD

**Issue by blue-sunset** [mozilla/multi-account-containers#2221]
Firefox permissions: You do not need to access other applications to implement account containers.

Stop trying to steal user data.

**Comment by hackel** [comment]
@blue-sunset This aggressive rhetoric is ridiculous and unhelpful.  No one is trying to "steal user data".  All of the source code is right here for you inspect to confirm this.

I do think it was a mistake not to include any mention of the new permissions in the release notes.  I came here to figure out what they were required for and so far have found nothing.  There isn't even a release for 8.0.2 on Github yet.  I shouldn't have to search the git blame of manifest.json just to discover that the nativeMessaging permission was added for MozillaVPN support.  This should really be made an optional permission for users who do not utilize Mozilla VPN.

**Comment by bakulf** [comment]
Hello! I can answer here. 8.0.2 introduces a "proxy-per-container" feature.  As a user, you can set a custom proxy configuration for each container. A lot of users have requested this feature for many years, and finally, we implemented it.
But the user of the proxy API requires extra permission in firefox.

And yes, we forgot to mention the new permissions in the release note.

Let me know if you want to know more.

**Comment by Nanzikambe** [comment]
I too would prefer this permission be optional

**Comment by bakulf** [comment]
Sounds good! We can make it optional in the next release.
