### ISSUE TITLE
Make "exchange messages with programs other than Firefox" permission optional

### ISSUE THREAD

**Issue by rsyring** [mozilla/multi-account-containers#2226]
Per https://github.com/mozilla/multi-account-containers/issues/2210#issuecomment-981915661, making this permission request optional is the plan.  But I had to read a few issues before I found that comment.  Creating this issue with the hope that it's helpful and easily found by others looking for the status of this permission.

Refs: #2210, #2221

**Comment by achernyakevich-sc** [comment]
Another duplicate found: #2240

**Comment by lesleyjanenorton** [comment]
Closing - this is fixed as of #2225 and was shipped today.

**Comment by NickDaly** [comment]
I just wanted to thank you folks for all the thought, care, and hard-work you put into addressing this little issue, particularly so close to the holidays.  Your efforts and your obvious care for your users are appreciated.
