### ISSUE TITLE
Add more colors to the extension

### ISSUE THREAD

**Issue by Bakkertje01** [mozilla/multi-account-containers#2228]
Can you please add more colors :)

**Comment by pianoskateboard** [comment]
And more icons! Waaaaay more!!!

**Comment by GarlandKey** [comment]
I second this. I've been using this extension since it was first released. Anyone using this extension is going to be a power user. As such, we need to be able to set our own colors or a much larger color palette should be added.

**Comment by dannycolin** [comment]
This needs to be implemented directly in Firefox. Also, if a solution is implemented upstream, it will definitely be a way to select a custom color so I'm going to close this issue in favor of #391. Please upvote this one. Thanks :)
