### ISSUE TITLE
"Open in X container" button is no longer focused on the "Open this site in your assigned container?" page

### ISSUE THREAD

**Issue by maples3** [mozilla/multi-account-containers#2230]
- Multi-Account Containers Version: 8.0.2
- Operating System + Version: Windows 10
- Firefox Version: 94.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:

**Add-ons**
> Name 	Type 	Version 	Enabled 	ID
> Adblock Plus - free ad blocker	extension	3.11.4	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
> Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
> Bing	extension	1.3	true	bing@search.mozilla.org
> Cookie Quick Manager	extension	0.5rc2	true	{60f82f00-9ad5-4de5-b31c-b16a47c51558}
> DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
> DuckDuckGo Privacy Essentials	extension	2021.9.30	true	jid1-ZAdIEUB7XOzOJw@jetpack
> eBay	extension	1.3	true	ebay@search.mozilla.org
> Facebook Container	extension	2.3.1	true	@contain-facebook
> Firefox Multi-Account Containers	extension	7.4.0	true	@testpilot-containers
> Google	extension	1.1	true	google@search.mozilla.org
> Google Container	extension	1.5.4	true	@contain-google
> LeechBlock NG	extension	1.1.1	true	leechblockng@proginosko.com
> React Developer Tools	extension	4.21.0	true	@react-devtools
> Redux DevTools	extension	2.17.1	true	extension@redux.devtools
> Temporary Containers	extension	1.9.2	true	{c607c8df-14a7-4f28-894f-29e8722976af}
> Web MIDI API	extension	1.0.2.6	true	{344fa695-4128-425d-97ad-5fcf54e84f21}
> Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
> Disable Facebook News Feed	extension	2.1	false	{85cd2b5d-b3bd-4037-8335-ced996a95092}

### Expected behavior
I have a website assigned to open automatically in a container.  (for example, slack.com to always open in the Work container)
When I type slack.com into the address bar, I hit Enter to go to the site.  This pops up the "Open this site in your assigned container?" page, with the "Open in Work container" highlighted and focused.  When I press Enter a second time, it submits the "Open in Work container" button and I then see slack.com in a Work container tab as expected.  This was the behavior before upgrading to version 8.0.2.  I manually uninstalled and downgraded the extension to 7.4.0 and verified that this is the behavior in the previous version.

### Actual behavior
When the "Open this site in your assigned container?" page is opened, the "Open in <name> container" button is no longer focused, preventing you from simply hitting Enter again to submit the button.

### Steps to reproduce
1. Install version 7.4.0 of the extension.
2. Assign a site to always open a container.
3. Navigate to that site in a regular tab.
4. Observe the "Open this site in your assigned container?" page - specifically, the "Open in <name> container" button is highlighted.
5. Press the Enter key on your keyboard
6. Observe that the button was submitted and the tab reloads in the assigned container.
7. Upgrade to version 8.0.2 of the extension
8. Repeat steps 3 and 4 above.
9. Attempt to press Enter to submit the button.  Observe that the button is not focused, and that hitting Enter no longer does anything.

### Notes
I find this workflow (type site - Enter to load - Enter to open in assigned container) very valuable.  I do not wish to check the "Remember my decision for this site" checkbox because I have not found any way to undo that selection and I occasionally have a need to open a site in a different container than normal.  One easy to understand example on a development website at work.  Ordinarily I do much of my testing on the dev site with a single user account, but sometimes I'll need to use a different user account for testing.  In this case, I want to open the site in a _different_ container than normal.  Therefore, I want to get the prompt everytime I open the site, and I want a very easy path to submit "yes, open in the assigned container", but also have the option to say "no, open in current container" in some circumstances.
The type-Enter-Enter pattern is extremely quick and easy to perform, and I have become very accustomed to it.  With version 8.0.2, I now need to remove my hand from the keyboard, move the mouse, click on the button, then move my hand back to the keyboard so I can start typing on the page (in most scenarios I use this for, there is already a text field focused on the page that I wish to type in).

If there's another way to solve the problem of "I want to open this site in this container 90% of the time, but still say NO sometimes", I would love to hear about it!  However I haven't found anything that works as well as the type-Enter-Enter pattern, and I'm disappointed that it is no longer functional in the newer version.  Container tabs are an amazing tool and I'm super grateful for all the effort that has been put into making them as great as they are!  I hope that restoring the focus on the button is something small and doable to increase the utility of this awesome extension.

**Comment by Tsunami2056** [comment]
Hi, I'm in the same boat. I strongly relied on this feature to address the same 90% use case and be able to conveniently manage the 10% case where I don't want to open this site in the same container.

![2021-12-06 16_00_58-Multi-Account Containers Confirm Navigation](https://user-images.githubusercontent.com/60357888/144869878-419390ed-e18f-400a-912f-b122d40e7657.png)
.

**Comment by Pfeil** [comment]
I am sure this is a duplicate of #2214 and was fixed in #2215 , which is already merged. I hope it will be released soon, as stated in https://github.com/mozilla/multi-account-containers/issues/2217#issuecomment-981098082 . Not sure what is holding back, it might be a lack of time or something else that has to be fixed.

**Comment by maples3** [comment]
Awesome, thanks!  I thought I had searched for this issue before posting but clearly not well enough :)
I'll subscribe to those other issues for updates.
Thanks @Pfeil !
