### ISSUE TITLE
Add the ability to collapse tabs for a given container

### ISSUE THREAD

**Issue by jsabin** [mozilla/multi-account-containers#2234]
It would be really nice to include a feature to collapse multiple tabs for a single container similar to Chrome's tab groups where clicking on the tab group collapses all tabs in the group to a single tab. Clicking on the tab again will expand the group into multiple tabs.

**Comment by achernyakevich-sc** [comment]
@jsabin, probably https://github.com/mozilla/multi-account-containers/issues/2131#issuecomment-925077221 will help you. If so then it would be great if you will close your issue. :)

**Comment by jsabin** [comment]
Yes, I realize I can use multi-account container with the simple tab groups plugin, but its kludgy and more complicated. It would be nice to include the functionality in this plugin. You have the ability to hide and show containers. Seems like collapsing is a small step above that.

I will use simple tab groups for now.

**Comment by achernyakevich-sc** [comment]
As I got impression from other talks in this repository the MAC team is focused on container functionality only, usability, extra features for hiding/showing/grouping/etc. is not in there sphere of interest and they recommend to use other add-ons that will be complement MAC. It will simplify main idea/features' development and will not stuck under pile of regression issues.

So Simple Tab Groups (STG) is recommended (as well Mozilla marked this add-on as recommended) as handle tab groups and tabs visibility very well. As well I would personally recommend you to introduce STG to your everyday work as it helps to be focused on important things at concrete moment and easily switch between different contexts. :)

P.S. Do not forget to close this issue. :)

**Comment by jsabin** [comment]
That's unfortunate. Thanks for the info.
