### ISSUE TITLE
V. 57 is not enough

### ISSUE THREAD

**Issue by riksoft** [mozilla/multi-account-containers#2236]
- Operating System + Version: Debian 10
- Firefox Version: ESR v. 78 from Debian repo

### Actual behavior
The addon cannot be installed. It is not even proposed as an installable addon, so it's not a matter of collision with other addons or whatever: it seems that the requirements are not  v.57+ but at least v.79+ (because with v.78 is not even proposed).

### Expected behavior
The addon should install since the doc here says v. 57+ is enough

### Steps to reproduce
1. Try to install the addon on Firefox ESR (v.78) on Debian Buster

### Notes
On the same computer with Debian, it works with FF Developer edition (v. 95)

**Comment by MuadDibIII** [comment]
Hello, 

I'm having the same issue on Firefox 91.6.0esr (64 bits), Debian 11

**Comment by dannycolin** [comment]
Closing in favor of #2286
