### ISSUE TITLE
Regression: Assigned Container Tab should autofocus on "Open in <name> Container" button

### ISSUE THREAD

**Issue by goodevilgenius** [mozilla/multi-account-containers#2237]
### Actual behavior

When I have a site that opens in a specific container, and I open that site, the "Open this site in your assigned container" tab pops up, and I have to type "Tab" three times to focus on the desired button.

### Expected behavior

It should be focused on the "Open in <name> Container" button, allowing the user to simply click "Space" or "Enter" to open in tab, without any additional behavior.

### Steps to reproduce
1. Set a specific site to open in a specific container. (E.g., github.com should open in "Code" container)
2. Open site in new tab
3. Try to click space bar to open in Code container
4. Find that the button is not focused

### Notes

![Screen Shot 2021-12-07 at 4 06 12 PM](https://user-images.githubusercontent.com/254662/145113711-2025b6f3-eff2-4863-8437-ced7b4033ea0.png)

The screenshot above shows what I'm talking about. In previous versions, when this tab opened, the blue button was already focused, and I could simply press the space bar to open the page. However, the most recent version has changed this, and no particular element is focused.

![Screen Shot 2021-12-07 at 4 13 40 PM](https://user-images.githubusercontent.com/254662/145114224-d719ad22-bd30-4d7a-9f3d-fd22cfabcabd.png)

This is how it should look, with the correct button focused. However, I now have to click Tab three times to get that button focused.

**Comment by jetpks** [comment]
Looks like this was fixed by #2215 and released in v8.0.3.

**Comment by goodevilgenius** [comment]
Works for me now. Thanks!
