### ISSUE TITLE
Remove the need to accept "may message external applications" permission?

### ISSUE THREAD

**Issue by Pomax** [mozilla/multi-account-containers#2240]
- Multi-Account Containers Version: 8.0.1
- Operating System + Version: win 10 x64
- Firefox Version: nightly
- Other installed Add-ons + Version + Enabled/Disabled-Status: n/a

I'm being badgered by Firefox to update multi-account containers but this requires accepting new permissions that I have no intention of accepting, specifically the "exchange messages with programs other than Firefox" permission. There is no mention of why it needs that permission, or which programs it wants to talk to, but for super obvious reasons I'm not going to grant that permission even if I trust Mozilla itself to have my best interest at heart.

![{FCE63313-FF17-4BC9-A006-BD39837D574D}](https://user-images.githubusercontent.com/177243/145866795-a5ed30f2-568d-4273-8164-51ab84d388da.png)

**Comment by achernyakevich-sc** [comment]
It looks this issue is duplicate of #2210 and guys already agreed to make these permissions optional - https://github.com/mozilla/multi-account-containers/issues/2210#issuecomment-981915661.

Probably this issue could be closed as duplicate.

**Comment by Pomax** [comment]
Ah, I missed that one, thanks for finding it. That does indeed seem the exact same issue. Closing this one.
