### ISSUE TITLE
Searching in a designated container opens a new tab by default

### ISSUE THREAD

**Issue by brochard** [mozilla/multi-account-containers#2245]
- Multi-Account Containers Version: 8.0.4
- Operating System + Version: Windows 10
- Firefox Version: 95.0.1

### Actual behavior
When on a site in a container set to Limit to Designated Site, when you use the search bar, instead of leaving the container and searching in this tab it opens a new tab.

### Expected behavior
Like with the Facebook container or other container extensions (like google container), when you use the search bar to search something, it opens it in the current tab and leaves the container.

### Steps to reproduce
1. Make a container limited to a site (for exemple duckduckgo.com)
2. Open the site
3. Use the search bar to search for something
4. It opens a new tab which seems abnormal

### Also
Since Facebook container and Multi-account container reacts differently there is an other problem when you use them together, when in a designated container, using the search bar to go to Facebook will both go to Facebook and open Facebook in a new tab.

**Comment by brochard** [comment]
EDIT:
There's a setting at the bottom of the addon options that manages that, but there's still the second issue with Facebook container

**Comment by dannycolin** [comment]
> Use the search bar to search for something

What search bar are you referring to?

**Comment by brochard** [comment]
> What search bar are you referring to?

I'm referring to the firefox URL bar,
Anyway this tab opening "problem" isn't one, it's just a weird default setting you can change in the multi account container settings, something like
"
Tab behavior
Replace the tab rather than create a new one
"
The weirder problem is if you have a Multi account container tab opened and then you open facebook (having the facebook container addon), it opens two facebook tabs

**Comment by dannycolin** [comment]
Now, I get what you mean! AFAIK, this is a limitation of the webextension API that doesn't support swapping the cookies jar of a tab for another one. This forced transition animation is visible to the user and the UX looks broken.

Sadly, there isn't a lot we can do on our side. It also looks like a variant of [bug 1511449](https://bugzilla.mozilla.org/show_bug.cgi?id=1511449) where you have the same UX issue.

I think I'll close this issue on our side and invite you to comment on the bug report I mentioned or to create a new one on bugzilla. 

Honestly, I don't think it's something that'll be prioritized anytime soon upstream but at least it'll be filed on the right platform when/if someone has the time to work on a solution.
