### ISSUE TITLE
DNS  leaks on socks proxy

### ISSUE THREAD

**Issue by Yoskaldyr** [mozilla/multi-account-containers#2248]
- Multi-Account Containers Version: 8.0.4
- Operating System + Version: All versions
- Firefox Version: All supported versions
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
DNS leaks exist with socks servers :(

### Expected behavior
No DNS leaks

### Steps to reproduce
1. Just use any socks proxy for container

### Notes
It can be fixed just one line of code
in file `src\js\background\assignManager.js ` 
change 
~~~~js
    if (!result.proxy.mozProxyEnabled) {
        return result.proxy;
    }

    // Let's add the isolation key.
    return [{ ...result.proxy, connectionIsolationKey: "" + MozillaVPN_Background.isolationKey }];
~~~~
to 
~~~~js
    if (!result.proxy.mozProxyEnabled) {
        return [{ ...result.proxy, proxyDNS: true }];
    }

    // Let's add the isolation key.
    return [{ ...result.proxy, connectionIsolationKey: "" + MozillaVPN_Background.isolationKey, proxyDNS: true }];
~~~~

**Comment by groovecoder** [comment]
Thanks for the issue report. Fix in https://github.com/mozilla/multi-account-containers/pull/2258.

**Comment by firefox4ever** [comment]
@groovecoder DNS leaks are still present even with `proxyDNS: true` when firefox proxy settings set to any value except manual proxy settings with socks proxy set and DNS over Socks enabled. Looks like firefox ignores  proxyDNS flag from webextension API when global DNS over Socks setting disabled. Issue exist on latest relese version and latest esr version.

I think this is firefox webextension proxy API issue. Because DNS leaks are present in all other similar addons.

**Comment by groovecoder** [comment]
@firefox4ever - are you running this merged branch of the add-on? Or still running 8.0.4? We haven't been able to release yet.

**Comment by firefox4ever** [comment]
@groovecoder Yes, I tested latest version of main branch with latest commits using web-ext
I develop own container proxifier addon and found this issue. And I decided to check all other addons with similar functions. 
I think it firefox issue, but I'm not sure.

**Comment by Lem** [comment]
As already mentioned in the other issue, this issue seems to break the "Advanced Proxy Settings" in 8.0.5.

**Comment by lxgr** [comment]
This is still (or again) happening in 8.1.2.
