### ISSUE TITLE
Suggestion for joining a new resource.

### ISSUE THREAD

**Issue by jcmljunior** [mozilla/multi-account-containers#2249]
![image](https://user-images.githubusercontent.com/82642883/147154006-00754a6d-f34c-4004-b7f3-7b476cce444e.png)

Would it be possible for you to consider joining a role to define a default container for opening new links?
A good way to adapt navigation with containers might be to set a container to work by default.
Thank you!

**Comment by achernyakevich-sc** [comment]
I'm not sure that development team will implement it because it is more about tabs handling than about containers.

The same behavior (or even more useful) you could achieve by using Simple Tab Groups (STG) add-on that is perfectly integrated with Multi-Accounts Containers (MAC) add-on. There you could configure `Always open tabs in container` per group of tabs. So any new tab open in the selected group will be automatically open in the appropriated container.

BTW: STG provides really brilliant functionality to organize your work and separation of work contexts. :) 

If it will match you need probably it will be a good idea to close this issue. :)

**Comment by jcmljunior** [comment]
> I'm not sure that development team will implement it because it is more about tabs handling than about containers.
> 
> The same behavior (or even more useful) you could achieve by using Simple Tab Groups (STG) add-on that is perfectly integrated with Multi-Accounts Containers (MAC) add-on. There you could configure `Always open tabs in container` per group of tabs. So any new tab open in the selected group will be automatically open in the appropriated container.
> 
> BTW: STG provides really brilliant functionality to organize your work and separation of work contexts. :)
> 
> If it will match you need probably it will be a good idea to close this issue. :)

I found this extension a little confusing to use.
![image](https://user-images.githubusercontent.com/82642883/147230167-5fbf18c3-aabc-4d50-a360-c452a6bddafd.png)

Google's browser manages to handle groups of tabs more simply.
![image](https://user-images.githubusercontent.com/82642883/147229937-732302b9-e4cc-408d-bcce-784028a45b2b.png)

I think I will wait for a response from one of the developers of this project.
Thanks for the tip of the extension.

**Comment by achernyakevich-sc** [comment]
You need one step forward - click `Group settings` and reach to group's configuration:
![image](https://user-images.githubusercontent.com/24388336/147242724-d6b10dc9-bc5c-44ce-a0fa-3d3e860625da.png)
like this:
![image](https://user-images.githubusercontent.com/24388336/147243261-62d58895-d400-428f-a401-8652528a7eda.png)

And you could configure every group for own container. And easily switch between groups of tabs that are currently open in your browser window.

Though you still could have some groups that will not behave as it is and provide possibility to open tabs in any container you would like to open tab in. So it is more flexible behavior/configuration than groups of tabs provided by Google or Apple in their browsers.

**Comment by jcmljunior** [comment]
> You need one step forward - click `Group settings` and reach to group's configuration: ![image](https://user-images.githubusercontent.com/24388336/147242724-d6b10dc9-bc5c-44ce-a0fa-3d3e860625da.png) like this: ![image](https://user-images.githubusercontent.com/24388336/147243261-62d58895-d400-428f-a401-8652528a7eda.png)
> 
> And you could configure every group for own container. And easily switch between groups of tabs that are currently open in your browser window.
> 
> Though you still could have some groups that will not behave as it is and provide possibility to open tabs in any container you would like to open tab in. So it is more flexible behavior/configuration than groups of tabs provided by Google or Apple in their browsers.

It's working for me. thanks for help.
