### ISSUE TITLE
stop asking me

### ISSUE THREAD

**Issue by exekutive** [mozilla/multi-account-containers#2256]
whenever I try to browser to a site A, by simply typing it in the address bar, I get a page saying

```
Open this site in your assigned Container?

You asked Firefox to always open someContainer for this site:
site A

Would you still like to open in this current Container?
```

I don't remember ever asking Firefox to do that. How do I un-ask it?

**Comment by achernyakevich-sc** [comment]
@exekutive , it looks like you have activate the `Aways Open in This Container` feature for the site A. So all you need is disabling it for this site.

You could try to do it by one of the way described in the [following comment](https://github.com/mozilla/multi-account-containers/issues/1730#issuecomment-997712373).

Please, close your issue if the advise will help. :)

**Comment by exekutive** [comment]
instructions are unclear


 > on the page open in the target container call context menu (right click) and you will get menu like here - just untick Aways Open in This Container.

right-click where?


>    click to MAC button on toolbar -> in opened UI click Manage Containers -> then click to your container (in your case it looks like it should be Shopping container) -> in opened UI click Manage Sites List... -> find URL of site that you would like to do not always open in the container and click bin icon. Close configuration window and restart Firefox.

This worked , but I had to search through all the containers to find the site.

Thank you.

**Comment by achernyakevich-sc** [comment]
> instructions are unclear

Strange that it is complicated. :)

See more details and screenshot below.

> > on the page open in the target container call context menu (right click) and you will get menu like here - just untick Aways Open in This Container.
> 
> right-click where?

Anywhere on the page that was open in undesired container. As result you will see context menu like this:
![image](https://user-images.githubusercontent.com/24388336/148211642-a6c33c50-3878-4f20-89cf-c4cbbdfcf57f.png)

And you will need just untick `Always Open in This Container`.


> > click to MAC button on toolbar -> in opened UI click Manage Containers -> then click to your container (in your case it looks like it should be Shopping container) -> in opened UI click Manage Sites List... -> find URL of site that you would like to do not always open in the container and click bin icon. Close configuration window and restart Firefox.
> 
> This worked , but I had to search through all the containers to find the site.

You needed just to check the page and name of the container it was open in. Like in red circle on the screenshot below:
![image](https://user-images.githubusercontent.com/24388336/148212312-8a263a5b-cff4-4e79-a9ab-ef9391ccbf8c.png)

and check manage that container settings to exclude site from it.

@exekutive, it looks like your problem is resolved so could you close this GitHub issue to show other people that correct answers available in comments. :)

**Comment by exekutive** [comment]
> Anywhere on the page that was open in undesired container. As result you will see context menu like this:

ok I found it.


Again , thank you.

**Comment by andfinally** [comment]
I've just discovered how I've been accidentally ending up with sites assigned to a container – this icon in the address bar, which I've never paid much attention to, and occasionally used without thinking.

<img width="227" alt="image" src="https://user-images.githubusercontent.com/1647564/183062676-3af75a6e-3188-4ceb-8750-ef27678de0bd.png">

It looks very similar to the "Multi-Account Containers" icon outside the address bar. But when you click it, it assigns the current site to a container. Unfortunately there is no preference in the extension to remove it.

**Comment by achernyakevich-sc** [comment]
@0xFlo Looks like you moved you already passed some way and reached your [question](https://github.com/mozilla/multi-account-containers/issues/1730#issuecomment-1381438635) in other thread.

As this issue is closed you could move to that thread and additionally read and vote for #2294.
