### ISSUE TITLE
Dropdown menues not working on https://homematic-forum.de/forum/index.php#

### ISSUE THREAD

**Issue by q-t-p** [mozilla/multi-account-containers#2260]
- Multi-Account Containers Version: 8.0.4
- Operating System + Version: macOS 10.14.6
- Firefox Version: 95.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Dropdown menues not working on https://homematic-forum.de/forum/index.php#
When hovering over the "Schnellzugriff" for example the text gets highlightet but nothing happens when klicking.
After disabling multi-account-containers Dropdown menues show up as expected

### Expected behavior
Dropdown menu should show up after klicking

### Steps to reproduce
1. open https://homematic-forum.de/forum/index.php#
2. klick "Schnellzugriff"
3.

**Comment by dannycolin** [comment]
Do you still experience this issue?

**Comment by dannycolin** [comment]
Closing: Stale.
