### ISSUE TITLE
Proxy works as Firefox setting but doesn't work in container

### ISSUE THREAD

**Issue by dehghani-mehdi** [mozilla/multi-account-containers#2281]
- Multi-Account Containers Version: 8.0.5
- Operating System + Version: Windows 10
- Firefox Version: 96.0.3
- Other installed Add-ons + Version + Enabled/Disabled-Status:
I disabled all installed add-ons, same result

### Actual behavior
Proxy doesn't work

### Expected behavior
Proxy should work

### Steps to reproduce
1. Create a container
2. Add proxy setting, e.g http://127.0.0.1:1234
3. Try to use created container to see a web page

### Notes
If I set same proxy setting in `Network Settings` in Firefox, everything works
Also I tested in brand new profile before posting issue here.

**Comment by pahennig** [comment]
Same happening with MacOS... seems like it was after an upgrade as it was working fine before.

**Comment by dariusjonda** [comment]
same here on linux using firefox 96.0.3.
It seems to only affect http proxies apparently, socks proxies are still working as before.

**Comment by groovecoder** [comment]
Dupe of #2278
