### ISSUE TITLE
Empty window/popup when clicking on icon

### ISSUE THREAD

**Issue by pokemaster974** [mozilla/multi-account-containers#2282]
Also please make sure that:
  - "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" is NOT selected => unselected
  - You are NOT using Firefox in a Private Window => I have a private window opened but using a no private window for the extension
  - You can see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs" => Yes

- Multi-Account Containers Version: 8.0.5
- Operating System + Version: Windows 10 build 19044
- Firefox Version: 96.0.3
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Add-ons Search Detection	extension	2.0.0	true	addons-search-detection@mozilla.com
Amazon.co.uk	extension	1.9	true	amazon@search.mozilla.org
automate-click	extension	1.4.7	true	{0d66b279-412d-441e-928b-7189c7005ded}
Bing	extension	1.3	true	bing@search.mozilla.org
Bitwarden	extension	1.55.0	true	{446900e4-71c2-419f-a6a7-df9c091e268b}
Bypass Paywalls	extension	1.7.9b	true	bypasspaywalls@bypasspaywalls
Bypass Paywalls Clean	extension	2.5.4.0	true	{d133e097-46d9-4ecc-9903-fa6a722a6e0e}
Chameleon	extension	0.22.20.2	true	{3579f63b-d8ee-424f-bbb6-6d0ce3285e6a}
ClearURLs	extension	1.22.0	true	{74145f27-f039-47ce-a470-a662b129930a}
Consent-O-Matic	extension	0.9.4	true	gdpr@cavi.au.dk
CORS Unblock	extension	0.1.9	true	{8d9dd0f0-6dc5-4595-8c81-fab876d0fef0}
Disconnect	extension	20.3.1.1	true	2.0@disconnect.me
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Export Cookies	extension	0.3.2	true	{36bdf805-c6f2-4f41-94d2-9b646342c1dc}
Firefox Multi-Account Containers	extension	8.0.5	true	@testpilot-containers
Gesturefy	extension	3.2.4	true	{506e023c-7f2b-40a3-8066-bc5deb40aebe}
Google	extension	1.1	true	google@search.mozilla.org
Neat URL	extension	5.0.0	true	neaturl@hugsmile.eu
NoScript	extension	11.2.19	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Popup View for Google™ Translate	extension	0.5.4	true	jid0-fbHwsGfb6kJyq2hj65KnbGte3yT@jetpack
Print Friendly & PDF	extension	4.3.0	true	jid0-YQz0l1jthOIz179ehuitYAOdBEs@jetpack
Privacy Badger	extension	2021.11.23.1	true	jid1-MnnxcxisBPnSXQ@jetpack
QookieFix	extension	0.1.26	true	{3b6e9729-589c-49e0-a8f6-303c43d87770}
Quick Dial	extension	0.1.20	true	quickdial@matmoul.com
Qwant	extension	1.1	true	qwant@search.mozilla.org
Reddit Enhancement Suite	extension	5.22.10	true	jid1-xUfzOsOFlzSOXg@jetpack
Snap Links	extension	3.1.11	true	snaplinks@snaplinks.mozdev.org
SponsorBlock pour YouTube - Supprime les publicités intégrées	extension	4.0.5	true	sponsorBlocker@ajay.app
Stylus	extension	1.5.21	true	{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}
Trace - Online Tracking Protection	extension	3.0.7	true	{6ff498ff-a3b6-4891-a614-12a825d4efcf}
uBlock Origin	extension	1.40.8	true	uBlock0@raymondhill.net
uMatrix	extension	1.4.4	true	uMatrix@raymondhill.net
Video DownloadHelper	extension	7.6.0	true	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
Violentmonkey	extension	2.13.0	true	{aecec67f-0d10-4fa7-b7c7-609a2db280cf}
weAutoPagerize	extension	1.7.6	true	weautopagerize@wantora.github.io
Wikipédia (fr)	extension	1.1	true	wikipedia@search.mozilla.org
Zotero Connector	extension	5.0.92	true	zotero@chnm.gmu.edu
Autofill	extension	10.0.10	false	{143f479b-4cb2-4d8c-8c31-ae8653bc6054}
Bulk Media Downloader	extension	0.2.2	false	{72b2e02b-3a71-4895-886c-fd12ebe36ba3}
FoxyProxy Standard	extension	7.5.1	false	foxyproxy@eric.h.jung
In My Pocket	extension	0.12.1	false	{cd7e22de-2e34-40f0-aeff-cec824cbccac}
MyJDownloader Browser Extension	extension	3.3.20	false	jid1-OY8Xu5BsKZQa6A@jetpack
Never-Consent	extension	1.15.3	false	{816c90e6-757f-4453-a84f-362ff989f3e2}
Privacy Possum	extension	2019.7.18	false	woop-NoopscooPsnSXQ@jetpack
Send to Kodi	extension	3.1.0	false	jid0-YCM0p5WlCGjvBJcZhAusQ5h26wM@jetpack
Tab Reloader (page auto refresh)	extension	0.3.7	false	jid0-bnmfwWw2w2w4e4edvcdDbnMhdVg@jetpack
Tab Session Manager	extension	6.11.1	false	Tab-Session-Manager@sienori

### Actual behavior
Opening an empty popup when I click on the Multi-Account Containers's icon

![Firefox](https://user-images.githubusercontent.com/28442699/152696124-aeaa78d6-62b2-4c14-aa12-72c43a5b79f5.jpg)

### Expected behavior
Having some settings when I click on Multi-Account Containers's icon

### Steps to reproduce
1. Open Firefoxe
2. Click on Multi-Account Containers's icon
3.

**Comment by dannycolin** [comment]
This was an issue with Firefox and should have been fixed in a recent version. If you ecounter this issue again, please file a bug report on bugzilla.mozilla.org.
