### ISSUE TITLE
The "New Tab" button hover menu is no longer displayed when Tab Center is either disabled or tabs are moved back to top

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/multi-account-containers#229]
[Affected versions]:
- Firefox 51.0.1 and above
- Tab Center 1.29.0 (Test Pilot version)
- Containers 0.9.1 

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was added in "about:config" page with "dev" value set on a new Firefox profile. 
- Test Pilot was already installed on the same profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Click on Containers experiment card and choose to "Enable" it.
3. Return to Test Pilot experiments page, click on Tab Center card and "Enable" it too.
4.  Hover on the "New Tab" button and observe the behavior.
5. From "Tab Center" experiment page, choose to "Disable" it.
6. Hover again over the "New Tab" button and observe the behavior.

[Expected result]:
- Containers hover menu appears both with or without Tab Center installed.

[Actual result]:
- Step 4: Containers hover menu appears when hovering the Tab Center "New Tab" button.
- Step 6: Containers hover menu no longer appears when hovering browser default "New Tab" button.

[Notes]:
- This also occurs if you choose to move tabs back on top from within Tab Center.
- The functionality returns to normal if browser is restarted.
- Here is a screen recording of the issue: https://goo.gl/MKQIUp.

**Comment by jonathanKingston** [comment]
Will debug and see who's issue this is.

**Comment by groovecoder** [comment]
Counterpart bug in TabCenter: https://github.com/bwinton/TabCenter/issues/953

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
