### ISSUE TITLE
Proxy settings dialog/popup truncates input to 50 characters

### ISSUE THREAD

**Issue by Caligatio** [mozilla/multi-account-containers#2295]
- Multi-Account Containers Version: 8.0.6
- Operating System + Version: Windows 10
- Firefox Version: 97.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: N/A

### Actual behavior
The containers proxy dialog/popup truncates long input to 50 characters which then mangles the proxy settings

### Expected behavior
To be able to enter proxy settings correctly

### Steps to reproduce
1. Open the dialog/popup to edit proxy settings for a container
2. Enter a 50+ character string, e.g. socks://username:password@test-socks5.relativelylongdomain.com:1111 and hit `Apply to Container`
3. Go back to the settings box and note that the parsed server is incorrect, e.g. socks://test-socks5.relativelylo:undefined
4. Attempting to use the container tab with the mangled proxy settings goes straight out using native connection

### Notes
The code in question is at https://github.com/mozilla/multi-account-containers/blob/cdd8ebc66a7101f33c62de7ab9d8d744f280c6d4/src/popup.html#L302

I'm happy to do a PR to eliminate the `maxlength` property but I'm not sure if there are side-effects to doing so.

**Comment by dannycolin** [comment]
Closing since a patch has been merged in the main branch.

**Comment by dabblejohns** [comment]
the 50 character limit on proxy still seems to be an issue is there a patch or way to fix this ?
