### ISSUE TITLE
Feature request: assign specific URL paths to container

### ISSUE THREAD

**Issue by jnbooth** [mozilla/multi-account-containers#2298]
- Multi-Account Containers Version: 8.0.6
- Operating System + Version: Arch Linux version 5.16.10-arch1-1
- Firefox Version: 97.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: Happens without any other add-ons installed

### Actual behavior

Containers filter by host name only. For example: if I add [www.google.com/android/find](http://www.google.com/android/find) to a container that stores cookies for my Google account, multi-account-containers assigns all URLs with the hostname of www.google.com   to that container. This is undesirable because it means all my searches through google.com will automatically be redirected into that Google container.

### Desired behavior

Containers can be instructed to filter by specific paths (optionally, URL patterns in general). This could be an option when adding the website to a container, while editing a container's site list, or both. Paths and subdomains are often used interchangeably (e.g. maps.google.com vs google.com/maps), and multi-account-containers does filter by specific subdomains, so it should be able to filter by paths as well.

### Notes

Alternatively, adding a site to a container could automatically base itself on the full path, so that if I select "Always open this site in" while at www.google.com/android/find, it would assign only www.google.com/android/find to a container. In order to add www.google.com to a container, I would need to select "Always open this site in" while specifically at www.google.com. In that case, website resolution might be based on starts-with, so www.google.com includes anything on www.google.com (including www.google.com/android/find), but www.google.com/android/find only includes  www.google.com/android/find/*.

**Comment by rockisch** [comment]
Sorry for necroing, but I'm pretty sure this is a separate issue. AFAIK currently MAC does not let you assign a URL path to a separate container, so even if you could manually edit the list, you would still not be able to do what OP mentions. The wildcard issues/PR also does not solve this issue.

Let me know if you'd rather I opened a new issue to track this.
