### ISSUE TITLE
Feature request: Search through enviroments 

### ISSUE THREAD

**Issue by arpsga** [mozilla/multi-account-containers#2299]
Since I'm using a lot of containers, it would really help to get a search bar to find the needed container tab asap.

**Comment by achernyakevich-sc** [comment]
There was many request like this. But it looks like this MACT add-on is not designed for it. From other side it provides greate capabilities for other add-ons. Your request could resolved by installing [Simple Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/) add-on that handles tabs (and not only in containers) in the great manner and has wide integration with MAC add-on (like sticky containers, etc).

If it helps you then could you closed this issue to show people that they could use the same. :)
