### ISSUE TITLE
Feature request: Nonpersistent containers

### ISSUE THREAD

**Issue by TinyAtoms** [mozilla/multi-account-containers#2303]
# Feature request
The option to make containers nonpersistent, or at least one default container that is nonpersistent. 
Then you just specify that you want this site to always use a container that does not have persistent storage.

Options in behaviour I'd appreciate:
* delete data from container as soon as tab closes
* delete data as soon as all tabs in container close
* delete data as soon as the browser closes
* delete data after a certain ammount of time
* and/or behaviour of the abovementioned

But honestly. I'd settle with only the first or the 2nd option.

## Why 
This is the usecase I am imagining is primarily online banking, but it'd be good for anything you want boxed of and don't want site data stored of. Honestly, any site you would currently use private mode for currently, with the benefit that you don't need to remember to open something in private mode.

The  options that kinda do what my request would do:
1. private mode. This has some problems, such as the fact that certain plugins, like bitwarden, don't work correctly in private mode, and the fact that you need to remember to open an private mode tab for it.
2. Going to settings > cookies and site data > make an exception to never store site data from a site. My problem with it is that it takes more steps than if the containers plugin had a nonpersistent container, in which case I just click the plugin > always open this site in > the nonpersistent container. This is what I curently do in combination with having sites set to open in a specific container, but it could certainly be easier. The other problem is that making the exeption on it's own does not box it of like containers does, although it is barely a hasstle to use these in conjunction.
3. Manually clearing cookies each time. Already a worse option than 2, because it requires you to keep doing it all the time.
4. Use a plugin that does cookie management. I haven't looked into these recently, but iirc, most of them I tried had a lot more initial setup compared to what this feature request would give.
5. something like https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/ which only happens to do what I want by opening new tabs in temporary containers. I don't want this accross all sites, if I wanted that I'd just use the settings to make firefox wipe all cookies when I exit or something.

# Alternatives to my suggestion that would also work
* [Per container privacy settings](https://github.com/mozilla/multi-account-containers/issues/318)
* Per container plugins, so something like Cookie autodelete could then emulate the behaviour of this feature request
*

**Comment by TinyAtoms** [comment]
> While I think overall it would be a huge benefit to everyone if MAC and Temporary Containers got unified, if I understand you correctly you _can_ do this in TC currently: auto on, global isolation off and just use per-domain isolation configuration. Is there something that this does not handle for you?

It_sounds_ like something that would work. But ... I have no idea how to configure TC so I can't  verify it works the way I'd like it to.
I have read the article and skimmed through the wiki linked on TC's repo, but I don't see __where__ I access the options they talk about, so I haven't been able to try it. 
It's not leftclicking the TC icon, that just opens a new temp tab.
It doesn't  provide an option in the rightclick menu to go to configuration/options, I just see the standard plugin options (Manage ext., Remove ext., blah)

**Comment by dannycolin** [comment]
Closing in favor of #929.
