### ISSUE TITLE
How delete the Firefox Sync Data of Multi-Account-Contrainers?

### ISSUE THREAD

**Issue by Maysi2k** [mozilla/multi-account-containers#2304]
- Multi-Account Containers Version: 8.06
- Operating System + Version: AllOS
- Firefox Version: 97.0.2

I have meanwhile since over a Year a Syncbug. One Container is over 100 Times there.
But i can't delete it. Firefox Sync is always override all local settings.

Screenshot: 
![1](https://user-images.githubusercontent.com/39185550/157225275-bf8fb8e4-c3ec-4fe5-bcb2-4e2b312f721b.png)
https://abload.de/img/1l7kel.png

Why is there no Option for "Delete Multicontrainer Syncdata" :(

**Comment by DesignatedJM02** [comment]
I have the same issue. I have containers from a while ago that I keep deleting but upon a new install and resync, they come back. It's very annoying.

**Comment by DrewNull** [comment]
I "solved" this by deleting my Firefox Account and starting over.
