### ISSUE TITLE
Some links do not open with this extension

### ISSUE THREAD

**Issue by zefilipe** [mozilla/multi-account-containers#2305]
Hi,

- Multi-Account Containers Version: 8.0.6
- Operating System + Version: Windows 10
- Firefox Version: 97.0.2 (but it occurs in previous versions)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Google Container - 1.5.4 - true
Facebook Container - 2.3.1 - true

### Actual behavior

Sometimes many links opened by example from gmail, its all time loading and do not show the contents of this link.
But it happens with somme websites that i try to open.
And if i try open new tab -> no container, the result its the somme !

### Expected behavior

Open links or websites, without show loading every time ... and i have to open in other browser !

### Steps to reproduce
1. Open GMAIL account
2. Click in link to open

Or 

1. Open a website in address bar

**Comment by achernyakevich-sc** [comment]
As I see you have installed `Google Container` add-on. Its goal is to protect your browsing from tracking by Google. I would expect that by blocking opening links sourced from Google it could block its opening.

Could you make the following tests - disable/uninstall `Google Container` add-on and check if links opening from GMail work.

**Comment by zefilipe** [comment]
Hi,

I disabled Google Container  addon, and test open links from Gmail, and this works well !
Maybe the problem its because Google Container, blocks somme links, to protect tracking !

Thank you !
Regards.
