### ISSUE TITLE
The extension tries to proxy even localhost / 127.0.0.1 / ::1

### ISSUE THREAD

**Issue by AlexanderDmitriyev** [mozilla/multi-account-containers#2307]
- Multi-Account Containers Version: 8.0.6
- Operating System + Version: Linux 5.8.0-43-generic 49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Firefox Version: 97.0.2 x86_64
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
When the proxy is configured the extension tries to proxy even localhost / 127.0.0.1 / ::1, at least for socks proxy that is relevant. 

### Expected behavior
localhost / 127.0.0.1 / ::1 are to be ignored by proxy settings 

### Steps to reproduce
1. Deploy any application locally on 80th port
2. Open http://localhost

**Comment by tom-HCgY7HY6kq** [comment]
Can you not just open in a non-proxied container?

There are instances when socks proxy for localhost is required and the expected behavior. E.g. If SSH tunneling through a remote host, accessing localhost through the proxy will expose local services on the proxied host.

**Comment by tom-HCgY7HY6kq** [comment]
Little disappointed this issue was "fixed" and closed without any view to the comment I made. 🤷 

Will open a new issue now a feature has been removed because of this.

**Comment by 303sec** [comment]
I used to use multi-account container to access localhost apps via SSH tunnels, exactly as @tom-HCgY7HY6kq describes, as well as to use local interception proxies like Burp Suite to access and test localhost apps. 

For anyone looking for answers, the only way to now proxy localhost traffic is through changing the config setting `network.proxy.allow_hijacking_localhost` to true. But I would really appreciate it if this was just an option in the extension instead!
