### ISSUE TITLE
The always-open-in-container button is too similar to the open-a-new-container-tab button

### ISSUE THREAD

**Issue by anordal** [mozilla/multi-account-containers#2312]
Many times, I have clicked the wrong button …

![wrongbutton](https://user-images.githubusercontent.com/4992374/158902081-46d67ec1-7edf-4bfa-b0f3-267426d2014b.png)

… and needed to google how to undo it because that's comparatively hidden.

The reason why my brain clicks on things in the wrong menu without even reading the context at the top of it, I think,
is because the two buttons and the two menus topologically match each other.

The mistake wouldn't be so easy if there was one button and one combined menu.

That said: Many thanks for making Multi-account containers! It is the main reason I use Firefox everywhere.

- Multi-Account Containers Version: 8.0.6
- Firefox Version: Nightly 100.0a1 (2022-03-17)
- Operating System + Version: openSUSE Tumbleweed 20220309"
- Other installed Add-ons + Version + Enabled/Disabled-Status: Undo Close Tab 7.5.0

**Comment by dannycolin** [comment]
Closing as WONTFIX because pageAction (left one) will be removed in the newest version of WebExtension API called Manifest V3 

See for more informations on Manifest V3: https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/
