### ISSUE TITLE
Allow containers to operate with "no VPN"

### ISSUE THREAD

**Issue by Caspy7** [mozilla/multi-account-containers#2316]
I run with Mozilla's VPN for general privacy but some sites detect a VPN and will not operate properly.
This forces me to use other browsers, which I don't prefer.

If this is already possible sorry if I missed it. I see that I can set containers to various locations but there's no option for "No VPN".

**Comment by dannycolin** [comment]
A good example:

1. Enable Mozilla VPN
2. Open Firefox
3. Go to Amazon Prime

AB:

Amazon Prime detects Mozilla VPN and prevents you from watching videos. The current solution is add another browser (or another copy of Firefox) to the split-tunneling option in Mozilla VPN

EB:

Create a container that use the split-tunneling functionality of the VPN so I can watch Amazon Prime videos in my main Firefox instance.

**Comment by derenv** [comment]
this feature would be really useful, for streaming services in particular.

@dannycolin 's workaround is a good one (i usually use developer edition but would happily use normal firefox to do this), but on linux [only GTK-based desktop environments support split tunneling](https://support.mozilla.org/en-US/kb/split-tunneling-use-mozilla-vpn-specific-apps-wind?redirectslug=split-tunneling-use-mozilla-vpn-specific-apps&redirectlocale=en-US).. meaning folks using Manjaro KDE (i.e. me lol) etc can't use it.

**Comment by dannycolin** [comment]
Closing duplicates of #2259
