### ISSUE TITLE
Redirect container(s) traffic without the rest of the traffic

### ISSUE THREAD

**Issue by Cimbali** [mozilla/multi-account-containers#2328]
I would like to have some containers to run via a VPN without having all my traffic redirected, in particular:
- some tabs may want to access websites directly like #2316 − I’m also thinking of requests on a local network or a corporate VPN
- some other applications may want to access directly without a VPN, e.g. ssh with whitelisted origin IPs

If to do this I disconnect the mozilla VPN, the tabs that should get routed via a VPN are not working anymore.

I understand there’s likely a need for the VPN app to be on and connected for MAC to use it − ideally the VPN app could be connected without all the traffic being redirected, and MAC could use it for select containers.

**Comment by dannycolin** [comment]
> some other applications may want to access directly without a VPN, e.g. ssh with whitelisted origin IPs

If I understand correctly, you want to use your VPN for some containers while allowing some applications outside your browser to bypass your VPN connection.

If this is the case then it's something you need to configure in your VPN application. It is called split-tunneling.

**Comment by Cimbali** [comment]
Yes I’d want split-tunneling for containers basically. Being able to run most of my Firefox traffic without a VPN when I can’t find a stable server, accessing IP-whitelisted resources from my browser, etc.

Not that there is split-tunneling in the mozilla-vpn app anyway, as I’m running on KDE and [that combination is not supported](https://support.mozilla.org/en-US/kb/split-tunneling-use-mozilla-vpn-specific-apps-wind).

**Comment by dannycolin** [comment]
> Not that there is split-tunneling in the mozilla-vpn app anyway, as I’m running on KDE and [that combination is not supported](https://support.mozilla.org/en-US/kb/split-tunneling-use-mozilla-vpn-specific-apps-wind).

There's an explaination for this limitation at https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1869#issuecomment-926065806. However, I hope they will find a better solution that covers more Desktop Environment since I'm also affected by this :(.

> Yes I’d want split-tunneling for containers basically. Being able to run most of my Firefox traffic without a VPN when I can’t find a stable server, accessing IP-whitelisted resources from my browser, etc.

Good. I'm going to close it in favor of #2259 to avoid duplicates so make sure to subscribe to it if you want to be notified of any progress.
