### ISSUE TITLE
When opening browser, all containers have disappeared

### ISSUE THREAD

**Issue by avoura** [mozilla/multi-account-containers#2331]
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: Ubuntu Studio 21.10
- Firefox Version: Waterfox G4.1.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

lus	extension	3.2	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
AdBlocker for YouTube™	extension	0.3.2	true	jid1-q4sG8pYhq8KGHs@jetpack
Amazon.co.uk	extension	1.9	true	amazon@search.mozilla.org
BibleTextFinder	extension	6.0	true	{e4d0dec7-7267-4aba-97e4-bbe0979cc48d}
Bing	extension	1.3	true	bing@search.waterfox.net
Bitwarden - Free Password Manager	extension	1.55.0	true	{446900e4-71c2-419f-a6a7-df9c091e268b}
Download	extension	8.87	true	download@addons.mozilla.org
DownThemAll!	extension	4.2.6	true	{DDC359D1-844A-42a7-9AA1-88A850A938A8}
DuckDuckGo	extension	1.1	true	ddg@search.waterfox.net
DuckDuckGo Privacy Essentials	extension	2020.10.13	true	jid1-ZAdIEUB7XOzOJw@jetpack
Easy Youtube Video Downloader Express	extension	17.4	true	{b9acf540-acba-11e1-8ccb-001fd0e08bd4}
eBay	extension	1.3	true	ebay@search.mozilla.org
Ecosia	extension	1.0	true	ecosia@search.waterfox.net
Enhancer for YouTube™	extension	2.0.109	true	enhancerforyoutube@maximerf.addons.mozilla.org
Evernote Web Clipper	extension	6.13.2	true	{E0B8C461-F8FB-49b4-8373-FE32E9252800}
Extensibles	extension	1.0.0	true	extensibles@waterfox.net
Facebook Container	extension	2.3.2	true	@contain-facebook
Firefox Multi-Account Containers	extension	7.1.0	true	@testpilot-containers
Forecastfox (fix version)	extension	4.26	true	forecastfox@s3_fix_version
Google	extension	1.2	true	google@search.waterfox.net
Highlighter + Notes	extension	1.0.0	true	highlighter-notes@pc
HTTPS Everywhere	extension	2022.3.24	true	https-everywhere-eff@eff.org
IPFS Companion	extension	2.19.1	true	ipfs-firefox-addon@lidel.org
No PDF Download	extension	1.0.6	true	{b9b25e4a-bdf4-4270-868c-3f619eaf437d}
Old Layout for Facebook	extension	7.1	true	{8792af17-0df8-40ab-81d3-6cc777171564}
Open in PDF Reader	extension	0.1.9	true	{0d3afca0-aedf-491f-b0f9-9ffc22113ea8}
Panorama View	extension	0.8.6	true	{60e27487-c779-464c-8698-ad481b718d5f}
pCloud Save	extension	1.4.0	true	{237ead2a-d4b4-4db1-9b50-5350452cabee}
Phantom	extension	0.15.1	true	{7c42eea1-b3e4-4be4-a56f-82a5852b12dc}
Presearch.org Search Extension	extension	1.1	true	{441ae0e7-c955-4b0e-8209-99462af458db}
Print Friendly & PDF	extension	3.2.0	true	jid0-YQz0l1jthOIz179ehuitYAOdBEs@jetpack
Qwant	extension	6.1.1	true	qwantcomforfirefox@jetpack
Return YouTube Dislike	extension	2.1.0.3	true	{762f9885-5a13-4abd-9c77-433dcd38b8fd}
Save as eBook	extension	1.4.2	true	{087005dc-849e-419b-acf6-32da1f83691d}
Search by Image	extension	3.1.0	true	{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}
Session Manager	extension	0.8.1.10	true	{1280606b-2510-4fe0-97ef-9b5a22eafe30}
Session Sync	extension	3.1.12	true	session-sync@gabrielivanica.com
session-resurrection	extension	1.5	true	{53bf5681-b6ad-4883-be7c-e831e167cec9}
Social Fixer for Facebook	extension	26.0.0	true	betterfacebook@mattkruse.com
SoundCloud Downloader - Technowise	extension	0.98	true	{c8d3bc80-0810-4d21-a2c2-be5f2b2832ac}
Startpage	extension	1.0	true	startpage@search.waterfox.net
Startpage.com — Private Search Engine	extension	1.3.0	true	{20fc2e06-e3e4-4b2b-812b-ab431220cada}
Tab Groups	extension	1.0.2	true	tabgroups@quicksaver
tab list	extension	1.7	true	{abed7ce6-ea64-4b94-9531-bacf5acb9166}
Tab List Board	extension	1.5.1	true	tablistboard@azisava.sakura.ne.jp
TabGroups Menu	extension	0.9.8	true	tabgroupsmenu@char.cc
Todoist	extension	10.3	true	support@todoist.com
uBlock Origin	extension	1.16.16	true	uBlock0@raymondhill.net
Video Downloader professional	extension	1.99.5	true	ffext_basicvideoext@startpage24
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
Yahoo!	extension	1.0	true	yahoo@search.waterfox.net
YT profile pic viewer	extension	1.1	true	{aaeaea7c-03bc-44a1-8fc3-494767dceb7e}
Zoom Scheduler	extension	2.1.18	true	{bf855ead-d7c3-4c7b-9f88-9a7e75c0efdf}
Tab Mix Plus	extension	0.4.2.0	false	{dc572301-7619-498c-a57d-39143191b318}
Video DownloadHelper	extension	5.4.2	false	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
YouTube Thumbnail Maker Download	extension	0.1.9	false	{0ebfc5e7-8955-4ee1-9b49-f150f66812d7}

### Actual behavior
When reopening, all tabs are no longer in Containers, although they had been before closing the browser.

### Expected behavior
All tabs should stay in the Containers they were assigned to previously.

### Steps to reproduce
1.
2.
3.

**Comment by achernyakevich-sc** [comment]
Why you use old version (`Multi-Account Containers Version: 7.1.0`)? Could you try to update add-on to the latest 8.0.6 version and check if it works well?

**Comment by dannycolin** [comment]
Closing since 7.1.0 isn't supported anymore. If you still have this issue in Firefox with the latest version of the addon, feel free to open a new bug report.
