### ISSUE TITLE
Backing up configurations/data

### ISSUE THREAD

**Issue by i-like-trains72** [mozilla/multi-account-containers#2334]
Is there any way of exporting configurations for containers? Will this data be cleared upon refreshing Firefox?
Alternatively, is there a way I can back up the data for containers by copying certain files? I am planning on refreshing Firefox, due to it feeling a bit sluggish, and I **really** don't want to lose the data, I have spent a lot of time customizing containers exactly to what I need.

**Comment by achernyakevich-sc** [comment]
Looks like a duplicate of #1427.

I would like to propose to close this one issue and vote +1 in the #1427.

**Comment by i-like-trains72** [comment]
Alright, thanks
