### ISSUE TITLE
Lost containers..   we need a proper sync 

### ISSUE THREAD

**Issue by cwjsmith** [mozilla/multi-account-containers#2338]
Is there a way to sync containers and the websites in those containers ?, I use three computers, and trying to keep all the websites/containers in sync is just too much trouble, my laptop has now lost most of its containers, no idea why they were there yesterday.

**Comment by DesignatedJM02** [comment]
This has been an issue for a while. I have had it for over a year to the point where I've just stopped trying to Sync. Either nothing gets synced, or everything gent's synced. I have the issue, of which I have made an issue report months ago, where when I delete a container and then it should "sync". But the container doesn't get deleted. I have had containers get synced that were there over a year ago of which I have since deleted, but it never gets "deleted" because the container comes back upon a sync on a new device even though I have tried to delete it.

**Comment by castlefox** [comment]
Dumb question but on Firefox Multi-Account Containers add-on settings,  Under Firefox accounts sync > do you have the "Enable Sync" checked off?   

Are you logged into your Firefox account on all 3 computers? 

In the Firefox settings, under the Sync tab, Check on the "Change" button.   Under Choose What to sync,  Do you have the Add-ons checkbox checked off?   If not, you need to turn that on.

**Comment by cwjsmith** [comment]
Hi Castlefox, thanks for replying.
When I say sync the website, I setup a lot of containers and in each container are some websites, I want to be able to copy them across several computers and not have to add each website into the right container.
in answer to your question I do have enable sync  in the multi-account containers settings. 
I also have the addons checkbox ticked. the sync does sync my addons but does not copy the containers and the web urls in them.
My main computer that I had the containers working perfectly, but yesterday had the firefox freeze up and I have had to reinstall firefox so I have lost all the containers and I will need to start again. This is want I wanted to avoid.

**Comment by castlefox** [comment]
My guess that you did not do one of those things selected on one of those machines.  The syncing stuff really needs to get streamlined,  having to do those 3 things on every install of Firefox is so stupid.     I just setup Firefox on a new Ubuntu 22.04 install and I had to log into my Firefox account, turn on sync with multi-containers add-on and then I had log into my Firefox account AGAIN.  

I really wish the Multi account containers gets built right into Firefox.  that way most of those syncing issues to sync my container settings does not get lost. 

I wish I could sync all of my containers and tabs in Firefox and then head home from, and I could open up Firefox at on my mobile or at home, and I could pick up exactly from where I last left off.     But right now Firefox isnt build to have like a single/unified experience across all Firefox instances, regardless if you are using Firefox on an Android phone or Firefox at another location.

**Comment by cwjsmith** [comment]
Hi Castlefox, I completely agree, syncing should be made much simpler with the default being sync all, then be able to exclude any parts you dont want to sync on a single page, before hitting the sync now button.
