### ISSUE TITLE
[RFE] sync to behave nicer with temp-containers

### ISSUE THREAD

**Issue by vbatts** [mozilla/multi-account-containers#2349]
- Multi-Account Containers Version: 8.0.7
- Operating System + Version: debian bullseye
- Firefox Version: 91.8.0esr-1~deb11u1
- Other installed Add-ons + Version + Enabled/Disabled-Status: temporary containers v1.9.2

### Actual behavior

Setup: using firefox from multiple desktops, all with sync'ed profile and sync'ed containers, and with the add-ons of Multi-account-containers and https://github.com/stoically/temporary-containers.

On every new machine I configure firefox and container sync, it installs _all_ containers, including those `tmp` containers already deleted from other machines. (>2000 containers)

The M-A-C menu becomes sluggish to respond with this many containers.

Further, attempting to delete these `tmp` containers from this fresh install takes a couple hours. Sitting at the [`about:preferences#containers`](about:preferences#containers) page, clicking `delete` one a time. This page too is sluggish with this many containers

### Expected behavior

Maybe:
* a pattern to tell container sync to _not_ sync `^tmp[[:digit:]]*` containers
* a management page to purge the containers to be sync'ed
* allow selecting multiple containers at a time to delete in bulk from [`about:preferences#containers`](about:preferences#containers)

### Steps to reproduce
1. use M-A-C and temp containers from more than one desktop, and have container sync
2. install a new firefox and sync the containers
3. try to delete or manage the containers

### Notes
similar to https://github.com/mozilla/multi-account-containers/issues/2076
_updated_: found https://github.com/stoically/temporary-containers/issues/371 already pinned on their repo

**Comment by dannycolin** [comment]
Fixed by #2231.
