### ISSUE TITLE
Provide a way to open a link in a specific container from the outside

### ISSUE THREAD

**Issue by sindresorhus** [mozilla/multi-account-containers#2360]
Many users want to able to make certain links open in specific containers (using a browser picker type app). This could be solved by adding a custom URL scheme where you can specify the container name and the URL as URL search parameters. Ideally, https://github.com/honsiorovskyi/open-url-in-container would be integrated into this extension or a similar system would be added.

**Comment by dannycolin** [comment]
See https://github.com/mozilla/multi-account-containers/issues/2361#issuecomment-1125381134

**Comment by webdev69420** [comment]
+1

**Comment by sindresorhus** [comment]
Moved it to a Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1774127
