### ISSUE TITLE
Accepted/included PR #2296 didn't make it into last release despite being included

### ISSUE THREAD

**Issue by Caligatio** [mozilla/multi-account-containers#2364]
I have no idea how this happened but my accepted PR,  #2296, which is supposed to be included in the 8.0.7 release didn't make it into the built artifacts. The source code zip/tarball both have my change but the built extensions do not have the change.

**Comment by dannycolin** [comment]
Looking at the commits, it seems like it was merged right after the version release.
![image](https://user-images.githubusercontent.com/7339076/172732526-e78e265d-2195-4a7d-8a31-345fe0d00a85.png)

So my guess is it didn't get picked up by the build script for AMO but it did for the build on GitHub. I'll see with the Mozilla staff if we can get a dot release soon-ish.

**Comment by Caligatio** [comment]
I don't understand but v8.0.7 still does not have the fix present. How is this possible?

**Comment by thansk** [comment]
It's been over 5 months, is this ever going to get released?

**Comment by dannycolin** [comment]
What an adventure it was to revive some development on this addon but it's finally live :)
