### ISSUE TITLE
Update devDependencies that have known vulnerabilities

### ISSUE THREAD

**Issue by marperia** [mozilla/multi-account-containers#2394]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. I cloned a repo
2. I ran `npm install --legacy-peer-deps`

### Actual behavior

While the initial set up run the following vulnerabilities are present in node

```
26 vulnerabilities (15 moderate, 8 high, 3 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force
```

### Expected behavior

No vulnerabilities should be present

### Additional informations

Looks like it is a copy of #1261. Should I run `npm audit fix --force` and submit PR?

### Provide a copy of Troubleshooting Information page

```plain text
I suppose you don't need any Information pages
```

**Comment by marperia** [comment]
One important detail: I had to run it three times before there were three "moderate" messages left

**Comment by dannycolin** [comment]
Thanks for the report. I'll look at it this week.
