### ISSUE TITLE
Context Menu Appears Upon Right Clicking

### ISSUE THREAD

**Issue by geedogz** [mozilla/multi-account-containers#2407]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Right click on page
2. Context menu appears

### Actual behavior

Context menu appears when right clicking on a page

### Expected behavior

Context menu should NOT appear upon right click

**Comment by dannycolin** [comment]
What is the context menu you're talking about? Could you share a screenshot?

**Comment by geedogz** [comment]
Hi.. yes, please look at the screen grab circled in red is the issue..

![fb](https://user-images.githubusercontent.com/69818302/185340822-fea82027-6ff3-4b70-b07d-382b17e2c3c7.png)

**Comment by geedogz** [comment]
Did you read my last comment and see my pic?

**Comment by dannycolin** [comment]
> Did you read my last comment and see my pic?

Yes.

**Comment by geedogz** [comment]
Will you fix this in the next update?

**Comment by geedogz** [comment]
Hello??

**Comment by geedogz** [comment]
Can you respond I didnt hear from you

**Comment by dannycolin** [comment]
It is unlikely that I will work on this anytime soon because I'm only a volunteer working on Multi-Account Containers on my free time. Also, this is currently the expected behavior and isn't a bug and that's why I triaged it as a feature request.

In the meantime, a solution would be to use a userChrome.css file and add a CSS rule to it that hides this menu entry. Looking at your screenshot, you seem to already know about what userChrome.css is but just in case I'm sharing a few links that can help:

* https://www.userchrome.org/
* https://www.reddit.com/r/firefoxcss
* https://matrix.to/#/#firefoxcss:mozilla.org

**Comment by winternet-studio** [comment]
This content menu should appear on right-clicking. It should appear only when right-clicking on the tab.

This is especially annoying because we're used to Inspect being the last entry and the brain just automatically click that item - but now that is suddenly no longer Inspect.... 😖

**Comment by geedogz** [comment]
> It is unlikely that I will work on this anytime soon because I'm only a volunteer working on Multi-Account Containers on my free time. Also, this is currently the expected behavior and isn't a bug and that's why I triaged it as a feature request.
> 
> In the meantime, a solution would be to use a userChrome.css file and add a CSS rule to it that hides this menu entry. Looking at your screenshot, you seem to already know about what userChrome.css is but just in case I'm sharing a few links that can help:
> 
>     * https://www.userchrome.org/
> 
>     * https://www.reddit.com/r/firefoxcss
> 
>     * https://matrix.to/#/#firefoxcss:mozilla.org

But it should be a bug since theres no reason it should exist upon right clicking when it should be accessed through the icon popup.

So I tried using CSS but I dont know the exact name of the CSS element and I've tried a few from what I found in Dev Tools. But none of them work. Would you mind telling me the element's name?

.

**Comment by geedogz** [comment]
> This content menu should not appear on right-clicking. It should appear only when right-clicking on a container tab.

Completely agree. I don't know why this annoyance is still not properly addressed. Very strange on the devs' part.

**Comment by geedogz** [comment]
> It is unlikely that I will work on this anytime soon because I'm only a volunteer working on Multi-Account Containers on my free time. Also, this is currently the expected behavior and isn't a bug and that's why I triaged it as a feature request.
> 
> In the meantime, a solution would be to use a userChrome.css file and add a CSS rule to it that hides this menu entry. Looking at your screenshot, you seem to already know about what userChrome.css is but just in case I'm sharing a few links that can help:

Well I hope you can put an end to this annoyance. Would appreciate it.

So I tried CSS but I dont know the exact name of the CSS element that pops up upon right clicking. I've tried a few element names from what I found in Dev Tools. But none of them work. Would you mind telling me the element's name?
