### ISSUE TITLE
Current tab shortcuts reuse reserved MacOS shortcuts

### ISSUE THREAD

**Issue by kerabite** [mozilla/multi-account-containers#2418]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Try opening a Container with Keyboard Shortcut 3 or 4 (Shift-Command-3/4).

### Actual behavior

A screenshot is being taken, because Shift-Command-3 and Shift-Command-4 are [reserved](https://developer.apple.com/design/human-interface-guidelines/inputs/keyboards/#reserved-keyboard-shortcuts) for screenshots.

### Expected behavior

The wanted Container should open.

**Comment by dannycolin** [comment]
As a workaround, you can change the default shortcuts for Multi-Account Containers by following the instructions in https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox.
