### ISSUE TITLE
containers unable to diferentiate alternative accounts on same service, prevents loading

### ISSUE THREAD

**Issue by singingotter** [mozilla/multi-account-containers#2420]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

I attempted to open gmail webmail for a Workspace account.
The Containers Choice screen appears with the option to 'always open in this container', which is unchecked because webmail is use for personal and work containers.
Clicking Open yields a blank screen then after an extended time an error message.
This is a problem because each service uses google services either in Workspace or  a personal account.
Opening gmail webmail in personal account container works.

### Actual behavior

Clicking Open yields a blank screen then after an extended time an error message.

### Expected behavior

Containers should detect whether I'm opening the Work, Personal or Non-profit account associated with the Container.

### Additional informations

this appears to be different from previous bugs which were reported intermittently, or only after cache was full.

**Comment by dannycolin** [comment]
> Clicking Open yields a blank screen then after an extended time an error message.

Do you get a "400 error code"?

**Comment by kurahaupo** [comment]
I think I recall that the ability of the built-in containers to redirect based on the path was removed a while back, so that plug-ins have to provide a filter function if you want to discriminate on anything other than the domain. I don't know if there are any plans to add this to MAC, but I note that currently you can only add a domain to the target list, not a whole URL.

On the other hand, Google Services are generally pretty good about allowing you to have multiple active accounts.

**Comment by dannycolin** [comment]
> I think I recall that the ability of the built-in containers to redirect based on the path was removed a while back

It never was in the builtin feature

> The Containers Choice screen appears with the option to 'always open in this container', which is unchecked because webmail is use for personal and work containers.

@singingotter You can't assign gmail to a container if you want to use it in two different container. To remove the assignment, see https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#remove-always-open-in-site-from-a-container

To use gmail in two container, you need to:
1. Open a new tab in the desired container
2. Go to Gmail and log in
3. Open a new tab in another desired container
4. Go to Gmail and log in

So currently, you can't automate the process. This feature is covered in #1749 and #691. For the error message you got, it's probably #1882.

Closing as duplicate and expected in the currently version.

**Comment by singingotter** [comment]
thanks
regards

Steven Lindsay

Confidentiality Notice: This electronic message is intended exclusively for
the individual or entity to which it is addressed. If you are not
the named addressee, you are not authorized to read, print, parse, retain,
analyse, copy, process or disseminate this message or any part of it. If
you have received this message in error delete all copies.

**Comment by kurahaupo** [comment]
@dannycolin 
> It never was in the builtin feature

Thanks for the correction.
