### ISSUE TITLE
Unable to manage site list a URL is too long

### ISSUE THREAD

**Issue by surreymagpie** [mozilla/multi-account-containers#2421]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

I accidentally added a site to my Work container.

I went to remove it by navigating through Manage Containers > Work > Manage Site List...

However, I cannot remove the site as the trash icon is not visible. I beileve this is because another site added previously has an unusually long URL and the icons are in the overflow to the right.
![Screenshot (1)](https://user-images.githubusercontent.com/5397497/194340917-2177b139-ea15-4fa2-a4c2-88732037f953.png)

### Actual behavior

Other containers are working normally and the trash icon to remove sites are visible at the right edge of the dropdown, eg
![Screenshot (4)](https://user-images.githubusercontent.com/5397497/194341650-1bb47d73-164b-4d07-bcad-43dffce6d3fd.png)

### Expected behavior

If the icon appeared to the left of the URLs, it would be possible to delete them no matter how long the URLs are.

**Comment by dannycolin** [comment]
I fixed and submitted a patch for the bug and I'm waiting for a developer to merge it. 

In the meantime, you can use this workaround:

1. Type `about:debugging` in your addressbar
2. Select *This Firefox* in the left sidebar of the page
3. Search for *Multi-Account Containers* in the list and click on the *Inspect* button.
4. In the new window that opened, go to the *storage* tab
5. In the left sidebar, expand the *Extension Storage* and click on the item revealed.
6. In the column *Key*, search for the domain name you want, right-click on it and choose *delete <the name of the domain>*

Here's a screenshot of what the window looks like:
![ext-storage](https://user-images.githubusercontent.com/7339076/194439036-d1c0571d-f24e-49b6-a13f-d4002858cecb.png)

**Comment by surreymagpie** [comment]
Thank you so much!

That was so prompt and your fix has helped me until your patch gets merged. I would not have found where those settings were stored by myself.

Once again, much appreciated 🥇
