### ISSUE TITLE
“NEW” toolbar icon label is cropped at the right side

### ISSUE THREAD

**Issue by acornestean** [mozilla/multi-account-containers#2430]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Install the 8.1.0 version of Multi-Account Containers
2. Open 100 containerized tabs to trigger the “NEW” label to appear on the toolbar icon
3. Notice the “NEW” label is cropped at the right side.

### Actual behavior

The “New” label which appears on the toolbar icon is cropped at the right side.

### Expected behavior

The label should be fully displayed.

### Additional informations

![2022-10-25_15h05_59](https://user-images.githubusercontent.com/50236075/197771209-3b8800f9-a789-4b83-9a29-8a8652332a39.png)

**Comment by dannycolin** [comment]
Closing since this is a bug with Firefox itself. See https://bugzilla.mozilla.org/show_bug.cgi?id=1423366
