### ISSUE TITLE
Sync – Deleting a container in one browser does not remove the container from the other browser

### ISSUE THREAD

**Issue by acornestean** [mozilla/multi-account-containers#2439]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Install the 8.1.0 version of Multi-Account Containers on 2 browsers and sign in with the same Firefox account on both. Make sure sync is enabled for both instances of the extension. 
2. On browser 1 (B1) create a container
3. On browser 2 (B2) wait for the sync or manually sync and check that the created container appears in the MAC container list
4. On B1, delete the container created at Step 2
5. On B2 wait for the sync or manually sync and check for the presence of the previously deleted container
6. Observe the container is still present on B2 after sync

### Actual behavior

The container which was deleted on B1 still persists on B2 and is not removed i.e. sync does not work with deleted/removed containers.

### Expected behavior

The container which was deleted on B1 should also be removed from B2 after syncing.

### Additional informations

Sync was performed on 2 Nightlies (108.0a1/20221101213659)

**Comment by acornestean** [comment]
@stoically

I tested the currently available public version 8.0.7 and indeed, containers are no longer present on the second Firefox instance after syncing.

However, I’m testing the pre-release version 8.1.0 (https://github.com/mozilla/multi-account-containers/releases/tag/8.1.0) and it seems with this one, containers are still present in the second instance of Firefox after they are deleted from the first one. I followed the instructions you provided in #2240 but to no avail.

I observed that the MAC developer console correctly logs the deleted container (I named it DELETE and I mention this so it can be more easily followed in the console logs).

So as you can see in the image below, the `deletedIdentityList` array on the left (first FX instance) which has data from deleting the “DELETE” container matches what should be on the second instance of FX (on the right). The list of available containers also matches and the “DELETE” container is nowhere to be seen there. 

![2022-11-03_12h39_41](https://user-images.githubusercontent.com/50236075/199721965-b7b2245e-78d6-47a0-9355-7f320aab5490.png)

So far so good. Only issue is that the container is still present in the second instance of FX (see screenshots).

First FX instance:
![2022-11-03_12h40_15](https://user-images.githubusercontent.com/50236075/199722069-1eae11d0-da98-427e-ac42-4412b27f4794.png)

Second FX instance:
![2022-11-03_12h40_25](https://user-images.githubusercontent.com/50236075/199722113-d0e1bfe6-21ee-4bab-b5ac-70e98a9c67cc.png)

The “DELETE” container does not go away and the only way to get rid of it is to manually delete it from the second FX instance.

Now, having the above conditions as a starting point, I added a new container in the first instance of FX, waited a few minutes, synced the second FX and it appears that the newly created container would not show up in the second FX until I manually removed the supposedly deleted “DELETED” container and waited a bit more. I did this a few times and each time I waited around 10-15 minutes to make sure I don’t jump the gun and give the sync a chance to do it’s thing, but the new container would not show up until I manually deleted the “deleted” container on the second FX.

Would you mind having a try at this using the 8.1.0 version please?

**Comment by dannycolin** [comment]
Fixed #2450

**Comment by acornestean** [comment]
Verified as Fixed with version 8.1.1 of Multi-Account Containers. Deleted containers are removed from the second browser instance as expected.

Tested on the latest Nightly and Beta under Windows 10, Ubuntu 16.04 LTS and macOS 11.3.1.
