### ISSUE TITLE
Sync – Renaming/Changing container color/icon on one browser does not rename/change container color/icon on the other browser

### ISSUE THREAD

**Issue by acornestean** [mozilla/multi-account-containers#2440]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Install the 8.1.0 version of Multi-Account Containers on 2 browsers and sign in with the same Firefox account on both. Make sure sync is enabled on both. 
2. On browser 1 (B1) create a container
3. On browser 2 (B2) wait for the sync or manually sync and check that the created container appears in the MAC container list
4. On B1, rename and change the color/icon of the container created at Step 2
5. On B2 wait for the sync or manually sync and check for the changes in name/color/icon of previously synced container
6. Observe the container has the same name/color/icon as when initially synced

### Actual behavior

The container which was re-customized on B1 is not updated on B2

### Expected behavior

The container which was re-customized on B1 should also be updated on B2 after syncing

**Comment by stoically** [comment]
I tried to reproduce but it worked for me on Firefox Developer Edition Version 107.0b8.

At some point while testing the sync feature in MAC wasn't enabled for me, even though I'm sure I clicked on "enable sync" in the welcome cards. I couldn't reproduce this tho.

Could you maybe try reproducing again and double-check the MAC preferences, whether the checkbox for "Sync" is actually checked?

**Comment by stoically** [comment]
Another thing I noticed while testing: It seems that manually clicking sync does not always actually update the Add-on-specific sync storage. It just takes a while – sometimes.

To manually verify, after enabling sync and changing the container: Open the developer console of MAC (about:debugging#/runtime/this-firefox, then click "Inspect") and execute `browser.storage.sync.get().then(console.log)`. Check the JSON output for the changed container. If the container data is including the change, then MAC sync worked and it's now up to Firefox sync to do the job. Click manually sync. Then also check the developer console on the second Firefox instance and see if the storage already updated to the expected state. If not, retry manually clicking sync until it updates.

So this seems to be a sync server inconsistency where manually clicking sync does not update all data.

**Comment by stoically** [comment]
So, if testing MAC sync features: Wait like 5-10minutes after changing container data, then manually click sync and things should work as expected.

**Comment by acornestean** [comment]
@stoically

Thank you for the explanation and tips !

After further testing, indeed the sync works as expected in the case of re-customizing containers.

Also please note that I’m testing the pre-release version 8.1.0 of Multi-Account Containers and not the currently publicly available v8.0.7.

**Comment by acornestean** [comment]
Re-tested on the latest pre-release version 8.1.1 of Multi-Account Containers and the sync is working as expected in the case of re-customizing containers.

Tested on the latest Nightly and Beta under Windows 10, Ubuntu 16.04 LTS and macOS 11.3.1.
