### ISSUE TITLE
"Quick video" is private and not viewable

### ISSUE THREAD

**Issue by mitchplze** [mozilla/multi-account-containers#2443]
### Before submitting a bug report

- [X] N/A ~~I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue~~
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

The [Add-On Store page](https://addons.mozilla.org/en-CA/firefox/addon/multi-account-containers/) for this extension contains a dead link.  

### Actual behavior

In the first paragraph of the "About this extension" section, there is a link to a "[quick video](https://prod.outgoing.prod.webservices.mozgcp.net/v1/a36f68b71d58a83b99fd6f69d3e51575f0cbe5861b5ad0664fea67cdaedcecf8/https%3A//www.youtube.com/watch%3Fv=Gy7lyvAfOSw)" that YouTube reports is private. 

` This is a private video. Please sign in to verify that you may see it. `

### Expected behavior

Video should be made public, or the link and copy removed from the store

**Comment by dannycolin** [comment]
Thanks for the report :). It has been removed since the video was outdated.
