### ISSUE TITLE
when a website opened with a container it request every time to open on the container!

### ISSUE THREAD

**Issue by m3asmi** [mozilla/multi-account-containers#2448]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

when a website opened with a container 

### Actual behavior

it request every time to open on the container!  I had to reinstall the add-on to skip this behavior!

### Expected behavior

Even if check **Remember my decision for this site** it request to open in the container the next time

**Comment by dannycolin** [comment]
> it request every time to open on the container! I had to reinstall the add-on to skip this behavior!

Do you mean reinstalling fixed the issue or you still experiencing it after a reinstall?

**Comment by m3asmi** [comment]
@dannycolin reinstalling maybe just remove some data of the addon, it fixes the issue

**Comment by achernyakevich-sc** [comment]
> Even if check Remember my decision for this site it request to open in the container the next time

@m3asmi
When you ticked "Remember my decision for this site" did you follow to selected container or clicked to continue in container it was earlier?

**Comment by dannycolin** [comment]
You might have accidentally clicked the right button in the confirm page.
![image](https://user-images.githubusercontent.com/7339076/202729040-9e08744e-e55a-4f83-92b0-f0d4eac987fa.png)

**Comment by m3asmi** [comment]
@achernyakevich-sc exactly
