### ISSUE TITLE
Firefox window wrong position at start with tripple screen

### ISSUE THREAD

**Issue by linuxaudiofoundation** [mozilla/multi-account-containers#2452]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. open Firefox, the window show up in first screen and then is moved to the correct position

### Actual behavior

when you open Firefox the window is showing up in first screen and then go to the correct position (last saved)

### Expected behavior

very easy to fix, when creating the window do not show up the window until it is positioned at the correct coordinates, then display it

**Comment by dannycolin** [comment]
> open Firefox, the window show up in first screen and then is moved to the correct position

Do you mean the main browser window or the popup opened when you click the Multi-Account Container icon?

**Comment by linuxaudiofoundation** [comment]
> > open Firefox, the window show up in first screen and then is moved to the correct position
> 
> Do you mean the main browser window or the popup opened when you click the Multi-Account Container icon?

The main window. 
In fact if you put the main window on 2nd monitor, the main window "flash" (show up) in first monitor first and then is sliding on the 2nd one (the last saved position). The main window must be created hidden until it is properly positioned.

**Comment by dannycolin** [comment]
If your issue is related to Firefox main window, you need to ask for help on https://support.mozilla.org/en-US/questions/new/desktop/form. 

For now, I'll close this issue since there's nothing on our side we can do to resolve this.
