### ISSUE TITLE
i18n AMO links in Wiki

### ISSUE THREAD

**Issue by Gitoffthelawn** [mozilla/multi-account-containers#2456]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

This is a simple issue report for the MAC wiki.

On wiki pages such as:  
https://github.com/mozilla/multi-account-containers/wiki/Moving-between-containers

the links would benefit from i18n.  For example, the AMO link to *Context Plus* can have `/nn-no` removed for proper i18n.

If you provide wiki edit permissions to my account, I'll take care of it myself, else someone with wiki edit permissions will need to do it.

### Actual behavior

See STR

### Expected behavior

See STR

**Comment by dannycolin** [comment]
Done :).

**Comment by Gitoffthelawn** [comment]
Thanks Danny. :)
