### ISSUE TITLE
Feature Request: add extension shortcut for sorting tabs by container

### ISSUE THREAD

**Issue by xenoruon** [mozilla/multi-account-containers#2457]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Assign a keyboard shortcut in the _Manage Extension Shortcuts_ section of Firefox Settings.
2. Use the shortcut previously assigned to trigger the _Sort Tabs by Container_ command located in the extension popup.

### Actual behavior

Currently, there is no extension shortcut for triggering the _Sort Tabs by Container_ command; you can only do so via the popup.

### Expected behavior

There should be an option to add an extension shortcut for sorting tabs by container.

### Additional informations

First of all, thank you so much to everyone involved in the development of this add-on!

One of the features I find myself using quite a bit is sorting the tabs by container, and I think it would be really helpful to be able to trigger this action using a keyboard shortcut.

**Comment by xenoruon** [comment]
I created a PR for this: #2458

**Comment by groovecoder** [comment]
The fix for this has been released in https://github.com/mozilla/multi-account-containers/discussions/2672.

**Comment by jayenashar** [comment]
i have about 25 pinned tabs and the order is more or less in muscle memory.  this is important when 7 of them are gmail and have the same icon.  i've pressed the shortcut key twice and completely ruined the order of the tabs.  please disable the shortcut key by default.
