### ISSUE TITLE
Accessibility of <details> for Firefox on Android

### ISSUE THREAD

**Issue by jjsarton** [mozilla/multi-account-containers#2469]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1) create a simple page with h1, details and further simple html elements.
```
...
<h1>Header</h1>
<details>
 </summary>summary</summary>
 <p>Some summary text</p>
</details>
<h2>Title level 2</h2>
<p>Some main text</p>
...
```
2) try this on Android with talkBack

### Actual behavior

The h1, h2 and p element can be reached
The details (summary) is nor seen as having the "focus" as for the other elements.

### Expected behavior

Don't ignore details ...

### Additional informations

Tested with Firefox 107.2.0
I don't know what the Multi-Account Container is!

**Comment by dannycolin** [comment]
Hi,

To report a bug for Firefox for Android, the right GitHub repository is https://github.com/mozilla-mobile/fenix.
