### ISSUE TITLE
Context menu persists after opening another browser tab

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/multi-account-containers#247]
**[Affected versions]:**
-Firefox 51.0.1 and up
-Containers Experiment 0.9.3

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Have Containers Experiment (v0.9.3) installed on a Firefox new profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisite.
2. Open a new tab and visit any website.
3. Right-click on a link from that website.
4. Open a New Tab.

**[Expected result]:**
- Context menu is dismissed when opening a new tab.

**[Actual result]:**
- Context menu persists on the new opened tab. 

**[Notes]:**
- Here is a gif with the issue:
![context menu](https://cloud.githubusercontent.com/assets/9248513/23221193/143b3dfa-f92d-11e6-8ed9-b3e2ec4906fa.gif)

**Comment by groovecoder** [comment]
Are you running with disabled pop-up auto-hide?

<img width="451" alt="browser-toolbox-sticky-popups" src="https://cloud.githubusercontent.com/assets/71928/23222687/8eba4328-f8dd-11e6-91eb-af078b532bdd.png">

**Comment by johngruen** [comment]
@groovecoder can you dig into this one

**Comment by bakulf** [comment]
@groovecoder this is easy to reproduce. Probably you have to dig into platform code.
I can mentor if you want/need and if you have time to take this bug :)

**Comment by jonathanKingston** [comment]
I replicated this, I think this has to do with how we are adding items to the context menu or changing the events on the new tab button. I can look into fixing this.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
