### ISSUE TITLE
Using a Container disables certain keyboard keys

### ISSUE THREAD

**Issue by Ogitto** [mozilla/multi-account-containers#2470]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

(0) On a Lenovo Notebook (T540P) with USB-Keyboard (Trust 21296) attached, running under Linux/XFCE,
(1) I open Firefox 107.0.1 (64-Bit) with tab environments activatet in general settings; 
(2) I open several tabs without using a container: All works well, no problem.

### Actual behavior

(3) I open a new tab WITH container: The Keys     - . , m n  Alt-Gr Fn     become dead. All other keys work;
(4) logout-login and reboot does not restore proper keyboard function, only shutdown and restart does.

### Expected behavior

(5) The mentioned keys should not fall dead when using a container.

### Additional informations

(6) The also availabel add-on 'Firefox Multiaccount-Containers' does not show this error (so far);
(7) the notebook's built-in keyboard is not affected;
(8) The problem first occurred with the previous version of Firefox (as far as I remember).

Update: After removing the downloaded multiaccount-container-addon and reactivating the builtin tab-environments (_with all custom environments gone_), the problem is not reproducable anymore.

**Comment by dannycolin** [comment]
1. Is your keyboard in a different language than English and/or qwerty format?
2. Could you try to reinstall Multi-Account Containers and delete all the default keyboard shortcuts for the extension? See instructions: https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#modify-extension-shortcuts

**Comment by Ogitto** [comment]
Thank you for the response. To your questions:
(1) The mentioned keyboard has a german layout.
(2) The multi-account-addon I installed is inactive. The one in question (the one I encountered the keyboard problem with) seems to be built-in, accessible not via the addon list, but only via 'settings', section 'general settings', under 'tabs'. It does not show up in the list of keyboard shortcuts for extensions, and I do not know a way to add keyboard shortcuts to it (or to delete default ones, should they exist). When I uninstall the downloaded, inactive Multi-Account-Addon, the one accessible via 'settings' is still in place. When I activate the downloaded Multi-Account-Addon, the built-in becomes inactive. Switching between the two deletes all custom containers, by the way.
(3) This firefox version came with Archlinux.

**Comment by dannycolin** [comment]
I think I misunderstood. The problem happens when only the builtin feature is enabled? If it does also happen with the builtin feature, this might be a problem with Firefox itself.

> When I activate the downloaded Multi-Account-Addon, the built-in becomes inactive. Switching between the two deletes all custom containers

It still active under the hood. Multi-Account Containers offers a nicer UI and the ability to assign websites to a specific containers. Currently, the default behavior is to delete all container data when all addons using it are disabled. This is why things are deleted. I've been working with the Mozilla developer to change this behavior but it still is a work in progress.

**Comment by Ogitto** [comment]
Thanks again for your comment. Indeed, the problem only occurred with the built-in feature. It may or may not occur with the download version, since I did not test the latter with as many custom containers and over a similar timespan as the builtin-feature.

Update: The problem has a keyboard-specific component. It disappeared after changing the keyboard (and immediately reappeared after switching back to the Trust keyboard).

**Comment by dannycolin** [comment]
> Indeed, the problem only occurred with the built-in feature.

Since it seems to affect the built-in feature, the best solution would be to report it on bugzilla.mozilla.org. Here's a direct link to the right Product/Component it should be filed in https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Widget%3A%20Gtk

I'll close this bug for now but feel free to ask questions if you need help on filing a bug on bugzilla.mozilla.org.

**Comment by Ogitto** [comment]
As a last note: More testing revealed, that the reported problem is neither related to the add-on 'Multiaccount-Containers' nor to the built-in Environment feature. Sorry for the stolen time! Will do more testing next time before reporting anything. Kind regards, Ogitto.

**Comment by dannycolin** [comment]
> Sorry for the stolen time!

No worries, it's better to waste a little of time than ending up with a major issue that could affect a bunch of users ;)
