### ISSUE TITLE
Content script of webextension operating in a tab using Firefox VPN through multi-account container does not go through vpn. 

### ISSUE THREAD

**Issue by noobLue** [mozilla/multi-account-containers#2483]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Create a container and set it to use a Firefox vpn in some location
2. Create a simple webextension with a content script that checks it's ip from some service. (webRequest to some ip service)
3. Check ip on container tab, it will be the ip address of the country defined in the container's Firefox VPN settings.
4. Check ip from content script, it will be your computers ip.

Check ip with jQuery:

```javascript
var apiKey2 = 'd9e53816d07345139c58d0ea733e3870';
$.getJSON('https://api.bigdatacloud.net/data/ip-geolocation?key=' + apiKey2, function(data) {
console.log(`My ip: ${data.ip}`);
});
```

### Actual behavior

Web requests made from a content script of a random webextension in a containerized tab don't go through the Firefox vpn, that is set up on a multi-account-container.

### Expected behavior

Content scripts that are designed to change the functionality of a webpage should go through the same network as that webpage. The firefox vpn option in multi-account containers should also support the WebRequests from a content scripts of a WebExtensions.

### Additional informations

Not sure if this is an issue with multi-account-container or is limited by Firefox design

**Comment by dannycolin** [comment]
By default, the browser doesn't allow WebExtensions to communicate with each others.

**Comment by noobLue** [comment]
> By default, the browser doesn't allow WebExtensions to communicate with each others.

Yes, thank you. I fixed the problem by injecting the code into the page DOM and the requests went through the vpn :)
