### ISSUE TITLE
After deleting history, "New container tab" is now disabled, no container functionality available

### ISSUE THREAD

**Issue by jernst** [mozilla/multi-account-containers#2484]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Unclear.

### Actual behavior

All container behavior has disappeared. Facebook container does not work any more either. The menu item "New container tab" is disabled. There is no icon in the toolbar.

I have enabled, disabled this extension and restarted Firefox in various combinations; no change.

How do I recover?

### Expected behavior

If I enable the extension, the pulldown menu "New container tab" should become selectable not greyed out.

### Additional informations

This is Firefox 108.0.2 on Apple M1.

**Comment by dannycolin** [comment]
How did you delete the history?

> I have enabled, disabled this extension and restarted Firefox in various combinations; no change.

You might have lost its data because Firefox deletes all containers data when all container addons are disabled.

**Comment by dannycolin** [comment]
> I deleted history in Settings / History and set it to "Never remember history" and "Clear history".

Setting "Never remember history" is the same as browsing in private mode and containers don't support it at the moment. It needs to be added in Firefox itself. 

See: [bug 1320757](https://bugzilla.mozilla.org/show_bug.cgi?id=1320757)

Closing for now.

**Comment by jernst** [comment]
Fair enough. Perhaps add a note somewhere so when people like me poke around everywhere they can find it?

**Comment by dannycolin** [comment]
I'm sure I'll still have people asking me about this but sure I can add it to the documentation tomorrow ;)
