### ISSUE TITLE
Theme support for "open container in" confirmation page

### ISSUE THREAD

**Issue by mathstuf** [mozilla/multi-account-containers#2494]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Prefer a dark theme
2. Open site that asks to open in a container
3. Be blinded at night :) 

### Actual behavior

Container confirmation page is always bright.

### Expected behavior

It should use the "new tab" color (as if `about:blank` at least) if at all possible.

**Comment by dannycolin** [comment]
Hey @mathstuf,

Could you provide the following information please:

* What's your operating system and Firefox version?
* In General > Language and Appearance > Website appearance, what value is set? (auto, light, dark)
<img src="https://user-images.githubusercontent.com/7339076/215623033-fab71885-6a62-4adc-8226-5bbc40533e64.png" width="400">
* Have you enabled `privacy.resistFingerprinting`. You can type about:support in the address bar and look in Important Modified Preferences section.

**Comment by mathstuf** [comment]
- Linux (Fedora 37's package)
- `firefox-106.0.4-1.fc37.x86_64`
- It is Automatic; changing to Dark doesn't change behavior of the extension
- `privacy.resistFingerprinting` is `true`

**Comment by mathstuf** [comment]
Unsetting `privacy.resistFingerprinting` makes it work with Dark. Is there a way to ignore that value for the extension-rendered page?

**Comment by dannycolin** [comment]
> Unsetting `privacy.resistFingerprinting` makes it work with Dark. Is there a way to ignore that value for the extension-rendered page?

In about:addons, select Multi-Account Containers and go to the preferences tab. By default, the theme option is set to auto-detect. You can change to value to force the dark theme.

**Comment by mathstuf** [comment]
Thanks!

**Comment by mathstuf** [comment]
So I've set the theme to Dark, but it seems that `privacy.resistFingerprinting` is still causing it to be the "light" theme. This happened after updating and restarting Firefox, so maybe something changed here?

**Comment by dannycolin** [comment]
I investiguated it a bit more and it seems that there's no way to partially override `privacy.resistFingerprinting` (RFP).

For reference:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1535189
* https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40337

I'll close this bug since it isn't an issue with Multi-Account Containers but something missing in RFP itself. It can only be fixed if Tor or Firefox decide to patch this.

**Comment by mathstuf** [comment]
Thanks for the link. I've filed a new issue by cloning that one asking for RFP to be loosened up in `moz-extension://` pages at least: https://bugzilla.mozilla.org/show_bug.cgi?id=1824467
