### ISSUE TITLE
Changing the proxy setting of a container requires too many clicks

### ISSUE THREAD

**Issue by dehghani-mehdi** [mozilla/multi-account-containers#2495]
### Before submitting a bug report

- [ ] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [ ] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

-

### Actual behavior

-

### Expected behavior

-

### Additional informations

Please add a button to the list of containers to open `change proxy setting form`

Or

Add proxy setting form to `about:preferences#containers` page

**Comment by dannycolin** [comment]
Closing as wontfix because:

* Proxy setting is something that most users set once per container and rarely need to change after that
* We only show the most used/useful options on the main panel so it's easy and fast to manage your container sessions.
