### ISSUE TITLE
Mozilla VPN not recognized on Windows

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/multi-account-containers#2502]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Be signed into Mozilla VPN on Windows
2. Open the MAC addon

### Actual behavior

Mozilla VPN is not recognized. VPN connectivity status icons are not visible.

### Expected behavior

Mozilla VPN is recognized and vpn connectivity is accurately communicated.

### Additional informations

- On Windows this is reproducible with Mozilla VPN v2.13 and v2.14.
- On Windows this is _not_ reproducible with Mozilla VPN v2.13 and the 8.0.4 build of the extension
- Doesn't repro on macos.
- Sounds like it may also happening on Linux. #2330 
...
- Does not reproduce when building and running unsiqned 8.1.1 ... Signature thing?

**Comment by ValentinaPC** [comment]
Verified this on Windows 10, while using the last MAC addon build from main branch and the 2.14.0 (2.202302081239) Mozilla VPN build, and the client is displayed in the addon. Same for Linux, at least for 2.14.
See video below.
![MACext](https://user-images.githubusercontent.com/15685960/217832474-754db377-253e-4782-b5dd-4435e3ecb313.gif)

Am I missing something? @lesleyjanenorton

**Comment by lesleyjanenorton** [comment]
Nope, looks perfect. Thank you! Plot thickens.

**Comment by strseb** [comment]
@lesleyjanenorton , @ValentinaPC - is this still a thing or can we close this ? :D
