### ISSUE TITLE
Many features are gone either due to firefox or plugin

### ISSUE THREAD

**Issue by AztrexDX** [mozilla/multi-account-containers#2518]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1 install latest version of firefox
2- install latest version of extension
3- extension is now coming within search bar
![image](https://user-images.githubusercontent.com/86340924/224764109-3569e30e-d608-4483-8856-2f3d26abcabf.png)

### Actual behavior

Issues
1- Not able to add new container. Earlier there was way to open and add containers
2- Not able to rename or remove container
3- There is issue of not able to remove "Open this site in your assigned Container?"

### Expected behavior

1- Able to add containers. Rename it, remove it
2- Not get continuous prompt to "Open this site in your assigned Container?" when opening a link

**Comment by dannycolin** [comment]
Firefox implemented a new menu for extensions. The right Multi-Account Containers icon is probably hidden in it. See https://support.mozilla.org/en-US/kb/extensions-button?redirectslug=unified-extensions&redirectlocale=en-US

![image](https://user-images.githubusercontent.com/7339076/224768705-88ee1dc5-142b-4b11-9bb0-157f22da33b5.png)

Can you see the puzzle icon in the toolbar? If yes, click on this and in the list you'll find Multi-Account Containers. You can right-click on it and "Pin to toolbar".

**Comment by TheElectronWill** [comment]
yes it's definitely in the new menu. Don't worry, nothing is gone :)
![Capture d’écran du 2023-03-16 19-16-33](https://user-images.githubusercontent.com/10965722/225715734-207ea2d9-4646-475a-adbd-441ae4c92c0c.png)

![Capture d’écran du 2023-03-16 19-16-42](https://user-images.githubusercontent.com/10965722/225715691-d8067749-f947-4e10-80ee-e65deddb899b.png)

**Comment by dannycolin** [comment]
Closing for now but feel free to ask questions if needed.
