### ISSUE TITLE
When sorting the containers in the popup, this order is not passed to the right-click menu in new-tab button

### ISSUE THREAD

**Issue by maagenta** [mozilla/multi-account-containers#2523]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Click the extension icon in the toolbar
2. Click in Manage containers
3. Change the order of the containers

### Actual behavior

Right click in new-tab button and the order of containers is the order in which they were created, not my custom order.

In `about:preferences#containers`, containers are also arranged chronologically, not according to my custom order

### Expected behavior

Right click in new-tab button and the containers are arranged in my custom order.

In `about:preferences#containers`, containers are arranged in my custom order.

**Comment by maagenta** [comment]
After a few minutes, the containers were sorted according to my customized order both in new-tab button and  `about:preferences#containers`

**Comment by dannycolin** [comment]
Duplicate fo #1958
