### ISSUE TITLE
"Open Tab in new Container:" option only appears when tabs are in horizontal layout

### ISSUE THREAD

**Issue by vraravam** [mozilla/multi-account-containers#2545]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Configure 2 or 3 container profiles in FF.
2. I used [this site](https://github.com/ranmaru22/firefox-vertical-tabs) to skin my FF nightly to go for vertical tabs with the Tab Center Reborn extension.
3. Rename the `<FFProfile>\chrome\userChrome.css` file to something else.
4. Restart FF.
5. Right-click on any tab and I see that the context menu when in the horizontal layout, and you will see the menu to open the current tab in any of the containers that were configured in step 1.
6. Now rename the file from step 3 back to `userChrome.css`
7. Restart FF
8. Right-click on any tab - you wont see that context menu

### Actual behavior

Context menu to open the current tab in one of the other containers is missing

### Expected behavior

Context menu to open the current tab in one of the other containers is shown in vertical (sidebar) layout as well.

**Comment by dannycolin** [comment]
This isn't an issue caused by Multi-Account Containers but most likely by the userChrome.css script you're using. You should report it directly to the author of that script.

**Comment by vraravam** [comment]
afaik, css will not suppress the context menu - isn't that right?

**Comment by vraravam** [comment]
yes - after some more digging, looks like this might be from the extension. Will follow up from there, thanks!
