### ISSUE TITLE
Can't imput any characters involving a modifier since commit ef1030789

### ISSUE THREAD

**Issue by leodag** [mozilla/multi-account-containers#2553]
I was testing another issue I will be opening soon, when I noticed I couldn't imput a ':' at all - in none of the text fields. In fact, nothing that needs a modifier was working, even doing Ctrl+v.

Bisecting from the version I'm actually using day-to-day (8.1.2) I reached the commit ef1030789, which changes shortcut handling.

**Comment by dannycolin** [comment]
Good catch. However, this commit isn't in 8.1.2 because it has been merged after it. So it should affect the version on AMO.

**Comment by leodag** [comment]
That's right, it doesn't affect the version on AMO, should have made that clear. I only caught this after pulling the extension while doing the fix for #2556.
