### ISSUE TITLE
"Edit Containers" button is clickable when there a no containers to edit

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/multi-account-containers#256]
**[Affected versions]:**
-Firefox 51.0.1 and up
-Containers Experiment 0.9.3

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Have Containers Experiment (v0.9.3) installed on a Firefox new profile.
-Remove all containers.

**[Steps to reproduce]:**
1. Click on "Containers" button from Toolbar.
2. Click "Edit Containers" button.

**[Expected result]:**
- "Edit Containers" button is grayed out. Nothing happens on click.

**[Actual result]:**
- "Edit Containers" button is clickable and edit menu is displayed.

**[Notes]:**
- Here is a GIF with the issue:

![edit containers](https://cloud.githubusercontent.com/assets/9248513/23257658/7ad5a7a8-f9cd-11e6-9055-99737acab706.gif)

**Comment by jonathanKingston** [comment]
We should probably have a message here. "You don't have any containers, click the add button to get some" or something nicer copy wise etc. @johngruen

**Comment by johngruen** [comment]
@ChenMorpheus maybe we could get a little graphic for when the user has deleted all of their containers?

@jonathanKingston easy fix would be to grey out the button

**Comment by ChenMorpheus** [comment]
@johngruen @jonathanKingston 
I can't think of any scenario which a user wants to delete all containers but do nothing about the empty list. Therefore, I would recommend to disable the delete button when there is only one container left(see attached screen). Is this engineering effort easier than the original proposal?

![2017-03-01 6 25 12](https://cloud.githubusercontent.com/assets/18019946/23455935/7319b48a-feac-11e6-8315-998e6add781f.png)

**Comment by ShivangiKakkar** [comment]
@groovecoder @jonathanKingston  I would like to take this up and possibly land a PR soon. :) May I ?

**Comment by groovecoder** [comment]
Let's disable both the "delete" and "edit" features when the list is empty.

When there is only 1 container left, let the user delete it - they may be trying to destroy all their container cookies completely.

**Comment by ShivangiKakkar** [comment]
> Let's disable both the "delete" and "edit" features when the list is empty.
> 
> When there is only 1 container left, let the user delete it - they may be trying to destroy all their container cookies completely.

Okay. On it! Thanks :)
