### ISSUE TITLE
Search in text area [issue](https://github.com/gdh1995/vimium-c/issues/984#issuecomment-1666559265) 

### ISSUE THREAD

**Issue by niksingh710** [mozilla/multi-account-containers#2560]
[issue](https://github.com/gdh1995/vimium-c/issues/984#issuecomment-1666559265) 
as this issue states that firefox does not allow to search in text area.

**Comment by dannycolin** [comment]
If you want to report an issue with Firefox, please file it at bugzilla.mozilla.org.
