### ISSUE TITLE
Please provide URL to always download the latest version of the xpi

### ISSUE THREAD

**Issue by rungitringit** [mozilla/multi-account-containers#2563]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

I'm configuring an Enterprise [policies.json](https://github.com/mozilla/policy-templates/tree/master) for Firefox and want to include Multi-Account Containers by default.  However I've been unable to find how I can reference the latest .xpi download.

I can see that the current latest is https://addons.mozilla.org/firefox/downloads/file/4058426/multi_account_containers-8.1.2.xpi but I need a "latest" link which always points to the latest version.

I need to produce something like this (which I believe uses the correct ID for this extension):
```
    "ExtensionSettings": {
      "@testpilot-containers": {
        "installation_mode": "force_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/multi_account_containers/latest.xpi",
        "default_area": "navbar"
      }
```
However that URL doesn't exist, I just made it up and have been unable to find the correct URL.

### Actual behavior

For example, the uBlock Origin Extension can be force installed using:

```
    "ExtensionSettings": {
      "uBlock0@raymondhill.net": {
        "installation_mode": "force_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
      }
```
in [policies.json](https://github.com/mozilla/policy-templates/tree/master) but I'm struggling to find the equivalent information for this extension.

### Expected behavior

Could you please provide a "latest" download URL for the latest version of the extension so that it can be added to a firefox policy.

### Additional informations

PS: Might be an idea to add this extension in the example policy files in future to encourage more use!  I love how I can pre-define the Containers for users!

**Comment by dannycolin** [comment]
You made a small typo ;). The right URL is: `https://addons.mozilla.org/firefox/downloads/latest/multi-account-containers/latest.xpi`
