### ISSUE TITLE
Firefox 117.0.1 (64-bit) on macOS deleted all Multi-Account Containers by itself

### ISSUE THREAD

**Issue by vszakd** [mozilla/multi-account-containers#2576]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Create containers
2. Use Firefox for weeks or months
3. Reboot the system 
4. It will randomly happen

### Actual behavior

All containers are lost.

### Expected behavior

No containers are lost.

### Additional informations

I guess the trigger is rebooting the system without first closing Firefox, but might be something else.

Last updated happened Sep. 12th to 117.0.1.

It had happened another time, too about 1 month ago but I did not record the version number.

**Comment by dannycolin** [comment]
Hm, I haven't heard of any similar issue with Multi-Account Containers on MacOS and I don't have an Apple device to test further. 

As a suggestion, you could try asking on [Firefox support forum](https://support.mozilla.org/questions/new/desktop/form or on [Mozilla chat platform](https://chat.mozilla.org). If you never used the chat platform, there's instruction on https://wiki.mozilla.org/Matrix#Getting_Started to help getting you started. Hope it helps and if I hear anything I'll make sure to report back here.
