### ISSUE TITLE
Address bar menu button too dark with Firefox dark theme

### ISSUE THREAD

**Issue by bbhtt** [mozilla/multi-account-containers#2585]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Install latest Firefox Nightly 
2. Install Multi Account Containers extension
3. Switch Firefox to dark theme
4. See that the bookmark button is too dark (see image)

### Actual behavior

Poor contrast, hard to see

### Expected behavior

Should be white

### Additional informations

![image](https://github.com/mozilla/multi-account-containers/assets/62639087/77be67e9-5744-4353-b260-91dbf6c7ac96)

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1859137

I opened an issue here since it comes from the addon. Not sure what needs to change.

**Comment by emilio** [comment]
This can be close. This was fixed in the extension in #2584, but the other thing is a Firefox issue.

**Comment by dannycolin** [comment]
Closing. See https://bugzilla.mozilla.org/show_bug.cgi?id=1859137 :)
