### ISSUE TITLE
Unable to create custom labled or named containers

### ISSUE THREAD

**Issue by jnz86** [mozilla/multi-account-containers#2586]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

I click on the MAC button at the address bar.

A box appears with Work, Personal, Banking, Shopping and nothing else.

I can not seem to create custom labels. 

The software appears to work but I have to use one of those four labels only. 

New install on Linux Mint 21.2

### Actual behavior

![Screenshot from 2023-10-16 14-19-23](https://github.com/mozilla/multi-account-containers/assets/26825637/684fe245-818a-4899-bcd8-9a487bee1320)

### Expected behavior

![image](https://github.com/mozilla/multi-account-containers/assets/26825637/fb65c78a-89bb-4ea3-9adb-8741a61d2b67)

### Additional informations

I tried removing the extension and re-installing.

**Comment by dannycolin** [comment]
This isn't a bug. Firefox, in recent versions, moved extension icons in an extension menu. See: https://support.mozilla.org/en-US/kb/extensions-button#w_manage-extensions for how to get to your extension list and pin it back to the toolbar.

**Comment by jnz86** [comment]
Wow. That makes me feel dumb even though it is completely unintuitive. Closed.

**Comment by dannycolin** [comment]
No worries. You aren't the only one who got confused by this change ;).
