### ISSUE TITLE
Containers panel is narrowed when the "Containers" button is moved in the Firefox menu

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/multi-account-containers#259]
[Affected versions]:
- Firefox 51.0.1 and up
- Containers Experiment 0.9.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have Containers Experiment(v0.9.3) installed on a Firefox new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Click the "Containers" button and observe the doorhanger size and items.
3. Right-click on the "Containers" button from the toolbar and select the "Move to Menu" option from the doorhanger.
4. Click the Firefox menu from the main toolbar.
5. Click on the "Containers" icon and observe again the panel size and items.

[Expected result]:
- The "Containers" panel its items are fully displayed.

[Actual result]:
- The "Containers" panel is narrowed getting the items from the right side out of the view.

[Notes]:
- You have to use the horizontal scrollbar in order to view the right side of the items in the "Containers" panel.
- As a side issue, the "Edit Containers" button gets an unneeded extra space under it.
![containers_send_to_menu](https://cloud.githubusercontent.com/assets/20083658/23267341/1c2bbf82-f9f3-11e6-9985-ebc052229298.gif)

**Comment by bakulf** [comment]
@jonathanKingston, is this something for you?

**Comment by jonathanKingston** [comment]
I can take this yeah, it likely might be a painful fix though. Will look into and report back.

**Comment by lmorchard** [comment]
FWIW, we dealt with this on the Snooze Tabs experiment [with a hack that adds a CSS class name to the body element on detecting the narrow width](https://github.com/bwinton/SnoozeTabs/blob/master/src/popup/snooze-bootstrap.js#L2) and [adding styles](https://github.com/bwinton/SnoozeTabs/commit/6857c186e091bf63e3281290f7e179caa071d15c#diff-6dee8eccb766ad0dda73480a14789d8aR609) to adjust from there. Didn't seem like media queries worked, and the toolbar-vs-menu resizing seemed a bit quirky.

**Comment by groovecoder** [comment]
@iillx yes, you can work on this one. Be sure to check out [the patch that @lmorchard linked in the comment above](https://github.com/bwinton/SnoozeTabs/blob/master/src/popup/snooze-bootstrap.js#L2) - it may help.

**Comment by nataliyah123** [comment]
@groovecoder and @maxxcrawford . can I try this .

**Comment by maxxcrawford** [comment]
@nataliyah123 Yes! This issue is yours. Be sure to checkout the patch @groovecoder mentioned above.

**Comment by nataliyah123** [comment]
@maxxcrawford . ok

**Comment by nataliyah123** [comment]
@maxxcrawford . 
[https://github.com/bwinton/SnoozeTabs/blob/master/src/popup/snooze-bootstrap.js#L2](url). the link in the @groovecoder not working . but I am trying to read it through Imorchard

**Comment by nataliyah123** [comment]
@maxxcrawford . when I ran the project and right clicked the containers it(the dropdown) does not have any option move to menu . I made an account and tried to login to pilottest and saw that it was closed in jan.

**Comment by maxxcrawford** [comment]
@nataliyah123 Would you like to work on a different issue instead? Not sure if I'm following you. If you want, please open a PR with your code and we can review it.

**Comment by maxxcrawford** [comment]
@nataliyah123 Following up on this. Thanks!

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
