### ISSUE TITLE
Add option to "always open in no container"

### ISSUE THREAD

**Issue by davidgamba-au** [mozilla/multi-account-containers#2603]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. When I click a github link from slack firefox is opening the github container I use for my personal github account.
My personal github container has no entries in its always open in container list so this shouldn't be hapenning.
2. There is no way to force a tab to always open in the no container container.

### Actual behavior

See repro

### Expected behavior

Add option to allow alway opening in no container

**Comment by Nothing4You** [comment]
While this feature may be interesting on its own, your specific issue is likely related to https://bugzilla.mozilla.org/show_bug.cgi?id=1874599

**Comment by strigona** [comment]
It looks like there is now a config to toggle this behaviour, but if I'm reading it correctly, it's slated for release 124, which has a release date of March 19: https://whattrainisitnow.com/calendar/

**Comment by simmel** [comment]
I've tried with `123.0+build2-0ubuntu0.22.04.1~mt1` from the [ppa](https://launchpad.net/~mozillateam/+archive/ubuntu/ppa) on jammy (with Firefox Multi-Account Containers 8.1.3) and:
* Starting a new "Personal" container and entering URL https://example.com and pressing enter
* Running `xdg-open https://example.com`
still opens https://example.com in a new "Personal" container and not in "Current tab"/No container.

Further more:
* Closing the tab with the "Personal" container that has https://example.com open
* Running `xdg-open https://example.com`
opens the `Open this site in your assigned Container?` page even though I never assigned that site to the "Personal" container.

Even further more:
* On the `Open this site in your assigned Container?` page if I select `Remember my decision for this site` and press `Open in current tab`
* Close the tab
* Open a new tab and surf to https://example.com I get the `Open this site in your assigned Container?` again.

**Comment by strigona** [comment]
I know it's tangential to this particular ticket, but the Firefox change/fix has been bumped up to v123 which will be released Feb 20.

> While this feature may be interesting on its own, your specific issue is likely related to https://bugzilla.mozilla.org/show_bug.cgi?id=1874599


Back on topic, even without the Firefox heuristics, I do strongly think Multi-Account Containers needs the option to "Always open in no container".

**Comment by endolith** [comment]
When a tab is in a container, I can click on Always Open This Site In... but there's no option for "default container", only other containers.

**Comment by il2020** [comment]
I really need this feature.

**Comment by dcormier** [comment]
This was closed, but I see no way to always open a given side in the default (no) container.

**Comment by endolith** [comment]
Why was this closed?  There is no option to always open in no container.
