### ISSUE TITLE
Keyboard shortcuts conflict with and shadow macOS screenshot shortcuts

### ISSUE THREAD

**Issue by matthurne** [mozilla/multi-account-containers#2629]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Install the multi-account container extension in Firefox on macOS
2. Press Shift-Command-3, Shift-Command-4, Shift-Command-5, or Shift-Command-6

### Actual behavior

The relevant [macOS screenshot functionality](https://support.apple.com/guide/mac-help/take-a-screenshot-mh26782/mac) for the shortcut entered is not triggered by the previous step, because the shortcut is captured by the multi-account container extension instead. This is the case even if the extension is configured to take no action for any keyboard shortcut by selection "None" for each "Container to open with Keyboard Shortcut #" setting in the extension's preferences.

### Expected behavior

The current actual behavior makes sense given the configurability currently offered by the extension, but I would like the ability to disable keyboard shortcuts for the extension entirely, or the ability to configure different keys for the shortcuts, so that the default macOS screenshot shortcuts can be used in tandem with the extension.

### Additional informations

I believe currently the only workaround for this issue is to disable/uninstall the extension.

**Comment by matthurne** [comment]
Apologies, I believe I was mistaken. I discovered immediately after submitting this issue that the macOS screenshot keyboard shortcuts were all disabled in my System Settings, for an unknown reason. After restoring them and re-enabling the multi-account containers extension, they are working even with Firefox open. In fact, even with the extension configured to open a tab in a given container for each of the relevant shortcuts, pressing the shortcut triggers the screenshot app, not the extension behavior!

**Comment by dannycolin** [comment]
You might also be interested by https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox. It explains how to modify extension shortcuts in Firefox.

**Comment by matthurne** [comment]
@dannycolin That is great info, thank you!
