### ISSUE TITLE
Context menu entry "Open in new tab in environment" and created environments are still there after removal

### ISSUE THREAD

**Issue by nesingho** [mozilla/multi-account-containers#2632]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Installed Multi-Account Containers
2. Edited some of the default environments and added some new
3. Deinstalled Multi-Account Containers
4. Context menu entry on tabs is still there
5. After reinstalling Multi-Account Containers my edited and added environments are still there
6. After re-deinstalling Multi-Account Containers it is the same as 4.

### Actual behavior

After removing Multi-Account Containers I found that the context menu entry "Open in new tab in environment" is still there.
After reinstalling Multi-Account Containers I found that my former created or edited environments where still there.
I deleted all of them ...  after removing Multi-Account Containers I found that the context menu entry "Open in new tab in environment" is still there now with an empty environment menu...

Any solution without deleting or cleaning my whole profile?

Thanks.

### Expected behavior

No context menu entry or other configuration or other data related to this addon should survive after removing the addon

**Comment by dannycolin** [comment]
You need to disable container tabs:

1. Uninstalling Multi-Account Containers
2. Go to Setting > General
3. Untick "Enable Container Tabs" checkbox

![image](https://github.com/mozilla/multi-account-containers/assets/7339076/272d51e1-1847-4b4e-abdc-e3cb1be56625)

**Comment by nesingho** [comment]
Thanks very much! It worked
But what about still remaining container entries? Where can I find them to delete?

Thanks

**Comment by dannycolin** [comment]
You can either click on the "Settings..." button or manually type "about:preferences#container" in the URL bar to access the builtin container page.

**Comment by bakulf** [comment]
The reason why this bug happens is that the "real" container storage is in firefox and not in the add-on. Disabling/Uninstalling the add-on does not impact the created containers.
