### ISSUE TITLE
mutil account tabs start BroadcastChannel event not work

### ISSUE THREAD

**Issue by abj3ct10n** [mozilla/multi-account-containers#2639]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. create A&B tab account containers.
2. A & B website listen BroadcastChannel event.
3. A & B website BroadcastChannel event not work/not communicate

### Actual behavior

use mult account open A & B containers, open www.domain.com website. BroadcastChannel event not work/not communicate

### Expected behavior

not use mult account open www.domain.com website. BroadcastChannel event work success.

**Comment by bakulf** [comment]
This bug is invalid. The purpose of Container is to create separate contexts. If we allow BroadcastChannel cross-container, this is a tracking vector that would break the container isolation.
