### ISSUE TITLE
Clicking the Page Shot button in a container tab loads the Page Shot install page instead of "My Shots" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/multi-account-containers#264]
[Affected versions]:
- Firefox 51.0.1	
- Containers 0.9.3
- Page Shot 5.2.201701261751

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have Containers and Page Shot add-ons installed through Test Pilot on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Open a new container tab and click the Page Shot button from browser toolbar.
3. Observe the browser behavior.

[Expected result]:
- You are redirected to "My Shots" page where all the saved shots are displayed.

[Actual result]:
- You are wrongly redirected to the install Page Shot add-on page.

[Notes]:
- This issue also affects a saved shot preview page if it's open in a new container. The saved shot preview page will be displayed as the Page Shot add-on is not installed.
- Here is a screen recording with the issue: https://goo.gl/7hFzBN

**Comment by TanviHacks** [comment]
We've moved out of test pilot and are an addon of our own.  So closing this.
