### ISSUE TITLE
Missing "Manage Containers" button

### ISSUE THREAD

**Issue by cwells** [mozilla/multi-account-containers#2644]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Installed extension in fresh install of Firefox
2. Clicked on icon
3. See a list of default containers but no other options
![Screenshot from 2024-06-20 11-06-32](https://github.com/mozilla/multi-account-containers/assets/28466/af566fb6-15f8-4f9e-b7ca-75e438a4427f)
4. There is also no such option in the extension settings

### Actual behavior

Unable to modify/add containers

### Expected behavior

Should be able to add/modify containers

### Additional informations

I've used this extension successfully several years ago, but have been using Chrome/Brave for some time. Came back to Firefox hoping to use this extension, but no luck.

**Comment by achernyakevich-sc** [comment]
@cwells You used wrong button. :)

Button in the URL line is only for marking URL as `Alway Open This Site in...`. What you need - use other button, see screenshot:
![image](https://github.com/mozilla/multi-account-containers/assets/24388336/9f7eb700-25f5-493c-8f99-98d03e66f906)

If this is not available on toolbar then probably it is hidden under `Extentions` button in toolbar.

If this advice helps then could you close this issue as it is not a bug. :)

**Comment by cwells** [comment]
Fantastic, thanks for the quick reply.
