### ISSUE TITLE
Can't see the full name of the container

### ISSUE THREAD

**Issue by naveen1583** [mozilla/multi-account-containers#2647]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Open a website
2. Can't see the full container name unless hover the mouse on the half name.

### Actual behavior

The containers are working fine, but it doesn't display the full name of the container. 

### Expected behavior

Earlier it used to show the full name of the container.

**Comment by dannycolin** [comment]
This is a change in Firefox. See https://github.com/mozilla/multi-account-containers/issues/2641#issuecomment-2174374989 for more information.

**Comment by joraff** [comment]
What was the outcome of this? Is this issue closed without a fix, or is there more discourse or commentary somewhere else? 

I see two tasks completed, but not the task information.

**Comment by dannycolin** [comment]
@joraff did you read [#2641 (comment)](https://github.com/mozilla/multi-account-containers/issues/2641#issuecomment-2174374989)?
