### ISSUE TITLE
After Container tabs are moved to a new window, the focused tab loses its URL

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/multi-account-containers#265]
[Affected versions]:
- Firefox 51.0.1
- Containers 0.9.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Containers add-on is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://en.wikipedia.org/wiki/Main_Page and open a few links in container tabs. (eg. Personal)
3. Click the "Containers" button from the browser toolbar.
4. Click the arrow next to the previously used container and choose to "Move tabs to a new window".
5. Observe the Address Bar.

[Expected results]:
- The page URL is displayed in the Address Bar.

[Actual results]:
- The page URL is no longer displayed in the Address Bar.

[Notes]:
- If you focus a different tab and then re-focus the previous one the URL is correctly displayed in the Address Bar.
- Here is a screen recording with the issue:
![the focused tab loses its url after container tabs are moved to a new window](https://cloud.githubusercontent.com/assets/18304511/23307535/9ef2e52c-fab0-11e6-83e4-78bbdaa14c51.gif)

**Comment by johngruen** [comment]
Fix would be not to focus URL bar after move

**Comment by TanviHacks** [comment]
Don't focus url bar after move.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
