### ISSUE TITLE
Typing 1 in search containers field opens a new tab

### ISSUE THREAD

**Issue by flodolo** [mozilla/multi-account-containers#2650]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Click the extension icon, type 1 in the `Search container name` field.

### Actual behavior

A new tab with the first container is opened.

### Expected behavior

Search for containers with the letter `1` in their name.

**Comment by dannycolin** [comment]
Note: This has been fixed by #2587 and merged in main but we haven't cut a release containing it yet. @rafeerahman Do you have an idea when a release will be made?

**Comment by rafeerahman** [comment]
> Note: This has been fixed by #2587 and merged in main but we haven't cut a release containing it yet. @rafeerahman Do you have an idea when a release will be made?

We're aiming for the week of August 19th as its MozWeek next week.

**Comment by bakulf** [comment]
It's landed!
