### ISSUE TITLE
Icons in Extension & Context Menus Have Poor Contrast in Dark Mode

### ISSUE THREAD

**Issue by smhatc** [mozilla/multi-account-containers#2660]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Switch to dark mode system-wide.
2. Open Firefox.
3. Install the containers extension.
4. Open right-click context menu and collapsed extensions menu.

### Actual behavior

The extension icon in the collapsed extensions menu and the right-click context menu still uses a dark color even when the user is using dark mode. With no white outline or anything, this could pose potential accessibility problems.

### Expected behavior

The icons in the collapsed extensions menu and the right-click context menu should both use a theme or outline which makes them easier to interact with for users using a dark theme.

### Additional informations

This does not seem to be the case for the toolbar pinned icon or the icon which appears in the URL bar, which both use the appropriate icon color depending on the user's theme.

### Provide a copy of Troubleshooting Information page (optional)

```plain text
Operating System: Windows 11 23H2
Firefox Version: 129.0.2
```

**Comment by dannycolin** [comment]
@smhatc Any chance you could share a screenshot of the issue?

**Comment by smhatc** [comment]
> @smhatc Any chance you could share a screenshot of the issue?
Context menu:
![image](https://github.com/user-attachments/assets/2fab0872-8862-43bc-9d00-a24dc6d2970d)
Extensions menu:
![image](https://github.com/user-attachments/assets/e84c6538-7f4e-43b8-a7cf-1d23bdf68432)
