### ISSUE TITLE
Cannot use socks5:// URIs 

### ISSUE THREAD

**Issue by alexolog** [mozilla/multi-account-containers#2669]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Verify that you can set up a SOCKS4 proxy for a container:

![image](https://github.com/user-attachments/assets/1881bb52-ccbe-45ab-8f7c-d9cd4e8cf9e0)

2. Try entering a SOCKS5 URL and clicking on "Apply to Container":

![image](https://github.com/user-attachments/assets/49e74948-5d32-4a13-bb49-147c84870307)

### Actual behavior

No `socks5://...` url is accepted

### Expected behavior

`socks5://...` urls should be accepted

**Comment by achernyakevich-sc** [comment]
@alexolog Why just do not use `socks://`?

For me it works well.

**Comment by LurkerHub** [comment]
Good to know, I'll try that.
Still a bug IMHO, since `socks5://` should work as well

**Comment by alexolog** [comment]
> @alexolog Why just do not use `socks://`?
> 
> For me it works well.

Interesting.

What is the definitive URI protocol?  I could not find it.

**Comment by achernyakevich-sc** [comment]
> > @alexolog Why just do not use `socks://`?
> > For me it works well.
> 
> Interesting.
> 
> What is the definitive URI protocol? I could not find it.

@alexolog I do not remember where I have found but I use it for few years as `socks://localhost:3131` for SSH connection having dynamic port (3131) forwarding. Probably I searching it in the add-on source code. I really do not remember.

**Comment by bakulf** [comment]
This bug is invalid. The right scheme for Socks5 URLs is `socks` and not `socks5`.

**Comment by brian6932** [comment]
> This bug is invalid. The right scheme for Socks5 URLs is `socks` and not `socks5`.

This is just wrong, I use 3proxy, and it uses `socks5://`. Firefox and Chromium's native proxies work with and use `socks5://`, but this addon doesn't.

Curl: https://github.com/curl/curl/blob/master/docs/cmdline-opts/_PROXYPREFIX.md
Chromium: https://github.com/chromium/chromium/blob/main/net/docs/proxy.md
