### ISSUE TITLE
Items from "List all tabs" drop-down menu are hidden if "New Container Tab" option is hovered

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/multi-account-containers#267]
**[Affected versions]:**
-Firefox 51.0.1 and up
-Containers Experiment 0.9.3

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Containers Experiment (v0.9.3) is installed on a Firefox new profile.
-Open multiple tabs with websites (container tabs and normal tabs) so that the "List all tabs" button is displayed near the "New Tab" button.

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisites.
2. Click on "List all tabs" button.
3. Click or hover on "New Container Tab" button from the drop-down menu.
4. Hover the mouse cursor over other websites displayed in "List all tabs" drop-down menu.

**[Expected result]:**
- Any tab can be hovered and selected. "List all tabs" drop-down menu with all tabs is still displayed after the  "New Container Tab" button has been hovered.

**[Actual result]:**
- Only the options above "New Container Tab" button are displayed. All other options and websites are not shown but the drop-down menu persists.

![list all tabs menu](https://cloud.githubusercontent.com/assets/9248513/23309009/ba4be3aa-fab5-11e6-8ed4-e8de51480476.gif)

**Comment by johngruen** [comment]
Current status: we might take out that new container tab thing anyway.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
