### ISSUE TITLE
Enhancements: About: New Temporary Containers How to Make them Great or much better?

### ISSUE THREAD

**Issue by Utone** [mozilla/multi-account-containers#2700]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Try to Open in New Temporary Container without opening the container view.

### Actual behavior

Currently only avaiilable when Container Tab Groups menu is open
<img width="430" alt="Screenshot 2024-12-12 at 21 04 39" src="https://github.com/user-attachments/assets/c1559321-b033-4e32-aa6c-a58d0e2607de" />
<img width="453" alt="Screenshot 2024-12-12 at 21 04 56" src="https://github.com/user-attachments/assets/82a888f5-503f-410a-9c62-28a3d7914b49" />

Not from any other contexp menu, from a Container, container less tab, the + or the V drop down 
Only in top bottom 
<img width="1351" alt="Screenshot 2024-12-12 at 22 06 09" src="https://github.com/user-attachments/assets/c3899d1d-9a28-4b17-9c11-6a354e686a38" />
menu when we open puging window

Maybe ass to top of lists like here:
<img width="343" alt="Screenshot 2024-12-12 at 22 07 44" src="https://github.com/user-attachments/assets/2f5de341-8a4c-4a97-9007-5ab036c0e9cb" />

Also can we assign a region or random location to Temp containers?

### Expected behavior

Not to take a while to find these buttons hidden away as Icon only in top right
<img width="136" alt="Screenshot 2024-12-12 at 22 16 31" src="https://github.com/user-attachments/assets/54ebbf4d-4322-4af3-b6cd-54cee64069b4" />
<img width="212" alt="Screenshot 2024-12-12 at 22 17 42" src="https://github.com/user-attachments/assets/5cd107f7-974b-4206-9e0f-bc67ebaea1f7" />

### Additional informations

<img width="608" alt="Screenshot 2024-12-12 at 22 19 14" src="https://github.com/user-attachments/assets/9b441f7c-d5df-43da-bbe5-286ec88f2c9f" />
Maybe include iit here too

Also it would be great if a Temporary container could get assigned a random location from Mozilla VPN

And in Preferences a checkbox Always Automatiically clean cookies of Temporary folders? 
[Currently it keeps them]
A way to assign Temp containers to a folder to have them where you'd expect or want them:
<img width="1663" alt="Screenshot 2024-12-12 at 22 56 43" src="https://github.com/user-attachments/assets/34c5f788-7dd6-4b34-b2b1-fc39d9c6b56a" />

**Comment by Utone** [comment]
Can we collectall temps and clear them too?
<img width="447" alt="Screenshot 2024-12-12 at 23 56 12" src="https://github.com/user-attachments/assets/0f01b27f-c792-48c9-bebe-e25d11514a67" />
Like export to another About:profiles for using without VPN?

**Comment by dannycolin** [comment]
I think you posted in the wrong place. This is the Multi-Account Containers issue tracker but the addon you're referring to is Container Tab Group. I looked on addons.mozila.org and their GitHub repository is https://github.com/menhera-org/TabArray.

Closing for now.

**Comment by Utone** [comment]
> I think you posted in the wrong place. This is the Multi-Account Containers issue tracker but the addon you're referring to is Container Tab Group. I looked on addons.mozila.org and their GitHub repository is https://github.com/menhera-org/TabArray.
> 
> Closing for now.

Ooops sorry!
