### ISSUE TITLE
See if there is a bug in moving tabs in other test pilot addons

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/multi-account-containers#273]

**Comment by groovecoder** [comment]
Confirmed that Pulse has its bug when moving tabs even without Containers experiment installed. @bakulf - did we already file an upstream issue or bug for this `adoptTab` problem? If we have already filed it somewhere, I'm happy to close this issue on our side.

**Comment by bakulf** [comment]
I don't think we need to file a bug for adoptTab()
I think the bug is in the addons, not able to deal with tab-moving. About testing other test-pilot addons, @groovecoder, do you have time to do it?

**Comment by groovecoder** [comment]
Neither Snooze Tabs nor MinVid have issues when moving to new window.

Only Pulse and Containers have an issue when moving their tabs to new windows.

Do we want to call this issue closed, or what is the follow-up now that we know those test pilot addons have bugs?

**Comment by groovecoder** [comment]
@bakulf I'm tempted to just close this now ... not sure what we can do about it?

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
