### ISSUE TITLE
Moving a single container tab to a New Window wrongly opens a 2nd New Tab

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/multi-account-containers#297]
[Notes]:
- The issue is not reproducible on the latest Nightly and it seems to have been fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1303113.
- The issue is only reproducible if you are moving a single tab to a new window.

[Affected versions]:
- Firefox Release, Beta and Aurora
- Containers 1.0.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Tab Center and Containers add-ons are installed on a new clean profile. ([download Tab Center](https://drive.google.com/open?id=0B8ICzPJynbchLUdHYUlCWUEzcUE)) ([download Containers](https://drive.google.com/open?id=0B8ICzPJynbchQks2OGpCZEZQLTA))

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a new container tab. (eg. Personal)
3. Click the "Containers" button from the browser toolbar.
4. Click the arrow next to the previously used container and choose to "Move tabs to a new window".
5. Observe the number of tabs in the newly opened window.

[Expected results]:
- One tab is displayed in the new window.

[Actual results]:
- Two tabs are displayed in the new window.

[Additional Notes]:
- Here is a screen recording with the issue:
![two new tabs tc and containers](https://cloud.githubusercontent.com/assets/18304511/23460436/1109197a-fe8e-11e6-9cb3-1b3cdc758f4a.gif)

**Comment by groovecoder** [comment]
This also only affects Firefox with Tab Center experiment also installed. So I'm marking this as a Sprint bug - not MVP.

One possible "fix" is to add Tab Center to the incompatible add-ons list, which will disable the "move" feature when Tab Center is installed.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
