### ISSUE TITLE
Reset cache/cookies of containers without deleting them

### ISSUE THREAD

**Issue by pollti** [mozilla/multi-account-containers#303]
It would be great to have an option to delete a container's data (cache/cookies/...) without recreating the container.

**Comment by maxnordlund** [comment]
This also ties in to the cookie deletion modal inside the settings. As far as I can tell, deleting a cookie there deletes it in all containers. Which means I need to login into all my accounts in various containers, which is rather unfortunate.

Perhaps more concretely, I would like to wipe all (or some) cookies from the default container leftover from setting up the various containers. I.e. visited github in default before assigning it to "work". Now every time I visit some other site, GitHub can potential track me.

Related, but not for this issue, is the ability to block cookies in some containers. See #1193

**Comment by AdKiller** [comment]
The option to delete cache and cookies of a specific container is a must.

**Comment by oneEyedCharlie** [comment]
Um, when will this get fixed?  It's been 18 months?

**Comment by jbyler** [comment]
I assumed when using the "Clear Cookies and Site Data..." button that only cookies and site data from the current container would be affected.  When I discovered that cookies from other containers were also deleted, it made me wonder if the multi-account containers add-on was actually segregating cookies at all.  After doing some research I believe that the problem is just with clearing cookies, not with setting cookies—but I want to emphasize the potential for losing trust with users if the "Clear Cookies and Site Data" feature does not respect containers.

**Comment by lhorace** [comment]
> but I want to emphasize the potential for losing trust with users if the "Clear Cookies and Site Data" feature does not respect containers.

I'm a bit dubious using the  '(dis)trust', nevertheless, I agree with the premise of the argument (feature request).

**Comment by activescott** [comment]
Combined with  #1346 this would be very powerful. I want to allow new sites/pages to open in a default container and only open a site in a container with my cookies in it when I explicitly choose too. Then periodically delete cookies from the default container (or on a policy like every day or on FF close).

**Comment by NeatWolf** [comment]
Duh, I can't believe this hasn't been implemented yet?

How am I supposed to clean my cache of a container if it gets broken?
I'm surprised this essential feature is missing!

**Comment by cruzzer** [comment]
Dear Mozilla Team. 

This would be a highly appreciated feature.
For example add a drop-down menu in the "Clear All history" dialog for selecting the container, including the default container. This would allow clearing only that specific container.

As of now, we have to clear the history of all containers and then re-login to the websites of that container. In my case, I would like to more often clear the history of my default container, but leave my specific containers untouched.

**Comment by Joseei** [comment]
> 
> 
> Dear Mozilla Team.
> 
> This would be a highly appreciated feature.
> For example add a drop-down menu in the "Clear All history" dialog for selecting the container, including the default container. This would allow clearing only that specific container.
> 
> As of now, we have to clear the history of all containers and then re-login to the websites of that container. In my case, I would like to more often clear the history of my default container, but leave my specific containers untouched.

This 100%. I'd love to have some containers where the cookies are never cleared (so to stay logged in), even when I clear all history/cookies from the "Privacy & Security" menu and also vice versa where I can delete cache/cookies inside a certain container if need be. There needs to be options and flexibility.

**Comment by dbm1175** [comment]
Absolutely agree here.  The Multi-Account Containers combined with the ability to automatically destroy all cookies for one of the containers when you exit or on a periodic basis (24-hours?) would be a great addition.  I've found "Cookie Quick Manager" that allows me to do this manually, but I'd love to see it built in as a "self destructing container" feature.

**Comment by do-adams** [comment]
Seconding this feature request. This capability is essential, but I can second @dbm1175 and confirm that Cookie Quick Manager integrates very nicely with the containers and allows you to achieve this functionality right now!

**Comment by popindavibe** [comment]
Not sure if I'm just doing it plain wrong, but the container is keeping cached files not matter the cache-control policy associated to a resource. My only way to force a refresh this way is to do it from the dev panel tool `Disable cache` checkbox. 
I could hardly recommend that plugin to anyone with such shortcomings. Please correct me and tell me that there is a solution for this. 
I've been truly enjoying the comfort this plugin, especially in providing a simple way to handle different account connections to the same website. I hope this will be addressed.

**Comment by 1JOe** [comment]
> 
> 
> Seconding this feature request. This capability is essential, but I can second @dbm1175 and confirm that Cookie Quick Manager integrates very nicely with the containers and allows you to achieve this functionality right now!

This is a good work around to find cookies per container or find all the cookies related to the site that might be in other containers.

**Comment by ameaninglessname** [comment]
[I think this extension does anything you want : Cookie-AutoDelete ](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete)

**Comment by poiNt3D** [comment]
> 
> 
> [I think this extension does anything you want : Cookie-AutoDelete ](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete)

No, it does not. I use  Cookie-AutoDelete for a long time, then i noticed that some stupid poll i clicked (without authorizing) remembered the answer. I tried manually deleting container cookies in Cookie-AutoDelete without any luck.
Clearing all browser cache\cookies helped.

**Comment by politas** [comment]
It's great that there are some solutions for clearing cookies from containers, but we really need a way to clear the cache from a container. Currently, it seems you need to delete the whole container and re-create it. Global cache clear does not clear the cache of containers!

**Comment by shmerl** [comment]
To clarify, when you do clear all cache from the settings, does it also clear it for all containers or only for no container?

**Comment by Kaleb-JCI** [comment]
As a developer who uses multi-account containers to log into various dev/staging/production/overseas environments. It would definitely be nice to be able to clear the cookies/cache/local storage for a given container without affecting the other containers.

**Comment by crisp5** [comment]
> I tried manually deleting container cookies in Cookie-AutoDelete without any luck. Clearing all browser cache\cookies helped.
This might have to do with [Total Cookie Protection](https://hacks.mozilla.org/2021/02/introducing-state-partitioning/). If you enable ETP Strict, Firefox isolates cookies and storage according to their first and third party contexts. Cookie AutoDelete hasn't been updated to handle the new behavior, the issue is being tracked [here](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/807).
My current settings are ETP Strict + Clear data on exit (with whitelisted sites for persistent logins within containers). Unfortunately, this means whitelisted site data is kept in every container. I'd like to be able to keep Google cookies in the Google container and clear them outside of it.

**Comment by calebplum** [comment]
This would be really convenient when you've accidentally logged into a site in the wrong container.

**Comment by Tyler-2** [comment]
I have FF clearing my cookies every session, and yet sites that I try to isolate from having access to my daily browsing get to keep their cookies forever.

**Comment by achernyakevich-sc** [comment]
There is a regular Firefox functionality to clear cookies. It could be achieved by two clicks:

![image](https://user-images.githubusercontent.com/24388336/161376842-3b92604b-0b48-4358-be48-5c81b81dd43b.png)

The only problem is that this kind cleaning cause cleaning site related cookies and data for **all** container.

So maybe correct way could be asking not MAC developers to provide cleaning functionality but ask Firefox developers to honor container that site is open in when they perform cleaning.

**Comment by crisp5** [comment]
That's fair. I couldn't find anything on Mozilla Connect, but there's this 4-year-old bug in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1480175. Maybe some day... :)

**Comment by djbrown** [comment]
There was a similar request in the Firefox Support Forum:
[Manage cookies in a container](https://support.mozilla.org/en-US/questions/1296755)

Official answer:
> I think that you will need to use a Cookie Manager extension for finer cookie control like Multi-Account Containers.
> You can search the Add-ons website.
> - Cookie Quick Manager https://addons.mozilla.org/firefox/addon/cookie-quick-manager
> - Cookiebro - Cookie Manager https://addons.mozilla.org/firefox/addon/cookiebro/
> - Cookie Manager https://addons.mozilla.org/firefox/addon/a-cookie-manager/

**Comment by jackbritchford** [comment]
Is there any status for this in Firefox? Would be nice to do without an extension

**Comment by politas** [comment]
Would be nice to do the cache at all.

**Comment by bunk3m** [comment]
Agree with @jackbritchford .   I just came across this today when I wanted to move a site to a new container (preferred) or delete all the cookies etc from one container ... and found it doesn't work. 👎

**Comment by LCameron** [comment]
I can't quite believe this feature isn't implemented!  
Deleting and re-creating a container seems excessive for a simple clean up. 
Also belongs as an entry in the docs on this page: https://support.mozilla.org/en-US/kb/containers

**Comment by gitgt** [comment]
"Clear cookies and site data" in addition to clearing more, does not work some pages and I must delete Container. 
Example: I have local install of Nextcloud and sometimes I cannot get tjhe page to work in Container only.

**Comment by chriscz** [comment]
Would be great to see this implemented, it's a major oversight imo. 

Does this extension use any privileged APIs not accessible to user-written extensions, if not, then I guess we could fork?

**Comment by ddybing** [comment]
Would definitely be very nice feature!

**Comment by warrenson** [comment]
This would be very useful indeed

**Comment by Kryptos-FR** [comment]
Any update on this? It makes using containers completely useless. Lots of website rotate their authentication data (as it is good practice) and cached data of such authentication makes the container failing to work after the first rotation.

It should be a basic feature.

**Comment by timur-g** [comment]
This one is important, but do not overreact and annoy with "It makes using containers completely useless." which is not true. 
When a site issue happens, just (temporarily) Disable Cache via Developer-Network.

**Comment by Kryptos-FR** [comment]
It's not an HTTP cache issue (which is the only thing that can be disabled in the Developer console). It is a site data/cookie cache issue.

So yes, still useless.

**Comment by djbrown** [comment]
I also don't think that missing this feature makes containers useless..
[Cookie Quick Manager](https://addons.mozilla.org/de/firefox/addon/cookie-quick-manager/) has supports containers pretty well and is my current solution for this.
But that doesn't handle other [Client-side storage](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage) e.g. [Web Storage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) (sessionStorage and localStorage), [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) and [Cache](https://developer.mozilla.org/en-US/docs/Web/API/Cache) (from [Serviceworker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API).

**Comment by politas** [comment]
> This one is important, but do not overreact and annoy with "It makes using containers completely useless." which is not true. When a site issue happens, just (temporarily) Disable Cache via Developer-Network.

Please don't use terms like "just" when describing something that is not obvious in the UI. How would a user even know how to do this? I don't know how to disable the cache. I'm actually using a completely different browser on my desktop because of this issue.

**Comment by SlackWhat** [comment]
I would like very much that feature too. 
It just makes sense. We can already assign specific websites to a container, have proxy and vpn settings within that container. It would only make sens to also be able to delete the cookies and cache specific to that container!

**Comment by squarrell** [comment]
i have no idea if i'm replying in the right place. last week my gmail stopped loading in my containers. it's only my gmail. i used to have them pinned and it was so convinient. my 2 primary emails in two separate tabs.

now i cannot open them on first go even off pinned. i try to load my gmail on the tab i was using before and it automatically opens a new tab and confirms which container i want to use.

what happened? it was so sudden and i don't understand! i didn't change anything on my computer. 

i deleted my cookies and cache but it didn't help

**Comment by groovecoder** [comment]
The fix for this has been released. https://github.com/mozilla/multi-account-containers/discussions/2672

**Comment by ddybing** [comment]
> The fix for this has been released. #2672

Awesome! Great job.

**Comment by WAZAAAAA0** [comment]
This *"Clear Container Storage"* button is incomplete in at least 2 ways:
1. It only clears Cookies and Local Storage. Session Storage, Indexed DB, Cache, Service Workers (and Plugin Data?) are all left untouched ([test page](<http://www.sharonminsuk.com/code/storage-test.html>)).
2. Can't clear the "DEFAULT" container.

**Comment by YoRyan** [comment]
> This _"Clear Container Storage"_ button is incomplete in at least 2 ways:

I wasn't satisfied with these restrictions either, so I wrote [my own extension](https://addons.mozilla.org/en-US/firefox/addon/cleantainer/).  It clears IndexedDB and sessionStorage using recently added API calls. (For now, we still can't touch service workers or plugin data.) It also supports the built-in default and Private Browsing containers.

**Comment by bunk3m** [comment]
@YoRyan I look forward to trying your extension.
