### ISSUE TITLE
Container menu slow to show up.

### ISSUE THREAD

**Issue by dCosminn** [mozilla/multi-account-containers#315]
When I click on the Container icon, the UI is really slow, It takes 1-2 seconds to show up. Once it's rendered everything works fine.
The Firefox hamburger menu works fine, it opens as soon as I click..

I'm on Windows 10 and the latest Nightly version.

**Comment by groovecoder** [comment]
Is this just the first time you open it per Firefox session, or every time you open it?

**Comment by Chiosc** [comment]
Every time.

**Comment by groovecoder** [comment]
Do you have a lot of tabs open?

**Comment by Chiosc** [comment]
No, 1-3 tabs open..

**Comment by jjdelc** [comment]
I'm also seeing this behavior. I'm on Nightly. Every now and then I get the warning that "Test Piliot may be making Firefox run slowly"

When I click the menu, I see the browser console show an error message: `TypeError: Can't access dead object (4) pointing to main.js:1305:120`. Clicking on that link to main.js shows a different error about not being able to find the source:
`NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIWebNavigation.loadURI]` on `viewSoruce-content.js:354` 

![testpilot-containers](https://cloud.githubusercontent.com/assets/59393/23685076/2efb6bd6-0370-11e7-936a-f1a5eee171f0.png)

**Comment by kjozwiak** [comment]
@ dCosminn and @jjdelc, are you still consistently seeing this issue with the current `Containers Experiment 2.0.0` version? You can check which version you're running with `about:support` under `Extensions`.

If you're still seeing this, does this happen with other test pilot experiments or just containers?

**Comment by dCosminn** [comment]
I'm on 2.0.0 and it's the same.   
Must be something related to the test pilot program, I just installed Snooze tab and has the same weird lag while the other extensions I have, like keepas, quicknote, poket are fast and smooth.

**Comment by kjozwiak** [comment]
Thanks for double checking @dCosminn :)

@johngruen, is this a known issue with the test pilot?

**Comment by jjdelc** [comment]
Sorry for the delay, I'm back. I updated to 2.2.0 and still seeing the same performance issuer. 
 
This is my list of extensions:
![captura_20170413-191915](https://cloud.githubusercontent.com/assets/59393/25028950/3904e2da-207e-11e7-8094-3756f47efa39.jpg)

**Comment by jjdelc** [comment]
Not sure if it's worth mentioning, I recently installed the extension [Bitwarden](https://github.com/bitwarden/browser) which also has a button that triggers a menu for its UI and it shows the same kind of sluggishness to pop out the menu.

**Comment by jjdelc** [comment]
Reported as Firefox bug, but was closed pointing that it was a bug on the extensions affected: https://bugzilla.mozilla.org/show_bug.cgi?id=1362638

**Comment by groovecoder** [comment]
Old bug that is upstream of this add-on code.
