### ISSUE TITLE
Accessiblity Reivew

### ISSUE THREAD

**Issue by groovecoder** [mozilla/multi-account-containers#333]
Need an accessibility review on the experiment.

**Comment by bakulf** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1338505

**Comment by jonathanKingston** [comment]
I don't think this other bug should block us doing changes here.
However a review likely won't make sense before #512

**Comment by dannycolin** [comment]
I guess this is still revelant in a sense because we should periodically do an a11y review (: However, I'm closing this since it was for the experiment and we could always discuss about a new review in a future meeting.
