### ISSUE TITLE
Awkward delay when opening a new container

### ISSUE THREAD

**Issue by emmyemi** [mozilla/multi-account-containers#337]
When I click to open a new container, there's a notable (~.75s) delay before the new tab opens. It feels quite clunky, but I'm not sure if it's only me or if others experience this as well.

I didn't have this issue with the non-Test Pilot implementation of Container Tabs, and I also don't have this issue when opening a non-container tab.

**Comment by bakulf** [comment]
Do you have the same delay when opening the container tab from the File menu? And from the plus button?

**Comment by emmyemi** [comment]
Just tested--I have the issue with both the File menu and the new tab button.

**Comment by kjozwiak** [comment]
@emmyemi, are you still getting performance issues with the latest version of containers?

**Comment by emmyemi** [comment]
@kjozwiak I am, though it's less pronounced now than it was. I'd like to get you guys a recording of the issue to work with—any recommendations for software that clearly displays mouse clicks?

**Comment by jjdelc** [comment]
Can confirm.

I have blank tabs configured and when opening a new container tab I can see the default search field home page flashing for a fraction of second and then about:blank being redrawn.

When opening new container tab without the extension, I noticed that the flash is still there but the whole process is way faster, it does not feel sluggish.

**Comment by jonathanKingston** [comment]
@bakulf I suspect this might be a platform issue, we don't do much more differently in terms of code path when in a container tab.

**Comment by jonathanKingston** [comment]
@emmyemi is this still occurring for you?

**Comment by emmyemi** [comment]
@jonathanKingston Not happening anymore—it hasn't been for a while, in fact. I can't say if anyone else is having trouble, but the issue seems to have been resolved for me.

**Comment by groovecoder** [comment]
Closing as resolved (since Aug 23)
