### ISSUE TITLE
Consider supporting seperate themes per container

### ISSUE THREAD

**Issue by groovecoder** [mozilla/multi-account-containers#343]
From https://news.ycombinator.com/item?id=13782073 ...

> I find that themes are great for knowing what context I'm in, like the Totem mechanism in Inception. I'm not sure if we can have a different theme for each container though.

**Comment by jonathanKingston** [comment]
Extensions can actually do this already. See my mockup: https://addons.mozilla.org/en-GB/firefox/addon/containers-theme/

**Comment by groovecoder** [comment]
Closing in favor of follow-up extensions (like @jonathanKingston's!)
