### ISSUE TITLE
Onboarding pages reappear every time history is cleared

### ISSUE THREAD

**Issue by nkestrel** [mozilla/multi-account-containers#381]
The onboarding seen state is saved in localstorage which is cleared along with the rest of browser history, it should be saved somewhere more permanent.

**Comment by groovecoder** [comment]
Nice catch, thanks for the bug report.

**Comment by bakulf** [comment]
We could use preferences instead localStorage. That would fix this issue.

**Comment by jonathanKingston** [comment]
@bakulf does extension storage clear in the same way? It would be cleaner to do this here, especially if we want the extension to stay to stick around.

**Comment by grahamperrin** [comment]
I can not reproduce this issue with extension version `3.7.0` added to Firefox `88`. 

https://user-images.githubusercontent.com/192271/116657936-261c4c80-a987-11eb-9a71-a1ade4a20c70.mp4

**Comment by dannycolin** [comment]
Fixed in the latest version (and for quite some time). Closing but feel free to reopen if it happens again.
