### ISSUE TITLE
Different preference options

### ISSUE THREAD

**Issue by Myer** [mozilla/multi-account-containers#385]
Version: 52.0
Build-ID: 20170302120751
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0
Containers Experiment: 2.0.0
Test Pilot: 1.1.2-dev-367bd83

Why are there different ways to edit the containers with different colors and icons? Which one is the current one and which work-in-progress?
Should I use the new icons or are they going to get removed?

![different icons](https://cloud.githubusercontent.com/assets/2845251/23967656/0bcc42ba-09c0-11e7-844c-26ce61fd43dc.PNG)

**Comment by jonathanKingston** [comment]
When the extension is removed and the icon is not in the about:preferences#containers list the tab won't have an icon. The context menus and other ways of accessing the container will have no icon either however from my testing the container will still exist and be able to be changed to a new icon.

Before we finish the test pilot extension we likely will be adding in more icons into the native experience.

I added the bug tab as I'm pretty certain users shouldn't be able to see this interface as the addon should disable the `privacy.userContext.ui.enabled` pref which removes the ability to find it under about:preferences#privacy.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
