### ISSUE TITLE
Secure connection error when connecting to Orange.fr webmail within container

### ISSUE THREAD

**Issue by lissyx** [mozilla/multi-account-containers#396]
STR:
 0. You need to be a customer of orange.fr
 1. Open a new tab in "Personnal" pre-built container
 2. Connect and identify on www.orange.fr
 3. Click on the webmail icon
 4. New tab gets opened in the "Personnal" container, for some webmailXX.orange.fr
 5. Wait

Expected:
 I do get to the webmail

Actual:
 I end up with a secure connection error, and not so much details as to why, except it fails on wassup.orange.fr
![capture d ecran de 2017-03-19 21-10-10](https://cloud.githubusercontent.com/assets/1645737/24084336/8f84e596-0ce8-11e7-90a8-2e0ea082c231.png)

The same webmail when using no container works well.

**Comment by lissyx** [comment]
This is on Firefox ESR 52 from Debian.

**Comment by lissyx** [comment]
Though I don't reproduce that on current Nightly.

**Comment by bakulf** [comment]
This happens because ESR52 doesn't container enough patches compared with what we have in nightly/beta/aurora/release. We could block the addon for ESR52, but, as @lissyx told me on IRC, debian ships ESR52 by default. Maybe we can show a popup saying that something can be broken in ESR52.
@groovecoder, feedback about the popup idea?

**Comment by pascalchevrel** [comment]
ESR52 and Release 52 share almost exactly the same code base, which container related patches are not in ESR52?

**Comment by lissyx** [comment]
I switched from Firefox ESR52 to plain Firefox 52, both from Debian sid, and I don't have the problem on "normal" release.

**Comment by jonathanKingston** [comment]
@bakulf could you clarify what you mean for the differences between ESR and normal 52?

**Comment by Stis** [comment]
In https://ftp.mozilla.org/pub/firefox/releases/ you can find 52.0 and 52.0esr (also with 52.0.1 and 52.0.2). I didn't check differences, but i think he's talking about that for the "normal" 52.

I also tested a new profil with only Containers on FF 52.0.2 (i admit i can't tell if it's ESR or not) x64 on Win Seven with the procedure described in OP. No problem reported, everything worked well.

**Comment by dannycolin** [comment]
Closing since this issue was related to Firefox 52 vs. 52 ESR and it's end of life now.
