### ISSUE TITLE
After assigning a site to container, need to keep an option to open in the default/non-container

### ISSUE THREAD

**Issue by mrmakeit** [mozilla/multi-account-containers#422]
If I assign a website a default container, and then try to open the website in another container, there is no option to not open it in it's default container.

Example
1. Assign facebook.com to always open in the Personal Container.
2. Open a new tab in the default container.
3. Navigate to facebook.com in the new tab.
4. Notification does not present an option to remain in the default container.

**Comment by jonathanKingston** [comment]
Yup we sort of guessed this would happen as a feature request. Depending on it's interest we can put it in the next release of one after.

If we wait for the next Firefox release we can actually implement this with standard Web Extension APIs and also clean up some of the wording around "*this* container".

This will require some History tracking to prevent us reopening back again the warning prompt.

**Comment by jonathanKingston** [comment]
This actually is now fixed (it has been for quite some time). Let me know if you have issues.
Thanks!
