### ISSUE TITLE
Consider adding "private container tabs"

### ISSUE THREAD

**Issue by smichel17** [mozilla/multi-account-containers#429]
Some sites are particularly bad about tracking and selling my data. (Google, Amazon, Facebook). When I open the url to one of these sites, I don't want it opened in the container I'm coming from, because I want as little metadata associated as possible. However, I also don't want it opened in a permanent container where I'm logged in and identifiable, like #306.

Currently I open these links in a new [private tab](https://addons.mozilla.org/en-US/firefox/addon/private-tab/). Unfortunately, private tabs (and windows) currently share a container. If I happen to visit Google and Facebook in the same private session, I don't want them to share active logins.

**I'd like the ability to open tabs in an ephemeral container that works like a private window.**

Related: #419

**Comment by groovecoder** [comment]
https://addons.mozilla.org/en-us/firefox/addon/containers-on-the-go/ does this. Does it solve your use-case?

**Comment by smichel17** [comment]
I started using it this past week and yes, it works quite nicely. I just wish there were a way to map <Ctrl-t> to this behavior.
