### ISSUE TITLE
Tabs and history are lost when disabling extension - please warn user first

### ISSUE THREAD

**Issue by longears** [mozilla/multi-account-containers#431]
To reproduce:
- Have 50 tabs open in various containers.
- On the [Test Pilot page](https://testpilot.firefox.com/experiments/containers), choose "Disable containers"
- All tabs that are in containers vanish forever, along with their history.
- Choose "Enable containers", but the extension seems reset to its default settings (default container names, and your tabs are still gone).

I lost a lot of work and I can't get it back since the history is gone too.  Please warn the user that their tabs and history will be deleted when disabling Containers.

I'm also using Tab Groups, if that matters.
Firefox 52.0.2 on OSX.

**Comment by jonathanKingston** [comment]
There should have been a warning about it deleting the containers? Is this just a wording issue?

**Comment by groovecoder** [comment]
FWIW, there's not a way to do this between the user action to remove the experiment and deleting the tabs. (See https://github.com/mozilla/testpilot-containers/issues/243)

We can put a warning on the Test Pilot page itself though.

**Comment by smichel17** [comment]
What about the initial walkthrough that explains how this experiment works? Or is that too obtrusive?

**Comment by longears** [comment]
I found the URLs of my lost tabs in the session store backups:
`~/Library/Application Support/Firefox/Profiles/_____/sessionstore-backups/previous.js`

The best behavior for the extension would be to not delete tabs when turning off the experiment.  It's ok if the tabs lose their cookies; at least the URLs will be preserved.

If that's impossible, a warning would be nice (on the Test Pilot page or in the walkthrough).  Something like "Disabling this experiment will permanently remove your containers and the tabs they contain."

**Comment by jonathanKingston** [comment]
@johngruen can we add a warning to disabling on the test pilot page perhaps? That still doesn't leave a clean route for the addon itself in about:addons though :/

**Comment by johngruen** [comment]
@jonathanKingston hrm...this is something we'd have to add.

**Comment by QuAzI** [comment]
Best way:
1. Show alert about history loss
2. Offer to user save tabs to bookmarks (like "Bookmark all tabs...") or to migrate into other workplace.
Because data loss is most worst case

**Comment by grahamperrin** [comment]
Please: is this still an issue? 

(I don't recall finding it with any recent release of Firefox.)

**Comment by groovecoder** [comment]
Test Pilot experiment is over now, so this is now invalid.
