### ISSUE TITLE
New tab long press UI

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/multi-account-containers#433]
As mentioned in email @ChenMorpheus we have some UI issues with the new tab button.

- This is currently not in platform and implemented in SDK so needs to be removed before 57
- Too many containers are an issue (some people have suggested hidden containers)
- UI doesn't have the same look and feel as the rest of the browser or updates we plan either (photon)
- Isn't themed for dev edition, nightly etc.

![selection_559](https://cloud.githubusercontent.com/assets/338988/24760186/d6bbfd82-1adf-11e7-894c-cab40ae97020.png)

**Comment by ChenMorpheus** [comment]
Sorry for the late reply. Before we dive in for the solutions, there are several questions I might need your clarification. Please find my comments inline.

> This is currently not in platform and implemented in SDK so needs to be removed before 57

Based on your following questions, it seems the UI can still survive before 57? Does this mean that we can't have this UI forever after 57? 

> Too many containers are an issue (some people have suggested hidden containers

For this issue, I believe Mark had provided a solution in #115. 

> UI doesn't have the same look and feel as the rest of the browser or updates we plan either (photon)

Right now Photon is still WIP, but we'll check if we can have a new look for this UI to fit in with other elements.

> Isn't themed for dev edition, nightly etc.

Do you mean this UI can change themes based on different versions?

**Comment by jonathanKingston** [comment]
> Based on your following questions, it seems the UI can still survive before 57? Does this mean that we can't have this UI forever after 57?

Yeah as soon as SDK dies, if we don't make it into platform then it has to be removed.

> For this issue, I believe Mark had provided a solution in #115.

Yeah the more button would be pretty cool. We probably would want reordering then.
It would also solve my desire for "hidden containers" where this new tab button and some of the others wouldn't show all containers. Only the menu would show the full list. (this is something containers making loads of containers need).

> Do you mean this UI can change themes based on different versions?

Yeah seems a little odd with the white on black etc.

Thanks!

**Comment by fangshih** [comment]
After discussed and review with other designers, we have updates for the new tab hover UI. 
It becomes more of the same look and feels as the rest of the browser.

![container open new tab light](https://cloud.githubusercontent.com/assets/4862573/26675972/7e4e83f0-46f8-11e7-90a1-63f9b2f294d5.png)
And the dev edition / dark theme 
![container open new tab - dark v2](https://cloud.githubusercontent.com/assets/4862573/26676034/ba59a190-46f8-11e7-9e63-2b12a9bf7060.png)

Thanks!!

**Comment by jonathanKingston** [comment]
Thanks again @fangshih!!!

**Comment by jonathanKingston** [comment]
Discussed the idea of moving this to long press like it is in Nightly now with the new UX shown. We can make the box scrollable etc.

**Comment by fangshih** [comment]
Hey @jonathanKingston, I have slightly updated the new tab UI to sync up with current Photon style. 
So the spacing and the font size is slightly different compared to the current build. 
Let me know if you need anything else. Thanks!   
![container open new tab light-new](https://user-images.githubusercontent.com/4862573/28457707-c0f88404-6e39-11e7-87d6-7a7820f2f264.png)
**visual measurement**
![dropdown panel spec](https://user-images.githubusercontent.com/4862573/28457712-c82031fa-6e39-11e7-98b0-12307faf2ffb.png)
https://www.dropbox.com/s/ghk51j203zc8sts/Dropdown%20panel%20spec.png?dl=0

**Comment by jonathanKingston** [comment]
Hey @fangshih we have just reverted back to the code that is in Nightly at the moment and didn't get time to update these. I think that we might get these styles for free when XUL panels are updated as it should be have like a standard context menu. However I will check closer to the time.

Thanks again for this!

**Comment by fangshih** [comment]
Got it! Thanks @jonathanKingston
