### ISSUE TITLE
If you add containers, then remove it, you cant use right click to open something in a new tab

### ISSUE THREAD

**Issue by Kryze** [mozilla/multi-account-containers#440]
Hello,
I was testing containers and then decided to remove it from my browser and suddently i wasn't able to open link in a new tab with right click
When i relaunch firefox the bug was gone
Have a nice day

**Comment by jonathanKingston** [comment]
Hey what version of Firefox are you using?

You can check about:support to see what extensions you have installed also.

**Comment by Kryze** [comment]
52.0.2
Adblock Plus
Pocket
TestPilot

**Comment by Stis** [comment]
52.0.2 and 52.0.2esr, both x64 on Win Seven.
Fresh profile with Containers and Tile Tabs.
I confirm the bug. You still see the option in the righclick menu, but clicking it doesn't work.
Relaunching to validate Containers deletion or canceling the deletion restore the functionality.

**Comment by kjozwiak** [comment]
Thanks for the bug report @Kryze and for the confirmation @Stis!

**STR:**

* install fx53.0 `buildid: 20170413192749, changeset: d345b657d381`
* install the [test pilot](https://testpilot.firefox.com/) and the [container experiment](https://testpilot.firefox.com/experiments/containers)
* remove the container experiment via `about:addons` or via the [containers experiment test pilot page](https://testpilot.firefox.com/experiments/containers)
* visit https://www.eff.org/ or any website, right click on any random link and select `Open Link in New Tab`

You'll get the following error in the browser console:

`JavaScript error: chrome://browser/content/browser.xul, line 1: TypeError: can't access dead object`

**Platforms used:**
* macOS 10.12.4 - Reproduced
* Ubuntu 16.04.2 LTS VM - Reproduced
* Win 10 Pro x64 VM - Reproduced

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
