### ISSUE TITLE
Middle click on assigned link forces focus to new tab

### ISSUE THREAD

**Issue by CircleCode** [mozilla/multi-account-containers#442]
Usually, hen i use middle click, the corresponding tab is opened in background, which is what I want.
But when I middle click to an url for which there is an assignment different than current container context, the new tab has focus.
Consider or example:

*   `github.com` is assigned to `GH` container
*   I am on a page in no container
*   I middle click on the link `github.com`
*   the new (temp) tab opens in background (which seems fine)
*   the extension copy the tab in a new (final) `GH` tab and destroy the temp tab
*   the final tab is focused (this is not wanted)

**Comment by Stis** [comment]
Reproduced in FF 52.0.2 x64 on Win Seven.
I confirm it's annoying.

**Comment by Radagast** [comment]
Also happens on Linux

**Comment by mat813** [comment]
It is annoying.

**Comment by jonathanKingston** [comment]
I was kinda hoping `browser.webNavigation.onCreatedNavigationTarget` would help solve this issue however it seems there isn't anything we can do without using a content script which would likely be buggy.

**Comment by LosEagle** [comment]
Well buggy content script would probably be better than having to deal with this every time I want to open link in new tab imho.

**Comment by cactux** [comment]
Same problem with FF 55.0.3 (win7). Really annoying.

**Comment by grssam** [comment]
I think the extension just respect the config `browser.tabs.loadInBackground` (which is true by default)

**Comment by Keith94** [comment]
Just ran into this bug, can anything be done about it?

**Comment by jonathanKingston** [comment]
@Keith94 I think there might be an API to address this however I haven't had time to play about with it.

Extensions don't have access to `browser.tabs.loadInBackground` nor the ability to detect what the user does in terms of shift+click or middle click.

**Comment by grssam** [comment]
@jonathanKingston Haven't played around with web extensions a lot, but if the extension cannot even read the said preference, then at least it can create a preference of its own - whether to open in background or foreground.

**Comment by woctezuma** [comment]
This issue is the only thing which annoys me with this extension.

**Comment by groovecoder** [comment]
Note: I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1421447 as the upstream bug that would enable this fix.

**Comment by gaborluk** [comment]
@jonathanKingston, @groovecoder, I'm not sure if I'm missing something here, but I believe I've fixed this issue in the PR above with a simple passing of the original tabs's `active` state to the artificially opened tab.

**Comment by staabm** [comment]
I realized that this issue regressed. I dont know whether it started again as of today or maybe even a few days before.

please re-open the issue

**Comment by gaborluk** [comment]
@staabm, @groovecoder, it's just that the fix hasn't actually been released yet, to the best of my knowledge. The last release of the extension was on December 1st, and my PR was merged on December 4th.

**Comment by gaborluk** [comment]
A release came out yesterday, and I can confirm that this is now working as expected.

**Comment by groovecoder** [comment]
Closing; this should have been fixed in the last release. (As mentioned by @gaborluk)
