### ISSUE TITLE
Want to add a quick switch to Containers on a page that has been opened

### ISSUE THREAD

**Issue by lovehomes** [mozilla/multi-account-containers#458]
Has been using mutlifox, but firfox53 not support, after the trial found that I can not meet the requirements, as follows:
1, can not open the page directly on the switch cookie, only in the new label switch, low efficiency
2, has been switched to shopping Containers, follow-up to open the new label can not be maintained for the shopping containers.

**Comment by jonathanKingston** [comment]
The issue title sounds a lot like #311.

> 1, can not open the page directly on the switch cookie, only in the new label switch, low efficiency

Is this a multi fox feature? If not could you explain further I'm having difficulty understanding.

> 2, has been switched to shopping Containers, follow-up to open the new label can not be maintained for the shopping containers.

Do you mean the default + tab button is not shopping container?

**Comment by lovehomes** [comment]
multifox 可以：新建两个配置，配置1登录各一个账号，配置2登录另外一个账号，登录taobao.com，可以在浏览的商品页面，该标签快速切换配置1 和配置2，而不要打开两个标签。这是multifox最吸引我的地方

**Comment by jonathanKingston** [comment]
Google translate tells me this is what you mean:

Multifox can: create two new configurations, configure 1 login each account, configure 2 login another account, log taobao.com, you can browse the goods page, the label quickly switch configuration 1 and configuration 2, and do not open two labels The This is the most multifox where I am most attractive

This itself doesn't make much sense either. 

Are you asking for hiding all containers and showing only one at once?

**Comment by jonathanKingston** [comment]
Closing as unanswered. Please let me know if we can answer this.
