### ISSUE TITLE
Container tab order is not preserved when restarting Firefox

### ISSUE THREAD

**Issue by vcchappell** [mozilla/multi-account-containers#481]
Example:

(from left to right:)
Tab 1 - Container 1
Tab 2 - Container 2
Tab 3 - no container
Tab 4 - no container

Exit and restart Firefox, now the tabs are re-ordered Tab 3, Tab 4, Tab 1, Tab 2.

It always puts the "no container" tabs first.

It would be nice if it kept the original order of the tabs, just like it did before containers.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
