### ISSUE TITLE
Hovering over "Containers" button displays Error: Popup destroyed ExtensionPopups.jsm:120:39 under browser console

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/multi-account-containers#491]
Hovering over the "Containers" button under the toolbar will display the following error message under the browser console:

`Error: Popup destroyed ExtensionPopups.jsm:120:39`

I haven't noticed anything that's broken because of the error but this is definitely a regression. I don't remember seeing this error before.

**STR:** [Example: [https://youtu.be/KYZHeWbzPw0](https://youtu.be/KYZHeWbzPw0)]
* install the latest version of m-c
* install the test pilot & the containers experiment
* once install, open the browser console via the hamburger menu
* hover over the Containers button and you'll see the error being displayed in the browser console

**OS's Used:**

* macOS 10.12.4 x64 - Reproduced
* Win 10 x64 VM - Reproduced
* Ubuntu 16.04.2 LTS x64 VM - Reproduced

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
