### ISSUE TITLE
Pinned tabs lost after installing and uninstalling

### ISSUE THREAD

**Issue by tobozo** [mozilla/multi-account-containers#505]
I only had three pinned tabs but they got destroyed on install. I re-pinned them in a common container, played a bit with the containers (great work btw), then uninstalled the addon today with the following observations:

- Pinned tabs are gone again
- Addon removal does not prompt for browser restart, but it should as it breaks the "open in new tab" functionality

**Comment by jonathanKingston** [comment]
Were these tab containers? IF so this is kinda expected.

I would however suggest that uninstalling containers doesn't close tabs and instead moves them into "default" non container tabs.

> Addon removal does not prompt for browser restart, but it should as it breaks the "open in new tab" functionality

What does it break about this?

**Comment by tobozo** [comment]
> Were these tab containers? IF so this is kinda expected.

My pinned tabs got destroyed on install, so yes those were tab containers.

>  What does it break about this?

After uninstall, right-click on a link/open in new tab had no effect.  Same for Ctrl+click. 
Everything related to tab behaviour became broken until I closed and restarted Firefox.

This addon just needs a "Restart is required" on removal.

**Comment by grahamperrin** [comment]
Please: is this still an issue?

**Comment by tobozo** [comment]
Not anymore, created a test profile, installed and removed the addon, no browser restart required and all pinned tabs are still there.
