### ISSUE TITLE
How to enable Firefox Containers extension via about:config or console command?

### ISSUE THREAD

**Issue by MurzNN** [mozilla/multi-account-containers#516]
I need to force install/enable testpilot-containers extension in all computers of company, without manual clicks and other actions. How can I do this?

**Comment by MurzNN** [comment]
I try to do in about:config pref `privacy.userContext.enabled` set to true, but this isn't help.

**Comment by jonathanKingston** [comment]
I was told to consult https://wiki.mozilla.org/Enterprise for more info on this. I'm trying to find more info.

It is worth pointing out it's probably not advisable to roll out en-mass Test Pilot stuff to many users as it is experimental. However we are working hard on making this a normal extension which should totally be possible. I'm not familiar with the tools to do this though so will be following up on that.

Yeah that pref enables the Nightly version and not all the UX that comes with test pilot.

**Comment by grahamperrin** [comment]
https://blog.mozilla.org/tanvi/2017/10/03/update-firefox-containers/#comment-36309 under today's [An Update on Firefox Containers | Tanvi Vyas](https://blog.mozilla.org/tanvi/2017/10/03/update-firefox-containers/#comment-36309) – just the essentials, not intended to be comprehensive.

**Comment by grahamperrin** [comment]
> ## … about:config …

https://support.mozilla.org/en-US/kb/containers#w_what-you-can-do-with-multi-account-containers ▶ **For advanced users:**

**Comment by dannycolin** [comment]
The best solution is to use Enterprise Policies (See: https://github.com/mozilla/policy-templates). If you have more questions, feel free to ask on our support forum at https://support.mozilla.org/questions/new/desktop/form.
