### ISSUE TITLE
Saving HTML pages while viewing in containers reverts to default identity

### ISSUE THREAD

**Issue by smoothchocolate** [mozilla/multi-account-containers#519]
When I am browsing with a container, saving the HTML (File -> Save Page As or Ctrl + S) will save the HTML as though I were browsing from my default profile without using a container, rather than the HTML page as viewed in the container. Is this typical behavior, or is there something wrong with my setup? If the former, how can I make it save the "correct" page as viewed through the container identity?

**Comment by SoftVision-EmilPasca** [comment]
I have tested this on Windows 10 x64 and Mac 10.12 with the latest Firefox Release(56.0), latest Beta(57.0b7-20171009192146) and also with the latest Nightly(58.0a1-20171011220113) with the latest Multi Account Containers (4.0.3) and haven't managed to reproduce the issue.

After opening a container tab and navigating to a website, when pressing CTRL+S to save the HTML, the file is saved correctly and when dragging it into the browser it is loaded in a new container tab of the same type from which was previously saved.

@smoothchocolate Is this the issue you were describing?

Here is a screen recording with the described behavior:
![save_in_container](https://user-images.githubusercontent.com/20083658/31546494-408aa7ea-b02c-11e7-86b7-11bc9fb63990.gif)

**Comment by cschramm** [comment]
I'm seeing the same issue. Your test does not cover the problem, @SoftVision-EmilPasca.

I'll take bugzilla.mozilla.org as an example. Two ways to see the problem:

1. Make sure you are logged out from Bugzilla in default mode.
2. Log into Bugzilla in a new container tab.
3. Visit https://bugzilla.mozilla.org/page.cgi?id=mydashboard.html in the container. The page title is "My Dashboard".
4. Save the page. You will get a page with title "Log in to Bugzilla" that is expected when you're not logged in.

Other way around:

1. Make sure you are logged out from Bugzilla in a container you want to test with.
2. Log into Bugzilla in default mode.
3. Visit https://bugzilla.mozilla.org/page.cgi?id=mydashboard.html in a new container tab. The page title is "Log in to Bugzilla".
4. Save the page. You will get the "My Dashboard" page for the account you're logged in with in default mode but not in the container.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
