### ISSUE TITLE
Support different Languages (L10N)

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/multi-account-containers#529]
To implement #528 we need to add the feature to actually work in different language.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization

We can start with moving strings into being referenced by an L10N file and then get people to help translate.

**Comment by flodolo** [comment]
I'm surprised: Containers are a Firefox feature, how long do we plan to keep this experiment running? My expectation was for this experiment to end, and integrate the needed changes in core Firefox.

For the record, I was contacted a while back about this experiment, and then it was decided (not by me) to make it en-US only. It seems extremely late to start localizing it at this point.

**Comment by jonathanKingston** [comment]
@flodolo this wasn't a suggestion that we would start work on it immediately, we are mostly "👍" driven development and I realised to support #528 we needed this.

I think it was initially suggested that we focus on only one language however I am a little upset(With myself) we didn't do this however the timescales were pretty tight in implementing the first prototype.

> Containers are a Firefox feature, how long do we plan to keep this experiment running? 

Yes they are, however this addon is potentially something that runs along side native support as a cleaner interface. There is also the possibility that we ship this to Firefox as a web extension.
We are also starting a shield study too which is based on this code, this likely might benefit most from L10N.

Anyway everything is an unknown and I just wanted to log the issue :).

**Comment by klint** [comment]
Am I the only one voting for this? :) Rather scary indeed!

**Comment by groovecoder** [comment]
Maybe for now. Our Test Pilot experiment is targeting English users. When we release to AMO, I expect we'll get more votes for this. And we'll try to point AMO users towards this repo to help vote on issues.

**Comment by flodolo** [comment]
(since @guerojeff was asking)

**Comment by hightower5** [comment]
Please add a multi language support for this extension.

**Comment by Elaborendum** [comment]
Any updates on this?

**Comment by exoosh** [comment]
Thing is, this feature is _extremely_ useful and currently a feature only available in Firefox. I've recommended it to many people as I've been using it successfully for quite some time now. However, on occasion I find that someone I recommend it to is startled (and scared) by the fact that it is available in English only.

**Comment by dannycolin** [comment]
Closing since MAC is available in multiple languages for a long time now.
