### ISSUE TITLE
Variables instead content in new container Tab

### ISSUE THREAD

**Issue by wellington1993** [mozilla/multi-account-containers#536]
Hi,

I only have variables not titles after create container tab:
welcome_title
welcome_body

--
settings_pane_header
settings_pane_body
settings_pane_search_header
settings_pane_search_body
settings_pane_topsites_header
settings_pane_topsites_body
settings_pane_topsites_options_showmore
settings_pane_pocketstories_header
settings_pane_pocketstories_body
settings_pane_highlights_header
settings_pane_highlights_body

Sorry if irrelevant or duplicated.
Thanks.

**Comment by groovecoder** [comment]
Can you be more specific? Where are you seeing this?

**Comment by jonathanKingston** [comment]
@johngruen these look a lot like activity stream stuff?!

@wellington1993 if you could provide a screenshot, browser version, OS name and version, Firefox version and paste the addon list you have in about:support that would be super helpful in us debugging what you have.

**Comment by wellington1993** [comment]
OK and Thans! @jonathanKingston @johngruen @groovecoder 

See:

![2017-05-26-090126_2880x900_scrot](https://cloud.githubusercontent.com/assets/6920053/26493861/469a708c-41f2-11e7-90d7-3c0a88e74efc.png)

about:support 

> 
> Informações básicas sobre o aplicativo
> --------------------------------------
> 
> Nome: Firefox
> Versão: 55.0a1
> ID da compilação: 20170525090417
> User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
> OS: Linux 4.10.0-22-generic
> Janelas multiprocesso: 2/2 (Habilitado por padrão)
> Chave do Google: Encontrado
> Chave do serviço de localização da Mozilla: Faltando
> Modo de segurança: false
> 
> Funcionalidades do Nightly
> --------------------------
> 
> Nome: Activity Stream
> Versão: 0.0.0
> ID: activity-stream@mozilla.org
> 
> Nome: Application Update Service Helper
> Versão: 2.0
> ID: aushelper@mozilla.org
> 
> Nome: Firefox Screenshots
> Versão: 6.6.0
> ID: screenshots@mozilla.org
> 
> Nome: FlyWeb
> Versão: 1.0.0
> ID: flyweb@mozilla.org
> 
> Nome: Form Autofill
> Versão: 1.0
> ID: formautofill@mozilla.org
> 
> Nome: Multi-process staged rollout
> Versão: 1.50
> ID: e10srollout@mozilla.org
> 
> Nome: Pocket
> Versão: 1.0.5
> ID: firefox@getpocket.com
> 
> Nome: Presentation
> Versão: 1.0.0
> ID: presentation@mozilla.org
> 
> Nome: Shield Recipe Client
> Versão: 51
> ID: shield-recipe-client@mozilla.org
> 
> Nome: Web Compat
> Versão: 1.1
> ID: webcompat@mozilla.org
> 
> Nome: WebCompat Reporter
> Versão: 1.0.0
> ID: webcompat-reporter@mozilla.org
> 
> Extensões
> ---------
> 
> Nome: Activity Stream
> Versão: 1.11.0
> Habilitado: true
> ID: @activity-streams
> 
> Nome: Containers Experiment
> Versão: 2.3.0
> Habilitado: true
> ID: @testpilot-containers
> 
> Nome: Min Vid
> Versão: 0.3.7
> Habilitado: true
> ID: @min-vid
> 
> Nome: Page Shot
> Versão: 5.2.201701261751
> Habilitado: true
> ID: jid1-NeEaf3sAHdKHPA@jetpack
> 
> Nome: Pulse
> Versão: 1.1.2
> Habilitado: true
> ID: pulse@mozilla.com
> 
> Nome: snoozetabs
> Versão: 1.0.17
> Habilitado: true
> ID: snoozetabs@mozilla.com
> 
> Nome: Tab Center
> Versão: 1.34.0
> Habilitado: true
> ID: tabcentertest1@mozilla.com
> 
> Nome: Test Pilot
> Versão: 1.1.2-dev-c4639a2
> Habilitado: true
> ID: @testpilot-addon
> 
> Nome: About Sync extension for Firefox
> Versão: 0.0.11
> Habilitado: false
> ID: aboutsync@mhammond.github.com
> 
> Nome: AngScope - Simple AngularJS Scope Inspector for Firebug
> Versão: 0.1.2.1-signed.1-signed
> Habilitado: false
> ID: angscopefb@gmail.com
> 
> Nome: AngularBug
> Versão: 0.2.0
> Habilitado: false
> ID: AngularBug@maoanran.com
> 
> Nome: Bookmark Deduplicator
> Versão: 1.3.1.1-signed.1-signed
> Habilitado: false
> ID: bookmarkdeduplicator@foxhatdev
> 
> Nome: Developer Profile
> Versão: 1.0.1-signed.1-signed
> Habilitado: false
> ID: developerprofile@xertoz.se
> 
> Nome: Firebug
> Versão: 2.0.19
> Habilitado: false
> ID: firebug@software.joehewitt.com
> 
> Nome: Flash Block (Plus)
> Versão: 0.1.6
> Habilitado: false
> ID: jid1-n8wH2cBfc2QaUj@jetpack
> 
> Nome: Ghostery
> Versão: 7.2.0.25
> Habilitado: false
> ID: firefox@ghostery.com
> 
> Nome: GNOME Theme Tweak
> Versão: 42.1
> Habilitado: false
> ID: {05f1cdaa-7474-43fa-9f69-c697555f4ea8}
> 
> Nome: HTTP/2 and SPDY indicator
> Versão: 2.3
> Habilitado: false
> ID: spdyindicator@chengsun.github.com
> 
> Nome: HTTPS Everywhere
> Versão: 5.2.17
> Habilitado: false
> ID: https-everywhere@eff.org
> 
> Nome: Integração com GNOME Shell
> Versão: 8.2.1
> Habilitado: false
> ID: chrome-gnome-shell@gnome.org
> 
> Nome: KDE5 Wallet password integration
> Versão: 1
> Habilitado: false
> ID: kde5wallet@guillermo.molina
> 
> Nome: Live HTTP headers
> Versão: 0.17.1-signed.1-signed
> Habilitado: false
> ID: {8f8fe09b-0bd3-4470-bc1b-8cad42b8203a}
> 
> Nome: MEGA
> Versão: 3.10.1
> Habilitado: false
> ID: firefox@mega.co.nz
> 
> Nome: Nightly Tester Tools
> Versão: 3.10
> Habilitado: false
> ID: {8620c15f-30dc-4dba-a131-7c5d20cf4a29}
> 
> Nome: Places Maintenance
> Versão: 2.0.2
> Habilitado: false
> ID: places-maintenance@bonardo.net
> 
> Nome: Poster
> Versão: 3.1.0.1-signed.1-signed
> Habilitado: false
> ID: {d48a39ba-8f80-4fce-8ee1-bc710561c55d}
> 
> Nome: SQLite Manager
> Versão: 0.8.3.1-signed.1-signed
> Habilitado: false
> ID: SQLiteManager@mrinalkant.blogspot.com
> 
> Nome: uBlock Origin
> Versão: 1.12.4
> Habilitado: false
> ID: uBlock0@raymondhill.net
> 
> Nome: Ubuntu Modifications
> Versão: 3.2
> Habilitado: false
> ID: ubufox@ubuntu.com
> 
> Nome: User Agent Switcher
> Versão: 0.7.3.1-signed.1-signed
> Habilitado: false
> ID: {e968fc70-8f95-4ab9-9e79-304de2a71ee1}
> 
> Nome: webcompat.com reporter
> Versão: 0.5.0
> Habilitado: false
> ID: jid1-mjpB54bRzP9Zxw@jetpack
> 
> Gráficos
> --------
> 
> Funcionalidades
> Composição: Basic
> Deslocamento/Zoom assíncrono: entrada wheel habilitada; arrasto da barra de rolagem habilitado
> Info WSI do driver WebGL 1: GLX 1.4 GLX_VENDOR(client): Mesa Project and SGI GLX_VENDOR(server): SGI Extensions: GLX_ARB_create_context GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_import_context GLX_EXT_visual_info GLX_EXT_visual_rating GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_EXT_texture_from_pixmap GLX_INTEL_swap_event GLX_EXT_buffer_age
> Renderizador do driver WebGL 1: Intel Open Source Technology Center -- Mesa DRI Intel(R) Haswell Desktop
> Versão do driver WebGL 1: 3.0 Mesa 17.1.0
> Extensões do driver WebGL 1: GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_APPLE_object_purgeable GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_INTEL_performance_query GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_shader_atomic_counter_ops GL_ARB_shader_clock GL_EXT_shader_samples_identical GL_MESA_shader_integer_functions
> Extensões WebGL 1: ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_sRGB EXT_shader_texture_lod EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_etc WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc MOZ_WEBGL_depth_texture
> Info WSI do driver WebGL 2: GLX 1.4 GLX_VENDOR(client): Mesa Project and SGI GLX_VENDOR(server): SGI Extensions: GLX_ARB_create_context GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_import_context GLX_EXT_visual_info GLX_EXT_visual_rating GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_EXT_texture_from_pixmap GLX_INTEL_swap_event GLX_EXT_buffer_age
> Renderizador do driver WebGL 2: Intel Open Source Technology Center -- Mesa DRI Intel(R) Haswell Desktop
> Versão do driver WebGL 2: 4.5 (Core Profile) Mesa 17.1.0
> Extensões do driver WebGL 2: GL_3DFX_texture_compression_FXT1 GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_trinary_minmax GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_object_purgeable GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_texture_float GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_IBM_multimode_draw_arrays GL_INTEL_performance_query GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_debug GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_NV_conditional_render GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_NV_texture_barrier GL_OES_EGL_image GL_S3_s3tc
> Extensões WebGL 2: EXT_color_buffer_float EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_texture_float_linear WEBGL_compressed_texture_etc WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc
> Infraestrutura de Áudio: pulse
> GPU #1
> Ativo: Sim
> Descrição: Intel Open Source Technology Center -- Mesa DRI Intel(R) Haswell Desktop
> ID do fornecedor: Intel Open Source Technology Center
> ID do dispositivo: Mesa DRI Intel(R) Haswell Desktop
> Versão do driver: 3.0 Mesa 17.1.0
> 
> Diagnósticos
> AzureCanvasAccelerated: 0
> AzureCanvasBackend: skia
> AzureContentBackend: skia
> AzureFallbackCanvasBackend: none
> CairoUseXRender: 0
> Registro de decisões
> HW_COMPOSITING:
> blocked by default: Acceleration blocked by platform
> OPENGL_COMPOSITING:
> unavailable by default: Hardware compositing is disabled
> WEBRENDER:
> opt-in by default: WebRender is an opt-in feature
> unavailable by runtime: Build doesn't include WebRender
> 
> 
> 
> 
> Preferências importantes modificadas
> ------------------------------------
> 
> accessibility.lastLoadDate: 1495799321
> accessibility.typeaheadfind.flashBar: 0
> browser.cache.disk.capacity: 1048576
> browser.cache.disk.filesystem_reported: 1
> browser.cache.disk.hashstats_reported: 1
> browser.cache.disk.smart_size.enabled: false
> browser.cache.disk.smart_size.first_run: false
> browser.cache.disk.smart_size.use_old_max: false
> browser.cache.frecency_experiment: 2
> browser.download.useDownloadDir: false
> browser.fixup.domainwhitelist.lablaudotest: true
> browser.places.smartBookmarksVersion: 8
> browser.search.useDBForOrder: true
> browser.sessionstore.upgradeBackup.latestBuildID: 20170525090417
> browser.startup.homepage: resource://activity-streams/data/content/activity-streams.html#/HOME
> browser.startup.homepage_override.buildID: 20170525090417
> browser.startup.homepage_override.mstone: 55.0a1
> browser.tabs.animate: false
> browser.tabs.warnOnClose: false
> browser.urlbar.daysBeforeHidingSuggestionsPrompt: 3
> browser.urlbar.lastSuggestionsPromptDate: 20160809
> browser.urlbar.maxRichResults: 12
> browser.urlbar.searchSuggestionsChoice: true
> browser.urlbar.usepreloadedtopurls.enabled: false
> browser.urlbar.userMadeSearchSuggestionsChoice: true
> dom.max_chrome_script_run_time: 0
> dom.push.userAgentID: e59722cd95f84cebb53afd36bd77f2cc
> dom.report_all_js_exceptions: true
> dom.storage.default_quota: -1
> extensions.lastAppVersion: 55.0a1
> font.internaluseonly.changed: false
> general.autoScroll: true
> media.decoder-doctor.MediaDecodeError.button-clicked: true
> media.eme.enabled: true
> media.gmp-gmpopenh264.abi: x86_64-gcc3
> media.gmp-gmpopenh264.lastUpdate: 1470842076
> media.gmp-gmpopenh264.version: 1.6
> media.gmp-manager.buildID: 20170525090417
> media.gmp-manager.lastCheck: 1495731746
> media.gmp-widevinecdm.abi: x86_64-gcc3
> media.gmp-widevinecdm.lastUpdate: 1475511137
> media.gmp-widevinecdm.version: 1.4.8.903
> media.gmp.storage.version.observed: 1
> network.cookie.prefsMigrated: true
> network.dns.disablePrefetch: true
> network.http.speculative-parallel-limit: 0
> network.predictor.cleaned-up: true
> network.prefetch-next: false
> places.database.lastMaintenance: 1495044124
> places.favicons.optimizeToDimension: 64
> places.history.expiration.transient_current_max_pages: 112549
> plugin.disable_full_page_plugin_for_types: application/pdf
> plugin.importedState: true
> print.print_bgcolor: false
> print.print_bgimages: false
> print.print_duplex: 0
> print.print_evenpages: true
> print.print_in_color: true
> print.print_margin_bottom: 0.5
> print.print_margin_left: 0.5
> print.print_margin_right: 0.5
> print.print_margin_top: 0.5
> print.print_oddpages: true
> print.print_orientation: 0
> print.print_page_delay: 50
> print.print_paper_data: 0
> print.print_paper_height: 11,69
> print.print_paper_name: iso_a4
> print.print_paper_size_unit: 0
> print.print_paper_width: 8,27
> print.print_scaling: 0,70
> print.print_shrink_to_fit: false
> print.print_to_file: false
> print.print_unwriteable_margin_bottom: 17
> print.print_unwriteable_margin_left: 17
> print.print_unwriteable_margin_right: 17
> print.print_unwriteable_margin_top: 17
> privacy.cpd.offlineApps: true
> privacy.cpd.siteSettings: true
> privacy.sanitize.timeSpan: 0
> privacy.trackingprotection.enabled: true
> privacy.trackingprotection.introCount: 20
> privacy.userContext.ui.enabled: false
> security.fileuri.strict_origin_policy: false
> security.ssl.errorReporting.automatic: true
> services.sync.declinedEngines: prefs,passwords,tabs,bookmarks,addons,forms,history
> services.sync.engine.bookmarks.validation.lastTime: 1495731813
> services.sync.engine.prefs: false
> services.sync.engine.prefs.modified: false
> services.sync.lastPing: 1495731755
> services.sync.lastSync: Fri May 26 2017 09:01:45 GMT-0300
> services.sync.numClients: 9
> storage.vacuum.last.index: 1
> storage.vacuum.last.places.sqlite: 1495220308
> 
> Preferências importantes bloqueadas
> -----------------------------------
> 
> Base de dados de lugares
> ------------------------
> 
> JavaScript
> ----------
> 
> GC incremental: true
> 
> Acessibilidade
> --------------
> 
> Ativado: true
> Bloquear acessibilidade: 0
> 
> Versões de bibliotecas
> ----------------------
> 
> NSPR
> Versão mínima esperada: 4.15 Beta
> Versão em uso: 4.15 Beta
> 
> NSS
> Versão mínima esperada: 3.31 Beta
> Versão em uso: 3.31 Beta
> 
> NSSSMIME
> Versão mínima esperada: 3.31 Beta
> Versão em uso: 3.31 Beta
> 
> NSSSSL
> Versão mínima esperada: 3.31 Beta
> Versão em uso: 3.31 Beta
> 
> NSSUTIL
> Versão mínima esperada: 3.31 Beta
> Versão em uso: 3.31 Beta
> 
> Funcionalidades experimentais
> -----------------------------
> 
> Isolamento
> ----------
> 
> Seccomp-BPF (Sistema de filtragem de chamadas): true
> Sincronização do Tópico Seccomp: true
> Espaço de nomes do usuário: true
> Isolamento do conteúdo processado: true
> Isolamento de plugins de mídia: true
> Nível de isolamento do conteúdo processado: 2
> 
> Chamadas do sistema rejeitadas
> ------------------------------
>

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
