### ISSUE TITLE
Selecting a tab through the container button sometimes selects the wrong one.

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/multi-account-containers#550]
STR:
- click the container button next to the awesome bar
- select the arrow next to "Work"
- select a tab

Expected outcome:
* The selected tab will be opened

Actual outcome:
* Another tab is opened

I think this has to do with multiple windows, but I'm not sure.
I know this is somewhat vague, but I'm happy to shed some extra light onto this if you let me know how I can help.

**Comment by jonathanKingston** [comment]
Probably isn't using the correct window ID, though we should check.

**Comment by SoftVision-EmilPasca** [comment]
I have tested this  on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64 with the latest Firefox Release(56.0), latest Beta(57.0b7-20171009192146) and also with the latest Nightly(58.0a1-20171011220113) with the latest Multi Account Containers (4.0.3) and haven't managed to reproduce the issue.

I have created many container tabs(including custom container tabs) and navigated to different websites and whenever selecting the arrow next to "Work" or other container and choosing a tab from there, the selected tab is opened.

@mozfreddyb Is this still reproducible on your end? Can you please add more information as Operating System, Firefox version and addons installed?

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This was never reproduced, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce and/or more information.
