### ISSUE TITLE
View container panel doesn't open

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/multi-account-containers#574]
I was able to STR in unbranded 53 on Ubuntu.

1. Open containers browser action
2. Click add button next to containers
3. Container is created
4. Go back to browser action and arrow is next to the container name
5. Click arrow

Expected:
Panel to open

Actual:
Nothing happens

This was only reproducible for me on a stale profile that already had previous versions and updated to the current 2.3.0.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-569)

**Comment by jonathanKingston** [comment]
Existing Containers profile, then updated to 2.3.0. Unbranded 53.0.2

> about:support

Application Update Service Helper	2.0	true	aushelper@mozilla.org
Containers Experiment	2.3.0	true	@testpilot-containers
Multi-process staged rollout	1.14	true	e10srollout@mozilla.org
Pocket	1.0.5	true	firefox@getpocket.com
Test Pilot	1.1.2-dev-f3fe9bf	true	@testpilot-addon
Web Compat	1.0	true	webcompat@mozilla.org
Ubuntu Modifications	3.2	false	ubufox@ubuntu.com

Stepping through the debugger it looks like an uncaptured promise here:
```
    return browser.runtime.sendMessage({
      method: "getTabs",
      userContextId: Logic.userContextId(identity.cookieStoreId),
    }).then(this.buildInfoTable);
```

I also get errors like this:
```
console.trace: 
_fronts/inspector.js 770 WalkerFront<.getMutations</<
_/Promise-backend.js 917 process
_/Promise-backend.js 801 walkerLoop
_/Promise-backend.js 737 scheduleWalkerLoop/<

console.error: 
  TypeError: can't access dead object: CssLogic.getComputedStyle@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/css-logic.js:686:7
get computedStyle@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/inspector.js:360:12
get isDisplayed@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/inspector.js:375:9
_onReflows@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/inspector.js:1027:11
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/event-emitter.js:191:13
_startEventLoop@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/reflow.js:314:7
setTimeout_timer@resource://gre/modules/Timer.jsm:30:5
```

**Comment by jonathanKingston** [comment]
Debugging
- index.js `async getTabs(args) {`
- Which then calls: `sendReply(this[message.method](message));`
- returns a promise which I was expecting to be resolved here:
  - http://searchfox.org/mozilla-central/source/toolkit/components/extensions/ExtensionChild.jsm#352


Unanswered questions:
- Is there anything different between unbranded and release
- Why would only a stale profile cause this
- Is there anything different in the bundled build (Have not been able to reproduce on the production branch)

**Comment by jonathanKingston** [comment]
IRC paraphrase for anyone else interested about the "fix":

This fixes the panel opening issue, it creates the likelihood that some icons might turn into pages even for nightly.
In nightly currently new tab and other icons go missing anyway which is another fix I did elsewhere... this fixes them all to be pages if they don't load

The main thing I was testing was the panel that lists the containers tabs, I don't think there is anywhere else that code is active.
In Release you will see goat icons and a 300ms delay and in Nightly you will see the icons and new goat icons for new tab pages.
I was only able to replicate using a broken old profile that had it's container install pre 2.3.0 and direct from the store.
I wasn't able to replicate by building the experiment/firefox and creating the mockup.
As Baku mentioned the way to "test" a broken profile is back it up and edit the XPI with vim to contain the patch

**Comment by jonathanKingston** [comment]
Tested on latest release unbranded 53 on a fresh profile and the issue doesn't happen.

**Comment by jonathanKingston** [comment]
@kjozwiak's comment from the previous bug...

> @kjozwiak would really appreciate your eyes on this as I dunno what is causing this and it might mean we have to cut an emergency release from the release branch.

I've been trying to reproduce this for a few hours on multiple platforms without any luck :/

> Perhaps we should change the title of this bug to reflect that, I don't really want to lift and shift all the comments to just close this bug.

I was going to suggest spinning off your [issue](https://github.com/mozilla/testpilot-containers/issues/566#issuecomment-305444672) into a seperate bug. Following this gets pretty confusing especially as there's two bugs here. One that @danieljakots reported and the other one that @jonathanKingston found [here](https://github.com/mozilla/testpilot-containers/issues/566#issuecomment-305444672). Someone who doesn't know the history behind this bug might assume all the debugging/comments are referring to the original problem which they're not..

**Comment by jonathanKingston** [comment]
The follow up to this bug should be using web extensions which likely wouldn't be impacted by this issue at all here.
Pushing a bigger SDK removal patch to prod late Thurs or Friday seems better than lying about what favicon the tab has and a 300ms delay.

**Comment by jonathanKingston** [comment]
Mozregression pointed at: https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=b01f44c896b2472b154a48c68cf343ae2289d6bd&tochange=d80c517658f5048491b7bf27da25246a297ab50b being the fix for this. So it will likely not impact newer builds that this.

**Comment by grahamperrin** [comment]
https://github.com/mozilla/multi-account-containers/issues/574#issue-235245940

The UI has changed, when I follow comparable steps I can not reproduce the issue. 

@jonathanKingston please, is this still reproducible for you?
