### ISSUE TITLE
Tab closing became very slow in today's nightly

### ISSUE THREAD

**Issue by past** [mozilla/multi-account-containers#598]
I've been using containers for quite some time, but I noticed after today's update that my nightly was very slow to close a tab when containers was enabled. This happened on my main profile in both windows and macOS. 

Here is a profile: https://perfht.ml/2rzd7Pf

mconley and florian suggested that sending telemetry is what is causing this. sendTelemetryPayload from resource://testpilot-containers/index.js may be triggering [bug 1369594](https://bugzil.la/1369594).

Could be related to https://github.com/mozilla/testpilot/issues/2422.

**Comment by mikeconley** [comment]
Filed by a separate user here: https://bugzilla.mozilla.org/show_bug.cgi?id=1373822

**Comment by jonathanKingston** [comment]
Hey @groovecoder the `sendTelemetryPayload` method goes straight to sending the call right? I wonder if using a message queue style setup to send the events on shutdown and when the browser is idle?

Should shared workers be investigated for preventing telemetry blocking the main code?

**Comment by kjozwiak** [comment]
Here's another [profile](http://bit.ly/2rFp6pH) that was added in [bug#1373822](https://bugzilla.mozilla.org/show_bug.cgi?id=1373822) which demonstrates the performance regression.

**Comment by grahamperrin** [comment]
Please: with release 56.0 of Firefox, is this still an issue? 

If it helps: Mozilla bug [1373822 - Lag when closing tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1373822) is RESOLVED INVALID.

**Comment by past** [comment]
Well that bug was closed as invalid, because this issue was the place where we would track the problem. That being said, I haven't experienced this issue again in the last few months.

**Comment by groovecoder** [comment]
Closing unless/until we can reproduce.
