### ISSUE TITLE
Edit container radio buttons are not aligned

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/multi-account-containers#622]
For some reason after merge the styles look like this. Each one is off centre left and right in order.
![selection_698](https://user-images.githubusercontent.com/338988/27434791-d040b82c-5751-11e7-8cdd-2abd6c7e162b.png)

**Comment by dnahol** [comment]
@jonathanKingston 

Is this still an issue? What version/ OS?

Here is what I see on
Mac OS High Sierra, version 10.13.6
Firefox Quantum, version 69.0.3 (64-bit)

<img width="367" alt="Screen Shot 2019-10-21 at 11 40 33 AM" src="https://user-images.githubusercontent.com/2976514/67233321-d1922b80-f3f7-11e9-8636-08e3d5f969f0.png">

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
