### ISSUE TITLE
Open Link in New Container Tab does not list custom containers

### ISSUE THREAD

**Issue by Smile4ever** [mozilla/multi-account-containers#634]
1. Right click a link. (the link context menu appears)
2. Hover over Open Link in New Container Tab (a context menu appears)

This context menu does not list custom containers (=containers that I added myself) as an option

**Comment by jonathanKingston** [comment]
Can you paste what you have in about:support? Also what OS and version of Firefox.

**Comment by Smile4ever** [comment]
Is this enough? Nightly from 20170622 on Windows 10.

Name 	Firefox
Version 	56.0a1
Build ID 	20170622030208
Update History 	Show Update History 
Update Channel 	nightly
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0
OS 	Windows_NT 10.0
Multiprocess Windows 	1/1 (Enabled by default)
Google Key 	Found
Mozilla Location Service Key 	Found
Safe Mode 	false

**Comment by jonathanKingston** [comment]
I really need to know what version of addons you are running. I haven't seen this in our testing but addons can impact each other.

Do you have the option to open these containers in the file menu?

**Comment by SoftVision-PaulOiegas** [comment]
@Smile4ever - Jonathan is asking for the "Extensions" section from "about:support" page. If you scroll down a bit on the page, you'll see it. That would help us to know if this is caused by an old version of the Containers experiment, or by other add-ons that may create a conflict situation.

**Comment by Smile4ever** [comment]
I've included all enabled addons:

Always Preview	0.1.6.1	true	{d2a46ca0-999d-11da-a72b-0800200c9b57}
Containers Experiment	2.3.0	true	@testpilot-containers
Dorando keyconfig	2016.2	true	keyconfig@mozilla.dorando.at
FastNav	1.0.3	true	fastnav@hugsmile.eu
Greasemonkey	3.11	true	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
Keyboard Shortcut for Tab Duplication	3.0.1	true	extension-ksftd@patrick.dark.name
Middle Click On Page Closes Tab	2.0.0	true	middleclickonpageclosestab@hugsmile.eu
Open Selected Links	0.9	true	selected-links@dveditz
Scrollkey	1.2.0	true	scrollkey@hugsmile.eu
Snap Links	3.1.1.3	true	snaplinks@snaplinks.mozdev.org
Stylish	2.0.7	true	{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}
Tab Center Redux	0.3.2	true	387cfaef37c37e18b9cda44092240ef0faf923d8@temporary-addon
Test Pilot	1.1.2-dev-9a0c55b	true	@testpilot-addon
Translate Now	3.0.1	true	@translatenow

**Comment by jonathanKingston** [comment]
@Smile4ever can you check with the latest version of "Multi-Account Containers" that this has been resolved? The extension has been simplified to a web extension which should iron out these bugs.

I'm going to close, please let me know if it's still happening.
Thanks!

**Comment by Smile4ever** [comment]
It's no longer happening in the latest release.

**Comment by jonathanKingston** [comment]
Great good to know, thanks for checking back @Smile4ever!
