### ISSUE TITLE
"Always Open in This Container" notification is not rendering smoothly on Nightly

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/multi-account-containers#636]
[Notes]:
- since this is a regression, I narrowed down a regression range:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=958d2a5d10091401fd5e900e8e063d21940c137e&tochange=7f894f791cdf170d788507d0eff30024ce699523

[Affected versions]:
- Nightly 56.0a1 
- Containers Experiment Build: 2.4.0

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Containers Experiment is installed on a new browser profile.

[Steps to reproduce]:
1. Start Firefox with the profile from prerequisites.
2. Open a new tab in a container (e.g. "Personal") and navigate to a website (e.g www.soundcloud.com)
3. Right click on the page's content.
4. Click on "Always Open in This Container" and observe the notification under the URL bar.

[Expected results]:
- The process of displaying the notification is smooth, without jerkiness while rendering.

[Actual results]:
- The notification is not smoothly displayed, this causing jerkiness while rendering.

[Additional notes]:
- This is also reproducible by accessing the "Always Open in This Container" option through the Containers toolbar button.
- Please see the following screencast of the issue:

![rendering](https://user-images.githubusercontent.com/26000308/27475847-4654570e-580f-11e7-8f2e-f62002226eec.gif)

**Comment by jonathanKingston** [comment]
I noticed this, I assumed it was just Ubuntu being crummy. Will check with others as this sounds a lot more like a Nightly issue itself.

**Comment by mstange** [comment]
This is a [gfx bug in Nightly itself](https://bugzilla.mozilla.org/show_bug.cgi?id=1373335) and is probably going to be fixed in today's nightlies.

**Comment by jonathanKingston** [comment]
@mstange ah thank you for commenting! I just was about to raise a bug. Will check back once the code drops.

**Comment by jonathanKingston** [comment]
This since has been fixed in platform and also the extension doesn't use the bile green there. Thanks
