### ISSUE TITLE
Very broken after Firefox 54

### ISSUE THREAD

**Issue by rmenessec** [mozilla/multi-account-containers#641]
The Containers experiment UI runs the introductory UX every time the browser is restarted. May have other problems as well on 55.x+—I have no way of telling without downgrading to ≤ 54.x. Looks like a browser problem.

Please see [this related bug](https://github.com/wallabag/wallabagger/issues/90#issuecomment-311452740) in a different extension for more information.

**Comment by jonathanKingston** [comment]
Are you running in always private mode Firefox? Do you always clear history
on firefox close for example.

**Comment by rmenessec** [comment]
No and no.

My default cookie policy is session-only, however.

about:config -> network.cookie.lifetimePolicy: 2

**Comment by jonathanKingston** [comment]
What is the value of `browser.privatebrowsing.autostart`?

**Comment by rmenessec** [comment]
It's false. I don't use Firefox Private Browsing at all, ever.

Instead, I use Chrome in an Incognito window during any potentially dangerous browsing, for maximum data separation and security.

**Comment by jonathanKingston** [comment]
@kjozwiak are you able to replicate this at all? We have had a few 54 errors reported.

**Comment by jonathanKingston** [comment]
Our tester at the time couldn't find an issue and no other user has reported this issue since. Could you reopen this issue if you are still having this issue.
It does however look like you are having issues with other extensions also which might lead to issues in this extension. You might want to try checking in a fresh profile.

Thanks

**Comment by rmenessec** [comment]
Yes, I'm sorry that I didn't follow up sooner. The problem is NoScript. It's breaking quite a lot of my other extensions—possibly also bits of Firefox—and so far the developer is ignoring me. 😩
