### ISSUE TITLE
Content in Firefox marketing hub 

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/multi-account-containers#650]
e.g. www.mozilla.org/firefox/features/containers or possibly just a content block on an existing page.

**Comment by hoosteeno** [comment]
This needs the amo-launch label.

**Comment by groovecoder** [comment]
Will assign to @fabiorios when he accepts invite.

**Comment by hoosteeno** [comment]
Suggest this is a block of content on http://www.mozilla.org/firefox/features/ that points at containers. Bug filed on www: https://bugzilla.mozilla.org/show_bug.cgi?id=1399227

**Comment by groovecoder** [comment]
Removing from AMO launch milestone - we can decouple this from launch.

**Comment by jonathanKingston** [comment]
Closing this happened too.
