### ISSUE TITLE
Sidebar Support

### ISSUE THREAD

**Issue by MrGus99** [mozilla/multi-account-containers#690]
"Open Link in New Container Tab" is available when you right click anywhere on a website but not available when I right click on a bookmark in the side tab.  Seems this would be quick to add so that I can open up bookmarks in different containers not just website links.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-577)

**Comment by grahamperrin** [comment]
The same for history, and other uses of the sidebar.

**Comment by bambooLoutre** [comment]
For the bookmarks toolbar too
