### ISSUE TITLE
Delete (not remove)

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/multi-account-containers#700]
Consistency. 

## Steps

1. point at a bin
2. observe the phrase _Delete … container_
3. click the bin
4. observe the confirmation dialogue

## Expected

- reuse of the word _delete_

## Actual result

- three uses of the word _remove_ (no use of _delete_).

## Environment

Containers Experiment 2.4.1

## Suggestion

Prefer the word _delete_. 

(_Removal_ is more often associated with something that can be easily replaced.)

**Comment by jonathanKingston** [comment]
Added PR to change the title you mention to "Remove" which was the wording agreed by product.

This is also used pretty much everywhere with few exceptions now in about:preferences I would actually suggest we clear up those last ones for consistency (not to be handled here and instead on Bugzilla).

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Firefox Multi-Account Containers version (4.0.2 built on 09/27/2017), tested on Windows 10 x64 and Mac OS 10.12 on Firefox Release (53.0.3) and latest Nightly (58.0a1-20170926220106).
