### ISSUE TITLE
Clicking container buttons doesn't work

### ISSUE THREAD

**Issue by jc86035** [mozilla/multi-account-containers#717]
Containers does not work for me (nothing happens when the four container buttons are clicked), although this may be due to ticking every box in the Clear History settings. I am unable to install Containers on a new profile for testing since the website is currently broken (https://github.com/mozilla/testpilot/issues/2746).

**Comment by collectorgeneral** [comment]
This issue is present on ALL experiments with me: e.g. [send](https://testpilot.firefox.com/experiments/send) or [voicefill](https://testpilot.firefox.com/experiments/voice-fill). Clearing history probably is not the issue since this exists on pristine new profiles. This is definitely related to the other issue.

**Comment by jonathanKingston** [comment]
Is this still happening or was it temporary? We haven't had other reports since this date?

I'm going to close as I missed this one but I don't think it is still happening.

**Comment by jonathanKingston** [comment]
Please reopen if not the case.

**Comment by Softvision-MariusComan** [comment]
I could not reproduce this issue on the latest "Multi-Account Containers" build (4.0.2). 
I have verified it on on Windows 10 x64, Ubuntu 14.04 and Mac 10.12, with the latest Firefox release (55.0.3) and the latest Nightly (58.0a1).
@lordserch, can you please verify if this is still reproducible on your end?

**Comment by jc86035** [comment]
I think this is actually because Containers is deliberately disabled in Private Browsing and similar for whatever reason (so not a bug), although a user who uses Private Browsing regularly might be more likely to _want_ to use Containers as well.

**Comment by jonathanKingston** [comment]
Yeah we have #866 to warn users and another task which requires Firefox changes to work in private mode.
