### ISSUE TITLE
Match doorhanger appearence

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/multi-account-containers#718]
in #561 we added a new doorhanger style however it doesn't match:

https://cloud.githubusercontent.com/assets/4862573/26675662/607e43de-46f7-11e7-9237-e7485ce9928b.png

**Comment by fangshih** [comment]
Here is the visual spec as the reference. Let me know if you need other specs or assets. Thanks!
![defualt container panel spec](https://user-images.githubusercontent.com/4862573/29261156-b710c3fa-8100-11e7-8f69-e2796a2c6584.png)

**Comment by groovecoder** [comment]
I think this bug is OBE: overcome-by-events. We should open new issues/bugs for doorhanger UI bugs.
