### ISSUE TITLE
After installing containers: Your Firefox profile cannot be loaded. It may be missing or inaccessible

### ISSUE THREAD

**Issue by arhi** [mozilla/multi-account-containers#721]
After installing containers Firefox is working normally, containers work ok. Turn off Firefox, restart win7, start Firefox - error "Your Firefox profile cannot be loaded. It may be missing or inaccessible." and after clicking ok the firefox starts normally, everything "works" until you click on "new tab". After you click on new tab, firefox freezes and a new popup "Your Firefox profile cannot be loaded. It may be missing or inaccessible." comes out, click ok, firefox unfreezes and you work normally. Next time you click to create new tab -> same thing.

I tried stracing it with processmonitor and I see that last thing it tries to read from disk before it fails (upon startup) is E:\Users\arhimed\AppData\Roaming\Mozilla\Firefox\Profiles\hk9ixpvl.bleh\extensions\. 

Removing tespilot and containers did not solve the problem, removing all extensions did not solve the problem, copying profile to another place and creating new profile with copy, did not solve the problem.. creating new profile (blank one) solves the problem but it's not really a solution :(

**win7-ultimate 64bit, firefox 56.0b1 (64-bit) _(beta update channel)_**

**Comment by groovecoder** [comment]
This sounds like Containers might just be a coincidence. Can you reproduce a busted profile on a brand new profile? I.e. ...

1. Create new profile
2. Install only Test Pilot + Containers
3. Quit Firefox
4. Restart Win7

Does that trigger "Your Firefox profile cannot be loaded. ..." error?

**Comment by groovecoder** [comment]
If not, can you remember and/or give us a list of other extensions you're running? There may be an incompatibility between some extensions?

**Comment by arhi** [comment]
was working good for ages, thing happened immediately after containers. could be coincidence, of course.

can you help me debug what the hack could be wrong? I click on new tab I get the ... profile cannot be loaded. It might ... weird behavior, what's worse, FF continue to work flawlessly after "ok", till I click again on "new tab"

the extensions directory (when the issue happened):
![image](https://user-images.githubusercontent.com/410177/29226769-96d0abc0-7ed3-11e7-8519-4571fd1f994c.png)

**Comment by arhi** [comment]
i doubt this will help but.. 
[extensions.zip](https://github.com/mozilla/testpilot-containers/files/1218771/extensions.zip)

**Comment by arhi** [comment]
ok, this is now getting weird ??!?!?!??

firefox -P
create new profile
start firefox with "new just created empty" profile
**Your Firefox profile cannot be loaded. It may be missing or inaccessible.**
?!?!?

attached are the process monitor logs (both original and csv format) if that helps anyone figure this one out ?! (btw antivirus turned on/off makes no difference)

[Logfile.pml.zip](https://github.com/mozilla/testpilot-containers/files/1219094/Logfile.pml.zip)
[Logfile.csv.zip](https://github.com/mozilla/testpilot-containers/files/1219095/Logfile.csv.zip)

**Comment by arhi** [comment]
update:
since nothing was working I even cleared 
E:\Users\arhimed\AppData\Roaming\Mozilla\*
and the problem STILL PERSISTED ?!?!?!

so I uninstalled firefox, cleaned 
E:\Users\arhimed\AppData\Roaming\Mozilla\* 
E:\Users\arhimed\AppData\Local\Mozilla\*

installed it from scratch

copied the content of the old prfile over the new blank one

everything works as a charm ??!?! so looks like it's not the content of the profile that's a problem but something else that ff reads that was corrupted :( ..

**Comment by TanviHacks** [comment]
Is this still an issue?

**Comment by arhi** [comment]
nope not an issue any more

**Comment by amresh1495** [comment]
Yes, it is an issue even now on Ubuntu.
