### ISSUE TITLE
Always open in Pending to be deleted

### ISSUE THREAD

**Issue by jflatz** [mozilla/multi-account-containers#723]
Firefox: 56.0b1 Build ID: 20170808170225
Containers Experiment 2.41

This may not be an actual issue of containers but FF has been wigging out a little and I lost some pinned tabs in between sessions and it also appears as though I lost some containers.

![screen shot 2017-08-11 at 9 29 46 am](https://user-images.githubusercontent.com/6561797/29215255-47e8d466-7e78-11e7-95a0-a920c2729582.png)

**Comment by jonathanKingston** [comment]
That status has since been removed and simplified.
Please reopen if this is still an issue which it shouldn't be now.
Thanks.
