### ISSUE TITLE
Softlock when clicking menu button on new tab page

### ISSUE THREAD

**Issue by Kilobyte22** [mozilla/multi-account-containers#732]
How to Reproduce:
1. Open New Tab
2. Immediately click the 'Containers' menu button
(Does not happen after manually navigating to about:newtab)

Expected Behaviour:
The menu opens up and gives you options to interact with containers

Actual Behaviour:
The button gets stuck, the menu does not open. It becomes impossible to close the tab or use the url bar (and potentially the rest of the menu bar, haven't checked). Browser needs a restart to fix the issue.

**Comment by TanviHacks** [comment]
Is this still an issue?

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
