### ISSUE TITLE
Pages content disappear when restarting Gnome

### ISSUE THREAD

**Issue by ibahnasy** [mozilla/multi-account-containers#740]
On Gnome Shell 3.24 and Firefox 55.0.2, if there are pages already opened in the containers then I restarted the Gnome Shell by (alt + F2) and entering 'r'; those pages content become blank.

Refreshing the page doesn't solve it but opening the same URL in a new container tab works fine or restarting the whole browser.

**Comment by jonathanKingston** [comment]
Hey I dunno anything about gnome shell are you able to provide what version of the extension you are using?

**Comment by ibahnasy** [comment]
It's Testpilot containers 3.1.0.

Regards,
Islam Bahnasy

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
