### ISSUE TITLE
Containers Appears To Have Stopped Working With Another Add-In - Vetical Tabs 

### ISSUE THREAD

**Issue by gspeyrer** [mozilla/multi-account-containers#742]
Upon the initial install of Containers, the product worked well with Vertical Tabs; another add-in.

When right-clicking on vertical tabs, an option in the menu would allow for a new container to be chosen and opened.

Then, about three weeks ago, the above function stopped working.

Uninstalled an reinstalled Vertical Tabs with no success.

Any assistance would be appreciated.

Thanks

**Comment by jonathanKingston** [comment]
Can you provide a link to the exact extension you are using? about:support
lists all your extensions too this information might help too.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. The information requested here was not provided, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
