### ISSUE TITLE
Opening a container websites shifts the 'New Tab' button

### ISSUE THREAD

**Issue by d-alleyne** [mozilla/multi-account-containers#744]
To replicate:
1. Have a website associated with a container
2. Start a new instance of Firefox, where it is set to open a blank page once opened.
3. Open the associated website from the address bar.

Expected Result: The associated website opens on the left of the 'New Tab' + button
Actual Result: The associated website opens to the right of the 'New Tab' + button

![image](https://user-images.githubusercontent.com/31164683/29488796-28210ec8-84e0-11e7-9006-32f55c8a97a3.png)

**Comment by collectorgeneral** [comment]
Also related:
Having **only one tab** (any container or default) and clicking the containers addon, "Sort Tabs" will also result in the same situation (that is the new tab goes front of the all the tabs and stays there).

**Comment by jonathanKingston** [comment]
That is pretty odd, it likely will be a platform issue.
Could you answer these:
What version of the extension are you using?
What OS are you using?
What version on firefox are you using?
Thanks

**Comment by collectorgeneral** [comment]
@jonathanKingston 
Woopsy daisy, I was too sleepy to comment! Forgot basic details.

[Troubleshoot Information](https://ghostbin.com/paste/fdp8d)

**Comment by d-alleyne** [comment]
I was using Firefox 54.0.1 yesterday. I have since updated to Firefox 55.0.2 and no longer have the issue.

**Comment by collectorgeneral** [comment]
My current version is 55.0.2 and I can still reproduce the issue. 
@d-alleyne  What platform are you using? Is it OSX?

**Comment by d-alleyne** [comment]
I'm using Windows 10 64-bit, along with the 64-bit version of Firefox.

**Comment by collectorgeneral** [comment]
So then my issue can be possibly unrelated.

Can you reproduce the steps I had in my first comment. Just have one tab open from any container, go to containers addon and hit "Sort tabs". Does it end up with the same result?

**Comment by d-alleyne** [comment]
@collectorgeneral I am able to reproduce your issue.

**Comment by collectorgeneral** [comment]
@d-alleyne Thanks, I could reproduce it on my Windows work PC as well
@jonathanKingston Based on the information so far, it appears to be platform independent since it is reproducible both on Windows on Linux platforms. Although this issue is slightly different than the original issue. We can continue investigating this in this issue over here or if you want a new issue can be opened.

**Comment by boltwatts** [comment]
Same issue here.

Firefox 55.0.2 (64-bit) on Windows 10

**Comment by TanviHacks** [comment]
This is fixed.
