### ISSUE TITLE
"Containers" panel is wrongly displayed when it's pinned to the Overflow Menu

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/multi-account-containers#766]
**Notes**
- "Pin to Overflow Menu" functionaly was implemented by the Photon restructure.
- There is a noticable delay when the "Containers" panel is displayed from the overflow menu.

**[Affected versions]:**
- Nightly build (57.0a1-20170824100243)

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest Containers add-on version (3.1.0-dev 08/25/2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Right-Click on the "Containers" toolbar button.
3. Choose the "Pin to Overflow Menu" option.
4. Click the ">>" toolbar button and click the "Containers" option.
5. Observe the "Containers" panel in the overflow menu.

**[Expected result]:**
- The "Containers" panel is correctly displayed.

**[Actual result]:**
- A blank space is displayed at the right side of the "Containers" panel.

**[Additional Notes]:**
- Attached a screen recording of the issue.
![containers_overflow_menu](https://user-images.githubusercontent.com/20083658/29719922-c4b5b09c-89c0-11e7-95c1-0b910a2f6e56.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This also happens when you resize the browser.
[Notes]
- I tested this issue on Windows 10 x 64, latest Nightly 57.0a1, Build ID: 20170906100107
- See the behavior here:
![resize](https://user-images.githubusercontent.com/31244235/30118221-2618bdc0-932b-11e7-963a-72058b8e3cc0.gif)
