### ISSUE TITLE
No funciona en windows 10

### ISSUE THREAD

**Issue by FabianIsaac** [mozilla/multi-account-containers#767]
Tengo la version 55.0.2, first offered to Release channel users on August 16, 2017 de firefox y la version de windows 10 Home Single lenguage y no funciona del todo, me deja crear containers pero no puedo abrirlos ...esto no me pasa en OSX. Intentare probarlo en otro computador de mi oficina a ver si pasa lo mismo.

**Comment by jonathanKingston** [comment]
Unfortunately nobody on the team speaks Spanish however it sound like you are unable to open containers?
Would you be able to test again as it has been quite some time since you sent this in and a lot has changed in the addon.

Thanks
