### ISSUE TITLE
Can't seem to write reviews on google maps

### ISSUE THREAD

**Issue by gutsle** [mozilla/multi-account-containers#768]
Looks like they are opening popups and other shenanigans which might break in the presence of containers.

**Comment by SoftVision-EmilPasca** [comment]
Hi @gutsle can you please give us more details about your system, such as what Firefox version you have installed, operating system and other addons you may have installed?

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
