### ISSUE TITLE
icon-free

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/multi-account-containers#771]
I don't need a circle, a fingerprint or any other icon. The name alone suffices. 

Please allow users to have containers without icons.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-584)

**Comment by jonathanKingston** [comment]
I disagree, I don't think we would do this either personally. Will leave open for people to vote on though.

**Comment by grahamperrin** [comment]
To clarify: a user preference, not a default.

**Comment by jonathanKingston** [comment]
User prefs are overused and require maintenance I disagree with using them for every tiny feature.

**Comment by grahamperrin** [comment]
Icons are overused … etc. ;-)

**Comment by jonathanKingston** [comment]
> WebExtensions APIs allow someone to develop an extension to suppress things such as colours, icons and over/underlines?

Possibly, perhaps less likely than a pref though. Again leaving this open for voters.

**Comment by jplatte** [comment]
As somebody who has only one container out of six that doesn't have a circle "icon", I don't particularily care whether I can disable them fully or not. But tbh I don't really see the point in having them in the first place. I always identify the container a tab is in by the tabs color, no matter if it is focused or not. I never pay attention to the container text + icon in the address bar.

**Comment by MichaelTunnell** [comment]
My two cents: I don't really care whether the icon is there or not because it takes up very little space and since it is in the far right side of the address bar I usually barely even notice it.

I would rather color options be HEX based so I can choose specific colors. I think that would be better for identification as I only use the tabs like @jplatte described to identify which one it is and I have multiple containers that would be a shade of blue so because I can't do different shades I have different colors that throw me off on occasion.

**Comment by grahamperrin** [comment]
> … color …

Please join the discussion at [Let users set custom colors · Issue #391 · mozilla/testpilot-containers](https://github.com/mozilla/testpilot-containers/issues/391) – thank you.

**Comment by grahamperrin** [comment]
An example. 

After adding (to a clean profile) some of the extensions that I use often, plus one more container-related extension that I found today: 

![2017-09-10 08 07 14](https://user-images.githubusercontent.com/192271/30247011-8f0651ac-9601-11e7-9c3d-6f07f242c1c5.png)

– the URL is invisible and the reload button is pushed partly beyond the boundary of the field. 

After moving a couple of items from the toolbar, to the menu: 

![2017-09-10 08 09 25 how do i install - activate - run container tabs in firefox firefox support forum mozilla support - mozilla firefox](https://user-images.githubusercontent.com/192271/30247015-bcb8f064-9601-11e7-802e-d4e181c48db2.png)

After moving the search field from the toolbar, to the menu: 

![2017-09-10 08 12 23 how do i install - activate - run container tabs in firefox firefox support forum mozilla support - mozilla firefox](https://user-images.githubusercontent.com/192271/30247016-c0d70d16-9601-11e7-8f15-b07c6250c041.png)

– still no sight of the tail of the URL. 

There we have four add-ons that can not function without taking space from the location field, and Mozilla's is the greatest hog; not a good precedent. 

Allowing the user to not show the icon in the location field will make the extension less troublesome in cases such as this.

**Comment by grahamperrin** [comment]
![2017-10-03 16 49 44](https://user-images.githubusercontent.com/192271/31135130-022b4fc2-a85c-11e7-9eec-23abe02206c3.png)

… top right, ah, that's better `:-)`

Just a little wasted space where previously there was an icon …

## Side note

After editing [`containers.js`](https://github.com/mozilla/multi-account-containers/wiki/Debugging-containers#wiki-body) I found it necessary to quit Firefox for the edition to become effective. (I could have experimented with a less disruptive workaround, but a quit was timely for other reasons.)

From <https://github.com/mozilla/multi-account-containers/issues/772#issuecomment-325522532> (2017-08-29) under _inconsitencies of colour and name · Issue `#772` · mozilla/multi-account-containers_: 

> … require a platform fix.

For Firefox 56.x (affected) I'll seek or raise something in Bugzilla@Mozilla. Or @jonathanKingston do you have a link handy? TIA.

**Comment by aaguptaayush** [comment]
where did i add css file in the project

**Comment by grahamperrin** [comment]
https://github.com/mozilla/multi-account-containers/issues/771#issuecomment-325522722

> … an extension to suppress things such as colours, icons and over/underlines?

[Containers Helper](https://addons.mozilla.org/addon/containers-helper/) makes it easy to stop the colour variations, with one exception: 

* https://github.com/charles-m-knox/firefox-containers-helper/issues/12

**Comment by dannycolin** [comment]
This is a design choice from Firefox and there isn't a lot we can do on our side especially for the address bar.
