### ISSUE TITLE
Decommission "containers" page.

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/multi-account-containers#785]
Once Containers graduates to a new name (https://github.com/mozilla/testpilot-containers/issues/763) and a new distribution platform (AMO), we should decommission its page on testpilot (https://testpilot.firefox.com/experiments/containers).

I support the new naming initiative. I also expect that giving it a new name will _lose_ some of its fans, who just get confused. We can help them via this decommissioning project.

* We can write some triumphal copy about what a great outcome "graduation" is for any testpilot experiment.
* We can add some imagery suggestive of graduation hoopla.
* We can make a big (gigantic, actually) link to the addon with its shiny new name.
* We can explain why the new name makes sense.

An approach like this will help with the UX for people who already know about this feature and call it "containers" and might do something for SEO too.

**Comment by jonathanKingston** [comment]
I don't think users will be super confused as they all should be getting the update to whatever we call it. But certainly whatever graduation work @johngruen does should account for this.

John will this happen at the same time as launch?

**Comment by johngruen** [comment]
Hey guys, we are landing new UI this sprint to link out to graduation reports. 

That work is being completed here: https://github.com/mozilla/testpilot/pull/2875

Once this lands and we've got the blog post up, we can toggle over the experiment to complete.

**Comment by jonathanKingston** [comment]
Closing as this happend.
