### ISSUE TITLE
Hacks post

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/multi-account-containers#805]
We should write a hacks post about Containers since it's a unique platform feature. We can link to our extension as a canonical implementation, and talk about opportunities that we see for other extension developers.

**Comment by jonathanKingston** [comment]
This is already in process feel free to discuss with me. Thanks for raising.

**Comment by groovecoder** [comment]
Assigned to @jonathanKingston and added to AMO Launch milestone.

**Comment by jonathanKingston** [comment]
Closing as this happened.
