### ISSUE TITLE
Sort tabs in FF 57 moves the plus button to the far left

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/multi-account-containers#813]
Using the addon in FF 57, when i click "sort tabs" the plus button that is usually on the right most side moves all the way to the left.

**Comment by jonathanKingston** [comment]
Looking into this but likely is a web-ext problem

**Comment by jonathanKingston** [comment]
@TanviHacks does this still happen. I can't replicate it?

**Comment by wanderview** [comment]
I just reproduced this in FF57 beta.  I had a single non-container tab open.

**Comment by jonathanKingston** [comment]
@wanderview have you ever had the drawer icon in your bar? I have a bug to fix with that. Other than that this is all web components.
Also what version of the extension are you using?

**Comment by wanderview** [comment]
I've had this beta profile for a while, but I've never used containers in it before today.

I installed the extension this morning from:

https://github.com/mozilla/multi-account-containers/releases/latest

And coincidentally, that was the one non-container tab I had open when I saw this.

I also had edited my containers a bit before hitting sort.  I thought maybe the "sort" function would let me reorder them in the list.  I had deleted all my containers and added a couple back to the get the list ordering I prefer.

**Comment by Softvision-MariusComan** [comment]
I've managed to reproduce this issue as described below:

**[Affected versions]:**
- Firefox 55 and up
- Multi-Account Containers 3.1.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with "Multi-Account Containers" add-on installed.
- To reproduce the issue only one tab must be opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Containers" button from the browser toolbar.
3. Click the "Sort Tabs" button and observe the behavior of the "Open a new tab" button.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- The "Open a new tab" button is moved in the left corner.

**[Notes]:**
- Attached a screen recording of the issue:
![open new tab button](https://user-images.githubusercontent.com/31243259/30958454-df0cf5be-a445-11e7-8f8c-4a2f95cb374f.gif)

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
