### ISSUE TITLE
AMO addon compatiblity discrepancy

### ISSUE THREAD

**Issue by LoneFenris** [mozilla/multi-account-containers#819]
The readme on Github states the required Firefox version is 53+, but the addon on AMO states it's compatible with 51.0a1+. Trying it on 52esr, the functionality of the addon appears incomplete. 

The addon button added to the Location bar doesn't work, nor does the menu shown on the "Open a new tab" (+) button. The "Open Container Tab" button added to the hamburger menu *does* seem to work, though.

**Comment by groovecoder** [comment]
53+ is correct. There's a PR for this already (https://github.com/mozilla/testpilot-containers/pull/800) but it seemed to cause side-effects so we haven't merged it yet.

**Comment by jonathanKingston** [comment]
This is a dupliacte of #692
@groovecoder the latest PR doesn't change the ID so should be safer.
