### ISSUE TITLE
Provide an option to remove/disable the keyboard shortcuts

### ISSUE THREAD

**Issue by vyings** [mozilla/multi-account-containers#823]
#668

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-592)

**Comment by iology** [comment]
PS. I don't think this shortcut is needed, because I still need to move my mouse into the panel.

**Comment by jonathanKingston** [comment]
There is a bug for better keyboard support somewhere however you should be able to tab through it. (currently firefox requires a first tab to get into the panel, which there is also a bug for).

Let me know if that still doesn't work for the shortcut.

**Comment by iology** [comment]
But I have this shortcut for my system input method, so I would wait for this feature.

**Comment by iology** [comment]
More details: `Ctrl`+`.` is a very famous IME shortcut to toggle Chinese/European language punctuation.

**Comment by jonathanKingston** [comment]
There is work in Firefox itself to expose what extensions are modifying in terms of shortcuts, it likely would be better to leverage that change. Currently an extension can't make an optional change to it's shortcuts which is essentially what you are asking for here.

**Comment by iology** [comment]
Good news. But this shortcut has not been documented, right? It is a surprise to people of both sides.

**Comment by lutoma** [comment]
This is hugely annoying because it conflicts with the default shortcut used by the 1Password extension. While I can change that shortcut, I'd much rather remove the Multi Account Containers one which I never use.

**Comment by rubenwardy** [comment]
> This is hugely annoying because it conflicts with the default shortcut used by the 1Password extension. While I can change that shortcut, I'd much rather remove the Multi Account Containers one which I never use.

Sorry for the bump. As a workaround, you can disable MAC and renable it. This puts it at a lower priority than 1Password, and so 1Password gets the key binding

**Comment by rubenwardy** [comment]
Ok, that doesn't work after a restart. I'm just going to disable multi account containers

**Comment by rubenwardy** [comment]
Turns out you can change shortcuts in Firefox already - this issue can be closed.

1. Go to the [add-ons manager](about:addons) > extensions
2. Click the settings cog in the top right.
3. Select "Manage Extension Shortcuts".
4. Find "Multi Account Containers" and click the trash icon next to ctrl+period.

**Comment by dannycolin** [comment]
For the official documentation https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox.

Closing now.
