### ISSUE TITLE
Multi-Account Containers addon - Add option to color whole tab to indicate container type

### ISSUE THREAD

**Issue by johngruen** [mozilla/multi-account-containers#828]
Copying the Test PIlot repo. Filed by @vardoger

> The current, and only, option for a Multi-Account Container tab is to underline the tab with a specific color.

> With multiple addons installed, and the bloom of color from websites broadly, page text, page pictures, and addon icons, the tab underline feels like it fades into the background and is not as easily identifiable when juggling multipe accounts.

> While the underline option should stay for those who perhaps prefer that more minimalist feel, there could be a checkbox option added in the Multi-Account Container toolbar dropdown menu to enable coloring the whole tab the color of applicable container type.

> This may aid more easily seeing the segmentation of different container types across multiple tabs.

**Comment by klint** [comment]
There is a very nice addon that does that but that requires FF57. Quite useful!

**Comment by jonathanKingston** [comment]
This extension implements this feature: https://addons.mozilla.org/en-GB/firefox/addon/containers-theme/

WebExtensions might also allow per tab colouring which you can probably expect setting / another extension from myself.

I don't think we will be implementing this here.

**Comment by groovecoder** [comment]
Please check out the containers theme add-on for this feature. Won't be uplifting it to the core experience here.
