### ISSUE TITLE
Misleading translation and default icon of personal container

### ISSUE THREAD

**Issue by kapep** [mozilla/multi-account-containers#838]
The default personal container name is translated as "Privat" in German. This is really misleading because of the similarity to private windows. In German, "Privat" is actually a good translation (as antonym to "Arbeit" ("work")) but to avoid confusion a better translation would be "Persönlich".

Its worst in the context menus, where "Link in neuem Privat-Tab öffnen" ("Open link in new private tab") is right above "Link in neuem privaten Fenster öffnen" ("Open link in new private window"). It really sounds like both tab and window used for the same thing.

The fingerprint icon is probably supposed to present something like _identity_ but since that symbol is also often used in the context of privacy, it doesn't really help here to show that the personal container is not about privacy.

I suspect that a similar issue could exist with other languages too. I think it would help to choose another icon, e.g. icon of a user (something that looks like U+1F464) or anything that better represents personal but not private activity.

**Comment by groovecoder** [comment]
@jonathanKingston - sounds like this should also be filed up-stream to the core Firefox feature?

**Comment by jonathanKingston** [comment]
@groovecoder yeah I also don't know where this even happens though. We have had similar bugs.

**Comment by kapep** [comment]
I have created a bug report for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1406076

**Comment by kapep** [comment]
The issue has been fixed in Firefox. The container is now called "Freizeit" ("free time" or "leisure time").
