### ISSUE TITLE
The icon remains disabled(gray)

### ISSUE THREAD

**Issue by ilmoralito** [mozilla/multi-account-containers#842]
The icon remains disabled after installing the add-on

OS: ubuntu 16.04
Firefox version: 55.0.2 (64-bit)

**Comment by jonathanKingston** [comment]
Do you mean the addon doesn't work or just that it is dark in colour? The icon colour will be fixed in dark themes in 57.

Please reopen if this isn't the issue.

**Comment by ilmoralito** [comment]
Hi @jonathanKingston thanks for answering, the icon remains disabled it does not work so i cant interact with it.

**Comment by ilmoralito** [comment]
Its enabled now

This is the process that follows first install the plugin from about: addons, it installs without newness but it remains deactivated which prevents it from being able to interact with it.

To repair it enter firefox test pilot, from there look for container that appears enabled then from the option to manage disable and enable again, after that the icon is activated and allows me to interact with the plugin
