### ISSUE TITLE
Title of current tab and Assignment taking up too much real estate

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/multi-account-containers#844]
When I want to open a new container tab, I open the popup menu.  I want to pick which Container to open, but first I am distracted by a favicon and large text.  What is that?  Then I realize, it's the page open in my current tab.  Then I move on to finding the right Container to open.

The favicon and large text for the current tab is too big and distracting.  Most of the time, the user isn't trying to assing the page.  And if they are, they dont' necessary need it to be so large and they arguably don't need the favicon at all.

Can we make this text smaller?  Maybe even move it to the bottom of the UI?

Marking as High priority, but feel free to disagree with me on that.

Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-600)

**Comment by TanviHacks** [comment]
@fangshih - What do you think?

**Comment by jonathanKingston** [comment]
>  slight variation on containers menu when in a container vs out in default land.
I think users are still going to want to create a container when in a container, so changing that might be odd.

However I agree maybe removing it from default might be an option. We have another feature request to allow users to assign to default #503 and I just added another which is also similar: #847 

Other assignment bugs:
https://github.com/mozilla/testpilot-containers/labels/assignment

#503 is to allow the user to assign websites to not open into the container I am in, which prevents accidents. #847 is the same direction but is to make assignment of the container an allowlist, throwing everything else into default (I'm a little worried about the security gurantees that might make the user think they have, but other than that it is something I want).

To answer your comment @hoosteeno I think assignment is really useful for:
- When you want a don't really want a page to use the logged in version of your account, like github. Assigning means links work fine and open in a github tab but pages iframing, having twitter links don't use your cookies.
- 99% of the time you use the account in one container and it helps force your link clicking to go there, this could be to:
  - no authed account (increasingly I think logging in with work, then assigning to "dead container" is smarter although super complex to explain to people)
  - authed account

**Comment by ChenMorpheus** [comment]
@TanviHacks I checked the measurement and found that we might be able to solve the problem by fine-tuning the UI. In the attached screen, you can notice that the options of containers are bigger than the current implementation, and the current tab section and the rest area are visually more balanced. 

Besides, there are reasons why we decided to put more weight on the current tabs: 
1. It needs a clear way to allow users to assign tabs and "know" what they've just assigned, especially when users assign by context menu.

2. Compared to the list of containers, which are an overview of all containers, this section plays an important role to introduce the attribute of the current tab.
 
![image](https://user-images.githubusercontent.com/18019946/31114424-9b970900-a850-11e7-9b32-ac08b5ed6f67.png)
![image](https://user-images.githubusercontent.com/18019946/31114480-de9d0678-a850-11e7-9687-ca69e3d5993e.png)

**Comment by dannycolin** [comment]
Closing since we don't show the current tab title in the UI anymore.
