### ISSUE TITLE
Document use cases

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/multi-account-containers#846]
The extension gets rave reviews from almost everyone. Most of the poor reviews are 1-star reviews by people who are unclear on one of these questions:

* what problems is it great for?
* how do I use it to solve those problems?

We should document use cases. The fastest path to comprehension for most is probably a screencast showing a specific use case (e.g. start from vanilla profile and take users through the use case, "I always want LinkedIn to open in a LinkedIn container"). It would be great if superfans of containers would consider submitting screencasts of their own use cases for potential inclusion on the addon page.

**Comment by jonathanKingston** [comment]
I know @TanviHacks was working on this, some of this is also in my post and some of why we can't do things are here: https://github.com/mozilla/testpilot-containers/wiki/Moving-between-containers

**Comment by jonathanKingston** [comment]
- When you want to keep like minded auth together without letting normal pages track you (so I sign into my work container with sso, however when browsing google search, maps etc in a default container I don't get tracked)

Also #428

**Comment by hoosteeno** [comment]
I reached out to @dustindriver about producing a couple how-to videos for this. Turns out Dustin's team has some goals that relate to producing content that sends people to AMO, hooray for serendipity.

Dustin's goals relate to publishing on Hacks, as I understand it. And Jonathan has a Hacks post in the works, as I understand it. Let's get on the same page about all that.

@TanviHacks has a list of user stories that we can pull the most common, general cases from as a starting point for scripts. I can help Dustin refine those for screencast.

I'm not convinced that Hacks audience is the exact audience we need to hit with "how-to" content, but once the videos are made and hosted, we can link to them from the AMO page and hopefully convert some of those 1-star reviewers.

**Comment by grahamperrin** [comment]
[An overview of Containers for add-on developers ★ Mozilla Hacks – the Web developer blog](https://hacks.mozilla.org/2017/10/containers-for-add-on-developers/) (2017-10-03) via https://twitter.com/KingstonTime/status/915231187139952640 and https://twitter.com/mozhacks/status/915234318502445057 

[An Update on Firefox Containers | Tanvi Vyas](https://blog.mozilla.org/tanvi/2017/10/03/update-firefox-containers/) (2017-10-03) via the retweet under https://twitter.com/grahamperrin/status/915284556374319104

**Comment by jonathanKingston** [comment]
@hoosteeno can we close this off or do we need to keep tracking this / documenting it?

Is there worth in writing down where we thing containers could be improved for use cases? And use cases we think are explicitly out of scope?

**Comment by hoosteeno** [comment]
I think we can close this, the gears are in motion.
