### ISSUE TITLE
Unset "Remember my decision for this site"

### ISSUE THREAD

**Issue by lukors** [mozilla/multi-account-containers#848]
I can't find a way to unset "remember my decision for this site". A site that I want to be prompted for which container to use each time I open it now opens without any container, and I can't seem to find a way to re-activate the prompt.

**Comment by falolaf** [comment]
If you open the widget for any tab there is a checkbox which you can tick/untick.

**Comment by lukors** [comment]
Ah ok, that's a bit confusing that I have to assign it to something. I thought I could tell it to just ask me when I open a site.

Thanks!
