### ISSUE TITLE
have fewer than three different names for the one extension

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/multi-account-containers#850]
[Containers name · Issue #763 · mozilla/multi-account-containers](https://github.com/mozilla/multi-account-containers/issues/763) and https://github.com/mozilla/multi-account-containers/commit/734b97beb05e8404f46a4259b351b6d037e1c5d0 changed the name: 

- from _Containers_
- to _Firefox Multi-Account Containers_

[Uncomfortably long context menu entry text · Issue #809 · mozilla/multi-account-containers](https://github.com/mozilla/multi-account-containers/issues/809) and https://github.com/mozilla/multi-account-containers/commit/80661d68f240e55ae81b72b9010576eb0baa79e0 changed the name of the name of the context menu item for the extension: 

- from _Firefox Multi-Account Containers_
- to _Containers_

https://addons.mozilla.org/addon/multi-account-containers/versions/ does not show a change of name but there's a mismatch, the name has changed. I browsed four areas of my long list of extensions, it was: 

- not listed alphabetically under C amongst enabled extensions
- not listed alphabetically under C amongst disabled extensions
- not listed alphabetically under F amongst enabled extensions
- not listed alphabetically under F amongst disabled extensions

Eventually I realised, the name of the extension has changed: 

- from _Firefox Multi-Account Containers_
- to _Multi-Account Containers_

– and the AMO page shows an outdated name (beginning with **F**). 

I preferred the original name (**of** the extension) – simply _Containers_ – until, around a week ago, I realised that Containers has become a feature of Mozilla Firefox (**without** the extension) …

**Comment by jonathanKingston** [comment]
"Containers" is a Firefox feature, like tabs is.

Firefox Multi-Account Containers is the name we use on addons.mozilla.org and that name is so people searching can find it more. The name also explains further what containers are used for: https://blog.mozilla.org/firefox/introducing-firefox-multi-account-containers/

Likely if you were using the extension you might have seen various versions of the name as you mention.

Within the extension we drop the "Firefox" keyword to make menus smaller etc.

We won't be changing the name back, as you mention Containers is a core feature. The extension doesn't need the same name. The addon is designed for general population and so needs to be as self explanatory as possible.

I'm going to close this as this was the name we decided upon with the marketing, addons and communications teams.

**Comment by klint** [comment]
One question though: will the extension be decommissioned at some point, as containers are a core feature (hence no need of add-on for that)? Or? ☺️ thanks

**Comment by jonathanKingston** [comment]
There is a possibility that the extension here might become a sytem addon if enough people like it yeah. We aren't sure on where containers will grow to etc.
