### ISSUE TITLE
Bump compatibility to include Firefox 58

### ISSUE THREAD

**Issue by canuckistani** [mozilla/multi-account-containers#852]
58 is in nightly, we should support it probably :)

**Comment by jonathanKingston** [comment]
Hey @canuckistani there isn't actually any limitation here based on max-version

As mentioned here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1402342
There is an issue with AMO not supporting us filed here: https://github.com/mozilla/addons-server/issues/6424

I also emailed dev-platform and we should be doing some more posts here to clear up some of the confusion.

I'll change the README to include 58 also, thanks.

**Comment by groovecoder** [comment]
Closing because I think this is referring to the AMO bug. The add-on itself installs and runs fine in 58.

**Comment by groovecoder** [comment]
In fact, AMO just merged a fix for this:

https://github.com/mozilla/addons-server/pull/6487

So by Thursday this should be cleared up.
