### ISSUE TITLE
Removed container is still displayed in the "Multi-Account Containers" panel until it is reopened

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/multi-account-containers#856]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version 4.0.2 installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click on the "Multi-Account Containers" button from the toolbar.
3. Click on the "Edit Containers" button.
4. Choose a container and click on "Delete container" button (trash bin icon).
5. Press "Tab" key two times (three times on Mac and Linux).
5. Press "Enter" key and observe the "Multi-Account Containers" panel.

**[Expected result]:**
- The removed container is no longer displayed in the containers panel.

**[Actual result]:**
- The removed container is still displayed in the containers panel.

**[Notes]:**
- If you click on the "Ok" button the container is removed from the panel.
- Attached a screen recording of the issue:
![delete containers](https://user-images.githubusercontent.com/31243259/30818135-62343346-a223-11e7-958c-4f03639f7e25.gif)

**Comment by jonathanKingston** [comment]
Appears to be that the enter handler fires twice where as clicking doesn't. This throws an exception which is handled but not through the same code path resulting in code that works but doesn't remove the row we want.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Firefox Multi-Account Containers version (4.0.2 built on 09/27/2017), retested on Windows 10 x64 and Mac OS 10.12 on Firefox Release (53.0.3) and latest Nightly (58.0a1-20170926220106).
