### ISSUE TITLE
Can't find the Container Drawer in FF57

### ISSUE THREAD

**Issue by klint** [mozilla/multi-account-containers#860]
I just have installed FF57b3 as Developer Edition and I'm trying to activate containers. Rather a mystery to me :)
What I succeeded so far (without joining the pilot):
- No option in FF settings for containers by default
- The official addon for containers is not available in the search results
- Yet if I install another container-related addon, then the option appears in the settings and is activated
- But I can't find the drawer icon
Thanks

**Comment by groovecoder** [comment]
It should be way less confusing after Thursday. tl;dr:

* Only Nightly has the option in FF settings
* Official addon should start showing up in search results Thursday
* Other container-related addons can enable Containers, but don't include this add-on's UI/drawer icon
