### ISSUE TITLE
drawer menu is not properly scaled on second monitor

### ISSUE THREAD

**Issue by wanderview** [mozilla/multi-account-containers#861]
My win10 desktop has two monitors:

1. A 4k monitor at 225% scaling
2. A non-4k monitor at 125% scaling

Trying to use the extension container drawer menu on the second monitor is difficult.  The scaling is not properly detected.  This is what it looks like in FF57 beta:

![screenshot 2017-09-26 11 26 11](https://user-images.githubusercontent.com/1256526/30869034-31fe504a-a2ae-11e7-89c7-aaa89c13e299.png)

It looks correct in windows on the primary monitor.

**Comment by wanderview** [comment]
If you point me at an extension I can try it.  I don't use a lot of extensions normally, so  not sure what would be equivalent.

**Comment by jonathanKingston** [comment]
Maybe HTTPS everywhere? https://www.eff.org/https-everywhere

**Comment by wanderview** [comment]
I tried ublock origin.  It has the same problem.

**Comment by jonathanKingston** [comment]
Sweet so maybe actually an issue with extensions in general. I know we have some scaling issues we can fix but I haven't seen this level of issue before.

**Comment by wanderview** [comment]
I'll file a bug.

**Comment by wanderview** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1403233

**Comment by jonathanKingston** [comment]
/me follows, then closes here.

Thanks @wanderview!
