### ISSUE TITLE
UI elements not working properly in FF57

### ISSUE THREAD

**Issue by kaysond** [mozilla/multi-account-containers#868]
Just installed FF 57.0b3 on Windows 7, and installed 4.0.2 from the github release. In about:preferences, Enable Container Tabs is visible and checked, but there is no message indicating an addon is using it. The Multi-Account Containers button exists, but has no icon (i.e. its a blank, clickable space), and does nothing when clicked. The long press '+'-button behavior appears to work, but I suspect its just the default containers functionality. I also don't get any options to always open a url in a given container. Its almost as if the addon isn't really installed...
Some about:config stuff that looks correct:
```
privacy.userContext.enabled;true
privacy.userContext.extension;@testpilot-containers
privacy.userContext.longPressBehavior;2
privacy.userContext.ui.enabled;true
privacy.usercontext.about_newtab_segregation.enabled;true
```

**Comment by kaysond** [comment]
Seemed to be an issue with the profile. Deleting it and generating a new one solved the problem.

**Comment by groovecoder** [comment]
Sorry it was flaky for you. Closing the issue. Please re-open if you notice it again with some steps to reproduce it.
