### ISSUE TITLE
FF57.0b3 : no drop down to select container when clicking new tab button

### ISSUE THREAD

**Issue by DharmeshPandav** [mozilla/multi-account-containers#869]
no drop down to select container when clicking new tab button

It always open the normal tab without any container 

I am using Firefox Developer Edition 57.0b3 (64-bit) on Mac Os 10.12.6 (16G29)

[It works when I long click on the new tab button, but it should work when i just click or at least an option to configure the behavior of click button or click keyboard shortcut]

**Comment by jonathanKingston** [comment]
This has since moved to a longpress instead of being on hover due to user feedback.

I hope that helps, please reopen if this isn't the issue. Where was it that you read that this would be possible, is there somewhere we missed in explaining?

Thanks!

**Comment by DharmeshPandav** [comment]
can you please add link to the duplicate thread/issue discussion

is it possible to have this option configurable ( longpress or just single click) ?
also, any plan to make this more keyboard friendly (shortcuts to open tab in specific container) ?

PS: all other container and tab groups options are gone after FF57 and really looking forward to something that just works

**Comment by jonathanKingston** [comment]
This is one of many like: https://github.com/mozilla/multi-account-containers/issues/689

As mentioned there: 
>We allow you to change this to a click to open which might be more preferred by changing in about:config privacy.userContext.longPressBehavior to "1".

This might be a valid alternative, there is also a bug to add "no container" when using this mode here, it;s just awaiting uplift: https://bugzilla.mozilla.org/show_bug.cgi?id=1330745
