### ISSUE TITLE
Use photon style icons

### ISSUE THREAD

**Issue by nt1m** [mozilla/multi-account-containers#871]
The edit, delete, subview arrows, + icons are not in photon style. See http://design.firefox.com/icons/viewer/ for photon style icons.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-606)

**Comment by jonathanKingston** [comment]
1. "Customize 16" ![](http://design.firefox.com/icons/icons/new/customize-16.svg)
2. "Delete 16" ![](http://design.firefox.com/icons/icons/new/delete-16.svg)
3. "New 16" ![](http://design.firefox.com/icons/icons/new/new-16.svg)
4. "Back 16" ![](http://design.firefox.com/icons/icons/navigation/back-16.svg)
5. "Subitem 16" ![](http://design.firefox.com/icons/icons/new/subitem-16.svg)
6. "Arrowhead left 16" ![](http://design.firefox.com/icons/icons/navigation/arrowhead-left-16.svg)
7. "Arrowhead right 16" ![](http://design.firefox.com/icons/icons/navigation/arrowhead-right-16.svg)

I think 4,5 are not used anywhere for extensions like ours, however not sure. 6,7 looks closer to ours and match page actions and library features in 57+.

@fangshih or @ChenMorpheus could you confirm if 1,2,3,6,7 are correct replacements for the icons we use in Containers?

**Comment by ChenMorpheus** [comment]
@jonathanKingston Since Fang is occupied with other projects now, we might need more time checking if the redesign of icons is required. However, I would recommend to fine tune the current UI first since the current implementation doesn't follow the specs. Then we can spend time on icons for Photon. Let me know if any questions, thanks.

**Comment by jonathanKingston** [comment]
We have #718 outstanding, I think the bigger issue there is we implemented a slightly older version mid iteration of the designs.

**Comment by ChenMorpheus** [comment]
@jonathanKingston I think Fang had uploaded the latest measurements on Github. But you can find them all here:
https://www.dropbox.com/s/m0nhgq976arlpnh/Confirmation%20page%20spec.png?dl=0
https://www.dropbox.com/s/qircuyc4z9qxzwn/Defualt%20container%20panel%20spec.png?dl=0
https://www.dropbox.com/s/q99t2fbz67qsfbl/Dropdown%20panel%20spec.png?dl=0
https://www.dropbox.com/s/4i4m2kwv9yaibaw/Onboarding%20Spec.png?dl=0

Please let us know if you need us to review the current implementation, thanks.

**Comment by fangshih** [comment]
@jonathanKingston 
Here are the icons that we can update 
![defualt container panel spec copy](https://user-images.githubusercontent.com/4862573/31537939-73dc2546-afc9-11e7-9042-8ede66f1b954.png)

You can also find the assets here: 
https://github.com/mozilla/testpilot-assets/tree/master/Containers/00_Assets

I strongly suggest that we need to update the measurements first. Photon icons will be too tight with current padding. It will be great if we can follow the visual spec first and update everything at once.

**Comment by dannycolin** [comment]
Closing since Photon has been replaced by Proton and there's a patch to update to this new design system that should go live with the next release (probably 8.1).
