### ISSUE TITLE
Document links aren't accessible when not logged in to Google

### ISSUE THREAD

**Issue by Ulexos** [mozilla/multi-account-containers#874]
https://docs.google.com/document/d/1WQdHTVXROk7dYkSFluc6_hS44tqZjIrG9I-uPyzevE8/edit#
for example

**Comment by jonathanKingston** [comment]
Can you explain what you mean not accessible?

**Comment by Ulexos** [comment]
When one wants to open the "Test Pilot Product Hypothesis Document" they
1. have to have a Google account and be logged into one
2. have to request access to the document and wait until access is granted instead of just directly having access aka. the document being publicly available

![image](https://user-images.githubusercontent.com/16191795/30941790-91ec51e8-a3e7-11e7-8eff-f840f03e1375.png)

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
