### ISSUE TITLE
Make sub domains also work for "Always open in this container"

### ISSUE THREAD

**Issue by grssam** [mozilla/multi-account-containers#875]
Would be nice if there is a way to allow all subdomains to also always open in a particular domain.

Currently, I have to manually add a.x.com, b.x.com and c.x.com. What if I just add x.com and have a setting which says "Enforce on subdomains as well".

**Comment by jonathanKingston** [comment]
This is a duplicate of #473 you might want to follow along there as there is more discussion on the implementation issues there.

**Comment by grssam** [comment]
Ah. thanks for the pointer.

**Comment by jonathanKingston** [comment]
Whoops I meant to close this, thanks!
