### ISSUE TITLE
placing about:about in a conainter causes mischief

### ISSUE THREAD

**Issue by JohnLGalt** [mozilla/multi-account-containers#883]
I finally created a fresh profile in Firefox because of the move to WebExtensions.  As a big supporter of Panorama, and then the addon Tab Groups, I tested containers when I first found it but continued to use Tab Groups until it finally just stopped working.

Issue:  Adding about:about to a container, then hiding that container, and later showing the conatiner puts the container into a loop where it continuously opens tabs repeatedly until Firefox hangs.

OS:  Windows 10 x64 Insider Preview build 1709 (17004.1000)
Fx:  58.0a1 (2017-09-29) (64-bit)
Addons:  Test Pilot and conatiners
Profile:  Brand new
Reproducible:  Always.

I tried searching this repository for about:about and only found references to about: in the code of hte addon, nothing in the issues section at all.

**Comment by jonathanKingston** [comment]
Have you tried with 4.x branch? I think this hiding issue has since been fixed there.
Can you check the addon version you have?

**Comment by grahamperrin** [comment]
Not reproducible here with Multi-Account Containers 4.0.3 on Firefox 56.0 (64-bit) on FreeBSD-CURRENT. 

Specifically: 

- the `about:about` page that was present before hiding is missing when the container is shown.

**Comment by groovecoder** [comment]
Closing unless/until we can reproduce on 4.0.3.
