### ISSUE TITLE
When 'Always open in <this> container' is set and confirmed, can't open site if container does not exist

### ISSUE THREAD

**Issue by Kingpeck** [mozilla/multi-account-containers#884]
I had an issue where for some reason, Firefox Dev Edition had reset the containers to the defaults. 

I had created a custom container name and was using it with "Always Open" and had several sites in there.

When the reset occurred (due to update maybe? around 1/Oct/17) it meant that the sites I had specified for this container group could not open this container definition, and closed immediately. If it was the only tab open, the browser would close.

I had a copy of the containers.json file from my profile (as it does not seem to sync with Firefox Sync) so I could use with both Dev Edition and Standard, so the issue is resolved for me (for now).

**Comment by jonathanKingston** [comment]
Can you double check with 4.0.2 that this is still the case, we recently made a code change that should remedy this issue?

Thanks

**Comment by Kingpeck** [comment]
I am currently running 4.0.2, did this update reset the container definitions to default? I'll do a check now by deleting the container definition and copying the json file over again to test.

**Comment by Kingpeck** [comment]
Tested and seems if the definitions change to remove one, it will auto close the tab without opening it properly.

This is on Firefox Dev: 57.0b3 (64-bit) with Version 4.0.2 of the Multi Account Addon.

Is there a different Multi Account Container addon I should be using for Dev Edition?

**Comment by Kingpeck** [comment]
It seems this is fixed in 4.0.3, not 4.0.2. 

4.0.3 isn't coming up in the automatic updates of addons for me yet, might be a matter of time. Once it updates, I will confirm fix for my issue.

**Comment by jonathanKingston** [comment]
@groovecoder I thought we released this? AMO and my version is 4.0.2.

**Comment by groovecoder** [comment]
This is fixed in [the 4.0.3 release](https://github.com/mozilla/multi-account-containers/releases/tag/4.0.3). It's uploaded to AMO but still pending review. You can download + install from the GitHub releases page to get it now.
