### ISSUE TITLE
A container tab can wrongly be moved to a new window even if it's the only opened tab

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/multi-account-containers#885]
**[Affected versions]:**
- Multi-Account Containers 4.0.3
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version (4.0.3) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Open a website in the "Personal" container and close other tabs if they exist.
3. Click on the "Multi-Account Containers" button from the toolbar.
4. Click on "View Personal container" button (>) and observe the "Move tabs to a new window" button.

**[Expected result]:**
- The button is greyed out.

**[Actual result]:**
- The button is active.

**[Notes]:**
- In our opinion this option should be greyed out because its effect uses system resources and does not do anything.
- In the same context, "Move to a new window" option from Firefox context menu is greyed out.
- The issue is reproducible with all containers.
- The issue is also reproducible with the TxP version of "Multi-Account Containers".
- Attached a screen recording of the issue:
![new window](https://user-images.githubusercontent.com/31243259/31081881-eb193b9e-a795-11e7-8d8a-77816f43bb40.gif)

**Comment by TanviHacks** [comment]
If the tab count is 1, grey out the Move to new Window option.

**Comment by ShivangiKakkar** [comment]
Hey! I would love to work on this issue. May I?

**Comment by ShivangiKakkar** [comment]
> Yes, you can certainly work on this.
> 
> Are you able to join the #containers channel on IRC? (IRC help here: https://wiki.mozilla.org/IRC)

Yes 😄 Thanks!
