### ISSUE TITLE
Move Tabs to new window duplicates tabs if all tabs hidden 

### ISSUE THREAD

**Issue by falolaf** [mozilla/multi-account-containers#886]
If all tabs for a given container is hidden, i.e. the container is hidden, Move tabs to new window duplicates all tabs in the new window. If I first do Show this container and then Move tabs to new window, then tabs are not duplicated.

I thought this duplication should have been fixed in 4.0.2!?

Multi account containers: 4.0.2
FF: 56.0
Windows 7

**Comment by SoftVision-EmilPasca** [comment]
Thanks for reporting this issue,  it is also been tracked in [https://github.com/mozilla/multi-account-containers/issues/791#issuecomment-329480413](https://github.com/mozilla/multi-account-containers/issues/791#issuecomment-329480413).
