### ISSUE TITLE
Nightly "Container Tabs" no longer work after you disable the "Multi-Account Containers" add-on from the experiment's page

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/multi-account-containers#889]
**[Notes]:**
- The issue in not reproducible with the TxP version of the "Multi-Account Containers" add-on.
- The "userContext" prefs values are changed to different values.
- I've tried to reproduce the issue on older "Multi-Account Containers" builds and I found out that the issue appeared somewhere between 3.1.1 build from 28.08.2017 and 3.1.1 build from 05.09.2017.

**[Affected versions]:**
- Multi-Account Containers 4.0.3 custom build
- Latest Nightly (58.0a1)

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" (4.0.3) custom build installed.
- Also have the latest "Test Pilot" add-on installed, from https://testpilot.firefox.com/.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Navigate to https://testpilot.firefox.com/experiments/containers and click the "Disable Containers" button.
3. Long press the "New Tab" button and observe the behavior.

**[Expected result]:**
- The Nightly "Container Tabs" context menu is displayed.

**[Actual result]:**
- Nothing happens.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![context menu containers](https://user-images.githubusercontent.com/31243259/31169809-87df61f2-a902-11e7-819b-0fdb0ec3bea6.gif)

**Comment by groovecoder** [comment]
We won't be able to fix this - the 2 add-ons are the same.

Next week we'll publish our Test Pilot graduation post and we'll redirect Test Pilot traffic to AMO so people won't notice this anymore.
