### ISSUE TITLE
Add open tabs to container?

### ISSUE THREAD

**Issue by darsparx** [mozilla/multi-account-containers#890]
Is there any way to add a open tab to a container or something? I kinda miss the tab groups that used to be available years ago, and have been searching for a replacement and this seems to slightly go back to that.

Also shouldn't it also be possible to categorize and only have open what is related to that specific container that you're in? (I open way too many tabs and never go back to them if I bookmark it)

**Comment by neclimdul** [comment]
Not sure if this is the same but I commonly want to move a tab to a container to. I get a link in chat or email and when I click it opens without a container and want to move it to work or something else. Being able to do it directly from a context menu or something would be a _lot_ easier then copying the url, opening a new tab in the container, pasting the url, closing the old tab.

**Comment by SoftVision-EmilPasca** [comment]
@darsparx @neclimdul Thanks for reporting this, however, I think the feature you are requesting has been discussed in #311, please follow that thread for more information.
