### ISSUE TITLE
Feature request: exporting functionality

### ISSUE THREAD

**Issue by v1kn** [mozilla/multi-account-containers#891]
After setting up categories and teaching firefox which sites I want opened in which containers, I'm a bit worried this work will be lost on any new installation. I can't see any easy way to sync, export or back up my current container settings (besides moving around the entire `~/.mozilla` folder, which is not ideal).

Do these settings get synced through Firefox sync service?
if not, I'd like to request some means of backing up or syncing custom settings of this addon.

**Comment by SoftVision-EmilPasca** [comment]
Hi @v1kn , thanks for reporting this, the feature you are requesting has also been discussed here https://github.com/mozilla/multi-account-containers/issues/339#issuecomment-331411399. please follow that thread for more information.
