### ISSUE TITLE
a show of, or hide of, a container's pages is unexpectedly partial

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/multi-account-containers#892]
I can't recall, with certainty, the steps that led to this – sorry – but it's likely that I stumbled across the issue whilst _attempting_ to reproduce issues, elsewhere, in which losses were reported; and so it's likely that what's below was not long after restoration of a session. Possibly/probably a session where the sole container was hidden before quit. 

2017-10-04 06:04:33

![2017-10-04 06 04 33](https://user-images.githubusercontent.com/192271/31195546-9a5d6f64-a942-11e7-8ca4-09b06d04570a.png)

2017-10-04 06:22:50 – as far as I recall, primarily a widening of the window to reveal the name of the container

![2017-10-04 06 22 50](https://user-images.githubusercontent.com/192271/31195618-cd6f71e0-a942-11e7-98c7-6cb13735c1e7.png)

2017-10-04 06:24:46 – probably after clicking _Show this container_

![2017-10-04 06 24 46](https://user-images.githubusercontent.com/192271/31195619-d00bf23e-a942-11e7-9b28-ab01223fdef4.png)

**Comment by Softvision-MariusComan** [comment]
I have managed to reproduce this issue on Windows 10 x64, Ubuntu 14.04 x64, Mac 10.12.6 with the latest Firefox release (56.0.2) and the latest Nightly (58.0a1) build installed.
To reproduce the issue please use the following STR:

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version (4.0.3 custom built on 11.10.2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites 
2. Open a container tab and open any website (e.g. Personal).
3. Open a new window and click the "Multi-Account Containers" button from the browser toolbar.
4. Open a new container tab, same as in step 2, and navigate to another website (e.g. Personal).
5. Hide the container used in step 2&4 and switch back to the first window.
6. Click the "View container" button (">") for the used container.
7. Observe the tabs listed in the container.

**[Expected result]:**
- Both tabs are hidden.

**[Actual result]:**
- One tab is shown and the other one is hidden.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32662002-ad250650-c631-11e7-9efd-babf48acf26e.gif)

**Comment by falolaf** [comment]
Something in the back of my head says that this is kind of expected behaviour with the release of the 4.x versions.
The containers are kind of window centric. I.e. in the second window when selecting the same container no tabs are shown there even if there are indeed tabs open in that container but in another window.

**Comment by TanviHacks** [comment]
Only the container tabs from the current window are hidden.  When you try to hide container tabs from another window, you have to first show the hidden ones.

I believe this is as designed.  We could change the design, but would need UX guidance since this could get quickly complicated.

**Comment by grahamperrin** [comment]
Thanks. I might give this some thought if/when I switch back to Firefox.
