### ISSUE TITLE
Containers menu does not render

### ISSUE THREAD

**Issue by royaldark** [mozilla/multi-account-containers#893]
I installed the Multi-Account Containers addon today, but the containers menu doesn't render correctly:

![screenshot from 2017-10-04 16-13-45](https://user-images.githubusercontent.com/1669397/31200078-288224ac-a91f-11e7-89bf-700734b0d0b5.png)

The browser console logs one error:

```
Error: Failed to retrieve the identities or variation. We cannot continue.   browser.contextualIdentities is undefined:88:13
```

The about:config settings I saw mentioned in other tickets look OK as well:

![screenshot from 2017-10-04 16-12-32](https://user-images.githubusercontent.com/1669397/31200018-e68017e4-a91e-11e7-814a-1a9d9c33c8d7.png)

I am running Firefox 54.0 with Multi-Account Containers 4.0.3 on Linux.

**Comment by jonathanKingston** [comment]
Do you have any add-onscontrolling browser storages? If you disable anything marked as a legacy a add-on does it work?

You can copy the list of add-ons in about:support

**Comment by julienschmidt** [comment]
Manually deleting the files in the profile folder used by this extensions (see https://github.com/mozilla/multi-account-containers/wiki/Debugging-containers) and restarting Firefox worked for me

**Comment by jonathanKingston** [comment]
If you are to take @julienschmidt's approach if you could do the following instead:

1. Delete `[root-directory]/jetpack/@testpilot-containers/simple-storage` 
2. restart Firefox, test
3. Delete `[root-directory]/browser-extension-data/@testpilot-containers/storage`
4. restart Firefox, test
5. Delete `[root-directory]/containers`
6. restart Firefox, test

If you do it in that order, containers should still work between those steps. Stop at 2 or 3 if it starts working again.

**Comment by royaldark** [comment]
Deleting the `simple-storage` directory seems to have done the trick. Thanks!
