### ISSUE TITLE
Assigned links no longer work in Private Browsing Mode

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/multi-account-containers#896]
> When I select a site to open only in one container, I can't open it in a private window anymore. That is not good. Both should work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-612)

**Comment by jonathanKingston** [comment]
So we actually already explicitly do nothing with private windows in terms of assignment due to us not supporting containers in Private mode:

https://github.com/mozilla/multi-account-containers/blob/master/webextension/js/background/assignManager.js#L142

This translates to, if you open an assigned site in private mode, it will open in a normal private tab.

**Comment by prog-amateur** [comment]
Please, could you help me ? it is not clear : I have setup Firefox into "always use private mode". When I open a new Firefox windows, I can see the containers icon, then when I click on one container, nothing happen (no new tab). Also, when I open a new tab, then the container icon is grey (disabled). 

1. Is this behavior normal ? 
2. Does Firefox automatically use container tabs when I am on "Private browsing mode" ?

Thank you

**Comment by SoftVision-PaulOiegas** [comment]
As mentioned by @jonathanKingston above, Containers is not supported in Private Mode and I'm not sure it will be in the future. So the whole functionality will be disabled there.

**Comment by dannycolin** [comment]
As mentioned, Multi-Account Containers doesn't work in Private Mode. Since this issue was filed for a very old version of both the addon and Firefox browser, I'm closing it. If you still experience this issue, please file a new bug.
