### ISSUE TITLE
"edit containers" isn't available when add on is in overflow menu

### ISSUE THREAD

**Issue by brettcurrie346** [mozilla/multi-account-containers#903]
![screen shot 2017-10-10 at 12 38 03 pm](https://user-images.githubusercontent.com/25022168/31396716-92fe275a-adba-11e7-851c-31206160ef4a.png)

{
  "application": {
    "name": "Firefox",
    "osVersion": "Darwin 16.7.0",
    "version": "57.0b6",
    "buildID": "20171005195903",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0",
    "safeMode": false,
    "updateChannel": "aurora",
    "supportURL": "https://support.mozilla.org/1/firefox/57.0/Darwin/en-US/",
    "numTotalWindows": 1,
    "numRemoteWindows": 1,
    "remoteAutoStart": true,
    "currentContentProcesses": 5,
    "maxContentProcesses": 4,
    "autoStartStatus": 1,
    "styloBuild": true,
    "styloDefault": true,
    "styloResult": true,
    "keyGoogleFound": true,
    "keyMozillaFound": true
  },
  "modifiedPreferences": {
    "accessibility.browsewithcaret": true,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.cache.disk.hashstats_reported": 1,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.frecency_experiment": 1,
    "browser.cache.disk.capacity": 358400,
    "browser.download.useDownloadDir": false,
    "browser.places.smartBookmarksVersion": 8,
    "browser.search.useDBForOrder": true,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20171005195903",
    "browser.startup.homepage_override.mstone": "57.0",
    "browser.startup.homepage": "about:home",
    "browser.startup.homepage_override.buildID": "20171005195903",
    "browser.tabs.warnOnClose": false,
    "browser.tabs.extraDragSpace": true,
    "browser.tabs.drawInTitlebar": false,
    "browser.urlbar.lastSuggestionsPromptDate": 20171005,
    "browser.urlbar.timesBeforeHidingSuggestionsHint": 0,
    "dom.push.userAgentID": "dba0ec302a9143d692bd5f9d451717bc",
    "dom.forms.autocomplete.formautofill": true,
    "extensions.lastAppVersion": "57.0",
    "font.internaluseonly.changed": true,
    "media.gmp-widevinecdm.lastUpdate": 1507203143,
    "media.gmp-gmpopenh264.lastUpdate": 1507203137,
    "media.gmp-widevinecdm.version": "1.4.8.1008",
    "media.gmp-gmpopenh264.abi": "x86_64-gcc3",
    "media.gmp-manager.lastCheck": 1507565610,
    "media.gmp-widevinecdm.abi": "x86_64-gcc3",
    "media.gmp.storage.version.observed": 1,
    "media.gmp-gmpopenh264.version": "1.6",
    "media.gmp-manager.buildID": "20171005195903",
    "network.predictor.cleaned-up": true,
    "network.cookie.prefsMigrated": true,
    "places.history.expiration.transient_current_max_pages": 114331,
    "places.database.lastMaintenance": 1507206307,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "privacy.userContext.ui.enabled": true,
    "privacy.usercontext.about_newtab_segregation.enabled": true,
    "privacy.userContext.enabled": true,
    "privacy.userContext.extension": "@testpilot-containers",
    "privacy.userContext.longPressBehavior": 2,
    "security.sandbox.content.tempDirSuffix": "{5e22f944-033f-1046-88dc-1435d6134071}",
    "services.sync.declinedEngines": "",
    "services.sync.lastPing": 1507569538,
    "services.sync.lastSync": "Tue Oct 10 2017 12:49:40 GMT-0300 (ADT)",
    "services.sync.engine.bookmarks.validation.lastTime": 1507483625,
    "services.sync.engine.addresses.available": true,
    "services.sync.engine.prefs.modified": false,
    "storage.vacuum.last.index": 1,
    "storage.vacuum.last.places.sqlite": 1507206307
  },
  "lockedPreferences": {},
  "media": {
    "currentAudioBackend": "audiounit",
    "currentMaxAudioChannels": 2,
    "currentPreferredChannelLayout": "stereo",
    "currentPreferredSampleRate": 44100,
    "audioOutputDevices": [
      {
        "name": "Internal Speakers",
        "groupId": "AppleHDAEngineOutput:1B,0,1,1:0",
        "vendor": "Apple Inc.",
        "type": 2,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 96000,
        "minRate": 44100,
        "maxLatency": 4588,
        "minLatency": 506
      }
    ],
    "audioInputDevices": [
      {
        "name": "Internal Microphone",
        "groupId": "AppleHDAEngineInput:1B,0,1,0:1",
        "vendor": "Apple Inc.",
        "type": 1,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 96000,
        "minRate": 44100,
        "maxLatency": 4162,
        "minLatency": 80
      }
    ]
  },
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0,
    "handlerUsed": false,
    "instantiator": ""
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.17",
      "version": "4.17"
    },
    "NSS": {
      "minVersion": "3.33",
      "version": "3.33"
    },
    "NSSUTIL": {
      "minVersion": "3.33",
      "version": "3.33"
    },
    "NSSSSL": {
      "minVersion": "3.33",
      "version": "3.33"
    },
    "NSSSMIME": {
      "minVersion": "3.33",
      "version": "3.33"
    }
  },
  "userJS": {
    "exists": false
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "contentSandboxLevel": 3,
    "effectiveContentSandboxLevel": 3
  },
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 1,
    "windowLayerManagerType": "OpenGL",
    "windowLayerManagerRemote": true,
    "windowUsingAdvancedLayers": false,
    "adapterDescription": "",
    "adapterVendorID": "0x1002",
    "adapterDeviceID": "0x6821",
    "adapterRAM": "",
    "adapterDrivers": "",
    "driverVersion": "",
    "driverDate": "",
    "offMainThreadPaintEnabled": false,
    "webgl1Renderer": "ATI Technologies Inc. -- AMD Radeon R9 M370X OpenGL Engine",
    "webgl1Version": "4.1 ATI-1.51.8",
    "webgl1DriverExtensions": "GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier",
    "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_sRGB EXT_shader_texture_lod EXT_texture_filter_anisotropic EXT_disjoint_timer_query OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc MOZ_WEBGL_depth_texture",
    "webgl1WSIInfo": "CGL",
    "webgl2Renderer": "ATI Technologies Inc. -- AMD Radeon R9 M370X OpenGL Engine",
    "webgl2Version": "4.1 ATI-1.51.8",
    "webgl2DriverExtensions": "GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier",
    "webgl2Extensions": "EXT_color_buffer_float EXT_texture_filter_anisotropic EXT_disjoint_timer_query OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc",
    "webgl2WSIInfo": "CGL",
    "info": {
      "AzureCanvasBackend": "skia",
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "skia",
      "AzureCanvasAccelerated": 1,
      "ApzWheelInput": 1,
      "ApzDragInput": 1,
      "ApzAutoscrollInput": 1,
      "TileHeight": 1024,
      "TileWidth": 1024
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "opt-in",
              "message": "WebRender is an opt-in feature"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "Build doesn't include WebRender"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  },
  "experiments": [],
  "extensions": [
    {
      "name": "Evernote Web Clipper",
      "version": "6.12.4",
      "isActive": true,
      "id": "{E0B8C461-F8FB-49b4-8373-FE32E9252800}"
    },
    {
      "name": "Firefox Notes",
      "version": "1.8.0",
      "isActive": true,
      "id": "notes@mozilla.com"
    },
    {
      "name": "Markdown Here",
      "version": "2.13.1",
      "isActive": true,
      "id": "markdown-here-webext@adam.pritchard"
    },
    {
      "name": "Min Vid",
      "version": "0.4.5",
      "isActive": true,
      "id": "@min-vid"
    },
    {
      "name": "Multi-Account Containers",
      "version": "4.0.3",
      "isActive": true,
      "id": "@testpilot-containers"
    },
    {
      "name": "OneNote Web Clipper",
      "version": "3.7.2",
      "isActive": true,
      "id": "Clipper@OneNote.com"
    },
    {
      "name": "snoozetabs",
      "version": "1.0.20",
      "isActive": true,
      "id": "snoozetabs@mozilla.com"
    },
    {
      "name": "Test Pilot",
      "version": "2.0.4-dev-18ce799",
      "isActive": true,
      "id": "@testpilot-addon"
    },
    {
      "name": "Tile Tabs WE",
      "version": "6.5",
      "isActive": true,
      "id": "tiletabs-we@DW-dev"
    },
    {
      "name": "ZenHub for GitHub",
      "version": "2.35.41",
      "isActive": true,
      "id": "zenhub@zenhub.io"
    },
    {
      "name": "Dark YouTube Theme",
      "version": "4.1",
      "isActive": false,
      "id": "jid1-hDf2iQXGiUjzGQ@jetpack"
    },
    {
      "name": "Enhancer for YouTube™",
      "version": "2.0.41",
      "isActive": false,
      "id": "enhancerforyoutube@maximerf.addons.mozilla.org"
    },
    {
      "name": "LastPass: Free Password Manager",
      "version": "4.1.54",
      "isActive": false,
      "id": "support@lastpass.com"
    },
    {
      "name": "Lucifox",
      "version": "0.9.14",
      "isActive": false,
      "id": "Lucifox@lucidor.org"
    },
    {
      "name": "Quick Locale Switcher",
      "version": "1.7.8.5.1-signed.1-signed",
      "isActive": false,
      "id": "{25A1388B-6B18-46c3-BEBA-A81915D0DE8F}"
    },
    {
      "name": "Regex Find",
      "version": "1.1.6",
      "isActive": false,
      "id": "regexfind@findbar.org"
    },
    {
      "name": "Super Start",
      "version": "7.4.0.1-signed",
      "isActive": false,
      "id": "superstart@enjoyfreeware.org"
    },
    {
      "name": "Tab Groups",
      "version": "2.1.4",
      "isActive": false,
      "id": "tabgroups@quicksaver"
    },
    {
      "name": "Tile View",
      "version": "6.9",
      "isActive": false,
      "id": "tileview@DW-dev"
    },
    {
      "name": "User Agent Switcher",
      "version": "0.7.3.1-signed.1-signed",
      "isActive": false,
      "id": "{e968fc70-8f95-4ab9-9e79-304de2a71ee1}"
    },
    {
      "name": "VimFx",
      "version": "0.20.10",
      "isActive": false,
      "id": "VimFx@akhodakivskiy.github.com"
    }
  ],
  "features": [
    {
      "name": "Activity Stream",
      "version": "2017.09.29.0895-52552f5e",
      "id": "activity-stream@mozilla.org"
    },
    {
      "name": "Application Update Service Helper",
      "version": "2.0",
      "id": "aushelper@mozilla.org"
    },
    {
      "name": "Firefox Screenshots",
      "version": "19.1.0",
      "id": "screenshots@mozilla.org"
    },
    {
      "name": "Follow-on Search Telemetry",
      "version": "0.9.3",
      "id": "followonsearch@mozilla.com"
    },
    {
      "name": "Form Autofill",
      "version": "1.0",
      "id": "formautofill@mozilla.org"
    },
    {
      "name": "Multi-process staged rollout",
      "version": "3.05",
      "id": "e10srollout@mozilla.org"
    },
    {
      "name": "Photon onboarding",
      "version": "0.1",
      "id": "onboarding@mozilla.org"
    },
    {
      "name": "Pocket",
      "version": "1.0.5",
      "id": "firefox@getpocket.com"
    },
    {
      "name": "Shield Recipe Client",
      "version": "76",
      "id": "shield-recipe-client@mozilla.org"
    },
    {
      "name": "Web Compat",
      "version": "1.1",
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "WebCompat Reporter",
      "version": "1.0.0",
      "id": "webcompat-reporter@mozilla.org"
    }
  ]
}

**Comment by SoftVision-EmilPasca** [comment]
I have managed to reproduce this issue on the latest Firefox Beta (57.0b6-20171005195903) and the latest Nightly(58.0a1-20171010100200) on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 using Multi-Account Containers(4.0.3).

**Comment by jonathanKingston** [comment]
This is a known platform bug in Photon, I don't think we can do anything here to fix it. I think there will be a patch in the coming days.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
