### ISSUE TITLE
When current tab is equal New tab, Always open in [[Container]] checkbox is disabled

### ISSUE THREAD

**Issue by JPabloMD** [mozilla/multi-account-containers#913]
Open a New Tab with in a container. (Either grid homepage, about:blank
Open Multi-Account Containers popup.
Observe the checkbox Always open in [[Container]]

https://github.com/mozilla/multi-account-containers/blob/c1e9cc3c568c40b4ae8e8740301b4d7e88740002/webextension/js/popup.js#L523-L527

I'm not sure if this is the expected behavior, makes sense for setting tabs, but I'm not sure about new tab.

Screenshot.
https://imgur.com/a7Uz5wO
Browser version details.
Version 	56.0.1 and 57.0b9, both 64-bit.
Windows 10
No add-ons (other than Containers)

**Comment by TanviHacks** [comment]
Yes, the checkbox is disabled for the newTab page, since it doesn't make sense to assign that to a Container.
