### ISSUE TITLE
Firefox freezes on high cpu load when clicking Multi-Account Containers icon on the toolbar

### ISSUE THREAD

**Issue by terence4444** [mozilla/multi-account-containers#916]
Sometimes Firefox freezes with high CPU load when I click on the menu to open a new profile tab.
Like this:
![Screen shot](https://wx1.sinaimg.cn/large/006CfXd8gy1fksluogdcij308a015dfo.jpg)

It takes at least 30 seconds to popup the profile selection menu and hangs for another 30 seconds before the menu closes automatically.

I have noticed that this happens when another extension: Request Policy Continued is activated.  I tried disabling Request Policy Continued then everything looks OK. But it is not necessarily happens, only perhaps a day in a week.
Request Policy Continued is an extension for blocking cross site request but I don't find any request sent from Multi-Account Containers.

Could you please help those 2 extensions work together? 

Firefox Version: 56.0.1
Multi-Account Containers: 4.0.3

Thanks & kind regards,

**Comment by terence4444** [comment]
I am not sure "hang" is the correct word, may be I should say "Firefox freeses when clicking the button on the toolbar".

**Comment by TanviHacks** [comment]
Is this still an issue?  Can you test it with Firefox 57+?

Also, is it an issue only with the combination?  Does the issue exist with just Multi-Account Containers installed?

**Comment by terence4444** [comment]
@TanviHacks 
Thank you for the response.

Since Request Policy Continued is not available on Firefox 57+ this problem is gone for good.
Now I am using Privacy Badger instead.

I guess this issue may be caused by network requests (account sync?) blocked by another extension.

Cheers
