### ISSUE TITLE
Feature request: Always open by matching title keyword

### ISSUE THREAD

**Issue by daiheitan** [mozilla/multi-account-containers#924]
Say I created a Rust container and want every webpage containing "Rust" go to the container, it would be nice to have this feature in the addon

**Comment by TanviHacks** [comment]
Actually, this can be easily gamed by a website that wants to track your "rust" data.  They can just add "rust" to somewhere in the url.

Perhaps this can be done in another addon, but isn't suited for multi-account containers.
