### ISSUE TITLE
containers tab background

### ISSUE THREAD

**Issue by staabm** [mozilla/multi-account-containers#925]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Build ID: 20171026221945

Steps to reproduce:

- define 2 containers A & B
- open a url which is configured to always open in container A
- from within this page open a url (hold ctrl to open in background), which is configured to always open in container B

Actual results:

- the tab which opens in the background jumps into the foreground

Expected results:

- the tab which opens in the background should stay in the background, even if containers are switched

Initially reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1412299

**Comment by staabm** [comment]
Might actually be a duplicate of https://github.com/mozilla/multi-account-containers/issues/442

**Comment by ArchangeGabriel** [comment]
Yes, dupe indeed.

**Comment by staabm** [comment]
confirmed, seems fixed
