### ISSUE TITLE
"Multi-Account Containers" toolbar button is wrongly active in Private Window

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/multi-account-containers#930]
**[Affected versions]:**
- Multi-Account Containers 4.0.3
- Firefox 58.0a1

**[Affected Platforms]:**
- All Windows
- All Mac (No longer reproducible 58.0a1-20171102100041)
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version (4.0.3) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Open a new Private Window (Ctrl+Shift+P).
3. Click the "Multi-Account Containers" from the browser toolbar and observe.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- The "Containers" panel is opened.

**[Regression Window on Windows]:**
- Last good revision: 71ea88d938e5d68c5843a3689b5ddc0fda38a063
- First bad revision: dda6098cc5161046af377ef69bae69099255b098
- Pushlog https://goo.gl/eAuBnK

**[Regression Window on Mac]:**
- First good revision: a0334f789772302ba5cfb6fd61290408842c7432
- Last bad revision: 0a50066b2de805de843762b9787b2b3d2d5bf93f
- Pushlog: https://goo.gl/NiAyM4
- It seems that the backed out from this pushlog made the issue no longer reproducible.

**[Notes]:**
- Attached a screen recording of the issue:
![regression](https://user-images.githubusercontent.com/20083658/32330463-deec8d9c-bfe8-11e7-874c-4103db70da0f.gif)

**Comment by Softvision-MariusComan** [comment]
An user can also encounter the following issue if he chooses to show previously hidden containers from a "Private Window":

**[Notes]:**
- This scenario will also break the "Show this container" option when clicked in a normal window.

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version (4.0.3 custom built on 11.08.2017) installed.
- Have a container hidden.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new Private Window (Ctrl+Shift+P) and click the "Multi-Account Containers" button from the browser toolbar.
3. Click the "View container" button (">") placed in the right of the container from prerequisites.
4. Click the "Show this container" option and observe the behavior.

**[Expected result]:**
- The hidden container tabs are displayed.

**[Actual result]:**
- Nothing happens.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32658578-4fc1194e-c623-11e7-97cb-62a01b305379.gif)

**Comment by groovecoder** [comment]
Yes, you can take it. Note: this fix here is *not* to make the extension work in Private Browsing mode - I believe that requires platform-level work.

The fix here is to disable the containers extension icon in private browsing windows.

**Comment by yatri1609** [comment]
@groovecoder I was thinking if we can show a message on clicking the button that this is not supported in Private browsing then it will be good. What do you think?

**Comment by romanrodriguez** [comment]
Hi @maxxcrawford, I'd love to work on this issue for my Outreachy application. :)

**Comment by AlbionaHoti** [comment]
If @romanrodriguez is not available to work on this task, I would want to continue. I am an Outreachy applicant.

**Comment by maxxcrawford** [comment]
@romanrodriguez Please proceed. Assigned! 

@AlbionaHoti You are next in line. 

Thank you both for your interest!
