### ISSUE TITLE
Not an issue - LastPass

### ISSUE THREAD

**Issue by gomopa** [mozilla/multi-account-containers#931]
This is not an issue, but I want to know how to use Multi Acoount Container Addon together with LastPass. I open all my links with LastPass, but don't find any way to open them with my Multi Account containers. #

**Comment by groovecoder** [comment]
I haven't used LastPass recently, but I think the way to start is to assign those sites to a certain Container. Presumably, when LastPass opens them, they will open into the correct container?

@jonathanKingston - does this seem right to you?

**Comment by jonathanKingston** [comment]
Are you talking about the lastpass.com website or the interface in the addon? If you use the web page you can right click to open in a container.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. It looks like the question was answered, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.
