### ISSUE TITLE
Allow user to set default Container to open pages in

### ISSUE THREAD

**Issue by nekromoff** [mozilla/multi-account-containers#936]
Steps to reproduce:
Currently, there is 'no content' container used by default.
Allow user set which container should be used by default to open URLs.

Actual results:
No content container is used

Expected results:
User default container is used

**Comment by SoftVision-EmilPasca** [comment]
Hi @nekromoff , thanks for reporting this. However, this looks like a duplicate of https://github.com/mozilla/multi-account-containers/issues/906.
