### ISSUE TITLE
An extra line is wrongly displayed at the bottom of the panel when editing a container

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/multi-account-containers#939]
**[Affected versions]:**
- Nightly 58.0a1

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version (4.0.3 custom built on 11.09.2017) installed.
- Have six websites assigned to the same container.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Multi-Account Containers" button from the browser toolbar.
3. Click the "Edit Containers" button.
4. Choose to edit a container that has six websites assigned to it.
5. Scroll down and observe the bottom part of the panel.

**[Expected result]:**
- The websites list is scrolled down.

**[Actual result]:**
- The websites list is scrolled down and an additional line is displayed.

**[Regression window]:**
Last good revision: a4fb78381ea0fe9fddd36a8ea7b74a63062a1bf3
First bad revision: 66ef885f0b66cb680a3f0734bfbfd8fd385fa104
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=a4fb78381ea0fe9fddd36a8ea7b74a63062a1bf3&tochange=66ef885f0b66cb680a3f0734bfbfd8fd385fa104

**[Additional Notes]:**
- The issue is reproducible only if you have six websites assigned to the same container.
- The issue is still reproducible if you scroll the list up after step 5.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32606360-b84fb248-c55d-11e7-877b-a1ab7c56ee66.gif)

**Comment by Softvision-CristinaBadescu** [comment]
A similar behavior can be observed when you have at least 8 assigned websites and you remove one. Extra artifacts vertical and horizontal artifacts are displayed in the panel.
![remove artefacts](https://user-images.githubusercontent.com/31244235/32734771-9f2ddad8-c89b-11e7-8494-408943a9a42e.gif)

**Comment by dnahol** [comment]
Is this still an issue? I tried replicating it and I see that there is no longer a section in the "Edit container" panel for "Sites assigned to this container"

Is this panel still present in the Windows version? Can someone using Windows confirm or deny this?

Here is what I see on
Mac OS High Sierra, version 10.13.6
Firefox Quantum, version 69.0.3 (64-bit)

<img width="393" alt="Screen Shot 2019-10-21 at 11 48 28 AM" src="https://user-images.githubusercontent.com/2976514/67233953-0652b280-f3f9-11e9-87de-c90b11046711.png">

**Comment by dannycolin** [comment]
Closing since the UI has completely changed in newer versions.
