### ISSUE TITLE
Keyboard Shortcuts within Popup Menu

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/multi-account-containers#941]
When a user hits "ctrl+." to open the containers popup menu, they should be able to easily use more hot keys to open the container they want.

1) The down arrow should take you directly to your first Container.  (right now you have to press tab first and then can use the arrows.)

2) Starting to type a Containers name should take you to the first match in the list with that name.  For example, if I have Personal 1 and Personal 2 in my Containers list (in that order).  And I start typing "Pers", I should end up on the Personal 1 item.  Clicking Enter should open a tab in the Personal 1 Container.

**Comment by groovecoder** [comment]
1. Requires https://bugzilla.mozilla.org/show_bug.cgi?id=1324255

2. will need about a week of work (and I'm not sure when I can get a free week to do it)

**Comment by groovecoder** [comment]
https://github.com/mozilla/multi-account-containers/pull/992 addresses some of this.

**Comment by jjdelc** [comment]
Some sort of autocomplete would be great, but something as simple as using the old windows menu & to select a hot key per container name would do. I could name a container "&Facebook" and typing F would trigger it. It ends up being up to me what to pick as that underlined letter.

In the case of many containers, I could see some sort of filter as you type thing to narrow down selection, but it's more keystrokes.

**Comment by HagarMostafa** [comment]
Hello @groovecoder, @maxxcrawford , I would like to work on this issue, can you please assign it to me?

**Comment by grahamperrin** [comment]
> down arrow should take you directly to your first Container. 

Down <kbd>⬇</kbd> selects the uppermost menu item, then progresses down to the uppermost container. 

Fixed?

**Comment by dannycolin** [comment]
> The down arrow should take you directly to your first Container. (right now you have to press tab first and then can use the arrows.)

Arrows work for me as soon as the popup panel is opened in the latest version. On an accessibility point of view, it doesn't and shouldn't skip the menu item to go directly to the container list. So we can consider 1 as fixed.

> Starting to type a Containers name should take you to the first match in the list with that name. For example, if I have Personal 1 and Personal 2 in my Containers list (in that order). And I start typing "Pers", I should end up on the Personal 1 item. Clicking Enter should open a tab in the Personal 1 Container.

This is going to be fixed by #2501. You would be able to press "/" to focus the new filter box.
