### ISSUE TITLE
 Multi Account Container Add-on Closing all tabs in the group

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [mozilla/multi-account-containers#944]
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID: 20171102181127

Steps to reproduce:

Not Sure this is a bug or a feature , but I've installed Multi Account Container add-on with FF 57 beta on Linux  4.9.51-1-MANJARO  x86_64 GNU/Linux. 

When I' open "Personal" container and duplicate the tab using duplicate tab option or click a link with open new tab option where I can work on multiple tab as usual

Actual results:

When I close one tab from those tabs , all other tabs closing too,  
( note : not all the "personal" tabs , but tabs that open through another tab ) 

Expected results:

I'm closing one tab and that's what I all want , closing all tabs is a not a feature look-like to me.

**Comment by nyordanov** [comment]
I came to report the same issue after upgrading to Firefox 57. I also tried 58 beta 4 (from https://launchpad.net/~mozillateam/+archive/ubuntu/firefox-next) and it is broken there as well.

I use Multi Account Containers 4.1.0.

**Comment by jonathanKingston** [comment]
Is this still happening? I think this was a known migration that we did.

**Comment by kendallcorner** [comment]
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.
