### ISSUE TITLE
Container names are wrongly displayed in the panel when there are more than two consecutive spaces in them

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/multi-account-containers#946]
[Affected versions]:
- Firefox 56.0.2 and up
- Multi-Account Containers v4.0.3

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a clean Firefox profile with the Multi-Account Containers v4.0.3 installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the addon button from the browser toolbar and choose "+" (Create new container) button.
3. Name the container and include at least two consecutive spaces.
4. Observe how container's name is displayed.

[Expected result]:
- All spaces are displayed in the container's name.

[Actual result]:
- Only one space is displayed.

[Notes]:
- Spaces are correctly shown in the address bar and in the long press menu.
- This issue is also reproducible in "about:preferences#containers" page.
- Here is a screen recording of the issue:
![blank spaces](https://user-images.githubusercontent.com/31244235/32658808-767b443c-c624-11e7-803d-ebaaca70a8a4.gif)

**Comment by dannycolin** [comment]
Closing since it has been fixed upstream.
