### ISSUE TITLE
Extra scrollbars are wrongly displayed while editing a container if it has more than 9 websites assigned

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/multi-account-containers#948]
[Affected versions]:
- Firefox 56.0.2 and up
- Multi-Account Containers v4.0.3

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the Multi-Account Containers v4.0.3 installed.
- Have one container populated with minimum 10 assigned websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the addon button from the browser toolbar and choose the "Edit container" button.
3. Click on the container's pencil icon and scroll all the way down.
4. Observe the assignments panel.

[Expected result]:
- One vertical scrollbar is displayed in the panel.

[Actual result]:
- An additional horizontal scrollbar is displayed.

[Notes]:
- If the horizontal scrollbar is moved to the right, an extra vertical scrollbar appears.
- This issue is not reproducible if you have under 9 assigned websites to a container, see below a screenshot:
![9 websites assigned](https://user-images.githubusercontent.com/31244235/32669121-275365f0-c648-11e7-89ab-b29245cdd7b4.png)

- Here is a screen recording of the issue:
![scrollbar](https://user-images.githubusercontent.com/31244235/32669244-7fec1964-c648-11e7-9b82-0406c882b598.gif)
![scrollbar](https://user-images.githubusercontent.com/31244235/32669252-869df0ca-c648-11e7-839d-fc616e6f7046.png)
- This issue is not reproducible on Mac, nor on Linux.

**Comment by groovecoder** [comment]
The fix probably involves scrollable class.

**Comment by Paarmita** [comment]
@groovecoder Can I take up this issue?

**Comment by groovecoder** [comment]
Yes, this is another good first bug.

**Comment by Paarmita** [comment]
@groovecoder Thanks! I will soon add a PR.

**Comment by groovecoder** [comment]
This was fixed in https://github.com/mozilla/multi-account-containers/pull/1476
