### ISSUE TITLE
Undo close tab after contained tab, "duplicates" the tab

### ISSUE THREAD

**Issue by yosubis** [mozilla/multi-account-containers#950]
If I open a "sleeping" tab (from previous session) that is in a container and then undo close tab shortcut (ctrl+shift+T), a duplicate of this contained tab it opened. If I continue undo close tab, the same tab is duplicated again.

**Comment by SoftVision-EmilPasca** [comment]
I have managed to reproduce the issue on Windows 10 x64 and Mac 10.12 with the latest Firefox release (56.0.2) and the latest Nightly (59.0a1-20171113100232) using the latest Multi-Account Containers (4.0.3).

Attached a screen recording of the issue:
![containers_duplicate_tab](https://user-images.githubusercontent.com/20083658/32728577-814c26e4-c889-11e7-94e6-f2cf41138238.gif)

**Comment by kris7453** [comment]
Same problem. Now i have duplicated tabs in container and I can't show hidden duplicated tabs nor show visible tabs. When I have separated showed tabs by another container group, then when I click show, all duplicated tabs will open and when i close browser and open again then i have tripled tabs.
The problem appear  for newest firefox quantum 57.0(64bit)
![image](https://user-images.githubusercontent.com/20442936/32858268-4b024f6e-ca4b-11e7-8cd5-283a6df6a509.png)

**Comment by TanviHacks** [comment]
Is wikipedia assigned to a container?

**Comment by oksmelnik** [comment]
I'd like to work on this issue (outreachy applicant)

**Comment by oksmelnik** [comment]
the problem is that opening recently closed container's tab triggers unhiding of all the other tabs of this container, including this particular tab again. Is containers tabs re-opening suppose to happen in this case, @groovecoder? If so, I'll try to find the way to not duplicate the tab.

**Comment by oksmelnik** [comment]
please, check my PR here 
https://github.com/mozilla/multi-account-containers/pull/1540

**Comment by groovecoder** [comment]
Fixed in #1540
