### ISSUE TITLE
Hide and group containers 

### ISSUE THREAD

**Issue by vlldk** [mozilla/multi-account-containers#957]
Would be nice to have options like Tab Group to hide specific groups. For instance, I want to show tabs related to my school container and hide regular containers. I've read the API was approved to hide tabs, so it should be doable?

**Comment by totokaka** [comment]
It is already possible to hide containers. Just click the container button, click the little arrow next to a container, and choose "Hide this container"

**Comment by vlldk** [comment]
I see - but why does it load all the tabs when showing the container?

**Comment by totokaka** [comment]
That I do not know the answer to...
It should probably be opened as a separete issue, and maybe this can be closed?
