### ISSUE TITLE
Feature Request: Add ability to open urls and their query parameters in specific containers

### ISSUE THREAD

**Issue by thisisshi** [mozilla/multi-account-containers#959]
Example:
www.example.com/login?account-type=development would open in "Development" container
www.example.com/login?account-type=qa would open in "QA" container

Currently opening www.example.com for either of the urls will open in the same container.

**Comment by jtzero** [comment]
would this be related? https://github.com/mozilla/multi-account-containers/issues/426

**Comment by jtzero** [comment]
I think this is related https://github.com/mozilla/multi-account-containers/issues/426

**Comment by groovecoder** [comment]
Dupe of https://github.com/mozilla/multi-account-containers/issues/691
