### ISSUE TITLE
After uninstalling addon Firefox loose containers

### ISSUE THREAD

**Issue by Dimas-sc** [mozilla/multi-account-containers#960]
I had Firefox 57b with the builtin containers features (long click new tab to create containers, custom containers, etc...).

What I've done?
I tried installing this addon > not interested > uninstalled

Result?
I don't have containers anymore! The options pref was disabled, but enabling it doesn't make long click to new tab button work again :-(

**Comment by Softvision-MariusComan** [comment]
@Dimas-sc, after you uninstalled the add-on, the "userContext" prefs were changed back to their default values. If you want to activate again the containers, please make sure that you have the following prefs in the "about:config" page:
	1) privacy.userContext.enabled - true
	2) privacy.userContext.longPressBehavior - 2
	3) privacy.userContext.ui.enabled - true
	4) privacy.usercontext.about_newtab_segregation.enabled - true

**Comment by Dimas-sc** [comment]
Thx @Softvision-MariusComan it worked. I suppose it's difficult for the addon to maintain the old user settings, isn't it?

I thought the containers was enabled by default, I don't remember to change this prefs manually. Maybe older settings set by testpilot experiment.

**Comment by Softvision-MariusComan** [comment]
Containers are enabled by default only on Nightly, on release and beta channels the "userContext" prefs are on false.
