### ISSUE TITLE
The userContext prefs are wrongly changed, after the "Multi-Account Containers" add-on is uninstalled

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/multi-account-containers#961]
**[Affected versions]:**
- Nightly channel

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" (1.9.0dev custom build from 11.14.2017) and with the latest "Multi-Account Containers" add-ons installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and go to the "about:addons" page.
2. Remove the "Multi-Account Containers" and refresh the page.
3. Go to the "about:config" page and observe the "userContext" prefs values.

**[Expected result]:**
- The "userContext" prefs are:
	1) privacy.userContext.enabled - true
	2) privacy.userContext.longPressBehavior - 2
	3) privacy.userContext.ui.enabled - true
	4) privacy.usercontext.about_newtab_segregation.enabled - true

**[Actual result]:**
- The "userContext" prefs are:
	1) privacy.userContext.enabled - false
	2) privacy.userContext.longPressBehavior - 0
	3) privacy.userContext.ui.enabled - true
	4) privacy.usercontext.about_newtab_segregation.enabled - false

**[Notes]:**
- The issue not reproducible on release and beta channels.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32779334-03f8efe8-c946-11e7-903a-a54ba6b03da0.gif)

**Comment by groovecoder** [comment]
Is this still reproducible? It may have been a WebExtensions Nightly bug that has since been fixed.

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest Nightly (59.0a1) build, with the latest version of the "Multi-Account Containers" (5.0.1) add-on installed.
