### ISSUE TITLE
The wrong icon is displayed for certain "about: *" pages, in the "Multi-Account Containers" panel

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/multi-account-containers#963]
**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version (4.0.3 custom built on 11.14.2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to the "about:addons" page. 
2. Click the "Multi-Account Containers" button from the browser toolbar and observe the displayed icon.

**[Expected result]:**
- The favicon of the "about:addons" page is displayed.

**[Actual result]:**
    1) On Windows the local drive icon, where windows is installed, is displayed.
	2) On Mac and Linux the system "file" icon is displayed.

**[Notes]:**
- The favicon of the "about:preferences" and "about:newtab" pages is correctly displayed in the "Multi-Account Containers" panel.
- The issue is also reproducible on the "about:config", "about:memory" and "about:crashes" pages.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32788029-c9a0b446-c960-11e7-8158-6593d8f1280e.gif)

**Comment by jonathanKingston** [comment]
This icon is when the default won't load. This is either a native bug or not fixable. Windows unknown icon is super odd too.

Won't fixing this, however I was aware of it. Perhaps it's better in central. We load the "goat" icon when the default is prevented from loading / one doesn't exist.
