### ISSUE TITLE
Firefox Quantum support?

### ISSUE THREAD

**Issue by pfremm** [mozilla/multi-account-containers#967]
Does this support the newest version of firefox quantum?  I cannot seem to install the extension.

**Comment by groovecoder** [comment]
It should, are you installing straight from https://addons.mozilla.org/firefox/addon/multi-account-containers/?

**Comment by ghostsquad** [comment]
I have it on Quantum, it seems to work just fine.

**Comment by cole-h** [comment]
Do you have `privacy.resistFingerprinting` set to true in your about:config?

**Comment by pfremm** [comment]
I changed the setting but it seems to think I have version 52 even though I have 57 installed.

**Comment by cole-h** [comment]
@pfremm It should be set to false. Setting that to true falsifies your user agent string to that of FF52. Changing it back to `false` should fix your issue.

**Comment by ArchangeGabriel** [comment]
But that is an ugly workaround. You’re saying: if you care about privacy (that’s what this addon is about), you should disable this very important privacy feature (that’s what this pref is about)…

**Comment by groovecoder** [comment]
Unfortunately that's the case until 59 becomes ESR 😞 Then `resistFingerprinting` will set user agent to 59. This add-on is primarily meant to separate and manage online accounts, which also helps to separate the tracking of those accounts. But it does require APIs from 57+ 😞

**Comment by cole-h** [comment]
@ArchangeGabriel The _add-on_ doesn't rely on the UA, _AMO_ does. There's nothing stopping you from installing the extension directly from GitHub or the "install anyway" button on AMO (to get to that now I believe you need to click the "view other versions" or similar near the bottom of the AMO page). Should then download the add-on and, if compatible, prompt you to install. That way you don't need to toggle the resist fingerprinting setting.

**Comment by ArchangeGabriel** [comment]
Oh, I didn’t realized the issue was trying to install from AMO being blocked by AMO, I thought that was the addon refusing to install itself. Silly me.

**Comment by groovecoder** [comment]
Closing because no updates since Nov 18.
