### ISSUE TITLE
Hello, can i ask for some features

### ISSUE THREAD

**Issue by navmesh** [mozilla/multi-account-containers#968]
Hello, thank you very much for the awesome add on, i used "cookie swap" add on before  https://addons.mozilla.org/en-US/firefox/addon/cookieswap/ but now it is not compatible with firefox ,and your add ons help me so much
by the way ,may i ask for some features 

1.Typing the first character to switch to the profile we want

the "cookieswap" addon i said above has a feature : you can switch profile by typing the first letter of the profile name, for example,i have profile name "steve" and when i type "s" when clicking on the switch profile button, it switch me to the first profile beginning with "s"
i made it more convenienty by naming the profile beginning with japanese/chinese characters (because it has many characters, for example i name the profile "steve" to  "七-steve" and when i type "七" , it switch to "steve" ,this is really useful so i use Autohotkey script to read the profile name i want to switch and type the corresponding character ,then it will switch to that profile
for example i want to switch to "七-001" profile , i input the "001" in the script and my autohotkey script will typing the "七" character, then it would switch to  "七-001" profile 
2. easily manage your profile
also with cookie swap,in firefox profile directory there is folder name "CookieSwap" ,it contains the txt files to store your cookie profile (one txt file for one profile), the txt file has the same name with the profile you create, so you can easily  create / edit ,copy cookie profile easily by copying the txt file 
and the currently using profile has  ".tx1" extension instead of txt like the other profiles
for scripting user, we can tell the script to know which profile is currently using by finding the file has "tx1" extension
can you make the similar function for this add on 

Thank you very much

**Comment by aplaice** [comment]
(Not affiliated with the extension etc.)

1. There's an addon which does almost what you want:

https://github.com/andreicristianpetcu/Search-and-Switch-Containers

You need to type `co start_of_name_of_container`, rather than just `start_of_name_of_container`, but otherwise it's very similar.

**Comment by groovecoder** [comment]
I believe there are existing add-ons or at least other issues similar to these feature requests already. Please check the issue list and upvote the issues that capture your requests:

https://github.com/mozilla/multi-account-containers/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
