### ISSUE TITLE
Refactor to async arrow functions

### ISSUE THREAD

**Issue by groovecoder** [mozilla/multi-account-containers#972]
See https://github.com/mozilla/multi-account-containers/pull/921#issuecomment-341670787 for details.

**Comment by Soundharyaam** [comment]
Hi, Can I work on this bug?

**Comment by groovecoder** [comment]
Yup.

**Comment by Soundharyaam** [comment]
Thanks!

**Comment by Soundharyaam** [comment]
PR: #1263

**Comment by Soundharyaam** [comment]
@armenzg I have made the PR. Could you please review this?

**Comment by Soundharyaam** [comment]
@groovecoder  I have made the PR. Could you please provide your review on this?

**Comment by groovecoder** [comment]
See https://github.com/mozilla/multi-account-containers/pull/1263#issuecomment-423744345. This is a big refactor - not just throwing `async` onto a single function.

**Comment by Paarmita** [comment]
@groovecoder So we need to assign arrow functions to all async functions in the code base?
And Can I work on this?

**Comment by groovecoder** [comment]
@Paarmita yes - we can clean up some code (i.e., make it less verbose) by using `async (...) => { ... }` in many places.

**Comment by jonathanKingston** [comment]
My intent on the previous bug was only to use `async () => {}` when it's something that is already inline, not changing named methods to be const async arrows.

This is less about changing just the code style in a blanket fashion and instead moving functions to be inlined whenever they are only used once.

The work might actually be check and see if there is any clean up that makes the code less verbose using async arrows. The answer might be it only makes it more verbose. IMO the latest PR makes it more verbose and less idiomatic.

When I suggested the use of these I believe we had small one line functions that are used only once.
```
async a(b) {
  await doThing();
},
async click() {
  for b in x {
    callback(await a(b));
  }
}
```

Which could be changed to something along the lines of:
```
async click() {
  for b in x {
    callback(await a(b) {
      await doThing();
    });
  }
}
```

**Comment by Paarmita** [comment]
@jonathanKingston I changed the async function to arrow functions which makes it more verbose, I can work on the suggested lines as well. Do I need to change arrow functions for which I opened the PR?

**Comment by ctgardner** [comment]
I understand the crux of this issue isn't to simply replace functions declared using the `function` keyword with arrow-functions, but to inline named async functions where sensible. I've reviewed all named async functions and I believe none would benefit from being inline, with the exception of a few handlers registered using `addListener`. Given the past confusion surrounding this issue, I believe this issue should be closed.
