### ISSUE TITLE
Broken container editing 

### ISSUE THREAD

**Issue by gbp** [mozilla/multi-account-containers#977]
If a site requires HTTP authentication and is set to "always open in" a container then its impossible to edit the container as the HTTP authentication prompt is displayed dismissing the multi-account containers popup.

**Comment by groovecoder** [comment]
You should be able to edit the Container in the pop-up.

You should also be able to edit the site assignments of the Container in the pop-up.

Can you provide more specific steps to reproduce?

**Comment by grahamperrin** [comment]
With Firefox 88, [Always In Container](https://addons.mozilla.org/addon/always-in-container/) seems to work around this issue. 

**Without** the additional extension, using the toolbar icon for Multi-Account Containers seems to produce a new tab: 

* with the required container
* without the corresponding URL.

**Comment by gbp** [comment]
Sorry for not providing enough details... the issue was when opening the pop-up, it would try and load something from the domain covered by the HTTP auth - I assume the favicon - and then authenication prompt would open which closed the Multi-Account Containers pop-up.

Anyway I can't reproduce anymore (without the additional extension meantioned above) so closing as fixed.

**Comment by grahamperrin** [comment]
Thanks for closing! 

I _do_ find some peculiarity, maybe it's platform-specific. I'll continue under #876
