### ISSUE TITLE
Reorganize actions between menus

### ISSUE THREAD

**Issue by Madis0** [mozilla/multi-account-containers#983]
I think the Containers menus are not very organized, not all actions are located where they make sense.

Here is the current state - X referring to Container's name:

**Toolbar button**

- Always open in X
- Sort tabs
- Create a X tab
- Container management
1. Hide this container
2. Move tabs to a new window
3. Switch to tab(s)
- Edit containers
- Create a container

**Page right-click**

- Always open in this container
- Hide tabs in this container
- Move tabs to a new window

**PageAction**

- _(nothing)_

**Hold new tab button**

- Create a X tab
- Manage Containers

And this is how I think it would make sense:

**Toolbar button**

- Sort tabs
- Create a X tab
- Container management
1. Hide this container
2. Move tabs to a new window
3. Switch to tab(s)
- Edit containers
- Create a container

**Page right-click**

- _(nothing)_

**PageAction**

- Always open in this container

**Tab right click**

- Sort tabs
- Hide X tabs
- Move X tabs to a new window

**Hold new tab button**

- Create a X tab
- Manage Containers

---

Summary of changes:

1. "Always open in this tab" removed from the toolbar button, along with the section of page title, icon, "Current tab"
2. PageAction is made clickable, and it shows the section described in change 1
3. In-page right click menu is removed, as it seems irrelevant
4. Tab right-click menu added, with options that manage tabs by current Container, along with general sort option
5. _(New tab hold menu unchanged)_

**Comment by dannycolin** [comment]
Closing. The menus have changed a lot since this issue was open. If there's changes to be made to the new menus order, it'll be best to open a new issue.
