### ISSUE TITLE
Letters/symbols/emoji as icons

### ISSUE THREAD

**Issue by Madis0** [mozilla/multi-account-containers#984]
In my opinion, the available icons and colors are very limited. The colors are being considered in #391, but the problem with icons is much harder to solve:

- Ask for more icons - takes time to do and the result may still be too few icons to satisfy users
- Let users choose an image file - a hard and messy option, would make compatible extensions complex too

So I was thinking - why not just use characters? There are many advantages: 

- Could be as simple as **F** for Facebook and **G** for Google
- Could use emojis to create thousands of color-character combinations (or show the platform-specific SVG and extract it's color)
- Could just use a period, underscore, space etc. to keep it minimalistic and solve #771 
- Could even remove the built-in icons and simply suggest some well-visible emojis to replace them
- Advanced users might not even need titles to know which icon represents which Container, especially Chinese 😁 

What do you think?

**Comment by yashha** [comment]
Maybe add brand icons like fb and twitter, I have each in a different container
https://github.com/simple-icons/simple-icons

**Comment by grahamperrin** [comment]
I manually edited my `containers.json` file, 

```json
{"version":2,"lastUserContextId":31,"identities":[{"userContextId":5,"public":false,"icon":"","color":"","name":"userContextIdInternal.thumbnail","accessKey":""},{"userContextId":19,"public":true,"icon":"","color":"","name":"📱"},{"userContextId":31,"public":true,"icon":"","color":"","name":"🍋"}]}
```

**Comment by jonathanKingston** [comment]
> I manually edited my containers.json file,

This is a bad idea, the APIs from memory don't handle this well.

**Comment by grahamperrin** [comment]
> … a bad idea, … 

Yeah, sorry. I forgot to add that I restart Firefox after edition, and so on …

**Comment by groovecoder** [comment]
This would need a platform-level patch; would need to file a bug in bugzilla.

**Comment by Madis0** [comment]
Forgot to make a BugZilla bug, but now [here it is!](https://bugzilla.mozilla.org/show_bug.cgi?id=1454188)
