### ISSUE TITLE
Allow default container setting to differentiate between ports

### ISSUE THREAD

**Issue by Alarm-Siren** [mozilla/multi-account-containers#985]
Basically, my email service and something I use for my job run on the same physical server, but at different port addresses. I am unable, as it stands, to get it to use different default containers for these different services.

e.g. 
example.org:2096 -> email -> Personal Container
example.org:2083 -> work site -> Work Container

I can do it using subdomains, but if I do this I lose SSL/TLS, and this is not something I can work around. As you can imagine I'd rather have TLS than Default Containers, but ideally I'd like both.

**Comment by TanviHacks** [comment]
This bug should be just for non-standard ports.  If http://example.org:80 is assigned to Work, then https://example.org:443 should also be assigned to work.

**Comment by Paarmita** [comment]
@TanviHacks @jonathanKingston @groovecoder Can I take up this issue as my first issue for outreachy?

**Comment by groovecoder** [comment]
You can try this one, yes. This may be difficult to test thoroughly - we will need to make sure whatever assignment changes we make to support port-specific assignments don't destroy existing assignments without ports.

**Comment by Paarmita** [comment]
@groovecoder Can u plz help me in finding the right file to make changes as I'm new to extensions?
