### ISSUE TITLE
Switch current container instead of opening a new tab

### ISSUE THREAD

**Issue by AdrienPoupa** [mozilla/multi-account-containers#987]
Context: I have created a container for Google (_Go_), and another one from Github (_Gi_). I have enabled the "Always open in Go" for Google and "Always open in Gi" for Github. I have checked "Remember my decision for this site" when asked Open this site in your assigned container?

Currently, while in the _Go_ container, for example viewing Google search results, clicking on a Github link will open a new tab having the _Gi_ container. If I was not using containers, I would just keep my actual tab.

Is there a way to keep using the same tab while switching containers? It would switch from the _Go_ container to the _Gi_ one seamlessly.

Another issue: if I'm in the _Gi_ container and I start a new search, Firefox will open a new _Go_ container while leaving the _Gi_ one open.

This issue seems to be related to https://github.com/mozilla/multi-account-containers/issues/923 but I'm not sure it is the same.

![video_2017-11-19_182346](https://user-images.githubusercontent.com/15086425/32996904-14c8575e-cd57-11e7-9cfa-43e8e20292c2.gif)

**Comment by I-am-me** [comment]
It's the same issue as #923 but your's explain it better (the gif is a nice addition)

**Comment by AdrienPoupa** [comment]
Thanks @I-am-me. I wasn't sure it was exactly the same issue.

**Comment by groovecoder** [comment]
Just released 5.0.1 which should fix this.

**Comment by AdrienPoupa** [comment]
I still have the same problem.
