### ISSUE TITLE
"Always open in" is always disabled

### ISSUE THREAD

**Issue by keyvanakbary** [mozilla/multi-account-containers#988]
The "Always open in [container]" checkbox always appear to be disabled. I could only changed it once, the first time I installed the add-on. Uninstalling and installing the add-on again does not change it. I might be missing something but I does look like a bug.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/717129/32996780-d083b24c-cd87-11e7-9db3-e0b581e9be6d.png">

My version is **Firefox Quantum v57 64b**

**Comment by AdrienPoupa** [comment]
![2017-11-19_181742](https://user-images.githubusercontent.com/15086425/32996817-fa8041aa-cd55-11e7-9ab3-224c4d0070df.png)
Weird, it seems to be working for me.

**Comment by keyvanakbary** [comment]
@AdrienPoupa same version?

**Comment by AdrienPoupa** [comment]
Yes

**Comment by Softvision-MariusComan** [comment]
@keyvanakbary, from your screenshot I've observed that you tried to assign a website to a regular tab (the "Default" container), however that action is not supported in the "Multi-Account Containers" feature and the "Always open in" option will be greyed out.
Also, for @AdrienPoupa, the issue is not reproducible because he assigned the website to a custom container (dev).

**Comment by keyvanakbary** [comment]
Oh, now I understand how the thing works. I thought this thing was for classifying sites into different containers, from the current page. Basically, going to a site and then click on "Always open in" and select a container to classify.

I didn't realise that I have to open a new tab with the desired container, go to the specific site and then classify it.

I'm not sure if people are already used to that behaviour but it does not seem very friendly. Coming from Chrome it was a bit confusing. Now I got what I wanted, thanks for the help!

<img width="293" alt="image" src="https://user-images.githubusercontent.com/717129/33047413-d962f548-ce55-11e7-94f4-142066ef3d11.png">

**Comment by trollepierre** [comment]
Hi guys,I would like to reopen this issue, because it doesn't work for me now
Version 65.0.2
<img width="315" alt="Capture d’écran 2019-03-18 à 19 13 18" src="https://user-images.githubusercontent.com/8363334/54553269-1cefe180-49b2-11e9-9997-b1b174288e66.png">
