### ISSUE TITLE
Feature Request: default URL when opening a container

### ISSUE THREAD

**Issue by lrgn** [mozilla/multi-account-containers#991]
Dear Mozilla team,

First, thank you for providing us this amazing add-on. I started using it after the Firefox 57 migration to replace [Priv8](https://addons.mozilla.org/en-US/firefox/addon/priv8/), which was not updated for WebExtensions, and it's doing a great job. However, one of the feature of Priv8 I am missing is the possibility to have a default URL which will be opened when opening a container.

Would it be possible to add this feature to the multi-acount containers extensions ?

Thanks & Best Regards,
LRGN

**Comment by QuincyLarson** [comment]
I use Chrome's "people" and have it automatically open several relevant tabs for a person whenever I switch to it. It would be nice if Firefox could do this, too. 

Otherwise, I would need to navigate to several different URLs whenever I switch containers.

**Comment by jonathanKingston** [comment]
Hey thanks for the bug, I think this is a duplicate of: #375 let me know if it isn't.

**Comment by lrgn** [comment]
My bad, I searched for another issue requesting the same feature, but probably missed that one.
