### ISSUE TITLE
Feature Request : Ignore saved url to certain container, when opening the url from some other specific container

### ISSUE THREAD

**Issue by yofiesetiawan** [mozilla/multi-account-containers#993]
This is a very useful addons. However i have a UX suggestion for this addon. I believe this is really important. So when i already save a link to be open (always) with certain container, right now, it always happen whether i open that link either from a default or other containers. So when i open certain container tab, and open a link, it always redirect to the container i saved before. My suggestion is, can we make it only redirected if we open from default container? I mean when i open an url with some specific container, i am well aware that i want to open that link from that container, not redirected... I hope my explaination make sense...

So in my case, for example, i make Facebook to be open always from my Personal container. Because i regularly open Facebook many times. But i want to help manage my mom's Facebook account. So i create a new Container called "My Mom", so that i can open my Mom's facebook from that specific "My Mom" Container. Right now, everytime i open facebook from "My Mom" container, i always redirected to my Personal container. That's why, i think it's important to not redirect us to saved container, whenever we open a link already from specific container. This makes much more sense for me....

**Comment by groovecoder** [comment]
It sounds like you should un-check the "Remember my choice" option for always opening Facebook in your Personal container. You can re-assign it again, but leave the "Remember" option un-checked. Then you'll be able to choose to open Facebook in the default or other container.
