### ISSUE TITLE
Please consider removing share feature

### ISSUE THREAD

**Issue by samlh** [mozilla/multi-account-containers#994]
Please consider disabling the sharing prompt (on 100 tabs opened). I consider that sort of self-promotion prompt to be annoying, and I want to discourage any future features in the same vein (in this or any extension). It is true that such prompts increase the number of ratings submitted, which makes it tempting. My concern is that if all extensions did it, then using as many extensions as I wished would end up being super annoying. That a Mozilla extension does it, encourages other extensions to game the system as well.

**Comment by groovecoder** [comment]
Appreciate the concern, which we've addressed:

* We only display the prompt after 100 container tabs opened, so it only appears to active/heavy users
* We never display the prompt again after the user clicks "Done" - regardless of whether or not they performed any of the sharing/rating actions

User will ultimately decide to keep extensions that do this appropriately, and uninstall extensions that abuse their experience.

**Comment by rrix** [comment]
Can there at least be a way to disable icon badging? There's nothing "NEW" in the addon except for it asking its users to market the addon. I don't care if it's in `about:config` or something, just somewhere that my site policy that I ship to my machines can disable it going forward.

Considering the fact that this was added without any discussion on whether it's the "right" thing to do, I worry that more "achievements" like this will be added in the future.

I don't particularly care if the feature is there, but seeing it across every installation of Firefox that I use is jarring and frustrating.

I'd also note that this breaks the "keyboard shortcuts" listed in the readme, which 100 tabs in across four different browser installations is entirely muscle memory which was disrupted (granted, only once, but is that the sort of user experience that every "heavy user" of this addon should have to face?

**Comment by kinderbueno25** [comment]
Hi. I know it's been a while and the issue is closed but is there any chance you add a parameter to disable the feature or even configure the number of tabs ?

**Comment by jx** [comment]
Please please please let folks turn this off. Firefox is a web browser, not a game console and we don't need little achievement banners in it. When I saw this it's such a turn off I almost want to fork it just to remove that. "If you love us tell lots of people" nags in apps are incredibly annoying to USERS even though marketing loves them. Please don't listen to the marketing people.

**Comment by unikitty37** [comment]
This extension is not just a social media toy. It's also for people using their browser to do serious work.

This nag, and the app badging, **has no place here. It is completely inappropriate to take people out of their workflow just to try and get them to do free promotional work for you.**

The only thing messages like this make me likely to share is "don't use this extension, it's nagware".
