### ISSUE TITLE
Containers working only partially Ubuntu MATE 16.04 / Quantum

### ISSUE THREAD

**Issue by taikedz** [mozilla/multi-account-containers#998]
Hello,

Since updating to Quantum, I have lost some parts of containers' functionality

* I have installed from the latest github release 4.1.0
* Firefox updated form the Ubuntu repositories
* Desktop is Ubuntu MATE
* x86_64
* quit and re-started browser after installing

Issues:

* Menu in menu bar (using the icon, next to the Settings menu) is tempy - a slim, horizontal white bar indicating the top of the menu, but no content
* No prompt to "open in preferred container" on sites previously registered as opening in those containers
* *can still* (OK) use containers explicitly via the `File` menu, and the containment does indeed happen

**Comment by groovecoder** [comment]
How did you install the add-on? It sounds like you installed a temporary add-on.

**Comment by taikedz** [comment]
Originally installed via Test Pilot ; I only noticed it not working after both the Experiment was over, and after the update to Quantum.

Before posting the Issue, i did try to remove Containers, and reinstall from the latest Release on this GitHub repo, but this did not change the situation.

Is there a way of purging the Containers info after uninstalling it, so I can try to "freshly" install it again ?

**Comment by SoftVision-PaulOiegas** [comment]
Hi @taikedz, have you tried installing it from [Mozilla Add-ons website](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)? Try that please and let me know of the results. We'll debug more if this does not fixes your issue.

**Comment by groovecoder** [comment]
When you un-install the Test Pilot add-on, it should remove the Test Pilot info. If you install the add-on from AMO, it should "upgrade" the add-on in its place.

**Comment by taikedz** [comment]
I removed the add-on via the Add-ons prefs page, closed firefox

Opened ffox, added the add on from the MAO (link you posted above), and closed ffox for good measure

Opend ffox again, but still the same issue persists

![](https://pasteboard.co/GZ6S5O5.png)

**Comment by taikedz** [comment]
Anything else I can do/provide to troubleshoot ?

**Comment by taikedz** [comment]
In the end I had to entirely purge the containers plugin data - simple "remove" the add-on was not sufficient

In `~/.mozilla/<profile>` I looked for any folders and files related to containers, and removed them ; after re-installing the plug in from the Firefox add-ons site, they work again, albeit with none of the previous preferences remembered of course.

Evidently a case of bad data, stemming from where I know not.
